### ISSUE TITLE
Start Page

### ISSUE THREAD

**Issue by edoardocavazza** [RocketChat/Rocket.Chat.Electron#1]
Hi there,

with the current project configuration, the Rocket.Chat app starts at the url [https://rocket.chat/home](https://rocket.chat/home), so there is not way to set another host url.

I propose:
My [ ] a local start page
- [x] this start page should look if an host url has already been provided and do a redirect
- [x] otherwise, it should show an input field for host url
- [x] if on start, the internet connection is unavailable and appcache is empty, the app should warn the user (right now, the app shows a blank screen)

**Comment by engelgabriel** [comment]
Agreed.

**Comment by edoardocavazza** [comment]
I am working on it

**Comment by edoardocavazza** [comment]
In order to enable the start page, un comment `var INDEX = 'file://' + path.join( __dirname, 'app.html' );` in `app/main.js`

**Comment by edoardocavazza** [comment]
Other acceptance criteria:
- [ ] validate the form and add ux callback

@engelgabriel what is the best way to identify an host as a Rocket.Chat instance?

**Comment by engelgabriel** [comment]
I am not sure.. maybe we have to create one.

**Comment by engelgabriel** [comment]
Probably using the event emitter once loaded, or a custom http header on the initial request

**Comment by rodrigok** [comment]
I prefer the header option

**Comment by engelgabriel** [comment]
@rodrigok can you implement this on the main project and let @edoardocavazza know?
https://github.com/RocketChat/Rocket.Chat/issues/286

**Comment by rodrigok** [comment]
@engelgabriel of course

**Comment by edoardocavazza** [comment]
I am thinking that this start page might be useful also for Cordova applications... if you agree, maybe we should move it to a dedicated repository, and use git subprojects in this one.

**Comment by engelgabriel** [comment]
Definitely... let's get it working first, and see how to do it.

**Comment by rodrigok** [comment]
@edoardocavazza I just added the header to all responses

**Comment by edoardocavazza** [comment]
Thank you @rodrigok !!!

**Comment by edoardocavazza** [comment]
When https://rocket.chat is updated to @rodrigok commit and ApplicationCache is enabled, I think we are ready for some tests.

**Comment by rodrigok** [comment]
@edoardocavazza, https://rocket.chat was updated to latest commit right now.

**Comment by edoardocavazza** [comment]
Thanks @rodrigok , the start page now properly recognize [https://rocket.chat](https://rocket.chat) as a valid Rocket.Chat instance :+1:

**Comment by rodrigok** [comment]
@edoardocavazza Nice :D

**Comment by mitar** [comment]
So how does one configure a custom Rocket.Chat instance?

**Comment by engelgabriel** [comment]
@mitar on the version 0.0.7 there is an option to change/add servers.

They will add icons to the right bar:

![image](https://cloud.githubusercontent.com/assets/1000217/9568133/b3f0ded4-4f17-11e5-8879-3ee6f35daa3b.png)
