### ISSUE TITLE
Microphone not working for the desktop app (ubuntu)

### ISSUE THREAD

**Issue by Bhasha03** [RocketChat/Rocket.Chat.Electron#1002]
## My Setup
- Operating System:
- App Version:
- Installation type: 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

**Comment by Bhasha03** [comment]
whereas for **webapp** its working after giving permissions.

**Comment by uweschaefer** [comment]
same here.

**Comment by tassoevan** [comment]
@uweschaefer Please inform OS version, app version, and installation type.

**Comment by uweschaefer** [comment]
sorry.

os: Ubuntu 18.04
app version: 2.14.5
package: deb x64

browser client works fine.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
