### ISSUE TITLE
Mac desktop client not correctly signed

### ISSUE THREAD

**Issue by rebeld** [RocketChat/Rocket.Chat.Electron#101]
Launching the Mac desktop client (v 1.0.0) results in this error (Mac OS X El Captain):

“Rocket.Chat.app” can’t be opened because it is from an unidentified developer.

Workaround is to ctrl+click and select Open from context menu.

**Comment by pcarn** [comment]
+1. Previous beta worked.

**Comment by rodrigok** [comment]
The binary was updated, it's signed now, thanks.
