### ISSUE TITLE
"Houston, we have a problem" visible when resizing window

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Electron#1014]
## My Setup
- Operating System: macOS
- App Version:2.14.4
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When resizing the chat window, you can see the "Houston, we have a problem" screen.

### Current Behavior
When resizing the chat window, you can see the "Houston, we have a problem" screen.
![something-bad-happened mov](https://user-images.githubusercontent.com/6295044/48973227-fbd14280-f008-11e8-9df7-af398cc04559.gif)

### Expected Behavior
Chat window should resize without jumping.

**Comment by tassoevan** [comment]
Closed by #1684
