### ISSUE TITLE
Help -> Reset App Data not working on Mac 2.14.4

### ISSUE THREAD

**Issue by gigawhitlocks** [RocketChat/Rocket.Chat.Electron#1015]
## My Setup
- Operating System: macOS
- App Version: 2.14.4
- Installation type: dmg

- [ X ] I have tested with the latest version
- [ X ] I can simulate the issue easily

## Description

Help -> Reset App Data does nothing. The client reloads but all settings remain. It should wipe the application cache. It works in 2.14.1 so I think there was a regression when this feature was fixed for Windows in issue #947 

### Current Behavior

Help -> Reset App Data has no effect.

### Expected Behavior

Help -> Reset App Data should clear the application cache and force the user to log back in to his or her server.

**Comment by tassoevan** [comment]
I couldn't reproduce it in 2.14.5.

**Comment by gigawhitlocks** [comment]
I can't reproduce on 2.14.5 either. 🙌
