### ISSUE TITLE
Black screen on Linux

### ISSUE THREAD

**Issue by unixfox** [RocketChat/Rocket.Chat.Electron#102]
Hi !

I'm using Rocket Chat on Linux with Gnome and when I connect to my personnal Rocket Chat, I get a black screen for unknow reason.

![](https://i.unixfox.eu/20-15-15-2016.png)

Here is a video of the problem : https://cloud.unixfox.eu/f/72a32834ac/.

### Informations about my PC
* OS : ArchLinux
* Graphical interface : Gnome Version 3.18.2
* Installed from AUR : https://aur.archlinux.org/packages/rocketchat-client

**Comment by rodrigok** [comment]
Can you download the latest version from our [releases page](https://github.com/RocketChat/Rocket.Chat.Electron/releases) and try again?

**Comment by rodrigok** [comment]
Your linux is x64 or x32?

**Comment by unixfox** [comment]
My Linux is x64 and I'm using the latest version from https://aur.archlinux.org/packages/rocketchat-client/. Look at the sources, it's the same link as releases page.

**Comment by gromain** [comment]
I do have the exact same problem, also on ArchLinux (well, on manjaro, a derivative), using the same package from AUR (which is the official release from GitHub too).
However, I'm using Cinnamon as the desktop environment.

**Comment by rodrigok** [comment]
Can you clone the repo and run the application as development mode?

```shell
git clone git@github.com:RocketChat/Rocket.Chat.Electron.git
cd Rocket.Chat.Electron
npm install
npm start
```

**Comment by unixfox** [comment]
Same error on branch master and develop but I noticed that I've a warning on `npm install` :
>npm WARN optional Skipping failed optional dependency //appdmg:
>npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.3.6

![](https://i.unixfox.eu/13-18-45-2016.png)

**Comment by rodrigok** [comment]
appdmg is a OS X thing, so, there is no problem.

I have no idea why your screen have this problem. Is working ok in ubuntu. Probably is na issue related with Electron.

**Comment by unixfox** [comment]
Did you tried on ubuntu with Gnome ?

**Comment by rodrigok** [comment]
I don't think so

**Comment by unixfox** [comment]
I've the same issue on XFCE, do you think it's related to the NodeJS version or maybe a package installed natively on ArchLinux ?

**Comment by rodrigok** [comment]
I really don't know, sorry.

Another electron projects that uses webview runs correctly in your machine?

**Comment by unixfox** [comment]
It's my first time! Can you provide a list so I can test other projects under Electron?

**Comment by michaudg** [comment]
Maybe related to this bug :  https://github.com/keybase/client/issues/2024

I have this problem too. I'm on Arch with latest Nvidia drivers.

**Comment by gromain** [comment]
I can confirm too that downgrading with `sudo pacman -U freetype2-2.6.2-1-x86_64.pkg.tar.xz` solve this problem for me too.

**Comment by unixfox** [comment]
Thank you @michaudg it's working !

If anyone want to downgrade to **freetype2 2.6.2**, here is how to make it :

1. Install **downgrader** from [AUR](https://aur.archlinux.org/packages/downgrader/) : `yaourt -S downgrader`
2. Execute the command : `downgrader freetype2`
3. Choose `freetype2-2.6.2-1` (2) and press enter.
4. Continue the installation and enjoy !

There is a [bug report](https://bugs.archlinux.org/task/48300) on Arch Linux.

**Comment by rodrigok** [comment]
Awesome, so can we close this issue?
