### ISSUE TITLE
Unable to close about page in fullscreen mode (macOS)

### ISSUE THREAD

**Issue by marcedicmihi** [RocketChat/Rocket.Chat.Electron#1020]
## My Setup
- Operating System: macOS 10.13.6
- App Version: 2.14.4
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When I go to Rocket.Chat > About Rocket.Chat and put the app in fullscreen mode I'm unable to close the window and get back to the app w/o quitting the app.

### Current Behavior
The about page open in a seperated window (popup). That's why in fullscreen mode it's huge and can't be closed.

### Expected Behavior
Normally you it's possible to reach the top bar of a window in macOS, even in fullscreen mode when you navigate the cursor to the top of the screen. Or a "Close" Button would help.

**Comment by lightweight** [comment]
I cannot close the "About RocketChat" window with version 2.15.1 on Linux - there's no close button. ESC doesn't do it either... The app is not full-screen.

**Comment by tassoevan** [comment]
@lightweight Which desktop environment?

**Comment by lightweight** [comment]
It's affecting my colleague who's on Ubuntu 18.04 (Gnome). Not happening for me, with Cinnamon on Linux Mint 19.2.
