### ISSUE TITLE
[New] Display Rocket.Chat window on new group messages

### ISSUE THREAD

**Issue by abicur** [RocketChat/Rocket.Chat.Electron#1022]
## My Setup
- Operating System: Windows
- App Version: 2.14.4
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

1. Go to some channel and setup notification prefernces for this chat to show on every message.
2. Setup "Show on unread" option.
3. Hide Rocket.Chat to the tray.
4. If someone send a message to this channel you will recieved a popup notification, but Rocket.Chat windows will stay hidden in tray. So when the popup window closes you won't know that someone wrote something in the chat. 

### Current Behavior
The Rocket.Chat window is not displaying.

### Expected Behavior
The Rocket.Chat windows must be shown and flashing

**Comment by tassoevan** [comment]
I believe it was achieved when "Show on unread messages" setting landed in the app. Please let me know if it isn't the case.
