### ISSUE TITLE
Some members of my team are not getting messages - the actual messages or notifications.

### ISSUE THREAD

**Issue by milanchotai** [RocketChat/Rocket.Chat.Electron#1023]
@stefanmaco and @veemex

I'm unable to message 2 people on our team. I thought the issue was due to being on invisible status by accident but issue continues. It's like my messages just don't send.

I'm on the mac app

**Comment by milanchotai** [comment]
Issue resolved - somehow i was set to invisible

There should be a note that messages don't seem to send right when on invisible and no prompt comes up reminding the user that this is happening. I lost a week trying to figure out how come I coudln't contact people correctly

**Comment by tassoevan** [comment]
This happens only via the desktop app? Does accessing it via browser work normally?

**Comment by veemex** [comment]
It seems it suddenly started working again . I received 40+ notifications at once . And after that we started to receive notifications again ( IOS ) . Desktop app did not refresh correctly . There were times when i received the message after several hours , or had to open/close the app multiple times. In the last couple of weeks it started to work normally.
