### ISSUE TITLE
yarn: Fetching packages fails. event-stream

### ISSUE THREAD

**Issue by ml-** [RocketChat/Rocket.Chat.Electron#1024]
## My Setup
- Operating System: Linux
- App Version: develop
- Installation type: git

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When running `yarn install`, it fails with the following message:
`error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"`

### Current Behavior
`yarn install` fails

### Expected Behavior
`yarn install` fetches all the packages succesfully.

**Edit:** event-stream and flatmap-stream are dependencies of dbus-native. dbus-native removed those in a newer version already. As a workaround it is possible to ignore the yarn.lock file.

**Comment by tassoevan** [comment]
Related to: https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident
