### ISSUE TITLE
No way to go previous screen.

### ISSUE THREAD

**Issue by techmehra** [RocketChat/Rocket.Chat.Electron#1029]
## My Setup
- Operating System: macOS Mojave Version 10.14.1 
- App Version: 2.13.3
- Installation type: pkg

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description
<img width="650" alt="screenshot 2018-12-04 at 4 43 10 pm" src="https://user-images.githubusercontent.com/18284379/49438237-c46e4d00-f7e3-11e8-9b9c-60658f577e88.png">

**Step To Reproduce**
1. Click on the glob icon on left menu. 
2. click on channel list
3. screen shot attached as result

### Current Behavior
No Way to go previous screen.
After killing the application now it is showing loader on that screen 

<img width="1138" alt="screenshot 2018-12-04 at 4 51 57 pm" src="https://user-images.githubusercontent.com/18284379/49438632-f2a05c80-f7e4-11e8-8a59-00bae5ea2adb.png">

### Expected Behavior
There should be a way to go to previous screen.

**Comment by techmehra** [comment]
There is still loader after restarting my System

**Comment by abicur** [comment]
I had a similar problem when I tried to open a link to a resource located at the same address as the chat server. For example, the chat is located at the address https://chat.test.com and the resource is located at the address https://chat.test.com/some-path/resource. In this case, the client tries to open this link inside the application, and not in the browser. And then it show "Page not found".
To solve this problem I had to clean the user profile.

**Comment by tassoevan** [comment]
It's an annoying bug from Rocket.Chat browser. The simplest fix is `View > Back` and `View > Reload`.

**Comment by tassoevan** [comment]
@techmehra Are you using the latest version (2.14.5)?

**Comment by techmehra** [comment]
Version 2.13.3

**Comment by tassoevan** [comment]
Ok. I'm closing this due to #1009.

**Comment by abicur** [comment]
> It's an annoying bug from Rocket.Chat browser. The simplest fix is `View > Back` and `View > Reload`.

@tassoevan Is there any milestones for this problem on web-client? As I see it is an old problem.

**Comment by tassoevan** [comment]
@abicur Not yet. @RocketChat/core is reviewing the entire process for planning and executing the milestones in 2019 and this should be included. There are some issues open, like this one https://github.com/RocketChat/Rocket.Chat/issues/11619.

**Comment by Nono-m0le** [comment]
I just had a similar issue as @abicur on Windows 10. A colleague wanted to send me a screenshot, it appears as a link to the instance url, and we both got "kicked out" with a white page => No other option than reinstalling the application.
