### ISSUE TITLE
Option to download uploaded files

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat.Electron#103]
On clicking a link in the desktop agent the file doesnt download to the machine.

Download works on the web version ok.

**Comment by mottobug** [comment]
+1

**Comment by shawnbon206** [comment]
this is a bug, not an enhancement.

**Comment by Shadosky** [comment]
+1

**Comment by tuxBurner** [comment]
+1

**Comment by mottobug** [comment]
i'll agree, this is clearly a bug, not an enhancement

further explanation and a suggestion to fix this is found at: https://github.com/RocketChat/Rocket.Chat.Electron/issues/145

**Comment by Jonbj** [comment]
+1
