### ISSUE TITLE
Bunch of files in temp directory

### ISSUE THREAD

**Issue by Ystro** [RocketChat/Rocket.Chat.Electron#1031]
## My Setup
- Operating System: Windows 10 x64 (also tested in Win7x64)
- App Version: 2.14.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The Rocket.Chat-Desktop app creates a bunch of temporary files in the %TEMP% directory. 
![image](https://user-images.githubusercontent.com/16974350/49501536-638e5580-f873-11e8-9dd0-87399af3f8a7.png)

### Current Behavior
The app creates multiple identical files in the %TEMP% directory on various dates, some have identic timestamps.

### Expected Behavior
The app creates only one copy of each needed file.

**Comment by tassoevan** [comment]
These should be cached avatars for notifications. Maybe some have the same content but came from different URLs, which is fine.
