### ISSUE TITLE
Is it possible to turn on spell check

### ISSUE THREAD

**Issue by channbora** [RocketChat/Rocket.Chat.Electron#1032]
## My Setup
- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by tassoevan** [comment]
Currently, right-clicking anywhere will open a context menu with the spell check language options.

**Comment by localguru** [comment]
@channbora can't confirm. Spellchecking is working in 2.14.6, even with custom language packages.

**Comment by gfernandez-me** [comment]
grammarly extension is not working in the input chat

**Comment by wandrade** [comment]
Would be nice if Grammarly did work on it. I believe it is a rocket chat issue since Grammarly works with everything else (Whatsapp, GitHub, Gmail even those tech support chats on stores pages)

**Comment by debMan** [comment]
Yep. It seems Grammarly won't work in the RocketChat web client. 
Is there any solution?

**Comment by RMCampos** [comment]
Grammarly still doesn't work. Can someone provide any sort of comment? Thanks, guys, Rocket Chat is really a great tool. It would be super nice to be able to use Grammarly on it!

**Comment by jeanfbrito** [comment]
@RMCampos I use Grammarly on the RC, whats the problem?
![image](https://user-images.githubusercontent.com/1177482/181345430-c782b55b-8517-4d59-aa9f-5903b62dac13.png)

**Comment by RMCampos** [comment]
@jeanfbrito really? Did you do something to get it working? My OS is Linux, Ubuntu. The browser is the official Google Chrome. It works on any other tab or inputs. However, at this workspace, nothing.

**Comment by jeanfbrito** [comment]
@RMCampos I use it on MacOS. But are you using the Electron or the web browser? This issue is for Electron Desktop App.

**Comment by RMCampos** [comment]
Hmm, yeah, I'm using the web browser version. Sorry.

**Comment by jeanfbrito** [comment]
Its not a Grammarly issue? I dont get how Rocket.Chat would make it not work.

**Comment by RMCampos** [comment]
That's the question! My first guess goes to the website because I can use it without a problem everywhere else. But I'll dig about it. Thanks anyway. @jeanfbrito

**Comment by jeanfbrito** [comment]
Ok, if you find something related, please tell us. Thank you @RMCampos

**Comment by adrielschmitz** [comment]
Nothing yet?
