### ISSUE TITLE
OTR Chat should be Removed on OTR session end.

### ISSUE THREAD

**Issue by techmehra** [RocketChat/Rocket.Chat.Electron#1033]
## My Setup
- Operating System: macOS 10.14.1
- App Version: 2.13.3
- Installation type: pkg

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The OTR chat should be cleared form the screen when user end the OTR session

### Current Behavior
OTR chat are still in the main window, and some kind of key on the left panel.

### Expected Behavior
OTR chat should be removed from both window.

**Comment by tassoevan** [comment]
I think this is an issue in the Rocket.Chat server. Do you mind open an issue in [the server repo](https://github.com/RocketChat/Rocket.Chat/issues/new)?

**Comment by techmehra** [comment]
Okay, I will open an issue there too.
