### ISSUE TITLE
2.14.5 for Mac doesn't respect servers.json 

### ISSUE THREAD

**Issue by mcclint680** [RocketChat/Rocket.Chat.Electron#1034]
## My Setup
- Operating System:  MacOS 10.12.6
- App Version: 2.14.5
- Installation type: Mac .pkg

- [X ] I have tested with the latest version
- [ X] I can simulate the issue easily

## Description
Brand new installation, app has not been launched yet, I put the servers.json file we've been using forever into ~/Library/Application Support/Rocket.Chat/ then launched the app.  It prompts me to input the server info.  I also tried putting the file in /Applications/Rocket.Chat.app/Contents/Resources/ with the same results.

### Current Behavior
It asks for server info upon first launch

### Expected Behavior
It should already have the server info as previous versions did.

**Comment by mcclint680** [comment]
To clarify this is from the standard .pkg installer, **not** the MacAppStore .pkg

**Comment by tassoevan** [comment]
@mcclint680 Check 2.14.6, please.

**Comment by t0r0X** [comment]
For sake of completeness:

I had similar issues with:
- Operating System: Windows 7 x64
- App Version: 2.14.4
- Installation type: rocketchat-setup-2.14.6.exe

App version 2.14.4 reads the `servers.json` from the INSTALL-Directory, only if a file named `servers.json` also exists in the `%APPDATA%/Rocket.Chat` directory.

Version 2.14.6 fixes this behaviour, the `servers.json` file is read from  `%APPDATA%/Rocket.Chat`, as described in the [README.md Post-install configuration](https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/README.md#post-install-configuration),

@tassoevan THANKS!

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
