### ISSUE TITLE
Tray Icon shows unread message icon but tooltip shows no unread messages

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Electron#1035]
## My Setup
- Operating System: Windows 10
- App Version: 2.14.5
- Installation type: exe

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description
The tray icon shows an icon for unread messages when using multiple servers, however, the tooltip does not show any messages unread.

### Current Behavior
(I couldn't take a screenshot and still have it show the "unread messages" tooltip, so here's a camera picture instead.)

![image](https://user-images.githubusercontent.com/6295044/49669776-5b2f4980-fa30-11e8-8912-8f41d599fd72.png)

### Expected Behavior
Should show "2 unread messages on Open.Rocket.Chat, 5 on chat.company.com"

**Comment by Maqsyo** [comment]
Wow.. i thought this is a wanted behavior...
"no unread messages" if these are only group-messages and no mentions.
"You have x messages" for mentions and direct-chats

Anyway it would be better to get a tooltip like "You have unread group-messages".

This behavior exists for "ages" or months maybe ^^

**Comment by tassoevan** [comment]
@Maqsyo You're right, but I believe that the message  and the tray icon look counter-intuitive; it's just an UX issue.

**Comment by luchsamapparat** [comment]
I also liked it better when the icon was displayed black/white when there were no news

**Comment by tassoevan** [comment]
@luchsamapparat Please take a look at #988. We're working on this and we'd like to hear your suggestions.

**Comment by wreiske** [comment]
This is unrelated, but a co-worker mentioned the following:

"When you click the notification on a Mac, it brings Rocket to the front, but it doesn't put you in the thread that caused the notification. It's annoying. That feature works on my ios device, but not on the mac client."
