### ISSUE TITLE
Desktop Notifications do not go away

### ISSUE THREAD

**Issue by nghtstr** [RocketChat/Rocket.Chat.Electron#1040]
## My Setup
- Operating System: Linux Mint 19
- App Version: 2.14.5
- Installation type: Software Manager

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Every time I get a message, I get a desktop notification. This isn't a problem, except that I have to manually close each notification for them to go away (instead of them automatically disappearing).

### Current Behavior
The notification is there, and won't go away without manual action to it.

### Expected Behavior
The notification should disappear on its own.

I also checked my notifications on my OS. There is nothing there about changing the duration of the notification. Also, I do not even see Rocket.Chat on the application list. (I don't know if this is the same issue or separate).

**Comment by idl0r** [comment]
Same here, using awesome as WM. Other programs notifications still work as before.

**Comment by nghtstr** [comment]
I am using GNOME, so it definitely seems like a Rocket.Chat or Electron issue...

**Comment by piotrkochan** [comment]
Same here, ubuntu 18 gnome

**Comment by zalloy** [comment]
🤔 I've got the opposite problem. I get no desktop notifications at all for RocketChat, even though my prefs are set to receive them. Running on Kubuntu 18.04.1 (KDE, Plasma 5.12.7)

**Comment by tassoevan** [comment]
@nghtstr I'm not using the native Electron Notification API for Linux distros, but this: https://www.npmjs.com/package/freedesktop-notifications. Is there any known bug about D-Bus notifications on Gnome and KDE?

**Comment by nghtstr** [comment]
@tassoevan There might be. There is one open issue that **might** be related to this issue. Here is the link: [Scripts won't terminate automatically](https://github.com/cronvel/freedesktop-notifications/issues/3)

**Comment by icerootsvw** [comment]
I also have this issue. Rocket.Chat Notifications don't go away, other programs like thunderbird, evolution and chrome dont have these problems.

Tested with Debian GNU/Linux Stretch and Mate. Rocket.Chat Version 2.14.6

**Comment by Forage** [comment]
You can add me to the list of people how find this behaviour annoying as well.

I did a quick search, but despite ["persistence" being mentioned](https://www.npmjs.com/package/freedesktop-notifications#getcapabilities) as a possible capability, there's no mention on how to use it.
Could it be that this is some undocumented feature with a bad default value that needs to be changed?

RocketChat: 2.14.7
OS: Ubuntu 18.10 (vanilla GNOME Shell)

**Comment by ml-** [comment]
Some addition. The persistent notification thingy is caused by this:
https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/src/background/notifications.js#L89
```javascript
timeout: 24 * 60 * 60 * 1000,
```
Yes, that's 24h.

Removing this line will make the notification daemon handle the duration. Which might work just fine, but not for everyone. Especially for WMs and daemons that refuse to adhere to standards.

**Comment by tassoevan** [comment]
Is this still happening?

**Comment by icerootsvw** [comment]
Not for me with the newest stable release but because the new stable release has a (new) bug with auto away, I switched back to an older version
