### ISSUE TITLE
How to increase the duration of the display notice on the desktop

### ISSUE THREAD

**Issue by djordjy25** [RocketChat/Rocket.Chat.Electron#1042]
How to increase the duration of the display notice on the desktop. In the settings, you increase the time, but this does not affect the duration of the display of the notification on the desktop. Employees complain about not seeing incoming messages.

## My Setup
- Operating System: Windows 7, windows 10
- App Version: rocketchat 2.14.6 
- Installation type: rocketchat-setup-2.14.6.exe

- [ х] I have tested with the latest version

**Comment by tassoevan** [comment]
You can't display a notification by more than 20 seconds due to Windows style guidelines.

**Comment by abicur** [comment]
> You can't display a notification by more than 20 seconds due to Windows style guidelines.

But notifications are not shown for 20 seconds. Usually popup shown for 5-7 seconds. Even if I set notification duration to 60000.
