### ISSUE TITLE
Installation in (Windows) Autostart

### ISSUE THREAD

**Issue by alonelion1987** [RocketChat/Rocket.Chat.Electron#1043]
## My Setup
- Operating System: Windows 10 x64
- App Version: 2.14.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

It would be cool if the Rocket.Chat client would register itself in Autostart.

I know that there is already such an opportunity, but it does not work. Need help in any direction :)

![_17](https://user-images.githubusercontent.com/13063572/49995567-363d5800-ff95-11e8-9838-2597a52f0400.png)

### Current Behavior

when restarting the operating system or when it starts, the Сlient does not start automatically with the system

### Expected Behavior

when restarting the operating system or when it starts, the Сlient should be start automatically with the system and set in system tray

**Comment by abicur** [comment]
I can't confirm that. I am on 2.14.6 and Rocket.Chat app starts with the OS perfectly.

**Comment by alonelion1987** [comment]
Yes that's right! Found that there is no problem! I close the problem.

as tests I changed the name of the application. The problem was that the name was replaced in all places except the `installer.nsh` file
