### ISSUE TITLE
Window -> Reload causes freeze

### ISSUE THREAD

**Issue by GR-C** [RocketChat/Rocket.Chat.Electron#1047]
Hello,

I noticed the following problem with Rocket.Chat.

## My Setup
- Operating System: Windows 10 1709
- App Version: 2.14.6
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

1. Go To Window -> Reload
2. Wait until the content is reloaded
3. Close the Rocket.Chat Window using the X-Button on the top right side

### Current Behavior
Rocket.Chat Window does not appear after clicking on the tray icon.  I have to kill 3 processes and restart Rocket.Chat

### Expected Behavior
Rocket.Chat Window appears after clicking on the tray icon

**Comment by tassoevan** [comment]
Changed the title since I confirmed this bug in Ubuntu and MacOS Mojave too.

**Comment by tassoevan** [comment]
Please could you test 2.14.7?

**Comment by GR-C** [comment]
Seems to be fixed. Thank you!
