### ISSUE TITLE
Applet icon not displaying correctly

### ISSUE THREAD

**Issue by dsgagi** [RocketChat/Rocket.Chat.Electron#1048]
## My Setup
- Operating System: Ubuntu Mate 18.10
- App Version: 2.14.5
- Installation type: Manual deb package install

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Applet icon is not displaying correctly on Ubuntu Mate 18.10 panel. Looks like it's not scaled properly.

![panel-size-30pixels](https://user-images.githubusercontent.com/15086032/50208822-812ee500-0372-11e9-9657-b3f6abfd659e.png)

![panel-size-20pixels](https://user-images.githubusercontent.com/15086032/50208829-855b0280-0372-11e9-81ea-97933c19a2a2.png)

**Comment by icerootsvw** [comment]
I can confirm this issue on Debian Mate with rocketchat-desktop 2.14.5

![auswahl_993](https://user-images.githubusercontent.com/40857785/50274865-62962000-043e-11e9-9191-639a397dfded.png)

![auswahl_994](https://user-images.githubusercontent.com/40857785/50274901-75a8f000-043e-11e9-93f4-424ff54e1501.png)

**Comment by GezimSejdiu** [comment]
I can also confirm that this issue is happening on the Ubuntu 16.04 as well with the latest version 2.14.5. It is even not displayed at all. See the image below.
![image](https://user-images.githubusercontent.com/5259296/50401165-c1d09900-078c-11e9-836e-fa8219062e7e.png)

Best regards,

**Comment by icerootsvw** [comment]
With this version (installed from snap) i can not reproduce the issue. So for me it is fixed with the newest version

rocketchat-desktop 2.14.6 from Rocket.Chat (rocketchat✓) installed

@GezimSejdiu did you activate the tray icon? By default the Linux Version does not have it enabled by default

![menu_995](https://user-images.githubusercontent.com/40857785/50532829-7c5ef380-0b1f-11e9-9b4c-2543355eaf4c.png)

**Comment by dsgagi** [comment]
Just installed the app from Snap store. The icon displays correctly in 2.14.6.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
