### ISSUE TITLE
[BUG] App requests an nonexistent macOS version when open it.

### ISSUE THREAD

**Issue by filipedelimabrito** [RocketChat/Rocket.Chat.Electron#1049]
## My Setup
- Operating System: macOS 10.14.2 (Mojave)
- App Version: 2.14.6
- Installation type: dmg

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

### Current Behavior
When opening the app after the computer be turned on I am not able to use it since the app starts requiring a nonexistent SO version (as shown bellow)

<img width="421" alt="screen shot 2018-12-19 at 09 55 47" src="https://user-images.githubusercontent.com/11776825/50225771-2ef4c080-0380-11e9-8698-efeaf52315ae.png">

<img width="443" alt="screen shot 2018-12-19 at 09 56 31" src="https://user-images.githubusercontent.com/11776825/50225780-374cfb80-0380-11e9-8313-0da502ec82be.png">

### Expected Behavior

The app should be opened successfully.

**Comment by filipedelimabrito** [comment]
Update: After trying to open the app again I was able to use it.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
