### ISSUE TITLE
It is Impossible to write 'ö' on US-International Keyboard Layout

### ISSUE THREAD

**Issue by pascal-t** [RocketChat/Rocket.Chat.Electron#1050]
### Description:

Writing German (or other special) characters on an English keyboard Layout requires you to first selct the United-States International Layout. Then you can hit [rightAlt] + [Key] to write the desired Umlaut.  
This works in most cases:  
[Atl]+[Q] for 'ä' and the uppercase variant; [Alt]+[Y] for 'ü' and the uppercase variant; [Alt]+[S] for ß;
However this does not work for [Alt]+[P] ('ö') (the uppercase variant works).

### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System: Windows 10
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. In Windows change the Keyboard Layout to USA-International
2. Click on any Chat text field
3. Press [RightAlt] + [P]

### Expected behavior:

an 'ö' appears at the location of the cursor 

### Actual behavior:

the cursor jumps to the Search bar

### Relevant logs:
none

**Comment by Kirinkunhime** [comment]
I guess it did not work when the bug was reported - mentioned here: https://github.com/RocketChat/Rocket.Chat/issues/9322

Facing the same issue & hoping for a fix soon-ish. :)

**Comment by tassoevan** [comment]
@pascal-t and @Kirinkunhime: could you please inform the Rocket.Chat server version?

**Comment by pascal-t** [comment]
@tassoevan I as a user cannot find a way to see the server version. I also don't see how it is relevant since the problem occurse exclusively in the desktop app. The proplem is still present after I updated the desktop app to the latest version (2.14.7)

**Comment by tassoevan** [comment]
@pascal-t Some keystrokes are captured by the web client version which is rendered inside the desktop app version; it's possible that the key shortcut to go to search bar has been captured instead of leaving the keys free for typing. In recent versions, some of those shortcuts changed. If access the server from a browser doesn't reflects the issue, so it's definitely a desktop app issue, of course.
As a user, you can check the server version by accessing the URL `https://<your server address>/api/v1/info` in any browser.

**Comment by pascal-t** [comment]
The server version is 0.73.2

**Comment by tassoevan** [comment]
@pascal-t Thank you!

**Comment by Kirinkunhime** [comment]
> @pascal-t and @Kirinkunhime: could you please inform the Rocket.Chat server version?

On my side it's 0.74.2

**Comment by Kirinkunhime** [comment]
FYI - at least on my side it seems fixed for now by updating to 0.15.0 of the Desktop-client.

Server does not seem to influence this, as I've seen this behaviour before on a 0.63.3 server and there it works now perfectly fine.

**Comment by pascal-t** [comment]
Can confirm that it is working after updating to v2.15.0
