### ISSUE TITLE
Search messages - autofocus search field

### ISSUE THREAD

**Issue by urosino** [RocketChat/Rocket.Chat.Electron#1051]
## My Setup
- Operating System:Windows10
- App Version: 2.14.6
- Chat Version: 0.72.0

## Description
Autofucus on the search field

### Current Behavior
When user clicks on the search messages icon he needs to click again to the search field before he can starts typing

### Expected Behavior
When user clicks on the icon he should be able to start searching immeaditly

**Comment by pbaity** [comment]
This is an open issue in the main repo too: https://github.com/RocketChat/Rocket.Chat/issues/11482

Looks like there's already a PR for it, but it's waiting on review: https://github.com/RocketChat/Rocket.Chat/pull/15573

So this issue might be considered a duplicate, but I wanted to give anyone interested a place to go voice their support.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
