### ISSUE TITLE
Saving a setting changes GUI language to English

### ISSUE THREAD

**Issue by derniwi** [RocketChat/Rocket.Chat.Electron#1057]
After changing a setting in the GUI the GUI language switches to English, regardless of the language setting. Restarting the program will display the GUI in the chosen language.

We have tested this behaviour on Mac OS Mojave and Windows 10 Pro 1803 x64.

The app version on Mac is 2.14.6

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Switch the language to German, save and restart the program. Then change i.e. the notification volume and the GUI switches to English, displaying "German" as selected language.

**Comment by tassoevan** [comment]
Your issue is related to the Rocket.Chat server, please reopen it in the [server repository](https://github.com/RocketChat/Rocket.Chat). Thanks!

**Comment by derniwi** [comment]
But it seems the server keeps the right data. It is just the GUI which switches the language until it is restarted. There is no need to change the language (in fact, even if I change the language it doesn't work until a restart of the program) to German back again.

**Comment by tassoevan** [comment]
@derniwi Sure, I didn't make it clear why it's a server issue: mostly of the UI comes from the server. This client adds some integration on desktop, like a tray icon and multiple servers, but the vast majority of the interface is the same one you see accessing Rocket.Chat using a web browser. BTW, I'd be glad if you may confirm the issue happening in a browser.

**Comment by derniwi** [comment]
@tassoevan: thank you for your explanation and yes, I confirm this bug appears also in the web browser.

So I'll open a ticket in the server repository.

**Comment by tassoevan** [comment]
Thank you!
