### ISSUE TITLE
Chat notifications are not occurring

### ISSUE THREAD

**Issue by danielbighelini** [RocketChat/Rocket.Chat.Electron#1058]
## My Setup
- Operating System: Windows 10 (1803)
- App Version: 2.14.6
- Installation type: exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

### Current Behavior
Chat notifications are not occurring.

### Expected Behavior
Direct messages to the user or users mentioned in a conversation should be notified by alerts in windows systray or popups on the desktop.

**Comment by derniwi** [comment]
I had the same problem, it seems thy complete systems needs a few hours until this works.

**Comment by regetskcob** [comment]
Had the same problem on macOS. had to reinstall the client, what solved the issue.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
