### ISSUE TITLE
Impossible to get back when 404 error appears

### ISSUE THREAD

**Issue by eliasnogueira** [RocketChat/Rocket.Chat.Electron#1059]
## My Setup
- Operating System: MacOs Mojave
- App Version: 10.14.2 (18C54
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Main frame shows a 404 Error.

<img width="1005" alt="screen shot 2019-01-11 at 16 55 00" src="https://user-images.githubusercontent.com/284888/51053744-ad303580-15c1-11e9-8da3-fe2b08bdb11b.png">

### Current Behavior

When you go to the _Directory_ item, search for a channel that does not exists and click on _No results found for: <search term>_ a screen appears with Error 404.

On desktop app there're no way to return to the previous page (directory).
If you do the same, on the web page, you can click on back button and see the previous page. On the desktop app you be trapped.

This block the desktop app for use.

Desktop app version: 2.14.6

### Expected Behavior

Some ideas:
* Have a way to back to the previous page
* Have an custom 404 page with a return link

### Steps to reproduce
1. Click on _Directory_ icon
2. On _Search Channels_ fill a channel that does not exists. E.g: "no_channel"
3. Click on _No result found for: no_channel_

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
