### ISSUE TITLE
Handle Context Menus for Links (http, email, etc)

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat.Electron#106]
##

**Comment by akashnimare** [comment]
Is it solved?

**Comment by rodrigok** [comment]
@akashnimare I don't think so.

**Comment by akashnimare** [comment]
It's fairly easy. I'll send a PR to fix this.

**Comment by engelgabriel** [comment]
hi @akashnimare 

Are you still willing to contribute with a PR for this?
