### ISSUE TITLE
Rocketchat won't start (snap package)

### ISSUE THREAD

**Issue by zalloy** [RocketChat/Rocket.Chat.Electron#1060]
## My Setup
- Operating System: Kubuntu 18.04 LTS
- App Version: 2.14.7
- Installation type: snap

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Up until about 15 minutes ago, Rocketchat-desktop was working fine on my system. I had to restart my machine, and after doing so Rocketchat no longer starts up. It appears to try to start, then closes. I am able to login to our Rocketchat servers via the browser, so I think something happened to the app on my end. 

This seems to be an issue with the snap package specifically, as I was able to remove the snap and install the deb package, which is working correctly.

### Current Behavior
Rocketchat-desktop tries to start, then closes. Trying to run it from the command line results in the following error: `ln: failed to create symbolic link '/home/laurie/snap/rocketchat-desktop/9/.config/gtk-2.0/gtkfilechooser.ini': File exists
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
Trace/breakpoint trap (core dumped)`

### Expected Behavior
Rocketchat should start when opened via the KDE launcher or command line.

**Comment by apcookrz** [comment]
I am having this exact issue, only it is with the .deb package.

**Comment by varac** [comment]
Same issue, rocket-chat won't start without any reasonable explanation:

```
 ~ $ rocketchat-desktop         
ln: failed to create symbolic link '/home/varac/snap/rocketchat-desktop/60/snap/rocketchat-desktop/60/Documents': No such file or directory
ln: failed to create symbolic link '/home/varac/snap/rocketchat-desktop/60/snap/rocketchat-desktop/60/Desktop': No such file or directory
ln: failed to create symbolic link '/home/varac/snap/rocketchat-desktop/60/snap/rocketchat-desktop/60/Downloads': No such file or directory
ln: failed to create symbolic link '/home/varac/snap/rocketchat-desktop/60/snap/rocketchat-desktop/60/Music': No such file or directory
ln: failed to create symbolic link '/home/varac/snap/rocketchat-desktop/60/snap/rocketchat-desktop/60/Pictures': No such file or directory
ln: failed to create symbolic link '/home/varac/snap/rocketchat-desktop/60/snap/rocketchat-desktop/60/Videos': No such file or directory
ln: failed to create symbolic link '/home/varac/snap/rocketchat-desktop/60/snap/rocketchat-desktop/60/Public': No such file or directory
ln: failed to create symbolic link '/home/varac/snap/rocketchat-desktop/60/snap/rocketchat-desktop/60/Templates': No such file or directory
```

Ubuntu 19.04, rocketchat-desktop 2.15.3 installed as snap.

**Comment by CM2Walki** [comment]
Go the same issue after upgrading from debian 9 to 10.

`
$ ~/snap/rocketchat-desktop# snap run rocketchat-desktop
ln: failed to create symbolic link '/root/snap/rocketchat-desktop/71/snap/rocketchat-desktop/71/Documents': No such file or directory
ln: failed to create symbolic link '/root/snap/rocketchat-desktop/71/snap/rocketchat-desktop/71/Desktop': No such file or directory
ln: failed to create symbolic link '/root/snap/rocketchat-desktop/71/snap/rocketchat-desktop/71/Downloads': No such file or directory
ln: failed to create symbolic link '/root/snap/rocketchat-desktop/71/snap/rocketchat-desktop/71/Music': No such file or directory
ln: failed to create symbolic link '/root/snap/rocketchat-desktop/71/snap/rocketchat-desktop/71/Pictures': No such file or directory
ln: failed to create symbolic link '/root/snap/rocketchat-desktop/71/snap/rocketchat-desktop/71/Videos': No such file or directory
ln: failed to create symbolic link '/root/snap/rocketchat-desktop/71/snap/rocketchat-desktop/71/Public': No such file or directory
ln: failed to create symbolic link '/root/snap/rocketchat-desktop/71/snap/rocketchat-desktop/71/Templates': No such file or directory
No protocol specified
`

**Comment by fidomax** [comment]
Ubuntu 20.10 the same problem:
```
$ snap version 
snap    2.46.1+20.10
snapd   2.46.1+20.10
series  16
ubuntu  20.10
kernel  5.8.0-19-generic
```
```
$ snap info rocketchat-desktop 
name:      rocketchat-desktop
summary:   Official Desktop Client for Rocket.Chat
publisher: Rocket.Chat (rocketchat✓)
store-url: https://snapcraft.io/rocketchat-desktop
contact:   https://open.rocket.chat/channel/ubuntu-snap
license:   unset
description: |
  Desktop application for Rocket.Chat using Electron.
commands:
  - rocketchat-desktop
snap-id:      G4dFdVrFArll5teSvqpgWfRXIMGjME0l
tracking:     latest/beta
refresh-date: сегодня в 07:21 MSK
channels:
  latest/stable:    2.17.11       2020-07-21 (173)  63MB -
  latest/candidate: 2.7.0         2017-05-17   (4)  88MB -
  latest/beta:      3.0.0-develop 2020-09-30 (190)  69MB -
  latest/edge:      2.14.6        2018-12-25   (5) 107MB -
installed:          3.0.0-develop            (190)  69MB -

```
```
$ rocketchat-desktop 
[bugsnag] Loaded!
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" setting to invalid value "rocketchat"
Segmentation fault
```

**Comment by MrSrsen** [comment]
Today I start the computer and RC is not working. I launch it with terminal and I get:
```
$ rocketchat-desktop 
[bugsnag] Loaded!
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" setting to invalid value "rocketchat"
```

**Comment by Shoggomo** [comment]
Got the same problem recently with the latest snap version on Kubuntu 18.04. It worked up until this week.

Console output:
```
[bugsnag] Loaded!
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" setting to invalid value "rocketchat"
[bugsnag] Uncaught exception, the process will now terminate…
TypeError: Cannot read property 'replace' of undefined
    at /snap/rocketchat-desktop/196/resources/app.asar/app/main.js:2684:37
    at Array.map (<anonymous>)
    at /snap/rocketchat-desktop/196/resources/app.asar/app/main.js:2681:24
    at on (/snap/rocketchat-desktop/196/resources/app.asar/app/main.js:2397:54)
    at /snap/rocketchat-desktop/196/resources/app.asar/app/main.js:2680:12
    at /snap/rocketchat-desktop/196/resources/app.asar/node_modules/reselect/lib/index.js:76:25
    at /snap/rocketchat-desktop/196/resources/app.asar/node_modules/reselect/lib/index.js:36:25
    at /snap/rocketchat-desktop/196/resources/app.asar/node_modules/reselect/lib/index.js:90:33
    at /snap/rocketchat-desktop/196/resources/app.asar/node_modules/reselect/lib/index.js:36:25
    at /snap/rocketchat-desktop/196/resources/app.asar/node_modules/reselect/lib/index.js:86:37
```

Environment

```
❯ uname -a
Linux XXX 5.4.0-60-generic #67~18.04.1-Ubuntu SMP Tue Jan 5 22:01:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
❯ snap list rocketchat-desktop
Name                Version  Rev  Tracking       Publisher    Notes
rocketchat-desktop  3.0.1    196  latest/stable  rocketchat✓  -
❯ snap --version
snap    2.48.2
snapd   2.48.2
series  16
ubuntu  18.04
kernel  5.4.0-60-generic

```

**Comment by Shoggomo** [comment]
Seems to work with the 3.2.0-snapshot version. I still get the `Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" setting to invalid value "rocketchat"` error, but none of the following errors and it doesn't crash.

**Comment by mihauck** [comment]
Same issue today with my Ubuntu 20.04:

```
$ snap version 
snap    2.48.2
snapd   2.48.2
series  16
ubuntu  20.04
kernel  5.8.0-41-generic
```

```
$ snap info rocketchat-desktop 
name:      rocketchat-desktop
summary:   Official Desktop Client for Rocket.Chat
publisher: Rocket.Chat (rocketchat✓)
store-url: https://snapcraft.io/rocketchat-desktop
contact:   https://open.rocket.chat/channel/ubuntu-snap
license:   unset
description: |
  Desktop application for Rocket.Chat using Electron.
commands:
  - rocketchat-desktop
snap-id:      G4dFdVrFArll5teSvqpgWfRXIMGjME0l
tracking:     latest/stable
refresh-date: today at 09:14 CET
channels:
  latest/stable:    3.0.1          2020-10-02 (196) 69MB -
  latest/candidate: 2.7.0          2017-05-17   (4) 88MB -
  latest/beta:      3.0.0-develop  2020-09-30 (191) 69MB -
  latest/edge:      3.2.0-snapshot 2021-01-28 (322) 67MB -
installed:          3.0.1                     (196) 69MB -
```
like @MrSrsen i reinstalled rocketchat for tmp workaround

**Comment by axkibe** [comment]
I believe this issue started to for me by updating the kernel (to vanilla)

**Comment by nickma82** [comment]
For me it starts just once after (re)installing.
From second start on it quits with *no* msgs on the console. exit code 1.

**Comment by carlson001** [comment]
I am having the same issue. Running Ubuntu 21.10, and Rocketchat Desktop 3.7.4 from the snap store. 
What I have noticed is after existing the program, several rocketchat-desk processes remain in the process list/system monitor. I have to manually kill those processes before I can re-open Rocketchat. 

Looks like the program does not fully exist when the window is closed.

**Comment by nickma82** [comment]
In my case I had symlinks on `~/Documents, ~/Downloads, ...` which lead to the failure at startup.
I opened an issue some time ago: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2178

**Comment by unfunfunt** [comment]
I was able to solve this issue by doing 'killall rocketchat-desktop' and then trying to launch it again.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Comment by Guiraud** [comment]
Saddly, I have the same issue : 
```BASH
$ rocketchat-desktop 
/snap/rocketchat-desktop/672/rocketchat-desktop: error while loading shared libraries: /snap/rocketchat-desktop/672/gnome-platform/usr/lib/x86_64-linux-gnu/libthai.so.0: ELF file's phentsize not the expected size
````
I tryed to remove/install rocketchat-desktop  but saddly no changes in the beahviour :( 
Any clue ? 
for info : 
```BASH
$snap version
snap    2.57.6
snapd   2.57.6
series  16
debian  11
kernel  6.0.0-0.deb11.2-amd64
```
