### ISSUE TITLE
MacOS text shortcuts don't work

### ISSUE THREAD

**Issue by dzienisz** [RocketChat/Rocket.Chat.Electron#1061]
## My Setup
- Operating System: MacOS
- App Version: 2.14.7

## Description

MacOS text shortcuts don't work in Rocket.Chat :(

https://www.maketecheasier.com/text-shortcuts-mac/

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
