### ISSUE TITLE
Rocket.Chat - Open source SSL

### ISSUE THREAD

**Issue by janczajkowski** [RocketChat/Rocket.Chat.Electron#1063]
## Description

Hello,

I'll try to install Auto SSL with Snaps, but it doesn't work.
https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl/

I need SSL to run Mobile Application on iOS.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
