### ISSUE TITLE
Timeout trying to Connect to Rocket.Chat Server from Windows Rocket.Chat Client 

### ISSUE THREAD

**Issue by cyohman** [RocketChat/Rocket.Chat.Electron#1065]
**Note: Works just fine in the Browser and Mobile Apps.**

## My Setup
- Operating System: Windows Server 2008 R2 Datacenter
- App Version: 2.14.7
- Installation type: exe

- [ X] I have tested with the latest version
- [X ] I can simulate the issue easily

## Description

1.  Add New Server
   
![image](https://user-images.githubusercontent.com/14913169/51394382-3d153880-1b08-11e9-9eff-7ac683cd9c7a.png)

2. Enter address and click Connect button

### Current Behavior

_Address omitted._

![image](https://user-images.githubusercontent.com/14913169/51394496-85ccf180-1b08-11e9-961d-53ff88137395.png)

### Expected Behavior
Should Connect to Server

### Workarounds
For most users this problems goes away after one time. For 2 out of 24 users, one of two solutions worked in getting them around the issue.

**Solution 1** 
1. View → Clear Trusted Certificates
![image](https://user-images.githubusercontent.com/14913169/51395571-21f7f800-1b0b-11e9-95bf-dd11bc5b331e.png)

2. View → Reload ignoring cache
![image](https://user-images.githubusercontent.com/14913169/51395605-2fad7d80-1b0b-11e9-8e30-ea5ee8016231.png)

3. View → Open DevTools 
![image](https://user-images.githubusercontent.com/14913169/51395660-49e75b80-1b0b-11e9-8c7b-f59127aef3fa.png)
![image](https://user-images.githubusercontent.com/14913169/51395771-a480b780-1b0b-11e9-9719-25d6c82c3976.png)

4. Window → Toggle DevTools (I've independently verified this will work by itself. The previous steps were from when I was fiddling with things to get it to work.)

![image](https://user-images.githubusercontent.com/14913169/51395965-148f3d80-1b0c-11e9-897a-7f7c7a3a9fc0.png)

5. Adding the server again now works

**Solution 2**
1) When adding a https server a timeout occurs.
2) When that fails, try the same server but with https. That should fail as well.
3) Retry https:// address. That should succeed.

**Errata:**
Setup the server using these instructions:
 https://rocket.chat/docs/installation/paas-deployments/aws/#5-configure-nginx-web-server-with-tlsssl

I don't consistently see error messages in the nginx error log, but I have seen these ones:
2019/01/14 21:28:37 [crit] 1127#0: *324196 SSL_do_handshake() failed (SSL: error:1408A0A0:SSL routines:SSL3_GET_CLIENT_HELLO:length too short) while SSL handshaking, client: <IP omitted>, server: 0.0.0.0:443
2019/01/15 14:38:17 [crit] 1125#0: *377566 SSL_do_handshake() failed (SSL: error:1408A0A0:SSL routines:SSL3_GET_CLIENT_HELLO:length too short) while SSL handshaking, client: <IP omitted, server: 0.0.0.0:443

It should be noted these users have issues from a Virtual Desktop Infrastructure. If they install outside of it, then it connects just fine.

I'm posting in hopes that someone as seen a similar problem with the client or the server itself.

Thanks!

**Comment by reetp** [comment]
Seems that this may be to do with the base OS but hard to tell.

Can you fill out some more information from here please.

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Need more on your server version, install type, proxy setup etc etc.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
