### ISSUE TITLE
[feature request] File is saved without extension

### ISSUE THREAD

**Issue by peterkogit** [RocketChat/Rocket.Chat.Electron#1067]
## My Setup
- Operating System: Windows 10
- App Version: 2.14.7
- Installation type: exe

- [х] I have tested with the latest version
- [х] I can simulate the issue easily

## Description
When downloading a file, if you change the name, the extension is not saved.

![image](https://user-images.githubusercontent.com/31727004/51745581-56902480-20b4-11e9-9f3f-9bd27094786d.png)

![image](https://user-images.githubusercontent.com/31727004/51745595-61e35000-20b4-11e9-862f-f0d1ac9b210a.png)

### Current Behavior
File is saved without extension if renamed.

### Expected Behavior
The file must be saved with the extension with which it was downloaded.

I apologize for the English.

**Comment by Fleta** [comment]
Save file with their extension, like `123.txt`.

**Comment by peterkogit** [comment]
> Save file with their extension, like `123.txt`.

I understand you.
But for ordinary users transmitting images with different extensions, it will be difficult to explain everything.

**Comment by Fleta** [comment]
If you rename a file without the extension, it is natural to be saved without the extension. It's hard to see Rocket.Chat as a problem. I think you'd better classify it as a `feature request`, not a `bug`.

**Comment by peterkogit** [comment]
This is a good idea. Since it was much more convenient to rename, a simple user without specifying additionally the file extension.

**Comment by exec228** [comment]
We have this issue too. And it is not feature.

I fact, current behaviour is of Windows-style. It's a deviation from Windows-style.

Windows (almost) always adds name extension.
You don't add.

Expected behaviour:
Once extension is deleted, Save-dialog adds extension.
Once extension is deleted, and user explicitly sets name in "quotes", Save-dialog does not add extension.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
