### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by intercreativa** [RocketChat/Rocket.Chat.Electron#1068]
## My Setup
- Operating System: Linux Based (Fedora 26 Distribution)
- App Version: 2.14.6
- Installation type: <Cloned from the repository: https://github.com/RocketChat/Rocket.Chat.Electron >

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

We are trying to make a custom build based on the source code once you have cloned the repository, however there are some issues related with circular dependency (can be just a warning) and a timeout to an async hook. Here's the Log of executing yarn test:

​[root@localhost Rocket.Chat.Electron]# yarn test
yarn run v1.12.3
$ gulp build-unit-tests --env=test
[20:14:51] Using gulpfile /home/it/Desktop/rocketChat/Rocket.Chat.Electron/gulpfile.js
[20:14:51] Starting 'public'...
[20:14:51] Starting 'i18n'...
[20:14:51] Starting 'bundle'...
[20:14:51] Starting 'less'...
[20:14:51] Starting 'environment'...
[20:14:51] Finished 'environment' after 451 ms
[20:14:52] Finished 'less' after 1.5 s
**Circular dependency: src/scripts/sidebar.js -> src/scripts/webview.js -> src/scripts/sidebar.js**
[20:14:52] Finished 'bundle' after 1.62 s
[20:14:52] Finished 'i18n' after 1.65 s
[20:14:52] Finished 'public' after 1.7 s
[20:14:52] Starting 'build-app'...
[20:14:52] Finished 'build-app' after 45 μs
[20:14:52] Starting 'build-unit-tests'...
Generated an empty bundle
[20:14:52] Finished 'build-unit-tests' after 142 ms
$ npm-run-all test-main test-renderer
$ xvfb-maybe electron-mocha --require source-map-support/register app/main.specs.js

  menus
    1) "before each" hook for "should be the application menu"

  0 passing (2s)
  1 failing

  1) menus
       **"before each" hook for "should be the application menu":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/it/Desktop/rocketChat/Rocket.Chat.Electron/app/main.specs.js)**
  

Failed with exit code: 1
Output:

error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "test-main" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Current Behavior

We can't make a new build from the source code, and we are planning to add some custom behavior.

### Expected Behavior

We should be able to create a build using your source code, after that we can start customizing.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
