### ISSUE TITLE
New Line in Message Input box on every character entered

### ISSUE THREAD

**Issue by esolix** [RocketChat/Rocket.Chat.Electron#1069]
## My Setup
- Operating System: MacOS 10.14.2
- App Version: 2.14.6
- Installation type: DMG

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description
I am having an issue where input area for messages on chat would auto expand (new line) on each character being entered into it. It happens randomly - but one thing I noticed is usually when the window has been resized.

### Current Behavior
New line and input box for message expand as a character is being typed in

### Expected Behavior
Only expand when line is filled
<img width="871" alt="screen shot 2019-01-24 at 12 07 27" src="https://user-images.githubusercontent.com/24265629/51651935-2a4fa780-1fd1-11e9-95d8-d059da0dc140.png">

**Comment by frdmn** [comment]
Pretty sure this is related to the Rocket.Chat server. https://github.com/RocketChat/Rocket.Chat/issues/11904
