### ISSUE TITLE
Desktop notification not working as expected on windows 7

### ISSUE THREAD

**Issue by Fleta** [RocketChat/Rocket.Chat.Electron#1070]
## My Setup
- Operating System: Windows 7 Professional K 64bit (6.1, build 7601)
- App Version: 2.14.7(current version on Rocket.chat install menu - https://rocket.chat/install)
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

I am using Rocket.chat 2.14.7 on windows 7. Except `Test Desktop Notifications`, notification not works when I receive every messages. 

I tried hard to find same issue but I failed. If this issue is duplicated, please tag the other issue or tell me how to find that issue. Thanks for your help.

### Current Behavior
No desktop notification when I receive messages. (But `Test Desktop Notifications` works)

### Expected Behavior
Destktop notification should pop up.

**Comment by dherik** [comment]
Same here on Windows 10. But today, after close and open the Rocket app, the notifications started to work.

**Comment by sigfriedseldeslachts** [comment]
Same issue here, desktop notifications don't work.

**Comment by schlicker** [comment]
Same here. Fresh install on Windows 7, user data deleted. No notifications show up. Dev Console shows:
`Uncaught (in promise) TypeError: g is not a function
    at 201f8e192f9ed2ed2b316010222f67a2251c89c8.js?meteor_js_resource=true:221
    at 201f8e192f9ed2ed2b316010222f67a2251c89c8.js?meteor_js_resource=true:1
    at <anonymous>`

**Comment by dhoeld** [comment]
* Operating System: Windows 7 Professional 64bit
* App Version: 2.14.7
* Server Version: 0.73.1

It's the same on our site (Windows 7 Pro). Our users can't adjust the notification duration at all. If they try to adjust it anyway the desktop notification stops working completely.

**Comment by tassoevan** [comment]
I'm closing this issue because the bug reported by @Fleta was [solved recently on server repo](https://github.com/RocketChat/Rocket.Chat/pull/13457).
For those who have another notification problems, please take a look at other issues reported.
