### ISSUE TITLE
RocketChat freeze on  background

### ISSUE THREAD

**Issue by adalenv** [RocketChat/Rocket.Chat.Electron#1072]
## My Setup
- Operating System: Windows 10 Pro
- App Version: 2.14.7
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

If you let Rocketchat in background it freeze and messages dont come

### Current Behavior

If you let Rocketchat in background it froze and messages dont come and when you open it takes time to load and then messages come
### Expected Behavior

Keep RocketChat on background even if not used for a long time

**Comment by adalenv** [comment]
any update?

**Comment by tassoevan** [comment]
Please, could you check if any application error messages are thrown (menu `Window > Toggle DevTools > Console`)?

**Comment by adalenv** [comment]
No error messages.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
