### ISSUE TITLE
Can't connect to any server behind basic-auth

### ISSUE THREAD

**Issue by Drintios** [RocketChat/Rocket.Chat.Electron#1073]
## My Setup
- Operating System: Ubuntu 18.04.1 LTS
- App Version: 2.14.7
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When trying to use any basic-auth url it throws error of no server available.

### Current Behavior
Can't connect to a server behind basic-auth ie: https://username:password@chat.server.com

### Expected Behavior
I should be able to login to a basic-auth server

**Comment by reisman234** [comment]
I tried also 3.7 and 3.8 as deb on Linux Mint and 3.8 on Windows 10 -- basic auth in URL is not working.

For the Version 3.8 on my Linux Mint, I have the following behavior:
Without the basic auth credentials in the URL, I'm getting an Unauthorized  error in the debugging window of the client. Which is expected. 
With the credentials in the URL, e.g. `https://user:pass@host.de` I'm  getting immediately a [no valid server error](https://i.imgur.com/jI0h0RH.png) on the Login but nothing appears in the debugging window or in the logs on my server.
Also does the login screen stuck, and I have to refresh the client
