### ISSUE TITLE
Use system-wide (hunspell) spell check languages

### ISSUE THREAD

**Issue by Forage** [RocketChat/Rocket.Chat.Electron#1077]
## My Setup
- Operating System: Ubuntu 18.10
- App Version: 2.14.7
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
RocketChat appears to be providing it's own (limited) set of spell check language files (/opt/Rocket.Chat/resources/dictionaries).
System-wide I already have multiple hunspell language packs installed to provide spell check files for multiple languages.
It's a shame those language files aren't used automagically.
There's an option provided to search for additional language files, but when using that to point to an existing hunspell file it will give an error that it failed to copy the files (needs root permissions).

### Current Behavior
RocketChat is not using the system-wide spell check languages (hunspell packages)

### Expected Behavior
RocketChat should be using the system-wide spell check languages (hunspell packages) instead of having to add/copy them manually.

**Comment by ml-** [comment]
Related: 
- https://github.com/RocketChat/Rocket.Chat.Electron/issues/706
- https://github.com/RocketChat/Rocket.Chat.Electron/issues/169

I also wanted this feature and ended up patching the AUR package which I now maintain.
The patch here: [fix-dictionarties.patch](https://aur.archlinux.org/cgit/aur.git/tree/fix-dictionaries.patch?h=rocketchat-desktop&id=9c2c05cb7bb944359bbdb87e4f2d5efbb3c9a302)

After digging through the code for a while, I ended up blaming it on the `spellchecker` package for failing to provide the default system dictionary path. But of course things aren't that easy, so I can't really go around pointing fingers at developers. It would be nice though to pass a flag or set an ENV var to provide the hunspell dictionaries path of the targeted distribution.

**Comment by tassoevan** [comment]
Over time, we've noticed that using global dictionaries is more confusing for users of other operating systems. Closing it while a better option for a good user experience is not suggested.

**Comment by Forage** [comment]
Too bad. It's the exact opposite that's true for Linux users so maybe it should not be treated as a general solution for all operating systems to begin with.
