### ISSUE TITLE
Notifications for everything - OS X client - 1.0.0 

### ISSUE THREAD

**Issue by Coros** [RocketChat/Rocket.Chat.Electron#108]
Every new line/entry from any person in the any channel I'm a member of triggers a desktop notiication.  I've changed the general channel's notification options to "nothing" (I was attempting to use mentions) and I'm still receiving a notification any time any user says anything in the channel.

![screen shot 2016-02-24 at 10 53 41 am](https://cloud.githubusercontent.com/assets/17457045/13293349/ef07e126-dae4-11e5-993d-1242c46817e2.png)
![screen shot 2016-02-24 at 10 53 51 am](https://cloud.githubusercontent.com/assets/17457045/13293354/f34a3e46-dae4-11e5-8745-06293737fc0d.png)

**Comment by rodrigok** [comment]
This is not an problem in Destkop app, the notification comes from RC server, is the same code that sends destkop notifications on web browsers.

Can you confirm if this behavior occurs in a web browser too? Like Safari?

**Comment by Coros** [comment]
Yes it does happen in Firefox.  I attempted to test it yesterday but I may not have allowed the notifications (which is why they wouldn't work).

**Comment by Coros** [comment]
Update.. we setup another server using docker and the issue doesn't exist on that one.  Must be something wrong with ours.
