### ISSUE TITLE
App in taskbar must already run

### ISSUE THREAD

**Issue by vdvas** [RocketChat/Rocket.Chat.Electron#1084]
## My Setup
- Operating System: Windows 7 x64
- App Version: 2.14.7
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I need notification of Rocket.chat electron on Windows 7. I use popup and tray icon.
But i need also icon in taskbar.
I want always run rocket chat app in taskbar and never close.
I need to show app already then it run shadow.
I think it's can be modify by source code.
I found this tutorial
https://electronjs.org/docs/tutorial/windows-taskbar
Where i can found file in source that is responsible for the taskbar?
### Current Behavior
When i click the link of app or click on tray icon the icon on task bar is active and stay in Flash Frame mode.
When i close application, but it continues work the icon disappear from taskbar.

### Expected Behavior
When application running, icon in taskbar must already be in Flash Frame mode.

**Comment by tassoevan** [comment]
Disabling the tray icon (menu `View > Tray icon`) isn't keeping the application running in the taskbar?

**Comment by vdvas** [comment]
Thank you.
Yes, when i disabling tray icon, the icon disappear from tray and stay running in taskbar, even if the user closes the application with a cross.
And how i can deploy rocket.chat electron with this options (disable tray icon)?

**Comment by tassoevan** [comment]
Unfortunately, there is no option for it available yet; deployed settings are a planned feature though.

**Comment by vdvas** [comment]
Maybe i can overwrite some settings file after user logon?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
