### ISSUE TITLE
Tray icon shows only some pixel of number of un-read messages

### ISSUE THREAD

**Issue by ghnob** [RocketChat/Rocket.Chat.Electron#1085]
## My Setup
- Operating System: Windows 7
- App Version: 2.14.7
- Installation type: 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Last version, I'm not sure which one, showed number of unread messages in tray icon

### Current Behavior
Now, the tray icon shows only some pixel of number of un-read messages
![grafik](https://user-images.githubusercontent.com/43337034/52710520-cdbc2880-2f8f-11e9-8051-bde7324fd1c1.png)

### Expected Behavior
Show number of unread messages in tray icon or at least, **show clearly there are unread messages**.

**Comment by tassoevan** [comment]
Related to #988.

**Comment by ghnob** [comment]
In case you are interested.
The described incorrect behavior has disappeared, probably due to a Windows update two days ago.
