### ISSUE TITLE
No Valid Server found at URL

### ISSUE THREAD

**Issue by SaravanaRaja88** [RocketChat/Rocket.Chat.Electron#1086]
## My Setup
- Operating System: Ubuntu 18 Desktop
- App Version:2.14.7
- Installation type: 
Snap install

- [x ] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description

No Valid Server found at URL
### Current Behavior

When i try to login to rocket-chat desktop application by giving the the url
Example -> https://chat.mywebsite.com/
### Expected Behavior

should login to my chat channel.

**Comment by tassoevan** [comment]
The desktop client tries to validate a host as a Rocket.Chat server by looking into `/api/v1/info` endpoint, e.g., https://open.rocket.chat/api/v1/info should show the Rocket.Chat server version of https://open.rocket.chat. Please check if this URI is accessible in your server.

**Comment by SaravanaRaja88** [comment]
Thanks a lot for the information.  I was able to connect with the server.

**Comment by rahra** [comment]
Same issue here. Debian with Rocketchat 2.14.7.
The server is accessible through its web interface but not with the desktop client. The Url pointed out above is accessible. It returns a JSON object: `{"info":{"version":"0.74.2"},"success":true}`

**Comment by rahra** [comment]
In my case I could track down the problem to a dependency on Google Chrome. See issue #1091.
