### ISSUE TITLE
Screen sharing in Video Chat stucks at loading

### ISSUE THREAD

**Issue by pawhal** [RocketChat/Rocket.Chat.Electron#1087]
Hi. While trying to share a screen via Video Chat the loading circle keeps moving but nothing happens
![untitled](https://user-images.githubusercontent.com/28776795/33929443-cdd883d2-dfe9-11e7-8de3-98c45986356a.png)
Jitsi server is fully functioning (screen sharing also) on both browsers (Chrome and Firefox).
Video and audio are great and the only thing that doesn't work is sharing a screen.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.4
* Operating System: Ubuntu 16.04 x64
* Deployment Method: snap
* Number of Running Instances: 1
* Node Version: v4.8.4

**Comment by eidermar** [comment]
Are there any news on this issue? Desktop sharing was working perfectly until the last Jitsi Meet update. Now we do see the same symptoms as described by OP. Anything that can be done within the configuration files to fix this?

**Comment by cool2bdave** [comment]
I am experiencing this with client 2.17.1
Monitor 1 Dell P2715Q 3840x2160
Monitor 2 Dell U2311H 1920x1080
Win10 Pro 1909

**Comment by pathikb** [comment]
This has been an issue since forever. This is probably not a priority for them to fix it seems or it is something that cannot be fixed.

**Comment by adelalmaleh2** [comment]
You could use the chrome to share your screen and it is working for me.
**Note:** you need to add the rocket extension to your chrome.
https://chrome.google.com/webstore/detail/rocketchat-screen-share/nocfbnnmjnndkbipkabodnheejiegccf

**Comment by pathikb** [comment]
True but it beats the entire purpose of making Electron-based apps for Desktops

**Comment by cool2bdave** [comment]
2.17.7 seems to work again for me

**Comment by pathikb** [comment]
I am on 2.17.9 and can confirm Screen Sharing does not work on macOS Catalina

**Comment by dredwilliams** [comment]
I just fought with this for a while ... the solution (work-around) I settled on was to set "Always Open in New Window" to on.  That enabled it to work across all platforms I have access to (Chrome and native apps on Windows 10 and CentOS 7).  That also solved a problem where the small window that opened up to the side was too small, but making it full screen locked up the desktop.

Client v 2.17.7
Server v 3.2.2

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
