### ISSUE TITLE
Why is there no option to disable automatic Windows startup?

### ISSUE THREAD

**Issue by fszcze** [RocketChat/Rocket.Chat.Electron#1088]
## My Setup
- Operating System: win 10
- App Version: 2.14.1
- Installation type:  exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

No option to disable automatic Windows startup from within the app

**Comment by jbkalla** [comment]
Does anyone know how to stop it from loading at startup?  I really don't want to uninstall it.

**Comment by jbkalla** [comment]
Ah, reinstalled and unchecked the option.

**Comment by andrewfinnell** [comment]
The Shortcut that automatically runs the app is locating at:

C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp

Just remove it and it should stop automatically starting for you.

**Comment by brownp2k** [comment]
None of the above applied/worked for me (no StartUp shortcut, re-install and unchecking the "Launch at startup" option), but what did work for me was using the Task Manager "Startup" tab to set Rocket.Chat to Disabled.

**Comment by frontfact** [comment]
For me the shortcut was located at:

`C:\Users\myusername\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
