### ISSUE TITLE
Not able to start recording through native app

### ISSUE THREAD

**Issue by anantaramdas** [RocketChat/Rocket.Chat.Electron#1089]
## My Setup
- Operating System: Windows 10
- App Version: 2.14.7
- Installation type: exe and self hosted server

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Trying to turn recording on through windows app via connecting to Dropbox. After confirming my account I got white screen and nothing happens after. I'm using Jisti public server. Through web interface everything working as expected.

### Current Behavior
See decription

### Expected Behavior
Dropbox enabled and able to start recording

**Comment by anantaramdas** [comment]
Screenshot describing particular issue
![image](https://user-images.githubusercontent.com/7561827/52791096-d5073300-3070-11e9-939c-15fc02b83176.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
