### ISSUE TITLE
Application crash when hiding or closing the app

### ISSUE THREAD

**Issue by szilardd** [RocketChat/Rocket.Chat.Electron#109]
Rocket.Chat version: 1.0.0
OS: Windows 10

Hi,

Sometimes when I'm hiding or closing the app from the tray icon this error pops up:
![image](https://cloud.githubusercontent.com/assets/1000217/13319484/abdc9f92-dba0-11e5-8058-7680d67dcb29.png)

Most of the times I can't even close the application and I have to kill the process.

Other than that it works great. Thanks.

**Comment by rodrigok** [comment]
This happens only when you close the app from the tray icon?

**Comment by szilardd** [comment]
Can't reproduce the issue now but I think it occurred once when closing the app from the main window too so it is not specific only to the tray icon.

**Comment by pcarn** [comment]
This happened to me on mac when I tried to use Command-R to reload it. When I try to quit, it minimizes it, and throws that
