### ISSUE TITLE
Desktop client depends on Google Chrome

### ISSUE THREAD

**Issue by rahra** [RocketChat/Rocket.Chat.Electron#1091]
## My Setup
- Operating System: Debian Linux
- App Version: 2.14.7
- Installation type: .deb package

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Rocket chat network (proxy) settings depend on the settings of Google Chrome.

### Current Behavior
If the network settings in Google Chrome are modified it influences Rocket Chat. E.g. Rocket chat cannot connect to the server anymore if Chrome network settings point to a proxy which is unavailable.

### Expected Behavior
The network settings should be independent or it should depend on the system wide settings. It typically is not expected that it depends on some other locally installed software.
(I wonder what would happen if Chrome is not installed.)

**Comment by tassoevan** [comment]
Are you using environment variables like `https_proxy` to set the proxy configuration? I think that's the default way to configure proxies on Google Chrome (besides command line parameters) and it is supposed to globally affect the system.

**Comment by rahra** [comment]
No, I don't use env variables. Within Chrome's settings there is an option to set the proxy (similar to what it looks like in Firefox) See Screenshot:
![image](https://user-images.githubusercontent.com/4337999/52956355-43106a80-338f-11e9-81f7-8f09c1e4aefd.png)

**Comment by tassoevan** [comment]
I'm on Google Chrome running over MacOS right now; the "Open proxy settings" button display the *system* configuration for a proxy. I'm sure that on Windows, the "Internet Options" Control Panel applet is shown too. I'll try to confirm if Chrome on Linux distros doesn't try to set a proxy for the entire system too.
BTW, there is an feature request to enable to setting a proxy *only* for the desktop app: #888.

**Comment by rahra** [comment]
Hi!
Meanwhile I figured out that Chrome on Linux also modifies the system settings. It wasn't obvious at first.
Thus, this ticket is actually a false positive ;) sorry.

Regards,
Bernhard
