### ISSUE TITLE
Jitsi - Videoconference link CLICK TO JOIN not working

### ISSUE THREAD

**Issue by kokotko1337** [RocketChat/Rocket.Chat.Electron#1095]
### Description:
autogenerated link - CLICK TO JOIN is not working for users in chat.

**UPDATE!**
This issue is only when link is generated in BROWSER, not in ROCKET CHAT WINDOWS APP

### Steps to reproduce:

1. User A - Start videoconference
2. Click to join - Link will be autogenerated and posted in chat window
3. User B,C, D click on Link Click to join - Unable to join with message - **Call already ended** , but conference is live and working
4. after paste link (I Icon in Jitsi) from jitsi to chat, Users B,C,D can join

### Expected behavior:

After Users click Click to join, they should be alble to join the conference dicetly from chat, without pasting link from Jitsi

### Actual behavior:

Generated: Click to Join - not working

### Server Setup Information:

Rocketchat and Jistsi are installed on the same server.

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu 16.04
- Deployment Method: deb package
- Number of Running Instances: 1
- NodeJS Version: v8.15.0
- MongoDB Version: MongoDB shell version v3.6.10

### Possible Hotfix ?

It is possible to disable autogenerated link CLICK TO JOIN to be autoposted ? 
This confusing users, it is better when moderator paste link, withouh CLICK TO JOIN.

Thank you guys

**Comment by woulf** [comment]
Hello,
i have a user with a similar problem, but it is never working wether the link have been generated in the web or in the APP.
Plus if the user click on the jitsi link in the rocketchat app it opens jitsi in the web browser instead of in the app.

RocketChat Windows App: 2.15.0 
OS: Windows 10 Pro
Connected trough RDP to the windows if it matters

**Comment by ankar84** [comment]
I think actual issue is being discussed [here](https://github.com/RocketChat/Rocket.Chat/issues/11649)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
