### ISSUE TITLE
Too many requests error in private conversations

### ISSUE THREAD

**Issue by sfiligoi** [RocketChat/Rocket.Chat.Electron#1097]
## My Setup
- Operating System: MacOS
- App Version: 2.14.7
- Installation type: AppStore

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily
- [x] I can reproduce the issue easily

## Description

All private conversation rooms return a "Error, too many requests" result (see picture)
![image](https://user-images.githubusercontent.com/2708665/53214644-36477d00-3602-11e9-8a6b-780c536bc3db.png)

I checked in DevTools mode, and indeed the server seems to be returning that message.
But this does not happen in the Web interface, just in the MacOS desktop app.

The problem started about a day ago, so I strongly suspect it is due to the latest client update.

Note that public rooms still work fine.

### Current Behavior

I get an error every time I try to open a private conversation tab.
 
### Expected Behavior

Open a private conversation tab and exchange chats with other people.

**Comment by eevrenci** [comment]
I get the same error on linux and windows machine too. As a workaround you can logout and login the electron app.

**Comment by crazyvonni** [comment]
I had the same issue on my windows machine and I have tried a lot.  

The only way to solve the issue for me was to completely uninstall the app with deleting the user data. There is a corresponding checkbox at the end of the uninstall process. 

After the reinstall everything works fine again.

**Comment by sfiligoi** [comment]
Deleting all the user data indeed works.
After a clean wipe of any RocktChat related files, my Mac client works again.

**Comment by McpCyber** [comment]
Hi there , is this the right solution ? or depends on the "Rate Limiter" Setting in Admin Panel ?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
