### ISSUE TITLE
Uncaught Exception: Error: EACCES: permission denied

### ISSUE THREAD

**Issue by mattsches** [RocketChat/Rocket.Chat.Electron#1102]
## My Setup
- Operating System: Ubuntu 18.04.02 LTS
- App Version: 2.15-develop
- Installation type: snap

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
A message pops up after a couple of minutes: `A JavaScript error occurred in the main process` containing the following stack trace:

```
Uncaught Exception:
Error: EACCES: permission denied, open '/home/mattsches/snap/rocketchat-desktop/24/.config/Rocket.Chat/window-state-main.json.__new__'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Object.writeFileSync (fs.js:1168:35)
    at writeFileSync (/snap/rocketchat-desktop/24/resources/app.asar/node_modules/fs-jetpack/lib/write.js:45:8)
    at writeAtomicSync (/snap/rocketchat-desktop/24/resources/app.asar/node_modules/fs-jetpack/lib/write.js:61:3)
    at Object.writeSync [as sync] (/snap/rocketchat-desktop/24/resources/app.asar/node_modules/fs-jetpack/lib/write.js:74:3)
    at Object.write (/snap/rocketchat-desktop/24/resources/app.asar/node_modules/fs-jetpack/lib/jetpack.js:226:13)
    at Object.saveState (/snap/rocketchat-desktop/24/resources/app.asar/app/src/background/windowState.js:55:15)
    at Timeout.call [as _onTimeout] (/snap/rocketchat-desktop/24/resources/app.asar/app/src/background/windowState.js:11:18)
    at ontimeout (timers.js:425:11)
```

![rocketchat_exception](https://user-images.githubusercontent.com/68414/53325750-4c945800-38e4-11e9-8a50-3ac0f537ba27.png)

I am not sure what triggers the exception, permissions seem to be correct for the given directory. The Rocket.Chat app continues working after I close the popup, but after a while the error returns.

### Current Behavior
Error window pops up because an exception is thrown.

### Expected Behavior
Error window should not pop up.

**Comment by lorek123** [comment]
I can't even start an app :(

**Comment by tetrapus** [comment]
I'm also getting this. Resizing or moving the window consistently replicates the issue for me.

* Operating System: Ubuntu 18.04.02 LTS
* App Version: 2.15-develop
* Installation type: snap
* Server version: 0.74.3

**Comment by mattsches** [comment]
Well, it seems I'm on `2.15.0` now - unfortunately `snap changes` lists only the changes within the last 24 hours - and the error hasn't appeared for a while. I'll keep watching, though.

**Comment by tassoevan** [comment]
@mattsches Could you confirm which snap channel are you using? 2.15.0-develop shouldn't have been published in the `stable` channel.

**Comment by mattsches** [comment]
@tassoevan 
```
$ snap list --all rocketchat-desktop 
Name                Version         Rev  Aufzeichnung  Herausgeber  Hinweise
rocketchat-desktop  2.14.7          9    stable        rocketchat✓  deaktiviert
rocketchat-desktop  2.15.0-develop  24   stable        rocketchat✓  deaktiviert
rocketchat-desktop  2.15.0          28   stable        rocketchat✓  -
```

So it seems that 2.15-develop has indeed been published in the `stable` channel.

**Comment by tassoevan** [comment]
@lorek123 and @tetrapus: please let me informed if everything will be fine after snap auto-update to 2.15.0.

**Comment by lorek123** [comment]
looks fine on my side :+1:

**Comment by mattsches** [comment]
I suppose we can close this issue now?

**Comment by KheireddineAzzez** [comment]
_### Error: EACCES: permission denied, stat ‘/home/dev/Projects/vendor-chat/data/db/_tmp/.meteorignore’_


**These two commands saved my life**
**

-  npm install --unsafe-perm


**

- And then ownership change command for current user.


sudo chown -R user:user path_to_rocketchat_codebase_directory 


   Example sudo chown -R **Alex** /myrocketchat
