### ISSUE TITLE
Excessive memory consumition

### ISSUE THREAD

**Issue by ErikRuann** [RocketChat/Rocket.Chat.Electron#1103]
## My Setup
- Operating System: Windows 10 x64
- App Version: 2.14.7
- Installation type: 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

**Comment by localguru** [comment]
@ErikRuann what OS are you running it on?

I've upgraded from 2.4.17 to 2.15.0 on Xubuntu 18.04 LTS and can see massive memory and CPU usage to. After deleting `~/.config/Rocket.Chat` the new 2.15.0 version works as it should.

**Comment by tassoevan** [comment]
When upgrading from Electron 2 to 4, we jumped from Chromium 61 to 69, therefore some overhead is expected on first run converting/optimizing some cache and configuration files.

**Comment by ErikRuann** [comment]
@localguru Windows 10 x64 build 1803

**Comment by KeithMnemonic** [comment]
issue reoccurs even after wiping config. There is a definite keyboard lag

**Comment by KeithMnemonic** [comment]
went back to 2.14.7 and no issues

**Comment by tassoevan** [comment]
@KeithMnemonic Do you have any additional information about your setup?

**Comment by KeithMnemonic** [comment]
sure, sorry for not adding that. Windows 10 x 64  build 1809 OS Build 17763.316.  I can also test the newer client on my Mac in the next couple of days and see how that responds.

**Comment by bkraul** [comment]
Is there any way to alleviate this issue? I am seeing memory consumption up in the 1GB for a single RC client instance. I'd say that's a bit much.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
