### ISSUE TITLE
No visible cursor in Message text box.

### ISSUE THREAD

**Issue by BigMayo** [RocketChat/Rocket.Chat.Electron#1106]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.0
- Installation type: exe

Worked in last version

## Description
Cursor is not visible (no blink) in the message field.

### Current Behavior
Typing does produce text and messages are sent, however there is no indication that you are actively 'in' the text field

### Expected Behavior
Blinking cursor

**Comment by BigMayo** [comment]
Apparently the blinking cursor does appear. Closing issue

**Comment by tassoevan** [comment]
Yeah, I've sporadically seen this behavior happening. I guess it's a Chromium bug.
