### ISSUE TITLE
Stuck on a blank website page after clicking a link

### ISSUE THREAD

**Issue by nodje** [RocketChat/Rocket.Chat.Electron#1108]
I've been stuck on a blank page after clicking on a link to register to cloud.rocket.chat.
I happened on 2.14.7, as the link is not working I'm stuck on a blank page, leading me to assume it was a bug.

Actually, opening Rocket chat today on a Wifi connection with a login portal, I realized that Rocket was only stuck on a non-loading/blank webpage because it loaded the portal login page.
 
So the issue in my case is: Rocket seems stuck on a webpage after clicking on a link with no apparent way to go back to the chat mode.

The problem persist after upgrading to 2.15.0 today.

I've only tried common Macos shortcut to go back (like Cmd+left arrow) or some others. I can't see any button to help me get out of this.

**Comment by tassoevan** [comment]
`View > Back` should be a work around for this issue.

**Comment by nodje** [comment]
I know it sounds very stupid: I never use menu with Electron apps, just totally forgot about it.

But I've tried the shortcut indicated in the menu before though (`Cmd+[`) and to no avail.
Using menu it doesn't work either.

I just can't get away from this blank page, I'm stuck with it.

Here's what I get in the console log on Reload:
```
DevTools failed to parse SourceMap: https://cloud.rocket.chat/Applications/Rocket.Chat.app/Contents/Resources/app.asar/app/preload.js.map
react-dom.production.min.js:188 TypeError: Cannot read property 'userData' of undefined
    at t.value (index.js:87)
    at t.value (index.js:196)
    at kn (react-dom.production.min.js:167)
    at Hn (react-dom.production.min.js:180)
    at Gn (react-dom.production.min.js:202)
    at $n (react-dom.production.min.js:203)
    at fr (react-dom.production.min.js:212)
    at lr (react-dom.production.min.js:211)
    at cr (react-dom.production.min.js:211)
    at or (react-dom.production.min.js:209)
Nn @ react-dom.production.min.js:188
Un.n.callback @ react-dom.production.min.js:195
tn @ react-dom.production.min.js:144
nn @ react-dom.production.min.js:145
pr @ react-dom.production.min.js:220
fr @ react-dom.production.min.js:212
lr @ react-dom.production.min.js:211
cr @ react-dom.production.min.js:211
or @ react-dom.production.min.js:209
Jn @ react-dom.production.min.js:207
Cr @ react-dom.production.min.js:224
Or @ react-dom.production.min.js:225
Sr.render @ react-dom.production.min.js:232
(anonymous) @ react-dom.production.min.js:236
yr @ react-dom.production.min.js:222
Hr @ react-dom.production.min.js:236
render @ react-dom.production.min.js:238
(anonymous) @ index.js:7
t @ bootstrap bc40f7ff8ccf97bc2d6e:19
(anonymous) @ main.f54cc8f6.js:18490
t @ bootstrap bc40f7ff8ccf97bc2d6e:19
(anonymous) @ bootstrap bc40f7ff8ccf97bc2d6e:62
(anonymous) @ bootstrap bc40f7ff8ccf97bc2d6e:62
index.js:87 Uncaught TypeError: Cannot read property 'userData' of undefined
    at t.value (index.js:87)
    at t.value (index.js:196)
    at kn (react-dom.production.min.js:167)
    at Hn (react-dom.production.min.js:180)
    at Gn (react-dom.production.min.js:202)
    at $n (react-dom.production.min.js:203)
    at fr (react-dom.production.min.js:212)
    at lr (react-dom.production.min.js:211)
    at cr (react-dom.production.min.js:211)
    at or (react-dom.production.min.js:209)
```

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
