### ISSUE TITLE
New tray icon doesn't show online status nor unread alert

### ISSUE THREAD

**Issue by lasombra** [RocketChat/Rocket.Chat.Electron#1109]
## My Setup
- Operating System: Fedora 29 fully updated
- App Version: 2.15.0
- Installation type: flatpak

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

1. Start Rocket.Chat
1. Enable tray icon
Screenshot: https://imgur.com/a/GlcG0nQ

### Current Behavior

Tray icon doesn't show the online status nor it shows if there are unread messages

### Expected Behavior

Display a green overlay image or change the icon to red to indicate the online status. For the unread messages I would expect a red overlay image as before

**Comment by tassoevan** [comment]
User presence (online, away etc.) is not shown in tray icon anymore since it was a convoluted feature for users using multiple Rocket.Chat servers. However, the unread status should be working... Does it not appear even on direct messages and mentions?

**Comment by lasombra** [comment]
Not even. That screenshot was taken while a direct message was unread.

**Comment by nrenich** [comment]
I have a similar issue where the icon just disappears after a day or two. Running on Windows 7 x64.
Screen Clip: https://imgur.com/a/G4cKtqO
If I quit and relaunch it comes back. This was not happening in 2.14.7.

**Comment by iprok** [comment]
I still have this in 2.15.1

**Comment by dmi7ry** [comment]
Can't enable `Unread Tray Icon Alert` option. I select `On`, press `Save changes`, then RC reloads data and option again is `Off`.
Tray icon shows direct (or mentions) messages as small red dot, but doesn't show for any other messages (for example, Slack shows red dot for direct messages and mentions and green dot for all other unread messages)

**Comment by sketch242** [comment]
> Can't enable `Unread Tray Icon Alert` option. I select `On`, press `Save changes`, then RC reloads data and option again is `Off`.
> 2.17.2, Win 10

Same thing happens on MacOS client 2.16.0 with server version 2.4.2

**Comment by tassoevan** [comment]
@dmi7ry @sketch242 This seems to be an issue with Rocket.Chat server not persisting your user preferences. Do you mind opening an issue in [the server repo](https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md)?

**Comment by sketch242** [comment]
Looks like someone beat us to it.  https://github.com/RocketChat/Rocket.Chat/issues/16288

**Comment by novoid** [comment]
> Can't enable `Unread Tray Icon Alert` option. I select `On`, press `Save changes`, then RC reloads data and option again is `Off`.

Same here: Xubuntu 1910 (xfce 4.14), Rocket.Chat version 2.17.2-1555.

Although I never see the Rocket.Chat panel icon. the app "Rocket.Chat" is enabled in the list of applications in the notifications panel plugin. In the Rocket.Chat settings, notifications are enabled. 

Whatever happens in Rocket.Chat, the icon does not get  shown in the panel.

When I re-visit the Rocket.Chat preferences (My Account - Preferences - Messages), the setting for "Unread Tray Icon Alert" is set to "off" again.

**Comment by elmo23** [comment]
I have the same problem. Any solution?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
