### ISSUE TITLE
Help -> About

### ISSUE THREAD

**Issue by giray** [RocketChat/Rocket.Chat.Electron#111]
Hi, 
  Currently its difficult to see which client version is in use.  It would be nice if there was a "Help" menu where you have an About screen with Version information.

**Comment by matthias-brun** [comment]
At least on OS X this is already implemented:
![screen shot 2016-02-26 at 14 34 12](https://cloud.githubusercontent.com/assets/10801000/13353636/1332fc4a-dc96-11e5-946f-f04ab8919a9f.png)

**Comment by giray** [comment]
Not on the linux package

![screenshot from 2016-02-26 14-54-03](https://cloud.githubusercontent.com/assets/316284/13354090/fde919fc-dc98-11e5-8b42-fca8fb6054c4.png)

<pre>
 dpkg -l | grep -i rocket
ii  rocketchat      1.0.0   amd64        Rocket.Chat Native Cross-Platform Desktop Application via Electron.
</pre>
