### ISSUE TITLE
Automatic reload causes issues with multi-server set up

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat.Electron#1110]
## My Setup
- Operating System: Windows 10 Pro 1809
- App Version: 2.15.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When the client is in a multi-server setup, and one of the servers is unavailable, the application tries to automatically reload. This causes a problem, because I may be on another server, having a conversation, and my client automatically refreshes, sending me back to the home page for the server.

### Current Behavior
App refreshes automatically, regardless of which server you are currently on, sending me to the home page and interrupting my conversation.

### Expected Behavior
Unavailable server should either reload in the background, or be only reloaded manually (which seems it was the original behavior).

![image](https://user-images.githubusercontent.com/14616851/53416109-655e4580-3998-11e9-86bf-d001346a1e83.png)
![image](https://user-images.githubusercontent.com/14616851/53416121-6b542680-3998-11e9-91c9-3ab04ad76d6a.png)
![image](https://user-images.githubusercontent.com/14616851/53416138-70b17100-3998-11e9-92e8-26b5a25b2544.png)
![image](https://user-images.githubusercontent.com/14616851/53416150-7444f800-3998-11e9-8e88-2ffece9954c2.png)

**Comment by KhinNoe** [comment]
I'm also facing this issue on my multiple instances. How did you solve it please?
