### ISSUE TITLE
The Away detection works only in Electron App

### ISSUE THREAD

**Issue by w4andy** [RocketChat/Rocket.Chat.Electron#1111]
## My Setup
- Operating System: macOS 10.14.3
- App Version: 2.15.0
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The Away recognition only works in the Electron App, if I work with another application I will be set to away in the Rocket.Chat App.

I have now installed v2.14.7 again, it does not have this bug.

**Comment by tassoevan** [comment]
The way we detect the user presence changed to match how we do on the browser-based client because some users found it confusing to have two different ways to automatically go away. I'd like to suggest you to check your configuration in `My Account > Preferences > User presence > Enable Auto Away`.

**Comment by tb0wn** [comment]
Can you make away behavior selectable in the admin interface, app away vs system away?  This new behavior does not work for our environment.

**Comment by ixlandia** [comment]
Please reconsider this change. I understand that you cannot detect system-level presence in the browser client, but that's part of the reason I'm using the electron client.
Due to this change, within 5 minutes of not chatting with anyone, I'm getting notified of every message by the mobile client and an e-mail. The only alternative I have right now is turning off auto-away altogether and changing it manually. Kinda defeats the purpose of the feature...

**Comment by tb0wn** [comment]
was #1124 to revert 2.15.x back to the 2.14.x behavior?  or are we out of luck getting that behavior  back?  my company only uses electron and system-away is a required setting.

**Comment by stleitner** [comment]
The OSX App Store Version 2.15.1 does not solve the problem. The status is switching from green to yellow within seconds. We had to revert back to 2.14.x

**Comment by tassoevan** [comment]
@stleitner Is `My Account > Preferences > User presence > Enable Auto Away` enabled?

**Comment by stleitner** [comment]
I'm not 100% sure because we tried a lot to change the settings. Most likely it was disabled

**Comment by krispayne** [comment]
I updated to Mac App Store 2.15.1 this morning and stopped getting notifications forwarded to my iPhone, I went to check my auto away settings per this thread and they were set to disabled, whereas previously they were enabled.
