### ISSUE TITLE
Rocket.Chat Windows Electron Release Builds are not being signed automatically

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Electron#1112]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The latest Rocket.Chat electron builds for Windows are not being signed automatically.

### Current Behavior
```
b:\Downloads>sign-check rocketchat-setup-2.15.0.exe
File isn't signed!
```
![image](https://user-images.githubusercontent.com/6295044/53443804-7e87e600-39da-11e9-8598-09c13c391abb.png)
https://www.virustotal.com/#/file/3e639086da37381e40f76fbd98a4dba743879012e62dcc91bf397e8feb097b50/details

## Other Info
We are not able to push out Rocket.Chat updates automatically to machines because the files are not signed.

**Comment by wreiske** [comment]
Posting this just for the sake of documentation.

![image](https://user-images.githubusercontent.com/6295044/54332432-7fcd2b80-45f4-11e9-9337-89abc3092b3b.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
