### ISSUE TITLE
Windows Defender SmartScreen prevented the start of "rocketchat-setup-2.15.0.exe"

### ISSUE THREAD

**Issue by schipplock** [RocketChat/Rocket.Chat.Electron#1116]
## My Setup
- Operating System: Microsoft Windows 10 Enterprise 2016 LTSB (1607)
- App Version: 2.15.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

I have just downloaded the rocketchat-setup-2.15.0.exe from https://rocket.chat/install and tried to execute it; however, Windows Defender SmartScreen prevented me from doing so. "Is this legit?" was my first reaction :). I really can't tell right now. Are there checkums you can provide? Thanks in advance.

### Current Behavior

The setup doesn't start.

### Expected Behavior

The setup should start.

**Comment by tassoevan** [comment]
Maybe related to #721 and #1112.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
