### ISSUE TITLE
System tray icon not showing up

### ISSUE THREAD

**Issue by phlegx** [RocketChat/Rocket.Chat.Electron#1118]
## My Setup
- Operating System: Ubuntu 16.04 LTS
- App Version: 2.15.0
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The RC icon in the system tray does not appear anymore since last release. 

Also with this version it does not seem to work.

### Current Behavior
System tray icon does not appear

### Expected Behavior
System tray icon should be shown

**Comment by tassoevan** [comment]
Is it enabled at menu `View > Tray icon`? It is disabled by default on the Linux platform.

**Comment by phlegx** [comment]
It was indeed disabled. Thanks so much!

Has this changed one version before? Since I cannot remember to have removed this flag and it was working until I upgraded to the previous version.

**Comment by tassoevan** [comment]
@phlegx Yes. If you have not set it, you're running under a default value changed in version 2.14.0, because we can't detect if a desktop environment support tray/notification icons (e.g. Gnome on Ubuntu) or not (Gnome on Fedora).
