### ISSUE TITLE
Test Desktop Notifications - Does not work

### ISSUE THREAD

**Issue by giray** [RocketChat/Rocket.Chat.Electron#112]
Going into My Account -> Preferences and pushing the "TEST DESKTOP NOTIFICATION" does not do anything.  v 1.0.0

**Comment by engelgabriel** [comment]
What OS?

**Comment by giray** [comment]
Ubuntu 15.10

**Comment by giray** [comment]
Turns out I was using v 1.0.0 beta 2; fixed in v1.0.0
