### ISSUE TITLE
RocketChat 2.15.0 - Fullscreen button for sent videos no longer functions.

### ISSUE THREAD

**Issue by Enz-Support** [RocketChat/Rocket.Chat.Electron#1120]
## My Setup
- Operating System: Win10
- App Version: 2.15.0
- Installation type: Desktop application updated to most recent version

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When sending a video in a group chat or direct message, the button to put the video in fullscreen no longer works. This appears to be a new issue with the most recent update.
This does not affect the browser version.

### Current Behavior
Fullscreen button no longer functions on shared videos.

### Expected Behavior
Fullscreen button functions for shared videos.

**Comment by tassoevan** [comment]
It's a bug on Electron 4: https://github.com/electron/electron/issues/16648

**Comment by DenisAraujo68** [comment]
Fullscreen to video and pictures don't work yet.
RocketChat Desktop 2.15.5 (for Linux, via snap).
RocketChat Server 1.1.3

Interestingly, it works normally on Firefox and Chrome.

**Comment by tassoevan** [comment]
It seems to be working after upgrade to Electron 10.
