### ISSUE TITLE
Failed desktop upgrade locks out account data - Enter E2E password to decode your key

### ISSUE THREAD

**Issue by jmason90** [RocketChat/Rocket.Chat.Electron#1127]
## My Setup
- Operating System:  Windows 10
- App Version:  2.14.7
- Installation type:   Client desktop app 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

The automatic Rocketchat upgrade failed on 3/3/19.
There is no recovery that I can find.
I know I can't access the leveldb database since it deleted my credentials on the upgrade 
I now can't get past this message: 
   Enter E2E password to decode your key
  It won't accept my account password to unlock my data
I have the app running ok on my Mobile device.
How do I recover my identity and data on Windows 10 so I can use the desktop app with my existing history???

### Current Behavior

see above 
Here's the failed LOG from the upgrade ..

rocketchat log from 3/3 on upgrade ...
2019/03/03-22:38:11.477 17380 Reusing MANIFEST leveldb/MANIFEST-000001
2019/03/03-22:38:11.478 17380 Recovering log #17
2019/03/03-22:38:11.480 17380 Reusing old log leveldb/000017.log 

wiped out account access !!

### Expected Behavior

All past rocketchat upgrades did not fail.
never hit this scenario before and can't recover from it

**Comment by tassoevan** [comment]
I'm not sure about what have triggered the issue, but it seems the upgrading Electron in this project corrupted some cache/application data... You need to ask one administrator of your server to reset your E2E password.

**Comment by jmason90** [comment]
Thanks but This is a local rocketchat install in Windows - no server.As the admin for my machine, I don't have a way to reset the e2e password.

    On Thursday, March 7, 2019, 9:27:11 AM EST, Tasso Evangelista <notifications@github.com> wrote:  
 
 
I'm not sure about what have triggered the issue, but it seems the upgrading Electron in this project corrupted some cache/application data... You need to ask one administrator of your server to reset your E2E password.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
