### ISSUE TITLE
development branch fails on npm install

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat.Electron#113]
Just tried to build the Rocket client and it fails when doing 
npm install

git clone gives "Permission denied (publickey).' "
If I change the electron-prebuilt setting in package.json to use https instead, then git clone will work

Failing
 "devDependencies": {
    "asar": "^0.7.2",
    "electron-prebuilt": "git@github.com:RocketChat/electron-prebuilt.git",
    "fs-jetpack": "^0.7.0",
    "gulp": "^3.9.0",

Working
  "devDependencies": {
    "asar": "^0.7.2",
    "electron-prebuilt": "https://github.com/RocketChat/electron-prebuilt.git",
    "fs-jetpack": "^0.7.0",
    "gulp": "^3.9.0",

Not sure if its a package.json error or if something is wrong on the github rep.

Happy Friday
Mathias

**Comment by rodrigok** [comment]
Can you try to replace this
`"electron-prebuilt": "git@github.com:RocketChat/electron-prebuilt.git",`

by this?
"electron-prebuilt": "https://github.com/RocketChat/electron-prebuilt.git",

**Comment by lunitic** [comment]
@rodrigok Exactly what i said the solution was is the ticket.. 

Then it works.. :+1:

**Comment by rodrigok** [comment]
Ohh, sorry, I didn't see.

I will fix that
