### ISSUE TITLE
macOS dock icon colors visually interferes with notification badges

### ISSUE THREAD

**Issue by maiksd** [RocketChat/Rocket.Chat.Electron#1136]
The rocket icon on macOS is currently white with red on the outside. Since the rocket is sideways, one of it's red legs is sticking out in the upper left corner, while notification badges will appear as a red circle in the upper right corner.

Especially when small icons are used in the dock, the app icon often looks confusingly similar to one that has an active notification badge on it when it doesn't, and vice versa a notification badge can easily be overlooked when one is there.

On iOS, the application icon can be changed to different color schemes. The same feature would solve this on macOS.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
