### ISSUE TITLE
notifications do not work

### ISSUE THREAD

**Issue by DariaAnt** [RocketChat/Rocket.Chat.Electron#1138]
No Notifications
## My Setup
- Operating System: windows server 2016
- App Version: 2.15.0
- Installation type: 

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

### Current Behavior
when messeges are sent, there's no notification about them

### Expected Behavior
notification pop-up or as in skype logo is highlighted and shows number of messages

**Comment by fzidarbbc** [comment]
Same here with v.2.15.0 on Win10 1809
"Test Desktop Notifications" -> no notification shows up

Desktop Notifications for Rocket.Chat are enabled in windows notification&actions settings.

**Comment by 9130khz** [comment]
Same behavior on v2.15.1
macOS 10.14.3

"Test Desktop Notifications" -> no notification shows up
Notifications are enabled in Notification Center

**Comment by IamDefiler** [comment]
Same issue with v2.15.1
macOS 10.14.3

**Comment by blackaeros** [comment]
I have same issue. v2.15.1
Linux -> windows 10 no notification shows up
Linux -> windows 7 notification show up
windows 7 -> Linux notification show up
windows 10 -> linux no notification shows up
windows 10 -> windows 7 no notification shows up

Downgade to v2.15.0 or v2.14.7 does not solve the problem.

**Comment by jcatarino** [comment]
Is there any update on this?

**Comment by reetp** [comment]
> Is there any update on this?

Check two things please:

1. Use the latest Electron client
https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.15.3

2. Test on latest Rocket.chat (currently 1.0.3)

**Comment by jcatarino** [comment]
I can confirm the problem occurs to me with Electron client 2.15.3 and server 1.0.3

**Comment by MSohm** [comment]
Also confirming this issue on 2.15.13 on Windows 10.
Nothing happens when pressing the "Test Desktop Notifications" button, nor am I getting any notifications from new chat messages.
Also using Rocket.Chat 1.0.3.

**Comment by DaleKramer** [comment]
I have Win10 2.15.3 on RocketChat server and cloud server and "Test Desktop Notifications" button works for both servers: 
![image](https://user-images.githubusercontent.com/7749699/57950344-fe746c80-78b4-11e9-889e-207baf0def31.png)

BUT I do not know if I will receive them 'in use' because I am still waiting for Threads 1.0 before I invite my Slack buddies to try RocketChat out ... ;)

**Comment by fzidarbbc** [comment]
Desktop notification test works for me now.
Win10 1809 Pro
RocketChat 2.15.3

**Comment by tassoevan** [comment]
I'll close this issue by now, but feel free to reopen it if this bug comes back.

**Comment by trig-ger** [comment]
No notifications for me.
Rocket Chat 2.17.7
Windows 10 Home 1909
Notifications are turned on, Focus Assist is turned off.
