### ISSUE TITLE
RC Electron  2.15.* not work in Debian 8

### ISSUE THREAD

**Issue by evant89** [RocketChat/Rocket.Chat.Electron#1142]
run command in terminal********  "/opt/Rocket.Chat/rocketchat-desktop" %U

/opt/Rocket.Chat/rocketchat-desktop: /lib/i386-linux-gnu/i686/cmov/libc.so.6: version `GLIBC_2.27' not found (required by /opt/Rocket.Chat/rocketchat-desktop)

/opt/Rocket.Chat/rocketchat-desktop: /lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by /opt/Rocket.Chat/rocketchat-desktop)

## My Setup
- Debian 8
- 2.15.0, 2.15.1 :

**Comment by tassoevan** [comment]
Looks like we did noticed that Electron dropped 32 bit support for Linux... https://electronjs.org/blog/linux-32bit-support

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
