### ISSUE TITLE
Copy/paste does not reliably work on Electron client

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat.Electron#1144]
## My Setup
- Operating System: Windows 10 Pro Build 1809
- App Version: 2.15.0
- Installation type: exe

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
It seems the copy/paste behavior does not work reliably when using the Electron client, even when using the context menu to expressly copy/paste text.

### Current Behavior
Nothing is copied, and the clipboard retains whatever was in the buffer before.

### Expected Behavior
The clipboard should consistently store what is copied from the app (message text, Administration info text, etc).

![ezgif-5-1f024b298217](https://user-images.githubusercontent.com/14616851/54354271-34cb0c80-4624-11e9-949a-fb93e84d20e4.gif)

**Comment by wreiske** [comment]
This is killing us, as well.

**Comment by dj301** [comment]
Same issue here.

**Comment by wreiske** [comment]
![AI7GEynV0w](https://user-images.githubusercontent.com/6295044/57553820-b3e77300-733d-11e9-88ba-d162cab1fbda.gif)

**Comment by tassoevan** [comment]
Thanks to @wreiske's information I've found the root cause: there is a serious bug on recent Electron versions related to `<webview>` tag focus where all views remain focused while the actions are only applied to the first one. I'm experimenting a little, trying to find a reliable workaround.

**Comment by tassoevan** [comment]
This doesn't seem to be a problem anymore. Could you confirm @bkraul and @wreiske?

**Comment by bkraul** [comment]
No. Still does not work on 2.16.2 (with 2.3.0-develop server).

**Comment by AlenaVorobiova** [comment]
I have the same issue on 2.17.7

**Comment by tassoevan** [comment]
It seems to have been fixed after updating Electron to v10.
