### ISSUE TITLE
Window size changes when new message arrives

### ISSUE THREAD

**Issue by t3chm4n** [RocketChat/Rocket.Chat.Electron#1145]
## My Setup
- Operating System: windows 10 pro
- App Version: 15.1 (15.0 também acontecia)
- Installation type: 

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

### Current Behavior

Não importa o que eu faço, sempre o rocket.chat fica preso num tamanho de janela pequeno, e eu gostaria de mantê-lo maximizado. Eu maximizo, alterno para outra janela, ele volta a ficar pequeno.
Eu tenho a impressão que acontece quando chega nova mensagem. Por exemplo, está maximizado, troco de janela, volto, continua maximizado. Tudo ok.
Mas aí está maximizado, troco de janela, recebo uma nova mensagem, quando vou para a janela do rocket está pequena novamente.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
