### ISSUE TITLE
Language keeps resetting itself to en_US after update to 2.15.1

### ISSUE THREAD

**Issue by maiksd** [RocketChat/Rocket.Chat.Electron#1146]
## My Setup
- Operating System: macOS 10.14
- App Version: 2.15.1
- Installation type: MAS

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

### Current Behavior
After app restart, text entered is spellchecked against en_US always instead of the configured profile language, which leads to red underlined text all over the place.

Setting locale in profile settings is reverted back to "default" after save. When saving, the UI comes back in English even when that save was supposed to set it to German.

I think this is a regression in the latest MAS update.

### Expected Behavior
Locale is respected and can be set differently from default.
There should be a way to disable spellchecking entirely.

**Comment by StellaTeam** [comment]
Confirmed here
