### ISSUE TITLE
New Windows/Mac/Linux Client 2.15.1 automatic switch to away

### ISSUE THREAD

**Issue by Michelle011997** [RocketChat/Rocket.Chat.Electron#1147]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.1
- Installation type: rocketchat-setup-2.15.1.exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
New Windows Client 2.15.1 switch automatic to away also when you have disabled it in account settings.

2.15.0 does not have this issue. So i switched back to this version and it works.

For testing i update again and same issue like before.
App switch automatic to away (yellow dot)

**Comment by phillipplum** [comment]
The problem also exists under macOS in version 2.15.1.

**Comment by icerootsvw** [comment]
This happens also on Linux Version 2.15.1

**Comment by bkraul** [comment]
Happening on Windows 10 1809. Thought it was the server, but seems it is the client. As a result countless push notification messages get sent to my mobile device. Might want to watch this, as once the push notification gateway pricing plans kick in, this could land us in some real trouble.

**Comment by Maqsyo** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/issues/731

I think i had a similiar problem in this issue. Maybe you could give it a try

**Comment by bkraul** [comment]
@tassoevan, so is this going to come on 2.15.2 or 2.16?

**Comment by tassoevan** [comment]
@bkraul 2.15.2.
