### ISSUE TITLE
Refactor tray functionality

### ISSUE THREAD

**Issue by floriangoeldi** [RocketChat/Rocket.Chat.Electron#115]
With @rodrigok agreed I open this issue to have a place for the discussion about the tray functionality of the application.

From my point of view - as windows user ;) - the following functionalities are kinda necessary:
- [x] Double click to toggle the application (on all plattforms)
- [x] Shouldn't crash anymore #109
- [ ] Number of mentions on the tray icon on all plattforms

And these menu points:
- Show (first item in the list) <- Do we even need this?
- Quit (last item in the list)
##

**Comment by rodrigok** [comment]
IMHO we need a list of servers in the menu, with the number of mentions for each entry.

@RocketChat/core what do you think?

**Comment by geekgonecrazy** [comment]
I think that would be very nice to have :+1: An over all count would be nice as well on the tray icon its self.

**Comment by rodrigok** [comment]
We have the total count of mentions beside the OS X "tray" icon, this is not possible for linux and windows I guess.

**Comment by floriangoeldi** [comment]
If the mentions are in the server list it should be possible not?
That the mentions are on the tray icon, like skype has it, would also be nice:

https://az545065.vo.msecnd.net/skype-faq-media/faq_content/skype/screenshots/fa11055/fa11055_2.png

But how they do it is the next question.

**Comment by rodrigok** [comment]
Probably they have 10 icons with numbers.

We show the mentions number in OS X
![captura de tela 2016-02-26 as 19 21 31](https://cloud.githubusercontent.com/assets/234261/13367086/56b40536-dcbe-11e5-8b82-995ec7443d9b.png)

**Comment by geekgonecrazy** [comment]
Maybe they actually swap out the tray icon and draw the numbers on it?  This would be my guess.

https://github.com/atom/electron/blob/master/docs/api/tray.md#traysetimageimage

On OSX they have a method called set Title, that makes it pretty easy to put text next to it.

**Comment by floriangoeldi** [comment]
This setOverlayIcon seems like the way to go?

The images with just numbers shouldn't be a problem, maybe like 1-9 and then something like a "more than 10" image?

I have added this to the checklist :+1:

**Comment by rodrigok** [comment]
@floriangoeldi the `setOveralyIcon` is for the taskbar item, not for the tray, but we can do that too.

For the tray, yes, `1`-`9` and `9+`

**Comment by engelgabriel** [comment]
@rodrigok and @floriangoeldi  Is this all working now on version 2.2.0?

**Comment by rodrigok** [comment]
@engelgabriel Which part?

**Comment by kkachura** [comment]
"Number of mentions on the tray icon on all plattforms" - not work on Windows

**Comment by monspid** [comment]
Cannnot we use just 12 pictures? One when we don't have any message, one with a dot for not direct messages, then nine with 1 to 9 numbers and at the end with 9+ for ditect messages. I have a code doing it, but the problem is that icons look poor. Can anyone make a nice looking tamplate?
![preview](https://cloud.githubusercontent.com/assets/18348137/23363812/c554fae0-fcfc-11e6-9d5f-4a24947cffb1.PNG)

**Comment by rodrigok** [comment]
@monspid Yes, we can use what you suggested. Can you open a PR? Then we can improve the icons later.

**Comment by jasonfah** [comment]
Is there any intention to put the unread count on the **taskbar** icon? Similar to Skype. (not talking about the system tray icon - that works fine)
