### ISSUE TITLE
fix small (not visible)  numbers for unread message on tray icon 

### ISSUE THREAD

**Issue by tendo256** [RocketChat/Rocket.Chat.Electron#1150]
## My Setup
- Operating System: elementary OS 5.0 Juno
- App Version: 2.15.1
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The unread messages number counter displays too small numbers which are not easily seen

### Current Behavior
http://i.imgur.com/Z8p7LnV.png

### Expected Behavior
Should show visible numbers (big numbers)

**Comment by tassoevan** [comment]
It's not possible to control tray icon appearance with respect to its display size on Linux platforms now, nor scale the indicator counter without subverting Rocket.Chat logo.
