### ISSUE TITLE
"Update Available" in 2.15.0: "INSTALL UPDATE" button doesn't seem to work

### ISSUE THREAD

**Issue by schipplock** [RocketChat/Rocket.Chat.Electron#1151]
## My Setup
- Operating System: Microsoft Windows 10 Enterprise 2016 LTSB (1607)
- App Version: 2.15.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Today rocketchat popped up a dialog informing me that there is an update available and ready to be installed. 

**It is showing me the following screen:**

![rocketchat-2 15 0-update-not-working](https://user-images.githubusercontent.com/49938/54518469-a11b7800-4964-11e9-9ec7-206563d489da.png)

I am clicking the "INSTALL UPDATE" button but nothing is happening. I clicked it again but it still didn't work. I brought up the main rocketchat window and inside the "Update Available" window I clicked "Toggle DevTools" however there's nothing logged there.

I noticed the "REMIND ME LATER" button doesn't do anything useful either. Nothing happens when I click it.

### Current Behavior

The button "INSTALL UPDATE" doesn't seem to do anything useful.

### Expected Behavior

The update should be downloaded and installed. Thanks in advance for looking into it.

**Comment by schipplock** [comment]
I'm sorry, this is a dupe of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1141.

**Comment by inon-peled** [comment]
Had the same problem with version 2.15.0, so I manually downloaded and installed version 2.15.1.
