### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by PabloHorno** [RocketChat/Rocket.Chat.Electron#1154]
## My Setup
- Operating System: Windows 10
- App Version: 
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Notifications on desktop or android still alive even when message is readed

### Current Behavior
When I recive a notification of an incoming chat and I open an read the messesage, the android app shows notification of the message even if it is already readed

### Expected Behavior
Clear notifications if readed in desktop or mobile

**Comment by PabloHorno** [comment]
Added App verswion

**Comment by tassoevan** [comment]
@PabloHorno Is this happening in which versions of server and desktop app?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
