### ISSUE TITLE
Add Download progress bar

### ISSUE THREAD

**Issue by abugandar** [RocketChat/Rocket.Chat.Electron#1155]
Where it can be seen the download progress bar?
if i am downloading multi-files how i can check if the download tasks all finished
and how i can resume or cancel download tasks ?

You need to add  Downloads Manager with thus options :+1: 
1-Download progress bar  (client)
2-Resume / Pause /Cancel option (client/Server)
3-History downloaded Files (client/Server)

**Comment by shinebayar-g** [comment]
This is much needed feature, when sending files over rocketchat, user need to know their download is finished or not.

**Comment by HappyTobi** [comment]
There is already a pr see: https://github.com/RocketChat/Rocket.Chat.Electron/pull/1180

Think they restructure many things internal thats the reason why you have to wait
