### ISSUE TITLE
Spinning Hourglass Instead of Unread Messages

### ISSUE THREAD

**Issue by Patrickh60** [RocketChat/Rocket.Chat.Electron#1156]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.1
- Installation type:  exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
 There was an indicator on the app system tray icon that I have unread messages.  Attempting to start the app leaves me with three dots flashing on & off.  An hourglass essentially.  Nothing is happening.

### Expected Behavior
 I expect the app to open and show me unread messages.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
