### ISSUE TITLE
Spellchecking not working when using multiple languages

### ISSUE THREAD

**Issue by dscheffer** [RocketChat/Rocket.Chat.Electron#1158]
## My Setup
- Operating System: macOS
- App Version: 2.15.0
- Installation type: dmg

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When choosing multiple spell checking languages every word is displayed as an error regardless of the language.
<img width="263" alt="Screen Shot 2019-03-25 at 15 02 20" src="https://user-images.githubusercontent.com/3116544/54925921-938b6280-4f0f-11e9-9609-b85ed16abe96.png">

I used this language configuration for reproducing this issue:
<img width="400" alt="Screen Shot 2019-03-25 at 15 01 15" src="https://user-images.githubusercontent.com/3116544/54926135-ff6dcb00-4f0f-11e9-9885-8ed7152bf2df.png">
 

### Current Behavior
Every word is displayed with red underline.

### Expected Behavior
Correct spelling of either language should be accepted.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
