### ISSUE TITLE
No User Interface visible on v2.15.1

### ISSUE THREAD

**Issue by cheffr** [RocketChat/Rocket.Chat.Electron#1161]
### Actual behavior:

![image](https://user-images.githubusercontent.com/48556334/54875960-6f7c3400-4dde-11e9-9df0-5efada9852f0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Win10
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by geekgonecrazy** [comment]
Transferred to appropriate repo

**Comment by alireza-salehi** [comment]
i can confirm the problem on version 2.15.2, 2.15.1 on Win10/x64/1809.

**Comment by franckadil** [comment]
Hi,
I had a similar problem with a colleague, and it turned out that his app was launching in the taskbar, and he didn't pay attention to that. @alireza-salehi please can you test ?

I was also able to test successfully:
>  Right-click a blank area of the task-bar, then select **Cascade windows**

**Comment by alireza-salehi** [comment]
> Hi,
> I had a similar problem with a colleague, and it turned out that his app was launching in the taskbar, and he didn't pay attention to that. @alireza-salehi please can you test ?
> 
> I was also able to test successfully:
> 
> > Right-click a blank area of the task-bar, then select **Cascade windows**

Hi , i can see multiple instances in Task manager but no Tray icon or no icon  on Taskbar, it is running in background. no user interface.

**Comment by cheffr** [comment]
Unfortunately cascasding the windows from the empty area of the taskbar does not help me.
I have RocketChat pinned to my taskbar, and I can see it initiate when I click it, and I can then find 5 instances of RocketChat in my TaskManager processes list, but unless I open a browser window and put in the URL I cannot see the RocketChat interface.  the rocketChat application is not displaying an interface (even trying to cascade the windows).




Robert

Robert Cheffcell 609.649.2372
 

    On Monday, April 29, 2019, 9:03:51 AM EDT, Alireza Salehi <notifications@github.com> wrote:  
 
 

Hi,
I had a similar problem with a colleague, and it turned out that his app was launching in the taskbar, and he didn't pay attention to that. @alireza-salehi please can you test ?

I was also able to test successfully:


Right-click a blank area of the task-bar, then select Cascade windows



Hi , i can see multiple instances in Task manager but no Tray icon or no icon on Taskbar, it is running in background. no user interface.

**Comment by alireza-salehi** [comment]
upgraded to version 2.15.3 , issue not present,
minimizing to taskbar and re-openning again, no problem.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
