### ISSUE TITLE
Online / away status bug

### ISSUE THREAD

**Issue by metaer** [RocketChat/Rocket.Chat.Electron#1165]
When logged in to the same account in Android app and in macOS desktop app - online status change from online to away automatically in macOS app. And when I set online, in few seconds it changes to away. And I manually change several times to online to set online status. This occurres not always. I can not track yet what cause this issue.

macOS 10.14.4
Rocket chat 2.15.1

**Comment by bkraul** [comment]
This is likely linked to #1147

**Comment by tassoevan** [comment]
Yes, it's a duplicate of #1147
