### ISSUE TITLE
Cursor not displayed and non-ASCII not entered if mac OS DPI not default

### ISSUE THREAD

**Issue by entonio** [RocketChat/Rocket.Chat.Electron#1166]
## My Setup
- Operating System: macOS 10.14
- App Version: 2.15.0
- Installation type: brew

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
- Set display resolution to 'Bigger text' (or anything larger than Default)
- Start Rocket.Chat

### Current Behavior
- The cursor is not shown
- Accented characters are not input, tho they can be pasted

IF display resolution is changed to default with RC open, then the issue goes away, and things works even after setting it back to non-default. After restarting RC, the issue comes back.

### Expected Behavior
- Cursor should be visible
- Keyboard input should work

**Comment by sakoula** [comment]
hi there, I am having the same problem. Any update on this?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
