### ISSUE TITLE
Add "OneClickURL"

### ISSUE THREAD

**Issue by ImmoWave** [RocketChat/Rocket.Chat.Electron#1170]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.1
- Installation type: exe

Hello there. Could you add a choice of clicks by URL links, i mean one left click to open site. 
I think this function can be added to settings, where user can select better one for him(eg Use quick open by LeftClick : true/false). I find it very useful

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
