### ISSUE TITLE
Zoom in/out feature only apply to the first server in the list

### ISSUE THREAD

**Issue by ktran-skilld** [RocketChat/Rocket.Chat.Electron#1171]
## My Setup
- Operating System: Fedora 29 (5.0.4-200.fc29.x86_64)
- App Version: 2.15.1
- Installation type: RPM file

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
With several servers connected, while using the zoom in/out feature (View > Zoom in/out), the zoom setting is only applied to the first server in the list.

### Current Behavior
* Using the zoom feature works normally on the first server's tab but is not applied on the others
* Using the zoom feature while displaying another server tab than the first does nothing for it, but still correctly apply it on the first server

### Expected Behavior
The zoom is applied all the same for all server tabs.

**Comment by winterz** [comment]
I also use Fedora 29.  I tried version 2.15.3  and zooming works for me only on the 3rd server in my list of 4 servers.  is there a way to hand-edit the Preferences file to get a larger font?

**Comment by DaleKramer** [comment]
This also an issue on Win10 , App version 2.15.3 with just 2 servers.

Only the top server zooms when zoom keys used in second server....

**Comment by 73** [comment]
duplicate of #1246?

**Comment by iadenisov** [comment]
Reproduces in 2.17.11  on Linux Mint 19.3

**Comment by corrigac** [comment]
Reproduces on app store installed version 2.17.9 on Mac Catalina 10.15.6

**Comment by tassoevan** [comment]
It's working right at 3.0.4.
