### ISSUE TITLE
Undo with "⌘ + Z" keyboard shortcut doesn't work anymore

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.Electron#1177]
## My Setup
- Operating System: macOS 10.14.4
- App Version: 2.15.2
- Installation type: DMG

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

Try to <kbd>CMD + Z</kbd> to undo changes in the composer/editor textarea. This has no affect anymore since one of the past updates.

### Current Behavior

Nothing.

### Expected Behavior

Undo the last change.

**Comment by s3lcsum** [comment]
I have the same OS and I've checked it on latest release (AppStore) and branch master (by yarn).

It's not only for keyboard shortcut but for entire function. If you choose "Undo" option from "Edit" menu at the top bar, it also has no effect.
