### ISSUE TITLE
Desktop notifications wont work even with new install

### ISSUE THREAD

**Issue by TonOfFun** [RocketChat/Rocket.Chat.Electron#1178]
## My Setup
- Operating System: Win 10
- App Version: 2.15.1 and tried all version past 6months
- Installation type:  exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

I'm a member of one hobby group where timely desktop alerts are very important. Desktop notifications stopped working 6months ago, settings doesn't help, updates doesn't help, different chat channels doesn't make any difference. I don't get @here or @all notifications. Task bar turns to orange but no sound or popup. I have checked windows settings and allowed all notifications. My SSD died and I MADE FRESH WIN 10 INSTALL with latest app versions and updates but still no luck. What can I do?

### Current Behavior

No sound or pop-up alert, task bar turns to orange. From user settings, test notification button works and gives me pop-up. Earlier with old versions, this didn't work (if it gives any clue for solution).

### Expected Behavior

Pop-up alert with sound when @here is mentioned in my channel.

Attached is image of settings bar: ![image](https://user-images.githubusercontent.com/49494915/55904417-71186b00-5bd8-11e9-801d-bdeed3c4bd00.png)

**Comment by alireza-salehi** [comment]
same issue:
App Version : 2.15.1
Windows 10 / 1809 Build 17763.404

i can confirm that when i click on "Test Desktop Notification" a notification will show but no other notification, notifications doesn't work anymore.

**Comment by rabbithats** [comment]
Can confirm - we have a number of users who aren't getting audio notifications (consistently, anyway).  Total re-installation after removing Electron seem to work on a very temporary basis.  

macOS desktop/laptop/mobile platforms seem to be most affected.

**Comment by jcatarino** [comment]
Can confirm. A lot of users are complaining about this.

**Comment by jcatarino** [comment]
Similar issues #1058 and #1138

**Comment by lewisgeorge-innoscale** [comment]
I can say we are having this issue too. It started with the last couple of updates. I didn't update between the first 2.13.x and the latest, then updated and have the issue. I have my whole team also reporting similar issues, across Windows, Linux, and Mac systems. Almost nobody is getting notifications at all and it is actually killing productivity. Not sure what info could help. Not really a desktop application developer. I have at least a dozen reports of this issue from my staff.

**Comment by alireza-salehi** [comment]
on version 2.15.0 , 2.15.1 , 2.15.2 we do not have notification, it seems that this problem appears from time to time.

**Comment by tassoevan** [comment]
@rabbithats Mobile platforms depend exclusively on Push notifications, configured on server.

**Comment by rabbithats** [comment]
> @rabbithats Mobile platforms depend exclusively on Push notifications, configured on server.

Right, our admins are working with our rocketchat server to tackle those particular issues.  I should've specified that our users with notification issues are exclusively Desktop/Laptop, v2.15.1.   

We're updating users to v2.15.2, but it's too early to tell if there are positive returns, plus silence can sometimes be a sign of normal function, so we'll see.

**Comment by c1hd** [comment]
No notifications on **some** Windows 10 Pro clients.
RocketChat-electron: 2.15.0; 2.15.1; 2.15.2;
Server: 0.74.0

Few users reported that they are not getting notifications after update from 2.14.7 to 2.15.1. I updated to 2.15.2 on one of the computers but it didn't help - still no notifications.
I had to downgrade client to 2.14.7 (with removing user data).

I discovered that on fresh Windows 10 install and RocketChat v2.15.2 notifications are working like a charm.

**Comment by franckadil** [comment]
@c1hd did you tried manually removing the user files when upgrading to 2.15.2 on the problematic computers ?

Thanks

**Comment by c1hd** [comment]
@franckadil unfortunately not, but I think it could work (everything works on fresh install, so problem might be there). We just ran script through GPO to install 2.14.7 silently - I think it doesn't remove user files, but since we downgraded no problems were reported.

**Comment by franckadil** [comment]
@c1hd Thank you, a ticket have been reopened I hope this gets fixed son, I'll do some testing.
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1195#event-2305672308
