### ISSUE TITLE
Missing stylesheets in desktop and web apps?

### ISSUE THREAD

**Issue by msanchezc** [RocketChat/Rocket.Chat.Electron#1179]
## My Setup
- Operating System: macOS 10.14.3
- App Version: 2.15.1
- Installation type: App Store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

This is what I see when I login both on the desktop app and the web app. I'm using the trial for the Cloud version.

![Imgur](https://i.imgur.com/6zBc8G2.png)

### Current Behavior

The UI colors and fonts are looking weird, making it hard to read. I think maybe there are some stylesheets missing or messed up.

### Expected Behavior

I should see a nice UI, just like on the community server I've used before.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
