### ISSUE TITLE
Timestamp is off by -1 hour

### ISSUE THREAD

**Issue by busches** [RocketChat/Rocket.Chat.Electron#1181]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.1
- Installation type: exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When viewing Rocket.Chat in the Electron Desktop app, all timestamps are off by -1 hour. e.g. If it's 11:32 AM, I see everything as 10:32 AM. If I load the server in the browser, on the same computer, I correctly see it as 11:32.

### Current Behavior
Timestamps are off by -1 hour

### Expected Behavior
Timestamps use current computer time.

I have uninstalled/reinstalled. I checked remove user data and even manually removed `AppData/Roaming` before installing. The issue started around the time Daylight Savings time went into effect. I've also traveled to another timezone and the timestamps worked then, but reverted back to -1 once I returned to my normal timezone. No other users on this server have reported this issue.

**Comment by tassoevan** [comment]
May I ask you in which timezone you are?

**Comment by busches** [comment]
Central Daylight Time. GMT-5.

**Comment by paulopera** [comment]
We are having the same issue with the macOS App V 2.16.0 but in the web app the hour is correct at least in Chrome. It shows +1 hour and our timezone is GMT-3.

**Comment by tassoevan** [comment]
@paulopera The origin of this bug lies on Node: https://github.com/nodejs/node/issues/30211
It's affecting all Electron-based apps (including desktop apps for Slack, Discord, Mattermost etc.) and there is no known workaround for now. We'll patch our app as soon as there is a fix for it.

**Comment by paulopera** [comment]
@tassoevan Thanks for reaching out and hope they could fix the problem.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
