### ISSUE TITLE
Unable to close windows application

### ISSUE THREAD

**Issue by msrost** [RocketChat/Rocket.Chat.Electron#1182]
## My Setup
- Operating System: Windows 10 Pro x64
- App Version: 2.15.1
- Installation type: Windows EXE

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

When i click on the X to close the window it just minimizes to the taskbar. when i right click on the taskbar and select close it does nothing. the rocket.chat icon is no longer in the system tray. the only way to stop the program is to force close with task manager. 

### Current Behavior

i can't close the program a normal way

### Expected Behavior

that i can close the program in a normal way

**Comment by tassoevan** [comment]
Enable tray icon via menu `View > Tray icon`.

**Comment by catdad** [comment]
I am not sure that the tray icon menu is a solution. When I close the application, I want it to stop running. I cannot accomplish that, tray menu or not, without force closing from task manager. Is there really no way to quit the application?
