### ISSUE TITLE
Yarn Release Error

### ISSUE THREAD

**Issue by premanandmanimaran** [RocketChat/Rocket.Chat.Electron#1184]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.1
- Installation type: Package

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Following the Packaging Instruction for Windows in the ReadMe. 
When running Yarn Release ( to Package the Application) in Windows, 
I get the following Error

 at process._tickCallback (internal/process/next_tick.js:61:11)
[13:51:39] 'release' errored after 1.42 min
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

I see the Dist folder is created and inside win-unpacked and the Application file is available.

When i copy and run the Application file in another Windows 10 ( with similar configuration) , i get 
"Code execution cannot proceed because ffmpeg.dll not found."

Can somebody help?

Thanks

Prem

**Comment by tassoevan** [comment]
Some errors are expected to be logged during `yarn release` because it not only builds the application as well publishes it in this repository if you have access to it. You cannot copy the generated `*.exe` only: all the files under `win-unpacked` folder are needed.
