### ISSUE TITLE
change my name

### ISSUE THREAD

**Issue by EnzoBAILLON** [RocketChat/Rocket.Chat.Electron#1185]
## Description
Hello, my name is Enzo BAILLON, but on Rocket Chat, I have Enzo Vincent BAILLON.
Could you just remove Vincent ?

**Comment by tassoevan** [comment]
This issue tracker is reserved for bug reports. Please check our forum (https://forums.rocket.chat/c/community-support) and community support channel (https://open.rocket.chat/channel/support) for help.
