### ISSUE TITLE
Unable to create Windows Application Installer

### ISSUE THREAD

**Issue by premanandmanimaran** [RocketChat/Rocket.Chat.Electron#1186]
Operating system : Windows 10
Current version downloaded from this git

When i try to rebuild after changing package.json ( Name, Productname) , app.html ( Title name) and changing the Images ( inside build, src/icon, public) "yarn" shows " win32 uncompatible error" , when run "yarn start" all good , when i run "yarn test" all good, "yarn e2e" shows "assertion error" and when i run "yarn release" only win-unpacked folder is created and following files and folders are not created win-ia32-unpacked , rocketchat-setup-2.16.0-develop.exe.blockmap, rocketchat-setup-2.16.0-develop.exe

**Comment by pcm211** [comment]
Try using win32 OS and do the same it compiles perfectly

**Comment by cygnusm** [comment]
use powershell instead of cmd, I think it 's better

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
