### ISSUE TITLE
[OS X] Spell checking language not autodetecting

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat.Electron#119]
The built in spell checking on OS X automatically detects the typed language among the configured system input languages. This doesn't seem to work in the message input field inside the OS X desktop app.

**Comment by rodrigok** [comment]
Do you have some idea how to do that?

**Comment by ulope** [comment]
No, sorry. In "normal" OS X applications "it just works" (i.e. it's a feature of the text input controls provided by the system)

**Comment by rodrigok** [comment]
Sure, but isn't the case in Electron application, we should implement this our selfs.

I will try to improve that.

**Comment by rodrigok** [comment]
I can't auto detect all the system languages, so I added an option to enable which languages you want via context menu.
