### ISSUE TITLE
Notification pop ups are visible even when Windows user is locked out

### ISSUE THREAD

**Issue by cptdustmite** [RocketChat/Rocket.Chat.Electron#1190]
## My Setup
- Operating System: Windows 10 64bit
- App Version: 2.14.6
- Installation type: exe, on premise installation

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When the Windows user is locked out (i.e. in the login screen), Rocket.chat notifications still pop up. This means that any person passing by or looking at the screen can see potentially sensitive messages being sent, while the computer is locked out.

### Current Behavior
Rocket.chat notification pop ups are visible even when the Windows user is locked out.

### Expected Behavior
Rocket.chat notification pop ups should not be visible when the Windows user is locked out.

**Comment by franckadil** [comment]
I think this is a normal behavior for apps on Windows 10. You can change this behavior, and even tailor it for specific apps as follow:

- https://support.microsoft.com/en-ph/help/4028678/windows-10-change-notification-settings
- https://winaero.com/blog/disable-lock-screen-notifications-windows-10/

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
