### ISSUE TITLE
Desktop App want start after update -> 2.15.2

### ISSUE THREAD

**Issue by nexidus** [RocketChat/Rocket.Chat.Electron#1191]
## My Setup
- Operating System: Windows 10 1809 (Build 17763.437) Tested on Notebook and Virtual Machines on a Proxmox Cluster on a network with Roaming User Profile
- App Version: 2.15.2
- Installation type: .exe, silent install

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Installed with GPO, copy the .exe on the Client and install it with a batch file, silent.

### Current Behavior
After installation, the desktopapp is only in the taskmanager. Cancle Task and restart the app dont work. No Icon at the clock, taskbar or otherwise. If i delete the rocketchat folder at %appdata% the app will start without problem.

**Comment by tassoevan** [comment]
@nexidus Did you update from which from version before 2.15.2?

**Comment by nexidus** [comment]
@tassoevan We updated from 2.15.1 -> 2.15.2

**Comment by northway** [comment]
+1 on Ubuntu Linux (18.04)

I updated with dpkg from 2.15.1 to 2.15.2 via the .deb file.

**Comment by tassoevan** [comment]
@northway Running it on terminal logs any kind of errors?

**Comment by northway** [comment]
No errors or warning. Just silently starts, but not showing any window or UI element.

Since then I upgraded to 19.04 if it matters.

**Comment by nexidus** [comment]
Additional information: We will roll it out as follows: Via GPO the setup file will be copied to the target computer and a CMD file will be executed: start "" c:\temp\rocketchat.exe /S /disableAutoUpdates

Until this update, this has always worked without problems, only since the update from 2.15.1 -> 2.15.2 Rocketchat then no longer opens, but only in the Task Manager. After deleting the Rocketchat folder in %appdata%, the launch of Rocketchat will work.


If you need more information about used server versions etc please ask for information.

**Comment by reini-1** [comment]
> No errors or warnings. Just silently starts, but not showing any window or UI element.
> 
> Since then I upgraded to 19.04 if it matters.

I had the same problem with Ubuntu 18.10 and 18.04. After deleting `~/.config/Rocker.Chat` directory, kill all rocket chat processes and start again, everything works fine.

**Comment by northway** [comment]
> I had the same problem with Ubuntu 18.10 and 18.04. After deleting `~/.config/Rocker.Chat` directory, kill all rocket chat processes and start again, everything works fine.
> I installed the amd64 debian package 2.15.2 from github.

It works, thx.

**Comment by reini-1** [comment]
> > I had the same problem with Ubuntu 18.10 and 18.04. After deleting `~/.config/Rocket.Chat` directory, kill all rocket chat processes and start again, everything works fine.
> > I installed the amd64 debian package 2.15.2 from github.
> 
> It works, thx.

Sorry but it did not work.
Everytime I quit and start Rocket Chat Desktop it hangs, so I have to do the same procedure again and again ...
I downgraded to 2.15.1 which did not have this problem.
I hope you can fix this problem in the next version.
Thanks in advance.

**Comment by tassoevan** [comment]
@reini-1 Could you please check if any errors are logged (`Window > Toggle DevTools > Console`) **before** quitting?

**Comment by nexidus** [comment]
I have updated now from 2.15.1 > 2.15.3 and the problem should be solved. I have tested it with to VMs und two users and one notebook with one user.

**Comment by reini-1** [comment]
> I have updated now from 2.15.1 > 2.15.3 and the problem should be solved. I have tested it with to VMs und two users and one notebook with one user.

On Ubuntu 18.04 it also seems to work with 2.15.3.

What was the problem?

**Comment by tassoevan** [comment]
It's possible that some dependency was broken; everything was upgraded on 2.15.3.
