### ISSUE TITLE
Server list don't show active servers on 2.15.2

### ISSUE THREAD

**Issue by dzienisz** [RocketChat/Rocket.Chat.Electron#1192]
## My Setup
- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

![Zrzut ekranu 2019-04-17 o 12 28 25](https://user-images.githubusercontent.com/3521624/56281223-62681180-610c-11e9-963f-15531cccd7a0.png)

### Current Behavior

I don't see active servers on 2.15.2

I clicked add and now I can't access my current server :(

**Comment by tassoevan** [comment]
@dzienisz Does `Window > Toggle DevTools > Console` show any errors?

**Comment by dzienisz** [comment]
![Zrzut ekranu 2019-04-17 o 16 47 51](https://user-images.githubusercontent.com/3521624/56297419-935a3d80-6130-11e9-8bd2-c7d8d5b78c4b.png)
