### ISSUE TITLE
Desktop notifications missing in Kubuntu

### ISSUE THREAD

**Issue by zalloy** [RocketChat/Rocket.Chat.Electron#1194]
I'm no longer receiving any desktop notifications, other than the test notification, when I get messages in RocketChat. I was using version 2.14.7, and tried installing 2.15.1 to see if it helped (it didn't) so I reverted it. 

Additionally, when I try to use emojis now, it isn't automatically suggesting any of our custom emojis, which is annoying, and there is also a scaling issue with the RocketChat indicator in my system tray when using 2.15.x. 

It is by far more annoying that I'm not getting notifications, as I have to keep scanning both of our RocketChat servers to check whether someone is trying to message me.

## My Setup
- Operating System: Kubuntu 18.10, KDE Plasma version 5.15.3 
- App Version: 2.14.7
- Installation type: deb package

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
See above

### Current Behavior
I am not receiving any desktop notifications, except for the test notification, for either of our RocketChat servers.

### Expected Behavior
I should receive desktop notifications when someone DMs me, mentions me in a channel, and for `@all` and `@here` mentions, as applicable.

**Comment by tassoevan** [comment]
Could you please test the recently released version 2.15.2? Also, what server version is running?

**Comment by zalloy** [comment]
I removed previous versions of the desktop app, and installed version 2.15.2. The scaling issue with the indicator is gone now, however I'm still not getting the notifications for messages. I get the red bubble on the indicator, but that's it. 

Our RocketChat servers are on version 0.71.1, and I've been bugging our DevOps person to upgrade those, but he's a little bit tied up atm.

**Comment by tassoevan** [comment]
After some tests, I can safely assume that something is wrong in your server setup. Please check our forum (https://forums.rocket.chat/c/community-support) and community support channel (https://open.rocket.chat/channel/support) for help.
