### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by giterium** [RocketChat/Rocket.Chat.Electron#1195]
I click update in the update window and nothing happens

## My Setup
- Win 7 x64
- 2.15.0
- exe

**Comment by dzienisz** [comment]
It's known bug. You need to update manually.

**Comment by giterium** [comment]
The update does not work for anyone?

**Comment by dzienisz** [comment]
only in this version, there was a bug

**Comment by giterium** [comment]
ok

**Comment by franckadil** [comment]
@giterium @dzienisz the updates seem to be broken in 2.15.2 too.

**Comment by Maqsyo** [comment]
@franckadil how do you know? i mean there wasn't an update for about 13 days, so the update dialog haven't shown up.

**Comment by giterium** [comment]
How to check the update in the latest version if when a new version is released the installed version becomes not the latest? :)

**Comment by Maqsyo** [comment]
@giterium what do you mean exactly?
There was a bug in v2.15.0 where the update-dialog doesn't work correctly.
So you have to update manually. Please find the correct package for your OS here: https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.15.2

**Comment by giterium** [comment]
In 2.15.1 the update works
