### ISSUE TITLE
Mouse pointer not scaled on hidpi displays

### ISSUE THREAD

**Issue by spldetatch** [RocketChat/Rocket.Chat.Electron#1199]
## My Setup
- Operating System: Ubuntu 18.04
- App Version: 2.15.2
- Installation type: Snappy

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
On hidpi displays, the mouse pointer is not scaled inside the app, making it difficult to see :)

### Current Behavior
Mouse pointer is not scaled on hidpi displays

### Expected Behavior
Mouse pointer should be saled on hidpi displays 

### Issue is discussed at
https://forum.snapcraft.io/t/rocket-chat-desktop-snap/222/29

### Proposed solution
Update package to use the latest snap core, and/or implement the following:
https://github.com/ubuntu/snapcraft-desktop-helpers/commit/da4d8f878eaeb40c1788789cd034b7142f7d6749

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
