### ISSUE TITLE
ability to change font size

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat.Electron#120]
It would be nice to have an option to increase/decrease **font size** for the app.

Having shortcut keys helping with that would be even better. :-)

**Comment by rodrigok** [comment]
We can try to enable the zoom like you do in web browsers. What do you think?

**Comment by rockneverdies55** [comment]
Since *zoom* changes the layout of the page too (everything on the page gets bigger and most of the time uglier), it's not ideal. 
But I guess it's better than nothing till we have an optimal solution.

**Comment by rodrigok** [comment]
Another option should be implemented in Rocket.Chat it self, so what we can do in Electron is enable the native zoom.

**Comment by willow9886** [comment]
Just to provide some quick steps to increase/decrease text size in the desktop app:

to increase: `ctrl` + `shift` + `+`

to decrease: `ctrl` + `-`

**Comment by Elendev** [comment]
Hello,

What if `ctrl` `shift` `+` doesn't work, is there an other way to do this on the settings ? ^^"

I'm on an Ubuntu 16.04 and the font of the chat app became really really small :-/

**Comment by Elendev** [comment]
> What if ctrl shift + doesn't work, is there an other way to do this on the settings ? ^^"

It looks like it's a mapping issue : I'm using a swiss-french keyboard and the `+` is on the `1`. I've tried with the `^` button and it did work well.

**Comment by dfaure-kdab** [comment]
I'm confused. I'm using rocketchat-2.17.2 (the desktop client, on Linux), and no amount of Ctrl + or Ctrl - changes the font size or zoom. I tried with and without shift (FR keyboard, the + is indeed accessible with "Shift ="), I also tried with the numerical keyboard. Has the feature been backed out since? Is it not available on Linux?

**Comment by jshumaker** [comment]
It works for me, also a View menu that has the same options.  However.. once you're a non-standard size I find scrolling all sorts of messed up.  When it shows someone is typing it scrolls, when they stop it doesn't scroll back the proper amount. Then auto-scroll gets disabled.  Effectively makes this solution not worth it.

**Comment by dfaure-kdab** [comment]
This issue should be reopened then, shouldn't it?

**Comment by jeanfbrito** [comment]
I think that this kind of stuff need to be implemented on Rocket.Chat side. The Electron is just a web client. You would need to increase font size on the Rocket.Chat web application to solve it even on browser. If this is an issue yet, of course.

**Comment by t-my** [comment]
nordic keyboard macOS: view -> zoom in/out or `cmd +` or `cmd -` does nothing. 
![image](https://user-images.githubusercontent.com/10090580/188877419-fd772726-ebcb-4deb-a7fa-1be969053475.png)

Is this broken?
