### ISSUE TITLE
Image drag & drop from Firefox into a Rocket channel does not work

### ISSUE THREAD

**Issue by reitzig** [RocketChat/Rocket.Chat.Electron#1208]
## My Setup
- Operating System: Ubuntu 18.04 LTS
- App Version: 2.15.3
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Drag an image file from Firefox (66.0.3 in my case) and drop it into a Rocket channel.

### Current Behavior
Nothing happens.

### Expected Behavior
File (or its URL) is sent to channel.

For reference: the browser app pastes the URL when the image is dropped onto the input textbox, and fails when dropped into the message list (cf. RocketChat/Rocket.Chat/issues/14358).

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
