### ISSUE TITLE
Cannot open the app after minimization to tray icon from start menu or pinned taskbar entry

### ISSUE THREAD

**Issue by densik** [RocketChat/Rocket.Chat.Electron#1209]
## My Setup
- Operating System: Windows 10 Pro
- App Version: 2.15.3
- Installation type:  exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
After clicking X to minimize rocket chat to the tray, you can only reopen the window through the tray icon, and not through the start menu or from a pinned taskbar entry.

### Current Behavior
After clicking X to minimize RocketChat to the tray icon, you cannot relaunch/restore the app through a pinned taskbar icon or the start menu. The only way to restore the app is through the tray icon. Reproducible on two different machines.

### Expected Behavior
After clicking X to minimize RocketChat to the tray icon, you should be able to relaunch/restore the app through a pinned taskbar icon or by launching it through the start menu.

**Comment by josephchan91** [comment]
Same on Windows 7

**Comment by marcuslayne** [comment]
When booting the local machine or closing the app and opening the app it will not actually open and stay within the system tray. This can be replicated on many workstations on our domain. It dose not just occur when closing the app by clicking the X or file>quit rocket chat.

**Comment by a110ut** [comment]
Same on Ubuntu 19.04

**Comment by UnePierre** [comment]
Same on Windows 10 Enterprise LTSC (build 1809) with Rocket.Chat App Version 2.15.3

**Comment by Dinip** [comment]
Some on Windows 7, 8.1 and 10. We have the same "problem" here on the office. People say that rocket is now working, because they have rocket pinned on task bar or try to launch it again by clicking on desktop icon.

**Comment by HieuHongLe94** [comment]
I also encountered the same problem. How to fix ?

**Comment by HieuHongLe94** [comment]
> I also encountered the same problem. How to fix ?

I tried ! But I want the app to reopen right away, not to render
