### ISSUE TITLE
Share my location doesn't appear in 2.15.3

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat.Electron#1210]
Hello,

The Share my location button doesn't appear in the contextual menu inside the Rocket.Chat.Electron:

Electron Screen Capture:
![image](https://user-images.githubusercontent.com/42721509/57119807-e94ff780-6d64-11e9-9ea9-6071993d9572.png)

Rocket.Chat Screen Capture:
![image](https://user-images.githubusercontent.com/42721509/57119768-95451300-6d64-11e9-983b-3d91318b070b.png)

Cheers

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
