### ISSUE TITLE
Rocket.Chat Client with big local cache is very slow at start

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Electron#1211]
## My Setup
- Operating System: Xubuntu 18.04
- App Version: 2.15.3
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Client almost freezes on startup; contents from the servers are not loaded; blank screen. After some time, however, the client works. The client has a local cache of about 350 MB.

After the cache under `.config/Rocket.Chat/` has been cleared, the problem no longer occurs.

I could observe this behavior several times in the past and could only help by deleting the local cache.

### Current Behavior

Client with big local cache almost freezes on startup.

### Expected Behavior

A large local cache should not delay the start of the client or make the client unusable.

**Comment by kaiwasaki** [comment]
How does it behave for you when it is staring slow? I usually see the window frame, but no content. The application window is transparent except the border around it, which causes quite some confusion for me. I am using xfce.
But maybe this is unrelated?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
