### ISSUE TITLE
Member List shortfall

### ISSUE THREAD

**Issue by qwickset** [RocketChat/Rocket.Chat.Electron#1212]
## My Setup
- Operating System: Linux server/Windows client
- App Version: client = 2.14.7 (tried 2.15.3 but was halted due to node.dll error, reverted)
- Installation type: client = exe

- [n/a - see above ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description
Problem Statement:  When considering adding a user to a room, there appears to be now way to see if they've already been added to the room.

Given: 3 members of room, Adam (online), Beth (online), and Carl (offline)....

### Current Behavior
1. click on Room from Groups List
2. click on "Member List" from upper-right icon palette
3. reports - "Showing 2. Online 2, Total: 3 users"
User list shows 2 users - Adam and Beth...no mention of Carl)

### Expected Behavior
1. reports - "Online 2, Total: 3 users" followed by a list of all members of room (not just online users)
(e.g., shows 3 users in following user list, say Adam, Bob, and Carl)

There appears to be no way, at lest via this interface, to tell if Carl (currently offline) is a member of the group or not.

It would be beautiful to see all of the members listed (even with offline being conditionally) in an online group followed by an offline group.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by qwickset** [comment]
Fixed! Thank you!
