### ISSUE TITLE
app does not hide file suffix in macOS finder although option is enabled

### ISSUE THREAD

**Issue by foss-** [RocketChat/Rocket.Chat.Electron#1214]
## My Setup
- Operating System: macOS 10.14.4
- App Version: 2.15.3
- Installation type: direct download (dmg)

## Description
- 100% reproducible and persisting with current release

### Current Behavior
in finder > programs the app is shown as "Rocket.Chat.app" despite the setting to "Hide Suffix" being enabled

### Expected Behavior
app should be listed as "Rocket.Chat" only. I wonder if the dot in the name is a problem? Also I noticed, the option to Hide Suffix is greyed out. It is in active (ticked) state. Since greyed out tick cannot be removed. Have not seen this for other apps. See screenshot for current behavior:

<img width="291" alt="app has suffix despite option to hide it being active" src="https://user-images.githubusercontent.com/5708172/57323037-4224e480-7105-11e9-9735-0ecda52ba80d.png">

**Comment by tassoevan** [comment]
> I wonder if the dot in the name is a problem?
Yes, more specifically the `*.chat` extension.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
