### ISSUE TITLE
Linux client blocks while searching for server

### ISSUE THREAD

**Issue by Skwanky** [RocketChat/Rocket.Chat.Electron#1215]
## My Setup
- Operating System: Linux
- App Version: 2.9.0
- Installation type: package manager

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

My client is connected with two server. One of these server was down. In this time the whole GUI did not respond.
### Current Behavior

When client searches for one server whole GUI is blocked 
### Expected Behavior
It should be possible to do stuff with the other ServerConnections. (First world problems)

**Comment by reetp** [comment]
You have not tested with the latest version. You are seriously out of date.

https://github.com/RocketChat/Rocket.Chat.Electron/tags
https://github.com/RocketChat/Rocket.Chat.Electron/releases

Please upgrade.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
