### ISSUE TITLE
Rocketchat Taskbar icon disappears after restart - even if pinned

### ISSUE THREAD

**Issue by raziel900** [RocketChat/Rocket.Chat.Electron#1216]
## My Setup
- Operating System: Windows 10 Build 15063
- App Version: 2.15.3
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I would like to set the icon on the taskbar to show permanently, however the setting is lost every time i reboot. There are 2 Rocketchat applications listed as per screenshot.

### Current Behavior
Icon is not visible anymore after reboot and you need to set the setting once again
![image](https://user-images.githubusercontent.com/49512131/57357037-3a4f5980-7172-11e9-95f0-53a682c7fa62.png)

### Expected Behavior
Icon should appear on taskbar after restart.
![image](https://user-images.githubusercontent.com/49512131/57357025-328fb500-7172-11e9-8cde-05010a3d3322.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
