### ISSUE TITLE
Ability to only show unread chats and channels

### ISSUE THREAD

**Issue by jibsonline** [RocketChat/Rocket.Chat.Electron#1217]
I am using the latest version on Mac Book Pro. I am not able to find the option to hide read messages and channels and only show chats and channels with unread messages. Slack provides this feature and is really helpful when you have more than 500 members and over 100 channels. 

Even the option to sort chats based on unread messages can't be found. Please include these features

**Comment by reetp** [comment]
Which version of the client are you using?

I don't think you are looking very hard. Try sorting A-Z, Unread on Top and/or Activity, and try different groupings.

It is the same on the web browser.

![A-Z](https://user-images.githubusercontent.com/3800384/57443533-8ff93400-724e-11e9-9c69-30c4d28d3220.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
