### ISSUE TITLE
Electron 2.15.3 on Mojave switching to away while computer still active

### ISSUE THREAD

**Issue by vinceogne** [RocketChat/Rocket.Chat.Electron#1218]
## My Setup
- Operating System: OSX Mojave 10.14.4
- App Version:  2.15.3
- Installation type: self update

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
We have auto-away enabled and idle set for 300 seconds.  Electron is going 'away' when app is in background even though system is still in use.

### Current Behavior
Status is changing to "away" even when we are still activity working.

### Expected Behavior
App should stay green/online while computer is being used (keyboard/mouse activity), even when it is not in the foreground. It should change to "away" only after system has been inactive for 300 seconds (as specified by idle setting).

**Comment by tassoevan** [comment]
Closing it since #1264 addresses it too.

**Comment by vinceogne** [comment]
is this fixed in the 2.16.0 downloads for mac and pc?
