### ISSUE TITLE
Trial Bronze cloud plan server not interfacing with same UI as Rocket.Chat server...

### ISSUE THREAD

**Issue by DaleKramer** [RocketChat/Rocket.Chat.Electron#1219]
[Please see this forum topic](https://forums.rocket.chat/t/slack-team-trying-to-evaluate-rocket-and-we-are-willing-to-use-bronze-server-but/3783)

I really like the current UI on the Rocket.Chat server but I can't show the powerusers.rocket.chat group to any of my Slack teammates who I am trying to convince to migrate to Rocket Bronze..

They would laugh in my face...

Any ideas how to get the current Rocket.Chat server UI onto my powerusers.rocket.chat group?

Thanks,
Dale

**Comment by tassoevan** [comment]
@DaleKramer I'll keep an eye on that forum topic while contacting the @RocketChat/cloud team to help you. I'm closing this issue since is not a desktop app problem.

**Comment by DaleKramer** [comment]
Thanks I did not know it wasn't a desktop app problem until I finally tried it on my iPhone , sorry...

**Comment by tassoevan** [comment]
No problem! :hugs:
