### ISSUE TITLE
Video play frame not entering Full Screen when icon clicked

### ISSUE THREAD

**Issue by DaleKramer** [RocketChat/Rocket.Chat.Electron#1220]
I am using Rocket.Chat v2.15.3 on a Win10pro computer.

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
1. The play in fullscreen icon on the mp4 file viewer does nothing....
2. The Sound icon only allows muting, no slider for volume level on mouse hover....

### Expected Behavior
The video should play in full screen when I click on the icon
The sound icon should bring up a slider that lets you adjust volume on a mouse hover

![NoFullScreen](https://user-images.githubusercontent.com/7749699/57574903-d0071500-740e-11e9-950e-ecec5887ad5d.jpg)

**Comment by adocampo** [comment]
Just point the error can be reproducible in Linux and MacOS

**Comment by wreiske** [comment]
YouTube and other video embeds seem to do the same thing. No full-screen:'(.

**Comment by tassoevan** [comment]
Seems to be working in `develop` branch.
