### ISSUE TITLE
Rocket chat continously not blinking Taskbar when recieved new message from anyone.

### ISSUE THREAD

**Issue by theonetech1** [RocketChat/Rocket.Chat.Electron#1221]
## My Setup
- Operating System: Ubuntu 18.10
- App Version: 0.74.3
- Installation type:  from terminal interface

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
