### ISSUE TITLE
Slack Channel forcing browser use

### ISSUE THREAD

**Issue by wonkaba** [RocketChat/Rocket.Chat.Electron#1222]
## My Setup
- Operating System: OSX 10.14.4
- App Version: 2.15.3
- Installation type: app store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I have multiple servers configured with my Rocketchat app. Most are Rocketchat servers which have no problems but one is a Slack server. Ever since the newest update (May 2, 2019) when I click on a channel in the Slack server, the Rocketchat app switches to that channel (as expected) but also OPENS UP A NEW BROWSER TAB and navigates to my slack channel. 

### Current Behavior
When I click on a channel in the Slack server, the Rocketchat app switches to that channel (as expected) but also OPENS UP A NEW BROWSER TAB and navigates to my slack channel. 

### Expected Behavior
Rocketchap app should only switch to the appropriate Slack channel. Not open up in browser.

**Comment by Floflobel** [comment]
Same problem on RocketChat app (version 2.15.1)

**Comment by millerf** [comment]
Same

**Comment by leszek-bumbul** [comment]
Issue still present in version 2.15.3

**Comment by da9l** [comment]
Still present in 2.15.5
OS: Windows 10

**Comment by millerf** [comment]
Still present in 2.15.5
OS: MacOS

**Comment by da9l** [comment]
Still present in 2.16.2
OS: Windows 10

**Comment by Jafaral** [comment]
2.17.2
Ubuntu 18.04
same issue

**Comment by ianmclinden** [comment]
Still present in 2.17.2
OS: macOS 10.14

**Comment by aaronreimann** [comment]
Still present in 2.17.7
OS: Windows 10

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
