### ISSUE TITLE
Auto-away not working

### ISSUE THREAD

**Issue by te-af-github** [RocketChat/Rocket.Chat.Electron#1225]
## My Setup
- Operating System: MacOS 10.14.4
- App Version: 2.15.3
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Auto-away is not kicking in.

### Current Behavior
App does not automatically switch to "away".

### Expected Behavior
App switches status to "away" after set seconds.

To reproduce:

Set Auto-away timer to 60 seconds, set focus to another app (to avoid side issues), wait 60 seconds. Rocket.chat should switch status to "away" but doesn't.

**Comment by scolinuca** [comment]
Same thing for me : mac os 10.14.5, rocket client 2.15.3, auto away is not working

**Comment by caldwell** [comment]
I am encountering the same thing: macOS 10.14.6 rocket chat client 2.16.0

A consequence of this is that since it always thinks I'm connected (even if my computer has put the display to sleep!), it doesn't send mobile notifications, so this is causing me to miss messages.

**Comment by neonardo1** [comment]
Same thing on Linux with client 3.1.1.

```
$ cat /etc/*-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
$ uname -r
5.4.85-1-lts
```

Using Cinnamon DM for what it's worth.

**Comment by neonardo1** [comment]
Also tested with 3.0.7 which of course shas the issue as well.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
