### ISSUE TITLE
opening file paths

### ISSUE THREAD

**Issue by fabigr8** [RocketChat/Rocket.Chat.Electron#1227]
## My Setup
- Operating System: Windows
- App Version:  2.15.3
- Installation type: .exe

- [ X] I have tested with the latest version
- [ X] I can simulate the issue easily

## Description
hi guys i have a problem openning a file url on the windows rocketchat client because the network drive name has a "_" in the name itself.. works not in the client for windows nor in the webbrowser (chrome)

here's the filename shortend: 
"file://wifak_w.rz.wuerzburg.de/WIFAK/..."

### Current Behavior
the default webbrowser opens with a faulty link / url containing only  "w.rz.wuerzburg.de/WIFAK/..." instead of "wifak_w.rz.wuerzburg.de/WIFAK/..."

### Expected Behavior
open windows explorer and filepath.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
