### ISSUE TITLE
RocketChat Desktop client -Server reload

### ISSUE THREAD

**Issue by karamsinghcore** [RocketChat/Rocket.Chat.Electron#1228]
## My Setup
- Operating System: Windows 10 Enterprise
- App Version: 2.15.3
- Installation type: exe 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Everytime i logout and relogin get the error "Server failed to load"
<img width="960" alt="Rocket Chat_Tx1tQcx51s" src="https://user-images.githubusercontent.com/43957060/57856561-9f97f000-77ed-11e9-84b6-fd9c516fe850.png">
.
### Current Behavior

Need to click retry to login to rocketchat desktop client. 
### Expected Behavior

It should login without throwing "Server Failed to load" error.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
