### ISSUE TITLE
Taskbar and the "orange background", intermittent operation

### ISSUE THREAD

**Issue by marcosmolinamaxicon** [RocketChat/Rocket.Chat.Electron#1233]
## My Setup
- Operating System: Windows10 
- App Version: 2.15.3
- Installation type: exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When you click the close button on the windows bar after that icon does not turn orange.

View > Tray Icon to Disable

![image](https://user-images.githubusercontent.com/39923299/58124234-211fc180-7be4-11e9-9d6b-7d967792bf1d.png)

but, when click em close button of program 
![image](https://user-images.githubusercontent.com/39923299/58124291-47456180-7be4-11e9-8819-8104a5c717b3.png)

![image](https://user-images.githubusercontent.com/39923299/58124343-63490300-7be4-11e9-96d3-c2a931f4e9d2.png)

### Current Behavior
Taskbar and the "orange background", intermittent operation
![erro](https://user-images.githubusercontent.com/39923299/58125550-30543e80-7be7-11e9-9a94-0f9719441c18.gif)

### Expected Behavior
always working

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
