### ISSUE TITLE
The chat start many video call alone. Video call spam. 

### ISSUE THREAD

**Issue by jbiancogyn** [RocketChat/Rocket.Chat.Electron#1234]
![Capturar](https://user-images.githubusercontent.com/16243323/58170914-1bb98a00-7c6b-11e9-9b27-45a1f994a25e.JPG)
## My Setup
- Operating System: Windows 10
- App Version: 2.15.3
- Installation type: exe 

- [X] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
The system is making video call spam.
Chat resends my video calls at some moment.

### Current Behavior
in conversations where I participated in a video call, at some point the chat tries to start a video call alone and in a repetitive way.
I suspect these calls are being created when the computer returns from a hibernation or a screen lock.

### Expected Behavior
do not make video calls alone

**Comment by eidermar** [comment]
We are having the exact same problem. Multiple 'Click to Join' links are generated randomly without user interaction. And sometimes when a video chat was actively created, no 'Click to Join' links is being generated at all. Just a suspicion, are those random links maybe the ones that were not generated when actually and then spammed into the channel with a strange and random delay?

**Comment by col-panic** [comment]
Experiencing the same problem here with v2.2.0 - sudden calls started in the middle of the night - by a seemingly sleeping computer. Or it might happen from the mobile phone! Is there any means to find out which device initiated the call?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
