### ISSUE TITLE
Space on device

### ISSUE THREAD

**Issue by piotrwlodarczyk** [RocketChat/Rocket.Chat.Electron#1235]
## My Setup
- Operating System: Windows Server 2016 standard
- App Version: 2.15.0
- Installation type: exe

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
Hi, i noticed that in my server it's huge number of small files (488,5KB each). Sum of them size is a little above 9GB. After cosultation with our admins I've got information about it's rocket chat. Deleting them doesn't affect on RocketChat stability etc. 
1.  Are they realy Rocket.Chat files?
2. What they're doing? And what for thar are being used?

### Current Behavior
a huge amount of files that take up a lot of disk space

### Expected Behavior
no trash files

![image](https://user-images.githubusercontent.com/24660357/58174112-63590980-7c9d-11e9-992c-6ab6dec5c87a.png)

**Comment by piotrwlodarczyk** [comment]
hello, any info?

**Comment by gfernandez-me** [comment]
someone?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
