### ISSUE TITLE
RocketChat launches in 'hidden' mode

### ISSUE THREAD

**Issue by Tom1701** [RocketChat/Rocket.Chat.Electron#1236]
**My Setup**

- Version 2.15.3
- OS - Win10 Pro
- Installation type: exe
- X -  I have tested with the latest version
- X -  I can simulate the issue easily

**Description** 

Rocket Chat client launches in hidden mode; manually killing the process and editing the window-state-main.json file allows me the launch and see the client window once; on subsequent launches the window is hidden.

**Current Behavior**

Application launches in hidden mode and changes the 'IsHidden' setting in the window-state-main.json file to 'true' after user edits it and changes it to false

**Expected Behavior**

Application launches and shows the client window.  'IsHidden' setting does not change without user intervention.

**Steps to reproduce:**

1. Kill all instances of Rocket Chat in Task Manager
2. edit c:\users\[username]\AppData\Roaming\Rocket.Chat\window-state-main.json - set "isHidden" to false - close & save file
3. launch Rocket Chat.  Client window shows.
4. close Rocket Chat (we can open the edit window-state-main.json file at this time and see that "isHidden" is still false)
5. launch Rocket Chat.  Client window does not show. 
6. Launch Task manager; note that 4 Rocket Chat processes show
7. Edit window-state-main.json.  Note that "isHidden" now shows true.

**Comment by r3wald** [comment]
It's the same for me using Linux.

**Comment by wizofaus** [comment]
Just found this after reporting the same thing (initially I'd only found it as an already-closed bug). So definitely still an issue.

**Comment by wizofaus** [comment]
STILL happening with 2.15.5. I'd say at least once every month or so I have to edit this file to get Rocket.Chat to load up correctly.

**Comment by christianbrb** [comment]
Hey guys :) It is great, that you are maintaining this client :) 👍 
Unfortunately, this is still happening with the latest version of RocketChat on Win 10 and it is really annoying. After closing RocketChat I always have to change the config file manually.
Thanks for your support!

**Comment by wizofaus** [comment]
I've actually given up using it because it was happening virtually every day, just sticking to the browsed-based interface.

**Comment by christianbrb** [comment]
I have found a workaround. You can click on the RocketChat Icon in the system tray on the right:

![grafik](https://user-images.githubusercontent.com/35398162/77514870-d90ea280-6e77-11ea-9f25-8fdfd0ed445d.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
