### ISSUE TITLE
Rocket.Chat not open after install on Windows 10

### ISSUE THREAD

**Issue by alissonb13** [RocketChat/Rocket.Chat.Electron#1237]
I am encountering problems when opening Rocket.Chat after installing on Windows 10.

When installed and run for the first time, everything works fine. But when I close Rocket.Chat and I try to open it again, it just does not open.

**Comment by ketanvault** [comment]
I'm having the same issue on 2.17.9 version

![image](https://user-images.githubusercontent.com/33649952/80705694-7d81a580-8b04-11ea-8a8a-46d0a13b5ac9.png)

**Comment by sujaysreedhar** [comment]
any solutions for this issue?
 
I just compiled a fresh copy and try to install the installer.  Not Opening.

**Comment by sujaysreedhar** [comment]
apparently the issue is from the clone of the repo (development branch). Use The issue seems not to be there on the release channel
