### ISSUE TITLE
Message is missing on conversation-window

### ISSUE THREAD

**Issue by aleoliva** [RocketChat/Rocket.Chat.Electron#1239]
## My Setup
- Operating System:
macOS Mojave Version 10.14.5 (18F132)
- App Version:
Rocket.Chat Version 2.15.3
- Installation type: 
dmg through App Store

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

Message was not visible on the dialog window. It also never appears, although new messages were wrote after that.

It was showed by the Mac's Notification Center as a pop-up but later on the message could not be found there either.

It is only visible on the left menu, under the channel preview (See screenshot attached, under the red circle):
<img width="1156" alt="Message missing" src="https://user-images.githubusercontent.com/19690082/58259168-4fcca200-7d74-11e9-9f95-ab23ba639eaa.png">

### Current Behavior

I received a notification of a new message on a favorite channel but when I scrolled bottom of that channel the message was not there.

I could read on my mobile device.

### Expected Behavior

Read all messages.

**Comment by Jaffex** [comment]
In our organisation, we have the same problem with some users.
Sometimes it helped to "Reload ignoring Cache" in the "View" Dropdown.

However sometimes that does not help either and some users are stuck with not being able to see other peoples messages inside the chat window.

Were you able to workaround this problem in any way?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
