### ISSUE TITLE
Focus message search field when open it

### ISSUE THREAD

**Issue by NikKomarov** [RocketChat/Rocket.Chat.Electron#1240]
## My Setup
- Operating System: win 10
- App Version: 2.15.0
- Installation type: exe

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When you click on search messages button, control opens, but search field is not focused. So you should click on it. It's so annoying. And it's easy to forget about click, start typing, press enter and send your search request to colleague

### Current Behavior
Search message control opens, but field is not focused

### Expected Behavior
Search message control opens and field is focused

**Comment by nopynoop** [comment]
This has already been requested multiple times. 

See [13062](https://github.com/RocketChat/Rocket.Chat/issues/13062) and [11482](https://github.com/RocketChat/Rocket.Chat/issues/11482)
