### ISSUE TITLE
Video Chat Full Screen Option

### ISSUE THREAD

**Issue by wagigi** [RocketChat/Rocket.Chat.Electron#1241]
## My Setup
- Operating System: Windows 7 - 10
- App Version: 2.15.3
- Installation type: .exe then by updates

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When you launch a video chat, you can't use the fullscreen option.

### Current Behavior
Nothing happen

### Expected Behavior
The video chat switch to full screen mode

**Comment by tlachy** [comment]
we are actually evaluating this communication tool in our company and this is showstopper for us too.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
