### ISSUE TITLE
Too many requests - Conversation button

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat.Electron#1242]
## My Setup
- Operating System: Ubuntu 
- App Version: 1.0.3
- Installation type: manual

- [ X ] I have tested with the latest **STABLE** version
- [ X ] I can simulate the issue easily

## Description
There is almost anytime no way to use "Conversation" button because too many requests error appears.

### Current Behavior
Just at in the description.

### Expected Behavior
Go to conversation with the user.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
