### ISSUE TITLE
voice icon hide when i press it to record a meesage

### ISSUE THREAD

**Issue by ho2015** [RocketChat/Rocket.Chat.Electron#1245]
## My Setup
- Operating System:  google chrom & windows
- App Version: latest version
- Installation type: 

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by ho2015** [comment]
![Untitled](https://user-images.githubusercontent.com/12132712/58700905-ad856d80-83b6-11e9-8aa3-a2a63050743b.png)

no voice record icon after i press it to record

**Comment by reetp** [comment]
This might want to go over to Rocket.Chat itself.

I can confirm I noticed this on open.rocket.chat this morning.

The Record button works OK in 1.1.1 so this is presumably a regression in Develop.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
