### ISSUE TITLE
Zoom Level only working for one server if there are more than one added to the client

### ISSUE THREAD

**Issue by r4tt4** [RocketChat/Rocket.Chat.Electron#1246]
## Description
I just upgraded my really old Desktop Client from rocketchat_2.10.5_amd64.deb to rocketchat_2.15.3_amd64.deb

After that i git the issue that it is not possible any more to change the zoom levels for the two independent servers I use.

### Current Behavior
Changing zoom in Server 1 alters the zoom level in 2. If I switch to 2 I can change the levels here without any problems.
Zoom in 1 is not possible, until I delete 2. Then zoom works in 1 as the only left connection. After adding the server 2 again, same problem. Zoom only in 2 possible.

### Expected Behavior
Changing zoom levels should be independent, as in the old Desktop Client, for each connected server.

## My Setup
- Operating System: Ubuntu 18.04 LTS
- App Version: Latest official .deb Build 2.5.13
- Installation type: Debian Package .deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

**Comment by Drakone** [comment]
Same problem for me.

Operating System: Manjaro (lastest official)
App Version: aur/rocketchat-desktop 2.17.3-2

**Comment by 73** [comment]
- Reproducible on  Ubuntu 20.04, snap package 2.17.11
- Not Reproducible on Ubuntu 20.04, .deb package 2.17.11

**Comment by iadenisov** [comment]
Reproduced in Mint 19.3 snap version 2.17.11

**Comment by tassoevan** [comment]
It's working right at 3.0.4.
