### ISSUE TITLE
Glitch with Links in the Announcement ribbon

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat.Electron#1248]
## My Setup
- Operating System: Windows 10, Mac OSX Mojave, Ubuntu Linux, Arch Linux, Manjaro Linux
- App Version: Latest
- Installation type: all available packages

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description

When adding a link in the Announcement ribbon, a popup appears when the link is clcked on with some cryptic code.

### Current Behavior
The popup appears for both download links and site URLs but it display a code instead of the link's  friendly name.
![image](https://user-images.githubusercontent.com/42721509/58839406-04fb3600-8662-11e9-80a9-2dfb495b73fc.png)

### Expected Behavior
Displaying the links name instead of code.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
