### ISSUE TITLE
Dev tools not working in 1.1.0 on Ubuntu 15.10

### ISSUE THREAD

**Issue by brylie** [RocketChat/Rocket.Chat.Electron#125]
When trying to troubleshoot some WebRTC difficulties, I am trying to view console output in the built-in dev tools. However, the dev tools window fails to render, instead showing a blank grey area.

What can we do to troubleshoot the dev tools issue?
##

**Comment by rodrigok** [comment]
I will update the version of electron today, maybe this can help us.

**Comment by rodrigok** [comment]
Depends on https://github.com/electron/electron/issues/3871 to update our electron version
