### ISSUE TITLE
Rochet.chat desktop app does not stop loading to show messages

### ISSUE THREAD

**Issue by Belencha** [RocketChat/Rocket.Chat.Electron#1250]
## My Setup
- Operating System: Windows 10 Pro
- App Version: 2.15.3
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I download for the Nth time Rocket.chat desktop app from the official site (latest version) and install in my system. Since I have the user data stored in my computer, Rocket.chat recognises my connection and directly tries to connect to my company host. It keeps loading over and over, but I do have notifications of new unread messages.

### Current Behavior
It is impossible to see the chats because it never finishes loading:
<img width="960" alt="rocket-chat-2 15 3 issue" src="https://user-images.githubusercontent.com/6985234/59258249-df5cc680-8c37-11e9-8c09-79bc8be64340.png">

### Expected Behavior
I expect it to finish loading, get to see my messages and talk to people as I used to do last week :)

**Comment by reetp** [comment]
Please give some details on your Rocket.Chat server. Version number, how is it hosted etc.

Can you connect with a browser?

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
