### ISSUE TITLE
"Access forbidden" when trying to log in with Nextcloud as custom Oauth2 client

### ISSUE THREAD

**Issue by p-jo** [RocketChat/Rocket.Chat.Electron#1251]
## My Setup
- Operating System: OSX 10.14, Windows, Ubuntu
- App Version: 2.15.3
- Installation type: dmg, exe, snap 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

I'm using Nextcloud as a custom Oauth2 client for Rocket.Chat. The login works in the IOS app and browser, but not in the desktop app. In the last step, when I'm granting access to Rocket.Chat, I get the message "Access forbidden State token does not match" from Nextcloud.

<img width="338" alt="bild" src="https://user-images.githubusercontent.com/5712075/59282760-b81eed00-8c69-11e9-8bab-f98bf743b1e9.png">

These are my custom OAuth settings in Rocket.Chat:

* Callback URL: https://example.com/_oauth/nextcloud
* URL: https://example.com
* Token path: https://example.com/apps/oauth2/api/v1/token
* Token sent via: Header
* Identity Token Sent Via: Same as Token Sent Via
* Identity Path: https://example.com/ocs/v2.php/cloud/user?format=json
* Authorize Path: https://example.com/apps/oauth2/authorize
* Scope: openid
* Param Name for access token: access_token
* Id: my id
* Secret: my secret id
* Login style: Popup
* Username field: osc.data.id
* Roles/groups field name: roles

### Current Behavior

When using Nextcloud to log in, the app opens a popup window as expected. But I get redirected from the app to the browser in the last step when I grant Rocket.Chat access to Nextcloud, and that is when the error occurs.

### Expected Behavior

The login should not redirect me to the browser, and as in the IOS app, I should be logged in to the app once I grant Rocket.Chat access to my Nextcloud account.

**Comment by yeoldegrove** [comment]
I have the exact same behaviour with the App version 2.15.5, also using outh via nextcloud.

**Comment by p-jo** [comment]
The problem seems to be that Rocket.chat is opening relative links in the app, but absolute links in the browser. I've tweaked my Nextcloud installation for now to fix it (by making the grant access link relative instead of absolute).
But not sure if the best option is to change the rocket.chat app's behaviour or the links in Nextcloud.

**Comment by yeoldegrove** [comment]
@p-jo Do you mind sharing the patch?

**Comment by p-jo** [comment]
Sure @yeoldegrove! This is for Nextcloud 15, I haven't had the time to make a pull request or anything yet.

in `core/templates/loginflow/authpicker.php` change this line

```
 	<br/>
 
 	<p id="redirect-link">
-		<a href="<?php p($urlGenerator->linkToRouteAbsolute('core.ClientFlowLogin.grantPage', ['stateToken' => $_['stateToken'], 'clientIdentifier' => $_['clientIdentifier'], 'oauthState' => $_['oauthState']])) ?>">
+		<a href="<?php p($urlGenerator->linkToRoute('core.ClientFlowLogin.grantPage', ['stateToken' => $_['stateToken'], 'clientIdentifier' => $_['clientIdentifier'], 'oauthState' => $_['oauthState']])) ?>">
 			<input type="submit" class="login primary icon-confirm-white" value="<?php p($l->t('Log in')) ?>">
 		</a>
 	</p>
```

**Comment by firlevapz** [comment]
thanks @p-jo for your fix here - I'm having exactly the same problem, but with a snap-installation of nextcloud it's not so easy to change the authpicker-code... 

Did you create a pull request already to change the link to a relative URL in the upcoming nextcloud release? 

I dont know if the nextcloud team is working on a fix to open all auth-related links inside the app?

**Comment by p-jo** [comment]
I’m glad it fixed your problem @firlevapz! No unfortunately I haven’t had time to follow it up at all, so submit the patch if you want to.

**Comment by cjhille** [comment]
Encountered the same issue here. I'd be really happy about a PR for this.

**Comment by firlevapz** [comment]
I've created a pull request already: https://github.com/nextcloud/server/pull/19646

But it still needs to be approved

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
