### ISSUE TITLE
Rocket.Chat.Electron RAM usage

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat.Electron#1253]
What are the normal Rocket.Chat.Electron RAM usage in Windows 7? 
We have 2.15.3 version and RAM usage are from 400-800 MB per client (we have ~ 20 users). Is that normal behavior?

**Comment by LXSysadmin** [comment]
![rocket_chat](https://user-images.githubusercontent.com/19779209/59501055-606bc600-8ea3-11e9-857e-97b5c0001148.jpg)

**Comment by LXSysadmin** [comment]
This is Windows 7 RAM usage

**Comment by Maqsyo** [comment]
Seems to be normal.
I think it's the fault of chrome which is running in the background (Electron)

**Comment by LXSysadmin** [comment]
> Seems to be normal.
> I think it's the fault of chrome which is running in the background (Electron)

How the Electron is connected to Chrome? Why it is depending on Chrome?

**Comment by Maqsyo** [comment]
> How the Electron is connected to Chrome? Why it is depending on Chrome?
https://electronjs.org/
I think this page can answer all your questions.
But in short:
electron brings an own node-service and chrome-instance with it, so that the programmer can use normal html, css and javascript to deploy an app on multiple platforms

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
