### ISSUE TITLE
Tray icon transparent

### ISSUE THREAD

**Issue by fuzzykiller** [RocketChat/Rocket.Chat.Electron#1254]
## My Setup
- Operating System: Windows 10 Enterprise 1809
- App Version: 2.15.3
- Installation type: exe

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
Sometimes, the tray icon becomes completely transparent. It still works normally though.

Presumably, the icon’s in-memory representation somehow breaks. Unfortunately, I cannot offer reproduction steps at this time, but it may be related to monitor configuration changes and/or the resulting DPI changes.

May be an Electron bug.

### Current Behavior
Sometimes, the default (all gray) tray icon becomes completely transparent. The icon still takes space normally. The context menu still works.

If the icon changes due to notifications, this different icon is visible again. After clearing the notification, the icon becomes transparent again.

### Expected Behavior
Icon should always show.

**Comment by nw-git** [comment]
I also have the same issue with the icon going completely transparent. Windows 10 Pro 1709. I do have 5 displays, all high resolution with DPI scaling. I also use Remote Desktop to access this workstation remotely- that could be related but I haven't specifically tested it.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by fuzzykiller** [comment]
Thank you for the update! I am no longer in a position where I use RocketChat, so I cannot test this. Sorry!
