### ISSUE TITLE
macOS app loads unsigned binary from /var folder

### ISSUE THREAD

**Issue by andreydanin** [RocketChat/Rocket.Chat.Electron#1255]
### Description:

Rocket.Chat from AppStore loads unsigned binary from /var folder.

### Steps to reproduce:

1. Run Rocket.Chat
2. Open TaskExplorer (https://objective-see.com/products/taskexplorer.html) and select Rocket.Chat to view loaded dylibs

Note: maybe you need to login on a server.

### Expected behavior:

No unsigned dylibs are loaded

### Actual behavior:

Unsinged dylib is loaded. Rocket.Chat doesn't work on macOS 10.15

![TaskExplorer-Rocket Chat](https://user-images.githubusercontent.com/16131131/58890877-2573d080-86f4-11e9-81e6-56150df700fd.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
