### ISSUE TITLE
Show Menu Bar

### ISSUE THREAD

**Issue by smtdede10** [RocketChat/Rocket.Chat.Electron#1256]
Hi, I hide menu bar, now I want show it, but I don't how to do that. Any key shortcut etc. Also, I changed manubar = true in code, but there is nothing after render. It still is hidden.

**Comment by smtdede10** [comment]
> Hi, I hide menu bar, now I want show it, but I don't how to do that. Any key shortcut etc. Also, I changed manubar = true in code, but there is nothing after render. It still is hidden.

I solved my problem with adding short cut 👍 

label: i18n.__('menus.showMenuBar'),
					type: 'checkbox',
					checked: showMenuBar,
					accelerator: 'CommandOrControl+H',
					click: () => events.emit('toggle', 'showMenuBar'),

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
