### ISSUE TITLE
[Feature Request] Compiling the app to only allow a single server

### ISSUE THREAD

**Issue by DonaldTsang** [RocketChat/Rocket.Chat.Electron#1257]
This might sound weird, but assume that I start my own server, I would like to make the desktop client to only access my server, or at least treat my server as "first class" such that I can distribute the compiled app binaries to my fans/users.
Is it possible to make a config file for this?

**Comment by jeanfbrito** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron#pre-release-configuration
