### ISSUE TITLE
launch success but no UI appears

### ISSUE THREAD

**Issue by dimaatkaev** [RocketChat/Rocket.Chat.Electron#1258]
## My Setup
- Operating System: KDE  5.58
- App Version: 2.15.3 amd64
- Installation type: deb

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily (not sure, if it meant that it is not an intermittent issue)

## Description
when I launch it from terminal get this warns:

```
$ rocketchat-desktop 

(rocketchat-desktop:17749): Gtk-WARNING **: 13:47:56.580: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(rocketchat-desktop:17749): Gtk-WARNING **: 13:47:56.581: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(rocketchat-desktop:17749): Gtk-WARNING **: 13:47:56.581: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

```

and the app doesn't visible

### Current Behavior
the app starts, but I cannot see UI, following in the console
`$ ps ax | grep rocketchat-desktop 
 1767 ?        Sl     0:00 /opt/Rocket.Chat/rocketchat-desktop
 1769 ?        S      0:00 /opt/Rocket.Chat/rocketchat-desktop --type=zygote --no-sandbox
 1829 ?        Sl     0:00 /opt/Rocket.Chat/rocketchat-desktop --type=gpu-process --enable-features=SharedArrayBuffer --no-sandbox --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=5920385071253770841
 1834 ?        Sl     0:00 /opt/Rocket.Chat/rocketchat-desktop --type=renderer --no-sandbox --autoplay-policy=no-user-gesture-required --enable-features=SharedArrayBuffer --service-pipe-token=12567370868897448461 --lang=en-US --app-path=/opt/Rocket.Chat/resources/app.asar --node-integration=true --webview-tag=true --no-sandbox --background-color=#fff --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=12567370868897448461 --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
 1872 ?        Sl     0:00 /opt/Rocket.Chat/rocketchat-desktop --type=renderer --no-sandbox --autoplay-policy=no-user-gesture-required --enable-features=SharedArrayBuffer --service-pipe-token=12570195991502335723 --lang=en-US --app-path=/opt/Rocket.Chat/resources/app.asar --node-integration=false --webview-tag=true --no-sandbox --preload=/opt/Rocket.Chat/resources/app.asar/app/preload.js --background-color=#fff --guest-instance-id=1 --enable-blink-features --disable-blink-features --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=12570195991502335723 --renderer-client-id=5 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
 1873 ?        Sl     0:00 /opt/Rocket.Chat/rocketchat-desktop --type=renderer --no-sandbox --autoplay-policy=no-user-gesture-required --enable-features=SharedArrayBuffer --service-pipe-token=8114776714988730591 --lang=en-US --app-path=/opt/Rocket.Chat/resources/app.asar --node-integration=false --webview-tag=true --no-sandbox --preload=/opt/Rocket.Chat/resources/app.asar/app/preload.js --background-color=#fff --guest-instance-id=1 --enable-blink-features --disable-blink-features --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=8114776714988730591 --renderer-client-id=6 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
 2000 pts/5    S+     0:00 grep --color=auto rocketchat-desktop
`

### Expected Behavior
the app does be visible

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
