### ISSUE TITLE
connection refused after ldap import

### ISSUE THREAD

**Issue by Sicoval31** [RocketChat/Rocket.Chat.Electron#1259]
Hi,
after a new install of rocketchat and a successfull import of ldap's users, nor the users or admin declared can't connect ...
If i ask a reset of the password (me as user or the admin user), i received the mail, can reset password and connect, but if I disconnect, i can't reconnect to RC (in navigator or with the client).

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
