### ISSUE TITLE
Screen sharing plugin not downloading on Ubuntu 15.10

### ISSUE THREAD

**Issue by brylie** [RocketChat/Rocket.Chat.Electron#126]
When making a call from version 1.1.0 on Ubuntu 15.10, we attempted to download the screen sharing plugin. When clicking screen share, the dialogue appears containing a 'download plugin' button. Clicking on the button yields no result, and we cannot see the console to troubleshoot this issue further.

**Comment by rodrigok** [comment]
We don't have support for screen sharing in Electron yet.

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat.Electron/issues/65
