### ISSUE TITLE
yarn start,如何调试代码，定位html元素呀？

### ISSUE THREAD

**Issue by keehao** [RocketChat/Rocket.Chat.Electron#1261]
## My Setup
- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
