### ISSUE TITLE
Must delete window-state-main.json in order to launch Rocketchat after reboot

### ISSUE THREAD

**Issue by tlyoder57** [RocketChat/Rocket.Chat.Electron#1262]
After I reboot, I have to delete window-state-main.json in order to launch Rocketchat.  If I don't delete the file, Rocketchat background tasks run but the GUI is not displayed.

## My Setup
- Operating System: Windows 10, version 1709
- App Version:  2.15.3
- Installation type: .exe

- [ x] I have tested with the latest version
- [x ] I can simulate the issue easily

### Current Behavior
  Reboot PC.  Launch Rocketchat.   No window appears.  Task Manager shows background tasks.

### Expected Behavior
 Window should appear.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
