### ISSUE TITLE
Support mac app  notarize hardenedRuntime

### ISSUE THREAD

**Issue by ljcp** [RocketChat/Rocket.Chat.Electron#1263]
## My Setup
- Operating System: macOS 10.14.5
- App Version: 2.15.3
- Installation type: dmg, pkg,app

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description
using notarize doesn't works

following all the steps to notarize the app from https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/ 

### Current Behavior
App crash when hardenedRuntime is set to true 

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000189e19502040
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2

kernel messages:

VM Regions Near 0x189e19502040:
    Memory Tag 255         0000189e19501000-0000189e19502000 [    4K] ---/rwx SM=NUL  
--> Memory Tag 255         0000189e19502000-0000189e1957f000 [  500K] r-x/rwx SM=COW  
    Memory Tag 255         0000189e1957f000-0000189e21428000 [126.7M] ---/rwx SM=NUL  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	0x0000189e19502040 0 + 27067308580928
1   com.github.Electron.framework 	0x000000010d8c5148 0x10c003000 + 25960776
2   com.github.Electron.framework 	0x000000010d8c3d3e 0x10c003000 + 25955646

```

### Expected Behavior
App should work fine with hardenedRuntime

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
