### ISSUE TITLE
scroll bar places up after click on chat

### ISSUE THREAD

**Issue by goodboy89** [RocketChat/Rocket.Chat.Electron#1266]
- Operating System:windows 10
- App Version: 2.15.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

when i open a new private or public chat , scroll bar is not at the last thread but instead it's up for few days or weeks ago and i have to scroll down to the last message.

**Comment by sparse91** [comment]
Same here!
I'm on Linux.

**Comment by brunohl91** [comment]
Any updates on this? Same thing here.

Win 10

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
