### ISSUE TITLE
Making WebRTC calls fails in Ubuntu 15.10, Electron 1.1.0

### ISSUE THREAD

**Issue by brylie** [RocketChat/Rocket.Chat.Electron#127]
# Observed behavior

When trying to make a WebRTC call, nothing happens on the receiving end.
# Expected behavior

When placing the call, a modal dialogue would appear on the receiving end, allowing the user to accept the call.
# Environment
- Ubuntu 15.10
- Rocket.Chat 0.19
- Electron 1.1.0
##

**Comment by rodrigok** [comment]
This do not seems to be a problem with Electron it self, do you have the same problem using google chrome?
