### ISSUE TITLE
Away status issue

### ISSUE THREAD

**Issue by umputun** [RocketChat/Rocket.Chat.Electron#1271]
## My Setup
- Operating System: OSX 10.14.5
- App Version: 2.15.3
- Installation type: app store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Away status (set to Enable Auto Away: True, Idle Time Limit: 60) constantly triggered if rocketchat window out of the focus (i.e. behind other windows). It seems to detect the system events somehow, but going back to away almost immediately after this. I.e. on activity in other windows status switching to green and back to yellow. 

### Current Behavior
see above

### Expected Behavior
I'd expect it to work with system-level idle, and see no good reason why away status set due to inactivity in rocketchat

**Comment by detoxhby** [comment]
ref https://github.com/RocketChat/Rocket.Chat.Electron/issues/1260
