### ISSUE TITLE
https://myrktserver/api/info

### ISSUE THREAD

**Issue by ChuckB0ris** [RocketChat/Rocket.Chat.Electron#1272]
## My Setup
- Operating System:

OS Name: Microsoft Windows 10 Pro 

OS Version: 10.0.17134 N/A Build 17134

OS Manufacturer: Microsoft Corporation

OS Configuration: Standalone Workstation

OS Build Type: Multiprocessor Free
- App Version: 2.15.3
- Installation type: 
exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![image](https://user-images.githubusercontent.com/35690704/60430665-8664ca80-9c06-11e9-8d4c-ee8af287804d.png)
![image](https://user-images.githubusercontent.com/35690704/60430711-a2686c00-9c06-11e9-8368-b5c17fc5d0f3.png)

### Current Behavior

When I try to access the server from windows desktop app it doesn't work, this works from ios/android app and web browser, only having issues with desktop client.
### Expected Behavior

Please provide some fixes, the https://rktserver/api/info
is accessible via browser
{"version":"0.74.2","success":true}

**Comment by reetp** [comment]
Please test against open.rocket.chat

You really ought to consider upgrading as you are getting left behind. 

Current stable is v1.2.1

**Comment by ChuckB0ris** [comment]
Hi @reetp,
So I am using docker-compose to compose a rocketchat-mongo-traefik env
I just used rocket.chat:latest and upgraded to {"info":{"version":"1.1.3"},"success":true}
The problem with the desktop client is still there, cant connect to the server, no valid server found at url
Any suggestions?

Thanks

**Comment by ChuckB0ris** [comment]
{"info":{"version":"1.2.1"},"success":true} and still the same issue

**Comment by ChuckB0ris** [comment]
Fixed the desktop client issue, by moving from traefik to nginx.
