### ISSUE TITLE
"Show on unread messages" not working

### ISSUE THREAD

**Issue by gackerfred** [RocketChat/Rocket.Chat.Electron#1277]
## My Setup
- Operating System: Windows 10 - 1809
- App Version: 2.15.2 & 2.15.3
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
"Show on unread messages" option is not working anymore since release 2.15.2
Issue has been observed on all machines checked. (all Windows 10)
Testing with 2.15.1 it does work.

### Current Behavior
Window is not shown on a received message, while the "Show on unread message" option is active.

### Expected Behavior
Window should be opened and highlighted on taskbar, once an unread message is available.

**Comment by aimador** [comment]
same here.

**Comment by HassanHashemi** [comment]
This issue still exists on 3.0.4
