### ISSUE TITLE
Copy/Paste not working in 2.15.3

### ISSUE THREAD

**Issue by clairesureau** [RocketChat/Rocket.Chat.Electron#1279]
I use the Rocket chat desktop application 2.15.3.
I want to copy an message with an image to paste it in other private message.

The copy works. But it can't paste the image into my other message window.

**Comment by nrenich** [comment]
I have noticed this on multiple platforms (Linux/Win10/macOS) using right click, Copy. Then when you try to right click and Paste in the chat text field it does nothing. However, if you use the keyboard shortcut for Paste, it works. (ctrl-v / command-v)

**Comment by vladimirschuka** [comment]
I have the same issue!!!
Please fix it 
Windows 10 PRO
COPY - PAST doesn't work! 
It is so annoying that such a small thing doesn't work.

**Comment by martinhoess** [comment]
This problem unfortunately still exists and is very annoying

OS: Windows 10 (on my Mac it works fine)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by prayingmantis1979** [comment]
Does no work in 3.7.5. I have no rights to reopen this issue.
![изображение](https://user-images.githubusercontent.com/80267795/149085285-fcea2ad1-9235-4a95-b2a3-0fc5b2222357.png)
