### ISSUE TITLE
OS X native client CPU usage spikes when avatars have animation

### ISSUE THREAD

**Issue by PRI-mcallen** [RocketChat/Rocket.Chat.Electron#1281]
Your Rocket.Chat version: Version 1.3.1 (15)

We have a lot of users with animated avatar gifs (for better or worse).  Using the native OS X client I notice that my CPU usage spikes to 100% and battery drops quickly if I'm in a channel with these animated avatars.  If I got to a channel without them, CPU usage is normal.  This CPU hit makes the native client barely usable.  Typing starts to noticeably lag, for example.

The web client is better, but anecdotally I see 20-30% CPU use by Chrome when using the web client with these animated avatars.  It drops when I go to a channel with no animation.

For the short term, trying to convince our users to not use GIFs, but in the long term it would be ideal to have the client not max out the CPU in this scenario.

**Comment by regetskcob** [comment]
+1
