### ISSUE TITLE
RocketChat login failures, multiple users

### ISSUE THREAD

**Issue by abrown0803** [RocketChat/Rocket.Chat.Electron#1282]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.3, and 2.15
- Installation type: exe

- [x] I have tested with the latest version X
- [x] I can simulate the issue easily X

## Description
Cannot login to an account that used to be able to login and use RocketChat

!
![image](https://user-images.githubusercontent.com/52296977/62374459-a3403680-b501-11e9-8ab3-57878e55b9da.png)

### Current Behavior
nothing cannot login

### Expected Behavior
Login and use chat like normal
[RocketChat.docx](https://github.com/RocketChat/Rocket.Chat.Electron/files/3461513/RocketChat.docx)

[RocketChat.docx](https://github.com/RocketChat/Rocket.Chat.Electron/files/3461520/RocketChat.docx)

**Comment by engelgabriel** [comment]
Are you able to log in when access via a regular browser?

**Comment by abrown0803** [comment]
We rebuilt the server. We got it working this morning.

Thanks for your response!
