### ISSUE TITLE
add dark mode and follow system default on macOS

### ISSUE THREAD

**Issue by foss-** [RocketChat/Rocket.Chat.Electron#1283]
## My Setup
- Operating System: macOS 10.14.6
- App Version: 2.15.3

## Description
Adding a dark theme to default electron app would be welcome.

### Current Behavior
No dark theme available.

### Expected Behavior
Dark theme should be available in settings. Ideally it would follow the system default on macOS.

There was an old issue requesting dark mode, but it was closed as invalid. Not sure how the feature request is invalid though:
https://github.com/RocketChat/Rocket.Chat.Electron/issues/666

**Comment by reetp** [comment]
Please don't just keep opening duplicate Issues. It isn't going to get fixed any faster.

Follow up on some of the existing ones please.

https://github.com/RocketChat/Rocket.Chat/pull/11071

**Comment by geekgonecrazy** [comment]
Yes electron actually adapts to color scheme in rocket.chat so if RocketChat/Rocket.Chat#11071 solved then this happens by default

**Comment by foss-** [comment]
> Please don't just keep opening duplicate Issues.

Not as if I hadn't done a search first. If "Dark Mode" was included in the title for ticket #11071 it would show for that search term. Excuse the dupe anyways.

**Comment by reetp** [comment]
Just do a search - this would have done it.

https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+dark

**Comment by foss-** [comment]
As mentioned my mistake was to search for "dark mode". Should have made that more clear and yes, my mistake. Should have used "dark".
