### ISSUE TITLE
Where is the server list ?

### ISSUE THREAD

**Issue by h4wkmoon** [RocketChat/Rocket.Chat.Electron#1284]
## My Setup
- ubuntu - gnome-shell (not the std ubuntu desktop)
- snap

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I'd like to connect my rocketchat client to an additionnal server. From the [doc](https://rocket.chat/docs/user-guides/connecting-to-a-server/#connecting-to-more-than-one-server), i read that I should look for the server list, and click on add. That seems quite obvious, but I can't find the server list.

I check every menu I could find no luck.

### Current Behavior
No server list visible.

### Expected Behavior
Server list visible.

**Comment by tassoevan** [comment]
Please enable it using the menu `View > Server list`.

**Comment by hullen** [comment]
hi @h4wkmoon, please see how to on this print:
https://d.hullen.me/EZHdUV
