### ISSUE TITLE
Error after upgrade to 2.15.4

### ISSUE THREAD

**Issue by hasmukhbarochiya** [RocketChat/Rocket.Chat.Electron#1289]
## My Setup
- Operating System: Ubuntu 18.04.2 lts
- App Version: 2.15.4
- Installation type: Snap

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Rocket chat is not opening in the foreground, as well as the tray icon is also gone from the top bar which is working fine before the update. 

### Current Behavior
Not opening in Foreground. Also not showing tray icon. 

### Expected Behavior
At-list show in the foreground and need to show the tray icon.

**Comment by regetskcob** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1288#issue-478803011

**Comment by hasmukhbarochiya** [comment]
Yes, I don't know that, I am closing.
