### ISSUE TITLE
Mac desktop client: Reload minimizes instead

### ISSUE THREAD

**Issue by rebeld** [RocketChat/Rocket.Chat.Electron#129]
Rocket.Chat version: 0.20.0
Mac Desktop App Version: 1.1.0(10)

Selecting 'Reload' from the View menu (or Cmd + R) minimizes the window to the dock instead of reloading. Subsequent menu commands (including Quit or Cmd + Q) result in error.

<img width="428" alt="screen shot 2016-03-02 at 9 20 27 am" src="https://cloud.githubusercontent.com/assets/329962/13462981/1c900600-e058-11e5-95d1-deaae2bf1297.png">

The app must then be force quit.

**Comment by rodrigok** [comment]
Can you test with our current develop version? https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/1.2.0

**Comment by rebeld** [comment]
Yeah, the behaviour is correct in v1.2.0. Reload (cmd+R) reloads the view, Quit (cmd+Q) continues function.

**Comment by rodrigok** [comment]
Great
