### ISSUE TITLE
Stuck on Cloud login page

### ISSUE THREAD

**Issue by jwhall** [RocketChat/Rocket.Chat.Electron#1293]
## My Setup
- Operating System: Windows 10 Pro x64
- App Version: 2.15.3
- Installation type: exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Cannot log into RocketChat Cloud, server window gets stuck on login screen

### Current Behavior

I'm attempting to log into the RocketChat Cloud to manage integration with my on-prem server. I'm doing so with the Admin -> Marketplace -> Login button. I get the RC Cloud login window, enter my known valid creds (i've tested from the website) and I'm immediately returned to the login prompt. There's also no way to return back to the normal chat interface from here - even if I close the Windows app and reopen I'm brought back to the Cloud Login page. Reloading doesn't help either, and using View -> Back does not take me back to another page.

### Expected Behavior

Logins should work. Failed logins or errors should drop me out back to the Administration page with an error.

**Comment by tomhung** [comment]
Did you ever get this solved?  I'm stuck there as well.

**Comment by pcmerc** [comment]
Bump +1

**Comment by Stratus41298** [comment]
Issue still exists. I was able to get back out by removing the server from the list (right click the server) and re-adding. For whatever reason I get wrong login creds no matter what. Forgot password does nothing.

**Comment by Aniz** [comment]
Same here :(

**Comment by nixoid** [comment]
same here. do i really have to remove the server to escape the login form OMG

**Comment by Stratus41298** [comment]
Yeah. You do. It's not too annoying to put back but should be fixed.

**Comment by bjoernHeneka** [comment]
I have the same problem. When having a look in the console i retrieve the following error:
`{"error":"oauth_workspace_client_different_account","requestId":"b72fb2d8-5b7e-48bd-9dbb-fbf9d35af37d","status":400}`

**Comment by nightphobos** [comment]
In my case it happed when I started to connect self-hosted installation with cloud account. I already created cloud account, and entered code of installation on local Connectivity Service page. 

My server user email and cloud are different, so after being stuck I entered exact cloud credentials, and successfully logged in, having chained my local account and cloud account. 

It was quite unexpected for me, I just wanted to register server, not connect my local-to-cloud users, but it solves the problem.

**Comment by mohammedragabsoftxpert** [comment]
Same error!!

**Comment by mohammedragabsoftxpert** [comment]
> Issue still exists. I was able to get back out by removing the server from the list (right click the server) and re-adding. For whatever reason I get wrong login creds no matter what. Forgot password does nothing.

Same error, that worked

**Comment by jackhk88** [comment]
Same issue here, Win10.64 and Rocket.chat client V2.17.11.
This is very enoying as I cannot register my own server to get notifications, and time is ticking like a bomb to August 14th to register.
So stressful.

**Comment by jackhk88** [comment]
some ideas to solve here https://forums.rocket.chat/t/cant-install-app-form-marketplace-stuck-in-an-authentication-loop/6018/13
My Server is in Docker on win10 "server". I spent a lot of time to have it up and running but I do not know how to follow the steps indicated in the link above, especially how to enter in command mode in docker.

**Comment by mojitaleghani** [comment]
@gabriellsh 
Hi. The same issue here....I'm using a double instance of rocketchat behind a nat. I can log in to cloud.rocket.chat manually but from connectivity I faced 

```
{status: 400, error: "oauth_invalid_request", requestId: "######"}
error: "oauth_invalid_request"
requestId: "#####"
status: 400
```

and still not solved

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
