### ISSUE TITLE
Support for WebAuthn / U2F when using SSO?

### ISSUE THREAD

**Issue by fillup** [RocketChat/Rocket.Chat.Electron#1294]
## My Setup
- Operating System: Windows 10
- App Version: v2.15.3
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
We are set up to use SSO with our corporate SAML IdP. Our IdP uses FIDO U2F for 2-step verification with yubikeys. When using the Electron based app it does not function properly. It does not trigger the authentication challenge and the light on the yubikey does not blink. Is this a known issue or limitation? Can anything be done to fix this?

### Current Behavior
U2F authentication is not triggered, perhaps the API needed for this is not available in Electron / Chromium?

### Expected Behavior
Given that Electron is built on Chromium and Chromium supports U2F I expected it to work.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by elg** [comment]
Seems to be present in the last version.
