### ISSUE TITLE
Clear cache functions do not seem to work

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.Electron#1295]
## My Setup
- Operating System: macOS 10.14.6
- App Version: 10.14.5
- Installation type: DMG

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When trying to clear the cache using the menubar options (View → Reload ignoring cache) or when removing a server from the server list, the local cache isn't getting cleared.

### Current Behavior
Cache isn't getting cleared.

### Expected Behavior
Cache should be cleared.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
