### ISSUE TITLE
Feature request: Close Icon or Esc-Key for txt files 

### ISSUE THREAD

**Issue by LeT0R** [RocketChat/Rocket.Chat.Electron#1296]
## My Setup
- Operating System: Mircrosoft Windows 10 Pro
- App Version: 2.15.0
- Installation type: exe

- [x] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

upload a txt file and open it in rocket chat

### Current Behavior

cannot find any obvious way to close the file
have to use View -> Back (Alt + Left Arrow) 

### Expected Behavior

- a close icon in the right corner 
- esc key to close the file view
- back key to close the file view

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
