### ISSUE TITLE
Windows Application Try Icon not working

### ISSUE THREAD

**Issue by betkani** [RocketChat/Rocket.Chat.Electron#1298]
I am using Desktop app, we have a version 2.15.5, but when someone is writing me in app icon below on task-bar, where is no try icon showing that i have 1 or 2 unread messages.

in account setting is true - "Unread Tray Icon Alert" 

no one can understand that he must open to read new messages

![try_icon](https://user-images.githubusercontent.com/54139552/63090102-46199b80-bf6b-11e9-8fb1-4c6aa40c0459.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
