### ISSUE TITLE
"Show window on unread changed" doesn't bring application into foreground (on Windows)

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.Electron#1299]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.5
- Installation type: .exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

Apparently on Windows OS, the option `Show window on unread changed` doesn't actually bring the application into the foreground. It pops up, just keeps staying in the background.

### Current Behavior

On new messages, the application does not jump into foreground 

### Expected Behavior

It should jump into foreground when there is a new message coming in.

**Comment by PauIGB** [comment]
have the same problem on Windows 10 in 3.2.2 ver.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
