### ISSUE TITLE
Auto update download notification not working

### ISSUE THREAD

**Issue by sandreddu** [RocketChat/Rocket.Chat.Electron#1300]
## My Setup
- Operating System: Windows 10 1803
- App Version: 2.15.3
- Installation type: exe

- [ ] I have tested with the latest version
              Issue is related to 2.15.3 and it is the version rolled out to the users as of today
- [x ] I can simulate the issue easily

## Description
After selecting to update to the latest version, we are informed that "you will be notified when the update is ready to install" but nothing happens after waiting for several hours
![image](https://user-images.githubusercontent.com/47738900/63593143-3f160d00-c5ab-11e9-93bf-a70d3a3c8256.png)

### Current Behavior
nothing happens

### Expected Behavior
a notification appears and the installer starts

**Comment by icerootsvw** [comment]
Same here on your windows 10 systems. Exactly the same as in the description

**Comment by sandreddu** [comment]
> 
> 
> I"m not sure how to properly mark this but I think this is the same bug I reported as #1301, looks like you beat me by 10 minutes. I"m still having this issue.

Hi
We also still have the issue. Really frustrating, since now our users are starting to complain how the updating process is being handled. I hope someone takes a look at any of our two tickets soon.

**Comment by stonewoodman** [comment]
The same behavior already exists in earlier version #1205

**Comment by sandreddu** [comment]
Meanwhile I have a new behaviour, in which if I select the "help" menu and then "about rocket.chat" -> "check for updates" -> "install update" I receive a pop-up according to which "You will be notified when the update is ready to be installed" - clicking OK here randomly crashes the client.
Is there any way I can display rocket.chat logs on a Windows client? sorry for the noob question but I really can't find this documented anywhere.

**Comment by nyetwurk** [comment]
Same.

**Comment by franckadil** [comment]
I can confirm tested with 2.15.5 and 2.16.0

**Comment by sandreddu** [comment]
Multi-user install.
Still not working with 2.16.2. The installer is downloaded correctly at the location 
`C:\Users\username\AppData\Local\rocketchat-updater\pending` but then it disappears without a trace.
A new 
`.updaterid`
file is created in the rocketchat appdata/roaming folder but then nothing happens.
I will try a "clean" reinstall of 2.15.5 to figure out what might be the difference

**Comment by sandreddu** [comment]
Same issue occuring between 2.17.0 and 2.17.1. The issue has now become an insider joke inside the company.

**Comment by icerootsvw** [comment]
I raised a support ticket ( ID 6067) pointing to this bug

**Comment by g2flyer** [comment]
+1

**Comment by torrycrass** [comment]
+1

**Comment by dennismeissel** [comment]
2.17.9-11 the same thing.

**Comment by pavananand** [comment]
Is there any update on this issue?

**Comment by mmgoilf** [comment]
Same issue here. Very frustrating for our windows users.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by dennismeissel** [comment]
For me the problem has been solved with the latest release. 

Thank you!
