### ISSUE TITLE
cannot post unicode characters in mac app since latest update

### ISSUE THREAD

**Issue by thawn** [RocketChat/Rocket.Chat.Electron#1302]
## My Setup
- Operating System: OSX 10.13.6
- App Version: 2.15.5
- Installation type: app store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily
- [x] I tested the web app in Firefox and there the issue does not occur

## Description

Try to post a unicode umlaut character using the mac desktop app by pressing Alt+u and then u a or o.

### Current Behavior

The app does not accept the input and noch character is posted.

### Expected Behavior

The app should accept unicode umlaut character input and post ü ä or ö.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
