### ISSUE TITLE
Homepage offers v2.15.3 for download

### ISSUE THREAD

**Issue by danielrentz** [RocketChat/Rocket.Chat.Electron#1303]
## Description
https://rocket.chat/install offers v2.15.3 in desktop downloads (linux, win, mac). Current version is 2.15.5

**Comment by antoniodfr** [comment]
This causes Windows clients to show the update window again and again.

**Comment by sandreddu** [comment]
Are you sure about this? I see the 2.15.5 in the direct download link on the home page, but the Windows clients still cannot upgrade through the update window

**Comment by danielrentz** [comment]
New version, same problem. (Non-functional) automatic update tells me about 2.16.2, but homepage still offers 2.15.5.

**Comment by bbrendon** [comment]
Same with 2.17.

**Comment by danielrentz** [comment]
no direct downloads anymore on homepage.
