### ISSUE TITLE
Unable to start Rocket.Chat production version

### ISSUE THREAD

**Issue by brifly** [RocketChat/Rocket.Chat.Electron#1309]
## My Setup
- Operating System: Windows 10
- App Version: 2.16.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

The current production version of rocket chat does not start. 

### Current Behavior
Nothing happens when opening:
- nothing in the windows tray
- no logs in the app directory 
- only one line of output to the console
- no identifiable process in task manager
- nothing in the windows event log
- app is not being blocked by security software

When run from the command line it prints the following message:
![image](https://user-images.githubusercontent.com/6075987/64223376-512a7080-cf06-11e9-9606-e2561c7994ff.png)

I have compiled and built the current version from source:
Running dist/win-unpacked/Rocket.Chat.exe after running `yarn release` has the same issue
Running dist/win-unpacked/Rocket.Chat.exe after running `yarn release-dev` works fine

I've tried:
- installing for all users
- installing for just me
- Running in windows 8 compatibility mode
- Running with as admin

### Expected Behavior
It should open normally

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
