### ISSUE TITLE
UX: search channels lose focus and close it on first action

### ISSUE THREAD

**Issue by lascapi** [RocketChat/Rocket.Chat.Electron#1310]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.2 and 2.15.5 
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Hi, did you notice a UX bug, when you're on the bottom of a conversation and you scroll down then you scroll up, the scroll is pinned ! And if you scroll down,you move the mouse and you scroll up, then the scroll is working !! Little bug, but annoying sometimes ! 

### Current Behavior
Sometimes the mouse scroll is blocked. 

### Expected Behavior
The mouse scroll must not be blocked.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
