### ISSUE TITLE
Activating rocket.chat cloud through the app breaks the app.

### ISSUE THREAD

**Issue by b-** [RocketChat/Rocket.Chat.Electron#1311]
## My Setup
- Operating System: macOS Catalina 10.15 Beta (19A546d) (latest build as of 2019-09-04)
- App Version: 2.15.5
- Installation type: Mac app store

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

Screenshot of what I see now: https://imgur.com/a/rWw201O

### Current Behavior

I end up at a modal dialog with a different sign in, and I can't find any way to escape it
### Expected Behavior

I think that I should be able to escape the modal dialog and go back to my server...

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
