### ISSUE TITLE
Strange behavior of the user-search form

### ISSUE THREAD

**Issue by dimqakolyada** [RocketChat/Rocket.Chat.Electron#1314]
## My Setup
- Operating System: Windows 7 Professional
- App Version: 2.15.3.1057
- Installation type: exe

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
![img-2019-09-11-17-51-47](https://user-images.githubusercontent.com/25640255/64698756-e6a4a200-d4bc-11e9-9518-904011403f34.png)
In our system, all users have first and second names. So, for example, I want to find Trump Donald.

### Current Behavior
I type "Trump" into the search field, but I see only 7 users with such second name, but there is no Donald Trump...
OK. I continue typing "Trump Donald" But I see all Donalds even without Trump in ASC order. So, as well, there is no Trump Donald...
By the way, we use Cyrillic.

### Expected Behavior
If I type Donald Trump I want to see all users with such string in name despite of register.

**Comment by NotACreativeUsername** [comment]
I also have this error:
App version: 3.0.7
OS: Windows 10 Enterprise
Installation: exe
Server version:  3.7.2
@diegolmello

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
