### ISSUE TITLE
Notifications Should Remain in Windows Notification List Until Dismissed by User

### ISSUE THREAD

**Issue by arminlinzbauer** [RocketChat/Rocket.Chat.Electron#1316]
## My Setup
- Operating System: Windows 10 1903 (OS Build 18362.356)
- App Version: 2.15.5
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Rocket.Chat Notifications disappear from Windows 10 Notification List after Notification Timeout. **I've had this issue with all Windows 10 Versions and all Rocket.Chat Client Versions.**

### Current Behavior
Notifications are not accessible in the Windows 10 Notification List after the timeout. They show up for the configured number of seconds and then disappear without a trace.

### Expected Behavior
Notifications are kept in the Windows 10 notification list until dismissed by the user (as is the case with many other apps including Outlook, OneDrive, etc...)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
