### ISSUE TITLE
Install update Button does not have any effect on Mac OSX 10.14.6

### ISSUE THREAD

**Issue by Thomasillo** [RocketChat/Rocket.Chat.Electron#1317]
## My Setup
- MacOSX 10.14.6
- App Version: 2.15.0 (Desktop App)
- Installation type: ?

- [ ] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
After checking for updates, I get the "Update available" Popup window, asking me to install 2.15.5

The buttons "Remind me later" and "Install update" are without function.
So I can't update the version this way.
The button "Skip this version" works. 

### Current Behavior
Mouseovever seems to work, the buttons slightly change appearance.
On pressing one of the mentioned buttons, nothing happens.

### Expected Behavior
The action that is written on the button.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
