### ISSUE TITLE
Rocket.Chat App (2.15.5), Windows 10: Channel window can't scroll without mouse wheel

### ISSUE THREAD

**Issue by hasuino** [RocketChat/Rocket.Chat.Electron#1318]
## My Setup
- Operating System: Windows 10, 64 Bit, Intel i5 processor
- App Version: 2.15.5
- Installation type: unknown, I assume it has been .exe in the beginning

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Maybe it's invisible, but I have not seen any scrollbar within the app, and
I've an ergonomic mouse without any wheel, therefore I can't scroll down
to see all channels and contacts.
Is this a bug or has this been designed as feature? Would it be possible
to add a simple scroll bar (it might appear when the mouse pointer is
moved to it so it won't waste precious space when inactive) so I can
scroll down and up within channels and contacts?

Thanks in advance :)

### Current Behavior
See above: No possibility to scroll without mouse wheel

### Expected Behavior
There should be a possibility (by keyboard or by mouse pointer)
to scroll within channels and contacts :)

**Comment by vkuhnde** [comment]
Have you tried clicking an empty space in the chats list and then using the arrow keys or page up / down key on your keyboard? Works for me on Windows 10 1809 with Rocket.Chat 2.15.5.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
