### ISSUE TITLE
Mobile keyboard opens automatically on docked tablet

### ISSUE THREAD

**Issue by jkshapiro** [RocketChat/Rocket.Chat.Electron#1319]
### Description:

I have a MS Surface tablet computer, with a keyboard, mouse, and monitors attached via a docking station. When it's docked, it's essentially a desktop computer.

In the Rocket.chat desktop client, whenever the "Message" area has focus, the onscreen keyboard comes up on my non-touchscreen, external monitors. This includes when the program loads, and when I switch from one channel to another.

I first noticed this in 2.15.3 and it is still the case in 2.15.5.

### Steps to reproduce:

1. On a docked MS Surface tablet computer running Windows 10 Enterprise v1709, open the desktop Rocket.chat app.

### Expected behavior:

Onscreen keyboard does not appear.

### Actual behavior:

Onscreen keyboard does appear.

**Comment by jkshapiro** [comment]
(Previously reported at https://github.com/RocketChat/Rocket.Chat/issues/15282)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
