### ISSUE TITLE
No unread message count barge

### ISSUE THREAD

**Issue by no-nice-username** [RocketChat/Rocket.Chat.Electron#1320]
## My Setup
- Operating System: OSX 10.14.6 
- App Version: 2.15.5
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Sometimes (actually pretty often) there is no unread count barge on the app icon.
I do see a dock icon jumping when I have a new direct message, but there is no unread count barge, so if you missed that jump - you will never know, that there is something unread.

### Current Behavior
No unread barge on the app icon

### Expected Behavior
App icon should display the quantity of unread private messages.

**Comment by no-nice-username** [comment]
Bump!
The issue still exists and makes using the app nearly impossible (who ever needs chat app without notifications?)

**Comment by areqq** [comment]
i have the same problem too

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
