### ISSUE TITLE
The size of the chat window changes when a new message arrives.

### ISSUE THREAD

**Issue by Softace42** [RocketChat/Rocket.Chat.Electron#1321]
## My Setup
- Operating System: Windows 7 x64 Pro
- App Version: 2.15.5
- Installation type: exe

- [x ] I have tested with the latest version

## Description
I use 2 monitors. The chat window is open on an additional monitor (full screen). When a new message arrives, the chat minimizes from full-screen to windowed mode.

After detecting the problem in version 1.15.5, installed version 1.15.3, the problem went away and reappeared after reinstalling version 1.15.5.

Deletion was performed completely, without saving user data.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
