### ISSUE TITLE
Continuously creating files on temp folder under Windows

### ISSUE THREAD

**Issue by tsmgodoi** [RocketChat/Rocket.Chat.Electron#1323]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.5
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Rocket.Chat keeps creating two files per minute of about 530 KB on my temp folder under Windows 10 when the server is offline and Rocket.Chat keeps trying to reconnect to it. It is a problem because the temp folder can grow to GB after a few days.

1. Add a new valid Rocket.Chat server
2. Make the server offline (or maybe unplug your Internet)
3. Look at your temp folder, it'll create two 530 KB files for each retry (each 60 seconds)

The files are on the format "<hash>.tmp.node". For example:
9bfb95ec-2aee-4120-a1dc-2c119f84f517.tmp.node

### Current Behavior
The temporary files should be deleted after each try.

### Expected Behavior
The files are kept there, which can cause the temp folder to grow bigger over the days.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
