### ISSUE TITLE
Tela de contatos some no modo estendido

### ISSUE THREAD

**Issue by marzari** [RocketChat/Rocket.Chat.Electron#1326]
Ao selecionar o modo estendido dos contatos, os mesmos desaparecem da tela e não é possível voltar

## My Setup
- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
