### ISSUE TITLE
Client window disappears if monitor setup is changed (deactivating a monitor in a multi-monitor setup)

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat.Electron#1329]
## My Setup
- Operating System: Win10 1809
- App Version: 2.15.5
- Installation type: exe
- 2 monitors

[ x] I have tested with the latest version
[ ] I can simulate the issue easily -> does not happen every time

## Description
This is not a big issue, but I just stumbled upon it.
If you have a multi-monitor setup, eg. 2 monitors, and you disable the monitor the RC client is running on, the window will not reappear, if you maximize it from the task bar. You'll see the maximizing animation, but that's it.
If you re-enable the monitor, the RC client will not appear anymore. You have to kill and restart the client.
Win key + arrow keys will not position the window anywhere, although it is still visible in the ALT-TAB list.

### Current Behavior
RC window dissappears, if the monitor RC is running on is deaktivated. Re-enabling the monitor does not ameliorate the situation. Win-key + arrow keys or ALT+TAB do not work either. Restarting the client is the only solution.

### Expected Behavior
RC window should be pushed to the other monitor. WIN+arrow keys should grab the window and move it around.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
