### ISSUE TITLE
Update cannot initiate.

### ISSUE THREAD

**Issue by igordgeorgiev** [RocketChat/Rocket.Chat.Electron#1331]
Update is offered when Rocket starts on Windows startup. After selecting "Install Update", a notification says I will be notified when the update can be installed and that never happens. Been like that for months

**Comment by reetp** [comment]
Please close as this is a duplicate of several similar bugs.

https://github.com/RocketChat/Rocket.Chat.Electron/issues?utf8=%E2%9C%93&q=is%3Aissue+update

You will have to download and manually update

**Comment by igordgeorgiev** [comment]
Closed due to duplication of the issue
