### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by dinosubasic** [RocketChat/Rocket.Chat.Electron#1333]
## My Setup
- Operating System: Win10
- App Version: v2.15.5
- Installation type: rocketchat-setup-2.15.5.exe

- [x ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
Any new message, notification is missing. Icon in taskbar is not changing color.

**Comment by reetp** [comment]
Read the links here:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Some server information is required.

Also check you push notifications settings. Follow the logic here.

https://rocket.chat/2019/09/27/push-notification/

**Comment by ddbrandonb** [comment]
Pretty sure this is a duplicate of #1376 ?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
