### ISSUE TITLE
Email notification for a message is sent even if you read the message on mobile.

### ISSUE THREAD

**Issue by igordgeorgiev** [RocketChat/Rocket.Chat.Electron#1335]
A message was received and read on the mobile version of the app. An email notification for those messages was sent.

**Comment by reetp** [comment]
Not sure what relevance this has to the Electron desktop application.

You probably ought to read this and check the flow diagram:

https://rocket.chat/2019/09/27/push-notification/

**Comment by igordgeorgiev** [comment]
> Not sure what relevance this has to the Electron desktop application.
> 
> You probably ought to read this and check the flow diagram:
> 
> https://rocket.chat/2019/09/27/push-notification/

I will test again, but it seems that there should not be email notification if the user is chatting with the sender (not ignoring him, replying and so on)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
