### ISSUE TITLE
thread view unreadable for code blocks

### ISSUE THREAD

**Issue by torpesco** [RocketChat/Rocket.Chat.Electron#1336]
## My Setup
- Operating System: Arch Linux
- App Version: 2.15.5
- Installation type: AUR package

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Code blocks delineated with lines of three back-ticks are limited to something like 35 characters due to the narrow width of the thread view. This makes text copied from terminals or code very difficult to read.

### Current Behavior
See description.

### Expected Behavior
Allow the thread view to optionally fill the whole width of the chat pane.

**Comment by reetp** [comment]
Please close this and follow up here:

https://github.com/RocketChat/feature-requests/issues/159

**Comment by torpesco** [comment]
Thanks
