### ISSUE TITLE
Installation of Client under CentOS 8 [libappindicator dependency]

### ISSUE THREAD

**Issue by ZenHarbinger** [RocketChat/Rocket.Chat.Electron#1337]
## My Setup
- Operating System: CentOS 8
- App Version: rocketchat-2.15.5
- Installation type: rpm

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I cannot install RPM

### Current Behavior

RPM requires libappindicator which does not exist for CentOS 8, however libappindicator-gtk does exist, could this be a suitable replacement?

So the RPM does not install.

### Expected Behavior

Installation to succeed.

**Comment by aminvakil** [comment]
Same error here.

**Comment by cmwik** [comment]
Same issue. Only source I am finding for libappindicator on CentOS 8 is a paid dnf repo https://www.getpagespeed.com which is not an option for me.

**Comment by ZenHarbinger** [comment]
What I ended up doing is installing it as a flatpak.
I at least get an app that I can run, but I don't get an indicator icon in the tray.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
