### ISSUE TITLE
Video call notification bug on our Rocket chat server -  https://racingandsports.rocket.chat/ 

### ISSUE THREAD

**Issue by JohnnyRahul** [RocketChat/Rocket.Chat.Electron#1338]
## My Setup
- Operating System: Windows 7 
- App Version: Version 2.15.5
- Installation type: <Direct download>

- [x ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
<
![Video call notification bug](https://user-images.githubusercontent.com/56241030/66280673-61eb4f00-e8d5-11e9-9457-6a796b359d7f.PNG)
>

### Current Behavior
<Looks like there is bug on our rocket chat server. When a user is offline I'm always getting a video call notification (it's happening only to me).

Could you please look into it and get back to me>

### Expected Behavior
<If a user is online and actually doing a video call request then I should get a notification>

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
