### ISSUE TITLE
Right click reload server

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#134]
Occasionally servers restart and if they get in a broken state they just show a blue screen.  We need the ability to refresh that server.

You can reload the entire app or click view reload.  But then its having to reconnect to all servers.

**Comment by rodrigok** [comment]
Sure, as I will change the CMD+SHIFT+I to open the developer console of current server I can change the CMD+R to reload the current webview and add another option to reload the entire app.

**Comment by geekgonecrazy** [comment]
Sweet, that'd be perfect

**Comment by geekgonecrazy** [comment]
:+1:
