### ISSUE TITLE
Binary downloads are in the Code tab

### ISSUE THREAD

**Issue by Chealer** [RocketChat/Rocket.Chat.Electron#1348]
I failed to find the installer for Rocket.Chat.Electron, and had to consult the README to find it. I then realized the problem was very simple - the Releases "tab" is inside the "Code" tab, as can be seen in the following screenshot:
![Rocket Chat website](https://user-images.githubusercontent.com/486141/66655512-31bfeb00-ec0a-11e9-8a16-dde9c4836e18.PNG)
Yet, the Releases tab contains all releases, not just source code packages.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by Chealer** [comment]
The Code tab changed a lot, but I am afraid releases are still only accessible there. Unfortunately I cannot reopen this "issue".

**Comment by jeanfbrito** [comment]
I dont think we can change it. Its the way Github is.

**Comment by Chealer** [comment]
Thank @jeanfbrito
I do not master GitHub enough to confirm or infirm that. If for example [I look at the Stretchly project](https://github.com/hovancik/stretchly), it is also affected. So whether or not this is configurable, I recommend making sure GitHub is tracking its issue with its default configuration.
