### ISSUE TITLE
App does not open.

### ISSUE THREAD

**Issue by holzfelix** [RocketChat/Rocket.Chat.Electron#1349]
#735  My Setup
- Operating System: Windows 10
- App Version: 2.15.5
- Installation type: exe

With Windows clients there is the problem that the application does not open. The app starts but the app window does not open.

If you click on the tray icon with a straight click on show then the application opens. 

Does anyone know the problem and has a tip to solve it permanently? 

Thanks

**Comment by Sicoval31** [comment]
I think you need to edit the window-state-main.json files and play with this command : 
  "isMaximized": true,
  "isMinimized": false,
  "isHidden": false,

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
