### ISSUE TITLE
voice calls does not ring

### ISSUE THREAD

**Issue by holzfelix** [RocketChat/Rocket.Chat.Electron#1350]
- Operating System: Windows 10 / Mac OSX
- App VErsion - 2.15.5

as soon as a voice call is started it does not ring on the opposite side. 

How can this be fixed?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
