### ISSUE TITLE
Rocket.Chat app forgets passwords

### ISSUE THREAD

**Issue by AndreSomers** [RocketChat/Rocket.Chat.Electron#1354]
## My Setup
- Operating System: Ubuntu 19.04
- App Version: 2.16.0
- Installation type: package from RocketChat website

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

Rocket.Chat does not keep the login information for chat servers. It requires a login on every restart of the application

### Current Behavior
Rocket.Chat requires a log in for the configured chat service(s) on every restart. It used to remember the login.

### Expected Behavior
Rocket.Chat should remember the login on restart, and not ask to log in again.

**Comment by djdi** [comment]
Same problem. Tested and can simulate the issue easily on the following setup:

Operating System: Windows 10
App Version: 2.16.2

**Comment by sgostelow** [comment]
Yes, we've also experienced this after updating.

Operating System: Windows 10
App Version: 2.16.2

**Comment by marcosmolinamaxicon** [comment]
Check in Rocket.chat
"Administration > Accounts> Forget User Session on Window Close" is ative

**Comment by osauzet** [comment]
For me, this setting -> "Administration > Accounts> Forget User Session on Window Close" has no impact (when checked or unckecked).
My workstations are connected to an active directory domain with roaming sessions....

**Comment by marcosmolinamaxicon** [comment]
I am also using LDAP, the setting has impact if active every time the software restart ask username and password.

**Comment by TulkasGer** [comment]
> Check in Rocket.chat
> "Administration > Accounts> Forget User Session on Window Close" is ative

For me this solved this Error
 on Win10 /Rocketchat Version >= 2.16

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
