### ISSUE TITLE
Changing language forces menu focus and makes it hard to write multi-language messages

### ISSUE THREAD

**Issue by steve-todorov** [RocketChat/Rocket.Chat.Electron#1355]
## My Setup
- Operating System: Ubuntu 19.10
- App Version: 2.16.0
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

After upgrading to 2.16.0 the chat application has become unusable for me and probably for any other user who has multi language and switches between the language with `ALT + SHIFT`.

### Current Behavior

The top menu (file,edit,view,window,help) gets focused each time I change my language and stays focused until I specifically press `ALT` again. It looks like this is some sort of Electron issue which I have noticed across other Electron based apps as well. It has literally made my life miserable.

### Expected Behavior

Don't steal focus while I'm typing. This was the behavior for 2.15.*.

**Comment by carlspring** [comment]
This is super-annoying! I'm getting this as well! Could you please look into it? Switching between languages triggers this **_everytime_**! :(

**Comment by sigsergv** [comment]
Related issue from Electron issues tracker: https://github.com/electron/electron/issues/11106

**Comment by steve-todorov** [comment]
It looks like this is now tracked in electron/electron#22213.
This issue is literally making Rocket chat unusable for me in each version **after** 2.15.5. 
If there is a braking change in Rocket chat which would require me upgrading after 2.15 - I'll literally have stop using it.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
