### ISSUE TITLE
Upload file is not working, at least in version 2.15.5

### ISSUE THREAD

**Issue by AdriWild** [RocketChat/Rocket.Chat.Electron#1356]
### Description:

Doesn't work when we want to upload files throw the Desktop App, it remains on 0%.

-> Throw Mobile App works perfectly, then is not a Server issue.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
