### ISSUE TITLE
version 2.16 breaks compatibility with mac OS 10.11 10.12

### ISSUE THREAD

**Issue by rouet** [RocketChat/Rocket.Chat.Electron#1357]
## My Setup
- Mac OS 10.11 & 10.12
- Rocket-Chat 2.16
- installed from App Store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
application don't start 
see this message in log : "SandboxViolation: Rocket.Chat Help(968) deny(1) forbidden-sandbox-reinit"

### Expected Behavior
application start

**Comment by rouet** [comment]
this issue solves the problem for 10.11 et 10.12

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1339

**Comment by tassoevan** [comment]
@rouet I'm sorry, how #1339 can solve the problem for El Capitan and Sierra?

**Comment by rouet** [comment]
Use theses commands

```
sudo xattr -cr /Applications/Rocket.Chat.app
sudo codesign --force --deep --sign - /Applications/Rocket.Chat.app
```

We test this an it works on 10.11 and 10.12.

**Comment by tassoevan** [comment]
Got it, looks like an issue with the code signing step of `electron-builder`; I'll try to patch it. Thank you!

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
