### ISSUE TITLE
Self build version opens in Debugmode

### ISSUE THREAD

**Issue by Phorms** [RocketChat/Rocket.Chat.Electron#1358]
## My Setup
- Operating System: Windows 10
- App Version: 2.16.0
- Installation type: exe but self build with yarn

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I downloaded the source code of 2.16.0 and added a server.json, built an exe via yarn release and whenever you start RocketChat after installation it opens in debug mode.
![2019-10-18_12h37_44](https://user-images.githubusercontent.com/14980311/67088175-c98e7d80-f1a4-11e9-89da-f9bc0163148a.png)

### Current Behavior
Opens in debug mode

### Expected Behavior
Does not open in debug mode

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
