### ISSUE TITLE
Screen Sharing is broken on Video Conferences on Mac OS and 2.16

### ISSUE THREAD

**Issue by charleshaa** [RocketChat/Rocket.Chat.Electron#1359]
## My Setup
- Operating System: Mac OS X 10.14.4
- App Version: 2.16
- Installation type: Auto-updated somehow

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

After the update, when trying to screenshare on the jitsi meet popup window, my CPU usage goes through the roof and I have to close the window to make it stop. There seems to be no source available for the screenshare as well. I have tested this on the same setup with a colleague as well. I have now rolled back to 2.15.5 and it works like a charm.

### Current Behavior

Unable to screenshare and high CPU Usage

### Expected Behavior

Should work as it does in 2.15.5

**Comment by franckadil** [comment]
The same error is easily reproducible under Windows and Linux Arch/Ubuntu.

**Comment by alleait** [comment]
I have the same issue on latest 2.16 Electron client on Windows. Jitsi Video/Audio works but screen sharing stuck on loading . Please fix this.

**Comment by STW-Ahartung** [comment]
we have the same issue on 2.16. client on Windows and Ubuntu. Jitsi Video/Audio works but screen sharing stuck on loading. Please fix this.

**Comment by eidermar** [comment]
Same issue here (macOS Mojave) 2.16.2
This is a big problem for us, is anybody looking into this or at least acknowledging the problem?

**Comment by ddejmek** [comment]
same here (macOS Catalina) rocketchat.app 2.17.1

**Comment by lucianomlima** [comment]
Should request screen recording permission

**Comment by ddejmek** [comment]
works again with 2.17.9 (and also with 2.17.7 I think)

**Comment by lucianomlima** [comment]
> works again with 2.17.9 (and also with 2.17.7 I think)

Not for me with 2.17.9 and MacOS Catalina 10.15.4

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
