### ISSUE TITLE
macoOS: App installed/updated from macOS App store crashes on startup

### ISSUE THREAD

**Issue by thawn** [RocketChat/Rocket.Chat.Electron#1360]
## My Setup
- Operating System: OSX 10.13.6
- App Version: 2.16.0 
- Installation type: macOS App store (the same dmg version downloaded from the github releases page works)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

The app version 2.16.0 installed via the macOS App store crashes on startup.  The same version downloaded as dmg from the GitHub releases page works.
### Steps to reproduce:
Install version 2.16.0 from the macOS App store and try to start the app

### Current Behavior

The app crashes on startup
If started from command line, it shows the following messages:
```
No data to migrate.
[837:1018/185826.391696:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
Trace/BPT trap: 5
```
### Expected Behavior

The app starts

**Comment by pramsky** [comment]
Same issue.

- High Sierra 10.13.6
- nvidia web drivers

**Comment by thawn** [comment]
@pramsky did you try to install [the dmg version 2.16.0 downloaded from GitHub](https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.16.0/rocketchat-2.16.0.dmg)?

**Comment by pramsky** [comment]
Yes, I downloaded 2.16 and it crashed the same way.

**Comment by stleitner** [comment]
+1 with Mac OS 10.12.6

**Comment by pramsky** [comment]
Downloaded 2.16.2 and it is working as expected. I still have not tried the app store version, but the latest release from here works.

**Comment by Etheryte** [comment]
The same issue is present on macOS 10.13.6, using the current App Store release (version 2.17.9 according to the plist) crashes on startup.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
