### ISSUE TITLE
Spell checking no longer working in 2.16.0

### ISSUE THREAD

**Issue by Forage** [RocketChat/Rocket.Chat.Electron#1362]
## My Setup
- Operating System: Ubuntu 19.04
- App Version: 2.16.0
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
After updating from 2.15.5 to 2.16.0, the spell checking no longer works when typing a message.
Nothing wrong gets underlined any more. Downgrading to 2.15.5 makes it work again.

I tried the different languages, disabling and enabling spell check completely, etc.

Let me know if you need any more information.

**Comment by tassoevan** [comment]
Closed by #1366
