### ISSUE TITLE
Rocket.Chat window focused immediately when DM'd [2.16.0]

### ISSUE THREAD

**Issue by jwmann** [RocketChat/Rocket.Chat.Electron#1363]
## My Setup
- Operating System: `macOS 10.14.5`
- App Version: `2.16.0`
- Installation type: `brew cask install rocket-chat`

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

When another user Direct Messages me, Rocket.Chat will immediately focus the window.

Regardless of what I'm doing, I could be typing away mid-code and as soon as someone messages me, it focuses the Rocket.Chat window and I'm now typing in Rocket.Chat

### Expected Behavior

When another user Direct Messages me, Rocket.Chat should _not_ focus the window.

**Comment by tassoevan** [comment]
@jwmann Is the option `Window` > `Show on unread messages` enabled?

**Comment by jwmann** [comment]
Yea it was. _\*facepalm*_

I was desperately trying to find an option for it and couldn't find it anywhere.
Didn't think to check the Window menu.

Thank you!
