### ISSUE TITLE
Sending Attachments doesn't work (Again)

### ISSUE THREAD

**Issue by AdriWild** [RocketChat/Rocket.Chat.Electron#1367]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.5
- Installation type: .exe

- [ X ] I have tested with the latest version
- [ X ] I can simulate the issue easily

## Description
We have server version installed in our server.

### Current Behavior
On sending files, it stay at 0%, and doesn´t work ( It works with Mobile Version ).
- It happened before with the old version an suddently worked again.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
