### ISSUE TITLE
Copy object (image for example) doesn't work

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat.Electron#1368]
### Description:

When using copy from menu on pasted file (for example image), there is bug on pasting - "[object Object]" - instead pasting image. Bug is on application (currently 2.15.2) and web version.

### Steps to reproduce:

1. Go to Rocketchat
2. Copy object (from menu or right mouse click)
3. Try to paste it, get nothing :(

### Expected behavior:

Object should be copied properly.

### Actual behavior:

Pasting "[object Object]", or blank space.

![rocket-copy-bug](https://user-images.githubusercontent.com/3985913/56290875-6869ec80-6124-11e9-8c93-eed7a65b127a.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0-rc.2
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: v8.15.0
- MongoDB Version: 4.0.5

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by prayingmantis1979** [comment]
In the latest version 3.7.5 it is not possible to copy image because the option Copy in the context menu is not available.
![изображение](https://user-images.githubusercontent.com/80267795/149083893-d805e8cd-ac23-4b3a-8f73-ad234902651e.png)

**Comment by jeanfbrito** [comment]
Ah I see, on windows is disabled. Reopening.
