### ISSUE TITLE
yarn fail!!!!

### ISSUE THREAD

**Issue by hericyan** [RocketChat/Rocket.Chat.Electron#1369]
![image](https://user-images.githubusercontent.com/22905186/67562488-62973880-f751-11e9-80ef-f227eea2cc83.png)

**Comment by franckadil** [comment]
Hi @hericyan you will need to use the latest dependencies in the develop branch the file is `package.json`, otherwise you will get this error.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by hericyan** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
