### ISSUE TITLE
Receiving a direct message in Windows 10 causes window to relocate and resize

### ISSUE THREAD

**Issue by williamjamir** [RocketChat/Rocket.Chat.Electron#1371]
## My Setup
- Operating System: Windows 10.0.18362
- App Version: 2.16
- Installation type: 

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

When the rocket chat is visible, but not with focus and someone sends me a direct message or notify me in a room, the application screen is resized.

![rocketchat_desktop_resize_bug](https://user-images.githubusercontent.com/5083518/67682818-f8f47580-f96e-11e9-9d1e-c556a9523632.gif)

### Current Behavior
The desktop app resizes and someone sends me a direct message, or notify me in a room.

### Expected Behavior
The desktop app should not be resized.

**Comment by Dunexus** [comment]
Same issue : https://github.com/RocketChat/Rocket.Chat.Electron/issues/1321

Really annoying behavior, especially on multiscreen configuration.

**Comment by Silimilikim** [comment]
Very annoying indeed, get crazy because it

**Comment by MartinSchoeler** [comment]
@williamjamir  @Silimilikim Does this happen exclusively when using 2 screens or have you seen this happening with only one screen as well?

**Comment by williamjamir** [comment]
@MartinSchoeler, first of all, thanks for your time to investigate this issue!

Unfortunately, I cannot reproduce more this issue (tested on 2.17), and I don't know if was a complete reinstall or a simple update that fixed this issue.
BTW, sorry for not updating this issue with this information 😞 

Either way, let's wait for @Silimilikim and @Dunexus to see if they still have this problem otherwise I think that we can this issue and  #1321

**Comment by Silimilikim** [comment]
@MartinSchoeler only one screen for me

**Comment by Dunexus** [comment]
I use it at work in a two/three screen configuration. It still happens on 2.17

**Comment by tassoevan** [comment]
May have been fixed by #1810
