### ISSUE TITLE
Cannot switch languages, application menu gets selected when click L alt + shift

### ISSUE THREAD

**Issue by shinebayar-g** [RocketChat/Rocket.Chat.Electron#1373]
## My Setup
- Operating System: Xubuntu 18.04
- App Version: 2.16.0
- Installation type: 
package manager .deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![image](https://user-images.githubusercontent.com/3091558/67774898-20476180-fa99-11e9-983d-66c68dc02fa2.png)

### Current Behavior

This menus get selected when I try to switch languages when typing (Left shift + Left alt buttons), thus resulting I cannot type after switching input languages.
### Expected Behavior

Just type normally after language switching. Actually this was working few versions earlier. It's broken now.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
