### ISSUE TITLE
Rocket.Chat hidden in Gnome Shell without "ubuntu appindicators" extension enabled

### ISSUE THREAD

**Issue by settermjd** [RocketChat/Rocket.Chat.Electron#1375]
## My Setup
- Operating System: Linux Mint 19.2 (Cinammon) running Gnome Shell
- App Version: 2.15.5-1403
- Installation type: APT package manager

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

It started intermittently but has now become a recurring problem. When I start Rocket.Chat, regardless of how, the application window is never visible. The relevant processes appear to be, and stay, running, which I have confirmed with `watch -n 2 pgrep --list-name rocketchat`. However, the app is impossible to access, for all intents and purposes.

### Current Behavior

I don't know if the problem started before or after installing _gnome-tweak-tool_ and _gnome-tweaks_, I suspect that it might have begun afterwards, specifically, after I had Rocket.Chat running and enabled/disabled the _Ubuntu appindicators_ extension. If you enable it, then the Rocket.Chat icon is visible in the top bar in Gnome Shell. From there, the application can be made visible and hidden. 

![Ubuntu appindicators extension enabled in Gnome Shell](https://user-images.githubusercontent.com/196801/67840552-6da5ec00-faf6-11e9-8ef3-a71eafc31ccd.png)

![Show/Hide Rocket.Chat from the Gnome Shell taskbar](https://user-images.githubusercontent.com/196801/67840885-29671b80-faf7-11e9-9357-4ca1bc3b0a3f.png)

### Expected Behavior

I would expect that, if the Ubuntu appindicators extension is disabled, then the main app window would be visible when the application is started, at most minimised. If the Ubuntu appindicators extension is enabled and the app was launched, I'd expect it to either initially be visible, or to resume its previous state.

**Comment by franckadil** [comment]
This issue is reproducible under the Gnome Desktop environment with latest release.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
