### ISSUE TITLE
App is not working on Ubuntu

### ISSUE THREAD

**Issue by gudge25** [RocketChat/Rocket.Chat.Electron#1377]
### Description:

Ubuntu  2.16.0 app  is not working

### Steps to reproduce:

1. install app from snaps (i  have tested  using  deb also)
2. log in  using user  and passwords
3. Close add  and open it  again 

### Expected behavior:
expect that session resume

### Actual behavior:

three  dots  on the  screen 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Centos  7
- Deployment Method: packages
- Number of Running Instances: 1
![image](https://user-images.githubusercontent.com/2346208/68111298-797b1f00-fef7-11e9-9e8b-398412b6048c.png)
![image](https://user-images.githubusercontent.com/2346208/68111318-86980e00-fef7-11e9-8075-b9c171ec501a.png)

### Client Setup Information

- Desktop App or Browser Version:  2.16.0
- Operating System: Ubuntu 18.04 

### Additional context

TESTED  on Linux  Mint --the same problem

### Relevant logs:
in Browser  it works fine
but in app 
![image](https://user-images.githubusercontent.com/2346208/68111953-f65ac880-fef8-11e9-9948-b56eb82fa95a.png)

**Comment by tassoevan** [comment]
@gudge25 Is clicking at the plus icon and then clicking on your server favicon on sidebar a workaround?

**Comment by gudge25** [comment]
@tassoevan  thanks fo reply 
But NO   -- still  dots

**Comment by tassoevan** [comment]
@gudge25 Any errors logged on the server console? (Accessible in `View > Open DevTools`)

**Comment by gudge25** [comment]
seems to be a  problem
![image](https://user-images.githubusercontent.com/2346208/68159178-f17a3100-ff59-11e9-9151-22a706e4a037.png)
on the right panel i opened up one if the links

**Comment by gudge25** [comment]
@tassoevan  thanks

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
