### ISSUE TITLE
Right Click on misspelled words slow on macOS

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Electron#1379]
## My Setup
![image](https://user-images.githubusercontent.com/6295044/68146322-c239d480-ff05-11e9-93fe-78819af3a13c.png)
![image](https://user-images.githubusercontent.com/6295044/68146412-ea293800-ff05-11e9-833b-4f87fecc998c.png)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Right-clicking on a word that is misspelled takes a few seconds for the context menu to appear. I do not see this behavior on Windows.

### Current Behavior
![slow-speller](https://user-images.githubusercontent.com/6295044/68146881-e944d600-ff06-11e9-9e33-1438f7863d3e.gif)

### Expected Behavior
Immediate right click!

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
