### ISSUE TITLE
Implement Jitsi Meet Remote control in Rocket.Chat.Electron

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1382]
Hello!
As I see, [jitsi-meet-electron](https://github.com/jitsi/jitsi-meet-electron) is the only client, that supports Remote Control feature in Jitsi Meet call.
I think it would be very useful for a lot of Rocket.Chat with Jitsi integrated users if native desktop Rocket.Chat client could support that feature.
So, please Implement Jitsi Meet Remote control in Rocket.Chat.Electron
Thanks!

**Comment by raphaelcasimir** [comment]
Remote control would be genius, next feature after this one would be shared whiteboard

**Comment by ankar84** [comment]
@tassoevan but please make that feature manageable with config files.
Our security department not so happy about that functionality itself.

**Comment by tassoevan** [comment]
> ~Remote control~ (currently disabled)

🤔  I'm not familiar with this feature. I guess [it has been disabled for security reasons](https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2020-0001.md) very alike the ones we mitigated going to the version 3.0.0 (i.e. Electron's preload script without isolation context).

**Comment by ankar84** [comment]
> I guess [it has been disabled for security reasons](https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2020-0001.md) very alike the ones we mitigated going to the version 3.0.0 (i.e. Electron's preload script without isolation context).

So, if it disabled in Jitsi itself, I close that issue.
Thank you, Tasso!

**Comment by foss-** [comment]
Context
[JSA-2020-0001](https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2020-0001.md)
and ["no short term plans to bring it back"](https://github.com/jitsi/jitsi-meet-electron/issues/483)
