### ISSUE TITLE
Notification popup on top

### ISSUE THREAD

**Issue by acomputerwiz** [RocketChat/Rocket.Chat.Electron#1383]
## My Setup
- Operating System: Windows 10 Pro
- App Version: 2.15.5  2.16.1
- Installation type: Windows exe client

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When a user receives a message, there is a toast, but it does not actually popup on the screen.  Even when 'Show on unread messages' is checked, 
### Current Behavior

Taskbar flashes orange.  Sometimes pops up in the background only but never on top.

### Expected Behavior

Window should popup on top or above all other windows and display the new message.

**Comment by metalcated** [comment]
I concur. I am also experiencing this issue. Works in the Web but not the Electron Client.

**Comment by JeGr** [comment]
I experience the same problem as @metalcated describes. Worked before in one of the older versions of the app but since 2.17.x (even 2.16.? won't show them anymore) it's gone. App shows no notifications at all, browser reacts normally, so currently the app is useless as daily driver.

**Comment by tassoevan** [comment]
@acomputerwiz @JeGr Does it still happen in version 2.17.5?

**Comment by acomputerwiz** [comment]
@tassoevan Yes, I do get the slide-out windows notification, but even with the 'Show on Unread Messages' being checked, still doesn't cause the actual application window to appear and be in front of other windows.  I feel like maybe there needs to be a check option for "Always on Top'.  I feel like either way it is some kind of focus issue.

I would even be willing to throw a dev at the problem to help figure it out, if you know whereabouts in the code it might be.

**Comment by tassoevan** [comment]
@acomputerwiz At least for "Show on Unread Messages", it is the desired behavior: to open the window without giving it focus, because otherwise it would block some users for using any other window on desktop.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
