### ISSUE TITLE
i'm not getting any sounds  once i changed the room notification.

### ISSUE THREAD

**Issue by nickerrienz** [RocketChat/Rocket.Chat.Electron#1384]
## My Setup
- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by plasmoa** [comment]
Same here on latest release 2.17.0 .

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
