### ISSUE TITLE
Dark Mode in Catalina

### ISSUE THREAD

**Issue by terra3110** [RocketChat/Rocket.Chat.Electron#1386]
Rochet Chat 2.16.0 for MacOS did not support the Dark Mode of Catalina correctly. 

The Menu Item for the Top Menu, should invert the colours otherwise the Icon become invisible.

<img width="192" alt="Screen Shot 2019-11-08 at 19 54 10" src="https://user-images.githubusercontent.com/57519597/68456050-afa30080-0261-11ea-8ab1-0095f2b5a92b.png">
<img width="206" alt="Screen Shot 2019-11-08 at 19 54 13" src="https://user-images.githubusercontent.com/57519597/68456051-afa30080-0261-11ea-9105-d909793c693f.png">

**Comment by alishadfar** [comment]
this happens in rocket.chat 2.16-2.16.2 for me as well.  2.15.5 worked like it was supposed to.

**Comment by foss-** [comment]
just adding a data point: this is working as expected on macOS 10.14.6 w 2.16.2.
![mojave dark mode](https://user-images.githubusercontent.com/5708172/68527653-8cbc2f00-02e9-11ea-91b2-674739aa1bc2.png)

**Comment by tassoevan** [comment]
Is it still an issue in 2.17.0?

**Comment by terra3110** [comment]
After updating to 2.17.0 RocketChat crashed on MacOS Catalina. I have to reinstall an older version and skip 2.17.0.

**Comment by DanDavies** [comment]
Just to add extra information here. The icon is only invisible when there are no unread messages. When there are unread messages, a white variant of the icon is displayed, however as soon as all messages are read the icon becomes invisible again.

**Comment by rex4539** [comment]
This is fixed in latest build. You are probably using an old build. Please upgrade.

**Comment by Hackmodford** [comment]
The version on the mac app store still has this issue. Downloading directly from the website fixed it.

**Comment by tassoevan** [comment]
It should be fine right now.

**Comment by josecanciani** [comment]
I have this problem in 3.0.3, installed from the Apple Store. Anyone else?
