### ISSUE TITLE
Bom dia, aqui no Brasil o horario de verão foi canbcelado, mesmo assim o software esta 1 hora adiantada, a hora do computador e servidor estão corretas.

### ISSUE THREAD

**Issue by edsonapiuna** [RocketChat/Rocket.Chat.Electron#1388]
## My Setup
- Operating System:
- App Version:
- Installation type: 

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by edsonapiuna** [comment]
![01](https://user-images.githubusercontent.com/41807254/68471584-45f10b00-01fd-11ea-8b46-14c4e54f45bd.png)

**Comment by jeronimofagundes** [comment]
Confirmo o bug. O mesmo ocorre em meu Ubuntu 19.10, com sistema atualizado. Client do Rocket.Chat instalado via snap. O horário do computador está correto, e do app está 1h adiantado.

**Comment by sampaiodiego** [comment]
closing the issue as duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1391
