### ISSUE TITLE
Unable to update from 2.16.0 to 2.16.2

### ISSUE THREAD

**Issue by Nono-m0le** [RocketChat/Rocket.Chat.Electron#1389]
## My Setup
- Operating System: Win 10
- App Version: 2.16.0
- Installation type: exe, download from https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.16.0/rocketchat-setup-2.16.0.exe install as "only me" during install (upgrade from 2.15.5 manually as no update was available from the auto-update checks).

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

On startup, the application show an update available from 2.16.0 to 2.16.2.
Clicking on 'update' trigger the usual popup "You will be notified when the update is ready to be installed" but system monitor show no downloading.

### Current Behavior
No update is downloaded/installed

### Expected Behavior
Update performed

**Comment by danielrentz** [comment]
This constantly happens for me with nearly every new update :-/

**Comment by Nono-m0le** [comment]
> This constantly happens for me with nearly every new update :-/

Well, we have this behavior since version 2.15.1 or so.
And I though that 2.15.5 was also impacted as we didn't received update for 2.16.0 at all.
But since I've upgraded manually to 2.16.0 and the "check update" is back, I was expecting to work this time ...

TBH: It could be due to remaining (previous) folder at my end.
For instance : 
`C:\Users\USER\AppData\Roaming\Rocket.Chat\update.json` content:
```
{
  "skip": "2.15.1"
}
```
`C:\Users\USER\AppData\Roaming\Rocket.Chat\__update__\` directory have 2 files: 
```
rocketchat-setup-2.15.0.exe
update-info.json
```
the last one, with this content:
```
{"fileName":"rocketchat-setup-2.15.0.exe","sha512":"Ho9FL8Q1XGVtdz1duJ6BSpq/BwzWH9nY4TwCqxMTjeJ/dNRp0G0FqUl67v1M6tTw5SkpfAj8rhlKRnBhjmWUgw=="}
```

**Comment by lk3de** [comment]
Looks like a duplicate of #1205

**Comment by raatti** [comment]
on Mac OSX, also 2.16.1 -> .2 fails too, it shows the dialog but never really updates, similiar issue.

**Comment by Nono-m0le** [comment]
It would be nice to know if we should manually update or not ? (indeed, like #1205 )

**Comment by Nono-m0le** [comment]
@tassoevan could it be linked to https://github.com/RocketChat/Rocket.Chat.Electron/pull/1381 ?

**Comment by tassoevan** [comment]
@Nono-m0le Yes 😞

**Comment by Nono-m0le** [comment]
@tassoevan In such case, may I kindly ask you to close this issue and inform people that they should update manually ? Otherwise, I'll do it (but it's better if it comes from you) Unless this can be solved on the current version but I've my doubts ?

**Comment by Nono-m0le** [comment]
Seems to be a recurring issue. (just noticed 2.17.7 today ...) I'm closing this issue as the update doesn't work anyway

**Comment by tassoevan** [comment]
@Nono-m0le Sorry for letting this issue falls into oblivion... Update is currently disabled for Windows users since a bug related to code signed appeared. It should be fixed in the next major version.
