### ISSUE TITLE
Update notification only allows user to click on 'Skip this version'

### ISSUE THREAD

**Issue by hmwakeling** [RocketChat/Rocket.Chat.Electron#1390]
## My Setup
- Operating System: MacOS Catalina but this has happened for previous versions
- App Version: 2.15.0 but this has happened for every previous version I've had
- Installation type: dmg

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Reproduce by restarting my mac and opening RocketChat app.

### Current Behavior
After restarting my mac and app, a notification appears with the latest versions of RocketChat. Clicking on anything other than 'Skip this version' has no response. 

### Expected Behavior
The update buttons should respond.

**Comment by Maqsyo** [comment]
Ongoing Problem and duplicate
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1428
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1300

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
