### ISSUE TITLE
Wrong time for Brazil timezone for DST areas

### ISSUE THREAD

**Issue by Mixelito** [RocketChat/Rocket.Chat.Electron#1391]
The docker image with the daylight saving time tzdata package is out of date.

In Brazil (-03:00) no longer has daylight saving time but is displaying timezone with -02:00

apt list --installed | grep tzdata
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
tzdata/now 2019b-0+deb9u1 all [installed,local]

**Comment by sampaiodiego** [comment]
Move the issue to the right repository as it happens only on the desktop app.

The issue itself is related to NodeJS and not to Rocket.Chat itself: https://github.com/nodejs/node/issues/30211

we're trying to work on a workaround while the official fix is not released by NodeJS

**Comment by sampaiodiego** [comment]
related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1181

**Comment by toppermitz** [comment]
I have the same issue, in version 2.16.2 this may seems OK

**Comment by dwolff** [comment]
It's totally a "band-aid", a tempfix, but if you set the "TZ" environment variable to "America/Bahia" and then execute the application, it works.
I use Ubuntu, so I changed the "Exec" on rocketchat-desktop.desktop to this:
`Exec=sh -c "TZ='America/Bahia' /opt/Rocket.Chat/rocketchat-desktop %U"`

Works for me.

**Comment by tassoevan** [comment]
I'm closing it since I believe it's fixed at the `develop` branch, soon to be released as 2.17.0.

**Comment by lkraider** [comment]
Will version 2.17 be released in the Mac AppStore ?

**Comment by tassoevan** [comment]
@lkraider I'm waiting for news about Electron 7 passing through the App Store validation. Until there, we're blocked. :disappointed:
