### ISSUE TITLE
directly show chat window on systray icon click instead of showing menu

### ISSUE THREAD

**Issue by blmt** [RocketChat/Rocket.Chat.Electron#1394]
## My Setup
- Operating System: Debian unstable
- App Version: 2.16.2 
- Installation type: deb

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

The behavior has been changed sometimes in the past but I believe it would be best to follow the other Linux chat apps behavior reverting to showing the chat window when clicking on the systray icon.

### Current Behavior

Clicking on the systray icon show an "open, quit" menu

### Expected Behavior

Clicking on the systray icon should open the chat window.

**Comment by tassoevan** [comment]
Duplicate of #1107.
