### ISSUE TITLE
Copied text within the app it gets copied to my X11

### ISSUE THREAD

**Issue by henryfok** [RocketChat/Rocket.Chat.Electron#1397]
## My Setup
- Operating System: GNOME
- App Version: 2.15.3
- Installation type: yum rpm

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

When I copy text from within the Rocket.Chat app (using Ctrl+C or the copy menu) it gets copied to my X11 register, meaning I have to middle click to paste it. It's different from the normal copy/paste behaviour in every other application. This causes me to keep pasting the wrong text.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
