### ISSUE TITLE
Feature Request : Memorise password

### ISSUE THREAD

**Issue by osauzet** [RocketChat/Rocket.Chat.Electron#1398]
Feature Request :  
I use RocketChat for an Public Organisation. The Users are on Windows10, and open session on windows active directory.

Currently, for users, at each login you have to think about login on RocketChat. Is it possible to have a button "memorize the password", so that each logon users are logged on RocketChat.

## My Setup
- Operating System: Windows10
- App Version: 2.15.5
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

**Comment by sgostelow** [comment]
We've had RocketChat running for some months and recently the Windows client began asking all users for a login and password each morning.  It seems this is a change to the functionality.

It would be very desirable to remember users login and password so they do not need to re-type their details every day.

**Comment by TulkasGer** [comment]
Related To:
#1354

**Comment by marcosmolinamaxicon** [comment]
Check 
Administration > Accounts> Forget User Session on Window Close is ative

**Comment by osauzet** [comment]
Pk thanks @marcosmolinamaxicon it works whith : "Administration > Accounts> Forget User Session on Window Close" unchecked and  Windows apps client in 2.17.0
nice :-)
