### ISSUE TITLE
Start client in hidden mode

### ISSUE THREAD

**Issue by flauschi** [RocketChat/Rocket.Chat.Electron#140]
It would be great if the Rocket.Chat client would support some options to simplify deployment:
(Other parts of this task #96, #139)

* command line option to start the client in hidden mode (tray icon) or remember this setting when closing the app

Probably fixed with #118 ?

**Comment by rodrigok** [comment]
Do you need an option to start the client in hidden mode or just opening after close it in hidden mode keep it hidden?

**Comment by flauschi** [comment]
It would be enough if it stays in hidden mode after close or shutdown in hidden mode.

**Comment by rodrigok** [comment]
Great, can you test our latest release? https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by flauschi** [comment]
Great! Works under Windows Server 2008 R2. I will try it under Windows 10 tomorrow and edit this comment.

**Comment by rodrigok** [comment]
Great, I will close this issue, reopen it if you need.

**Comment by flauschi** [comment]
Sorry, I have to reopen it. It works if I close the app with rightclick on the statusbar icon and click quit.
But it does not remember the setting if I just logout and the app is still open.

**Comment by hugoeustaquio** [comment]
Guys, what are the parameter that makes it start on system tray?
I'm using linux, and rocketchat doesn't have an 'man' neither it responds to '$ rocketchat --help'.

Thanks.
