### ISSUE TITLE
RocketChat Electorn stuck after connect to server

### ISSUE THREAD

**Issue by toppermitz** [RocketChat/Rocket.Chat.Electron#1400]
## My Setup
- Operating System: Windows 10 
- App Version: 2.16.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![image](https://user-images.githubusercontent.com/13020454/69172894-6ebaaf80-0add-11ea-9d3d-3a1647aa4c47.png)

My server information:
![image](https://user-images.githubusercontent.com/13020454/69173120-e2f55300-0add-11ea-8cc6-3484988d0c71.png)
![image](https://user-images.githubusercontent.com/13020454/69173148-f0124200-0add-11ea-9e02-217522db4e66.png)

### Current Behavior

After update to last version(2.16.2), my old version is 2.15.2, rocket connect to server and when I click in any conversation stuck in a gray screen.

### Expected Behavior

Works normally and not stuck on a gray screen

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
