### ISSUE TITLE
Not connecting via https to local server

### ISSUE THREAD

**Issue by kkachura** [RocketChat/Rocket.Chat.Electron#141]
Client is not connecting to the server (self signed sertificate) in local network via https:
Error "Not a valid instance url" and connection line changed to HTTP://<server> not HTTPS://<server>
Connected only via http (on port 3000 by default).
System: Linux Mint 17.3, Manjaro Linux

**Comment by JamesonFinney** [comment]
We've observed this in our environment when the server has an invalid certificate. Would not surprise me if self signed certificates are considered as invalid as well.

**Comment by rodrigok** [comment]
We do not support invalid ssl certificates, this can be dangerous.

If you are using a self signed certificate you can create a CA for your certificate and install in your OS.
