### ISSUE TITLE
feature request - minimize to systray when clicking close button in linux?

### ISSUE THREAD

**Issue by pescobar** [RocketChat/Rocket.Chat.Electron#142]
Hi 

it would be nice to have an option to select "minimize to systray when clicking close button" 

In osx it's like that but not in linux. is this possible in the linux client?

thanks

**Comment by sampaiodiego** [comment]
This is how it is working right now :smile: 
Tested in Ubuntu 15.10 - Rocket.Chat+ App 1.2.0
