### ISSUE TITLE
Screen Sharing via Jitsi no longer works on 2.17.2 (latest)

### ISSUE THREAD

**Issue by alleait** [RocketChat/Rocket.Chat.Electron#1421]
## My Setup
- Operating System: Windows 10 Pro
- App Version: 2.17.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
When starting screen sharing popup window keeps loading and never gives option to select whole screen or , app windows. Problem exists since version 2.16.2 . 

### Expected Behavior
Screen sharing should start and work normally.

**Comment by ankar84** [comment]
I confirm that bug.
Screen Sharing is broken.
![image](https://user-images.githubusercontent.com/4023037/69950282-361acd00-1504-11ea-9297-188e0f4f691f.png)

**Comment by ankar84** [comment]
I have tested Screen Sharing on version 2.16.0 and have the same bug.
Checked version 2.15.5 and it works fine.

**Comment by STW-Ahartung** [comment]
we have the same issue on 2.17.0 and 2.16. clients on Windows and Ubuntu. Jitsi Video/Audio works but screen sharing stuck on loading. Please fix this.

**Comment by ankar84** [comment]
Rocket.Chat Electron version 2.17.1 didn't fix that issue, please fix it.

**Comment by shoelzle** [comment]
Same problem on MacOs Catalina with Rocket.Chat Electron version 2.17.1.

**Comment by alleait** [comment]
updated my thread for the issue , it persists through latest 2.17.1 version.

**Comment by sandreddu** [comment]
Same problem on 2.17.2

**Comment by JackNWeems** [comment]
Just another having the same issue vote.

**Comment by Bob0t** [comment]
Stuck on 2.15.5 because I need to use it :(

**Comment by ankar84** [comment]
> Stuck on 2.15.5 because I need to use it :(

Same for me.

**Comment by alternativshik** [comment]
Also stuck on 2.15.5...

**Comment by math-uzh** [comment]
Also downgrade from 2.17.2 back to 2.15.5 - need this feature heavily.

**Comment by alleait** [comment]
any plans on fixing this?

**Comment by ankar84** [comment]
Screen Sharing works great in RC.Electron version 2.17.3
Good job, @tassoevan !

**Comment by math-uzh** [comment]
Some on our site: 2.17.3 screen share works as well as pasting images via clipboard - Thanks a lot.

**Comment by Bob0t** [comment]
Works like a charm now ! Thanks !

**Comment by macmacy** [comment]
Having exactly this issue with freshly installed 2.17.7
