### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by RetMarut1** [RocketChat/Rocket.Chat.Electron#1423]
## My Setup
- Operating System: MacOS
- App Version: 2.16.1
- Installation type: dmg

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description

On my machine, all chat & communication applications have a blue app icon and a red marker, if there are unread messages - except for rocket.chat! I usally ignore new rocket.chat messages because they are hard to recognize (little red marker on red icon). 
### Expected Behavior

Blue application icon.

**Comment by rafaelclaycon** [comment]
I would suggest adding this blue icon as an option in My Account > Preferences.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
