### ISSUE TITLE
2.16.2 offers update to 2.17.0 which is known to crash

### ISSUE THREAD

**Issue by MacLemon** [RocketChat/Rocket.Chat.Electron#1424]
## My Setup
- Operating System: macOS 10.13.6
- App Version: 2.16.2
- Installation type: dmg (Since 2.16.0 from Mac App Store is known to crash and never launch.)

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
After Installing 2.16.2 from dmg I'm immediately presented a notification to update to 2.17.0.
Version 2.17.0 is known to crash immediately upon launch on macOS. This is the reason for 2.16.2 in the first place and why 2.17.0 is not offered on the website for download. (at least not for macOS)

2.16.2 must not display an update notification for a withdrawn release (on said platform).

### Current Behavior
An update notification is presented. If you actually do the update, your application will not launch anymore.

![Rocket chat offers crash update](https://user-images.githubusercontent.com/90635/69961360-fce65b00-150b-11ea-8a1a-c23f38eca740.png)

### Expected Behavior
A withdrawn release should never be offered as an update!

**Comment by hypercodex** [comment]
How does one roll back to 2.16.2 after running this update? It seems it has now corrupted my 2.16.2 as well. Reinstalled 2.16.2 and now it is unresponsive and seems broken.

macOS 10.15.1

**Comment by shoei101** [comment]
> How does one roll back to 2.16.2 after running this update? It seems it has now corrupted my 2.16.2 as well. Reinstalled 2.16.2 and now it is unresponsive and seems broken.
> 
> macOS 10.15.1

mine was doing the same thing, so i used an "uninstaller app" then reinstalled 2.15.5 because 2.16.2 doesn't like darkmode in Catalina.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
