### ISSUE TITLE
Some UTF-8 characters not printed correctly

### ISSUE THREAD

**Issue by 1100101** [RocketChat/Rocket.Chat.Electron#1429]
## My Setup
- Operating System: Windows 7 64-bit
- App Version: 2.17.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
UTF-8 strings starting with a non-valid character, e.g. `１７８８８`  in a code block (\`\`\`１７８８８\`\`\`), or as inline code (\`１７８８８\`) the complete text is getting mangled.

### Current Behavior
![image](https://user-images.githubusercontent.com/1006337/70225706-d57fd000-174f-11ea-9399-946c580b44d1.png)
Without code tags, it looks fine:
![image](https://user-images.githubusercontent.com/1006337/70225772-f516f880-174f-11ea-9273-1cd5cecc524e.png)

The same messages are displayed fine in the browser (Firefox 71.0):
![image](https://user-images.githubusercontent.com/1006337/70225943-42936580-1750-11ea-8740-80c272c4cec2.png)

The text is displayed correctly when you remove the first character from the string.

### Expected Behavior
Text is not mangled when used in code tags.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
