### ISSUE TITLE
Improve error handling for connecting to server

### ISSUE THREAD

**Issue by JamesonFinney** [RocketChat/Rocket.Chat.Electron#143]
I've noticed that when connecting the client to a server, at least two scenarios result in the same error message:

- Attempting to connect to an HTTPS sever with an invalid or self signed certificate
- Connecting to a new version of the server with an older client

Ideally these situations would be handled in such a way as to result in different and descriptive error messages.

System: Mac OS X El Capitan

**Comment by richardwlu** [comment]
Our users are having the same issue with the latest version on Windows.

When the user attempts to connect to our https instance, it fails to connect as a valid instance and attempts to fall back to http in the input box.

Is there a solution for this?

**Comment by rodrigok** [comment]
Are your instances running with a valid SSL or self signed?

We do not support self signed certificates, if you are using one you should generate a CA certificate and install each machine.

**Comment by richardwlu** [comment]
We're using self signed. We have generated CA certificates and installed on all machines. It was working previously but for some reason when they updated to the latest version of the desktop client it fails to connect. I'll take a look at the certs on the desktops again. Any other thoughts are appreciated!

**Comment by rodrigok** [comment]
@richardwlu we didn't change anything related with that, but can be a problem with Electron since we upgraded to the latest version.

**Comment by rodrigok** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat.Electron/commit/0b86ae91254b0c2962d6e6b885f83cd709eb88ca
