### ISSUE TITLE
Rocket Chat App not installing - No Feedback

### ISSUE THREAD

**Issue by NathanBeddoeWebDev** [RocketChat/Rocket.Chat.Electron#1430]
## My Setup
- Operating System: Windows 10
- App Version: 2.17.0 (Occurred on older versions)
- Server Version: 2.1.1
- Apps Engine Version: 1.6.0
- Installation type: EXE

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When trying to upload a Rocket.Chat app as a zip, it does nothing.
![Rocket Chat not uploading extension](https://user-images.githubusercontent.com/2762119/70296236-8f9d3780-1835-11ea-8832-3744d4cfaeea.gif)

### Current Behavior
I choose a zip file of a rocket chat app from my file system, that was constructed from the CLI. I click install, and then nothing happens.

This issue occurs on the web as well.

### Expected Behavior
It should attempt to send it to the server to install, and if failed, give me feedback on why it failed, and if it succeeded, send me back to the apps page.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
