### ISSUE TITLE
Don't auto launching when start ubuntu

### ISSUE THREAD

**Issue by HieuHongLe94** [RocketChat/Rocket.Chat.Electron#1434]
When start ubuntu i want to auto launching rocket-chat

**Comment by apaarfus** [comment]
This is less of a RocketChat-Electron issue, and more of an OS issue.  [Please refer to Ubuntu's documentation on startup applications](https://help.ubuntu.com/stable/ubuntu-help/startup-applications.html.en).

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
