### ISSUE TITLE
Choice Boxes are "Shifted Left" (Right-Border Black Bars)

### ISSUE THREAD

**Issue by apaarfus** [RocketChat/Rocket.Chat.Electron#1437]
## My Setup
- Operating System: Windows 7 Professional x64
- App Version: 2.17.0
- Installation type: Windows Binary Installer

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
List/Choice Boxes in Desktop client (Electron) show black-bars on the right side of the dialogue box; meaning each item in the list must be selected individually, to see what item is shown in the input box to see what it is.  I'd assume this is "just" a CSS bug based on the behavior change from 2.16.2 to 2.17.0

![Screenshot_1](https://user-images.githubusercontent.com/38731016/70476722-510db400-1aa5-11ea-9e5c-ffa39c466e24.png)

### Current Behavior
Opening a List/Choice dialogue results in the listed options being "shifted" outside of the viewport, specifically in the Electron version.

### Expected Behavior
Like in the web-browser client, the listed options should be totally visible.

**Comment by tassoevan** [comment]
Probably related to https://github.com/electron/electron/issues/21152

**Comment by stephan1827** [comment]
Still exists in 2.17.1

**Comment by Shaverdoff** [comment]
in windows 10 the same!
