### ISSUE TITLE
Updates Do Not Start Through Prompt

### ISSUE THREAD

**Issue by callae606** [RocketChat/Rocket.Chat.Electron#1438]
## My Setup
- Operating System: Windows 10
- App Version: 2.16.2
- Installation type: exe

- [ ] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When launching Rocket Chat, it attempted to update to 2.17 and the dialog pops up. You can choose to install updates and clicking it prompts a second window reading "You will be notified when the update is ready to be installed". But it never updates or give notice of a readied update.

![image](https://user-images.githubusercontent.com/58737243/70537062-e3f23100-1b2d-11ea-9598-62c1c9896456.png)

### Current Behavior
Will not update through client update notification

### Expected Behavior
It should download the update, notify me when ready, and then allow for the update to be installed

**Comment by sbronko** [comment]
Same behavior on update attempt from version 2.15.3, Windows 10 to version 2.17 and previously also to 2.16.

**Comment by Maqsyo** [comment]
Ongoing Problem
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1428
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1300

**Comment by JorinL** [comment]
Version 2.17.0:

On Win10 the update to 2.17.1 gets downloaded as "temp-rocketchat-setup-2.17.1.exe" under "%homepath%\AppData\Local\rocketchat-updater\pending", but then you just see it disappear.

The "Install Update" button starts the download - but after that magic is happening - but wrong :)

Even running the client with admin privs does not change that.

**Comment by CitizenDev** [comment]
I can replicate the issue

**Comment by alleait** [comment]
This persists through latest version 2.17.0 to 2.17.1

**Comment by baphomutt** [comment]
persists on 2.17.11 -> 3.0.3, Windows 10

**Comment by TheBassTeddy** [comment]
Persists on 3.02 -> 3.03 and 3.02 -> 3.04

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by JorinL** [comment]
Party hard!
![image](https://user-images.githubusercontent.com/33031729/150033127-ea59e22a-1bcd-412c-ac59-55e43c02a639.png)


Thankful for this! :-) 👍
