### ISSUE TITLE
HTTP Basic Authentication support

### ISSUE THREAD

**Issue by alfredbez** [RocketChat/Rocket.Chat.Electron#144]
Is it possible to implement Basic HTTP Authentication?

It would be nice to prompt the user for a username and password if needed.

see also: atom/electron#3250

**Comment by rodrigok** [comment]
Great idea, I will work on that as soon as possible.

**Comment by alfredbez** [comment]
Where can I enter the username and the password?

**Comment by alfredbez** [comment]
Ok, I looked into [the code](https://github.com/RocketChat/Rocket.Chat.Electron/blob/618e58708e5399aaf52b526e721198a8d44853ef/app/scripts/servers.js#L137-L146) and I think you just need to enter your url like this: `http://username:password@host`

**Comment by rodrigok** [comment]
@alfredbez yes, if you enter your address the app should suggest this tip to you if your server reply requiring basic auth

**Comment by marcinbiegun** [comment]
It's possible to log in using `http://username:password@host` server url, but the the client doesn't perform well - it reloads the whole webapp every time URL is changed (i.e. on channel change).

**Comment by alfredbez** [comment]
@marcinbiegun Which version are you using (client)?

**Comment by gucki** [comment]
@rodrigok I'm using the latest docker image of rocket chat. I put a caddy container in front to have ssl with letsencrypt. This is where I also added basic auth. Everything seems to work, but when a link is clicked (ex, switch the channel or user one is writing with) the whole page reloads. It still works though, it's just a bit annoying. Any idea how to fix it?
