### ISSUE TITLE
Localization dropdown broken

### ISSUE THREAD

**Issue by Have-a-question-about-this-project** [RocketChat/Rocket.Chat.Electron#1441]
## My Setup
- Operating System: Windows 10 1909
- App Version: 2.17.0 and 2.17.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily (simulate? do you mean reproduce?)

## Description
My account, preferences, localization, language dropdown. The left aligned text is aligned beyond the edge of the dropdwon, therefore cropping it so it cannot be read, only the tail end of longer entries can be seen.

### Current Behavior
See description

### Expected Behavior
Text should be aligned so its readable.
![image](https://user-images.githubusercontent.com/35617009/70706332-9b717980-1ccd-11ea-835f-a7cd6dc0285b.png)

**Comment by CitizenDev** [comment]
There is already issue posted about it.
#1437
