### ISSUE TITLE
Don't autorun tray icon when start ubuntu

### ISSUE THREAD

**Issue by HieuHongLe94** [RocketChat/Rocket.Chat.Electron#1442]
Don't autorun tray icon when start ubuntu !

**Comment by ColbyWanShinobi** [comment]
Did you try enabling the "Tray Icon" item in the "View" menu? That worked for me once I enabled it, and the tray icon re-appeared when I restarted the program as well.

**Comment by HieuHongLe94** [comment]
i enabled but i'm not working

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
