### ISSUE TITLE
Can't install electron client on windows

### ISSUE THREAD

**Issue by todeskin** [RocketChat/Rocket.Chat.Electron#1443]
## My Setup
- Operating System: windows 7
- App Version: rocketchat-setup-2.17.1
- Installation type: exe

Just trying to setup rocket.chat client on the windows and it doesn't work.
It just stopping and can't finished, when it should be finished.
![image_2019_12_13T09_47_50_035Z](https://user-images.githubusercontent.com/947081/70791117-7cdfb100-1da7-11ea-8b3b-3154d57f6de7.png)

**Comment by Sierra1011** [comment]
Similar - getting an error on install, returns error code 5. Done everything I can think of that should work, does not apply to all machines I have.
OS is Windows 10.
Similar results using PDQ and Choco to install. 

smb://soit042vm1/c$/Scripts/WhatsApp%20Image%202019-12-11%20at%2018.28.07.jpeg

**Comment by todeskin** [comment]
Hey, any solution?

**Comment by Sierra1011** [comment]
No advances here. Guessing you don't have one either!

**Comment by Sierra1011** [comment]
We actually managed to get it installed today, required rebuilding the user profile. Maybe try clearing all the AppData/ProgramData from your profile?

**Comment by all3kcis** [comment]
I had the same problem,
I used CCleaner, I had an old version of rocket.chat still detected in the applications even if it was no longer installed, I removed it with Ccleaner and it works in 2.17.2

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
