### ISSUE TITLE
App don't autorun tray icon with Operating System Ubuntu 

### ISSUE THREAD

**Issue by HieuHongLe94** [RocketChat/Rocket.Chat.Electron#1444]
## My Setup
- Operating System: Ubuntu 
- App Version: 18.04
- Installation type: .deb

## Description
When I start Ubuntu , app not autorun with system
### Current Behavior
app not autorun with system
### Expected Behavior
App autorun tray icon with system

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
