### ISSUE TITLE
suddenly close application

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat.Electron#1446]
## My Setup
- Operating System: Windows 10
- App Version: 2.17.1
- Installation type: exe

## Description
some times then i hide client on cross button to system-try and after notifications have arraived double click on system-tray icon of rocketchat to popup it on desktop, client will close without any warning 

### Current Behavior
suddenly close applicatino

### Expected Behavior
must popup and correctly worked

**Comment by jdee78** [comment]
I have exactly the same issue.

**Comment by Shaverdoff** [comment]
i get this forclose in 2.17.x version of client...  @jdee78 what version of client you use?

**Comment by jdee78** [comment]
> i get this forclose in 2.17.x version of client... @jdee78 what version of client you use?

2.17.1.

**Comment by romolozambelli** [comment]
Same here with version 2.17.1

**Comment by bkraul** [comment]
Is this being looked at? It is quite prevalent in 2.17.1. Possible duplicate issue: #1439

**Comment by darkpal** [comment]
Same for all our office.
2.17.1

**Comment by ManuelGrund** [comment]
Same for me and my friends - happens since a recent update 

When rocketchat is a while in the tray - and i want to get it open, the window opens, flashes white - and rocketchat crashes/closes

OS: Windows 10 1909

**Comment by apaarfus** [comment]
I'm not experiencing this behavior on Windows 10 Pro x64 1909, but I'm using the most recent release of the electron app, 2.17.2 -- are all of you experiencing this on 2.17.1?

**Comment by bkraul** [comment]
No. I experience it on 2.17.2 as well. Just not as often.

**Comment by rcadmin19** [comment]
This is not an issue on 2.17.7 anymore. In my opinion this issue could be closed.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
