### ISSUE TITLE
2.17.1 Mac puts Electron.dSYM in /Applications

### ISSUE THREAD

**Issue by mcclint680** [RocketChat/Rocket.Chat.Electron#1448]
## My Setup
- Operating System: MacOS 10.14.6
- App Version: 2.17.1
- Installation type: .dmg

- [X ] I have tested with the latest version
- [X ] I can simulate the issue easily

## Description
Install RocketChat 2.17.1 for Mac via .pkg and launch. The Electron.dSYM file is created in /Applications

### Current Behavior
Install RocketChat 2.17.1 for Mac via .pkg and launch. The Electron.dSYM file is created in /Applications

### Expected Behavior
It should NOT put that file there.

**Comment by krispayne** [comment]
This happens for me as well

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by mcclint680** [comment]
2 years later and you’re just now getting to this? Wow.
