### ISSUE TITLE
Download of files does not work

### ISSUE THREAD

**Issue by tuxBurner** [RocketChat/Rocket.Chat.Electron#145]
Hi, 

  i could not download a file in the electron app. In the webview it worked. I found out that the link for the download has a target="_blank" this does not work for electron. I changed it with the dev tools to _top and it worked.

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat.Electron/issues/103

**Comment by tuxBurner** [comment]
Okay thx
