### ISSUE TITLE
Update of macOS App Store version is delayed?

### ISSUE THREAD

**Issue by Aldekein** [RocketChat/Rocket.Chat.Electron#1451]
The latest version in macOS App Store is 2.16.0 and was released 2 months ago. Is there a plan to release an 2.17.1 update in App Store? Or are there some other preferred ways of app distribution enabling automatic updates to recent app version?

![image](https://user-images.githubusercontent.com/671454/71175473-3b18a400-229a-11ea-8adc-e0abf5e1d279.png)

**Comment by tassoevan** [comment]
@Aldekein Apparently, App Store is rejecting Electron apps. 😞  There is no current workaround for the version used here (7.*) and the backports for 5.* and 6.* have degraded performance because video hardware acceleration had to be disabled. I'm waiting for news from the Electron team.

**Comment by Aldekein** [comment]
Thanks, didn't know it, but now I've Google'd -
https://9to5mac.com/2019/11/04/electron-app-rejections/

**Comment by foss-** [comment]
For reference this is the Electron Issue: https://github.com/electron/electron/issues/20027

**Comment by TheGr8Wonder** [comment]
@tassoevan - Upgrading to Electron 8.0.2 will solve this issue - https://www.electronjs.org/releases/stable?page=1#release-notes-for-v802
I'm sure others are eager to have the updated app via the App Store!

**Comment by TheGr8Wonder** [comment]
Also version 7.1.14 - https://www.electronjs.org/releases/stable?page=1#release-notes-for-v7114.
2.17.7 was compiled using 7.1.10. So just bumping up to 2.17.8 with the later compile date and no additional changes _should_ solve this

**Comment by rpkoller** [comment]
...it got an update to version 2.17.9 in the Appstore three or four weeks ago. only downside that version is instantly and consistently crashing on startup :/
