### ISSUE TITLE
Marketplace - Pop-up buttons not working

### ISSUE THREAD

**Issue by rsjr** [RocketChat/Rocket.Chat.Electron#1455]
-> Operating System / Version / Architecture (64 bit?)

Linux x64

-> Rocket.Chat version

2.3.2
Electron 2.17.2 

-> Expected behavior

Pop-up buttons to work

-> Actual behavior

Cancel and Get buttons are not working, no action is done. The pop-up is closed only when hitting Esc key

-> Can the bug consistently be reproduced? If so, how?

1. Go to Administration > Marketplace
2. Select any Free app > Install
3. Pop-up will appear -> click in any button

-> Relevant errors and other log output

Uncaught ReferenceError: cancel is not defined
    at HTMLDivElement.onclick (buy?workspaceId=5defcc6…&token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50SUQ…:230)
onclick @ buy?workspaceId=5defcc6…&token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50SUQ…:230

-> Screen shots as necessary
![marketplace_popup](https://user-images.githubusercontent.com/11891939/71290807-2514ed00-2347-11ea-8682-e94a11fc973a.png)
![cancel_2](https://user-images.githubusercontent.com/11891939/71290815-2c3bfb00-2347-11ea-8711-cc0c1ae22202.png)

**Comment by graywolf336** [comment]
Will look into it. Until then, it should work in a web browser.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
