### ISSUE TITLE
problem with download files in desktop client

### ISSUE THREAD

**Issue by mohammadt-github** [RocketChat/Rocket.Chat.Electron#1456]
Hi
I install rocketchat recently. Do we can download files in desktop clients?
I can download all files in web browser but cant download with Windows Desktop app.
Thanx.

**Comment by tassoevan** [comment]
We can't help you because you have not filled in a proper bug template.

First read this:
https://rocket.chat/docs/contributing/reporting-issues

Then use this as a template:
https://raw.githubusercontent.com/RocketChat/Rocket.Chat.Electron/develop/.github/ISSUE_TEMPLATE.md

Thanks!
