### ISSUE TITLE
"Electron failed to install correctly, please delete node_modules/electron and try installing again" (After update to Electron7)

### ISSUE THREAD

**Issue by ghuser** [RocketChat/Rocket.Chat.Electron#1457]
## My Setup
- Operating System: Ubuntu 18.04.3 LTS
- App Version: 2.17.2 (actually 2.17.*)
- Installation type: source-code (using: `yarn install && yarn`. To run: `yarn start`)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

The code builds ok but on `yarn start` I get the following error: 

```
[12:22:08] [gulp-execa] electron .
/opt/Rocket.Chat.Electron/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^
```

- I have removed `node_modules/`, `~/.cache/yarn/` and  `~/.cache/Electron/` and then rebuild the app but the issue remains.

- This happens on all 2.17.* but not on 2.16.*. It seems to be related to Electron update. It could be possibly related to this issue: https://github.com/electron/electron/issues/20994

### Expected Behavior

The application should be able to start.

**Comment by tassoevan** [comment]
Have you checked for broken permissions on `~/.yarn-cache`?

**Comment by ghuser** [comment]
I think I had deleted the specific file when testing the issue but with no result. 

For some reason now it works: 
Tested on `2.17.2` and on current master (`2.17.5`).

**Comment by tassoevan** [comment]
Great! Please feel free to reopen this issue if needed.
