### ISSUE TITLE
I can not specify a password when creating a user.

### ISSUE THREAD

**Issue by dima23414** [RocketChat/Rocket.Chat.Electron#1458]
I can not specify a password when creating a user. Previously, when the Administrator created the user, it was possible to specify a password. But now the Administrator cannot do this. How to fix it???
![image](https://user-images.githubusercontent.com/59282502/71514949-90ac0c80-28a9-11ea-856f-82f18fba0fee.png)
Such a window opens. But the password field in this window has disappeared. Although it used to be.
![image](https://user-images.githubusercontent.com/59282502/71514975-ba653380-28a9-11ea-8f06-85290f8ebd6b.png)

**Comment by apaarfus** [comment]
This is a change made to the Rocket.Chat server, not the clients.  The current consensus by the development team is that the "Require Password Change" & "Set random password" are the most secure way to handle passwords in the UI, as administrators should not know them as per best practices.

To join the discussion, please head to [#15888](https://github.com/RocketChat/Rocket.Chat/issues/15880) for more details.

**Comment by MartinSchoeler** [comment]
As mentioned above, please head to #15888 for more details.
