### ISSUE TITLE
"Check for updates" shows no update even if there is new version

### ISSUE THREAD

**Issue by Roberto6969** [RocketChat/Rocket.Chat.Electron#1462]
## My Setup
- Operating System: WIN10
- App Version: 2.15.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
If i check for update on version 2.15.0 it says "No updates are available"

### Expected Behavior
It would be fine if latest version could be installed, in this case 2.17.2. Otherwise, please make available latest good version to be downloaded.
![Capture](https://user-images.githubusercontent.com/21200507/71830571-4bf15400-30a7-11ea-94c1-fcb2ce59ec09.PNG)

**Comment by apaarfus** [comment]
You can download the latest version of Rocket.Chat.Electron from the releases page, or even the [official product's webpage](https://rocket.chat/install).

I don't have the ticket number to hand, but there's also an issue with `electron-updater` that adds to the lack of automatic updates being reliable.

For the time being, I've just opted to telling our staff to manually update...or I'll take care of it for them whilst I'm working a different ticket for them.

**Comment by Roberto6969** [comment]
Perfect - just tested and .exe file now could be installed.

Thank You!

**Comment by apaarfus** [comment]
Welcome -- its a bit of a horky-borky workaround until actual updates can be implemented...something about the `electron-updater` package not being functional in production; but I know there's a big refactor going on; so hopefully the "just install a new version, it'll update then" workaround will be resolved sometime in the future.

**Comment by franckadil** [comment]
Linked to #1460 .

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by apaarfus** [comment]
I've just tested this within Windows Sandbox for 3.7.4 -> 3.7.5.  At least in this environment, it does appear to _actually_ prompt the user to install the update once the installer downloads:

![image](https://user-images.githubusercontent.com/38731016/149154383-eae0eac0-e556-473a-9e83-23f59f9859de.png)
