### ISSUE TITLE
[BUG] Broken notifications

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat.Electron#1464]
## My Setup
- Operating System: any
- App Version: a few latest versions
- Installation type: any

- [ ] I have tested with the latest version `I've tested it on v2.17-1, I think that people with MacOS have auto updates to latest`
- [x] I can simulate the issue easily

## Description
There are a lot of opened issues for broken notifications. I'm using RC desktop (linux 2.17-1) and notifications doesn't work (event with `test notification` working). It didn't work on linux 2.15-1 too. People using same RC server told me that they cannot receive notifications from channels and radnomly in DM (using MacOS).
I've found many opened issues for many platforms that notifications are broken. Can someone take a look at it.

**Related to:**
#1461 
#1454 
#1376 

### Current Behavior
1. Receive message in channel with turned on notifications
2. No notification, only channel highlight

### Expected Behavior
1. Receive message in channel with turned on notifications
2. Receive notification and channel highlight

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.3
- Operating System: Debian 9/10
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 8.15.1
- MongoDB Version: 6.9.0
*It`s not related to only one version of server. It's general issue on 3 servers (this one, one with RC 2.4.0 and one with unknown version)*

### Client Setup Information

- Desktop App or Browser Version: app
- Operating System: Linux / MacOS and so on

**Comment by tassoevan** [comment]
@dusatvoj Does it still happen in version 2.17.5?

**Comment by dusatvoj** [comment]
I'm using `v2.17.2` I'll upgrade and test.

**Comment by dusatvoj** [comment]
@tassoevan 
On my Arch linux with i3 is still the same. No urgent status of window, no notification received. :/
I'm using caprine and rocketchat. Both electron apps. Caprine's notifications works.

**Comment by kmil21** [comment]
Maybe this information help. On version 2.13.3 notification show counter.

**Comment by tassoevan** [comment]
It may have been fixed by #1662. Please let me know if otherwise.
