### ISSUE TITLE
Gray systray icon lacks contrast

### ISSUE THREAD

**Issue by Chealer** [RocketChat/Rocket.Chat.Electron#1465]
## My Setup
- Operating System: Windows 8
- App Version: 2.17.2

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The system tray icon is Rocket.Chat's logo with grey instead of red and a red disc bottom right when there are messages to read. But when there are none, the icon is a monochrome version of Rocket.Chat's logo only in gray.

As I do not keep Rocket.Chat's window continuously open, when I want to write to a contact, I open it from the systray. I therefore have to identify which systray entry I need to click. As the following screenshot shows, it can be non-trivial to identify which entry is Rocket.Chat's (in this case, it is the third):
![Rocket Systray](https://user-images.githubusercontent.com/486141/72016115-285a1500-3231-11ea-8850-aefa6a242ca5.PNG)

While I succeed to do so with time or by elimination, this process would be much faster/easier if the discreet version of the icon was more contrasted, so that at least the logo's shape can be easily identified. This could be achieved either by adding a color in the discreet version (for example, a black contour around the grey).

**Comment by ankar84** [comment]
I agree. Red contour RC icon (like Windows desktop icon) would be nice.

**Comment by GeorgeGedox** [comment]
> 
> 
> I agree. Red contour RC icon (like Windows desktop icon) would be nice.

Or completely white would help

**Comment by Chealer** [comment]
> 
> 
> > I agree. Red contour RC icon (like Windows desktop icon) would be nice.
> 
> Or completely white would help

I am not sure that simply changing the monochrome color would solve this generally. In my setup it would, but I expect that the result would be the same with a different theme / taskbar background color.

**Comment by Chealer** [comment]
Looking at this better, I think it would suffice (and make more sense) to take the logo displayed where there are unread messages, only substracting the red disc. That would have both gray and white.

**Comment by oaxiento** [comment]
+1 for an Icon that is visible on a light background. A red icon would be fine, blinking when there are any messages.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by Chealer** [comment]
@jeanfbrito For your information, I cannot reopen this ticket, but my organization has moved away from Rocket.Chat, so I do not intend to retest this at this time.
Thank you anyway if this is solved.
