### ISSUE TITLE
Application Quits on Startup (Sporadic)

### ISSUE THREAD

**Issue by apaarfus** [RocketChat/Rocket.Chat.Electron#1466]
###  My Setup
- Operating System: Windows 10 Pro 1909 x64 Build 18363.535
- App Version: 2.17.1 & 2.17.2
- Installation type: rocketchat-setup-2.17.X.exe

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
We've recently been receiving reports that the desktop application will, for _only some_ of our users, quit immediately after launching on startup.  Currently, reinstalling the application appears to resolve the issue for the time being, but I've not been able to track down the root cause, nor replicate the issue in my own environment.

All users affected have been using Windows 10 Pro 1909 x64, with either RocketChat version 2.17.1, or 2.17.2.  Due to the _still_ broken updates mechanic within RocketChat, not all of our users are always running the latest version--I'll update them when I'm made aware of this; however I've seen this issue occurring on both versions of the desktop application.

One other user was able to temporarily remedy this behavior by restarting their computer immediately after they noticed this issue.  However, I've been unable to confirm or deny whether this is a viable workaround to this issue; as I've been unable to do adequate testing.

### Current Behavior
On startup, as expected, the Rocket.Chat.Electron application starts as usual, and the systray icon is visible.  Almost immediately after the GUI is drawn on screen, the application fully quits without warning.  Any further attempt to start the application manually is met with the same behavior.

### Expected Behavior
I think it goes without saying that the expectation is for the application to launch and remain running until closed by the user.

### Additional Information
I'd like to add the the vast majority of issues our users have reported I've not run into on my production machine in the office.  At home, I've found a couple of the same bugs they've reported--but not too many.  Its possible that RocketChat is being falsely flagged as a PUA by our AV solution...however, I'd expect that behavior to be repeatable on all systems with the AV solution installed and running.

I will try to get additional information moving forward as I'm aware this sort of description without any error log is essentially pointless.

**Comment by tassoevan** [comment]
Maybe related to #1439?

**Comment by tassoevan** [comment]
@apaarfus Does the same happens in the latest version?

**Comment by apaarfus** [comment]
Since my initial post, I haven't heard any additional reports -- however:  since the "Check for Updates" dialogue is, to my knowledge, still not able to download/install updates properly; none of our users have updated beyond 2.17.2.  Unfortunately, as it stands, updating RocketChat to the latest version (and ensuring its actually updated & not ignored) requires me to personally visit every employee's desk, download & install the new version.  Considering how short the installation is, this isn't a huge deal on its own; though we have no had the chance since the initial post to push everyone to 2.17.5 or 2.17.7.

So, while I haven't heard any additional reports, nothing has changed on the clients' machines outside of Windows Updates.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by apaarfus** [comment]
We have received a handful of complaints from our users of this issue; however, not from any of the users that have migrated to the latest version.  Should this reappear, I'll _either_ reopen the ticket, or generate a new one.

**Comment by jeanfbrito** [comment]
> We have received a handful of complaints from our users of this issue; however, not from any of the users that have migrated to the latest version. Should this reappear, I'll _either_ reopen the ticket, or generate a new one.

Yes, please. We made a lot of fixes on the last releases, but if continues. tell me. Thanks!
