### ISSUE TITLE
Windows Overrides Notification Timeout Timer

### ISSUE THREAD

**Issue by apaarfus** [RocketChat/Rocket.Chat.Electron#1467]
## My Setup
- Operating System: Windows 10 Pro 1909 x64 Build 18363.535
- App Version: 2.17.2
- Installation type: rocketchat-setup-2.17.2.exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
We've been experiencing this issue with Windows since 2.15, when we first launched our deployment.  Within Rocket.Chat's preferences, the user may specify how long (in seconds) a notification should be displayed, as well as the option to require user interaction to keep the notification rendered.  Within a web browser, these features work fine.  However, the majority of our users have found that when using the Electron application, these settings are completely ignored within a Windows environment.

It would appear that, in Windows, notifications are limited by the "Ease of Access" settings for a given user account.

![image](https://user-images.githubusercontent.com/38731016/72089858-da015080-32da-11ea-9b06-e9fdc6054228.png)

As shown above, it would appear as though Windows will prevent desktop notifications from exceeding a 5 minute timeout as a maximum.  Its also important to note, that the setting here will affect notifications globally within Windows, meaning if your timeout setting here is set to "5 minutes", *_all_* notifications display on screen will be displayed for 5 minutes without user interaction.

From what I've found, it would appear that 5 minutes is the absolute maximum in regards to this setting -- more granular options are available, with registry changes...but no time entered into said keys above 5 minutes will be respected.

Please see the Additional Information below on why it may be worth looking into possible alternative notification options for Windows clients (if supported).

### Current Behavior
In-Application settings for notification timeouts & user interaction are completely ignored when used within a Windows-based environment.

### Expected Behavior
If possible, I'd expect the notification options within the application itself to actually be applicable.  If a user enables "require user interaction", I would expect the notifications to remain on-screen until the user interacts with it...assuming this is even possible in Windows at this point.

### Additional Information
I'm aware this may just be a quirk of Windows--but, hear me out.  Prior to deploying our RC instance, we had previously used an instant-messaging client known as "Fonality HUD 3.5.0".  The notifications for this application could, and would, completely disregard the Accessibility feature's timeout settings; as well as allow indefinite rendering of the notification.  However, the notifications for HUD didn't look anything like desktop notifications for Windows 7 or 10 specifically--in fact, they were the same UI design across both OS's.

From what I've been able to gather about those notifications, is that they are based on whatever notification scheme was used for Microsoft Office 2010.  Based on what little I can find about this style of notification, at one time it may have been referred to as "New Mail Desktop Alerts".  I've found this is possible to use as a notification system without relying on Office 2010 as a dependency, as HUD was able to utilize this functionality as a standalone application.  As an example, this is the notification style I'm referencing (Outlook 2010):

![image](https://www.howtogeek.com/wp-content/uploads/2010/07/sshot20100716162024.png)

While I'm not saying this particular style of notification is either usable or worthwhile; and alternative notification standard on the desktop client may be worth looking into, to obtain feature-parity with the web application in this regard...especially if the timeout/interaction settings are completely ignored on the Windows platform entirely.

**Comment by apaarfus** [comment]
Another quick not on the windows notification behavior -- if possible, a *reminder* notification may be a good alternative to trying to work around Window's global timeout; in a similar fashion to how mobile devices can be configured to send a secondary "don't forget about me" notification to the user if the notification hasn't been handled in `x` amount of time.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by apaarfus** [comment]
> Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.
> 
> Thank you!

I wouldn't say this issue is fixed, per se, as the option to specify a notification timeout length does not appear in user preferences anymore:

![image](https://user-images.githubusercontent.com/38731016/149152884-eb8f0d6a-f206-4447-8c45-f0744700e0aa.png)

However, defaulting to Windows' notification duration length is likely the best option; so I'll leave the ticket closed.
