### ISSUE TITLE
[BUG] Custom OAUTH not working in 2.17.0 and later

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1468]
## My Setup
- Operating System: Windows 10 1909 x64
- App Version: 2.15.5, 2.16.0, 2.17.0, 2.17.1, 2.17.2
- Installation type: exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
We are using a **custom oauth authenticator (KeyCloak)** and experiencing **oauth login problem** on Rocket.Chat.Electron versions **greater then 2.16.0**
Actually, I can not reproduse that bug on version **2.17.0** because it crashes right after start.
I have tested versions **2.15.5** and **2.16.0** - **oauth login process works fine**.
But versions **2.17.1 and 2.17.2** I get **blank oauth window** and **can not login to Rocket.Chat**.
![image](https://user-images.githubusercontent.com/4023037/72129807-99f8a700-3388-11ea-9874-a4737968802c.png)
![image](https://user-images.githubusercontent.com/4023037/72129830-aed53a80-3388-11ea-989a-e21604313eee.png)
![image](https://user-images.githubusercontent.com/4023037/72129839-b563b200-3388-11ea-8ca9-19f41a0e14b0.png)
![image](https://user-images.githubusercontent.com/4023037/72129814-a250e200-3388-11ea-9d4e-607fe089dc64.png) ![image](https://user-images.githubusercontent.com/4023037/72129826-a977f000-3388-11ea-8100-4af9ace49590.png)

### Current Behavior
With versions 2.17.1 and 2.17.2 user can not login to Rocket.Chat with custom oauth (KeyCloak) authorization.

### Expected Behavior
All latest versions should work with custom oauth (KeyCloak) authorization as older versions do.
Please fix it.
Thanks!

**Comment by ankar84** [comment]
Maybe somehow related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/669 but on computer with problem I don't use any proxy server. It is not domain joined.
@tassoevan please check my issue, thanks!

**Comment by ankar84** [comment]
Just tested version 2.17.2 official Linux client and it works fine.
So problem is on latest Windows clients only.

**Comment by ankar84** [comment]
I think it can be Kerberos related somehow.
On **domain joined computers** we added _KeyCloak URL_ to **Local Intranet zone** in **Internet Explorer Security Settings** and got SSO (no any username or password needed).
But on **workgroup computers** we get blank screen.

**Comment by ankar84** [comment]
@tassoevan I can give you connection details to try yourself.

**Comment by fcoppolani** [comment]
We have the same environnent (KeyCloak + Windows and same list of client apps) and the same issue, the root cause is quite complex and yet identified. We got back to 2.16.2 and it seems ok.

**Comment by ankar84** [comment]
I think it is realy Kerberos related
![kerberos](https://user-images.githubusercontent.com/4023037/73362125-dad54300-42d8-11ea-9dba-e7b57f12fdb7.gif)
Here you can see Kerberos Unsuported header on version 2.15.5
More modern version are stuck on that paticular stage.

**Comment by ankar84** [comment]
Another important information:
Version 2.17.2
Not domain joined computer
I **added KeyCloak URL to Local Intranet security zone in Internet Explorer settings** and blank screen was fixed!
Then I **removed KeyCloak URL from Local Intranet security zone in Internet Explorer settings and blank screen returned**!
**Trusted Sites zone did not fix that bug.**
So, I'am pretty sure  - that bug somehow related to **Integrated Windows Authentication (IWA) and Kerberos Authentication.**

And another experiment.
I disabled **Integrated Windows Authentication (IWA) in IE settings, restart IE.**
Then try to login in RC- blank screen and stuck.
Then **I added KeyCloak URL to Local Intranet security zone in Internet Explorer settings and blank screen was fixed**! Even **if Integrated Windows Authentication (IWA) was totaly disabled**.
So maybe it is **some IE setting that good for KeyClock in IE Local Intranet security zone and bad in other zones.**

**Comment by aimador** [comment]
Aaaaah you just saved my day 👍 🤣 
Had a similar issue here, but we have no popup, but redirect configured. We're in a domain environment here.
A user messed around with the internet settings (control panel -> internet settings -> security) and user authentication settings there and forgot to set those back. When you hit the OAuth login button, nothing happend after the loading animation.
I thought it was related to the latest updates for server and client.

The correct setting was under "user authentication" in each zone. I had to set "only login automatically in the intranet zone"

**Comment by ankar84** [comment]
@tassoevan I think this issue can be related to https://github.com/electron/electron/issues/20752

**Comment by ankar84** [comment]
I don't what changed (maybe rc server that 3.0.3 now or keycloak was updated, but workaround with oauth2 URL to Local Intranet zone do not works now. And the only solution for not domain joined Windows computers is to use version 2.16.2

**Comment by ankar84** [comment]
As a workaround I can advice this:

- Install [version 2.16.2](https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.16.2/rocketchat-setup-2.16.2.exe) (any pre 2.17)
- Login to RC successfully
- Update to [latest RC.Electron](https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.9/rocketchat-setup-2.17.9.exe)

**Comment by ankar84** [comment]
Works fine in 3.0.1
I successfully logged in though KeyCloak in that version.

**Comment by ankar84** [comment]
Totally fixed in 3.X versions
Thanks!
