### ISSUE TITLE
AppCrashes of Rocket.Chat.exe on MS W2K16 XenApp Terminalserver

### ISSUE THREAD

**Issue by mdbertmann** [RocketChat/Rocket.Chat.Electron#1469]
## My Setup
- Operating System: Windows Server 2016
- App Version: Rocket Chat Windows Client 2.17.2
- Installation type: rocketchat-setup-2.17.2.exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Since version 2.16 it is not possible to us to run the RC electron client on a Windows Server 2016 with enabled Terminalserver and XenApp on it. The one, who installs the software can run it. But when I connect as a different terminalserver user the app does not start an crashes immediately. A lot of application errors are then in the eventlog.
The RC Client was installed für "all users on this computer"

The only way to run it is to revert to 2.15.5

Is anybody else experiencing this issue?

## Error screenshots

![image](https://user-images.githubusercontent.com/41046930/72258026-5367ae80-360d-11ea-9ff0-100c28a63e90.png)

### Current Behavior
Application crashes.

### Expected Behavior
Application starts.

Thanks for your help
Martin

**Comment by tassoevan** [comment]
@mdbertmann Does it happen in latest version?

**Comment by mdbertmann** [comment]
Yes. It also happens with 2.17.5.

**Comment by rcadmin19** [comment]
This appears also with client version 2.17.7 on Windows Server 2012R2/Citrix environment.

**Comment by Tjan69** [comment]
I got the same Problem on a XenApp/W2k16 environment with Rocket Chat 2.17.7. You found a solution for this problem yet?

**Comment by PandaSITT** [comment]
Same problem with Windows Server 2019 (1809) and Rocket.Chat 2.17.7

**Comment by concellodeponteareas** [comment]
Same problem with Windows Server 2016/Citrix and Rocket.Chat 2.17.7 and 2.17.6 
No execute rocket chat desktop

**Comment by concellodeponteareas** [comment]
Solution: https://support.citrix.com/article/CTX265011

**Comment by PandaSITT** [comment]
> 
> 
> Solution: https://support.citrix.com/article/CTX265011

The Registry entry has caused other problems.
It's also a knows bug: https://support.citrix.com/article/CTX220418

**Comment by mdbertmann** [comment]
Works for me as well with the https://support.citrix.com/article/CTX265011 regkey.

**Comment by ohmvdek** [comment]
The Solution from https://support.citrix.com/article/CTX265011 doesn't work for me. I run into the grey screen problem described in https://support.citrix.com/article/CTX220418.

There is a reason why CTX265011 is no longer available and CTX220418 recommends to not use them, the registry keys can cause much more trouble than they solve.

On Windows Server 2016 with enabled terminal server and installed XenApp 7.15 LTSR I still run in the exact same error with Rocket Chat windows client 2.17.11.
Version 2.15.5 works fine.

Any ideas how to solve the problem?

Thanks for your help!
