### ISSUE TITLE
yarn release but Node_env don't change mode

### ISSUE THREAD

**Issue by khanhbao0508** [RocketChat/Rocket.Chat.Electron#1470]
## My Setup
- Operating System: Ubuntu 18.4
- App Version: 2.18.0-develop
- Installation type: .deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

i build yarn release and i have file install.deb when i finish run app NODE_env = 'development' mode not 'production' mode
i used solution:
 - add 'export NODE_ENV='production'' in appveyor.yml
 - electron-builder 
all solution doesn't work

**Comment by timololipop** [comment]
Hey, how did you resolve this?
