### ISSUE TITLE
App crash on window show (EventID 1000)

### ISSUE THREAD

**Issue by menkow** [RocketChat/Rocket.Chat.Electron#1471]
## My Setup
- Operating System: Windows 10 Pro N [Version 10.0.18362.592]
- App Version: 2.17.2
- Installation type: exe

- [ x] I have tested with the latest version

## Description
App crash commonly on show window after idle. Can't easily reproduce, but crashing very often (few times a day)

## Event Data
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
        <Provider Name="Application Error" />
        <EventID Qualifiers="0">1000</EventID>
        <Level>2</Level>
        <Task>100</Task>
        <Keywords>0x80000000000000</Keywords>
        <TimeCreated SystemTime="2020-01-16T05:57:19.844137800Z" />
        <EventRecordID>41346</EventRecordID>
        <Channel>Application</Channel>
        <Computer>DESKTOP-AFVH8DM</Computer>
        <Security />
    </System>
    <EventData>
        <Data>Rocket.Chat.exe</Data>
        <Data>2.17.2.1284</Data>
        <Data>5df95fad</Data>
        <Data>Rocket.Chat.exe</Data>
        <Data>2.17.2.1284</Data>
        <Data>5df95fad</Data>
        <Data>c000041d</Data>
        <Data>00000000021788e4</Data>
        <Data>2784</Data>
        <Data>01d5cc298e4775cf</Data>
        <Data>C:\Users\menko\AppData\Local\Programs\rocketchat\Rocket.Chat+\Rocket.Chat.exe</Data>
        <Data>C:\Users\menko\AppData\Local\Programs\rocketchat\Rocket.Chat+\Rocket.Chat.exe</Data>
        <Data>89639278-278b-4519-b0c5-7ab5607d92d0</Data>
        <Data />
        <Data />
    </EventData>
</Event>
```

**Comment by mtemmen-ww** [comment]
Having the same issue. Don't know if it has anything to do with it, but I'm always clicking on the icon in the system tray to open RocketChat. On some days it feels like every time I'm trying to open it, it crashes.

OS: Windows 10 Pro 1909 18363.535
App version: 2.17.1

**Comment by equinoxefr** [comment]
Same issue here. Windows 10 and Rocket 2.17.2

**Comment by equinoxefr** [comment]
Hi,

Some news about this issue. Since Rocket 2.17.3, it seems to be ok, no more crash. I didn't see anything in the changelog about a fix.

Best regards

**Comment by tassoevan** [comment]
Closing because #1439
