### ISSUE TITLE
Application hang when windows desktop app is minimised to the system tray then restored.

### ISSUE THREAD

**Issue by alex-nicholas** [RocketChat/Rocket.Chat.Electron#1474]
## My Setup
- Operating System: Windows 10 Pro v1709 (Can't upgrade past this due to AD limitations of my work network)
- App Version: 2.17.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I have the application configured to minimize to the system tray. When I try to restore the minimized app from the system tray, the application hangs. I receive a windows error saying the application has stopped responding and will be closed.

I have to then re-open the application, upon doing so, the last conversation I was in will display a red message in the chat window saying "Not Allowed". I must then move to a public room, close the application, re-open it again, and then re-enter the private conversation I was originally having to get back to where I was.

### Current Behavior
Application locks up when restored from being minimized to the system tray requiring multiple application restarts to be 100% operational again

### Expected Behavior
I should be able to restore a minimized application without the application crashing

**Comment by levifranzen** [comment]
I've updated to 2.17.4 and the bug hasn't occured so far.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
