### ISSUE TITLE
Ability to change the App icon (icon shows in task bar) and Favicon  

### ISSUE THREAD

**Issue by SamvegJain** [RocketChat/Rocket.Chat.Electron#1475]
## My Setup
- Operating System: Microsoft Windows 10
- App Version: 2.15.5 (Fix is not available in latest version 2.17.2 as well)
- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Ability to change App icon and Favicon are available for browsers. We need the same ability for Electron app as well. 

### Current Behavior
Not able to change the app icon and Favicon

### Expected Behavior
Should be able to change the icons

**Comment by tassoevan** [comment]
@SamvegJain I'm sorry, what is supposed to be the "app icon" and the "favicon" in this context? The executable icon is static (defined at build time), so are any shortcut icons (`*.lnk` files). The only ones that could be adjusted without doing a custom build, just by a setting, are the taskbar icon, the window title bar icon, and the system tray icon.

**Comment by tassoevan** [comment]
Closed by #1720

**Comment by giterium** [comment]
Where does the icon for the taskbar come from?
