### ISSUE TITLE
Ability to select the certificate from electron app

### ISSUE THREAD

**Issue by SamvegJain** [RocketChat/Rocket.Chat.Electron#1477]
## My Setup
- Operating System: Microsoft Windows 10
- App Version: 2.15.5 (Fix is not available in latest version 2.17.2 as well)
- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Currently electron app is automatically selecting the first certificate, in case of multiple certificates. Instead of giving user an option to select the certificate. 

### Current Behavior
If there are multiple certificates, then electron app is automatically selecting first certificate in line. 

### Expected Behavior
In case of multiple certificate, user should be displayed all the certificate installed and allowed to select the certificate.

**Comment by tassoevan** [comment]
Closed by #1511
