### ISSUE TITLE
Installing dmg version over appstore version lost settings

### ISSUE THREAD

**Issue by lkraider** [RocketChat/Rocket.Chat.Electron#1479]
## My Setup
- Operating System: macOS 10.14.6
- App Version: 2.16.0 -> 2.17.2
- Installation type: updating from App Store to latest DMG

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

After installing latest version over 2.16 and opening the app, all my servers are gone from the list.

Downgrading seems to work to restore the settings. Both open side by side:

![Screen Shot 2020-01-23 at 09 50 11](https://user-images.githubusercontent.com/52256/72985913-c9b2a080-3dc5-11ea-9486-97f3d5d5587e.png)

### Current Behavior

App opens asking for server info.

### Expected Behavior

Show all my previously configured servers.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
