### ISSUE TITLE
Feature request:  Information about other unread messages in tray icon

### ISSUE THREAD

**Issue by Vulg** [RocketChat/Rocket.Chat.Electron#148]
It would be helpful if the tray icon is similar to that of the slack. When there are messages in private groups, which I am a member, private messages and mentions the icon displays a red dot. When there are other unread messages it displays blue dot (without displaying any popup). It would be great if Rocket app behaved in the same way. Now we only have the red dot.

**Comment by rodrigok** [comment]
Which version are you using and OS?

We have the red dot with number inside when you have mentions and a red dot with a white dot inside when you have only unread messages.

For the number of mentions on the tray icon we already have an issue for that https://github.com/RocketChat/Rocket.Chat.Electron/issues/115

**Comment by Vulg** [comment]
At home I'm using Windows 10 x64. There are only to states of the tray icon
Everything_read is when I don't have unread messages but also when there are unread messages but without mentions.
![everything_read](https://cloud.githubusercontent.com/assets/17987108/13933121/e7332376-efab-11e5-843c-406be53b0f89.PNG)



Mention is displayed only when someone mentioned me or talked to me in private conversation.
![mention](https://cloud.githubusercontent.com/assets/17987108/13933120/e72d1e86-efab-11e5-9b37-3211c96615d0.png)

Tomorrow I'll check how it behaves on Ubuntu at work, and will check when the blue and red dot are displayed in slack app.

**Comment by rodrigok** [comment]
Sure, the "notification icon" over the tray icon is listed in this issue: #115

This is working for OS X since we can add text beside the icon, but we will do that for the other platforms until the version 1.3.0.

I will close this issue in favor to the #115, if you want you can add more information there.

Thanks
