### ISSUE TITLE
Opening multiple instances of the app.

### ISSUE THREAD

**Issue by Vulg** [RocketChat/Rocket.Chat.Electron#149]
In windows every time You run the exe new instance of the application is launched. I think it should reopen minimized window, or make it active window if it is opened but not focused. You could add option to run only one instance of the app if current behavior is needed.

**Comment by rodrigok** [comment]
Which version are you using? The application should allow one instance only.

**Comment by Vulg** [comment]
I'm using v1.1.0  on Windows 10 x64

**Comment by rodrigok** [comment]
@Vulg can you try the version [1.2.0](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/v1.2.0)?

**Comment by Vulg** [comment]
Works great. After second running exe file apps window is restored from systray. In Windows and on Linux.

**Comment by rodrigok** [comment]
Awesome
