### ISSUE TITLE
screenshare not working on bigbluebutton

### ISSUE THREAD

**Issue by jackydai** [RocketChat/Rocket.Chat.Electron#1490]
## My Setup
- Operating System:  macos 10.13.1
- App Version: 2.17.3
- Installation type:  dmg 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

i share my desktop through bigbluebutton, but screenshare not working.
bigbluebutton encountered an error.
`I20200131-00:07:55.487(8)? error: {"logCode":"startup_error","logDescription":"ReferenceError: ipcRenderer is not defined","extraInfo":{"stackTrace":"ReferenceError: ipcRenderer is not defined\n    at window.getScreenConstraints (https://xxx.top/html5client/compatibility/kurento-extension.js?v=VERSION:807:22)\n    at WebRtcPeerSendonly.WebRtcPeer...`

This is kurento-extension.js change record
https://github.com/bigbluebutton/bigbluebutton/commit/265275018e6a8a4c3133a8eab12c58663696e5cb

### Current Behavior

![image](https://user-images.githubusercontent.com/7478508/73597168-31a27d00-4564-11ea-9992-1c9048bba101.png)

bbb version:
BigBlueButton Server 2.2.0-rc-3 (1675)
                    Kernel version: 4.4.0-171-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16432 M

### Expected Behavior

screen sharing works

Thanks!

**Comment by jackydai** [comment]
i testing in Chrome screen sharing is work.

**Comment by jsalatiel** [comment]
Also having this problem using the linux client.
It works on Chrome, but It would be more professional it it worked on the Native Client.

**Comment by jsalatiel** [comment]
Running BBB 2.2.5 server.

**Comment by Askotion** [comment]
I have the same problem with the mac client. It works fine in the browser. (installed the latest BBB Server and RocketChat)

**Comment by Cormoran96** [comment]
Any upodate ?

Can you help us ? @wolbernd

**Comment by jsalatiel** [comment]
Rocketchat 3.2.2 fixed the screenshare problem for Firefox, but still it does not work for the desktop app ( at least on linux )

**Comment by fduba** [comment]
Same problem on windows with the last client 2.17.11

**Comment by Helyux** [comment]
Would be good if we could get some feedback from the dev team.

**Comment by salmoooon** [comment]
Same issue here, the windows desktop app version screen sharing doesn't work.

**Comment by welkervinicius** [comment]
Same issue here. Server and Windows desktop app in latest version. 

**Is there any way to make desktop app open bbb window on default browsers instead app?**

**Comment by jeanfbrito** [comment]
> Same issue here. Server and Windows desktop app in latest version.
> 
> **Is there any way to make desktop app open bbb window on default browsers instead app?**

Yes, there is a option in the settings nowadays.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
