### ISSUE TITLE
[FEATURE] Make some View settings manageable by administrators

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1491]
Please make some of **View** menu settings manageable for system administrators with file, like it done with **servers.json** and **update.json** files is **resources** folder for Windows Electron application
I mean that settings:
- Tray Icon
- Menu Bar
- Server List
![image](https://user-images.githubusercontent.com/4023037/73621234-6850c400-4646-11ea-90a0-f3eb3284e56d.png)
Thanks!

**Comment by tassoevan** [comment]
Do these admin level settings should be enforced or suggested?

**Comment by ankar84** [comment]
For us best option for that settings is enforced. But I think for everybody would be nice and more flexible to set default settings in file and some force parameter in same file.

**Comment by ankar84** [comment]
Hello, @jeanfbrito 
That feature https://github.com/RocketChat/Rocket.Chat.Electron#overridden-settings is solving that issue!
Than you!
