### ISSUE TITLE
Rockat.chat segmentation fault with dictionary

### ISSUE THREAD

**Issue by Xarkam** [RocketChat/Rocket.Chat.Electron#1492]
## My Setup
Rocket.Chat version 2.17.3
OS: Manjaro KDE 18.5.1

### Current Behavior
Hi, I add the french dictionary from chrome (.config/google-chrome/Dictionaries/fr-FR-3-0.bdic ) into rocket resources folder (/opt/Rocket.Chat/resources/dictionaries/) .
Rocket.Chat crash if I make right click on bad word for correcting.

```
[bugsnag] Loaded!
[1]    6846 segmentation fault (core dumped)  rocketchat-desktop
```
I see i my localstorage log file an syntax error, but I can't copy here.

### Expected Behavior
Using french chrome dictionary or another given by rocket.chat teams

**Comment by Orodeth28** [comment]
Hi all, i have the same problem. While i make a right-click on highlighted bad word, the application instantly crash. No problem for right-click when no words highlighted.

My setup : Rocket.Chat 2.17.3 on snap, using Xubuntu 18.04.

One difference : i haven't change the language selection for dictionary and haven't add the french dictionary.

```shell
------------------------------------------------------------
~ » rocketchat-desktop                                                                                                                                                                                                                                                    130 ↵
[bugsnag] Loaded!
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
[1]    15642 segmentation fault (core dumped)  rocketchat-desktop
------------------------------------------------------------
```

**Comment by tassoevan** [comment]
@Xarkam Are you using the snap version too?

**Comment by Xarkam** [comment]
@tassoevan no it's aur package https://aur.archlinux.org/packages/rocketchat-desktop/
It gets the archive from the github repository here.

I not tested under windows.

**Comment by tassoevan** [comment]
> No problem for right-click when no words highlighted.

And after that, I can right-click the highlighted ones without problem... Maybe it is a racing condition when using the spell checker module.

**Comment by ml-** [comment]
I do patch the spell checking code in the AUR package. Maybe I broke something. Will look into it.

**Comment by Xarkam** [comment]
I will test on a KDE Neon if I have the same result.

**Comment by ml-** [comment]
I could reproduce it on ArchLinux with my rocketchat-desktop package.

It only seems to happen when the word is misspelled (underlined) and a replacement exists for it.
Here is a stacktrace, excuse the lack of symbols:
```
#0  0x00007f71156bf3a8 in hunspell::BDictReader::GetReplacementIterator() const () at /tmp/.org.chromium.Chromium.7gf7AM
#1  0x00007f71156ba146 in SuggestMgr::replchars(char**, char const*, int, int) () at /tmp/.org.chromium.Chromium.7gf7AM
#2  0x00007f71156bc9b2 in SuggestMgr::suggest(char***, char const*, int, int*) () at /tmp/.org.chromium.Chromium.7gf7AM
#3  0x00007f71156b5911 in Hunspell::suggest(char***, char const*) () at /tmp/.org.chromium.Chromium.7gf7AM
#4  0x00007f71156b0a35 in spellchecker::HunspellSpellchecker::GetCorrectionsForMisspelling(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () at /tmp/.org.chromium.Chromium.7gf7AM
#5  0x00007f71156afa55 in (anonymous namespace)::Spellchecker::GetCorrectionsForMisspelling(Nan::FunctionCallbackInfo<v8::Value> const&) ()
    at /tmp/.org.chromium.Chromium.7gf7AM
#6  0x00007f71156ad1a2 in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) () at /tmp/.org.chromium.Chromium.7gf7AM
#7  0x000055aef3a0a48e in  ()
#8  0x0000000000000030 in  ()
#9  0x00007ffeedcc6010 in  ()
#10 0x0000000000000004 in  ()
#11 0x000015a969864310 in  ()
#12 0x00007ffeedcc5fe0 in  ()
#13 0x000055aef3cbf23a in  ()
#14 0x00001666710c04b1 in  ()
#15 0x0000000000000006 in  ()
#16 0x00002cf49bc9bff0 in  ()
#17 0x00002cf49bc9a648 in  ()
#18 0x00007ffe00000000 in  ()
#19 0x00000000000072ae in  ()
#20 0x0000000000000001 in  ()
#21 0x00002cf49ba16000 in  ()
#22 0x00007f71156ad100 in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) () at /tmp/.org.chromium.Chromium.7gf7AM
#23 0x0000000000000000 in  ()

```

**Comment by Xarkam** [comment]
I reference the #1497 because, It could be the same problem.

**Comment by daledavies** [comment]
I'm getting a very similar problem. Spell checker not working correctly (standard/default language), always incorrectly underlines first word (and other random words), when right click on an underlined word the app instantly crashes. Sometimes there is no cursor in the message box.

Ubuntu 18.04
Rocket.Chat App 2.17.5 installed as snap

**Comment by Orodeth28** [comment]
I have installed the release 2.17.5 on snap, i'm not able to reproduce the crash for highlighted word by the spell checker.
Thanks a lot for this speed patch !

**Comment by Xarkam** [comment]
I just tested on my Manjaro with AUR package and all everything seems to be working.
Rocket no longer crashes anymore and spelling work.
