### ISSUE TITLE
Rockat.chat update into 2.17.3 leave reference of deleted dictionaries

### ISSUE THREAD

**Issue by Xarkam** [RocketChat/Rocket.Chat.Electron#1497]
## My Setup
- Operating System: Windows 10 1909
- App Version: 2.17.3
- Installation type: exe

## Description
![image](https://user-images.githubusercontent.com/331816/73727015-ed180c80-4730-11ea-928b-23798affb068.png)
![image](https://user-images.githubusercontent.com/331816/73727392-a971d280-4731-11ea-846d-15c0638025d4.png)
![image](https://user-images.githubusercontent.com/331816/73727465-cad2be80-4731-11ea-80a2-187071c2c268.png)

### Current Behavior
I have updated Rocketchat from 2.17.2 to 2.17.3.
I still see the list of old dictionaries used in the old format.
But, they were installed in the dictionaries folder: `C:\Program Files\Rocket.Chat\resources\dictionaries`
I added the new FR dictionary from chrome.
The correction no longer works. As on the capture we see that no dictionaries are selected. That's why it doesn't work anymore. When I click to select a dictionary present on the disc, I do not have the check mark in the menu.
I do not understand how the list of old format dictionaries is still present.
There are no errors in the console.

### Expected Behavior
Using dictionary

**Comment by ankar84** [comment]
Same here. 
I copied dictionary file from c:\Users\UserName\AppData\Local\Google\Chrome\User Data\ru-RU-3-0.bdic to c:\Program Files\Rocket.Chat\resources\dictionaries\ru-RU.bdic but nothing happened.

**Comment by tassoevan** [comment]
The app always get the list of dictionaries by looking at the directory; nothing is cached besides the list of enabled ones. Is this happening even after restarting the app?

**Comment by Xarkam** [comment]
@tassoevan yes, is happening even deleting \AppData\Roaming\Rocket.Chat folder.

**Comment by tassoevan** [comment]
@Xarkam @ankar84 What about the `%AppData%\Microsoft\Spelling\` directory? Maybe the [Windows Spell Checking API](https://docs.microsoft.com/en-us/windows/win32/intl/about-the-spell-checker-api) is adding files there and the `@felixrieseberg/spellchecker` module is loading them by default.

**Comment by Xarkam** [comment]
@tassoevan no because it's come from Office
![image](https://user-images.githubusercontent.com/331816/73763728-21f88380-4772-11ea-9eea-235835ba4391.png)
And I have more fr spelling dictionaries referenced.

I have already searched for all the .dic files on my disks and cannot find anything.
Rocketchat is installed for all users of the machine.

In my listing the fr_FR-3-0 come from chrome. 
Even if the references are ghosts, I should be able to use the dictionary coming from chrome. This is not the case.

**Comment by ankar84** [comment]
> @Xarkam @ankar84 What about the `%AppData%\Microsoft\Spelling\` directory? Maybe the [Windows Spell Checking API](https://docs.microsoft.com/en-us/windows/win32/intl/about-the-spell-checker-api) is adding files there and the `@felixrieseberg/spellchecker` module is loading them by default.

For me it is 2 folders in c:\Users\UserName\AppData\Roaming\Microsoft\Spelling\ folder
![image](https://user-images.githubusercontent.com/4023037/73806469-a121a200-47da-11ea-976e-97e2de766aa1.png)

I updated to 2.17.5 
![image](https://user-images.githubusercontent.com/4023037/73806624-0bd2dd80-47db-11ea-991c-c7f059b4d8a6.png)
and I can see this:
![image](https://user-images.githubusercontent.com/4023037/73806546-d0d0aa00-47da-11ea-8c8e-9e2f65170cc0.png)
And now I can check ru-RU
![image](https://user-images.githubusercontent.com/4023037/73806572-e940c480-47da-11ea-954b-153d3fbbc1fa.png)
But spell check don work anyway
![image](https://user-images.githubusercontent.com/4023037/73806595-fcec2b00-47da-11ea-9281-5037fd111053.png)

Then I copied dictionary file from c:\Users\UserName\AppData\Local\Google\Chrome\User Data\ru-RU-3-0.bdic to c:\Program Files\Rocket.Chat\resources\dictionaries\ru-RU.bdic again and restart Rocket.Chat
And now I can not check ru-RU againg
![image](https://user-images.githubusercontent.com/4023037/73806769-80a61780-47db-11ea-96a5-faf1261c0456.png)
Then deleted c:\Program Files\Rocket.Chat\resources\dictionaries\ru-RU.bdic file and restart RC and now I can ckeck ru-RU again but Russian spell check do not work
![image](https://user-images.githubusercontent.com/4023037/73806903-df6b9100-47db-11ea-9f23-f368a9df401a.png)

**Comment by Xarkam** [comment]
Have tested the latest version.
I can select spelling dictionnary in my list:
![image](https://user-images.githubusercontent.com/331816/73860089-55531500-483b-11ea-8439-436744b943a2.png)
1. I selected fr-be but i have no idea where he finds it
2. I added fr-FR-3-0.bdic from chrome. I can't select he.

If you try to install spelling dictionnary with rocket.chat installed for all users and is not launched as administrator, you ha this error:
![image](https://user-images.githubusercontent.com/331816/73860404-c98db880-483b-11ea-862b-d2a71ec4375b.png)

**Comment by ankar84** [comment]
With version 2.17.7 dictionary selection is much better. And en-US spell checker works fine.
But ru-RU do not checking russian text. How to add Russian spell checker support to Rocket.Chat.Electron?

**Comment by tassoevan** [comment]
@ankar84 I've rolled-back to plain text dictionaries (pair of `*.aff` and `*.dic`). Are you importing both files?

**Comment by ankar84** [comment]
> @ankar84 I've rolled-back to plain text dictionaries (pair of `*.aff` and `*.dic`). Are you importing both files?

Yes.
I added dic and aff files from [here](https://extensions.openoffice.org/en/project/Russian_dictionary_AOT_base_ieyo)
I unpacked files, remane it and convert to UTF-8 in Notepad++
[dictionaries.zip](https://github.com/RocketChat/Rocket.Chat.Electron/files/4189607/dictionaries.zip)
But anyway no spell checking...
![image](https://user-images.githubusercontent.com/4023037/74298634-e31f8a80-4d7c-11ea-917f-f1ab384866b1.png)

**Comment by cdisabatino** [comment]
Other issue : https://github.com/RocketChat/Rocket.Chat.Electron/issues/1426

Version 2.17.7 offers few languages. There is no French whereas in a previous version, French was offered.

![image](https://user-images.githubusercontent.com/46713357/74314663-1e6a8b00-4d76-11ea-8780-d73876aa1035.png)

**Comment by Forage** [comment]
Again, French was not included by default in the past. You must have added it yourself manually. To have more included by default is a different discussion/issue though.

**Comment by Xarkam** [comment]
I tested last night under linux (arch) and I added the hunspell dictionary fr without problem by copy, but only with the root account.

I will test the day under windows if the addition goes well.

**Comment by cdisabatino** [comment]
Sorry but it looks like it is not a manual installation. Several colleagues installed the windows client and the fix worked. Personally, I keep the Windows client up to date to make sure it works properly before encouraging my colleagues to update their client.

Currently, a colleague, with version 2.15.5 has several dictionaries and the correction in French works. He did not do manual installation. Its dictionary folder does not contain the languages ​​offered in the rocketchat menu.

I found issues out.

With this https://github.com/RocketChat/Rocket.Chat.Electron/issues/169 I went back to the sources of Atom https://github.com/atom/node-spellchecker/issues/51.

https://github.com/atom/node-spellchecker/pull/69 and https://github.com/atom/node-spellchecker/issues/54 lets me imagine that a version of Atom allowed in a previous version to search for dictionaries on a PC.

I have not analyzed the rocketchat code. I don't have the skills.

Does this hypothesis seem plausible to you ?
It is not the code of rocketchat but of Atom ?

This could explain why the menu offers dictionaries that are not available in the rocketchat dictionaries folder.

**Version :** 
![rc_version](https://user-images.githubusercontent.com/46713357/74327285-30572880-4d8c-11ea-8b7a-a8b1297328b5.png)

**Proposed dictionaries :**
![rc_langues](https://user-images.githubusercontent.com/46713357/74327291-33eaaf80-4d8c-11ea-9e9c-e0e9848c29e6.png)

**Dictionary folder :**
![rc_directory](https://user-images.githubusercontent.com/46713357/74327298-351bdc80-4d8c-11ea-93fe-a9d8d544eda1.png)

**Functional correction in French :**
![rc_correct](https://user-images.githubusercontent.com/46713357/74327300-36e5a000-4d8c-11ea-8a11-41e4295ba179.png)

**Comment by cdisabatino** [comment]
I confirm my previous message.

On my computer, I uninstalled the windows client version 2.17.7 by deleting the user data. I installed version 2.15.5. I have not installed additional dictionaries. Spelling correction works in French. Rocktechat offers 20 dictionaries.

Version 2.15.5 : https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.15.5

**Comment by Forage** [comment]
They are not included in the different ZIPs, nor the DEB. So unless the EXE is the exception, they must be obtained in some other way on your system, or maybe some stale resource folder somewhere.

**Comment by tassoevan** [comment]
2.15.5 uses the [`spellchecker`](https://www.npmjs.com/package/spellchecker) package; until 2.17.5, [`@felixrieseberg/spellchecker`](https://www.npmjs.com/package/@felixrieseberg/spellchecker) was used. Both state the following:

> Native bindings to NSSpellChecker, Hunspell, or the **Windows 8 Spell Check API**, depending on your platform. Windows 7 and below as well as Linux will rely on Hunspell.

According to https://docs.microsoft.com/en-us/windows/win32/intl/about-the-spell-checker-api:

> The user-specific dictionaries for a language, which hold the content for the Added, Excluded, and AutoCorrect word lists, are located under **"%AppData%\Microsoft\Spelling\"**. The filenames are default.dic (Added), default.exc (Excluded) and default.acl (AutoCorrect). The files are UTF-16 LE plaintext that must start with the appropriate Byte Order Mark (BOM). Each line contains a word (in the Added and Excluded word lists), or an autocorrect pair with the words separated by a vertical bar ("|") (in the AutoCorrect word list). Other .dic, .exc, and .acl files present in the directory will be detected by the spell checking service and added to the user word lists. These files are considered to be read-only and are not modified by the spell checking API.

Please notice that all French dictionary names have hyphens (e.g. `fr-FR`), indicating they come from the Windows Spell Checking API because Hunspell conventions to use underscores (e.g. `en_US`).

2.17.7 depends on [`electron-hunspell`](https://www.npmjs.com/package/electron-hunspell) which provides only the Hunspell engine consistently across platforms. I've to ascertain @ankar84's report though.

**Comment by ankar84** [comment]
> 2.17.7 depends on [`electron-hunspell`](https://www.npmjs.com/package/electron-hunspell) which provides only the Hunspell engine consistently across platforms. I've to ascertain @ankar84's report though.

I confirm that pre 2.17.7 versions find a lot of system (?) dictionaries, because they have hyphens in their names (like en-US).
![image](https://user-images.githubusercontent.com/4023037/74501890-a5497000-4efc-11ea-8d5e-849702de7213.png)
![image](https://user-images.githubusercontent.com/4023037/74501901-ae3a4180-4efc-11ea-8942-00942b5258a9.png)

Version 2.17.7 find only dictionaries in folder c:\Program Files\Rocket.Chat\resources\dictionaries\ and one can easy check it by underscores in their names (en_US).
But anyway, I did not find the way to add Russian Spell checker functionality with two different Hunspell dictionaries: [one](https://extensions.openoffice.org/en/project/Russian_dictionary_AOT_base_ieyo) and [two](https://bitbucket.org/Shaman_Alex/russian-dictionary-hunspell/downloads/ru_RU_UTF-8_20131101.zip)
And help in that is appreciated.

**Comment by Forage** [comment]
Too bad non of that automatic importing has ever worked on Ubuntu (no matter which package was used) : https://github.com/RocketChat/Rocket.Chat.Electron/issues/1077

**Comment by tassoevan** [comment]
@Forage Since now we have some fine control over where to look for dictionaries, we don't need to wait for changes in those packages anymore.

**Comment by ankar84** [comment]
Fixed in 3.0
![image](https://user-images.githubusercontent.com/4023037/94756179-6b4fb000-039f-11eb-9c2d-13830bd46e7f.png)

**Comment by tassoevan** [comment]
Closed by #1737
