### ISSUE TITLE
The application crashes on the highlighted (marked) text after click on the right mouse button

### ISSUE THREAD

**Issue by stanom** [RocketChat/Rocket.Chat.Electron#1498]
## My Setup
- Operating System: `4.9.0-9-amd64 SMP #1 Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux`
- App Version: `2.17.3` (rocketchat-desktop), `rev 123`
- Installation type: `snap`

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
The application crashes on the highlighted (marked) text when I click on the right mouse button

### Expected Behavior
A pop-up (context) menu should be displayed

**Comment by stanom** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1492#issuecomment-581418777

**Comment by ml-** [comment]
Additional info: Only crashes when there are suggestions available. Simply typing it random characters that will receive no suggestions won't reproduce the issue.
