### ISSUE TITLE
Rocket.Chat.Electron deletes file extension in Save As dialog

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1501]
## My Setup
- Operating System: Windows 10
- App Version: 2.17.3
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When user try to download any file from RC.Electron client **Save As** dialog windows appeas and filename there **without extension**.
And if user do not add proper extension to file it will be saved **without any extension**.
But if user try to download file in RC web version (google chrome) - **file just downloads with proper name and extension**. So, it is RC.Electron bug.

### Current Behavior
Press **download icon** (cloud and arrow down) in RC.Electron client
![image](https://user-images.githubusercontent.com/4023037/73813581-755de680-47f1-11ea-9877-dbb5166a2bcc.png)
**Save As** dialog delete file extension
![image](https://user-images.githubusercontent.com/4023037/73813593-7db62180-47f1-11ea-9a5b-c802b0745baf.png)
And Chrome just download file after pressing **download icon**
![image](https://user-images.githubusercontent.com/4023037/73813630-99212c80-47f1-11ea-8659-2a23c2032ea6.png)

### Expected Behavior
File saved with it's extension. Maybe even without Save As dialog winodow.

**Comment by CitizenDev** [comment]
Can confirm, I have noticed this only with .txt files though

**Comment by ankar84** [comment]
> Can confirm, I have noticed this only with .txt files though

I see that with every file with every extension.
Here is examples with png and gif
![image](https://user-images.githubusercontent.com/4023037/73903583-874f9000-48aa-11ea-8562-521ca44899f7.png)
![image](https://user-images.githubusercontent.com/4023037/73903601-93d3e880-48aa-11ea-8798-ac7ec30fc521.png)
![image](https://user-images.githubusercontent.com/4023037/73903621-a0584100-48aa-11ea-88c0-bd5e2f7eb84c.png)
![image](https://user-images.githubusercontent.com/4023037/73903636-a64e2200-48aa-11ea-820f-f641964b1458.png)

**Comment by abhigyank** [comment]
Can't replicate on Linux, could it be a Windows specific issue (if it still exists?)

**Comment by ankar84** [comment]
Issue still persist in 2.17.11

**Comment by ankar84** [comment]
One more detail.
**On Windows 10 2004 Save As dialog works perfect** and file extensions remain with same 2.17.11 version.
![image](https://user-images.githubusercontent.com/4023037/92230543-81b83800-eed5-11ea-8d79-ca79c34a00a0.png)
![image](https://user-images.githubusercontent.com/4023037/92230570-8e3c9080-eed5-11ea-847a-20752aea1195.png)
![image](https://user-images.githubusercontent.com/4023037/92230597-9694cb80-eed5-11ea-95ed-17352797633d.png)
![image](https://user-images.githubusercontent.com/4023037/92230615-9eed0680-eed5-11ea-916c-65881941719f.png)
![image](https://user-images.githubusercontent.com/4023037/92230630-a6acab00-eed5-11ea-8915-06506b42837c.png)

**Comment by ankar84** [comment]
Unfortunately 3.0.1 not fixed this yet...
![image](https://user-images.githubusercontent.com/4023037/94891573-1db07180-048b-11eb-82ac-92eca177180b.png)
![image](https://user-images.githubusercontent.com/4023037/94891588-2739d980-048b-11eb-8edd-60613c318331.png)
![image](https://user-images.githubusercontent.com/4023037/94891604-31f46e80-048b-11eb-9140-74fcf38016c5.png)
![image](https://user-images.githubusercontent.com/4023037/94891636-49335c00-048b-11eb-80d6-c92302e1bcb9.png)
![image](https://user-images.githubusercontent.com/4023037/94891651-54868780-048b-11eb-8e9b-e73dd7528a19.png)

Windows 10 1809
![image](https://user-images.githubusercontent.com/4023037/94891664-623c0d00-048b-11eb-88b1-188bd56d6499.png)

**Comment by ankar84** [comment]
Same files on same RC desktop app version 3.0.1 but on Windows 10 2004 saving perfect
![image](https://user-images.githubusercontent.com/4023037/94919817-45312980-04df-11eb-9a44-a280b51cb92d.png)
![image](https://user-images.githubusercontent.com/4023037/94919722-216de380-04df-11eb-963a-3b579cad8670.png)
![image](https://user-images.githubusercontent.com/4023037/94919742-29c61e80-04df-11eb-9197-150498c4c293.png)
![image](https://user-images.githubusercontent.com/4023037/94919784-3b0f2b00-04df-11eb-8f99-08e3a6664f97.png)

**Comment by ankar84** [comment]
Definitely fixed
![image](https://user-images.githubusercontent.com/4023037/95038760-a7ed1580-06d7-11eb-8591-b03f07b984da.png)
