### ISSUE TITLE
App does not show up anymore when started since 2.17.3

### ISSUE THREAD

**Issue by atemp** [RocketChat/Rocket.Chat.Electron#1502]
## My Setup
- Operating System: CentOS 7.7.1908
- App Version: 2.17.3, 2.17.4, 2.17.5
- Installation type: RPM

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When the app is started it shows no window, no tray icon but it does not die:
```
> /opt/Rocket.Chat/rocketchat-desktop 
[bugsnag] Loaded!
```
That happens even with a test user that has not been logged in before. I tried the following desktop environments, but the result is always the same:
* GNOME 3
* XFCE
* MATE

### Current Behavior

App is not starting. Downgrade to 2.17.2 makes it work again.

### Expected Behavior

The app should show a window.

**Comment by selimt** [comment]
Same here. With 2.17.5 no window shows up. We are on Cent OS 7.4.

**Comment by atemp** [comment]
works again for me with `rocketchat-2.17.7.x86_64`

**Comment by atemp** [comment]
one more comment: for some users it was necessary to remove `~/.config/Rocket.Chat`, else the app would stop directly after starting

**Comment by selimt** [comment]
@atemp Thanks, I can confirm that it works with 2.17.7.
