### ISSUE TITLE
Restoring maximized window from tray restores to not maximized window size

### ISSUE THREAD

**Issue by Vulg** [RocketChat/Rocket.Chat.Electron#151]
### Action:
Set window to maximized from "normal" size and send it to tray via X button. Then restore application from tray.

### Output:
Window is restored in "normal" size.

### Expected-output:
Window restored in maximized state.

### Specs:
Windows: 10 and Ubuntu 14.04
Electron: 1.2.0
Rocket.chat: 0.22

**Comment by corell82** [comment]
+1 on Windows 7

**Comment by graywolf336** [comment]
This is happening to me as well.
