### ISSUE TITLE
2.17.5 do not start on XFCE

### ISSUE THREAD

**Issue by paulz1** [RocketChat/Rocket.Chat.Electron#1513]
## My Setup

- Operating System: CentOS 7, XFCE
- App Version: 2.17.5
- Installation type: rpm (yum install rocketchat-2.17.5.x86_64.rpm)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Just installed the latest version 2.17.5 using 
```
yum install rocketchat-2.17.5.x86_64.rpm
```
The application do not start now. 
Launching it via CLI a get an error :

> [bugsnag] Loaded!
> xdg-settings: default-url-scheme-handler not implemented for xfce

### Current Behavior
Application do not start

### Expected Behavior
Application should start.

1) Additional comment. The previous version I used was : 2.17.2 and it worked.

2) During installation there were some warnings :

> Unknown media type in type 'all/all'
> Unknown media type in type 'all/allfiles'
> Warning in file "/usr/share/applications/fedora-gnumeric.desktop": usage of MIME type "zz-application/zz-winassoc-xls" is discouraged ("zz-application/zz-winassoc-xls" should be replaced with "application/vnd.ms-excel")

3) It could be linkedf to #1060 but not sure.

**Comment by tassoevan** [comment]
Maybe related to #1502 too.

**Comment by atemp** [comment]
> `xdg-settings: default-url-scheme-handler not implemented for xfce`

This warning comes from an old xdg-utils package included in CentOS 7, updating it to e.g. 1.1.3-5 (rebuilt from fc31) solves that, but the app still does not start. So i guess its a different problem.

**Comment by paulz1** [comment]
Just tried on 2.17.7 and it's gone. The application starts successfully.
I do not know that you have changed, but thank you very much :-)

I think we could close this ticket.
