### ISSUE TITLE
[FEATURE] Add Russian Spell checker dictionary

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1516]
Please add the Russian dictionary.
After version 2.17.7 bdic file no good, but you can add dic and aff files from [here](https://extensions.openoffice.org/en/project/Russian_dictionary_AOT_base_ieyo)
I unpacked files, rename it and convert to UTF-8 in Notepad++
[Russian dictionary for Hunspell](https://github.com/RocketChat/Rocket.Chat.Electron/files/4189607/dictionaries.zip)
I also did try [dictionary](https://bitbucket.org/Shaman_Alex/russian-dictionary-hunspell/downloads/ru_RU_UTF-8_20131101.zip) from [here](https://code.google.com/archive/p/hunspell-ru/) with no luck.

**Comment by tassoevan** [comment]
@ankar84 Could you give me some example words that should pass and fail the spell checking?

**Comment by ankar84** [comment]
> @ankar84 Could you give me some example words that should pass and fail the spell checking?

**привет тест** should pass and _привт тетс ккк очепятка_ should fail he spell checking as on screenshot:
![image](https://user-images.githubusercontent.com/4023037/74523779-d347a800-4f2e-11ea-9727-b4b9fa17d9f0.png)

**Comment by tassoevan** [comment]
@ankar84 Ok, I've found the root cause. We couldn't do multi-language checks.

**Comment by ankar84** [comment]
> @ankar84 Ok, I've found the root cause. We couldn't do multi-language checks.

Great! Good news!
But actually I did try to enable only ru_RU with no luck.

**Comment by tassoevan** [comment]
@ankar84 Actually, it's the way we call `webFrame.setSpellCheckProvider()`. The first parameter is empty, but Electron expects a language to filter which character set should compose words.
