### ISSUE TITLE
default server leads to a security problem by unneeded users

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Electron#1521]
## My Setup

- Operating System: Win/macOS/Linux (all clients)
- App Version: 2.17.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
After installing the desktop client, the server open.rocket.chat is set as default in the input line for the server. In our environment we observe quite a lot of users who do not enter our own "internal" server URL after installing the client (although our documentation clearly states our server address), but simply click on "connect", thereby connecting to the open.rocket.chat server and entering their local access data, but think or are believed to be connected to the server of their own organization. This way, user data of an organization is transferred to third parties, Rocket.Chat. I trust Rocket.Chat as an organization of course, but from a security point of view this is ultimately a security risk. Admittedly, this is of course misconduct on the part of the users, but it is still a security risk that inexperienced users disclose their local user data. This problem could be solved by a version of the desktop client pre-built with the server data, but then an admin would have to package the clients for each operating system including the mobile apps. This would involve considerable effort. Of course I understand that Rocket.Chat wants to offer its own open platform as low-threshold as possible. But this might be a security risk for other systems.

![grafik](https://user-images.githubusercontent.com/8544984/74477581-d5b4ee00-4eab-11ea-8206-906bebb53f88.png)

### Current Behavior

open.rocket.chat is set as default

### Expected Behavior

no default server or a secure way not to "accidentally" connect to it

**Comment by ankar84** [comment]
In our organization we do not have that issue at all.
All you need to do is add **servers.json** file to folder **c:\Program Files\Rocket.Chat\resources\** and configure your own server in **servers.json** file.
So every Rocket.Chat.Electron application will connect to your RC server at startup.
And no security breach at all.

**Comment by aimador** [comment]
We also had to configure that, but despite having rolled out the server.json to all clients, a handfull still managed to connect to the wrong server - after several months that is.
If the server.json is present, it should hide the server bar on the left. But via the upper menu bar some still managed to select the wrong server by accident - as stupid as that might sound. They frantically called us to fix it. Anyway, there should be an option to completely hide or restrict access to other servers. But I guess that would be an improvement suggestion for the server section.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
