### ISSUE TITLE
provision to create internal team group

### ISSUE THREAD

**Issue by ansalok** [RocketChat/Rocket.Chat.Electron#1528]
## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by tassoevan** [comment]
We aim to keep our Github issues for bugs, and this entry does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
