### ISSUE TITLE
Select/Right copy click uses 100% CPU on multi line message

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.Electron#1529]
## My Setup

- Operating System: Xubuntu Bionic 18.04
- App Version: 2.17.7
- Installation type: deb

- [x] Tested on open.rocket.chat
- [x] I can simulate the issue easily - 3 desktops so far

## Description
Select message text, right click, try and select copy

### Current Behavior
As the message line length increases the hang time increases, especially if you have a blank line in the message

Select a couple of words and it isn't noticeable. As you select more lines it increases.

Possibly due to the context sensitive right click menu trying to work out if it has URLs in there or spellcheck etc?? 

It IS inconsistent though, but I can reproduce regularly and it is driving my users mad.

No errors in devtools 

I also note that despite having hunspell installed with dictionaries I get no spell checking and wonder if this is related?

(did experience this originally but added the directory manually - that stopped the log noise but the issue persisted

app.js:6161 Error: ENOENT: no such file or directory, scandir '/home/server/files/users/john/.config/Rocket.Chat/dictionaries'
getPairsOfDictionaryFiles @ app.js:6161
)

https://github.com/RocketChat/Rocket.Chat.Electron/commit/c11600ca509c8c1806c734b189a33981b5ba002e

https://github.com/RocketChat/Rocket.Chat.Electron/commit/c11600ca509c8c1806c734b189a33981b5ba002e#commitcomment-37155896

I can see these installed which Rocket seems to completely ignore:
/usr/share/hunspell/en_GB.aff
/usr/share/hunspell/en_GB.dic
/opt/Rocket.Chat/resources/dictionaries/en_GB.aff
/opt/Rocket.Chat/resources/dictionaries/en_GB.dic

These all seem related to the dictionary issue:

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1520
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1497
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1077

### Expected Behavior
No delay on right click, copy

**Comment by reetp** [comment]
Is this related too?

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1144

**Comment by tassoevan** [comment]
This seems to be a bug related to spell checking. I'll test it ASAP.

**Comment by Ahmad-Ali-Sherazi** [comment]
Yes its also happens for me too 

My Setup : Windows 10 pro education
App version : 3.0.0-develop

**Comment by Schwuuuuup** [comment]
I had 2.16.x installed and then installed 2.17.9 as a snap on Linux Mint. German spelling was not recognized anymore and I got that error in the dev console:

`app.js:6161 Error: ENOENT: no such file or directory, scandir '/home/<username>/snap/rocketchat-desktop/157/.config/Rocket.Chat/dictionaries'`

**Comment by Schwuuuuup** [comment]
Oh scratch that It works after RE-selecting my language

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
