### ISSUE TITLE
All words are triggering the spell-checker red line

### ISSUE THREAD

**Issue by agentirons** [RocketChat/Rocket.Chat.Electron#153]
Trying out the 1.2.0/build 13 release, found that every word I type is getting the red underline for spellchecking.

**Comment by rodrigok** [comment]
Which OS are you using?

**Comment by bgomelsky** [comment]
@agentirons Make sure that at least one option is checked under "Spelling languages" menu.

**Comment by agentirons** [comment]
@rodrigok Sorry, this is the OSX client. This morning when I got in I updated to 10.11.4 and now the problem has vanished. It's not clear that you can right click on the text input to find the Spelling Languages menu that @bgomelsky mentioned, but when I did I saw that 'en' was now checked, and unchecking returned the spellchecking red lines. I see there was an issue about this a few weeks ago: https://github.com/RocketChat/Rocket.Chat.Electron/issues/119 - Is 'en' checked by default?

**Comment by rodrigok** [comment]
Yes, we try to get the language from your Rocket.Chat profile and from your "navigator" to enable by default.

So I will close this issue, if you you have more problems please reopen it.
