### ISSUE TITLE
Custom OAuth issues since RC 3.0.0

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat.Electron#1531]
## My Setup

- Operating System: Win10  Pro x64
- App Version: 2.17.2 & 2.17.7
- Installation type: exe

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
We use Keycloak for OAuth here. Since the Server Update to Version 3.0.0 multiple users, but not all,  experience login problems with the desktop client. They click on the login button, the circle animmation on the button starts, and then nothing happens. On the server side no logs are generated.
The browser version is not affected.

What we had to do after the update of RC: 
- Nodejs had to be updated as well, which caused some trouble.
- We had to change the custom OAuth settings (login URL) from https to http, since our nginx has a redirect configured. With https we could not login anymore at all with OAuth. I know that the Android App and the Desktop Client had some issues with this roughly less than a year ago.

This issue could be related to this: [1468](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1468)
I've posted there already, but that was a different matter (misconfiguration of IE settings for Kerberos SSO). The affected users now have standard settings.

Reload ignoring cache, un- and reinstalling the Client, deleting the RC Profile folder under Appdata\Roaming, and updating from 2.17.2 to 2.17.7 did not help either.

### Current Behavior
Login fails, nothing happens.

### Expected Behavior
Login via OAuth should work on all clients.

**Comment by ankar84** [comment]
Hi! #1468 is my issue.
And I can tell you, that we a currently testing RC 3.0.0 in test environment and have no problem with KeyCloak login nor at domain joined computers nor at workgroup computers where KeyCloak FQDN is in Local Intranet security zone on Internet Explorer. If I remove KeyCloak FQDN from Local Intranet security zone on Internet Explorer - I get white screen with RC.Electron 2.17.7 and RC 3.0.0.
Can you try it in your environment on clients with problem?

**Comment by aimador** [comment]
Hi, 
I've just double checkend and can confirm, that all our machines have the same settings. The Keycloak FQDN is set in the internet options (tab "security" -> intranet zone -> sites -> additional settings) on all our machines. Why would some of them fail to login?
We do not get the "white screen" since we use the redirect option in the custom OAuth settings. Our symptom is a frozen login button.
I've tried different users on the affected machines. It's definitely not a user problem :)
I've also tried different client versions. 2.16.2 does not handle the nginx redirect properly, 2.17.0 crashes after 1 second and 2.17.1 and above fail to log in.

**Comment by ankar84** [comment]
> I've just double checkend and can confirm, that all our machines have the same settings. The Keycloak FQDN is set in the internet options (tab "security" -> intranet zone -> sites -> additional settings) on all our machines. Why would some of them fail to login?

Could you please try to add Keycloak FQDN to Local Intranet security zone on Internet Explorer on onw single computer with problem? Just for a test reasons.


> We do not get the "white screen" since we use the redirect option in the custom OAuth settings. Our symptom is a frozen login button

Yes, that's because you set to redirect. If you try to set New window you will get a white screen in that new window.

**Comment by aimador** [comment]
Sorry, there was a typo there. It should say intranet, not internet. It is already set. Yes, i can also confirm the white window.

**Comment by ankar84** [comment]
> Sorry, there was a typo there. It should say intranet, not internet. It is already set. Yes, i can also confirm the white window

You need to find out what is the difference between nornal and problem computers. For example, maybe problem computers go to KeyCloak though proxy server and normal computers has direct connection (KeyCloak URL excluded from proxy)

**Comment by aimador** [comment]
Can be closed. We had an old config entry in the systemd service file "node --tls-cipher-list". After removing that all our clients started to behave normally again. Some had to wait for the Keycloak token to expire. IOs and Android apps seem to be ok now. The frozen login button in the desktop app apparently is also fixed apparently.
