### ISSUE TITLE
RC.Electron 2.17.3 crashes on Windows 7

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1532]
## My Setup

- Operating System: Windows 7
- App Version: 2.17.3
- Installation type: exe

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When select text and get context menu on that text, RC.Electron crashes on Windows 7
![crash](https://user-images.githubusercontent.com/4023037/74829611-754a0480-5322-11ea-91e4-86448db9cac1.gif)

### Current Behavior
May be related to #1529
2.17.7 not affected! And that's  good!

### Expected Behavior
RC.Electron do not crash

**Comment by CitizenDev** [comment]
I'm pretty sure that we should not maintain compatibility for out of service abandoned operating systems.

**Comment by ankar84** [comment]
> I'm pretty sure that we should not maintain compatibility for out of service abandoned operating systems.

I agree with you in that perspective, but anyway Windows 7 still installed on tons of computers.
But 2.17.7 not affected of that bug, we will update client.

**Comment by tassoevan** [comment]
Closing as it should've been fixed on 2.17.7.
