### ISSUE TITLE
Cursor disappearing from message composer

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.Electron#1536]
## My Setup

- Operating System: macOS 10.15.2 (+ Windows clients are apparently affected as well) 
- App Version: 2.17.7
- Installation type: DMG

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

Sometimes the mouse cursor disappears in the message composer while typing a message, which can get quite confusing.

### Current Behavior

Mouse cursor should be always visible.

### Expected Behavior

Mouse cursor disappears under certain conditions. Here's one to reproduce the issue:

1. Open any Rocket.Chat server within Electron client
2. Make sure mouse cursor is within the message composer bos
3. Hit <kbd>CMD</kbd> + <kbd>R</kbd>, to reload the current server
4. Notice how the mouse cursor is hidden but the input focus is still on the composer box.

### Demo video:

[<img width="1876" alt="Bildschirmfoto 2020-02-24 um 13 26 47" src="https://user-images.githubusercontent.com/944459/75152453-56c08080-5709-11ea-88cf-80091923323d.png">
](https://up.frd.mn/s82Cf3.mp4)

**Comment by longvubka98** [comment]
I'm facing the same problem

**Comment by rcadmin19** [comment]
This is a real problem when signing in with external IDP (SAML) and you have to enter credentials and OTPs. Each time when new login page is loaded you have to minimize/maximize the client window.  And again when logged in and entering message. Not so user friendly.

**Comment by subesokun** [comment]
Same issue here. What's even worse is that you can't type the special character ` for some reason if that bug occurs.

**Comment by foss-** [comment]
This is a bug that has existed for much longer than when this issue was filed. Somewhat amazing it has not yet been addressed. It's quite irritating to not have a cursor in a mostly text based application.

**Comment by rodrigok** [comment]
For me I just need to switch the focus to another application and go back, then the cursor appears.

**Comment by nachtgold** [comment]
I have the same bug on Mac and Win after reloading the content with shortcut (CTRL+R or CMD+R)

**Comment by rcadmin19** [comment]
Just tested desktop client version 3.0.1 (Win10 x64) and unfortunately the bug still exists.

**Comment by rcadmin19** [comment]
I did some more testing with 3.0.1 and for example login with external IDP (SAML) does not hide the cursor in username and password fields anymore which was the situation earlier. But after Help / Reload the cursor still disappears from the message composer field but that's not a real problem anymore I think. Still continuing testing anyway.
