### ISSUE TITLE
SAML Login method not working on Electron [Windows only]

### ISSUE THREAD

**Issue by rsjr** [RocketChat/Rocket.Chat.Electron#1538]
## My Setup

- Operating System: Windows 10 (latest)
- App Version: 2.17.7 (latest)
- Installation type: .exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
SAML login method is not working on Electron app, occurring only on Windows.

### Current Behavior
While trying to use SAML login method on Electron, "server failed to load" error is triggered
Sometimes the issue happen in the first time, but most likely when clicking in the SAML, then going back. In the second time it will fail on server failed to load.

![Screenshot - Server Faild to Load](https://user-images.githubusercontent.com/11891939/75802972-6ae52d00-5d5c-11ea-8ae1-41689da148e2.png)

**Comment by rainer-wei** [comment]
Any update on this?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
