### ISSUE TITLE
uninstall cmd switch for Windows?

### ISSUE THREAD

**Issue by nexidus** [RocketChat/Rocket.Chat.Electron#1539]
## My Setup

- Operating System: Windows 10 1909
- App Version:  2.17.4
- Installation type: exe over GPO deploy (copy file to client, copy cmd file to client what starts installation with /S /disableautoupdate switch)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

It is certainly not a mistake, but we have the following situation. We have been using Rocketchat since a very early version and have still installed it without /allusers switch. So it is installed directly for the user. We wanted to change this centrally and remove it completely and at the same time reinstall it with /allusers. Unfortunately I can not find an uninstall switch, even when trying out the usual options, only the installation process is always started. However, we cannot go to each user individually and uninstall the app, because the app does not appear under wmic product get name either.

Is there an uninstall switch? Or is there another sensible way to solve the problem?

If there is no uninstallswitch, it would be good if this were added, or, as has been desired elsewhere, an MSI package.

**Comment by gabriellsh** [comment]
We indeed want to implement a MSI package installation soon. Will keep this open for the record.

**Comment by havx** [comment]
> Is there an uninstall switch? **Or is there another sensible way to solve the problem?**

You could write a simple, one-line command that executes the uninstaller found in the user's `\AppData\Local\Programs\rocketchat\` directory. Deploy via GPO with it running when the user logs in. Don't forget the `/S`!
