### ISSUE TITLE
The error page is not shown if the server is down (response 503)

### ISSUE THREAD

**Issue by ramrami** [RocketChat/Rocket.Chat.Electron#1545]
## My Setup

- Operating System: macOS
- App Version: 2.17.8
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
If the server is down (returns a response 5xx), the desktop app does not show error page.

### Current Behavior
The app print the server response "503 Service Unavailable ..."
<img width="993" alt="Capture d’écran 2020-03-12 à 23 11 24" src="https://user-images.githubusercontent.com/9569590/76571005-d5157480-64b6-11ea-8139-3603d8c865b5.png">

### Expected Behavior
Show error page when the server is down.

### More context
Looking at the source code in `src/scripts/webview.js` there is an event listener `did-get-response-details` which is supposed to handle this case, but it was deprecated and removed from `electron` in a previous version :

```js
webviewObj.addEventListener('did-get-response-details', (e) => {
    if (e.resourceType === 'mainFrame' && e.httpResponseCode >= 500) {
         webviewObj.classList.add('failed');
    }
});
```

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
