### ISSUE TITLE
snap: Electron not starting up on Linux

### ISSUE THREAD

**Issue by lazyfrosch** [RocketChat/Rocket.Chat.Electron#1552]
## My Setup

- Operating System: Debian testing / Ubuntu 19.10
- App Version: 3.0.0-develop 2020-03-13
- Installation type: snap

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

After switching in snap from the stable to the beta channel, the application is no longer starting.

You can see the Electron processes in the process viewer, but no UI appears at all.

I haven't tested with the normal packages yet. Let me know if I can test / do anything. I'm not sure how to debug Electron...

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
