### ISSUE TITLE
macOS - reinstalling app does nothing (also no camera permission)

### ISSUE THREAD

**Issue by customizeXF** [RocketChat/Rocket.Chat.Electron#1553]
Using macOS 10.15.3 and RocketChat 2.17.7

After removing the app from mac and reinstalling it all configurations stay. Nothing happens, I'm instantly logged in to my servers after launching the app. So no server login credentials are asked, nothing. 

I tried to remove the app with ForkLlift app too. All files and folders moved to trash, but the result after installing it again is the same. Like no config files are deleted or something else.

The reason for reinstalling is that I can't use camera from my iMac with RocketChat. There is no app in System preferences > Security & Privacy where I could grant permission.

Any help appreciated.

**Comment by iwonazytkiewicz** [comment]
Exactly the same case at our side. He downgraded to version 2.17.3 to have it working. At least 3 cases that confirm this. I hope it helps you before it gets fixed.
Best, 
Iwona

**Comment by maze0203** [comment]
Same here. Had to downgrade to version 2.17.3. But I'm using Ubuntu 19.10 with Gnome 3.34.2

**Comment by User35123** [comment]
Same here. Also does not work on 2.17.9. Works fine on 2.17.3. System: macOS 10.15.4

**Comment by customizeXF** [comment]
Works with 2.17.9.

I uninstalled version 2.17.7 with the help of ForkLift app. So completely removed everything. Then installed version 2.17.9 from the App Store and now video works fine. Seems issues are gone for me.

**Comment by User35123** [comment]
> Works with 2.17.9.
> 
> I uninstalled version 2.17.7 with the help of ForkLift app. So completely removed everything. Then installed version 2.17.9 from the App Store and now video works fine. Seems issues are gone for me.

Hmm 2.17.9 was my very first installed version. Never used rocket.Chat before. Didn't work for me.

**Comment by foxpalace** [comment]
Jupp - tested today - removed 2.17.9 from Mac OS X 10.14.6 and installed 2.17.3. Now I get the System-Question for using camera and microphone

**Comment by Tuxdiver** [comment]
After starting a video call with 2.17.3 and accepting the permissions, it also works with the current 2.17.9 - so permissions are saved.

**Comment by foxpalace** [comment]
ok, i give it a try - but thats only a workaround

**Comment by Tuxdiver** [comment]
Right! But maybe some developer can have a look and see, what changed between 2.17.3 and "now".
After using 2.17.3, Rocket.Chat is listed in "Systemeinstellungen -> Sicherheit -> Datenschutz -> (Kamera / Mikrofon)" (don't know the correct english names of the Mac preferences) - so all further versions will be OK ;-)

**Comment by Bruce-Ming** [comment]
Uncheck camera authorization again, restart

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
