### ISSUE TITLE
Server Login to Rocket.Chat Cloud does not work

### ISSUE THREAD

**Issue by rudiservo** [RocketChat/Rocket.Chat.Electron#1557]
Ubuntu Snap server latest

Login to Rocket.Chat Cloud does not work
I get 400 oauth_workspace_client_different_account

also cannot sync
rocketchat-server.rocketchat-server[19427]: Failed to sync with Rocket.Chat Cloud.  Error: internal_server_error

**Comment by rudiservo** [comment]
sorry it's for rockechat server, I am going to change it.

**Comment by thorin8k** [comment]
I'm having the same issue trying to connect my self-hosted instance to the cloud.

In DevTools, after login,  it says:
400: oauth_workspace_client_different_account

Have you been able to solve this problem? How?

**Comment by bjoernHeneka** [comment]
Sorry for reopening.... Did you solve the problem? I have the same issue

**Comment by WilfredLemus** [comment]
I have the same issue RocketChat 3.6.2 snap
