### ISSUE TITLE
Save hidden state at Windows logout

### ISSUE THREAD

**Issue by flauschi** [RocketChat/Rocket.Chat.Electron#156]
## My Setup

 - __My OS name and version__: Windows 10
 - __My current app version__: 1.2.0-rc.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

The app does not save the hidden state if I log out from windows and the app is still open. It only saves the hidden state if I close the app manually. (See comments in  #140)

#### Current Behavior

Hidden state is not saved at Windows user logout.

#### Expected Behavior

Hidden state is saved at Windows user logout.

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Electron/commit/0416f587f1d843df1a5fbc7841ae582cf6e24afd
