### ISSUE TITLE
Linux usability issue of tray icon

### ISSUE THREAD

**Issue by sirkon** [RocketChat/Rocket.Chat.Electron#1560]
Hi!

I am using the latest app build for Ubuntu (v2.17.7) and the issue I am reporting refers to all Ubuntu versions I have tried (18.04, 20.04).

It always bothered (annoyed and keep annoying in fact) me I need to do additional action to reveal a window: left click on tray icon shows a menu

* Hide/Show
* Quit

and then choose Hide/Show.

I would love to have a fast access to chat window: either open a window or move to the opened one with left click and show this damn useless menu on the right button click.

I suspect you are following pretty questionable and already outdated (after the Unity was abandoned) notifaction area indicators HIG, so it is possible builds for other Linux distributions provide already provide a behavior I wish.

See the screencast. Don't mind ugly cut icons, this is Linux at last (LOL). The behavior or Deluge I played with first is what I would love to have with Rocket.Chat.

https://youtu.be/YcFIbFWbshA

PS Thank you for the tremendous amount of work!

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
