### ISSUE TITLE
macOs unable to open after build

### ISSUE THREAD

**Issue by christiancuri** [RocketChat/Rocket.Chat.Electron#1561]
## My Setup

- Operating System: macOS Catalina (10.15.3)
- App Version: latest
- Installation type: dmg

- [ X ] I have tested with the latest version
- [ X ] I can simulate the issue easily

## Description
Rocket.chat not show after i build, i only cloned the repository and builded, when i try open the app, the icon in dock is show openned and shows Rocket.chat on bar, but the windows is not rendered (only in builded version, if i run in development mode [yarn start], the window is rendered)

![Screenshot at Mar 24 16-27-17](https://user-images.githubusercontent.com/52043761/77468492-64425680-6dec-11ea-84bf-479b0ae8bf44.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
