### ISSUE TITLE
Camera Permission for Jitsi Video Conference 

### ISSUE THREAD

**Issue by user1233445** [RocketChat/Rocket.Chat.Electron#1562]
Hey,

we want to use the integrated video chat solution in RocketChat (macOS) via Jitsi. Unfortunately the sub program has no access to the internal camera. I don't know if this is a bug or if the program was distributed wrong from our side. 

<img width="804" alt="Screenshot 2020-03-19 at 15 43 40" src="https://user-images.githubusercontent.com/62391194/77081960-b3a71200-69fb-11ea-80e8-a59cf16616d1.png">

<img width="602" alt="Screenshot 2020-03-19 at 15 46 01" src="https://user-images.githubusercontent.com/62391194/77081980-bc97e380-69fb-11ea-887b-e79fe47afd9d.png">

Information about the system:
macOS Version: 10.14.6
RocketChat Version: 2.17.9
RocketChat Server Version: 2.1.0

It seems that RocketChat does not get the Privacy Preference Policy Control for the Camera App. Do you have a tip for me on how to solve the problem?

**Comment by ramrami** [comment]
Also video messages are not working, so I don't think it's related to jitsi

**Comment by ramrami** [comment]
Trying to send a video message throws an error `NotReadableError: Could not start video source`. This error comes from the web app code in `app/ui/client/lib/recorderjs/videoRecorder.js` when calling `navigator.mediaDevices.getUserMedia`

**Comment by abhigyank** [comment]
@gabriellsh Would it better to open all Jitsi links in the browser instead?

**Comment by tobzsc** [comment]
I do not think that this is the way to go. jitsi works best with chrome and firefox and safari seem to have issues. This way some users would still have issues. This is something which has to be fixed for the desktop app itself.

**Comment by gabriellsh** [comment]
> @gabriellsh Would it better to open all Jitsi links in the browser instead?

That's an admin option already.

> I do not think that this is the way to go. jitsi works best with chrome and firefox and safari seem to have issues. This way some users would still have issues. This is something which has to be fixed for the desktop app itself.

You're right. Also because this is a shared feature, and makes way more sense for it to be used on the desktop app than in the web app (which works btw).

**Comment by autoize** [comment]
> > @gabriellsh Would it better to open all Jitsi links in the browser instead?
> 
> That's an admin option already.

Unless mistaken the "open in new window" option only applies to users using Rocket Chat from a browser window. The Electron app does pop up a separate window for Jitsi, but using a WebView in Electron rather than a standard browser window. 

Because the Electron app does not prompt for Camera or Microphone permission in Mac OS X Catalina, no audio or video is functioning. @abhigyank's suggestion was to open the Jitsi window in a standard Chrome window **not** within the Electron app.

**Comment by abhigyank** [comment]
> > @gabriellsh Would it better to open all Jitsi links in the browser instead?
> 
> That's an admin option already.
But we do open it in an Electron Browser Window than in a browser? It is simpler for us to directly open in the browser rather than in electron window, this also ensures that it works all the time.
However, if we want to continue open in the electron window, that is also possible, we just have to prompt for camera and microphone permissions in the new window.

**Comment by gabriellsh** [comment]
I actually assumed it opened in a new window. @tassoevan can we have your opinion here please?

**Comment by lightweight** [comment]
This is affecting me, too, in the desktop app, but for mike and video camera permissions for the BigBlueButton integration...

**Comment by sgrosse** [comment]
> 
> It seems that RocketChat does not get the Privacy Preference Policy Control for the Camera App. Do you have a tip for me on how to solve the problem?

FYI: For me it was solved by installing the Rocket Chat app via App Store instead of using the dmg.

**Comment by autoize** [comment]
Can confirm that installing RocketChat from the App Store makes camera and audio permissions work. Wondering if it can be resolved for the DMG if the developers sign the build with their key?

**Comment by tobzsc** [comment]
Currently the Desktop app does not really seem to be maintained. There is no development going on since several weeks.

**Comment by adolfombarros** [comment]
> Hey,
> 
> we want to use the integrated video chat solution in RocketChat (macOS) via Jitsi. Unfortunately the sub program has no access to the internal camera. I don't know if this is a bug or if the program was distributed wrong from our side.
> 
> <img alt="Screenshot 2020-03-19 at 15 43 40" width="804" src="https://user-images.githubusercontent.com/62391194/77081960-b3a71200-69fb-11ea-80e8-a59cf16616d1.png">
> 
> <img alt="Screenshot 2020-03-19 at 15 46 01" width="602" src="https://user-images.githubusercontent.com/62391194/77081980-bc97e380-69fb-11ea-887b-e79fe47afd9d.png">
> 
> Information about the system:
> macOS Version: 10.14.6
> RocketChat Version: 2.17.9
> RocketChat Server Version: 2.1.0
> 
> It seems that RocketChat does not get the Privacy Preference Policy Control for the Camera App. Do you have a tip for me on how to solve the problem?

Yes. Install the version 2.17.7 (deb package) from https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.7/rocketchat_2.17.7_amd64.deb

This solve for me !

**Comment by bluealpha-dev** [comment]
We've the same problem with the webcam problem. Our Workaround is to use Rocket.Chat 2.17.7

**Comment by ankar84** [comment]
> We've the same problem with the webcam problem. Our Workaround is to use Rocket.Chat 2.17.7:
> works under
> 
> * Ubuntu 18.04 LTS
> * Ubuntu 20.04 LTS
> * Windows 10

Today one user come to me with mic issue on Windows 10 1709 and desktop version 2.17.7
![image](https://user-images.githubusercontent.com/4023037/90389336-0f042b80-e092-11ea-8d2d-1d5377da6765.png)
I Chrome - all fine.
How can I fix that?

**Comment by ankar84** [comment]
> In Chrome - all fine.
> How can I fix that?

It appeared to be some issue with antivirus software. When I unloaded antivirus - microphone was accessible to Rocket.Chat Electron application.

**Comment by BenelliFurtado** [comment]
For me it worked under Ubuntu 20.04 (KDE Plasma 5) when installing it via Snap Store and then changing the permissions (Use camera) in snap store:

![rocket_chat_permissions](https://user-images.githubusercontent.com/55577810/113848586-f075b080-9798-11eb-896f-656b9d764065.png)
