### ISSUE TITLE
Adding additional dictionaries to snap client through dialog fails

### ISSUE THREAD

**Issue by alberto-miranda** [RocketChat/Rocket.Chat.Electron#1565]
## My Setup

- Operating System: Ubuntu 19.10
- App Version: 2.17.9
- Installation type: snap

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description

When trying to add additional languages using the "Browse for language..." dialog, the following error is returned: 

```
Error copying dictionary file: Error invoking remote method 'spell-checking/install-dictionaries': [object Object
```

Perusing through `dmesg` logs, I found this seemingly related message:

```
[lun mar 30 19:05:25 2020] audit: type=1400 audit(1585588096.824:281): apparmor="DENIED" operation="open" profile="snap.rocketchat-desktop.rocketchat-desktop" name="/run/mount/utab" pid=20716 comm="rocketchat-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
