### ISSUE TITLE
Russian spell checker not work

### ISSUE THREAD

**Issue by wowansm** [RocketChat/Rocket.Chat.Electron#1567]
## My Setup

- Operating System: Windows 10
- App Version: 2.17.7
- Installation type: exe

## Description
I'm copiyng file *.aff and dic to c:\Program Files\Rocket.Chat\resources\dictionaries\
If i'm try to add dictionary from programm i get error: 
`Error ccpiyng dictionary file: Error invoking remote method 
"spell-checking/install-dictionaries": [object Object] `

### Current Behavior
Input incorrect word not have red lines 

### Expected Behavior
Input incorrect word must be with red lines

I`m use this dictionary 
[dictionaries.zip](https://github.com/RocketChat/Rocket.Chat.Electron/files/4414283/dictionaries.zip)

**Comment by wowansm** [comment]
I`m Creating folder in c:\Users\wowansm\AppData\Roaming\Rocket.Chat\ and copying dic and aff filles to there.
Nothing change, spell checker for russian langusge doesnt work.
No red lines under incorrect word

**Comment by gabriellsh** [comment]
Related #1565

**Comment by ankar84** [comment]
Fixed in 3.0
![image](https://user-images.githubusercontent.com/4023037/94756075-2deb2280-039f-11eb-9e5d-56e54adfd29f.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
