### ISSUE TITLE
Icons are huge and basic and text is ultra tiny. Tried completely uninstalling or changing the setting and no effect. It was fine last night. I left it up and this morning it had changed.

### ISSUE THREAD

**Issue by Norlion** [RocketChat/Rocket.Chat.Electron#1568]
## My Setup

- Operating System:
- App Version:
- Installation type: 

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by Norlion** [comment]
![rocketerror](https://user-images.githubusercontent.com/63051782/78248003-d7695e00-74b9-11ea-95dc-c35387049b1a.png)

**Comment by gabriellsh** [comment]
That is most probably an issue with the server. Sometimes when reloading on develop this happens to me. There is a small chance it's related to Electron, but I doubt it. Maybe try restarting the server, or open it through the web app to see if there's any difference.

**Comment by gabriellsh** [comment]
Please provide more info too. Server version, app version, OS, etc.

**Comment by Norlion** [comment]
Reloading it fixed the problem. Windows 10 PC.
