### ISSUE TITLE
The main window opens each time when a message comes on Linux Mint 19.3

### ISSUE THREAD

**Issue by Aeliot-Tm** [RocketChat/Rocket.Chat.Electron#1570]
## My Setup

- Operating System: Linux Mint 19.3 Tricia
- App Version: 2.17.9
- Installation type: from Linux Mint default repository (UI)

- [    ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description

The main window opens each time when a message comes. It's very noisy.

### Steps to reproduce:
1. Launch application.
1. Minimize to tray.
1. Wait until a message comes.

### Current Behavior

The main window of application opens the main window each time when a message comes.

### Expected Behavior

The application opens only on demand.

**Comment by gabriellsh** [comment]
This is weird, I don't think this happens in other linux distros (never heard of it anyway). Doesn't happen in catalina too. Needs more investigation.

**Comment by honysch** [comment]
Same problem on **macOS Mojave 10.14.5** with **app version 2.17.9**.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
