### ISSUE TITLE
Dropbox Oauth Login issue for Recording Jitsi Video Conferences

### ISSUE THREAD

**Issue by jimDKE** [RocketChat/Rocket.Chat.Electron#1571]
Really enjoying the Jitsi integration into RocketChat so far!  Looks like we may have found a bug regarding Dropbox oauth and Jitsi video conference recordings.  It occurs in the electron app but not in Firefox or Chrome (details below).

## My Setup

- Operating System: Windows 10 Enterprise 2016 LTSB x64 Build 14393
- Desktop App: RocketChat Electron 2.17.7 (also tested with 2.16.2 and 2.17.9)
- Installation type: exe

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description

When Jitsi video chat is accessed via electron desktop app, the oauth to dropbox fails consistently.  When accessing the Jitsi video chat room via web browser (Firefox and Chrome), oauth login to Dropbox works and video session is successfully recorded and saved to Dropbox.  

RocketChat Electron 2.17.7 (exe install)
Firefox x64 v74.0
Chrome v80.0.3987.149

### Current Behavior

While in Jitsi video conference session (Electron client), clicking "Start Recording" brings up an oauth window for Jitsi to access a Dropbox account.  

![dropbox_oauth_prompt](https://user-images.githubusercontent.com/45210650/78510233-af435e80-7748-11ea-975c-24bf08bccbd8.png)

After typing in the correct username and password, the oauth window turns completely white (though I can still see the Electron menu buttons at the top of that window "File", "Edit", "View").  This oauth window does not disappear on its own.  If I close the oauth window, the Jitsi video conference window continues asking me to "Sign In" to Dropbox.

![dropbox_oauth_blank_oauth_window](https://user-images.githubusercontent.com/45210650/78510269-e74aa180-7748-11ea-90f2-3cadda8ad7d0.png)

The following doesn't seem to fix the problem: reloading the Jitsi window, reloading the Electron client, completely closing and reopening the electron client.

### Expected Behavior

Oauth into Dropbox should succeed if credentials were correct, the oauth window should disappear and Jitsi should present the user with a button to start recording to Dropbox.  (This is what happens when the user accesses the Jitsi video conference in the Firefox or Chrome.)

Has anyone else run into this issue too?

**Comment by jimDKE** [comment]
This is a shot in the dark, but I come across a few GitHub posts from April/May 2019 regarding Dropbox support for OAuth on Electron browser.  Not sure if this ever got resolved or whether it's related to what's causing the issue now.

**How to authenticate user dropbox access in an Electron desktop app?**
https://github.com/dropbox/dropbox-sdk-js/issues/242

https://github.com/dropbox/dropbox-sdk-js/issues/245

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
