### ISSUE TITLE
Add spell check dictionary error

### ISSUE THREAD

**Issue by LePixaliz** [RocketChat/Rocket.Chat.Electron#1574]
## My setup

- Operating System: Windows (Rasberry pi 4 server)
- App Version: 1.0.3

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Hi ! I'm trying to add a french dictionary, so I click on "Rechercher un langage..."
![chrome_1CrhGJk9sT](https://user-images.githubusercontent.com/22474454/78658868-0a04c380-78cb-11ea-8dcf-a91cbbb097f2.png)
and select either my .aff or my .dic file and I got this error :
Error copiyng dictionary file: Error invoking remote method "spell-checking/install-dictionaries": [object Object]
![Rocket Chat_aOP2c1iimJ](https://user-images.githubusercontent.com/22474454/78658688-c5792800-78ca-11ea-83d4-b670808632c4.png)

Is my file corrupted in some way or is it Rocket Chat's fault ?

(Meanwhile, is there some setting to disable spell check completely ? I found this page : https://github.com/RocketChat/Rocket.Chat.Electron/issues/281 but I don't think there is a "Disable spell check" button)

Thanks

**Comment by JakubJachym** [comment]
Was just about to report it too.

@LePixaliz to disable spellcheck for given language, uncheck it. Open the Languages menu, and click `en_US` and it will untick it. Done. (Thanks for referencing https://github.com/RocketChat/Rocket.Chat.Electron/issues/281 - it's written there. :smirk: It was annoying to have everything in my language underlined in red...)

**Comment by JakubJachym** [comment]
And fix is described in ticket https://github.com/RocketChat/Rocket.Chat.Electron/issues/1534.

Create `dictionaries` folder in RocketChat's folder. Just did and it works.

**Comment by LePixaliz** [comment]
> Was just about to report it too.
> 
> @LePixaliz to disable spellcheck for given language, uncheck it. Open the Languages menu, and click `en_US` and it will untick it. Done.

Oh ! I didn't understand that you can click AGAIN on a language to have it disabled. Thanks for explaining it to me haha !

And thanks for the fix. I'll close the issue then :)

**Comment by mastenm** [comment]
I wanted to report this issue, too. It is annoying.
Everything that should be done to my opinion is, that a client creates missing 'dictionaries' folder. And users will be able to load new languages with easy.
It rally is a pity that a functionality exists, but there is another 0.1% needed to be done for better user experience. Namely, many users thinks a feature is broken otherwise.
