### ISSUE TITLE
remove electron-hunspell & fix spellcheck mess

### ISSUE THREAD

**Issue by Raboo** [RocketChat/Rocket.Chat.Electron#1575]
This is a wish or a feature request to improve the spellchecking situation.

Today Rocket.Chat.Electron depends on electron-hunspell.
electron-hunspell has been archived and deprecated as it says on the [README](https://github.com/kwonoj/electron-hunspell#deprecated-electron-provides-built-in-spellchecker-now-httpsgithubcomelectronelectronpull20897).

Electron provides built in spellchecker now, https://github.com/electron/electron/pull/20897.
It says: 
>  We will use the OS spellchecker on macOS and hunspell on all other platforms.

For me that is nice, as it uses native spellchecker for MacOS and I use MacOS, then I don't have to worry about adding dictionaries.

The user experience today is poor when it comes to spellchecking.
- Quite hidden way of changing language. It actually required me to Google how to do it.
- 5 languages bundled, what about the rest of the world? They need to find their way to this git repo to figure how to add new dictionaries and what type of dictionaries to download. And then having to download dictionaries from arbitrary sources. This would discourage most users.

Would be better to switch to the built-in spellchecker on electron. That solves the problem for MacOS.
For other platforms I would suggest using a download function instead of bundling all the worlds languages. Have a list of all languages with proper names, and then auto-download the dictionary if it doesn't exist locally.

**Comment by abhigyank** [comment]
Yes, it would be good to move to the in-built spellchecker. Though as of now it removes the suggestions for correct spellings, so we would have to build our own suggestion menu.

**Comment by Raboo** [comment]
Well since the electron-hunspell is archived eventually it will be forced to that anyway.
However I must stress that it should be easy to spellcheck any language. As not every Rocket.Chat user is a techie.

**Comment by KarlisVe** [comment]
This is very actual feature for many users, a specially outside IT community. Currently it is one of showstoppers to use it in company (500+ employees)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
