### ISSUE TITLE
Cursor doesn't show blinking in Username/Password textbox when app is launched or tab is pressed to move to another textbox.

### ISSUE THREAD

**Issue by vbmade2000** [RocketChat/Rocket.Chat.Electron#1578]
## My Setup

- Operating System: Windows 10
- App Version: 2.17.7
- Installation type: exe

- [X ] I have tested with the latest version
- [ X] I can simulate the issue easily

## Description
IMHO cursor should be shown as blinking in Username text box when app is loaded. Cursor does not blink in Username and Password TextBox and so user is not able to know where the text will be entered (either in Username box or Password Box). There is no feedback. Even after you press tab you can not know where the cursor is.

### Current Behavior
Cursor does not blink in Username and Password TextBox

### Expected Behavior
Cursor does not blink in Username and Password TextBox so that user can know that current focus is on i.e Username box and so what she is going to enter will be entered in Username box.

**Comment by rcadmin19** [comment]
This is the same bug described here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1536. Minimize/maximize brings cursor back. Hoping soon fix for this.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
