### ISSUE TITLE
Cannot download attachments on Mac client

### ISSUE THREAD

**Issue by axeloz** [RocketChat/Rocket.Chat.Electron#158]
## My Setup

Server
- hosted on DigitalOcean
- Docker
- latest tag of the Docker image
- just pulled new image

Client
- MacOs 10.10.5
- Rocket 1.2.0 from AppStore

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Attachments can't be downloaded on Mac client. 
The download link appears but nothing is happening when clicking the link. 
Same problem when trying from the "files" right panel. 
However, the files can be download from a browser (Chrome) so it seems to be a client related issue. 

#### Current Behavior

Clicking the file link doesn't do anything...

#### Expected Behavior

The file should be downloaded

**Comment by axeloz** [comment]
Hello @gwelchc ,

It does fix the download from the main window. 
Still broken in the "Files list" right panel. 
Thanks a lot,

Axel

**Comment by gwelchc** [comment]
Didn't thought of that. Let me check on it.

**Comment by gwelchc** [comment]
Check it out now. #160

**Comment by axeloz** [comment]
Yep, that's good for me. 
When do you plan on releasing the version app?
Thanks a lot

**Comment by gwelchc** [comment]
I'm not a member of Rocket.Chat, I just happened to have the same issue, and figure out how to solve it.

I'm making a slim version to work with a single server that is preconfigured (and thus it needs and allows no configuration).

**Comment by axeloz** [comment]
All right, well done then ...
