### ISSUE TITLE
windows build success,but this app can not opened

### ISSUE THREAD

**Issue by Bruce-Ming** [RocketChat/Rocket.Chat.Electron#1580]
## My Setup

- Operating System:Microsoft Windows 10 Professional Edition OS version: 10.0.18363
- App Version:latest version
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

Description

Rocket.chat not show after i build, i only cloned the repository and builded, when i try open the app, the icon in dock is show openned , but the windows is not rendered (only in builded version, if i run in development mode [yarn start], the window is rendered)
There is a process in the task manager, but the window does not open.

![20200416101534](https://user-images.githubusercontent.com/37186519/79407133-520e9f00-7fcb-11ea-813b-ffe552630307.png)

**Comment by Bruce-Ming** [comment]
sorry, I switched to the latest 3.0 branch, there should be a bug in the 3.0 branch

**Comment by ketanvault** [comment]
I'm experiencing the same in 2.17.9 version

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
