### ISSUE TITLE
Cannot share a single screen on Linux

### ISSUE THREAD

**Issue by mhoeher** [RocketChat/Rocket.Chat.Electron#1582]
## My Setup

- Operating System: Fedora 31
- App Version: 2.17.9
- Installation type: Flatpak

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

* We use a combination of Rocket.Chat and Jitsi for team internal communication.
* We want - in a video/audio call - to have the possibility to share the content of a single screen/monitor (besides the possibility to share e.g. single application windows).

### Current Behavior

* Currently, we can only select either application windows or sharing the entire screen (i.e. the "virtual" area which consists of all attached screens).

### Expected Behavior

* It should be possible to select individual screens to share.

I did some quick research on the topic and it seems that this is actually not an issue of the Rocket.Chat desktop client per se. Instead, it seems to be an issue with Chrome/Chromium on Linux. There is an [issue over in the Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=396091) which has more details. It seems that the most recent developer/beta builds of Chrome include the changes and hence when starting a Jitsi call from a current Chrome Beta, I am able to share individual screens.

I am not sure if there is much that can be done in the Rocket.Chat desktop app for the time being, but maybe it would be possible to pull in the fix (via a more recent Electron version?) to have this available in the app as well?

Thanks for considering and in general for your great work on Rocket.Chat :-)

**Comment by tassoevan** [comment]
Is it still a problem at the current version?

**Comment by mhoeher** [comment]
I just gave it a try with the latest version from Flathub: Works for me now :+1:

Thanks a lot!
