### ISSUE TITLE
Taskbar icon always show notification even if desktop notification are disabled

### ISSUE THREAD

**Issue by xi67** [RocketChat/Rocket.Chat.Electron#1583]
With this notification configuration : 
![image](https://user-images.githubusercontent.com/12096081/79839418-c7f07d00-83b4-11ea-9458-02bd0b99bf60.png)

I receive no sound or alert but the RocketChat icon in taskbar show i've received message :
![image](https://user-images.githubusercontent.com/12096081/79839562-f66e5800-83b4-11ea-890e-d227e0d456a0.png)

The only way to hide notification is to "Hide counter" but in this case, the channel not showing anything in thr channels list.

The taskbar icon should reflect desktop notification and not the fact there is unread message counter on a channel.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
