### ISSUE TITLE
Not able to close File Upload

### ISSUE THREAD

**Issue by sevspo** [RocketChat/Rocket.Chat.Electron#1584]
## My Setup

- Operating System: Win 10
- App Version: 2.17.1
- Installation type: install executable from official dl page

- [ x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
If I open the File Upload window accidentally, I' m am not able to close it anymore.

![image](https://user-images.githubusercontent.com/17132540/79859396-3c391980-83d1-11ea-8b02-d830246d8ab0.png)

**Comment by ankar84** [comment]
Just ctrl+r

**Comment by gabriellsh** [comment]
This has duplicates in the main repo and is not related to Electron. Thanks for the notice anyway!
