### ISSUE TITLE
View menu checkmark does not respond to manual fullscreen.

### ISSUE THREAD

**Issue by TaimurAzhar** [RocketChat/Rocket.Chat.Electron#1585]
## My Setup

- Operating System: macOS 10.15.4
- App Version: 2.17.7
- Installation type: dmg 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

The "Full screen" option in the View menu on the top does not work properly. This is a minor UI issue for the checkmark that shows if you click the "Full screen" option or use the "cmd+ctrl+F" shortcut the checkmark appears and disappears as expected but doing it manually using the window buttons does not make the checkmark appear or disappear. 

The menu and checkmark are: 
<img width="220" alt="Screenshot 2020-04-27 at 1 16 41 AM" src="https://user-images.githubusercontent.com/30270349/80318667-1672a100-8825-11ea-8f7c-c051ba1cf697.png">

### Current Behavior

When I use the window buttons to exit fullscreen.
<img width="292" alt="Screenshot 2020-04-27 at 1 16 56 AM" src="https://user-images.githubusercontent.com/30270349/80318680-29857100-8825-11ea-889f-2668fa5ee906.png">

The checkmark is still there when the app is not in fullscreen mode.
<img width="914" alt="Screenshot 2020-04-27 at 1 17 48 AM" src="https://user-images.githubusercontent.com/30270349/80318694-415cf500-8825-11ea-8170-993bf442331e.png">

### Expected Behavior

The checkmark should not be shown anymore. Vice versa for when going into fullscreen using the window fullscreen button.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
