### ISSUE TITLE
Desktop Taskbar Notifications not flashing for channel or group messages

### ISSUE THREAD

**Issue by devadminn** [RocketChat/Rocket.Chat.Electron#1587]
## My Setup
Windows 10 (Ver 1909)
Rocket Chat Version
![image](https://user-images.githubusercontent.com/64443606/80427093-e1556580-889b-11ea-9f1f-4a51bf7cb87c.png)
![image](https://user-images.githubusercontent.com/64443606/80427112-eca89100-889b-11ea-8c57-9d575cd2bda6.png)
Rocket Chat Hosted on Ubuntu Server
Version 18.04.04 LTS

- [X ] I have tested with the latest version
- [X ] I can simulate the issue easily

## Description
We've have a fresh setup and noticed that the rocket chat doesn't flash if someone receives a message through Channel/Private Group chat unless they are specified using @.

### Current Behavior
Receiving a direct message the taskbar will flash to indicate a new message, this does not work if the message is in a Channel or Private Group
![image](https://user-images.githubusercontent.com/64443606/80427032-caaf0e80-889b-11ea-8d11-c78afaccd90e.png)

Channel\Private Group Behavior
![image](https://user-images.githubusercontent.com/64443606/80427071-da2e5780-889b-11ea-8581-2b64b1995515.png)

### Expected Behavior
Notification flash for any message including channels/private groups user is part of unless settings have been changed.

**Comment by CitizenDev** [comment]
#1395 Probably related to this

**Comment by devadminn** [comment]
I took a look and enabled "Require Interaction to dismiss Desktop notifications
![image](https://user-images.githubusercontent.com/64443606/80611823-fba05800-89ef-11ea-88f8-646c40cb29e5.png)
I get the system tray icon showing an unread message indicator now but the taskbar icon isn't flashing still.
![image](https://user-images.githubusercontent.com/64443606/80611940-27234280-89f0-11ea-88ca-a2aa7d8e6963.png)

**Comment by mano87** [comment]
There seem to be many open questions on this subject. However, it has not been solved until today.

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1104

What's so difficult about adding a function to the Windows Desktop Client that displays a badget in the Windows taskbar when new unread messages are received. With WhatsApp, Jabber and Telegram this is also possible.

**Comment by rodrigok** [comment]
@devadminn the flash happens only on messages that affects the sidebar counts, mainly mentions but it depends on how you configure your rocket.chat or on the user's preferences.

It's not intended to blink on every message or it would be annoying for users with many rooms or busy teams, you can always reconfigure your settings and check how it will affect you.

Since we don't have plans to remove this relation of Unread Counts and Blink I'll move forward and close this issue. Let us know if you find any other bug related to this behavior.

Thanks
