### ISSUE TITLE
Loading Animation for 30 minutes now

### ISSUE THREAD

**Issue by georgwall** [RocketChat/Rocket.Chat.Electron#1589]
## My Setup

- Operating System: Windows
- App Version: 2.17.7
- Installation type: rocketchat-setup, exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
Loading Animation after paste channel name.

### Expected Behavior
Loading Anoimation would end and show me the chat after that.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
