### ISSUE TITLE
Show on unread messages doesn't keep sizing

### ISSUE THREAD

**Issue by kjordan2001** [RocketChat/Rocket.Chat.Electron#1590]
- Operating System: Windows 10
- App Version: 2.17,9
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
1. Maximize window 
2. Check that you want to show on unread messages.
3.  Minimize or put window to background.
4.  Wait for message.
5. Return to window.

### Current Behavior
Window is not maximized, but some random window size instead.

### Expected Behavior
Should stay maximized.

**Comment by alicjamusial** [comment]
I have the same issue on Windows 7.
