### ISSUE TITLE
Embedded doesn't display (403) from Lightshot screenshots

### ISSUE THREAD

**Issue by artemChernitsov** [RocketChat/Rocket.Chat.Electron#1591]
## My Setup

- Operating System: macOS Catalina 
- App Version: 2.17.9 and in the browser (Google Chrome) 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When I paste the link from Lightshot App (https://app.prntscr.com/), the embedded image doesn't display.
### Current Behavior
When I paste the link from prntscr.com/ embed should display correctly (like this https://prnt.sc/sbqmug)
### Expected Behavior
When I paste the link from prntscr.com/ embed doesn't display https://prnt.sc/sbqnch

**Comment by artemChernitsov** [comment]
up

**Comment by artemChernitsov** [comment]
up

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
