### ISSUE TITLE
Rocket.chat-Client 2.17.7 freezes and crashes under Ubuntu 18.04

### ISSUE THREAD

**Issue by pixxelspotter** [RocketChat/Rocket.Chat.Electron#1592]
## My Setup

- Operating System: Ubuntu 18.04.4
- App Version: 2.17.7, 2.17.9 and 2.19.11
- Installation type: .deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The client freezes(white screen) and sometimes crashes when working, the freezing sometimes stops after some minutes, sometimes the client crashes completely. We also use Version 2.17.7 under Ubuntu 16.04.6 with no issues.

### Current Behavior
The client freezes(white screen) and sometimes crashes when working, the freezing sometimes stops after some minutes, sometimes the client crashes completely.
Strace shows me this: (rocketchat-desktop:8912): libnotify-WARNING **: 11:09:28.919: Failed to connect to proxy
) = 111
### Expected Behavior
No freezes and crashes.

**Comment by borzaka** [comment]
Try to update to 2.17.9
See https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by pixxelspotter** [comment]
Doesn't fix the Problem. Freezes still occur.
Let me know if you need additional Information.

**Comment by pixxelspotter** [comment]
I'm still waiting on a fix as i can get our environment to production without a fix.

**Comment by pixxelspotter** [comment]
Hey there

The Problem is still persitent in 2.17.11. 
Could you please fix that?

> Try to update to 2.17.9
> See https://github.com/RocketChat/Rocket.Chat.Electron/releases
