### ISSUE TITLE
Acento com problemas

### ISSUE THREAD

**Issue by rafa9000** [RocketChat/Rocket.Chat.Electron#1593]
Bom Dia!!!!

Não estou conseguindo utilizar "acentos" nas palavras nas conversasões, estou utilizando o rocket.chat desktop v2.17.9.
Ubuntu 20.04.

aguardo retorno,

Rafael Rodrigues

## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
