### ISSUE TITLE
unwanted behaviour of Alt+Shift shortcut

### ISSUE THREAD

**Issue by petrsmetana** [RocketChat/Rocket.Chat.Electron#1597]
## My Setup

- Operating System: Debian 10
- App Version: 2.17.7
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
If I want to switch the keyboard layout with Alt+Shift it shifts the focus from the text input to the menu. So I have to pres Alt once again to get the focus back.

### Expected Behavior
The focus should stay in the text input field.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
