### ISSUE TITLE
add keyboard shortcut to open search (macOS: cmd F)

### ISSUE THREAD

**Issue by foss-** [RocketChat/Rocket.Chat.Electron#1598]
- Operating System: macOS 10.15.4
- App Version: 3.2.1

## Description
Opening a search query is not possible via keyboard shortcut.

### Current Behavior
No support for keyboard shortcut.
Users have to click the magnifying glass icon to open search.

### Expected Behavior
Keyboard shortcut to open search.
macOS should probably be ⌘F.
Add the keyboard shortcut to the tooltip info when hovering magnifying glass icon with mouse.

**Comment by x-f** [comment]
Search opens on ⌘K.
⌘F would be more obvious, I agree.

**Comment by jrozelle** [comment]
Hello,
⌘K is not working anymore when window is "condensed" (small window, without contact list on the left), am I the only one ?

**Comment by ggazzo** [comment]
⌘K or ⌘P
