### ISSUE TITLE
Verification code is not sent to email

### ISSUE THREAD

**Issue by atoshiobr** [RocketChat/Rocket.Chat.Electron#1599]
## My Setup

- Operating System: win10
- App Version: 2.17.7
- Installation type: rocketchat-setup-2.17.7.exe

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
email and password completed and sent but a window open asking for a verification code.
check my email, but the email does not reach any of the folders

### Current Behavior
verification code does not reach any of the folders

### Expected Behavior
recieve a verification code in my email

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
