### ISSUE TITLE
White Screen on Windows 7

### ISSUE THREAD

**Issue by angeltonio** [RocketChat/Rocket.Chat.Electron#1600]
When I execute the PC version on Windows 7 I have a white screen with nothing more..can fix it??...

**Comment by 564064202** [comment]
me too

**Comment by RohitGalgali** [comment]
Installed Rocket.Chat v2.17.11 on windows 7. It shows white screen on the page where we enter the server address.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
