### ISSUE TITLE
Window resize bug

### ISSUE THREAD

**Issue by kotla85** [RocketChat/Rocket.Chat.Electron#1602]
## My Setup

- Operating System: Windows 10
- App Version: 2.17.7
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
 it occurs every time I receive a new message

### Current Behavior
when I receive a new message, the Rocket.Chat window is resized from maximized to a small one in the centre of the screen.

### Expected Behavior
the Rocket.Chat window should remain maximized sized

**Comment by txwheeler** [comment]
Having the same issue.

**Comment by kotla85** [comment]
It turned out that version 2.17.9 is already available on GitHub. I updated the program and it solved the problem.
