### ISSUE TITLE
unable to connect to RocketChat

### ISSUE THREAD

**Issue by jaram55** [RocketChat/Rocket.Chat.Electron#1603]
Hi, I'm unable to connect to rocket chat.  I tried resetting my password but it tells me there is no such email for user.  If I then try to register a new account with my email it tells me that the email already exists.

my info is below:

email:
Jaramillo@kcse.com
windows 10
Version: 2.17.7
https://rchat.kcse.com

Thank you

## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
