### ISSUE TITLE
Chat window stuck in a drag operation

### ISSUE THREAD

**Issue by raffaeler** [RocketChat/Rocket.Chat.Electron#1605]
## My Setup

- Operating System: Windows 10
- App Version: 2.17.9
- Installation type: installer/exe 

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When you start dragging a file over a chat but you do **not** drop the file, a box with dashed strokes appear (showing: "drop to upload file") and you cannot dismiss it anymore (you can only start a new drag and drop operation or close the app).

**Important Note:** In order to repro the problem you should move the mouse over the chat window very quickly, otherwise the box will correctly go away.

### Current Behavior
After the box with dashed strokes appear during a drag operation, if you don't drop the box won't go away.

### Expected Behavior
if the drag&drop operation is aborted, the box should go away (or at least pressing esc it should go away).

**Comment by apaarfus** [comment]
As a work-around while this issue is tackled; reloading the session (`Window > Reload`, or `Ctrl+Shift+R`) appears to abort the drag operation.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
