### ISSUE TITLE
Invite link to private group doesn't work in desktop app

### ISSUE THREAD

**Issue by xbiafra** [RocketChat/Rocket.Chat.Electron#1606]
## My Setup

- Server: 3.2.0
- Invite link: https://go.rocket.chat/invite?host=rocketchat.COMPANY.DOMAIN&path=invite%2XYZcanG

- Operating System: MacOS Catalina, Windows 10
- App Version: 2.17.9
- Installation type: dmg or exe
- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description
Invite user option through Invite link (Members --> Invite Users --> Invite link) doesn't work in dekstop app, but works used in web browser version.

### Current Behavior
User (tested few times, different computers) opens link and it opens application but he isnt' added to the private group he was invited to.

### Expected Behavior
When the same user opens link via webbrowser he is joining the group he was invited to.

**Comment by DavidGay** [comment]
I have the same problem on macOS 10.15.4. 

I open the Rocket.Chat app, enter the URL and get a message saying that I need to login to The Hive**but** clicking on the link does nothing and using right-click to open the link takes me to the correct place but doesn't register that the login has taken place.

This works on the iOS app.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
