### ISSUE TITLE
File upload when connect to server by ssh tunnel

### ISSUE THREAD

**Issue by gena-moscow** [RocketChat/Rocket.Chat.Electron#1608]
## My Setup

- Operating System: windows 10
- App Version: 2.17.7 and web version through chrome
- Installation type: 

- [+ ] I have tested with the latest version
- [ +] I can simulate the issue easily

## Description

Can't send a file

### Current Behavior

I have shh tunnel to my corporate rocket chat server. So connect is like this:
http://212.237.30.231:63000/ 
I am trying to send file. Request goes to corporate Site_Url 
POST http://rchat.my_company.local:3000/ufs/GridFS:Uploads/G7w6ktR3E3wFdfXD3?token=fb3918d8ab&progress=0.041473966125206624

### Expected Behavior

expected url is http://212.237.30.231:63000/

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
