### ISSUE TITLE
Add possibility to hide systemtray icon

### ISSUE THREAD

**Issue by messmaker** [RocketChat/Rocket.Chat.Electron#161]
## My Setup
 - Archlinux 64bits 
 - rocket.chat v1.2.0

## Description
Currently, there is no way to hide the rocket.chat icon in the system tray while keeping the application running. Do you mind to had this feature please ?

Btw thank you all for the great work you made with this ! - Messmaker

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat.Electron/issues/74

@messmaker thanks
