### ISSUE TITLE
ban users from my private chatroom

### ISSUE THREAD

**Issue by debbiekatz** [RocketChat/Rocket.Chat.Electron#1610]
## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by debbiekatz** [comment]
i don't have option to ban a user. it only says i can remove a user but they can re enter the room

**Comment by ggazzo** [comment]
this is not the right place to open this kind of issue, please check https://github.com/RocketChat/Rocket.Chat
I'm not moving because I'm 99% sure we already have some request like that there
