### ISSUE TITLE
Bibgluebutton Screensharing doesn't work in the desktop app

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.Electron#1615]
Hi all!

Bibgluebutton Screenshare doesn't work in the desktop app.
In browser (all) screenshare works fine in Bigbluebutton. 

In desktop top i try to click on screenshare button and nothing happens. No message, no events, no errors.

How fix this? Thank you advanced

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.1
- Operating System: Centos 7
- Deployment Method: docker

### Client Setup Information

- Desktop App or Browser Version:  Desktop (2.17.7)
- Operating System: Windows,Linux

**Comment by arpsyapathy** [comment]
hi!
the problem still persists
last version on Win and Mac.
@gabriellsh

**Comment by Cormoran96** [comment]
I have the same problem

**Comment by salmoooon** [comment]
Still an issue on the windows app version now.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by Cormoran96** [comment]
Already have a problem. But not the same error message. 

The error message was "Code 1136. Permission to capture the screen needs to be granted."

**Comment by jeanfbrito** [comment]
> Already have a problem. But not the same error message.
> 
> The error message was "Code 1136. Permission to capture the screen needs to be granted."

In what version? 3.7.5? In what OS?

**Comment by Cormoran96** [comment]
BBB version: 2.4.0
Rocketchat client: 3.7.5
Rocketchat server: 4.3.0
Os: LinuxMint 20.3

**Comment by jeanfbrito** [comment]
And are you granting permission to capture the screen?

**Comment by Cormoran96** [comment]
Rocketchat client did not ask me
