### ISSUE TITLE
Desktop Notifications not working

### ISSUE THREAD

**Issue by estebanGramajo** [RocketChat/Rocket.Chat.Electron#1619]
## My Setup

- Operating System: macOS Mojave 10.14.6 
- App Version: 2.17.9
- Installation type: AppStore

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
I'm not getting desktop notifications either here or in PC with the other users. I tried changing a bunch of setting but nothing works. 

<img width="888" alt="Screen Shot 2020-06-01 at 4 42 32 PM" src="https://user-images.githubusercontent.com/14099858/83461938-2cc4db80-a427-11ea-917e-a144fe8efe43.png">
<img width="896" alt="Screen Shot 2020-06-01 at 4 38 00 PM" src="https://user-images.githubusercontent.com/14099858/83461945-2f273580-a427-11ea-98e0-2b25dce23292.png">
<img width="903" alt="Screen Shot 2020-06-01 at 4 37 24 PM" src="https://user-images.githubusercontent.com/14099858/83461947-2fbfcc00-a427-11ea-834c-41e2d9f50e8e.png">
<img width="777" alt="Screen Shot 2020-06-01 at 4 37 11 PM" src="https://user-images.githubusercontent.com/14099858/83461949-2fbfcc00-a427-11ea-9621-7d065b8cbbf0.png">

The sound does work, it sounds for every message, but no pop up notification.

### Current Behavior
Push notification does work on my phone, but desktop notifications doesnt.

### Expected Behavior
It should notify as Slack or any other app does.

**Comment by estebanGramajo** [comment]
Little Update, they started working a few times, but now instead of showing a notification, the bell rings and the entire screen of the app shows up, but if I type or something, it still interacts with the program if was using before the app popping up.

**Comment by klou** [comment]
Do you have the same debug console errors as mine?  #1618

**Comment by estebanGramajo** [comment]
> Do you have the same debug console errors as mine? #1618

Excuse me being too new on this, how do I see the debug console?

**Comment by klou** [comment]
View > Open Dev Tools

**Comment by estebanGramajo** [comment]
Seems to be the same of the one you redirected your post.

<img width="924" alt="Screen Shot 2020-06-03 at 2 24 08 PM" src="https://user-images.githubusercontent.com/14099858/83685583-1f822b00-a5a6-11ea-968b-1272dfe48fa5.png">

**Comment by klou** [comment]
See #1579

**Comment by klou** [comment]
And #1509

**Comment by frdmn** [comment]
Can you guys please try version 2.17.11 which was just released?

The PR #1662 should fix this problem. 😊

**Comment by lucasmello** [comment]
I have tested with 2.17.11 and it's working now! Thanks!

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
