### ISSUE TITLE
OS X client - every word typed is highlighted as being misspelled

### ISSUE THREAD

**Issue by BrianZachary** [RocketChat/Rocket.Chat.Electron#162]
## My Setup

 - __OS X El Capitan 10.11.4__: 
 - __1.2.0 (13)__: 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

Every word I type into the message entry text area is highlighted as being misspelled
<img width="168" alt="screen shot 2016-04-01 at 1 46 09 pm" src="https://cloud.githubusercontent.com/assets/8387848/14215544/a0e6fdc0-f811-11e5-8f0c-423a215be185.png">
#### Expected Behavior

Only words that are actually misspelled should be highlighted as being misspelled

**Comment by k2patel** [comment]
selecting spelling languages on message windows, issue disappear.
it might require to set some default language ?

**Comment by BrianZachary** [comment]
k2patel's suggestion was correct. Right-click within text entry box, Spelling Suggestions -> en, now all of the ugly red underlines go away. Raises another issue though, that a spelling suggestion language should be selected by default to prevent the appearance of all the correction marks to begin with.

**Comment by rodrigok** [comment]
I will force some default language to prevent this.

**Comment by BrianZachary** [comment]
Would it make sense for the spelling suggestion language to be set by the Localization Language chosen in the Account Preferences pane? The two seem to be independent right now, but I think the user expectation would be to choose their language in a single place, and then not have to worry about choosing a spellcheck dictionary. Or at the least, put the localization and spellcheck language choices next to each other in the preferences pane.

**Comment by rodrigok** [comment]
@BrianZachary we are doing that as you can see here https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/app/scripts/preload.js#L125-L131

I will try to improve and force `en` if I can't get information from these options.

**Comment by BrianZachary** [comment]
Ah, nice! Thanks for pointing that out.
