### ISSUE TITLE
User names / login names shown in front of messages

### ISSUE THREAD

**Issue by obfuscoder** [RocketChat/Rocket.Chat.Electron#1620]
## My Setup

- Operating System: MacOS Catalina 10.15.5
- App Version: 2.17.9
- Installation type: via AppStore

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Since the latest update, chat windows show sometimes the full names, sometimes the login names of users. The option "hide user names" in preferences is switched on. I already tried to toggle this configuration without success. The config does not seem to have any effects. I did a complete reinstall and app reset without success as well. Most annoying is that the name display is not even consistent. Within 5 minutes I get from the same person a chat message and I will see both "Max Mustermann" and "mmustermann" in front of those messages. 

### Current Behavior

User names as well as login names are shown despite having "Hide usernames" switched on.

### Expected Behavior

Neither user names nor login names are to be shown when "Hide usernames" is switched on.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
