### ISSUE TITLE
User state not updated as expected after approving a user

### ISSUE THREAD

**Issue by raffaeler** [RocketChat/Rocket.Chat.Electron#1621]
## My Setup
- Operating System: Win10
- App Version: 2.17.9
- Installation type: exe
- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When an administrator approves a user in the `Administration` - `Users` window, the status of the user is not refreshed.
Step by step:
1. As an admin you receive the request to approve a user
2. Open the administrator - users window
3. Click on the user at the top of the list, three dots icon and `activate`
4. The user in the list is still marked as `deactivated`
5. Click on `Rooms` and then back to `Users` from the Administration panel
6. Now the user is list  is correct

### Current Behavior
The users list is not updated after a change on a user

### Expected Behavior
An automatic refresh of the user list/state is expected

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
