### ISSUE TITLE
Notifications for new messages doesnt work

### ISSUE THREAD

**Issue by IVIJL** [RocketChat/Rocket.Chat.Electron#1622]
## My Setup

- Operating System:
- App Version: 2.17.9 but tried even on 2.17.6
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The notifications doesn't work from desktop app on windows 10 (on the browser does)

### Current Behavior
Nothing, when I press test notification, nothing comes.

### Expected Behavior
receive sound and notification right now if I am not on the web I am never informed about new message. So cannot use this app because I never know that I have some unread messages.

**Comment by frdmn** [comment]
Can you guys please try version 2.17.11?

The PR #1662 should fix this problem. 😊

**Comment by MoisMoshev** [comment]
We recently updated to 2.17.11 (not sure of the original version, not too old), but it seems like the notifications broke at that point.
Private messages do show a notification most of the time, but e.g. mentions in a channel do not.

* Operating System: Windows 10
* App Version: 2.17.11
* Installation type: exe

**Comment by frdmn** [comment]
@MoisMoshev Can you take a look at the client console (View → Open DevTools) for any related messages?

**Comment by MoisMoshev** [comment]
No relevant messages in my console, only something about dictionaries/spell checking:
```
    app.js:6156 Error: ENOENT: no such file or directory, scandir 'C:\Users\mmoshev\AppData\Roaming\Rocket.Chat\dictionaries'
getPairsOfDictionaryFiles @ app.js:6156
app.js:6120 Error: Invalid key: already registered key
    at SpellCheckerProvider.loadDictionary (C:\Program Files\Rocket.Chat+\resources\app.asar\node_modules\electron-hunspell\dist\cjs\spellCheckerProvider.js:113)
    at registerSpellCheckingDictionary (app.js:6118)
    at async Promise.all (index 0)
    at async enableSpellCheckingDictionaries (app.js:6127)
```

**Comment by larkinson** [comment]
Exactly the same issue. What's the update on this one?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
