### ISSUE TITLE
Rocket.Chat 2.17.9 crashing right on start with illegal instruction 4

### ISSUE THREAD

**Issue by rpkoller** [RocketChat/Rocket.Chat.Electron#1624]
### Description:

I've upgraded Rocket.Chat to the latest version 2.17.9 in the MacOS Appstore. After upgrading, if I try to start Rocket.Chat, the app crashes right on start. 

### Steps to reproduce:

1. Upgrade to Rocket.Chat 2.17.9
2. Click the Application Icon 
3. Crash each time I try to start the app

### Client Setup Information

- Rocket.Chat 2.17.9
- MacOS 10.13.6 all the latest patches applied on a Macbook Pro 13" early 2011

### Additional context

Posted that issue already over at Rocket.Chat (https://github.com/RocketChat/Rocket.Chat/issues/16881) . Wasn't aware that the electron app has a separate repo. 

### Relevant logs:
[Rocket.Chat.Helper.GPU._2020-03-13-232529-1.crash.zip](https://github.com/RocketChat/Rocket.Chat.Electron/files/4733217/Rocket.Chat.Helper.GPU._2020-03-13-232529-1.crash.zip)

**Comment by franckadil** [comment]
Reproducible on Windows 10 1909

**Comment by franckadil** [comment]
@tassoevan I ran some tests to day on all platforms with same result, but this happen for me only on the develop branch. Also note than in development mode (yarn start) the app runs flawlessly, it only fails on production release.

```sh
(electron:109684): Gtk-WARNING **: 23:32:47.573: Theme parsing error: gtk.css:1710:67: Junk at end of value for background-image

(electron:109684): Gtk-WARNING **: 23:32:47.579: Theme parsing error: gtk.css:2822:2: Expected semicolon

(electron:109684): Gtk-WARNING **: 23:32:47.588: Theme parsing error: gtk.css:4591:34: Expected a valid selector
[109716:0614/233300.200657:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command


  icon
    ✓ app
    tray
      ✓ darwin
      ✓ darwin-dark
      ✓ linux
      ✓ win32

```

**Comment by rpkoller** [comment]
well updated to version 3.0.3 via the MAS and the exact same behavior aka crash persists (right on start meaning clicking the dock icon) :(((( I'll attach one of the crashlogs: 
[Rocket.Chat Helper (GPU)_2020-10-14-040421.zip](https://github.com/RocketChat/Rocket.Chat.Electron/files/5375142/Rocket.Chat.Helper.GPU._2020-10-14-040421.zip)

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
