### ISSUE TITLE
Type your new password

### ISSUE THREAD

**Issue by Cyprian7** [RocketChat/Rocket.Chat.Electron#1625]
Opened the window with "This email has already been used and has not been verified. Please change your password.

Type your new password"

And I take the new password 
Still information about 
"ERROR"
"Entered password same as current password [error-password-same-as-current]"
Enter different passwords and still the same error and i cant logged in

**Comment by broth-eu** [comment]
I am having the same issue. Did you find a solution / workaround?

**Comment by OlafDammann** [comment]
same here: oAuth against a WordPress instance, first login seem to work, second ones fail. Not all, don't see a pattern right now.

**Comment by OlafDammann** [comment]
Changes I made, issues I solved (feedback missing so far):
* Backend - Settings - Accounts: Disable Change username, password and email (as this has to come from the oAuth)
* Usernames: The oAuth created several Usernames including an "@", which is illegal in R.C. I changed them in oAuth and R.C to just $FIRSTNAME.$LASTNAME
* Userrole: Some of the accounts created by oAuth didn't had any role, so no rights. I manually added them all into "users"-Role

Let's see, if this was it

**Comment by OlafDammann** [comment]
This https://forums.rocket.chat/t/imported-ldap-users-have-no-role/8021 heavily suggests, the missing userrole is the main error in the system.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
