### ISSUE TITLE
Can't install new language dictionary

### ISSUE THREAD

**Issue by plinnie** [RocketChat/Rocket.Chat.Electron#1626]
Operating System: Windows 10, 64 bit, Intel
Rocket.Chat version: 2.17.7
Expected behavior: Be able to install Dutch dictionary using right-click on input area 'Spelling Lanugages > 'Browse for language'. Select a .dic file, and the language should be added
Actual behavior: Error message
Can the bug consistently be reproduced? Just try to install a dictionary
Relevant errors and other log output:
```
app.js:6161 Error: ENOENT: no such file or directory, scandir 'C:\Users\Admin\AppData\Roaming\Rocket.Chat\dictionaries'
getPairsOfDictionaryFiles @ app.js:6161
3app.js:6125 Error: Invalid key: already registered key
    at SpellCheckerProvider.loadDictionary (C:\Users\Admin\AppData\Local\Programs\Rocket.Chat\resources\app.asar\node_modules\electron-hunspell\dist\cjs\spellCheckerProvider.js:113)
    at registerSpellCheckingDictionary (app.js:6123)
    at async Promise.all (index 0)
    at async enableSpellCheckingDictionaries (app.js:6132)
```

After getting the error, I manually created the directory 'dictionary' which did not exsits, and now it works.

Attached: Dutch dictionary I tried to install
[Dutch.zip](https://github.com/RocketChat/Rocket.Chat.Electron/files/4750471/Dutch.zip)

**Comment by plinnie** [comment]
Never mind, I actually can't select the dictionary. I also renamed it to nl_NL.dic, and installed it, but that also does not work. I get the error:
```

  | registerSpellCheckingDictionary | @ | app.js:6125
-- | -- | -- | --
  | async function (async) |   |  
  | registerSpellCheckingDictionary | @ | app.js:6122
  | enableSpellCheckingDictionaries | @ | app.js:6132
  | (anonymous) | @ | app.js:6318
  | (anonymous) | @ | app.js:6044
  | Promise.then (async) |   |  
  | (anonymous) | @ | app.js:6044
  | apply | @ | callbacks-registry.ts:45
  | (anonymous) | @ | remote.js:286
  | (anonymous) | @ | remote.js:276
  | emit | @ | events.js:203
  | EventEmitter.emit | @ | domain.js:476
  | onMessage | @ | init.ts:50
```

**Comment by plinnie** [comment]
I found a dictionary including a .aff file, and now it works. 
So, I would suggest two improvements:

1.  A dictionary directory should be automatically created on installation, or when adding a dictionary for the first time
2. It should not allow installation of a language w/o the accompanying .aff file.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
