### ISSUE TITLE
Can't get chat on SeekingAlpha

### ISSUE THREAD

**Issue by DBISSETT413** [RocketChat/Rocket.Chat.Electron#1627]
Says it all.  Can't access chat on SeekingAlpha.  CLicking on CHAT took me to Rocketchat download page, why??? Never had to before, this was seamless.  Installed on desktop, then asked to sign in, to what???  Registered, then tried to sign in, sign in window  got stuck, still can't access chat on SeekingAlpha.  This is a work day.  Rocket chat needs to work, without all the glitches.  If it can't then the group I belong to needs to take their business somewhere else.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
