### ISSUE TITLE
RC v2.17.7 limiting photo and gif sizes

### ISSUE THREAD

**Issue by eholloway135** [RocketChat/Rocket.Chat.Electron#1629]
## My Setup

- Operating System: Windows 10 v1903
- App Version: v 2.17.7
- Installation type: .exe

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description

Photos and Gifs that previously could be uploaded give "Request Entity Too Large" error. Get error randomly, as sometimes it accepts gifs over 1mb and sometimes it won't  at all.
Steps to reproduce:
Go to file explorer
Find pictures you frequently send via Rocket.Chat
Test upload
If picture is past a certain size it will give an error, even if you could previously upload
### Current Behavior

Error "Request Entity Too Large"
### Expected Behavior

The photo or Gif uploads

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
