### ISSUE TITLE
Windows toast notification not showing script altered avatar

### ISSUE THREAD

**Issue by jcrower** [RocketChat/Rocket.Chat.Electron#1631]
## My Setup

- Operating System: Windows 10 64bit
- App Version: 2.17.9
- Installation type: exe

- [X ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When using an Incoming Webhook to send a message and changing the avatar along the way via script, the Windows toast notification does not display the altered avatar, only the users original avatar image. The altered avatar does display correctly in the main chat window.

### Current Behavior
Windows toast notification only ever displays sending users original avatar.

### Expected Behavior
Windows toast notification should show same avatar as the message within the main chat window.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
