### ISSUE TITLE
livestream video image is blurry

### ISSUE THREAD

**Issue by mhow2** [RocketChat/Rocket.Chat.Electron#1632]
## My Setup

- Operating System: ubuntu 18.04 LTS
- App Version: 2.17.9
- Installation type: debian package as shipped at https://github.com/RocketChat/Rocket.Chat.Electron/releases

 
- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
See below a screenshot of a livestream on the electron app (left) and the same stream on firefox (right)

![2020-06-17_16-50](https://user-images.githubusercontent.com/9987241/84914062-7bc36f80-b0bb-11ea-9133-8f226b1a81dc.png)

### Current Behavior
Image is blurry with the Electron app

### Expected Behavior
Same image quality on the Electron app than for any browser.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
