### ISSUE TITLE
(version 2.7.17-3.0.0) rocketchat can not run while built succeed under windows10

### ISSUE THREAD

**Issue by r00t1900** [RocketChat/Rocket.Chat.Electron#1634]
(Just wonder how the release version of 2.7.17 was created...I just could not built it anyway, hope some guys can share his experience for me, I got windows 10 with VS2020 C++ Desktop development to compile .exe version and WSL or VM to compile .deb version. Hope some people can help me with this, Thank you!)

Actually I have 2 questions about compiling the rocket.chat electron based desktop client:

**question#1: build the latest version v3.0.0-develop**

I clone the latest version of rocket.chat.electron to my windows 10 x64 laptop which with node(x64) and npm version:
>node -v
v12.18.0
>npm -v
6.14.4
This environment comes from official site:https://nodejs.org/dist/v12.18.0/node-v12.18.0-x64.msi

also I have yarn already with command npm install -g yarn, the yarn version is 1.22.4.
then I change directory to the root of rocket.chat.electron project and use command yarn to install dependencies. It was a suceess and can run perfectly when I use command yarn start.
However when I want to pack this to a executable file like .exe, It just won't show a GUI but all messages echoed by yarn release shown that the compiling is successful(finally I even install Microsoft Visual Studio 2019 with C++ Desktop development and set npm msvs_verison to 2019, but it did not help).
Here is the console output:
![image](https://user-images.githubusercontent.com/57323846/85089966-8e9e8700-b216-11ea-8102-3501f785e87a.png)
![image](https://user-images.githubusercontent.com/57323846/85089970-92caa480-b216-11ea-811b-c39d5bfe4c6a.png)

And it just won't show any display, but I can find 4 progress in Windows Task Manager, both with a 0%CPU usage. I just confuse why the official website can give a release download but I could not get a perfect build. So I come to website and found the downloadable install package is based on version 2.17.7:
![image](https://user-images.githubusercontent.com/57323846/85089988-9ceca300-b216-11ea-924f-4abdcd9012bd.png)

download url is:https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.7/rocketchat-setup-2.17.7.exe
So I come to the release page and find the 2.17.7 release:
![image](https://user-images.githubusercontent.com/57323846/85090005-a70ea180-b216-11ea-8bc8-00195ee9583a.png)

and choose the source code option in assets:
https://github.com/RocketChat/Rocket.Chat.Electron/archive/2.17.7.zip
Then I come with the question#2 cause I meet another problem ...

**question#2:build the release 2.17.7 stable version**
I reinstall node and npm and change work directory to the project directory, run the following command:
>yarn

![image](https://user-images.githubusercontent.com/57323846/85090029-b130a000-b216-11ea-838f-23d81f1f5285.png)

it seems to be ok about the dependencies.
>yarn start

![image](https://user-images.githubusercontent.com/57323846/85090038-b7268100-b216-11ea-85f3-41ff12090c28.png)

now I can not even build to app folder ... so I can even run it. These 2 problems confuse me and I could not just fall asleep last night.

 Does anyone have any good idea? I search in the issues of git repo and found that source code in version 2.17.9  also suffers from question#1.

**Comment by trinh-ngo-ntq** [comment]
This may related to ticket #1616 (https://github.com/RocketChat/Rocket.Chat.Electron/issues/1616)
I don't know  but those releases are not really stable and broken down anyway.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
