### ISSUE TITLE
Desktop App oauth issue

### ISSUE THREAD

**Issue by subendra** [RocketChat/Rocket.Chat.Electron#1635]
## My Setup

- Operating System: ubuntu 20.04
- App Version: 2.17.7
- Installation type: deb file

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

### Current Behavior

when we click button of oauth in login page, it pop up new window of oauth website (first). after that we put credential and tried to click login in, again it open up same web link in another browser(second) stating "state token does not match". fails to login. 
Note: Sometime it open up and gets authenticate in first login page.

### Expected Behavior

It should authenticate in first login page which is popped up at first time.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
