### ISSUE TITLE
Notification issue in i3

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat.Electron#1638]
On Ubuntu 20.04 i3wm, with the most recent desktop client for Ubuntu, there are no popup notifications for direct messages or mentions. The workspaces do not change color to indicate a unread message. The taskbar icon only shows up if you click "tray icon" twice. There is no way to see if someone sent a new message to you. In Arch XFCE, this problem does not happen.

**Comment by lapaloma1980** [comment]
> On Ubuntu 20.04 i3wm, with the most recent desktop client for Ubuntu, there are no popup notifications for direct messages or mentions. The workspaces do not change color to indicate a unread message. The taskbar icon only shows up if you click "tray icon" twice. There is no way to see if someone sent a new message to you. In Arch XFCE, this problem does not happen.

I have the same problem with i3 and Ubuntu I can only here the message sound. But it's not very reliable because I listen often to music while programming.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
