### ISSUE TITLE
Ola, a opção de live chat não aparece no portal de administração após instalação, é necessário mais algum procedimento? Desde já agradeço.

### ISSUE THREAD

**Issue by flavioteles** [RocketChat/Rocket.Chat.Electron#1639]
## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by tassoevan** [comment]
Por favor, procure nosso canal de suporte à comunidade (https://open.rocket.chat/channel/support) para ajuda.
