### ISSUE TITLE
Severe lag with OS X client when application is running on Retina Display

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat.Electron#164]
@frdmn commented on [Wed Apr 06 2016](https://github.com/RocketChat/Rocket.Chat/issues/2783)

Your Rocket.Chat version: just recloned from master

![bildschirmfoto 2016-04-06 um 10 39 33](https://cloud.githubusercontent.com/assets/944459/14310737/e015d32e-fbe3-11e5-950c-821520584d6d.png)

I am using a Cinema Display in addition to my MacBook Pro Retina screen and I noticed that whenever `Rocket.Chat+` is running on the Retina display, the fans are spinning like crazy and the Rocket.Chat client by itself gets really unresponsive and laggy.

Whenever I move the application from the MacBook screen to my (non-retina) Cinema Display, the application is fast and the lag/performance issues are gone immediately.

I made two comparison GIFs to show you the issue:
#### Retina display (laggy) - [alternative .mov](http://up.frd.mn/6Fx2uOSoUW.mov)

![1_laggy mov](https://cloud.githubusercontent.com/assets/944459/14310816/37c1293e-fbe4-11e5-9e93-6d825656d118.gif)
#### Cinema display (no lag) - [alternative .mov](http://up.frd.mn/hnM9nrxmyM.mov)

![2_non-laggy mov](https://cloud.githubusercontent.com/assets/944459/14310861/6d4894d4-fbe4-11e5-9bbc-1ba8ef31845c.gif)

Any ideas?

---

@frdmn commented on [Wed Apr 06 2016](https://github.com/RocketChat/Rocket.Chat/issues/2783#issuecomment-206244171)

Crud, I just noticed that i should have probably raised this issue in the https://github.com/RocketChat/Rocket.Chat.Electron/ repository.

---

@rodrigok commented on [Wed Apr 06 2016](https://github.com/RocketChat/Rocket.Chat/issues/2783#issuecomment-206344558)

@frdmn Had you downloaded the app from the Map App Store?

If yes, can you try the DMG version? https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/1.3.0

I'd test here and this happens for me only when I'm using the version distributed via Mac App Store. If you confirm I will open a new issue on the electron's repository.

Thanks

I will move this issue to the correct place
##

**Comment by frdmn** [comment]
@rodrigok Thanks for the quick reply. I can confirm that version 1.3.0 fixed the issue for me, and that i was also using 1.2.0 out of the Mac App Store.

**Comment by rodrigok** [comment]
@frdmn ok, so, the 1.3.1 will have the same issue if you download from Mac App Store after apple review (I sent to review a few hours ago).

**Comment by frdmn** [comment]
Alright, I'll keep an eye on this issue for further updates :

**Comment by ulope** [comment]
For me this problem still persists with 1.3.1 from the MAS. Scrolling and typing is excruciatingly slow on the retina display.

**Comment by mbialas** [comment]
Seeing this issue as well. 2016 rMBP via USB-C --> DP adapter. Pushing 2560 x 1440 to a ViewSonic 4k monitor

1.3.1 from MAS

**Comment by ulope** [comment]
Any news on this? Can we as the community help somehow?
The lag and graphics issues are really very annoying. Esp. in the fast channel switcher (Cmd/Ctrl-P) and in the user completion popup (when typing "@").

**Comment by engelgabriel** [comment]
@ulope can you test with the version `2.2.3`?

**Comment by dmitrijnikolajev** [comment]
Ubuntu Gnome 16.10 (asus ux306ua hidpi screen 3200x1800) might have same performance issue:

![screenshot from 2017-03-21 16-34-24](https://cloud.githubusercontent.com/assets/23337957/24152730/22af8b42-0e55-11e7-996b-054f7a5a2459.png) 
![screenshot from 2017-03-21 16-34-40](https://cloud.githubusercontent.com/assets/23337957/24152731/22b17e2a-0e55-11e7-81e3-bd06995dc4ca.png)

**Comment by ulope** [comment]
@engelgabriel I only recently became aware that there have been a lot of releases, just not in the MAS :/

I can confirm that with current versions the performance is indeed much better (if maybe not entirely up to "native" feel)

**Comment by engelgabriel** [comment]
We are updating the MAS version right now.

**Comment by compuguy** [comment]
@engelgabriel Any progress on updating the MAS,  #403?

**Comment by engelgabriel** [comment]
Yes @compuguy MAS updated!!!
