### ISSUE TITLE
Oauth2 error exclusively from the app with nextcloud.

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.Electron#1641]
## My Setup

- Operating System: Windows 10 19.09
- App Version: 2.17.7
- Installation type: .exe

## Description
`Access denied
The given token does not match`

I receive this error after logging into nextcloud. It happens exclusively with the Rocket desktop app. I already tried from the browser and authentication by Outh2 works correctly. Similarly check the id and the token provided by my nextcloud server and it is correct. As I already mentioned, it works in the browser.

Regards

![token](https://user-images.githubusercontent.com/35962168/86280785-7af60780-bbaa-11ea-91e7-ff0888adf4a2.jpg)

**Comment by aleadco** [comment]
Related with  #1639

**Comment by aleadco** [comment]
It was tested in the app for macOS and I get the same error.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
