### ISSUE TITLE
Win10 client (2.17.7) Delay in sending messages, stuck, consume memory

### ISSUE THREAD

**Issue by liujunfei980** [RocketChat/Rocket.Chat.Electron#1646]
## My Setup

- Operating System: Windows 10 v1903
- App Version: v2.17.7
- Installation type: .exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

We use the stress test tool jmeter to simulate 100 virtual users to send information through the rocket api interface. During the test, the user terminal was stuck, the information transmission was severely delayed, and the computer memory will continue to increase. After the stress test, the computer memory will not be automatically released. Only by forcibly closing the rocket process from the task management can the memory be released.

### Current Behavior

We upgraded the client from 2.17.7 to 2.17.9, the problem remains the same
### Expected Behavior

We hope to solve this problem or provide a better stress test solution

**Comment by tassoevan** [comment]
> the user terminal was stuck
Not sure if I got what "user terminal" means. Do you mind explaining?

**Comment by LeeThompson** [comment]
Seen this type of behavior as well (especially using insane amounts of memory), however, I've also seen the high memory usage just running the browser client (also in Chrome) so this may be partially a Chromium issue.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
