### ISSUE TITLE
Icon is distorted when placed in a folder in the macOS Launchpad

### ISSUE THREAD

**Issue by beingmrkenny** [RocketChat/Rocket.Chat.Electron#1648]
## My Setup

- Operating System: macOS 10.14.16
- App Version: 2.17.9
- Installation type: App Store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
<img width="103" alt="image" src="https://user-images.githubusercontent.com/2005857/87177471-97ddb980-c2d3-11ea-99c1-ff0565737dbc.png">

The rocket chat icon is on the bottom row, furthest to the right.

### Current Behavior
When the app icon is placed in a folder in macOS's launchpad, the smaller version that is generated is distorted, resembling "snow" on a detuned TV.

I've tried this with a fresh installation of rocket chat, after a system reboot

### Expected Behavior
A smaller icon should appear

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
