### ISSUE TITLE
Zoom level lost after closing the app

### ISSUE THREAD

**Issue by michaudg** [RocketChat/Rocket.Chat.Electron#165]
ArchLinux
Rocket.Chat :  1.3.1

If I zoom in, close the application and reopen it, the zoom level back to original zoom.
##

**Comment by giray** [comment]
+1

**Comment by engelgabriel** [comment]
Zoom level also resets to its original value when it hits a cached video, like a preview from youtube.

I think it has something to do with the old version of jQuery there.

**Comment by gustavkarlsson** [comment]
I had a similar issue where I first zoomed out, and then couldn't restore the default zoom level again and making it stick.
Everytime I switched conversation, the zoom level went back to the "zoomed out" state. A restart fixed it.

**Comment by gustavkarlsson** [comment]
Further investigations show that all zoom levels EXCEPT default sticks.

Whenever I switch conversation, it restores the last zoom level that **isn't** default. So if I change from the default, I can never permanently go back... Not sure if this is the same issue or not.

**Comment by vcapretz** [comment]
hey @michaudg are still facing this issue? I just tested on v 2.9.0 and works fine!

**Comment by michaudg** [comment]
Yes, that's fine now! Zoom level is persistent. I think the issue can be closed.
