### ISSUE TITLE
Error was raised with custom dictionary: path" argument must be one of type string, Buffer, or URL.

### ISSUE THREAD

**Issue by Xarkam** [RocketChat/Rocket.Chat.Electron#1657]
## My Setup

- Operating System: windws 10 2004
- App Version: 2.17.10
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
After creating missing folder `AppData\Roaming\Rocket.Chat\dictionaries`, I add my language dictionary (dic and aff files), I selecte it.
The dictionary run correctly, but a trace error was raised:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.readFile (fs.js:302)
    at Object.fs.readFile (electron/js2c/asar.js:485)
    at Object.fs.readFile (electron/js2c/asar.js:485)
    at internal/util.js:286
    at new Promise (<anonymous>)
    at Object.readFile (internal/util.js:285)
    at registerSpellCheckingDictionary (app.js:6117)
    at Array.map (<anonymous>)
    at enableSpellCheckingDictionaries (app.js:6127)
    at app.js:6313
registerSpellCheckingDictionary @ app.js:6120
```

### Current Behavior
An error is raised in the console for custom dictionary

### Expected Behavior
No error on path for custom dictionary

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
