### ISSUE TITLE
/assets/favicon.svg requested constantly from Electron app -- starving our proxy

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat.Electron#1658]
## My Setup

- Operating System: (Windows, Mac)
- App Version: 2.17.7 and others
- Installation type: N/A

- [ - ] I have tested with the latest version
- [ - ] I can simulate the issue easily

## Description

We are seeing many, many requests for `/assets/favicon.svg` in our logs. Many -- e.g. constant requests, 90k in 15 minutes. There are two issues here.

1. we are hosting Rocket.Chat under `/chat`, but the favicon request is to `/assets/favicon.svg?_=###` where `###` is a cache-buster
2. the favicon is requested constantly, it is starving our proxy!

The version of desktop client used is not within our control, as we have thousands of users who may, potentially, elect to use the RC desktop client.

### Current Behavior

The desktop / Electron app continuously requests the favicon.

### Expected Behavior

The desktop / Electron app does not continuously request the favicon.

**Comment by JoshMcCullough** [comment]
This is crushing our _production_ system, any thoughts from the team?

**Comment by JoshMcCullough** [comment]
This appears to be a bug in RC v. 2.17.x due to a bug in Electron 7.1.x, and is fixed in the current develop branch. When is the next release which includes an upgrade to Electron v7.3.2 coming out?

**Comment by JoshMcCullough** [comment]
One final chart showing requests for `/assets/favicon.svg` over the last 24 hours, broken out by RC/Electron version:

![image](https://user-images.githubusercontent.com/4859660/88081745-d7679980-cb4e-11ea-9f8f-8218365a1945.png)

**Comment by fitzyjoe** [comment]
I tested Master 2.17.10 and I watched it make a bunch of requests for favicon.svg.  Then I tested the develop branch (HEAD) and it seems to reasonably only request the favicon.svg once.  I suspect commit [4c06582](https://github.com/RocketChat/Rocket.Chat.Electron/commit/4c06582ba3021fcf10e6230286231d50e26e2723) on July 15 fixed the problem by upgrading from Electron 7.1.1 to 7.3.2

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
