### ISSUE TITLE
Problemas com corretor / idioma 

### ISSUE THREAD

**Issue by oliveira-wareline** [RocketChat/Rocket.Chat.Electron#1659]
Estava utilizando a versão 2.17.8 e apareceu mensagem de atualização para versão 2.17.10, a partir da atualização o comportamento do corretor aparenta não estar no português brasil, pois tudo que escrevo aparece grifado como se estivesse errado.
![erro grafia](https://user-images.githubusercontent.com/68356435/87726168-e4723a80-c794-11ea-8b00-ae5b04f3f477.jpg)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
