### ISSUE TITLE
Client Update Failing 2.17.7 -> 2.17.10 (Windows)

### ISSUE THREAD

**Issue by icerootsvw** [RocketChat/Rocket.Chat.Electron#1660]
Using currently 2.17.7 on Windows and the Client is informing that there is a new version available 

![image](https://user-images.githubusercontent.com/40857785/87908031-0d7d1e80-ca66-11ea-80a9-38434693c289.png)

Trying to install this version is doing nothing.

As it seems on the download-page there is only 2.17.9 available, so maybe this is already the bug that there is no 2.17.10 for download?

![image](https://user-images.githubusercontent.com/40857785/87908310-72d10f80-ca66-11ea-99d4-1694193cf0f7.png)

**Comment by Smove** [comment]
> As it seems on the download-page there is only 2.17.9 available, so maybe this is already the bug that there is no 2.17.10 for download?

There is the 2.17.10, the link on the homepage is unfortunately still wrong.
https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.10/rocketchat-setup-2.17.10.exe

All current releases can be found here: https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by icerootsvw** [comment]
@Smove thank you for the information. Do you know if the desktop client is failing because the 2.17.10 is not on the website? or is there another reason? is there some useful output i can find and deliver to debug this issue with the update?

**Comment by Smove** [comment]
I don't know. Unfortunately, I have exactly the same problem.

**Comment by pRieStaKos** [comment]
Windows is blocking the Windows build. I have to choose to run anyway to install the `2.17.10` and `2.17.11`.

**Comment by athanasio** [comment]
SmartScreen on Windows is blocking the installation of both 2.7.10 and 2.7.11. Downloading the setup with Chromium Edge in addition warns that the software can harm your computer and offers to delete it. 2.7.9 downloads and installs without issues.

**Comment by Smove** [comment]
This seems to be the same problem as #1205

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
