### ISSUE TITLE
".Ipa" file upload problem

### ISSUE THREAD

**Issue by MaxBruev** [RocketChat/Rocket.Chat.Electron#1663]
I can't import ".ipa" files into chat. A similar problem appeared after updating RocketChat. Throws an error like this: 
![Безымянный](https://user-images.githubusercontent.com/68557707/88011372-57870280-cb41-11ea-88d9-276329e145d0.png)

**Comment by ankar84** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/18323

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
