### ISSUE TITLE
Rocketchat 2.17.10 on snapcraft does not respect font settings

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat.Electron#1664]
- Operating System: Debian 10 Buster
- App Version: 2.17.10
- Installation type: snapcraft

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

On debian 10, using Rocketchat from snapcraft does not respect the font settings in Administration -> Settings -> Layout -> Body Font Family, but rather gives it some default font. If I experiment with changing the font here, the font will successfully change in the browser, and on the 2.17.10 client for windows and on arch linux, but on Debian the font will not change. I have tried this on both my desktop and laptop, both are running Debian 10 with a rocketchat snapcraft install.

**Comment by mmgoilf** [comment]
This problem exists on 2.17.11 as well

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
