### ISSUE TITLE
Client takes 10 min to start up before successfully connecting to server (both on a local network, cut off from Internet)

### ISSUE THREAD

**Issue by ttushka** [RocketChat/Rocket.Chat.Electron#1666]
## My Setup

- Operating System: Windows 10
- App Version: current
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Client and server cut off from Internet. Connection works, but only after 10 min of start up on client side. 

### Current Behavior
My Rocket.Chat Desktop Client can connect to my Rocket.Chat Server just fine, all good. Only it takes literally 10 min for the Desktop Client to start up initially. 
Both the client and server are cut off from the Internet. I suspect the issue is one of polling the internet for something and only after 10 min finally timing out and moving on. 

### Expected Behavior
I’d like to change an Environment Variable of some other thing to prevent the client software from fetching stuff from the internet. Or set the timeout to after only a few seconds.

**Comment by tassoevan** [comment]
@ttushka Does this delay happens when logging into the server via web browser?

**Comment by ttushka** [comment]
@tassoevan No it does not. Web Browser is instant.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
