### ISSUE TITLE
Erro ao abrir anexo.

### ISSUE THREAD

**Issue by berkeuer** [RocketChat/Rocket.Chat.Electron#1667]
Ao abrir anexo a região da conversa fica travada com a mensagem para anexar arquivo.
Porém a ação esperada, seria abrir uma im
![image](https://user-images.githubusercontent.com/64744488/88290347-ff7d0700-cccc-11ea-894d-513d945625f9.png)
agem recebida.

**Comment by tassoevan** [comment]
Por favor, procure nosso canal de suporte à comunidade (https://open.rocket.chat/channel/support) para ajuda.
