### ISSUE TITLE
[Bug] Enable Auto Away feature don't work on Windows 7 - User status doesn't change on desktop lock

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1669]
## My Setup

- Operating System: Windows 7
- App Version: 2.17.7
- Installation type: exe

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
**Enable Auto Away** feature works perfect on Windows 10 when pressing WIN+L combination to lock desktop or after **Idle Time Limit**
But on Windows 7 when user locks desktop by WIN+L user status doesn't change and remain **Online**
That leads to push notification not send to user when ho out of computer.
Maybe related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1225

### Current Behavior
On Windows 7 when user locks desktop by WIN+L user status doesn't change and remain **Online**

### Expected Behavior
On Windows 7 when user locks desktop by WIN+L user status must be change to **Away**

**Comment by ankar84** [comment]
That issue is not 100% reproducible  on Windows 7.
Sometimes Windows Locks leads to Auto-Away.

**Comment by stylefish** [comment]
i have the opposite behavior (but on windows 10): when auto away ist enabled and i lock my sceen, my status ist set to `away` but after i unlock my screen, the status is not reverted to the "original" status (e.g. online)... i think this might be related to #1542

**Comment by ankar84** [comment]
I'm closing that issue, because it's not 100% reproducible on Windows 7 and I don't know actual circumstances.
