### ISSUE TITLE
RocketChat Desktop stuck at cloud login page

### ISSUE THREAD

**Issue by mohammedragabsoftxpert** [RocketChat/Rocket.Chat.Electron#1672]
## My Setup

- Operating System: Ubuntu 16.04
- App Version: 2.17.11
- Installation type: deb

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
I was trying to register our workspace, and clicked on Login cloud button and it gave me the below screen, and can't login and can't get back to the normal rocketchat dashboard, no error at all
![image](https://user-images.githubusercontent.com/47364489/88486179-30369800-cf7c-11ea-87ab-64dfcdc99389.png)

I tried to reset the app, re-install, reload ...etc nothing

### Current Behavior
Stuck at the above screen

### Expected Behavior
Either login to cloud or remove that screen and continue with my rocketchat dashboard

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
