### ISSUE TITLE
yarn release fails with Exit Code 1 'not a Git repo'

### ISSUE THREAD

**Issue by ttushka** [RocketChat/Rocket.Chat.Electron#1673]
## My Setup

- Operating System: Windows 10
- App Version: current
- Installation type: not installed, cloned git repo

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I cloned the git repo and followed the instructions to try and build it. No changes made in the repo whatsoever. I installed the yarn version plugin. Commands `yarn` and `yarn start` work as expected.

### Current Behavior
 Command `yarn release` fails with exit code 1.
```
C:\myProjectPath\Rocket.Chat.Electron>yarn release
yarn run v1.22.4
$ C:\myProjectPath\Rocket.Chat.Electron\node_modules\.bin\release
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
Error! Directory is not a Git repository.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior
Successful build and a newly created dist folder with the built app in it.

**Comment by tepafril** [comment]
I have the same issue.

 `yarn run v1.22.5
error Command "release" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by tassoevan** [comment]
@tepafril Currently we don't have the `release` npm script at the `develop` branch anymore. Please look at `.travis.yml` as reference properly to invoke `electron-builder`.
