### ISSUE TITLE
I have been using rocket.chat since mid-June. For the past several days, the app opens with a message stating that a new version - 2.17.11 - is available. I select install. Then the app says it will install the update when ready. This message continues to appear every day I start the app. The update has not been installed. How can I update the app to the lastest version on my Windows PC?

### ISSUE THREAD

**Issue by teachertools** [RocketChat/Rocket.Chat.Electron#1674]
## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by Smove** [comment]
Seems to be a duplicate of #1205 #1660 #1670 

Currently the only solution is probably to update Rocket.Chat manually. Since the link on the website is not updated, it is best to download the latest installer from https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by teachertools** [comment]
Thank you. Sorry for the redundancy; I am new to github. I will download the latest installer through github. Can you provide guidance on how to do this? I see this list, but I am not sure what I am supposed to do or select to download the installer on my Windows 10 PC. I tried downloading some of these files yesterday but could not find an installer. 

![image](https://user-images.githubusercontent.com/68863156/88699070-de555580-d0d4-11ea-9a31-0fa8ed442ca7.png)

**Comment by Smove** [comment]
For Windows you need to download and run the _rocketchat-setup-2.17.11.exe_

**Comment by teachertools** [comment]
Thank you! I followed your instruction. Running rocketchat-setup-2.17.11.exe resolved the issue. I appreciate your help.
