### ISSUE TITLE
macOS Double Notification Sound

### ISSUE THREAD

**Issue by jf-jflo** [RocketChat/Rocket.Chat.Electron#1682]
## My Setup

- Operating System: macOS Catalina (10.15.5)
- App Version: 2.17.9 (Latest Available on App Store)
- Installation type: Apple App Store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When push notifications are enabled, macOS will play 2 notification sounds even though only 1 notification is received. It plays the user (or default) selected notification sound (as selected in rocketchat - My Account > Preferences > Sound) as well as playing the macOS notification sound. This only happens when the rocketchat desktop client is opened. 

Current workarounds are:
1. Disabling push notifications completely (Administration > Push > Disabled) resulting in only the selected rocketchat client notification sound to play (not the macOS notification sound).

2. Going to your System Preferences > Notifications > Rocket.Chat and toggling off the "Play sound for notifications" setting which will disable the macOS notification sound only (rocketchat selected notification sound will continue to play)

### Current Behavior

2 notification sounds (rocketchat selected + macOS) will sound when a notification is received 

### Expected Behavior

only 1 notification sound plays (the rocketchat selected notification sound)

**Comment by rollitoJFLO** [comment]
Leaving an update on this issue, recently upgraded to macOS Big Sur (11.0.1) and it looks like the double notification issue is no longer happening. 

Rocket.Chat client version: 3.0.7
Rocket.Chat server version: 3.7.1 (docker)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
