### ISSUE TITLE
Cannot install latest version

### ISSUE THREAD

**Issue by Rich-Hopkins** [RocketChat/Rocket.Chat.Electron#1683]
App repeatedly tells me that there is an update available, and when I click install, it tells me that it will do so when ready, but never does. I typically just go to the web and download the new version, but now the website is two versions behind what the app says is "ready". This is what happened with 2.17.10, and now with 2.17.11. 

## My Setup

- Operating System: Windows 10 1903
- App Version:2.17.9
- Installation type: downloaded windows install from rocket.chat. 

- [ ] I have tested with the latest version - I cannot test with latest version, as it is not available for me to install.
- [x] I can simulate the issue easily - by just starting Rocket Chat

## Description
Described above

### Current Behavior
Described above

### Expected Behavior
It should install the new version. Or failing that, I should be able to download the new version so that I can force the install.

**Comment by xmedeko** [comment]
Same for me, I have 2.7.10 and auto update to 2.7.11 fails on Windows 10.
A file `c:\Users\...\AppData\Local\rocketchat-updater\pending\temp-rocketchat-setup-2.17.11.exe` is being downloaded, but after a moment it's removed and nothing happens.

**Comment by ankar84** [comment]
Same as https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670
