### ISSUE TITLE
Consider update Electron Version min to 9.0.1

### ISSUE THREAD

**Issue by IhorNykyha** [RocketChat/Rocket.Chat.Electron#1685]
## My Setup

- Operating System: Windows 10
- App Version: 2.17.10
- Install method: Appx

## Description
Consider updating Electron Version min to 9.0.1.
In the previous version, the electron js has a problem with process.windowsStore. 
This may cause a problem with auto-update if you have installation from an Appx.
Useful links:
describe bugs: https://github.com/electron/electron/issues?q=is%3Aissue+process.windowsStore
fixed version: https://www.electronjs.org/releases/stable?page=2#release-notes-for-v901

### Current Behavior
Chat installed from the Appx package show auto-update dialog and install another one chat desktop client. As a result, we have two desktop clients in the system.

### Expected Behavior
Chat installed from the appx package shouldn't show an auto-update dialog and shouldn't start the auto-update process.

**Comment by tassoevan** [comment]
Thank you very much! I'm closing it as `develop` already is using Electron 10. It will soon be merged into `master`.
