### ISSUE TITLE
Unresolved Deps on Windows

### ISSUE THREAD

**Issue by starhound** [RocketChat/Rocket.Chat.Electron#1687]
## My Setup

- Operating System: Win10 build 2004
- App Version: Latest
- Installation type: exe/win unpacked

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
trying to compile with electron-builder reports unresolved deps:

```
• unresolved deps  unresolved=minimist nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=argparseesprima nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules\i18next-node-fs-backend\node_modules round=0
  • unresolved deps  unresolved=argparseesprima nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=1
  • unresolved deps  unresolved=convert-source-map@emotion/hash@emotion/memoizebabel-plugin-macrosbabel-plugin-syntax-jsxescape-string-regexpfind-root@babel/helper-module-imports@emotion/serialize
                     nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules
                     round=0
  • unresolved deps  unresolved=import-freshpath-typeyaml nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=json-parse-better-errorslines-and-columns@babel/code-frameerror-ex nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=@babel/helper-validator-identifierjs-tokens nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=escape-string-regexp nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=color-convert nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=parent-module nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=builder-util-runtimefs-extrajs-yamllazy-vallodash.isequal nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=esprimaargparse nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=loose-envifyprop-typesreact-is@babel/runtimehoist-non-react-statics nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=loose-envifyobject-assignreact-is nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=loose-envifyobject-assignprop-typesscheduler nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=loose-envifyobject-assign nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=prop-typesloose-envifyobject-assign nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=loose-envify nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=loose-envifysymbol-observable nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=conf nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=ajvatomicallydebounce-fnjson-schema-typedmake-dirdot-propenv-pathsonetimepkg-up
                     nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules
                     round=0
  • unresolved deps  unresolved=semver nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=path-exists nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
  • unresolved deps  unresolved=p-limit nodeModuleDir=C:\Users\Wesley\Desktop\BayonetChat\Rocket.Chat.Electron-develop\node_modules round=0
```

### Current Behavior
electron-builder produces an installer and a win-unpacked dir, but running the installer or the unpacked exe result in nothing happening.

### Expected Behavior
rocket chat client to be ran.

**Comment by starhound** [comment]
Seems to be the same issue even when compiling on a Ubuntu system:

wesley@bayonetchat:~/Chat/Rocket.Chat.Electron$ yarn install
yarn install v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ run-s install-app-deps clean build
yarn run v1.22.4
$ electron-builder install-app-deps
  • electron-builder  version=22.8.0
  • loaded configuration  file=/home/wesley/Chat/Rocket.Chat.Electron/electron-builder.json
  • spawning        command=/home/wesley/Chat/Rocket.Chat.Electron/node_modules/app-builder-bin/linux/x64/app-builder node-dep-tree --dir /home/wesley/Chat/Rocket.Chat.Electron
  • unresolved deps  unresolved=stackframe nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=@bugsnag/coreerror-stack-parseriserrorstack-generator nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=once nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=debug nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=loose-envifysymbol-observable nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=regenerator-runtime nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=schedulerloose-envifyobject-assignprop-types nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=loose-envify nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=loose-envifyobject-assign nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=loose-envifyobject-assign nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=loose-envifyobject-assignreact-is nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=loose-envifyobject-assign nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=conf nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=atomicallyjson-schema-typedajvdebounce-fndot-propenv-pathsonetimepkg-up nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=path-exists nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=p-limit nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=hoist-non-react-staticsloose-envifyprop-types@babel/runtime nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=loose-envifyprop-types nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=react-is nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=regenerator-runtime nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=@redux-saga/deferred@redux-saga/delay-p@redux-saga/is@redux-saga/symbols@redux-saga/typestypescript-tuple@babel/runtime
                     nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules
                     round=0
  • unresolved deps  unresolved=@babel/runtime nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=symbol-observableloose-envify nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=symbol-observableloose-envify nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=@redux-saga/symbols nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=@redux-saga/symbols@redux-saga/types nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=once nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=oncewrappy nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=@babel/runtime nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=@emotion/memoize@emotion/utils nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=@emotion/hashbabel-plugin-macrosescape-string-regexpfind-root@babel/helper-module-imports@emotion/serializebabel-plugin-syntax-jsxconvert-source-map@emotion/memoize
                     nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules
                     round=0
  • unresolved deps  unresolved=@emotion/hash@emotion/serialize@emotion/memoize nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=@babel/runtime nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=import-freshpath-typeyaml nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=error-exjson-parse-better-errorslines-and-columns@babel/code-frame nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=@babel/helper-validator-identifierjs-tokens nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=js-tokens nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=escape-string-regexp nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=escape-string-regexp nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=color-convert nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=parent-module nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=@babel/helper-validator-identifier nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=@emotion/stylis nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=loose-envify nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=loose-envify nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=react-is nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=@rocket.chat/fuselage-tokens nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=object-assign nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=nanoid nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=lazy-vallodash.isequalfs-extrajs-yaml nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=debugsax nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=debug nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=graceful-fsuniversalify nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=graceful-fs nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=argparseesprima nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=@emotion/utils@babel/runtime@emotion/serialize nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=@emotion/stylis@emotion/utils@emotion/sheet nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=@emotion/serialize@emotion/utilsbabel-plugin-emotion nodeModuleDir=/home/wesley/node_modules round=0
  • unresolved deps  unresolved=js-yaml nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=js-yaml nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=minimist nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=html-parse-stringify2 nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=regenerator-runtime nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=regenerator-runtime nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=loose-envifysymbol-observable nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=loose-envifysymbol-observable nodeModuleDir=/home/wesley/node_modules round=1
  • unresolved deps  unresolved=loose-envifyobject-assignprop-types nodeModuleDir=/home/wesley/Chat/Rocket.Chat.Electron/node_modules round=0
  • unresolved deps  unresolved=loose-envifyobject-assignprop-types nodeModuleDir=/home/wesley/node_modules round=1
  • exited          command=app-builder code=0 pid=1032854 out=[{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules","deps":[{"name":"@babel/code-frame","version":"7.10.4"},{"name":"@babel/helper-module-imports","version":"7.10.4"},{"name":"@babel/helper-validator-identifier","version":"7.10.4"},{"name":"@babel/highlight","version":"7.10.4"},{"name":"@babel/runtime","version":"7.11.2"},{"name":"@babel/types","version":"7.10.5"},{"name":"@bugsnag/browser","version":"7.2.0"},{"name":"@bugsnag/core","version":"7.3.0"},{"name":"@bugsnag/cuid","version":"3.0.0"},{"name":"@bugsnag/js","version":"7.2.0"},{"name":"@bugsnag/node","version":"7.2.0"},{"name":"@bugsnag/safe-json-stringify","version":"6.0.0"},{"name":"@emotion/cache","version":"10.0.27"},{"name":"@emotion/core","version":"10.0.28"},{"name":"@emotion/css","version":"10.0.27"},{"name":"@emotion/hash","version":"0.7.4"},{"name":"@emotion/is-prop-valid","version":"0.8.6"},{"name":"@emotion/memoize","version":"0.7.4"},{"name":"@emotion/serialize","version":"0.11.15"},{"name":"@emotion/sheet","version":"0.9.4"},{"name":"@emotion/styled","version":"10.0.27"},{"name":"@emotion/styled-base","version":"10.0.27"},{"name":"@emotion/stylis","version":"0.8.5"},{"name":"@emotion/unitless","version":"0.7.5"},{"name":"@emotion/utils","version":"0.11.3"},{"name":"@emotion/weak-memoize","version":"0.2.5"},{"name":"@redux-saga/core","version":"1.1.3"},{"name":"@redux-saga/deferred","version":"1.1.2"},{"name":"@redux-saga/delay-p","version":"1.1.2"},{"name":"@redux-saga/is","version":"1.1.2"},{"name":"@redux-saga/symbols","version":"1.1.2"},{"name":"@redux-saga/types","version":"1.1.0"},{"name":"@rocket.chat/css-in-js","version":"0.13.1"},{"name":"@rocket.chat/fuselage","version":"0.13.1"},{"name":"@rocket.chat/fuselage-hooks","version":"0.13.1"},{"name":"@rocket.chat/fuselage-tokens","version":"0.13.1"},{"name":"@rocket.chat/icons","version":"0.13.1"},{"name":"ajv","version":"6.12.3"},{"name":"argparse","version":"1.0.10"},{"name":"at-least-node","version":"1.0.0"},{"name":"atomically","version":"1.3.2"},{"name":"babel-plugin-emotion","version":"10.0.27"},{"name":"babel-plugin-macros","version":"2.8.0"},{"name":"babel-plugin-syntax-jsx","version":"6.18.0"},{"name":"balanced-match","version":"1.0.0"},{"name":"brace-expansion","version":"1.1.11"},{"name":"buffer-to-arraybuffer","version":"0.0.5"},{"name":"byline","version":"5.0.0"},{"name":"callsites","version":"3.1.0"},{"name":"color-convert","version":"1.9.3"},{"name":"concat-map","version":"0.0.1"},{"name":"conf","version":"7.1.1"},{"name":"convert-source-map","version":"1.7.0"},{"name":"cosmiconfig","version":"6.0.0"},{"name":"csstype","version":"2.6.13"},{"name":"debounce-fn","version":"4.0.0"},{"name":"debug","version":"4.1.1"},{"name":"dictionary-de","version":"2.0.4"},{"name":"dictionary-en","version":"3.0.1"},{"name":"dictionary-en-gb","version":"2.2.2"},{"name":"dictionary-es","version":"3.0.1"},{"name":"dictionary-fr","version":"2.5.1"},{"name":"dictionary-pt","version":"2.0.1"},{"name":"dictionary-ru","version":"2.0.2"},{"name":"dictionary-tr","version":"1.3.4"},{"name":"dot-prop","version":"5.2.0"},{"name":"electron-hunspell","version":"1.1.2"},{"name":"electron-main-fetch","version":"1.0.0"},{"name":"electron-redux","version":"1.5.3"},{"name":"electron-store","version":"6.0.0"},{"name":"electron-updater","version":"4.3.1"},{"name":"emscripten-wasm-loader","version":"3.0.3"},{"name":"end-of-stream","version":"1.4.4"},{"name":"env-paths","version":"2.2.0"},{"name":"error-ex","version":"1.3.2"},{"name":"error-stack-parser","version":"2.0.6"},{"name":"escape-string-regexp","version":"1.0.5"},{"name":"esprima","version":"4.0.1"},{"name":"fast-deep-equal","version":"3.1.1"},{"name":"fast-json-stable-stringify","version":"2.1.0"},{"name":"find-root","version":"1.1.0"},{"name":"fs-extra","version":"9.0.1"},{"name":"fs.realpath","version":"1.0.0"},{"name":"getroot","version":"1.0.0"},{"name":"glob","version":"7.1.6"},{"name":"graceful-fs","version":"4.2.4"},{"name":"hoist-non-react-statics","version":"3.3.2"},{"name":"html-parse-stringify2","version":"2.0.1"},{"name":"hunspell-asm","version":"4.0.2"},{"name":"i18next","version":"19.6.2"},{"name":"i18next-node-fs-backend","version":"2.1.3"},{"name":"import-fresh","version":"3.2.1"},{"name":"inflight","version":"1.0.6"},{"name":"inherits","version":"2.0.4"},{"name":"invariant","version":"2.2.4"},{"name":"is-arrayish","version":"0.2.1"},{"name":"is-obj","version":"2.0.0"},{"name":"iserror","version":"0.0.2"},{"name":"js-tokens","version":"4.0.0"},{"name":"js-yaml","version":"3.13.1"},{"name":"json-parse-better-errors","version":"1.0.2"},{"name":"json-schema-traverse","version":"0.4.1"},{"name":"json-schema-typed","version":"7.0.3"},{"name":"jsonfile","version":"6.0.1"},{"name":"lazy-val","version":"1.0.4"},{"name":"lines-and-columns","version":"1.1.6"},{"name":"lodash","version":"4.17.19"},{"name":"lodash.isequal","version":"4.5.0"},{"name":"loose-envify","version":"1.4.0"},{"name":"mimic-fn","version":"2.1.0"},{"name":"minimatch","version":"3.0.4"},{"name":"minimist","version":"1.2.0"},{"name":"ms","version":"2.1.2"},{"name":"nanoid","version":"2.1.11"},{"name":"node-fetch","version":"2.6.0"},{"name":"normalize-path","version":"2.1.1"},{"name":"object-assign","version":"4.1.1"},{"name":"once","version":"1.4.0"},{"name":"onetime","version":"5.1.0"},{"name":"p-limit","version":"2.2.2"},{"name":"p-try","version":"2.2.0"},{"name":"parent-module","version":"1.0.1"},{"name":"path-exists","version":"3.0.0"},{"name":"path-is-absolute","version":"1.0.1"},{"name":"path-parse","version":"1.0.6"},{"name":"path-type","version":"4.0.0"},{"name":"pkg-up","version":"3.1.0"},{"name":"prop-types","version":"15.7.2"},{"name":"pump","version":"3.0.0"},{"name":"punycode","version":"2.1.1"},{"name":"react","version":"16.13.1"},{"name":"react-dom","version":"16.13.1"},{"name":"react-i18next","version":"11.7.0"},{"name":"react-is","version":"16.13.1"},{"name":"react-keyed-flatten-children","version":"1.2.0"},{"name":"react-redux","version":"7.2.0"},{"name":"redux","version":"4.0.5"},{"name":"redux-saga","version":"1.1.3"},{"name":"regenerator-runtime","version":"0.13.7"},{"name":"remove-trailing-separator","version":"1.1.0"},{"name":"reselect","version":"4.0.0"},{"name":"resolve","version":"1.17.0"},{"name":"rimraf","version":"3.0.2"},{"name":"sax","version":"1.2.4"},{"name":"scheduler","version":"0.19.1"},{"name":"sprintf-js","version":"1.0.3"},{"name":"stack-generator","version":"2.0.5"},{"name":"stackframe","version":"1.2.0"},{"name":"symbol-observable","version":"1.2.0"},{"name":"to-fast-properties","version":"2.0.0"},{"name":"tslib","version":"1.13.0"},{"name":"typescript-compare","version":"0.0.2"},{"name":"typescript-logic","version":"0.0.0"},{"name":"typescript-tuple","version":"2.2.1"},{"name":"universalify","version":"1.0.0"},{"name":"unixify","version":"1.0.0"},{"name":"uri-js","version":"4.2.2"},{"name":"use-subscription","version":"1.4.1"},{"name":"void-elements","version":"2.0.1"},{"name":"wrappy","version":"1.0.2"},{"name":"yaml","version":"1.10.0"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/babel-plugin-emotion/node_modules","deps":[{"name":"source-map","version":"0.5.7"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/color-convert/node_modules","deps":[{"name":"color-name","version":"1.1.3"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/conf/node_modules","deps":[{"name":"make-dir","version":"3.1.0"},{"name":"semver","version":"7.3.2"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/convert-source-map/node_modules","deps":[{"name":"safe-buffer","version":"5.1.2"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/cosmiconfig/node_modules","deps":[{"name":"parse-json","version":"5.0.1"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/debounce-fn/node_modules","deps":[{"name":"mimic-fn","version":"3.1.0"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/electron-redux/node_modules","deps":[{"name":"redux","version":"4.0.5"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/electron-store/node_modules","deps":[{"name":"type-fest","version":"0.16.0"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/electron-updater/node_modules","deps":[{"name":"builder-util-runtime","version":"8.7.0"},{"name":"semver","version":"7.3.2"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/i18next/node_modules","deps":[{"name":"@babel/runtime","version":"7.10.5"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/i18next-node-fs-backend/node_modules","deps":[{"name":"json5","version":"2.0.0"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/import-fresh/node_modules","deps":[{"name":"resolve-from","version":"4.0.0"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/pkg-up/node_modules","deps":[{"name":"find-up","version":"3.0.0"},{"name":"locate-path","version":"3.0.0"},{"name":"p-locate","version":"3.0.0"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/react-i18next/node_modules","deps":[{"name":"@babel/runtime","version":"7.8.3"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/react-redux/node_modules","deps":[{"name":"react-is","version":"16.12.0"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/@babel/highlight/node_modules","deps":[{"name":"ansi-styles","version":"3.2.1"},{"name":"chalk","version":"2.4.2"},{"name":"has-flag","version":"3.0.0"},{"name":"supports-color","version":"5.5.0"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/@redux-saga/core/node_modules","deps":[{"name":"redux","version":"4.0.5"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/@rocket.chat/css-in-js/node_modules","deps":[{"name":"@emotion/hash","version":"0.8.0"}]},{"dir":"/home/wesley/Chat/Rocket.Chat.Electron/node_modules/conf/node_modules/make-dir/node_modules","deps":[{"name":"semver","version":"6.3.0"}]}]
  • spawning        command=/home/wesley/Chat/Rocket.Chat.Electron/node_modules/app-builder-bin/linux/x64/app-builder rebuild-node-modules cwd=/home/wesley/Chat/Rocket.Chat.Electron

**Comment by starhound** [comment]
I believe I'm having the same issues that were described here: https://github.com/electron-userland/electron-builder/issues/3860 

But thats about all I can dig up so far.

**Comment by tassoevan** [comment]
> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json

Follow the tip given by yarn and, additionally, prune `node_modules/` and `dist/`, preferably via `git clean -xfd .`.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
