### ISSUE TITLE
Could flash window when new message incoming?

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat.Electron#1689]
## My Setup

- Operating System: Win10
- App Version: 2.17.11
- Installation type: exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
If new message incoming.It's only show notification.But if user not in seat. The user don't know somebody have send new message. How to fix it?

**Comment by ankar84** [comment]
You can check **Require Interaction to Dismiss Desktop Notification** option of users preferences
![image](https://user-images.githubusercontent.com/4023037/90236975-32c63800-de2c-11ea-9b89-5945a07d0340.png)
But it's only for web version for now.
And new unread message will be appeared in chatlist with number of unread messages in that chat. And name of that chat will be bold.

**Comment by akong77** [comment]
Thanks for your reply.
However, the user must always open the rocket.chat window or check the rocket.chat as soon as he gets back to his seat. This is really not ideal. If a new message comes in, it will flash in the taskbar. This should be a better way.

**Comment by tassoevan** [comment]
@akong77 Could you confirm if at least the notification counter (the badge above the server icon) is showing? If it's not, it maybe be a server-side issue.

**Comment by akong77** [comment]
@tassoevan Could you screenshot for notification counter?I don't know where is it.

**Comment by ankar84** [comment]
> @tassoevan Could you screenshot for notification counter?I don't know where is it.

Here it is
![image](https://user-images.githubusercontent.com/4023037/92088601-bfce3280-edd5-11ea-9375-9694e3d2d1c0.png)
And tray icon with notification
![image](https://user-images.githubusercontent.com/4023037/92088521-a75e1800-edd5-11ea-83b1-56962f3dd194.png)

**Comment by akong77** [comment]
OK, I found rocket.chat client Window --> Show unread message.I enable this.I can see rocket.chat flash.

**Comment by tassoevan** [comment]
Oh, now I get it: your window is not minimized, it's completely hidden. Ok, let's fix this.

**Comment by akong77** [comment]
Sorry, I found another question.If direct message is will flash window.But if new message coming to channel.It's not flush window.
I mean flush window like this.

![圖片](https://user-images.githubusercontent.com/6081927/92197099-659ba300-eea3-11ea-8304-f2e6d0ea8a35.png)

Please check it.

**Comment by ankar84** [comment]
> I mean flush window like this.

Look at this issues
https://github.com/RocketChat/Rocket.Chat.Electron/issues/628
https://github.com/RocketChat/Rocket.Chat.Electron/issues/618
https://github.com/RocketChat/Rocket.Chat.Electron/issues/693

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
