### ISSUE TITLE
Dark Mode hightlight cause post to be unreadable

### ISSUE THREAD

**Issue by rkesters** [RocketChat/Rocket.Chat.Electron#1697]
## My Setup

- Operating System: OSX
- App Version: 7.17.11
- Installation type: dmg

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Place the app in dark mode and then mouse over any post.
![Screen Shot 2020-08-24 at 1 28 54 PM](https://user-images.githubusercontent.com/5572145/91076707-e0e09780-e60d-11ea-9aeb-b708530a5744.png)

### Current Behavior
The post is changed to white and the text to a greyish. 

### Expected Behavior
The post changes to maybe a grey and the text to a white.

**Comment by tassoevan** [comment]
Rocket.Chat doesn't support dark mode in its core yet. Please check if you're having trouble with a third-party solution, like [pbaity/rocketchat-dark-mode](https://github.com/pbaity/rocketchat-dark-mode).

**Comment by rkesters** [comment]
This is a bit confusing, I'm using the app downloaded off the rocketchat website and it has a dark mode option. Hence how is this not included?

**Comment by tassoevan** [comment]
@rkesters It could have been configured at the Rocket.Chat server you're accessing through the desktop app. As this app is a Electron-based one, the center of the main window is the same interface you can see in a web browser. The server administrator may have patched its instance to show the dark mode toggle switch.
