### ISSUE TITLE
Notification shows pop-up instead of integrating with notify

### ISSUE THREAD

**Issue by giray** [RocketChat/Rocket.Chat.Electron#170]
## My Setup
- **My OS name and version**:  Ubuntu 16.03
- **My current app version**: 1.3.1
- [x ] I have tested with the latest application version
- [x ] I can simulate the issue easily
## Description

Desktop notifications show up as Pop-Up windows instead of integrating with Unity notify osd
#### Current Behavior

Pop-Up windows with "Cancel"/"OK" pops up

![image](https://cloud.githubusercontent.com/assets/316284/14456362/d72ad26c-00a4-11e6-8d39-9a393994cbb9.png)
#### Expected Behavior

Expect notification bubble ala;
![image](https://cloud.githubusercontent.com/assets/316284/14456579/e0ea0a4c-00a5-11e6-8d81-b44aae984fc7.png)
##

**Comment by xtian777x** [comment]
Same thing happening on Ubuntu 16.04LTS

**Comment by alfredbez** [comment]
I had the same issue on Ubuntu 16.04.

This fixed it for me:
```
$ sudo touch /usr/lib/libunity-electron_notification_fix
```
[source](https://github.com/electron/electron/issues/465#issuecomment-206582829)

You can also do `export ELECTRON_USE_UBUNTU_NOTIFIER=1`
[source](https://github.com/electron/electron/issues/465#issuecomment-214324870)

**Comment by xtian777x** [comment]
@alfredbez Thanks a lot! The first solution fixed this annoying bug :)

**Comment by cbajohr** [comment]
Thanks! 

`export ELECTRON_USE_UBUNTU_NOTIFIER=1`

... fixed it for me

**Comment by JordyMoos** [comment]
This did not work for me on ubuntu 16

**Comment by krisleech** [comment]
@cbajohr where did you put the `export` in your `.bashrc` / `.zshrc` file?

**Comment by cbajohr** [comment]
@krisleech right at the bottom of the file(s)

**Comment by engelgabriel** [comment]
Guys, can you please try again with the version `2.2.0`?

**Comment by graywolf336** [comment]
Confirmed it is fixed with the latest version, v2.2.0.
