### ISSUE TITLE
Rocket.chat-Client freezes and crashes under Ubuntu 18.04 with Mate GUI

### ISSUE THREAD

**Issue by pixxelspotter** [RocketChat/Rocket.Chat.Electron#1707]
## My Setup

- Operating System: Ubuntu 18.04.4
- App Version: 2.17.7, 2.17.9 and 2.19.11
- Installation type: .deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The client freezes(white screen) and sometimes crashes when working, the freezing sometimes stops after some minutes, sometimes the client crashes completely. We also use Version 2.17.7 under Ubuntu 16.04.6 with no issues.

### Current Behavior
The client freezes(white screen) and sometimes crashes when working, the freezing sometimes stops after some minutes, sometimes the client crashes completely.
Strace shows me this: (rocketchat-desktop:8912): libnotify-WARNING **: 11:09:28.919: Failed to connect to proxy
) = 111
### Expected Behavior
No freezes and crashes.

**Comment by ankar84** [comment]
> Failed to connect to proxy

I think you should investigate that

**Comment by pixxelspotter** [comment]
> > Failed to connect to proxy
> 
> I think you should investigate that

Its not the proxy(already checked that) , i have freezes when switching between chats and sometimes it even crashes and i have to quit it an restart it.

**Comment by tassoevan** [comment]
Any chance of this being a GPU-related issue? Check if running the app from command line with the flag `--disable-gpu` is in anyway different.

**Comment by pixxelspotter** [comment]
> Any chance of this being a GPU-related issue? Check if running the app from command line with the flag `--disable-gpu` is in anyway different.

Starting it with `--disable-gpu` fromthe commandline still produces this error: (rocketchat-desktop:1947): libnotify-WARNING **: 07:18:55.868: Failed to connect to proxy , the freezing got a little less oftenbut is still there and crashes i didnt notice by this time

**Comment by ankar84** [comment]
> I don't see where the proxy comes in.
> Could you tell me how to fix it?

Can you show me result of command `env | grep proxy` in your terminal?
And then try to add your Rocket Chat server address to `no_proxy` environment variable.

**Comment by pixxelspotter** [comment]
> > I don't see where the proxy comes in.
> > Could you tell me how to fix it?
> 
> Can you show me result of command `env | grep proxy` in your terminal?
> And then try to add your Rocket Chat server address to `no_proxy` environment variable.

 `env | grep proxy` shows an empty response
After adding it to the no_proxy env variable i still get: 
(rocketchat-desktop:4218): libnotify-WARNING **: 09:10:51.868: Failed to connect to proxy

**Comment by pixxelspotter** [comment]
With Version 3.0.7 it will only start while using the Disable GPU Setting.
Starting it without disabling the GPU it will remain grey and you cant do anything.

**Comment by pixxelspotter** [comment]
> 
> 
> With Version 3.0.7 it will only start while using the Disable GPU Setting.
> Starting it without disabling the GPU it will remain grey and you cant do anything.

@tassoevan can this be fixed in the next version that we can finally upgrade to the new OS version?

**Comment by tassoevan** [comment]
Interesting. I wanna make the disabling of GPU a persistent setting for situations like this one, but I wonder if this is related to the Electron version we're using.

**Comment by pixxelspotter** [comment]
@tassoevan I can't tell you if it related to the Electron version.
But fixing this issues is key for us, so we can finally update our systems

**Comment by paulopera** [comment]
We are facing the same problem both in Windows and macOS (less than windows but still) where on launch or randomly the RocketChat app window became grey/black and only with a force reload it came back. 
Disabling GPU also works to fix the problem and also launches the app faster too.
If I set the  --disable-gpu in the Windows launcher to test.
We're using it less on browsers and I can't remember if I saw someone complaining about it.

### My environment:
Version 3.12.1
Apps Engine Version 1.23.0
Node Version v12.18.4
Database Migration 218 (March 9, 2021 8:08 AM
MongoDB 4.0.23 / mmapv1 (oplog Enabled)
Commit Details HEAD: (f2817c056)
Branch: HEAD
