### ISSUE TITLE
Menus are blank (working) but blank

### ISSUE THREAD

**Issue by iGallina** [RocketChat/Rocket.Chat.Electron#171]
## My Setup

 -Windows 7: 
- 1.3.1: 

- [X] I have tested with the latest application version
- [ ] I can simulate the issue easily
## Description

When the application launches everything looks goods on the menus.
When I connect to server there is a refresh of some sort on the UI and the menus get blank, even the right click on the notification icon.
They work, fi I know where something is and click it, it works, but is all white.
#### Current Behavior

All links in all menus even the notification icon right click.
#### Expected Behavior

The names of the menus are ok, but the listings are blank, I expect to see something there.

During application load:
![image](https://cloud.githubusercontent.com/assets/62770/14471955/62ea6ade-00c7-11e6-8a2b-b7387676cee6.png)

After Load:
![image](https://cloud.githubusercontent.com/assets/62770/14471983/7dbead48-00c7-11e6-8563-c8574325858d.png)
##

**Comment by iGallina** [comment]
I'll try the mac version now

**Comment by iGallina** [comment]
Duh, mac centrilzes menus on OSX menubar, all great in Apple's Land.

**Comment by dvolpato** [comment]
I'm having the same here. Previous version (I was using 1.2.0, I guess) was working. After upgrading to 1.3.1, got the blank menus.
As a matter of fact, this behavior was also observed in the installation program. Lots of blank components, which appeared partially when I hovered over.

**Comment by alexbrazier** [comment]
@iGallina @dvolpato Are you still experiencing this issue with the latest version?

**Comment by alexbrazier** [comment]
Closing this, if its still an issue in the latest version then reopen
