### ISSUE TITLE
Volume of second Participant increases to 100% when third Paticipant joins to a Video Chat

### ISSUE THREAD

**Issue by D3rWolff** [RocketChat/Rocket.Chat.Electron#1714]
![User Volume in Video Chat](https://user-images.githubusercontent.com/70936754/92444015-971db280-f1b2-11ea-8f35-aa5b1257048e.png)

## My Setup
- Operating System: Windows 10 Pro Version 2004
- App Version: 2.17.11
- Installation type: exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
1. Start a new Video Chat (Total participants connected = 1)
2. 2nd participant connects to Video Chat (Total participants connected = 2)
3. Adjust Volume of second participant to about 25% (Total participants connected = 2)
4. 3rd participant connects to Video Chat (Total participants connected = 3)
5. Volume of 2nd participant is automatically adusted to 100%  (Total participants connected = 3)

### Current Behavior
The Volume of the second connected participant in a Video Chat is automatically adjusted to 100% when a third participant connects to the Video Chat. This only happens when a third participant connects to a Video Chat.

### Expected Behavior
The Volume of the second participant should not be adjusted

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
