### ISSUE TITLE
Add FR spell checker by default

### ISSUE THREAD

**Issue by bellegarde-c** [RocketChat/Rocket.Chat.Electron#1715]
## My Setup

- Operating System: Fedora 33
- App Version: Last
- Installation type: Flatpak

- [X] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
FR spell checker is not available. 

### Current Behavior
User need to install spell checker manually (after creating dictionnaries directory manually).

### Expected Behavior
Spell checker works out of the box

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
