### ISSUE TITLE
I have to open the desktop app multiple times to log me in 

### ISSUE THREAD

**Issue by mohammedragabsoftxpert** [RocketChat/Rocket.Chat.Electron#1716]
## My Setup

- Operating System: Ubuntu 16.04
- App Version: 2.17.9 and 2.17.11
- Installation type: .deb installation

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
Very randomly when i open the application (especially when i start up my laptop), the desktop app doesn't just open and log me in, but instead it keeps loading and loading forever, till i decide to close/ kill it and re-open it 2 or 3 more times

![image](https://user-images.githubusercontent.com/47364489/92507477-556b2700-f207-11ea-92fc-ceb42ddfc896.png)

### Current Behavior
Randomly needs multiple open/ close tries to log me in, without any error or log!

### Expected Behavior
Open directly and log me in from first time!

**Comment by stleitner** [comment]
+1 We have the same problem with Mac App-Store Version 2.17.9 connected to 3.6.2 Server.

**Comment by recounter7** [comment]
We are expecting the same issue on several computers with windows app version 2.17.11.

**Comment by recounter7** [comment]
This issue is still not fixed in the current version 3.0.7.
I don't understand why the removal of such bugs in the desktop client, which affect a lot of users, is not fixed.
Can someone from the developers give some feedback?

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
