### ISSUE TITLE
Hangs on connection to server and forgets avatar image

### ISSUE THREAD

**Issue by zhigarartem** [RocketChat/Rocket.Chat.Electron#1718]
I have a desktop client of Rocket.Chat (2.17.1) and have two different issues:

1. I have Rocket.Chat in startup on my Windows 10.
   And sometimes Rocket.Chat hangs on connection to server (after computer turned on).
   The current solution for me is to close application and start it again.
   This problem appeared recently (one or two months ago).

2. Rocket.Chat often forgets my avatar image. And every time I need to upload my photo as at the first time.
   This problem have become from the beginning of Rocket.Chat using.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
