### ISSUE TITLE
[bug] Desktop version shows not all integrations

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1724]
## My Setup

- Operating System: Windows 10
- App Version: 2.17.7
- Installation type: exe

- [ ] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
I have pretty much integrations and in Electron Application I have not ability to get all of them, but web version show all.
I think it's some kind of limits or something.

My integrations
![image](https://user-images.githubusercontent.com/4023037/93291629-43cbe580-f7ec-11ea-935b-6c80a43bb529.png)

### Current Behavior
Desktop version shows not all integrations
Web version shows all integrations

### Expected Behavior
Desktop version shows all integrations even if you have a lot of it.

**Comment by tassoevan** [comment]
This is odd, as integrations are totally a server thing. @ankar84, do you mind transferring this issue to the [server repo](https://github.com/RocketChat/Rocket.Chat)? It may be a bug at the web client itself.

**Comment by ankar84** [comment]
Hi, @tassoevan 
Sure, if you think, that is server side bug.
But web client show me all integrations when Electron did not.

**Comment by ankar84** [comment]
@tassoevan so strange. Today all integrations are shown in Electron application.
So, I think it was some temporary issue. I did try to Reset Application Data with no luck yesterday. But today it works fine. Maybe close-open helped, I don't know.
So, closing that issue.
