### ISSUE TITLE
Yarn release fails with UnhandledPromiseRejection

### ISSUE THREAD

**Issue by charaneval** [RocketChat/Rocket.Chat.Electron#1725]
## My Setup

- Operating System: Windows 10
- App Version: Node.js 12.x, visual studio 2017 tools, node-gyp
- Installation type: 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When i follow instructions from github notes and issue yarn release command its throwing following error. Release is not working
![image](https://user-images.githubusercontent.com/57132438/93336441-63dbc300-f845-11ea-82bd-d014f41f417c.png)

### Current Behavior
Yarn release failing with following error.
(node:3372) UnhandledPromiseRejectionWarning: Error: EBUSY: resource busy or locked, rmdir 'D:\RocketChat\Rocket.Chat.Electron\.dist'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Expected Behavior
It should release windows specific installer for rocketchat client.

**Comment by tassoevan** [comment]
Your command line and output looks related to `yarn-release`, which this project *DOES NOT* use. Also, currently at the `develop` branch we're invoking `electron-builder` directly (`yarn electron-builder --publish onTagOrDraft --x64`).

**Comment by charaneval** [comment]
Thank you, but it throwed another issue now. 

![image](https://user-images.githubusercontent.com/57132438/93348132-78bf5300-f853-11ea-981c-18e1676d3953.png)

**Comment by tassoevan** [comment]
@charaneval Strange. Have you invoked `yarn build` before `yarn electron-builder`?
