### ISSUE TITLE
Notification bubble not disappearing in a channel even after clicking inside of the "reply in thread".  

### ISSUE THREAD

**Issue by NotACreativeUsername** [RocketChat/Rocket.Chat.Electron#1727]
## My Setup

- Operating System: Windows 10 Enterprise
- App Version: 12.17.11
- Installation type: package

- [X ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

![Chat bubleblue](https://user-images.githubusercontent.com/71467594/93637392-28fb9b80-f9bb-11ea-8ac9-15a20b857821.PNG)

### Current Behavior

Bubble stays, very intermittent if this does happen. I don't find this happening in the web version, and after an hour or so it worked again.

### Expected Behavior

Bubble should disappear.

**Comment by ankar84** [comment]
Try pressing `Esc` button as a workaround

**Comment by Leepfrog1** [comment]
> Try pressing `Esc` button as a workaround

That worked, thanks for the work around!

**Comment by NotACreativeUsername** [comment]
This workaround no longer works sadly. Any update on this @ankar84 @tassoevan

**Comment by ankar84** [comment]
> This workaround no longer works sadly. Any update on this?

Probably it's new Threads implementation.
You need just open unread Thread and read it.

**Comment by NotACreativeUsername** [comment]
> > This workaround no longer works sadly. Any update on this?
> 
> Probably it's new Threads implementation.
> You need just open unread Thread and read it.

Sadly not the case. Its happening intermittently with 2.17.11 Windows 10 enterprise build 1909 and Mac OS, and also 3.0.3 Mac OS Catalina 10.15.7. going in to each chat, reading hit, and using the esc key doesn't make it go away. anything else to test/try?

**Comment by ankar84** [comment]
> Sadly not the case

What server version do you use?

**Comment by NotACreativeUsername** [comment]
> What server version do you use?

Version 3.6.3

**Comment by ankar84** [comment]
> Version 3.6.3

Yeap, I think it's definitely new Threads. My users complaining about the same.

**Comment by NotACreativeUsername** [comment]
> > Version 3.6.3
> 
> Yeap, I think it's definitely new Threads. My users complaining about the same.

Strange, I've hopped on the end users machine myself, clicked on every thread in a chat, hit esc every time, and its still not going away.

**Comment by NotACreativeUsername** [comment]
> > Version 3.6.3
> 
> Yeap, I think it's definitely new Threads. My users complaining about the same.

Would it go away if someone deletes the thread?

**Comment by ankar84** [comment]
> Would it go away if someone deletes the thread?

Maybe not https://github.com/RocketChat/Rocket.Chat/issues/18419

**Comment by NotACreativeUsername** [comment]
> > Would it go away if someone deletes the thread?
> 
> Maybe not [RocketChat/Rocket.Chat#18419](https://github.com/RocketChat/Rocket.Chat/issues/18419)

Perfect! I'll follow that thread more closely, thank you! @ankar84

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
