### ISSUE TITLE
Server Pane goes black

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#173]
OS: Windows 10
 App Version: 1.3.1

Using the app for a while, it'll just suddenly go black.  Only way to get it to come back is to goto View->reload application or restart the app.

This is related to the spellcheck stuff.  Compiling and completely removing the spellcheck library causes it to work.  From what i've seen this is a Windows only thing, and directly related to the spellcheck.  Something about it is killing the render thread.

You really have to use it for more then a few minutes to notice this behavior.

Some times you'll just minimize to tray after using for a while and come back and its black.

**Comment by hadarawhite** [comment]
I'm also having this issue. As requested in the support channel, I've attached a screenshot.

![capture](https://cloud.githubusercontent.com/assets/17689787/14590262/55a0914a-04c4-11e6-8c98-ef8f6efa0e57.PNG)

**Comment by frenchsquared** [comment]
My support team is having this is on windows 10.   8 computers on the same network. 
All have this issue. About every 10 min, the screen goes blank. Program is not usable for them. 

I also have 4 developers using windows not on the same network, not in the same location and they don't have the issue. 

Is there a way to turn off spell check?

**Comment by Sing-Li** [comment]
See all the linked tickets for scope of problem.

**Comment by RobertPratico** [comment]
This issue occurs for me on Windows 10 64 Bit using version 1.3.1.

Issue similar to https://github.com/RocketChat/Rocket.Chat.Electron/issues/150

**Comment by lunitic** [comment]
Adding my setup.

Sorry for posting in wrong ticket.. 

I have also notice this issue on one PC. The PC is a Win 10 64bit.
The PC has dual graphic cards
GTX 960 and a onboard Intel graphic card.

Both screens runs in 1920*1080

**Comment by danielcandea** [comment]
It happens to me on two different machines and some colleagues as well, all on Windows 10 64 bit.
I can't reproduce it as it seems to happen randomly.

**Comment by Sing-Li** [comment]
Very likely to be a problem of Chromium compositor GPU optimization.   

Can we please report some information on the Video Card hardware and Video driver version on the system(s) that have this problem.  Thanks.

**Comment by Sing-Li** [comment]
Good news.    Please help test this version with GPU optimization disabled. 

Please uninstall existing version, install this one, and run it for a few days on problematic system(s).

Please let us know if it solves the problem on those systems.

[installer for test solution to black squares problem](https://cdn-download.rocket.chat/build/rocketchat-v1.3.1-nogputest-win32-ia32.exe)

**Comment by OmsagroSylph** [comment]
@Sing-Li Testing https://cdn-download.rocket.chat/build/rocketchat-v1.3.1-nogputest-win32-ia32.exe

**Comment by rhires** [comment]
So far so good. Been about an hour now and not having that issue anymore.

**Comment by frenchsquared** [comment]
It seems to be working for my staff as well. 


Gordon French
Primal Health LP
Systems Architect
gordon@primalhealthlp.com

**Comment by OmsagroSylph** [comment]
Aye, so far so good.

**Comment by Lonewolff** [comment]
I have used it all day without a single black screen. The issue seems to be solved to me. Thanks for the fixed version!

**Comment by geekgonecrazy** [comment]
Looks like we found a fix.  Going to close this and track this on one issue.  Please follow / continue here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/150

**Comment by geekgonecrazy** [comment]
Just to close the loop:  Please download the new Windows installer from the release page: [here](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/1.3.1)

If you're seeing graphical glitches other then just full blackout try out the build @Sing-Li Posted: [GPU-Accel Disabled Windows Build](https://cdn-download.rocket.chat/build/rocketchat-v1.3.1-nogputest-win32-ia32.exe)

In the future we're going to add the option to disable into the main installer.  Please let us know if you have any issues here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/150

**Comment by samcarter8** [comment]
I had the same issue with the `Version 2.3.0 (2.3.0.261)` for mac OSX. 

![screen shot 2017-02-07 at 12 06 20](https://cloud.githubusercontent.com/assets/8226363/22689544/b85e3e30-ed31-11e6-8404-28d2ec2ff23f.png)

The screen would turn black as soon as I typed more then a few letters (`test` was OK, but `test ` already caused the problem)

![screen shot 2017-02-07 at 12 05 53](https://cloud.githubusercontent.com/assets/8226363/22689551/bfce3814-ed31-11e6-85ad-91d461754e9f.png)


On de-selecting all languages from `Spelling languages` it now works.
![screen shot 2017-02-07 at 12 24 30](https://cloud.githubusercontent.com/assets/8226363/22689532/afea42e4-ed31-11e6-96bb-f9a9e47cbf15.png)

**Comment by graywolf336** [comment]
@samcarter8 Update to 2.4.0 and see if there is an improvement, as there were some recent improvements to the spellchecker.

**Comment by samcarter8** [comment]
@graywolf336 Works with 2.4.0. Thank you for your fast reply!
