### ISSUE TITLE
Status description

### ISSUE THREAD

**Issue by corell82** [RocketChat/Rocket.Chat.Electron#174]
It would be nice to have "description" option to set my own description like "I'm on vacation" or something like this. It could be displayed on the top of conversation with other user.
##

**Comment by gdelavald** [comment]
I'll close this in favor of the [feature requets](https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20status)  on Rocket.Chat web repository, since this needs to be implemented in the client.
