### ISSUE TITLE
Link to open downloaded attachments

### ISSUE THREAD

**Issue by xi67** [RocketChat/Rocket.Chat.Electron#1742]
### Description:

When you get an attachment in a channel you can download it but after you have to go to the file location by yourself.
It would be very nice and natural to have a link button to open directly the file.

### Steps to reproduce:

1. Receive a file
2. Download it
3. Have to go to the file manually

### Expected behavior:

Have a link to open the file

### Actual behavior:

No link / button

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.2
- Operating System: Windows
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.14.0
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Desktop app 2.7.11
- Operating System: Windows 10

### Additional context

No additional context

### Relevant logs:

No relevant logs

**Comment by changlogi** [comment]
It will be very nice to have a link button or context menu named as "open" to open directly the file.

**Comment by Noidart** [comment]
Hey!
Please tell me if you managed to solve this problem? there is a lack of link support in the Windows desktop application.

**Comment by jeanfbrito** [comment]
This is solved on the Downloads screen. There is a link to each file now:
![image](https://user-images.githubusercontent.com/1177482/178825061-08c4e65c-c676-4abb-b594-987c4b6aabe1.png)
