### ISSUE TITLE
New v3 version doesn't connect with a valid server

### ISSUE THREAD

**Issue by lucianomlima** [RocketChat/Rocket.Chat.Electron#1743]
## My Setup

- Operating System: macOS Catalina v10.15.6
- App Version: 3.0.0
- Server version: 2.4.11
- Installation type: brew but update by inapp update system

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

After update to latest version get `No valid server found at the URL`

### Current Behavior
Can't connect to working server (I'm connected on browser)

### Expected Behavior
Connect properly to server like on mobile apps and browser.

**Comment by drdelaney** [comment]
Same here
Operating System: Windows 10.1909
App Version: 3.0.0
Server version: 2.4.9
Installation type:  exe from releases

**Comment by lucianomlima** [comment]
Reverting to v2.17.11 and works fine.

**Comment by drdelaney** [comment]
> Reverting to v2.17.11 and works fine.

Same here.  And my manager on a Mac.

**Comment by AmatorPhasma** [comment]
Same gere

Operating System: Windows 10 Version: 2004
App Version: 3.0.0
Server version: 3.6.3
Installation type: exe from releases over version 2.17.11

**Comment by AleMScof** [comment]
Same thing here.

Operating System: Windows 10
App Version: 3.0.0
Server version: 2.4.9
Installation type: exe from releases over version 2.17.11

**Comment by ankar84** [comment]
Confirm that issue!
Fixed that by creating valid `c:\Program Files\Rocket.Chat\resources\servers.json` file with my server in it

**Comment by maulikvora** [comment]
Same here

Operating System: macOS Catalina v10.15.6
App Version: 3.0.0
Server version: 2.4.11

**Comment by tassoevan** [comment]
Desktop app 3.0 pushed the compatibility to Rocket.Chat servers at the version 3.x, rejecting 2.x servers; it's probably a mistake. @AmatorPhasma Could you please double check your conditions?

**Comment by ankar84** [comment]
> Desktop app 3.0 pushed the compatibility to Rocket.Chat servers at the version 3.x, rejecting 2.x servers; it's probably a mistake. @AmatorPhasma Could you please double check your conditions?

I'm on 3.6.3 now and experiencing that bug.
I can workaround this issue only creating `servers.json` file with same server address which shows invalid on add server window.

**Comment by AmatorPhasma** [comment]
@tassoevan 
Yes, that server version is correct 3.6.3, but it only appears if my users don't write the protocol in front of the domain: 
- works: https://rocket.xxx.de 
- don't work: rocket.xxx.de (works with <= 2.17.11)

**Comment by mes85** [comment]
Same problem here: After upgrading the client on both my Windows and Debian mashine, I can no longer connect. Server version is 3.6.3.
I have tried with and without protocol.
I don't even see something in the nginx log on the server.

**Comment by XF9** [comment]
Same here. Removing the trailing slash or using http works though.

- don't works: https://xxx.de/
- works: https://xxx.de
- works: http://xxx.de

**Comment by AkimoA** [comment]
Can confirm with `servers.json` placed in 
~/Applications/Rocket.Chat.app/Contents/Resources/ 

 works again 
macOS Big Sur Beta 9 

for more Info and Syntax of servers.json -> [Here](https://github.com/RocketChat/Rocket.Chat.Electron#default-servers)

**Comment by amuller-AXT** [comment]
Thank you @AkimoA I've had to use a different path but creating a `servers.json` file with my company server URL did the job. 

I've had to create it here on my version of macOS Catalina 10.15.7 : 
`/Applications/Rocket.Chat.app/Contents/Resources/servers.json`

**Comment by plmorpheus** [comment]
Adding a space after slash is workaround ( https://rocket.server.url/_ )

**Comment by pdussart** [comment]
FYI: Both workarounds (trailing slash and/or space & servers-file) did not work for me. Reverted to 2.17

(macos 10.15.6)

**Comment by AkimoA** [comment]
u must have done something wrong then , `servers.json `workaround  works here on 10.14.x, 10.15.x, and macOS 11

**Comment by plmorpheus** [comment]
> FYI: Both workarounds (trailing slash and/or space & servers-file) did not work for me. Reverted to 2.17
> 
> (macos 10.15.6)

In my case I first put url without https:// and clicked connect and when app corrected the url with https and tell me that url is wrong, I added a space.
But I will also revert to 2.17 - version 3 is quite buggy at the moment - I noticed also problems with graphics, moreover app asks server's address every start, it hung twice on my computer... I thing this app should be in alpha or beta stage because of to these bugs.

**Comment by pdussart** [comment]
> u must have done something wrong then , `servers.json `workaround works here on 10.14.x, 10.15.x, and macOS 11

you're right. my bad.

**Comment by Nono-m0le** [comment]
Same here, can't access my server (using specific Port) like: https://sub.domain.com:4444 
Server in v3.6.3

But what if I don't have/find this `servers.json` ? What's the content on it ?
My client is installed (win10) on %appadata%\Rocket.Chat\ (and no "resources" folder there)

**Comment by Nono-m0le** [comment]
> @Nono-m0le Did you consult this? I didn't at first, and because of that I wasted everybodies time :)
> 
> https://github.com/RocketChat/Rocket.Chat.Electron#default-servers

Which mean I need to create the folder too?

**Comment by tassoevan** [comment]
Thanks @plmorpheus, I've found that the app fixes the typed URL but still uses it to check the server version - what obviously fails because there is no protocol in the URL.

**Comment by edgardleal** [comment]
To downgrade on ubuntu following the suggestion from @lucianomlima :

```
sudo snap refresh rocketchat-desktop --edge
```

**Comment by apaarfus** [comment]
> 
> 
> Desktop app 3.0 pushed the compatibility to Rocket.Chat servers at the version 3.x, rejecting 2.x servers; it's probably a mistake. @AmatorPhasma Could you please double check your conditions?

Is rejection of 2.x servers an intended change?  I didn't see this in the release notes for this build.

**Comment by MaciekBaron** [comment]
Thanks for addressing the issue, hoping it will be pushed as a hotfix soon!

**Comment by rostisluv** [comment]
server v. 2.2.0 still same problem with v. 3.0.1 client

**Comment by AkimoA** [comment]
confirmed  also on macOS

when entering server address it duplicates https:// 

workaround from yesterday still works

**Comment by ankar84** [comment]
It's not fixed yet really, @tassoevan 
![image](https://user-images.githubusercontent.com/4023037/94908178-fcab4900-04a9-11eb-8508-f94825de81f8.png)
That URL works perfect in Web version
RC Server version is 3.6.3
Paid Wildcard certificate

**Comment by LudovicVaudois** [comment]
Hi,

I found a wordaround which works for me:

Add the server Url into the config.json located in c:\windows\users\user\AppData\Roaming\Rocket.Chat like this:

{
	"__internal__": {
		"migrations": {
			"version": "3.0.1"
		}
	},
	"currentServerUrl": "https://yourserver.com/",
	"doCheckForUpdatesOnStartup": true,
	"isMenuBarEnabled": true,
	"isShowWindowOnUnreadChangedEnabled": false,
	"isSideBarEnabled": true,
	"isTrayIconEnabled": true,
	"rootWindowState": {
		"focused": false,
		"visible": false,
		"maximized": false,
		"minimized": false,
		"fullscreen": false,
		"normal": true,
		"bounds": {
			"x": 460,
			"y": 240,
			"width": 994,
			"height": 594
		}
	}

Add it in our config made the authentification pass with success. Hopes it will help and still look for the client or server hotfix.

**Comment by UnnamedHero** [comment]
Confirm bug in 3.0.1 from Ubuntu snap package

**Comment by rostisluv** [comment]
@UnnamedHero you can install 3.0.2 from latest/edge, works fine for me

**Comment by KamilTancula** [comment]
Confirm bug in 3.0.2 for https URL. 
Fix by add file `servers.json`

**Comment by kalsan** [comment]
The `servers.json` fix does not work on snap installed instances because the snap is installed in a readonly FS and cannot be adjusted.

**Comment by LudovicVaudois** [comment]
> 
> 
> The `servers.json` fix does not work on snap installed instances because the snap is installed in a readonly FS and cannot be adjusted.

the servers.json file is intended to be added on client side, not on server, it works on our RC installed on snap/ubuntu

**Comment by kalsan** [comment]
Yes it's the client I'm talking about ;-) I'm unsure if I understand you correctly - is the RC on snap workaround something that "end users" can reproduce or are you talking about a staging version in a development setup?

**Comment by LudovicVaudois** [comment]
No problem :) we are using a Rocket Chat server in production environment, the server is a snap in Ubuntu. Onto clients, we add the servers.json to avoid server authentification process and it works fine, tried on w7 and w10. Hopes my english is clear, thanks RC team for support 




Ludovic VAUDOIS 
Responsable informatique 
ESAD de Reims 

tél. : 03.26.89.42.76 

www.esad-reims.fr 
----- Mail original -----

De: "Sandro Kalbermatter" <notifications@github.com> 
À: "RocketChat/Rocket.Chat.Electron" <Rocket.Chat.Electron@noreply.github.com> 
Cc: "LudovicVaudois" <lvaudois@esaddereims.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Lundi 5 Octobre 2020 12:25:20 
Objet : Re: [RocketChat/Rocket.Chat.Electron] New v3 version doesn't connect with a valid server (#1743) 



Yes it's the client I'm talking about ;-) I'm unsure if I understand you correctly - is the RC on snap workaround something that "end users" can reproduce or are you talking about a staging version in a development setup?

**Comment by borisBelloc** [comment]
same problem here, don't you have a beta version ? 
How can this bug go public 😥

**Comment by jkpatel1463** [comment]
> Same here
> 
> Operating System: macOS Catalina v10.15.6
> App Version: 3.0.0
> Server version: 2.4.11

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743#issuecomment-701660331

**Comment by jkpatel1463** [comment]
We can fix issues by downgrading client version to 2.17.11

@lucianomlima Thank you

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743#issuecomment-701660331

**Comment by plmorpheus** [comment]
> We can fix issues by downgrading client version to 2.17.11
> 
> @lucianomlima Thank you
> 
> [#1743 (comment)](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743#issuecomment-701660331)

I agree. The best solution at this moment is to remain at 2.17.xx version when you have production environment. I think that v3 will be soon patched but until then it shoul be used only for testing purposes.

**Comment by lucianomlima** [comment]
Follow-up: here I'm using v3.0.2 without issues.

**Comment by chefino** [comment]
Same problem here. Tried server 3.6.0 and even upgraded to 3.7.0, can't connect. Using same URL via web browser works fine.

![image](https://user-images.githubusercontent.com/4114876/95436700-6e750e00-0954-11eb-845a-17badab1f5ec.png)

Using client 3.0.2 on Windows 10 Pro 2004

**Comment by ankar84** [comment]
As I know, all that problems will be resolved in 3.0.3

**Comment by mortac8** [comment]
Hosed here on 3.0.2.  Where can I find an example servers.json?

**Comment by ankar84** [comment]
> It's not fixed yet really, @tassoevan
> ![image](https://user-images.githubusercontent.com/4023037/94908178-fcab4900-04a9-11eb-8508-f94825de81f8.png)
> That URL works perfect in Web version
> RC Server version is 3.6.3
> Paid Wildcard certificate

Problem with my server completely fixed in 3.0.3 version

**Comment by FrankDaze** [comment]
All that is not working for me on Mac Catalina

**Comment by AkimoA** [comment]
> All that is not working for me on Mac Catalina

it doesnt really hurt if you define a bit more in depth  what your problem is and how u went about it to fix it 

die you create a servers.json  did you put it in the right  place  ?

**Comment by FrankDaze** [comment]
Sorry, I wrote my comment in haste. It's working now. Was my mistake. I made a servers.js instead of servers.json file.

**Comment by zenhighzer** [comment]
I have similar issues: 
Rocket-Chat-Server / nginx (both on raspberry pi) with self-signed CA and certificates

- iphone: Browser and App: HTTPS -> No Problem 
- Desktop: Linux Mint 19.1 Tessa: Browser: HTTPS -> No problem
- Desktop: Linux Mint 19.1 Tessa: App / snap version 3.0.1 -> No valid Server
- Desktop: Linux Mint 19.1 Tessa: App / deb version 3.0.4 -> ERR_CERT_AUTHORITY_INVALID

**Comment by tassoevan** [comment]
@zenhighzer Could you create a new issue describing the `ERR_CERT_AUTHORITY_INVALID` in more detail, please?

**Comment by tabletenniser** [comment]
Still encounter the same "No valid server found at the URL" issue with:
Client version: 3.0.3 on Mac BigSur 11.1
Server version 1.3.2 (cannot upgrade due to https://github.com/RocketChat/Rocket.Chat.Embedded.armhf

Manually creating server.json file under /Applications/Rocket.Chat.app/Contents/Resources/servers.json bypasses the issue, but is it possible to update the client side on Mac Desktop to not have the check?

**Comment by hubertnnn** [comment]
Since the bug still have not been fixed, here is a workaround for ubuntu/snap version of RocketChat:

Edit file `/home/<username>/snap/rocketchat-desktop/current/.config/Rocket.Chat/config.json`
The servers key will probably be an empty array looking like this:
```
{
    ...
    "servers": [],
    ...
}
```

Replace it with following code (Make sure to replace `rocketchat.example.com` in my code with the url to your rocketchat instance):
```
	"servers": [
		{
			"url": "https://rocketchat.example.com/",
			"title": "Rocket.Chat - https://rocketchat.example.com/",
			"lastPath": "https://rocketchat.example.com/channel/general",
			"badge": 141,
			"style": {
				"background": "rgb(47, 52, 61) none repeat scroll 0% 0% / auto padding-box border-box",
				"color": "rgb(158, 162, 168)"
			},
			"favicon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAOtUlEQVR4Xu1dCXAUVRr+/p6BBCKERcIhJCTdPYkHgpaopSsq3uuJlKIlpW7JikdpyZaoi3jrUuutyKqIVykoKwpoAM+SuCKriJxyZKbfJIQoEETMAeSafluvDTEhM91vTjph/qqpCeR///+9/8vrd/3vNSEtrooAuQpNGgzShLjsjyBNSJoQl0XAZXDSLSRNiMsi4DI4MbWQiqKiIxpCoTxPKGQqXm9ts2nWeUKh2vzy8loCQi6rY6eC40iI3+c7WTHNczhwDoC8lo/XppZ+DvwAYLWH8w2NprnxqPLy8k4VlYMItgMhGwsKhnbzeEZxzkcRcCaAwgTg+5KAuc1e79wjS0trE2Cvy5poJWTrkCE99mVkTCVgarJqS8AWTjTXSzS3IBBYkyw/ndluKyEBTfsQwKUpqwzR+8T5izpjS1PmsxM4avfIMjRtBQdOTDHuad5Q6NGC8vL6FPt1pbsOfUhAVb8F0ckpRUu0QjHNR7VgcFFK/brQWdhRVkBVN4HoyFTjJWCazljS+rBU1ycWf2EJMTStPwdWAzgiFqNxlSF6XTeMiYfqfCbiPISp6kgTKAFRVlwBjqEwB5Zwj2dikd//U9viAV3vbYZCBV6iwSGi/gByFCBHfJtAfwXgnKiKc75TAarEzwCsj6koVYW9elXRDz80xQApZUVsJ4ZMVceaRB+kDE17R6s48DUB+RwoEN8AeicAyyYCVnCiFcT5mvqMjHXDNm6sS4DdhJhwnKkHdP1ZcD4pId7cacSEIAhY4+F8bTPnq4rKylYcLKiOhJTl5/dpVpSlIDruYIFMtV/RMgEUc4+nuMjv35xK/46ECDClmjZGARakEphbfHFgsSDH9HqLjywt/TnZuKQIESACqvoeiK5MNiC32ueA6GeKOeezi4LBJcnCKU2Iv6DgdFKUr5IFpDPZ5cBcBZihM/ZNonFLE2K1Ek2bBeBviQbRWe1x4BUP5zO0YHB9ouoQHSG6fi04fytRzruInX0EzGg0zX8fXVa2Jd46RUVIsKCgKKQoKR117K+gJycHGYWFUHr3tj6elm8lO7v1Z6Fr1tQgVFMDs7r6j5/Fv2tq0FBaitAvv8Qbs0jldxDwT52xF+JxEBUhLY+t7QAGxOPUqazSqxcyhw9HxrHHImPYMGQOGwbvkCFOxaR+31xZifq1a1G/fj0aN29Gw+bNiSbpPwTcpzNmSAE6QCkWQsT+hdhJTKhkHHMMskaPRs/TT7dIoO7dE2rfzpggZd+332Lv0qXY+01C+umtnPN/FAaD70RbiYNKSHdd/52E0aPR46STosWeFP1Gvx97BDFLl2LfypXx+eB8ii8Y/Fc0Rg4KIb2vugqHXXABeo4aFQ3WlOs2rF9vkVM9Zw5Cu3bF5N/k/OGiYPAh2cIpJaTXmDHIHj8emccfL4vPFXrNP/1kkSI+5p49UWMiYLLO2NMyBaMiJKCqk0D0rIzhtjqiNQgiepxySrRFXaXfGAyipoUY3twcHTaicT7DmOdUSJqQgKqOB9FsJ4Ntfy9GSX3vuANZZyZ8DBANjITrNmzciN9eew21H4q8kChEghQpQgK6fh44F94zZd1nnXsuBjzxBMQQtqvK7hdfxK5nnommerVcUc4tDAS+i1TIkZCArh/fQkaurOfs665DzgMPyKp3ar26zz7D9ltvjaYOJXpu7rlUUhL2medIiF/TFhNwoazHQTNnIuvss2XVu4ReI2OoOP/8aOrytI+xyeEK2BIS0PUrwfl7sp50I6bJqax51+sZui6PkWi0zzBKDixgT4imSc/K8z7+GN19PnlAXVCzYcMGbL3sMtmafeRjrINyREL8mvZXAt6QsT7w+edx2EUXyah2eZ2aefNQNWWKXD2JrvUZRruRqx0hK0girbTvbbeh76SunAMhF9u2WrtnzcKuxx93Lki0wmcY7bJEIyXK/UXkRjlZzDrrLAx65RUntUPy979Onw7xcRJummcUlpX9d79eWEL8mjadgNudjAkyBClp6RiB5qoqVI4ZA/FtJxx4qpCxu2wJCWjaTgD97AylW4fzn6FMKyGgVGesNY+6QwspVdULFSKR+mIr6dbhFCFYrUOmlRAwUmdMHAPseJNDQNPmArgq2a1j79dfo371ajT8+CO65eVZm1JiEZIypVdnLIiNpaXWppJYKqcePZA5cqT1GPX06eMcsTYa5t691tpUvdgD8XqROWKE9REbZ/GIZCu5SWfM6ow7tBBD09ZyYLgdiH73348+118fM87qt97Czkce6VC+29ChGPjCC8g4+mgp23uXLbOWLUQw24q3f38cfs896CU5J6hftQpVU6eiMRBoZ0fsWvabMgXZ114rhSeckszcRGSvFDJ2U6QWInohkVEeUeJ5XG27+Wbs+eIL2wrmL18OEVQ7qX77bex8+GFbnSPefBM9TzvNVqfu44+x/Xb78YuMnUhOxP5JcMQIWwwELNMZs3br2rUQDngMTXNc6B/6xRfoli+S0aOTmvfeQ9W99zoWchowiL+6yiuvBG9stLWl9OyJIfPmoXtRUUS9iosush57diJjx678lrPPRtMW2wyhH32MHduBkNLCwsFKKFRpZ5wyMqBt2OAY1HAKOyZPRu3ChVJlcxcutPqVcFL9zjvYKbmaPODZZ9HrkkvC2hHJDVsvvlgKT79770WfG26Q0j1Q6ecJE7D3K9ukz0ofY9ZqersWsllVR3qIvrfz2r2wEHlLHOeMYU2Un3EGxHaojPR/7DH0vvrqsKo77rkHtR/IHVsRfUCfCRPC2qmZPx9Vd98tA8ciVZAbi4j+UvSbNlLnY8zaOIqaENHh5n70USy4kCYkYtiafIxZeU/tCJF5ZHkOPxwF30Xc8LIlKv3IihieHT7GBnYgRLZTV9etg+joopV0px4xYpt8jFlj/Q7zkICmOQ578z75BCLJLRZJD3vDRu0bH2PW+DymieGgWbOsjMNYJT0x7BC5V32M3RiphTgunRx28cUY+NxzsfJhldu7fDmat29HaMcOKH36wJuTY03iYlk6afD7EaqqAnXrBu+gQcg88cSYlk7E0LR52zZAUeAdMOD3JZ14l05mzMCvDrEygduLGJsRlhDZxUUx0pJd4oiLuU5cWByB2HrppWiqtJ3aweR8VFEwuCwsIeI/ZZbfxdhejPHTEjkCv73+On6ZNs02RBzY1ZiRkb//rHzMG1Sefv0w5P330S1B5za6GrG8qclqHQcuWHaoJ9EbPsNoXQKIawtXrKYOeFoqh7irxduxPtXvvoud99/vqEfAWJ2x1iPncSc55DzyCLKvucbR8aGksOfLL61tAYmEbFaZm3vk6DZZjHGnAXn69sXg2bMh1rjSAogsxsorroBZ63y1JAF36Yw91TZuCUmUE4nVA6dPt4adh7qUn3qqY2JDS4xKfIx1mMwlLJVUHEkb8OST8A4efMhyIrHv8UdsiC7wGcanBwYrocnWYtNqwFNPIfO4Q+aemtZ4br38cmtfX0qInvMZxt/D6ToSIi4y40SLuORRaCUry2opWeedJ4WtsyuJncDKcePkzyByvsZrmqMLyst/i4kQUSjai8x6jR1rHdbp6iJGU9smToyqmiZweRFjEbdNHVvIfm9MVSeZkucLxR523mLH1K6oKuI2Zen83TbAZU7kShMi7AZ0/RlwHvbZd2DA1NWru+Rxttr5863TuOI2iGhEhgxhLypCLFIkz4wMnjMHPU5O7fW/0QQoWt26JUssIvbFsltK9IHPMK6Q8Zk0QnKLi5Fx1FEyGFytI/oJQYRD1ohdHcIezIlUIGmE5JeUJOzCmFQzJu492X+9hjibHqscmNkuYydphKirVlnXKHUWEXnG+0lo2LQpXthbQTTVZxhvR2soekJUNQiiAidHsRwArV2wADvuusu6eqPtxzvQSshImIg7s0SnLDIgRbKcuKapqaIiUfZTdz3Tpvz8fK/HU+aEXKxtDXrpJSe1dr/fT0a4QiKTPaMlG731wjJxcVl29u8XmrX8LMo6XWAmZtMJDH5buDsJeDSlF5gxVb3GJJrjFOn+06ah97hxTmqtvxePim03Wnv8nVM4fxGK8ozPMFi8FYjqkeXXtJkEOE5No0nGFsPIn8aPj7ceB6v8R+IynnDnzWMFJE2IoWkncMDxRi+xsCi2dmWkbvFibL/jDhlVt+msaiEiqst4ZCohTYhs65A9zLN75kzsevJJGYxu0mEgehWAaBUNyQAmRYhs6xA5UXmLFlmdbCQRj6jdL78McaStk8hOEBUT58UaY8XJfq+JLCELODDGKYB/uuUWHH7nnWHVRG5S9ezZ+O1V8QfmemkA58VEVNytqal4aEXF7lQhdiRE9hY5sX2bu2gRumtaO+x7Pv8cdZ98grpPPwWvd+97vziwjoC14t0iimkWqwm4FDkWEm0J8ft8x5FpigtoHI+0isM1OffdZx3dEssNIh9JECFu+YxRxHm1AIjywXmi3/KzBZyvICLxYpd1nlBorVpWtiNGnAktFpEQpqrZIaJFBNifmmyBI1Z2BQmhX3+NGyABFZxo4v495+3Dh2fV7dlTwIlUbpoFJF53RNRTEMWJshTOe4pvcC5ezlINoMb65ryGt/m3B6gmzn90S/DDBSoiITLn1eOOfBgDHPje6/HcqPr90W04JAPMQbAZKZVUagKYcLycFzeY5sRh5eXiOvNDUsKdD3mCA62XoaQoKo0ceKyQsUdT5M+1btqfMVTVhxSiB1OJlsQr8oge8xnG/1Lp162+WgkJqOqDIJK+EjsBFRLL+DN8hhHbWeMEAHCjiVZCDE07iwPiApPrkghULDcsJGABJ1qYrOWHJOJPuukOfYh4aUuzolxGv7/K+8+JQMCBZUS0wCRaWBQIxL4nmggwLrdhOzFkqipS2k8wiU4Q3wDyWj5e23pxvgaKUgLTXOnhfKVaVmZ/mYjLg5RKeI5LJ+HAVBQVHdEQCglyOlxulVlfvy63sjL+2WEqo+AiXzER4iL8XQ5KmhCXUZomJE2IyyLgMjjpFpImxGURcBmcdAtxGSH/B8P8+bBwIPqQAAAAAElFTkSuQmCC",
			"failed": false,
			"webContentsId": 3
		}
	],
```

**Comment by frdrchsps** [comment]
kind of hard to believe that this is still the same with current version 4.1.0
