### ISSUE TITLE
v3 application starts minimized by default.

### ISSUE THREAD

**Issue by shinebayar-g** [RocketChat/Rocket.Chat.Electron#1745]
## My Setup

- Operating System: Debian 10
- App Version: 3.0.0
- Installation type:  amd64.deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Just updated to 3.0.0. Every time  I open the app, it starts minimized by default. I had to right click on rocketchat icon from panel bar and click on **Show** to use the app.
### Expected Behavior

When I launch the application, it start normally and doesn't start minimized by default.

**Comment by AmatorPhasma** [comment]
Same here

Operating System: Windows 10 Version: 2004
App Version: 3.0.0
Server version: 3.6.3
Installation type: exe from releases over version 2.17.11

**Comment by ankar84** [comment]
Confirm that bug.

**Comment by tassoevan** [comment]
Probably the same root cause of #1744
