### ISSUE TITLE
Windows Client

### ISSUE THREAD

**Issue by HassbergKliniken** [RocketChat/Rocket.Chat.Electron#1748]
## My Setup

- Operating System: Windows 10
- App Version: 2.17.11
- Installation type: exe

Client reports that a new version (3.0) is available. This version is not in the Microsoft Store. How do you get the new version?

Best regards.

Jörg

**Comment by urosino** [comment]
Check:
https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by homberger** [comment]
Better wait some days. I just installed it and all configured servers are lost.

**Comment by urosino** [comment]
> Better wait some days. I just installed it and all configured servers are lost.

I confirm. You need to re-enter all your credentials.

**Comment by berndlackinger** [comment]
i confirm too: server list does not get saved

**Comment by esron** [comment]
My install is not finding my server.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
