### ISSUE TITLE
Chat pane goes black after a period of time

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat.Electron#175]
Chat pane goes black after a period of time, clicking on reload app fixes it for a while but will eventually go black again after inactivity.

**Comment by Megatronic79** [comment]
seems related to

https://github.com/RocketChat/Rocket.Chat.Electron/issues/173

**Comment by Sing-Li** [comment]
@Megatronic79 - which video card and video card driver version are on the system(s)?   tia

**Comment by Megatronic79** [comment]
Windows 10
Nvidia Quadro FX1800
9.18.13.4195

Windows 10
Nvidia Geforce GT 335M
9.18.13.4192

reported in the other ticket this can be merged.

**Comment by Sing-Li** [comment]
Please help test this version with GPU optimization disabled. 

Please uninstall existing version, install this one, and run it for a few days on problematic system(s).

Please let us know if it solves the problem on those systems.

[installer for test solution to black squares problem](https://cdn-download.rocket.chat/build/rocketchat-v1.3.1-nogputest-win32-ia32.exe)

**Comment by geekgonecrazy** [comment]
We've got issues for this all over the place.  Lets consolidate on this ticket: https://github.com/RocketChat/Rocket.Chat.Electron/issues/150  Thanks!

**Comment by geekgonecrazy** [comment]
Just to close the loop:  Please download the new Windows installer from the release page: [here](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/1.3.1)

If you're seeing graphical glitches other then just full blackout try out the build @Sing-Li Posted: [GPU-Accel Disabled Windows Build](https://cdn-download.rocket.chat/build/rocketchat-v1.3.1-nogputest-win32-ia32.exe)

In the future we're going to add the option to disable into the main installer.  Please let us know if you have any issues here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/150
