### ISSUE TITLE
Rocketchat 3.0.0 exe installer overwrites servers.json

### ISSUE THREAD

**Issue by sandreddu** [RocketChat/Rocket.Chat.Electron#1751]
My Setup

- Operating System: Windows 10 1909
- App Version: 3.0.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Rocketchat 3.0.0 exe installer overwrites servers.json
App installed version: 2.17.11 (all users)
Run exe installer (all users) for 3.0.0

### Current Behavior
At first start of 3.0.0 , we are prompted to enter a server to connect to.
If entered the server url, we are asked for authentication

### Expected Behavior
servers.json should be preserved in the resources folder and users should keep connecting to their server at the start of 3.0.0
Ideally, they should not be asked to login again

**Comment by Nimbusaro** [comment]
Same here. Windows 10 1909, rocket chat 3.0 installed with exe.
I'm prompted a server to connect to, and the setting is lost when you close rocket.chat (you are prompted to enter the server again when you open rocket.chat)

**Comment by ankar84** [comment]
Confirm that

**Comment by marcosmolina90** [comment]
I confirm. You need to re-enter all your credentials.

**Comment by Arnall** [comment]
I confirm that each time you quit Rocket Chat v3 you have to enter the server again in the next session...

**Comment by Medicate117** [comment]
I can confirm the behaviour from OP aswell. Once the server is choosen and logged in, it presists so far.

**Comment by krikk** [comment]
the servers.json works in the 3.x release, it only has the "unexpected" behaviour that it wants to add another server, even if you already have one defined in servers.json file

![image](https://user-images.githubusercontent.com/5165445/95593463-07d21c00-0a4a-11eb-98ef-5851084ae708.png)
see the image above, server is there, but not selected... if you select the bubble you see the login prompt:
![image](https://user-images.githubusercontent.com/5165445/95593702-4f58a800-0a4a-11eb-8792-8921358ed4e3.png)

the default selected server on first start should be the one defined in servers.json

**Comment by sandreddu** [comment]
Hi @krikk , I'm aware of the fact that the server.json works if you add it manually, but the point of my ticket is that the exe installer (at least in version 3.0.0, I honestly stopped testing after that) **overwrites an existing one**, with the result that if you had a working server.json with release 2.7.11 and install 3.0.0, there goes your no server.json. You can understand how this is a major pain in a business environment where we have 100+ users who would suddenly scream that "the server has disappeared". At the moment, we are holding back the rollout of v.3 because of this and the client certificate problem which renders our video call system unusable.

**Comment by ankar84** [comment]
All true!

> You can understand how this is a major pain in a business environment where we have 100+ users who would suddenly scream that "the server has disappeared".

I would advice you to test first.
I'm now testing every new RC desktop version until it get satisfying quality.

**Comment by sandreddu** [comment]
@ankar84 sure I tested it, that's why it was not rolled out yet. Mine was just an hypotetical scenario ;-)

**Comment by sandreddu** [comment]
Seems like it's working ok in version 3.0.4. Thank you!
