### ISSUE TITLE
3.0 crashes on specyfic user private message

### ISSUE THREAD

**Issue by JackiMode** [RocketChat/Rocket.Chat.Electron#1752]
## My Setup

- Operating System: Win 10 version 2004
- App Version: 3.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
3.0 crashes on specific user private message when window is in background

**Comment by Yanonix** [comment]
I confirm it also in Ubuntu 18.04 with snap latest/stable 3.0.0
Even if the windows is open, but not focus. It closes when receiving a new private message (I see the notification, and then the app close)

**Comment by pompi-stefana** [comment]
Hi, I had the same problem, but workaround it by disabling the "Show on unread messages" option from the "Window" menu. 
At least this solved the issue on my PC.

**Comment by tomboe311** [comment]
same here with Ubbuntu 20.untu 20.04.1 LTS and Version 3.0.1

**Comment by tassoevan** [comment]
Folks, have you all `Window > Show on unread messages` checked?

**Comment by Yanonix** [comment]
> Folks, have you all `Window > Show on unread messages` checked?

Yes, I have

**Comment by tassoevan** [comment]
Is it still happening at the current version?

**Comment by pompi-stefana** [comment]
> Is it still happening at the current version?

On 3.0.2 this didn't happened anymore. Didn't got the chance to check this on 3.0.3.

**Comment by JackiMode** [comment]
> 
> 
> Is it still happening at the current version?

Looks good in 3.0.2 and 3.0.3
