### ISSUE TITLE
Video call with Jitsi with client certificate authentication does not open

### ISSUE THREAD

**Issue by sandreddu** [RocketChat/Rocket.Chat.Electron#1754]
My Setup

- Operating System: Windows 10 1909, Mac OS X 10.14
- App Version: RocketChat 3.0.0
- Installation type: exe on Windows, DMG on Mac

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
We use an own Jitsi server where client certificate authentication is configured
When starting a video call, the window pops up to select a client certificate
We select the correct client certificate, and then nothing happens
On browser and on version 2.17.11 it works without problem

### Current Behavior
Nothing happens, neither on Mac nor on Windows

### Expected Behavior
Videoconference with Jitsi starts in the same client window

![image](https://user-images.githubusercontent.com/47738900/94793839-5ee94880-03db-11eb-93f1-bf805c895341.png)

**Comment by hogthrob** [comment]
We have the same issue, Jitsi with certificates worked perfectly using the 2.17.x client but stops working on 3.0.x 
This is a stop working condition for us and we have to downgrade to 2.17.x. We are also facing #1781 btw,

**Comment by sandreddu** [comment]
I can confirm the same behavior with 3.0.1, 3.0.2. At the moment we rely heavily on the video call function and cannot update

**Comment by bug** [comment]
I have that at login (Rocketchat server using certificate based auth) too with all 3.x releases: one single client crt in the client, it gets shown, hit select and auth never happens. Reverted to version 2.17.11.

**Comment by sandreddu** [comment]
Working OK from release 3.0.4. Thank you!

**Comment by hogthrob** [comment]
In our case, I cannot confirm this to be fixed. It is most likely a different issue, as we are correctly asked for the certificate by 3.0.4 and we see the JitsiMeet site briefly (< 0.1s) flashing up. But then the Jitsi window turns white (we use the "Call in separate window" option). It does not happen in Jitsi 2.17.11 (all the rest is identical). Maybe other can confirm my observation and we open a new issue for this one then.

**Comment by sandreddu** [comment]
@hogthrob you are right, and I already opened a new issue #1841 for this, with more details. My error was at the time testing with the Linux client and not with the Windows one. We encounter exactly the same problem as you do

**Comment by hogthrob** [comment]
@sandreddu  Thank you! Now going over to #1841 to see what is going on there.
