### ISSUE TITLE
Windows Client 3.0 Window disappears and can not be restarted

### ISSUE THREAD

**Issue by Langlaeufer** [RocketChat/Rocket.Chat.Electron#1757]
Version 3.0.0
under windows 10 2004

Client Window in windows disappear after a while.
was not able to open (a new client) window by re-starting the program.
Then taskbar symbol disappeared when moving the mouse over.
Task manager showed still some rocket chat processes.
After killing all processes manually it was possible to restart the client.
Problem occurred some hours later again.
Here I was not able to restart after killing all processes.

**Comment by makarov-ittx** [comment]
Same thing

**Comment by Langlaeufer** [comment]
same on Version 3.0.1

**Comment by Langlaeufer** [comment]
the remaining processes have a high processor load.
maybe it's related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1768

**Comment by tassoevan** [comment]
@Langlaeufer is it possible to have crashed while receiving messages?

**Comment by Langlaeufer** [comment]
I always noticed the crash later so I can not be sure if a message was the trigger. But it is possible.

**Comment by MartinSchoeler** [comment]
From my testing it seems that if you receive a dm while the chat with that user is open and the setting `Window > Show on unread messages` is set to true, it crashes

**Comment by Langlaeufer** [comment]
Until now release 3.0.2 seems to be stable.
