### ISSUE TITLE
unexpected characters in servers list

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat.Electron#176]
Using v1.3.1 and still seeing ^1, ^2, etc... characters in servers list:

![image](https://cloud.githubusercontent.com/assets/4588562/14621067/4a9b0008-058e-11e6-9cc7-0f55d612a1ac.png)
##

**Comment by Blackth0rn** [comment]
These characters represent the hotkey combo to navigate to that chat server, in your screen shot Ctrl+1 will navigate you to the top (rocket) server and Ctrl+2 will navigate you to the bottom (GA) server.
