### ISSUE TITLE
[3.0.1] Server icon repeated verticaly on sidebar

### ISSUE THREAD

**Issue by prigal** [RocketChat/Rocket.Chat.Electron#1761]
## My Setup

- Operating System: Ubuntu 20.04
- App Version: 3.0.1
- Installation type:  deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Server icon (svg) is repeated verticaly on the side bar.

![Capture d’écran de 2020-10-02 07-28-42](https://user-images.githubusercontent.com/895267/94891050-4af82200-0481-11eb-8f33-4522455c1ae3.png)

**Comment by tassoevan** [comment]
Wow. The `Window` (`Fenêtre`) menu shows only one server to select?

**Comment by prigal** [comment]
Yes only one server can be selected, the first one. 

And icon to add a server is still clickable.

**Comment by prigal** [comment]
Still present in 3.0.2.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
