### ISSUE TITLE
[3.0.1] Initial launch screen should be from server.json

### ISSUE THREAD

**Issue by klou** [RocketChat/Rocket.Chat.Electron#1762]
MacOS 10.13
Rocket.Chat 3.0.1

```server.json```  is deployed to ```/Applications/Rocket.Chat.app/Contents/Resources/servers.json``` as a postinstall, so it affects all users.

At first launch, the configured server(s) appear on the left sidebar.  However, the initial/default screen is to add a new server.

It should log in or at least focus the first configured server.

**Comment by AmatorPhasma** [comment]
Same on Windows 10 Pro Version 2004

![001](https://user-images.githubusercontent.com/49910825/94909292-3dec2a80-04a3-11eb-9300-d16defa385e3.png)

**Comment by klou** [comment]
Confirmed, again with Windows 10 1909.

If the Server List is hidden view View->Server List (unchecked), then it looks like it's not configured at all as it just prompts to add a new server.
