### ISSUE TITLE
[3.0.1] Spell Checker no longer work

### ISSUE THREAD

**Issue by jpele-tis** [RocketChat/Rocket.Chat.Electron#1766]
- Operating System: Windows 10 version 2004
- App Version: 3.0.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Spell Checker no longer work since 3.x
I've try to add manually disctionnaries in user env and sys env => same problem
Modifying the file for en_US and fr_FR in "C:\Users\jpadmin\AppData\Roaming\Rocket.Chat\Preferences" => same problem
![image](https://user-images.githubusercontent.com/57767497/94901251-a5e84400-0496-11eb-9def-583c87c6e745.png)

### Current Behavior
Option find languages disapear (screen on 2.17.x)
![image](https://user-images.githubusercontent.com/57767497/94901512-0a0b0800-0497-11eb-9e74-9411dc3f85ce.png)

### Expected Behavior
Incorrect words should be at least underlined in red.

**Comment by AmatorPhasma** [comment]
Intresting... same configuration on my end, but it works.: tested with german and french.

![001](https://user-images.githubusercontent.com/49910825/94907125-f6b06a80-049f-11eb-8bfb-6a2bfd383d36.png)
![002](https://user-images.githubusercontent.com/49910825/94907129-f87a2e00-049f-11eb-850e-f974342c1ccf.png)

**Comment by blacklord049** [comment]
Try uncheck the langage in the dropdown menu then check it again or do it in another channel ? It worked for me.

**Comment by jpele-tis** [comment]
> Try uncheck the langage in the dropdown menu then check it again or do it in another channel ? It worked for me.

Same problem on 2 PCs.

**Comment by tassoevan** [comment]
The dictionaries are downloaded from Google CDN. Is it possible that any download was blocked by some network rule or error?

**Comment by ankar84** [comment]
> The dictionaries are downloaded from Google CDN. Is it possible that any download was blocked by some network rule or error?

Indeed.
I checked **en-US** in dictionaries list 
![image](https://user-images.githubusercontent.com/4023037/94995289-93b9f300-05c7-11eb-85ec-f4b44e945674.png)
and here what was after
![image](https://user-images.githubusercontent.com/4023037/94995228-273ef400-05c7-11eb-80c7-ffa73370b5a6.png)
en-US-9-0.bdic file was downloaded to C:\Users\ankar84\AppData\Roaming\Rocket.Chat\Dictionaries\en-US-9-0.bdic
and copied to C:\Users\ankar84\AppData\Roaming\Rocket.Chat\en-US-9-0.bdic
![image](https://user-images.githubusercontent.com/4023037/94995265-6cfbbc80-05c7-11eb-91d7-7ef58d447481.png)
![image](https://user-images.githubusercontent.com/4023037/94995277-77b65180-05c7-11eb-8279-93570a10ccbc.png)
And it works perfect.
**No need to do something with dictionaries manually**

**Comment by jpele-tis** [comment]
> The dictionaries are downloaded from Google CDN. Is it possible that any download was blocked by some network rule or error?

It is surely blocked by our network, we do not plan to open much for Google, where can we download `.bdic` files manually? We got a powerful SDT so we're able to place them manually.

Addittionnaly, it is planed to block Google download with an RC option?
Would you consider impletmenting bdic files in the RC binary?

**Comment by ankar84** [comment]
Agree with @jpele-tis 
**Automatic download of selected dictionary it's a really convenient**, but there is a lot of companies that **block such connections** and **manual dictionary management** it's must have function for such clients.

**Comment by tassoevan** [comment]
> Would you consider impletmenting bdic files in the RC binary?

Not really, as it would increase the bundle size with unused dictionaries.



> **Automatic download of selected dictionary it's a really convenient**, but there is a lot of companies that **block such connections** and **manual dictionary management** it's must have function for such clients.

I'll do a double-check in Electron source, but its docs don't state anything about it. For instance, the only option listed is to host your own dictionaries: https://www.electronjs.org/docs/tutorial/spellchecker#does-the-spellchecker-use-any-google-services

**Comment by jpele-tis** [comment]
> Not really, as it would increase the bundle size with unused dictionaries.

You're right, 350MB of file size will be really overkill for only dictionnaries.

I managed to found the Google repo, enjoy packaging ;)

`git clone https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries`

**Comment by jpele-tis** [comment]
Btw, I've packaged RocketChat with dictionnaries in user env (you need the SDT WAPT)
You can get it here : https://store.wapt.fr/store/tis-rocketchat

**Comment by Naworm** [comment]
So what you plan to do btw @tassoevan ?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
