### ISSUE TITLE
[3.0.1] set user status to online every new start: "Invisibel" or "Away" setting is not persistent.

### ISSUE THREAD

**Issue by AmatorPhasma** [RocketChat/Rocket.Chat.Electron#1767]
3.0.1 is setting my user status to online every new start: "Invisibel" or "Away" setting is not persistent.

## My Setup
- Operating System: Windows 10 Pro x64 Version 2004
- App Version: 3.0.1
- Server Version: 3.6.3
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
- Start Rocket.Chat
- Set user status to "Away" or "Invisible"
- Quit Rocket.Chat
- Start Rocket.Chat: User status is back to "Online"

### Current Behavior
Set user status to online every new start.

### Expected Behavior
Manual set user status is persistent like in version<= 2.17.11.

**Comment by AmatorPhasma** [comment]
EDIT: 
"Busy" is also not persistent on all restarts, sometimes it is...

**Comment by tassoevan** [comment]
Does it affects only the desktop client? Is the web one ok?

**Comment by AmatorPhasma** [comment]
@tassoevan 
I would say after some tests, its only the desktop client.

I'm now on:
- App Version: 3.0.2
- Server Version: 3.7.0

still happens. 

But after some trys (around 30) it only happens on the last focused account/server in the desktop app (I have 4 servers in my list).

**Comment by tassoevan** [comment]
@AmatorPhasma 3.0.3 may have you covered (due to #1800).
