### ISSUE TITLE
3.0.1 Windows 10 desktop app - Uses almost 100% of CPU

### ISSUE THREAD

**Issue by morgenstern72** [RocketChat/Rocket.Chat.Electron#1768]
## My Setup

- Operating System: Windows 10 2004
- App Version: 3.0.1
- Installation type: MSI

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
After a short time, especially after crashes like reported in https://github.com/RocketChat/Rocket.Chat.Electron/issues/1760, 3 tasks appear, all taking 25% of CPU (=100% of a core)
![301](https://user-images.githubusercontent.com/11777765/94906791-6114db00-049f-11eb-83e4-950ceaa1dfce.jpg)

### Expected Behavior
Version 2.17.11. CPU is used between 0-6%
![21711](https://user-images.githubusercontent.com/11777765/94906807-65d98f00-049f-11eb-88e0-630ea76380b9.jpg)

**Comment by vajoslav** [comment]
For me it's OK
![image](https://user-images.githubusercontent.com/61011615/94910627-45143800-04a5-11eb-88e7-47dcdd28be7f.png)

**Comment by blacklord049** [comment]
For me too it's OK. Maybe doing a clean install could solve this?

**Comment by ankar84** [comment]
It's OK for me too
![image](https://user-images.githubusercontent.com/4023037/94920788-29c71e00-04e1-11eb-8093-3cc79a1d4f01.png)

**Comment by tassoevan** [comment]
@morgenstern72 Is it really tied to crashes or can it happen at random?

**Comment by MartinSchoeler** [comment]
Yep it seems that everytime it crashes it leaves a lingering process that consumes more cpu than it should
![image](https://user-images.githubusercontent.com/20868078/94950806-975f5400-04b9-11eb-9fd8-e44a6f0f619a.png)

**Comment by MartinSchoeler** [comment]
It seems to be tied with the setting `Window > Show on unread messages` and it is related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1752 and https://github.com/RocketChat/Rocket.Chat.Electron/issues/1757

**Comment by wadjeroudi** [comment]
@tassoevan thx for your fix, it's better but still some lagging occurs, it seems that it's not totally fixed for win client.

**Comment by tassoevan** [comment]
@wadjeroudi I need some extra info on how to reproduce it. Is there anything special in you usage that could be a clue?
