### ISSUE TITLE
Login via Azure AD not possible

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat.Electron#1769]
## My Setup

- Operating System: macOS 10.15.6
- App Version: 3.0.1
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When signing in via Azure AD the login process gets stuck.

### Current Behavior

As shown in the screenshots below

![Screenshot 2020-10-02 at 11 51 18](https://user-images.githubusercontent.com/6920421/94911327-41cd7c00-04a6-11eb-8e0b-e9f5fdd1e6ce.png)
![Screenshot 2020-10-02 at 11 51 37](https://user-images.githubusercontent.com/6920421/94911347-4c881100-04a6-11eb-96a8-fab58d824a85.png)
![Screenshot 2020-10-02 at 11 52 21](https://user-images.githubusercontent.com/6920421/94911372-53af1f00-04a6-11eb-8716-d4f7ac07d62b.png)

This screen gets shown forever and in the dev inspector I see a pending request against our ADFS refered from https://login.microsoftonline.com/
When logging in via the browser (incognito) everything works as expected or when using the old v2 version.

### Expected Behavior

Login succeedes

**Comment by tassoevan** [comment]
Maybe related to #1754

**Comment by subesokun** [comment]
Awesome, thanks!
