### ISSUE TITLE
Add flash notifications for unread channels

### ISSUE THREAD

**Issue by force-net** [RocketChat/Rocket.Chat.Electron#178]
## My Setup

- Windows: 
- 1.3.1: 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

Please, add flash notifications, if unread channel messages exists. Currently, you parse badge value as a number. But for channels, this value is '●', so in code it has considered as empty notification. So, there are no ability to know, if somebody post something in chat or private room.

If this logic was made specially, additional solution (instead of flashing) can be implemented - overlay icon. It can be set as empty circle for unknown unread messages and circle with number for known number of unread messages. 
##

**Comment by mbraun01** [comment]
Is there any update on this issue?
Thanks.

**Comment by force-net** [comment]
is there any progress for this issue?

**Comment by Kochise** [comment]
Is there any update on this issue?

**Comment by jwallet** [comment]
are you using the tray icon to see if you have unread messages (not mentions) ? or you want this feature on the app icon in the task bar

**Comment by force-net** [comment]
App Icon should flash and show some symbol, notifying about unread messages. 
We're using Rocket.Chat in company and chat messages has the same importance as a private messages. Without this feature, lot of people miss messages. Tray icon is useless, nobody see it.

**Comment by jwallet** [comment]
does the PR i referenced is what you need, badges on the app icon

**Comment by Kochise** [comment]
Private messages : tray icon goes red/white with counter and sound notification
Public messages : tray icon goes blue/white

Would have been great to have also counter and sound notification too.

In the channel list, channels that get new messages turns bold, why not also adding a counter about how many new unread messages there is ?

BTW : the notification setting is a mess, you have to go into each channel and select '...', goes through a load of options in a scroll list. Why not a property sheet with a treelist like widget that shows the actual settings of all channels and the global setting as top row ?

**Comment by engelgabriel** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat.Electron/pull/760

**Comment by theonetech1** [comment]
can you Implement anything related to this Issue ?
