### ISSUE TITLE
Can't open Jitsi VC session via "Add server"

### ISSUE THREAD

**Issue by bognerf** [RocketChat/Rocket.Chat.Electron#1782]
## My Setup

- Operating System: Windows 8.1
- App Version: 3.0.2
- Installation type: exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

"Add Server" does not allow to use a Jitsi URL for a direct VC anymore

### Current Behavior
Error message: **"No valid server found at the URL"**

### Expected Behavior

In earlier versions the Jitsi VC opened inside the Rocket Client....

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
