### ISSUE TITLE
Absent/away after inactivity does not work. Client always online

### ISSUE THREAD

**Issue by RKD31** [RocketChat/Rocket.Chat.Electron#1783]
## My Setup

- Operating System:Windows 10 (1909) / MacOS 10.15: Catalina
- App Version: 3.0.2
- Installation type: exe / dmg

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description
Client status shows always online

### Current Behavior
The status is not set to absent after inactivity. Tested with 3.0.0 / 3.0.1 and 3.0.2

### Expected Behavior
The status should automatically be set to absent after the specified time. This works fine with version 2.17.11

**Comment by ankar84** [comment]
I do not confirm that issue.
Tested it on 3.0.2 on Windows 10 1809
For experiment I set idle time to 60 seconds (as I remember it's a minimum) and after 1 minute status of my user changed to Away automatically
Windows Lock (WIN+L) works perfect too - set user status to Away immediately. .

**Comment by RKD31** [comment]
I have the problem on all windows and also on the MacOs clients. It doesn't matter how high the idletime is set... The status is always online. With version 2.17.11 it works fine on both OS.
Maybe it's the combination of server version 3.7.0 and the new client version (3.0.0 - 3.0.2).

**Comment by ankar84** [comment]
> Maybe it's the combination of server version 3.7.0 and the new client version (3.0.0 - 3.0.2).

Indeed.
Just try 3.0.2 with test 3.7.0 server and user always online.
Maybe it's related to https://github.com/RocketChat/Rocket.Chat/pull/18892 in part of user presence.
So can you try to use `USE_NATIVE_OPLOG=true` like described [here](https://github.com/RocketChat/Rocket.Chat/issues/19082#issuecomment-703079731)?

**Comment by RKD31** [comment]
I have added "USE_NATIVE_OPLOG=true" to my systemd service file

.
.
Environment=USE_NATIVE_OPLOG=true
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01
Environment=MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01

Unfortunately this had no effect. The problem still exists after a server restart.

**Comment by RKD31** [comment]
Same problem with version 3.0.3
Server Version: 3.7.1
At first it looked good but after a restart of the client application the status always stays online again...

**Comment by RKD31** [comment]
Unfortunately I do not know why... but now it works with version 3.0.3 as well as with 3.0.4
