### ISSUE TITLE
2.x channel on snap

### ISSUE THREAD

**Issue by kalsan** [RocketChat/Rocket.Chat.Electron#1784]
Due to the issues with the 3.0 version (in particular #1743) I need to downgrade rocketchat to 2.x in order to use the application. However, on a fresh installation it seems that no snap channel provides 2.x releases. Is there any? If not, I'd like to suggest to provide such a channel since the automatic upgrade to 3.0 breaks many installations.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by kalsan** [comment]
Thank you, I now see channels stable, candidate, beta and edge. That will be helpful.
