### ISSUE TITLE
remove auto update feature

### ISSUE THREAD

**Issue by bbrendon** [RocketChat/Rocket.Chat.Electron#1788]
I think its time to stop stringing everyone along. Remove it until you're ready.

**Comment by frac6969** [comment]
Normally I use /disableAutoUpdates, but that doesn't seem to work for 3.x.

**Comment by ankar84** [comment]
> Normally I use /disableAutoUpdates, but that doesn't seem to work for 3.x.

Yeap, file `c:\Program Files\Rocket.Chat\resources\update.json` do not work anymore.

```
{
  "canUpdate": false,
  "autoUpdate": false
}
```

**Comment by bbrendon** [comment]
Seems like a reasonable change. Anyone?   @tassoevan  @rodrigok

**Comment by AlbyGNinja** [comment]
@bbrendon workaround solution here: [https://github.com/RocketChat/Rocket.Chat.Electron/issues/1871#issuecomment-733569302](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1871#issuecomment-733569302)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
