### ISSUE TITLE
Support for Servers Behind Identity Aware Proxy

### ISSUE THREAD

**Issue by anilcosar** [RocketChat/Rocket.Chat.Electron#1789]
We host our rocket.chat instance behind "Identity aware proxy" on Google Cloud which validates a google login before redirecting to actual website. (https://cloud.google.com/iap)

However because there is an additional login step,desktop app can not validate the site as a valid rocket.chat instance.

Would it be possible to disable server validity check?
Would it possible to open a browser window to show actual page if a validation fails (so that we can login to identity aware proxy) ? Could be "test" button when press it show success message or open in browser page.

Client version:3.0.2
Server version:3.7.0

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
