### ISSUE TITLE
Locking and unlocking screen on windows does not revert status back to its original value before lock

### ISSUE THREAD

**Issue by stylefish** [RocketChat/Rocket.Chat.Electron#1794]
## My Setup

- Operating System: Windows 10 x64
- App Version: 3.0.2
- Installation type: msi/exe

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
- enable auto away in user settings (timeout irrelevant)
- set status to "online" if not already
- lock screen (Win+L) [status gets updated to away correctly]
- unlock screen [status gets not updated back to "online"]
=> status is not being reverted to the "original" status (eg. online)

### Current Behavior
status is not being reverted to status before lock

### Expected Behavior
status gets reverted back to status that was active before locking the screen

**Comment by stylefish** [comment]
i think this might be related to #1542

**Comment by stylefish** [comment]
issue persists in 3.0.4, additionally i sometimes arent able to manually switch from "away" to "online". if i click "online" i stay "away". this issue persists until i restart rocket.chat.

**Comment by drdelaney** [comment]
And 3.0.5, 3.0.6 and now 3.0.7.
Same here. Windows 10.20H2 64bit.
Happens every time my screensaver turns on, so it is easily replicatable.

As a side note, the status is stuck in away and a client restart is required on my side to fix.  Even if I manually select another state, it never leaves Away.

**Comment by pdussart** [comment]
> As a side note, the status is stuck in away and a client restart is required on my side to fix. Even if I manually select another state, it never leaves Away.

Well, I had this problem as well on macOS Catalina with previous versions of the client, but it appears to be fixed for me since v3.0.7. 

(fyi: rocketchat-server  3.6.2      1442   3.x/stable )

**Comment by pdussart** [comment]
I just found out you really have to visit the client before the status automatically changes from away to available. So you could be back at work for already an hour after lunch, but this doesn't mean your colleagues know that you're online. At least it's possible to change the status manually without having to restart the client

**Comment by redRolf** [comment]
I can reproduce this issue on:
* macOS: 11.3.1
* app version: 3.0.3
* server version: 3.14.0

Even visiting the client does not automatically change my status.
