### ISSUE TITLE
User can no longuer acces to server in a sub-folder hosting.

### ISSUE THREAD

**Issue by ledshark24** [RocketChat/Rocket.Chat.Electron#1796]
## My Setup

- Operating System: ubuntu 20.04
- App Version: 3.0.1 
- Installation type: snap

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Our instance is hosted behind a reverse proxy with a URL like this  (fictitious url) : 
`https://tools.myownorganisation.fr/the_chat`
one of our users relies on the desktop app for everyday use and reported that the app "no longer works"

### Current Behavior
add a server with the url `https://tools.myownorganisation.fr/the_chat`
the server is added and works

### Expected Behavior
the desktop apps tries to add the server with a incomplete url : `https://tools.myownorganisation.fr/` (so it seems)
with the last version installed via the .deb file I have acces to the config file and it doses not includes the directory of our server, only the root URL. I tried editing the config file in `.config/Rocket.Chat/config.json` but no luck.

P.S. as a french person I fell the need to apologize for my poor English.

**Comment by BriceGUILLAUME** [comment]
I am experiencing the same issue with the 3.0.2 version as well.

**Comment by nathanael-h** [comment]
Idem on Windows, version 3.0.1 and 3.0.2. Server is the Rocket Chat integrated in Univention https://www.univention.com/products/univention-app-center/app-catalog/rocketchat/

**Comment by ura14h** [comment]
try 3.0.3 (#1775)

**Comment by julijane** [comment]
We experience the same problem and 3.0.3 does not fix it.

**Comment by dbradley771** [comment]
I'm also experiencing this on 3.0.3.

Our Rocket.Chat server is hosted at https://apps.example.com:9443/rocketchat/. Adding that URL creates this server list in the `config.json` file:
```json
[
    {
        "url": "https://apps.example.com:9443/",
        "title": "https://apps.example.com:9443/"
    }
]
```
This results with a 404 error in the client.

Closing the client, changing the `config.json` file to use the correct URL (the slash at the end is necessary), and opening the client fixes the issue.
```json
[
    {
        "url": "https://apps.example.com:9443/rocketchat/",
        "title": "https://apps.example.com:9443/"
    }
]
```
The client can then access the server and grab the correct configuration.
```json
[
    {
        "url": "https://apps.example.com:9443/rocketchat/",
        "title": "Rocket.Chat - https://apps.example.com:9443/rocketchat/",
        "lastPath": "https://apps.example.com:9443/rocketchat/home",
        "badge": "",
        "style": {
            "background": "rgb(47, 52, 61) none repeat scroll 0% 0% / auto padding-box border-box",
            "color": "rgb(157, 162, 171)"
        },
        "favicon": "[SNIP]"
    }
]
```

**Comment by johanneshiry** [comment]
Came here from #1781 - we're experiencing the same on latest Rocket.Chat instance with latest Desktop clients on macOS and Windows. 

In addition to the workaround from @dbradley771 for windows pls find a macOS workaround [here](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1781#issuecomment-708961785)
