### ISSUE TITLE
Login with Two-Factor Authentication not available

### ISSUE THREAD

**Issue by antoninaLebedzeva** [RocketChat/Rocket.Chat.Electron#1798]
## My Setup

- Operating System: Windows 10
- App Version: 3.0.2
- Installation type: exe

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description

During the login the Two-Factor Authentication is not asked.
### Current Behavior

Attempting to sign in using the two-factor authentication with Google Authenticator. Successfully enter login name and password but after this the two-factor authentication is not asked.
### Expected Behavior

It should be asked during the login to authenticate using two-factor authentication.

**Comment by j0wns** [comment]
I agree this issue persists in version 3.0.4 of the electron client.
In my environment, users are required to log in with certificate based SAML authentication.
The 3.0.4 overrides/covers the server-configured logon page and does not provide an option to select user certificate.
I've included a side-by-side: Electron client on the left, Chrome browser on the right.
![image](https://user-images.githubusercontent.com/19246095/96470807-aa359080-11fc-11eb-99ae-6a49e6115177.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
