### ISSUE TITLE
App (3.0.2) crashes when one is trying to record a video message (MacOS Catalina)

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat.Electron#1802]
## My Setup

- Operating System: MacOS Catalina
- App Version: 3.0.2
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When trying to record a video message app crashes immediately.

### Current Behavior
App crashes.

### Expected Behavior
App does not crash.

**Comment by tassoevan** [comment]
Does it shows a crash report window?

**Comment by himpierre** [comment]
No, it just quits. 

Am 14. Oktober 2020 00:43:27 MESZ schrieb Tasso Evangelista <notifications@github.com>:
>Does it shows a crash report window?

**Comment by tassoevan** [comment]
Does it still happen in 3.0.4? If it does, could it be reproduced using [Rocket.Chat's open server](https://open.rocket.chat/)?

**Comment by himpierre** [comment]
Yes, it still happens. Even with 3.1.1. It's actually the same as https://github.com/RocketChat/Rocket.Chat.Electron/issues/1965. When I start the app via terminal everything works.

**Comment by himpierre** [comment]
#2132
