### ISSUE TITLE
Connecting to a new server ignores system proxy settings

### ISSUE THREAD

**Issue by azikic** [RocketChat/Rocket.Chat.Electron#1803]
## My Setup

- Operating System: Windows 10 (2004)
- App Version: 3.0.2
- Installation type: Rocketchat Desktop App via Installer

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When connecting to a new server, the client does ignore the systems proxy settings and reports a connection timeout.

### Current Behavior
When connecting to the server for a first time, the request is sent directly and not via the configured http proxy.
We can see the packages beeing dropped by our firewall.

If we make an firewall excemption to allow the connection the client can connect. 
After authentication with the server the problem goes away, eg. after the rule is enabled again chatting works as expected, even after restarting the client.

### Expected Behavior
Adding a new server from behind a corporate proxy should work, it did work with client versions 2.17.x (edit, corrected client version).
We upgraded to 3.0.2 and it stopped working.

**Comment by hibobmaster** [comment]
Any plan to add a custom proxy choice, such as http/socks5 proxy ?

**Comment by azikic** [comment]
The issue is no longer present with client 3.0.4, closing.
