### ISSUE TITLE
Jitsi end to end encryption

### ISSUE THREAD

**Issue by idarlund** [RocketChat/Rocket.Chat.Electron#1806]
## My Setup

- Operating System: Fedora 33
- App Version: 3.0.3
- Installation type: rpm

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
With the newest electron (https://github.com/RocketChat/Rocket.Chat.Electron/blob/master/package.json#L97) deployed with the app, there's a new feature available; Insert-able streams. This is utilized to create E2E encrypted video conferences in Jitsi.

### Current Behavior
When starting a jitsi video call I would expect to find the E2E enable button (screenshot from browser):
![image](https://user-images.githubusercontent.com/3417634/95748197-ecf5e680-0c99-11eb-8cca-6e7e05d763e3.png)

### Expected Behavior
When starting a jitsi video call from the electron client the enable button is not represented:
![image](https://user-images.githubusercontent.com/3417634/95748437-44945200-0c9a-11eb-8ccb-0dd290452b72.png)

### Possible solution
I'm not sure if the flag is set or not, but this bug might be because of an possible unset flag: chrome://flags/#enable-experimental-web-platform-features
Also not sure if it's possible for users to set this flag or if it needs to be done at build time.

**Comment by ankar84** [comment]
Good feature! Users ask for it.

**Comment by idarlund** [comment]
With Chrome 87 we don't have to turn on chrome://flags/#enable-experimental-web-platform-features to get E2E encryption in jitsi. Chrome 87 was integrated in electron 11.

This issue could potentially fix it self with upgrading to latest electron version.

When this comment is written, the current version of electron is 10.0.1: https://github.com/RocketChat/Rocket.Chat.Electron/blob/3b2d0aaa51eaf96442c3084eaeb8621465d40cee/package.json#L92

**Comment by idarlund** [comment]
Any progress on this? Electron versions are flying by, but Rocket Chat is still stuck on 10 :-1:

**Comment by idarlund** [comment]
With a series of updates (https://github.com/RocketChat/Rocket.Chat.Electron/pull/2129 as the latest) the running version of Electron is now 13.2.2.

Jitsi now works with end to end encryption within the electron client. No need to open URL in a browser anymore.
