### ISSUE TITLE
Rocketchat never updates

### ISSUE THREAD

**Issue by mewlove** [RocketChat/Rocket.Chat.Electron#1807]
## My Setup

- Operating System: Windows 10 Home
- App Version: 2.15.2
- Installation type: 

- [ ] I have tested with the latest version 
- [ ] I can simulate the issue easily

## Description

Prev version and this version requires me to uninstall and reinstall new rocketchat. Install Updates never works.

### Current Behavior

Clicking on Install Updates will show "You will be notified when update is ready to be installed". But it never gets installed.

### Expected Behavior

New updates installed immediately.

**Comment by TdMxm** [comment]
Same here

Operating System: Windows 10 Pro
App Version: v 2.17.11 and all previous versions
Installation type: exe

**Comment by inickolay** [comment]
One more

Operating System: Windows 10 Home (ver. 1903)
App Version: v 2.17.9
Installation type: exe

**Comment by Maqsyo** [comment]
Duplicate of #1670
