### ISSUE TITLE
"A JavaScript error occurred in the main process" when moving app window

### ISSUE THREAD

**Issue by localhorst** [RocketChat/Rocket.Chat.Electron#181]
## My Setup
- Windows 7 64Bit, SP1. 
- All updates installed
- Rocket.Chat+ v 1.3.1 
- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description
- After installation (update from 1.2)
- Starting the app
- Loggin in to the server
- Moving the app window
## Current Behavior

Moving the app window makes an error message pop up: 
"A JavaScript error occurred in the main process ..." 
## Expected Behavior

No error message
## Full error message:

`
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: EPERM: operation not permitted, rename 'C:\Users\myusername\AppData\Roaming\Rocket.Chat+\window-state-main.json.**new**' -> 'C:\Users\myusername\AppData\Roaming\Rocket.Chat+\window-state-main.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:729:18)
    at writeAtomicSync (C:\Program Files (x86)\Rocket.Chat+\resources\app.asar\node_modules\fs-jetpack\lib\file_ops.js:105:8)
    at Object.writeSync [as write](C:Program Files %28x86%29Rocket.Chat+resourcesapp.asarnode_modulesfs-jetpacklibfile_ops.js:116:5)
    at Object.write (C:\Program Files (x86)\Rocket.Chat+\resources\app.asar\node_modules\fs-jetpack\lib\jetpack.js:192:21)
    at Object.saveState (C:\Program Files (x86)\Rocket.Chat+\resources\app.asar\background.js:72:21)
    at BrowserWindow.<anonymous> (C:\Program Files (x86)\Rocket.Chat+\resources\app.asar\background.js:268:25)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:169:7)
[OK]
`
## More
- Uninstalling previous version beforehand did not solve this issue.
##

**Comment by localhorst** [comment]
Uninstalling previous version beforehand solved this issue.

**Comment by rockneverdies55** [comment]
Can confirm this is happening:

![image](https://cloud.githubusercontent.com/assets/4588562/14890625/719ef93e-0d31-11e6-933c-1b39c028d1a5.png)

**Comment by istanleyyaw** [comment]
same issue.

**Comment by localhorst** [comment]
Issue still exists on Windows 10 and Rocket.Chat+ Version 1.3.1

**Comment by adesimonepeak6** [comment]
Same here, using version 1.3.1 and 0.35 backend

**Comment by rockneverdies55** [comment]
Can replicate in my ubuntu box. Only happens in windows 7 for me.

**Comment by alkovpro** [comment]
Did anyone solve this?

**Comment by seerl** [comment]
... same here. annoying.
Windows 10, version 1.3.1, 0.42 server

Any suggestions?

**Comment by dcbell** [comment]
Just installed a brand new rocket.chat server and I'm seeing this on my Windows 10 machine I'm testing on.

**Comment by aliozgur** [comment]
Same here

**Comment by apomes** [comment]
I had the same issue on my machine (Windows 10, McAfee antivirus installed). Turning off McAfee's real-time analysis fixed the problem.

**Comment by aliozgur** [comment]
Agreed McAfee is the culprint

**Comment by theoryshaw** [comment]
McAfee confirmed.

**Comment by seerl** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail. Ich bin derzeit in Winterpause über die Feiertage. 

Ab dem 02.01.2017 bin ich wieder für Sie da. Diese Mail wird nicht weitergeleitet, aber aufgehoben :)

Mit freundlichen Grüßen,
Sebastian Erlhofer

-- 
mindshape GmbH
Hohenstaufenring 47-51
50674 Köln

Registergericht: Amtsgericht Köln, HRB 71255
Sitz der Gesellschaft: Köln
Geschäftsführer: Sebastian Erlhofer, Robert Neumcke
UstID: DE275057780

**Comment by dcbell** [comment]
I do not have McAfee on my machine, so that can't be the sole issue. FYI, just upgraded to desktop agent 2.0.2 on Windows 10 and I'm still seeing the issue.

**Comment by graywolf336** [comment]
Can you share a screenshot of the error that is happening now?

**Comment by dcbell** [comment]
Here is a screenshot. I tried disabling Kaspersky and that did not resolve the issue.

![Screenshot](https://cloud.githubusercontent.com/assets/930515/21734705/6a25e224-d42a-11e6-849d-d153a27d537f.PNG)

**Comment by engelgabriel** [comment]
Can you guys please test with the version 2.2.0?

**Comment by theoryshaw** [comment]
![image](https://cloud.githubusercontent.com/assets/507113/21898540/bf8448c8-d8b2-11e6-9b32-2b056ae593ec.png)

Windows 10
Mcafee Installed
![image](https://cloud.githubusercontent.com/assets/507113/21898609/fb2ce812-d8b2-11e6-9ea9-18cb96f71dc6.png)

**Comment by dcbell** [comment]
Same error after updating to 2.2.0.

**Comment by engelgabriel** [comment]
Guys,

On McAfee, if allowed for following file to be excluded  do you still have this issue?

```
C:\Users\*\AppData\Roaming\Rocket.Chat+\window-state-main.json
```

**Comment by engelgabriel** [comment]
@rodrigok is `window-state-main.json` used to save the sate of the window? 
Maybe we are writing too many time and to fast to it? 
Can we Debounce the write function?

**Comment by graywolf336** [comment]
Would someone mind testing the build from the result of the pull request? Let us know if you're still having issues with McAfee and Rocket.Chat?

https://ci.appveyor.com/api/buildjobs/2tojs8hrcqkf6e3w/artifacts/dist%2FRocket.Chat%2B%20Setup%202.2.1.exe

**Comment by dcbell** [comment]
Just to be clear, I'm having that issue and I do not run McAfee. We run Kaspersky here.

**Comment by graywolf336** [comment]
@dcbell Okay, mind trying the build I linked to above as well?

**Comment by theoryshaw** [comment]
![2017-01-20_08-25-17](https://cloud.githubusercontent.com/assets/507113/22152795/14493818-deea-11e6-860d-234a11fa5e00.gif)

Bingo

**Comment by graywolf336** [comment]
So it works now?

**Comment by theoryshaw** [comment]
Yes, It seems to.

**Comment by dcbell** [comment]
@graywolf336 Working on my machine now as well.

**Comment by graywolf336** [comment]
@theoryshaw and @dcbell Awesome, thanks for reporting back!

**Comment by fndos** [comment]
Use git init from git bash on your main GitHub directory

**Comment by LootDigger** [comment]
have the same trouble. Windows 8

**Comment by tassoevan** [comment]
@LootDigger Can you please share the error shown in the dialog?

**Comment by Jabark** [comment]
This problem appears to have reared it's ugly head again, we have McAfeee running too. 

![image](https://user-images.githubusercontent.com/9607853/45286211-1c473180-b4dd-11e8-83d3-5a22124f4661.png)

**Comment by mikhey** [comment]
I just started getting this error message after 2.13.2 installed for just my user account on my Windows 7 workstation.  The previous version was installed at `~\AppData\Local\Programs\Rocket.Chat` the new version installed at `~\AppData\Local\Programs\Rocket.Chat+`.  Out of curiosity renamed the old `Rocket.Chat` folder to `Rocket.Chat.Old` then removed the `+` on the new folder. 

I ran the new install from the renamed folder: `~\AppData\Local\Programs\Rocket.Chat` and I didn't receive the error on startup or when moving/resizing the window.  

Could the `+` in the Rocket.Chat.exe path be the cause of this or cause McAfee to throw a false positive?

**Comment by tomkralidis** [comment]
I'm having the same issue on 2.13.2 on Windows 10.

**Comment by tassoevan** [comment]
@tomkralidis Can you verify if [2.13.3-beta.1](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.13.3-beta.1) has this issue?

**Comment by tomkralidis** [comment]
@tassoevan installing 2.13.3-beta1 fixes this issue for me.

**Comment by Sabnock01** [comment]
I've just gotten this issue today. And I don't run McAfee. It does this whenever I try to open the desktop app. It always worked fine before. I don't know what changed about my system.
