### ISSUE TITLE
`Also send to channel` behaves wrong when creating new threads

### ISSUE THREAD

**Issue by atemp** [RocketChat/Rocket.Chat.Electron#1811]
## My Setup

- Operating System: CentOS Linux
- App Version: 3.0.3
- Installation type: RPM; 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

In Account settings you can disable `Show thread messages in the main thread`. This should have an influence on the `Also send to channel` checkbox while posting message to or creating threads.

### Current Behavior

The client does not honor this setting when doing the first reply to a message, creating a thread. It does honor the setting when you post another message to an already existing thread.

### Expected Behavior

If show thread messages in main threads are disabled in settings, it should always be honored by the client.

**Comment by ankar84** [comment]
> If show thread messages in main threads are disabled in settings, it should always be honored by the client.

I agree that either should be a per user setting to enable\disable **Also send to channel** checkbox for first thread reply either if **Show thread messages in the main thread** is turned off, then **Also send to channel** checkbox should be not checked by default.
