### ISSUE TITLE
[Bug] In versions 3.X User can't change status to online

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1812]
## My Setup

- Operating System: Windows 10 1809
- App Version: 3.0.3
- Server Version: 3.6.3
- Installation type: exe,

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I think https://github.com/RocketChat/Rocket.Chat.Electron/pull/1800 introduced a bug, that user now can not change status to online

### Current Behavior
It happens not all time, but in some circumstances
![online](https://user-images.githubusercontent.com/4023037/95955239-3151c580-0e05-11eb-8fab-91108107e6b3.gif)

**Reload** by **CTRL+R** helps
### Expected Behavior
If user set status to Online it should be online.
If user status become Away because inactivity, then it should set to Online right after some activity (mouse movement or something like that)

**Comment by foss-** [comment]
Working here with Server 3.7.1 and Electron Client 3.0.3. Feels like this could be related to https://github.com/RocketChat/Rocket.Chat/issues/19209

**Comment by x-f** [comment]
I had the same issue - server considered me "away" and sent emails and notifications to me while I was chatting, I couldn't set me "online".
Resolved by restarting Rocket.Chat and changing the status once again.
Versions 3.0.0 (AppStore) and 3.6.2 server.

**Comment by ankar84** [comment]
I see this in 3.0.5.
Still only **CTRL+R** helps

**Comment by ankar84** [comment]
3.0.7 issue still here

**Comment by ankar84** [comment]
As I see that issue is server undependent.
Now I get it in [open server](https://open.rocket.chat) with **3.10-develop in 3.0.7**
