### ISSUE TITLE
3.0.3 Mac Don't start

### ISSUE THREAD

**Issue by superzr** [RocketChat/Rocket.Chat.Electron#1814]
Mac system version 10.15.6 , Dont' start , Don't use。

**Comment by tassoevan** [comment]
We can't help you because you have not filled in a proper bug template.

First read this:
https://docs.rocket.chat/contributors/contributing/reporting-issues

Then use this as a template:
https://github.com/RocketChat/Rocket.Chat.Electron/issues/new?template=ISSUE_TEMPLATE.md

Thanks!
