### ISSUE TITLE
Regression: Rocket Chat Electron Client no longer remembering window screen position

### ISSUE THREAD

**Issue by foss-** [RocketChat/Rocket.Chat.Electron#1815]
## My Setup

- Operating System: macOS 10.15.7
- App Version: 3.0.3
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When starting RC electron client, the window position is no longer remembered. This was not a problem in previous versions.

### Current Behavior
Window keeps opening on same location. I keep moving it to where I want the window to be. Restart app, back to wrong location.

### Expected Behavior
Remember window position.

**Comment by lk3de** [comment]
Same issue here.

- OS: Windows 10 1809
- App Version: 3.0.2, just updated to 3.0.4 and still the same
- Installation type: exe Installer

The issue mainly happens to me when resuming the main window from system tray. It seems like the window automatically scrolls up to the top, then starts loading older messages, scrolls up again, loads older messages again, and so on. This repeats 2-3 times until it stops.

**Comment by AlynxZhou** [comment]
Same issue, I guess some code was added to set display position window recently, which prevent desktop manager to put it into last position.

- OS: Arch Linux
- App Version: 3.0.4
- Installation Type: AUR

Now it always shows in center of desktop, but I always set it to left half of my desktop.

**Comment by Crack** [comment]
Can confirm:

- OS: Windows 10
- App Version: 3.0.6
- Installation Type: exe

Restoring from tray changes scroll position in opened channel.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
