### ISSUE TITLE
enhancement : focus to preconfigured server

### ISSUE THREAD

**Issue by Mystikal57** [RocketChat/Rocket.Chat.Electron#1817]
Hello,
Could you add the possibility to focus to servers preconfigured in servers.xml ?
Preconfiguration of "currentServerUrl".
Others config parameters could be fine
Or just use a config.json for all users
Because by default it focus to add new server

thank you

**Comment by Mystikal57** [comment]
Seems to be okay with [#1850](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1850 )

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
