### ISSUE TITLE
3.0.3 (Mac App Store): Doesn't remember the server URL

### ISSUE THREAD

**Issue by Tekl** [RocketChat/Rocket.Chat.Electron#1818]
## My Setup

- Operating System: macOS 10.15.6 and macOS 11 Big Sur Developer Beta
- App Version: 3.0.3
- Installation type: Mac App Store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

Every time I launch Rocket.Chat on my Macs it asks me to enter the Server URL. I connect to an internal server. Interestingly the credentials are saved, I don't need to enter my login data again.

I tried to delete the sandbox folder with the settings, but that does not help.

### Expected Behavior

As pre 3.0-Versions the App should remember the Server.

**Comment by gondhijagapathi** [comment]
Hi, any update on this issue?

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
