### ISSUE TITLE
3.0.3 (Mac App Store): Doesn't send/receive audio/video from Jitsi Video Conference

### ISSUE THREAD

**Issue by OSPFS** [RocketChat/Rocket.Chat.Electron#1819]
## My Setup

- Operating System: macOS 10.15.7 & macOS 11 Big Sur beta
- App Version:  3.0.3
- Installation type: Mac App Store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
When I connect to Video Conference (Jitsi meet) I can't receive video and audio from another users (I see how many users in conference and thier names/avatars), they also does not see/hear me. This problem with Mac App Store version only, because dmg file version 3.0.3 from GitHub works properly.

**Comment by ankar84** [comment]
I confirm that issue.
I [reported it](https://open.rocket.chat/channel/desktop?msg=hEvNerkdkzg9KXfKm) in open.rocket.chat
In my case our MacOS users comply about jitsi calls after desktop client was updated from 2.17.9 to 3.0.0
Looks like some access to microphone issue or something.
In same time in Chrome all works fine
![image](https://user-images.githubusercontent.com/4023037/96152489-ce604b80-0f36-11eb-9cc0-f1b5e1cf6eaa.png)
3 0.3 from GitHub fix that issue in a moment

**Comment by danel1** [comment]
We can also confirm this issue - Rocket.Chat 3.0.3 from MacApp Store used on macOS Catalina (10.15.7).

No video and no audio is being transmitted. It worked well with 2.17.11.

**Comment by L4rS6** [comment]
Got the same problem here with AppStore version 3.0.3 on macOS Catalina 10.15.7.

**Comment by gcommit** [comment]
Same here ....

**Comment by mimurrayy** [comment]
The problem also occurs for linux clients.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
