### ISSUE TITLE
OS X Cmd+W hide instead of close

### ISSUE THREAD

**Issue by tholu** [RocketChat/Rocket.Chat.Electron#182]
Cmd+W should hide the window instead of closing it, to keep Rocket.Chat running in the background (like Slack does, and browsers like Firefox and Chrome as well).

Related issues:  #72 #89

**Comment by ulope** [comment]
Works for me in the lastest app store version

**Comment by tholu** [comment]
Sorry still had 1.0.0 - replaced it with current App Store Version 1.3.1 and it works fine!
