### ISSUE TITLE
[3.0.3] Does not work with servers running under a prefix

### ISSUE THREAD

**Issue by kalsan** [RocketChat/Rocket.Chat.Electron#1821]
## My Setup

- Operating System: Debian 10
- App Version: 3.0.3
- Installation type: snap 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

URLs with a prefix are truncated but shouldn't (for an example, see below).

### Current Behavior

- "Enter your server URL": https://mydomain.com/mychat/
- URL is truncated automatically to https://mydomain.com/ (the prefix `mychat` is deleted)
- Since the Rocketchat runs under prefix `/mychat`, this does obviously not work.

### Expected Behavior

Correct behaviour would be as in Rocket Chat 2.x: The URL https://mydomain.com/mychat/ worked fine there.

**Comment by Tusko** [comment]
+

**Comment by icelaser** [comment]
i have the same Problem

**Comment by ura14h** [comment]
Same issue #1796
