### ISSUE TITLE
Option to disable third party requests for embedded content

### ISSUE THREAD

**Issue by user234683** [RocketChat/Rocket.Chat.Electron#1824]
If a link to, for instance, a Youtube video, is posted, the Rocket.Chat client will embed the video (meaning that the electron client will make connections to Youtube to retrieve the embed page and assorted javascript). This is a privacy leak, so it would be nice to have an option to disable this behavior, or to disable all such third party connections in general.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
