### ISSUE TITLE
Message notifications appear in FRONT of lock screen

### ISSUE THREAD

**Issue by rhires** [RocketChat/Rocket.Chat.Electron#183]
## My Setup

 OS: Win 10 
App version: 3.1.1 (modified w/ the GPU optimization disabled)

- [x] I have tested with the latest application version
- [ ] I can simulate the issue easily
#### Current Behavior

I had my screen locked and noticed that I was seeing messages - not sure if they were to me directly, but I believe so. 

#### Expected Behavior

not have messages show in front of lock screen
##

**Comment by engelgabriel** [comment]
Guys, can you please try again with the version `2.2.0`?

**Comment by alexbrazier** [comment]
This sounds like a windows 10 setting/feature.

@rhires What are your notification preferences for Rocket.Chat/ does changing them fix the issue, e.g. changing to keep private, or disabling all together?

![image](https://cloud.githubusercontent.com/assets/5689874/22623057/98ca0088-eb45-11e6-88c5-fbdafd213bec.png)

![image](https://cloud.githubusercontent.com/assets/5689874/22623059/9d4ae154-eb45-11e6-9981-687ec3f676b7.png)

**Comment by alexbrazier** [comment]
Closing this, reopen if it is still an issue with the latest version

**Comment by Jimmy062006** [comment]
This is an issue in the current version.
