### ISSUE TITLE
3.0.4 Invalid server url

### ISSUE THREAD

**Issue by ThomasKientz** [RocketChat/Rocket.Chat.Electron#1830]
## My Setup

- Operating System: macOS 10.15.7 
- App Version: 3.0.4
- Installation type:  dmg (downloaded from github, fresh install)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Impossible to connect to my server : `https://chat.my-company.com/` (dummy url, real one works when accessed from a browser).

### Current Behavior

Got the error :

> No valid server found at this url 
(translated from French)

### Expected Behavior

To connect to the server with no error, as before v3.

**Comment by ygrange** [comment]
I have the same issue. I noticed a commit that I think suggests a change in minimum server version. Maybe that is the issue here, or would I expect another error then?

**Comment by tassoevan** [comment]
@ygrange Yes, it's the server version.

**Comment by ygrange** [comment]
So it seems that the check of the server version has been fixed in 3.0.4; it would be useful to have a line in the changelog to make it explicit. (I have no clue wether changing the changelog text for a current release os considered good practice...)

**Comment by kalsan** [comment]
Same problem here. Probably not the same bug as #1743 since that one should have been fixed in 3.3 (but I was unable to test due to bug reported in #1821 which was fixed in 3.4).

My server version is 1.0.2 with apps engine version 1.4.2.

**Comment by flipphillips** [comment]
Continue to have same problem w/ 3.0.4. Unsure what version server is running since I don't run it (but presume there is a way to check via web client?) Other users @ same group have had to revert back to 2.x.

**Comment by ygrange** [comment]
If tou are not admin, you can check chat.<mydomain>/api/info

**Comment by kyoshiro** [comment]
Workaround:
1. Add servername as suggested by the app: "open.rocket.chat", do not enter any credentials there.
2. Close the app
3. Open ~/.config/Rocket.Chat/config.json
4. Replace all occurrences of "open.rocket.chat" with your server's name
5. Open the app again
6. Click on the rocket chat icon in the navigation, ét voilà you should be placed to the login mask of your server
7. Login to the rocket chat server as usual
Whatever the client does when checking the initial entered URL, it doesn't when it's already configured.

Hope that helps someone else :)

**Comment by flipphillips** [comment]
> Workaround:
> ...
> 3. Open ~/.config/Rocket.Chat/config.json
> ...

`~/Library/Application\ Support/Rocket.Chat/config.json` for the macOS users

**Comment by kalsan** [comment]
@kyoshiro This works for me, too, thanks for the workaround!

**Comment by Kolomiits** [comment]
In version 3.0.4 authentication don't work with your's issuer in ~/.config/Rocket.Chat/. 
  When i adding string  < "open.rocket.chat": "https://mychat.example.com",>  in config.json, nothing happents. 
And what do, when this problem for each users in our company ?
![image](https://user-images.githubusercontent.com/36440171/97196872-a1712b80-17b5-11eb-8d45-ca27892ef755.png)
![image](https://user-images.githubusercontent.com/36440171/97197336-32480700-17b6-11eb-94c5-2cfdc175e8a4.png)

**Comment by intissar12** [comment]
> 4\. Replace all occurrences of "open.rocket.chat" with your server's name

i didn't find any recurrence of  "open.rocket.chat" in my config.json any help plzzzzz

**Comment by kyoshiro** [comment]
> > 4. Replace all occurrences of "open.rocket.chat" with your server's name
> 
> i didn't find any recurrence of "open.rocket.chat" in my config.json any help plzzzzz

intissar12:
The value "open.rocket.chat" matches the default value, explained in Step 1.
>> 1. Add servername as suggested by the app: "open.rocket.chat", do not enter any credentials there.

The workaround was just a try & success :) It may help if your remove the config.json file and start over.
But not sure.

**Comment by intissar12** [comment]
> > > 1. Replace all occurrences of "open.rocket.chat" with your server's name
> > 
> > 
> > i didn't find any recurrence of "open.rocket.chat" in my config.json any help plzzzzz
> 
> intissar12:
> The value "open.rocket.chat" matches the default value, explained in Step 1.
oppps my bad thx you man

**Comment by Ghanimaid** [comment]
unfortunatly it does not work. Our Server runs on port 8080
Does not work

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
