### ISSUE TITLE
Black Page on certain links (ie: Twitter)

### ISSUE THREAD

**Issue by Nono-m0le** [RocketChat/Rocket.Chat.Electron#1832]
## My Setup

- Operating System: Windows 10
- App Version: 3.0.4 (also true on 3.0.3)
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When posting a twitter link, the "description" automatically added below contain the text, a link to the image, and the date (with its permalink url).
Clicking on the image or date link does nothing or let RocketChat in a black page (no server/room/discussion are visible anymore).
EDIT: To illustrate : 
![image](https://user-images.githubusercontent.com/3726435/96445297-f6d69700-120f-11eb-9a2d-fd619dab6a37.png)

![image](https://user-images.githubusercontent.com/3726435/96445304-fb02b480-120f-11eb-8f51-39a2bf0315a5.png)

### Current Behavior
Clicking on the image/date link of a twitter URL description leave rocket chat on a black page

### Expected Behavior
The link should be openned within the default browser.

**Comment by tassoevan** [comment]
Probably a server-side issue too, i.e., the web client is not opening those links in a new window/tab.
@Nono-m0le do you mind [opening an issue there](https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md) while I'll be working around it in the app?

**Comment by pompi-stefana** [comment]
Not sure if this is related, but the behavior seem pretty similar with issue #1834

**Comment by Nono-m0le** [comment]
I confirm, still not fixed on 3.0.5 thus the milestones changes I guess.
