### ISSUE TITLE
Rocketchat Desktop turns grey when accessing certain Chats

### ISSUE THREAD

**Issue by pixxelspotter** [RocketChat/Rocket.Chat.Electron#1834]
## My Setup

- Operating System: Ubuntu 16.04
- App Version: 3.0.3, 3.0.4, 3.0.5 and 3.0.7
- Installation type: .deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The Client turns grey when clicking on certain Chats, reloading Server is needed to access other chats.
Screenshot found here: https://imgur.com/a/ayPFhJo
Also tried it with Disabled GPU Setting --> Same Result

### Current Behavior
The Client turns grey when clicking on certain Chats, reloading Server is needed to access other chats.

### Expected Behavior
Access chats without client getting grey and needs reloading

**Comment by dasfreak** [comment]
Same here:

Operating System: Manjaro
App Version: 3.0.4
Installation type: AUR / .deb

Happens when I start or participate in a Jitsi Call (in new window).

**Comment by pompi-stefana** [comment]
Same as @dasfreak , it happen after starting/joining a Jitsi Call (also new window).

Installation type: Docker
RocketChat Server: 3.7.1
RocketChat Client: Rocket Chat Electron 3.0.4 (Windows 10)

Sometimes also the Jitsi popup gives the same behavior (grey window).

**Comment by stleitner** [comment]
Same problem with Mac App Version 3.0.3
