### ISSUE TITLE
default server

### ISSUE THREAD

**Issue by q16marvin** [RocketChat/Rocket.Chat.Electron#1836]
## My Setup

- Operating System: win10
- App Version: 3.0.4
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
we use server.json in C:\Program Files\Rocket.Chat\resources to give a default server, but it shows "new server" as default

### Current Behavior

![grafik](https://user-images.githubusercontent.com/19844709/96553072-ecbaa400-12b4-11eb-8643-753037cd7b38.png)

### Expected Behavior

![grafik](https://user-images.githubusercontent.com/19844709/96553183-1378da80-12b5-11eb-85de-c6230a38c6ea.png)

in earlier versions it was like expected, doesnt remember which version ^^

**Comment by masterbbgit** [comment]
Same problem in this version
