### ISSUE TITLE
Feature request - Read partially configured "config.json" from <INSTSALLDIR>\resources

### ISSUE THREAD

**Issue by MJPGPleasant** [RocketChat/Rocket.Chat.Electron#1838]
## My Setup

- Operating System: Windows 10  19041.508
- App Version: 3.0.4
- Installation type: MSI / InTune (Per-Machine install)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Rocket Chat should read config.json from the Resources folder and populate the user configuration using these defaults.

Currently if you manually copy a partially built config.json file into %APPDATA%\RocketChat, the configurations within the file are maintained. 
Examples
- Server Config
- Default Server
- Certificates
- Disable startup checks

However this is not practical when installing per-machine.

### Current Behavior

File in resources folder is ignored

### Expected Behavior

If there is no user config present, the file should be copied into user space and built from there.

**Comment by jeanfbrito** [comment]
Hey @MJPGPleasant you can use overridden-settings to force settings to the users config.json. This resolves for you?
https://github.com/RocketChat/Rocket.Chat.Electron#overridden-settings
