### ISSUE TITLE
Add MSI parameter to disable launch after install

### ISSUE THREAD

**Issue by MJPGPleasant** [RocketChat/Rocket.Chat.Electron#1839]
## My Setup

- Operating System: Windows 10 19041.508
- App Version: 3.0.4
- Installation type: MSI / InTune (per-machine)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Add a parameter (MSI Property) to disable first launch after install 

### Current Behavior

Rocket Chat launches in installation context (potentially as "System") after silent installation.

### Expected Behavior

Add a flag "LAUNCH" (or similar) which can be set to 0 to prevent launch.

**Comment by ankar84** [comment]
Agree with that request!
Config file could be nice alternative.

**Comment by ankar84** [comment]
@tassoevan hey!
That's a real big issue for organizations with centralized installations systems like InTune or System Center.
Please take a look at that issue.

**Comment by ankar84** [comment]
We have a workaround for that problem, @MJPGPleasant 
Edit MSI in **advanced installer**
Delete **launch after installation** in **Existing custom actions**
![image](https://user-images.githubusercontent.com/4023037/98925429-03849d00-24e7-11eb-8db2-b794ea2be976.png)
But native solution is waiting!

**Comment by MJPGPleasant** [comment]
Thanks - Yes I had already edited the MSI to disable this step - Added a condition "NEVER" to "runAfterFinish" in the InstallExecuteSequence" table via Orca :)

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
