### ISSUE TITLE
Add option to disable GPU acceleration

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#184]
With our recent black screen issue we realized we have some clients where GPU acceleration doesn't work too well.  So we should add the option for the user to disable

Could be added in here: https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/app/app.js#L15

with flags looking like this:

```
app.commandLine.appendSwitch('--disable-2d-canvas-image-chromium');
app.commandLine.appendSwitch('--disable-accelerated-2d-canvas');
app.commandLine.appendSwitch('--disable-gpu');
```

Just need to check their settings on startup to decide to apply the flags or not.
##

**Comment by Romich777** [comment]
With different intel GPU I get this issue very often

**Comment by playmono** [comment]
Black screen came to me after 2.10.

**Comment by vchrombie** [comment]
I am really interested in contributing to Rocket.Chat
Can you help me in getting started?

Can I work on this issue?

**Comment by gdelavald** [comment]
@vchrombie Hey, it's awesome to hear that, so welcome.
For this issue, I would suggest looking at the flags that @geekgonecrazy added above and check if they solve the issue of GPU acceleration, also, you would need to add a menu option for `Disable GPU Acceleration` that would trigger a restart of the app and enable those flags on launch.
If you need more guidance, please join us at open.rocket.chat on the #desktop channel.

**Comment by demyxco** [comment]
Any news on this? Didn't have an issue in Mojave but it's enabled in High Sierra now. Using the 2.17.2 version from .dmg. The installation from the App Store crashes.

**Comment by bkraul** [comment]
How can we have this option persisted? I toggle the Disable GPU option, but it always reverts to use GPU after a restart of the app.

**Comment by bkraul** [comment]
@iamhammer well that's kind of a drag...Thankfully I haven't been having performance issues lately due to that being enabled. Great tip tho! Thanks!

**Comment by jeanfbrito** [comment]
@bkraul we are adding a setting to persist disabling hardware acceleration. Next release it will be available.
