### ISSUE TITLE
Notification sound not working

### ISSUE THREAD

**Issue by dwasylowski** [RocketChat/Rocket.Chat.Electron#1846]
## My Setup

- Operating System: Windows 10
- App Version: 3.0.4
- Installation type: .exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

the sound notifications do not work correctly, with channels it works, but with private groups and direct massages it does not work although the notification preferences are set the same as with channels.
![image](https://user-images.githubusercontent.com/73329208/96963773-8aa6ac80-1509-11eb-90fc-90fab762cfcb.png)

### Current Behavior
there is no sound

### Expected Behavior
there should be a sound like with channel

**Comment by Jan-NiklasB** [comment]
Bump, same problem over here with Win7 64bit, installed and downloaded today (exe installer)
No Notifications at all, also no soundserver registerd or at least visible when checking the windows audio mixer

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by Weuxel** [comment]
Broken again in 3.8.7 to 3.8.9 in Mac App.

**Comment by jeanfbrito** [comment]
Using the DMG installer from GitHub or the apple store one?

Em sex., 2 de set. de 2022 02:42, Norman Rieß ***@***.***>
escreveu:

**Comment by jeanfbrito** [comment]
Just tested here and it works. Are you using your status at `busy`? Then it will not alert.
