### ISSUE TITLE
[Bug] macOS Big Sur: Wrong Tray icon color

### ISSUE THREAD

**Issue by MrMarmelade** [RocketChat/Rocket.Chat.Electron#1848]
## My Setup

- Operating System: macOS Big Sur 11 Beta 10 (20A5395g)
- App Version: 3.0.3
- Installation type: Mac App Store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Wrong RocketChat tray icon color (that first black icon in the screenshot).
<img width="444" alt="Screen Shot 2020-10-23 at 22 57 23" src="https://user-images.githubusercontent.com/23004033/97053628-9767e680-1583-11eb-914d-83cc2de90ee5.png">

### Current Behavior
Tray icon has a black color in Light mode, Dark mode is fine (white icon).

### Expected Behavior
Tray icon should be contrasting => white.

**Comment by spipau** [comment]
In addition, when I use dark mode (Dunkel) then my status bar in Big Sur stays in a light colour, but the RocketChat Icon is white and completely hidden. My Desktop background is white and this influences the status bar colour. If I change the background to black, then I'm facing the same bug as @MrMarmelade.

![Bildschirmfoto 2020-11-17 um 09 37 09](https://user-images.githubusercontent.com/2797845/99366840-6f854d80-28b9-11eb-9742-4f4ee2964a92.png)

![Bildschirmfoto 2020-11-17 um 09 37 16](https://user-images.githubusercontent.com/2797845/99366854-757b2e80-28b9-11eb-93b0-ea95a917da69.png)

**Comment by bfanger** [comment]
The color of the menubar in Big Sur does not depend on dark or light mode, but depends on the wallpaper.

**Comment by sergeysova** [comment]
And how it should be solved?

**Comment by bfanger** [comment]
Use a Template image to let macos determine the icon color. 

https://github.com/electron/electron/blob/main/docs/api/native-image.md#template-image 

https://developer.apple.com/documentation/appkit/nsimage/1520017-template

**Comment by jeanfbrito** [comment]
The Apple Store version is updated, you can install it from there right now.
