### ISSUE TITLE
No able to run rocket chat desktop client after installation

### ISSUE THREAD

**Issue by pavananand** [RocketChat/Rocket.Chat.Electron#1854]
#735  My Setup

- Operating System: Windows 10
- App Version: 3.0.5
- Installation type: .exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I had generated the installer with the latest source code and then I had installed using the .exe file. After the installation process finished nothing happens and after I clicked on the shortcut created on the desktop nothing is happening not sure what the issue is

I had run the .exe file present in the dist/win-unpacked/rocketchat.exe the same behavior is observed.

**Comment by IhorNykyha** [comment]
@pavananand Maybe this helps for you. https://github.com/RocketChat/Rocket.Chat.Electron/issues/1804

**Comment by pavananand** [comment]
@IhorNykyha, That resolved the issue! Thanks a lot :))
