### ISSUE TITLE
cannot set "default-url-scheme-handler" setting to invalid value "rocketchat"

### ISSUE THREAD

**Issue by bringmetheaugust** [RocketChat/Rocket.Chat.Electron#1855]
## My Setup

- Operating System:  **Ubuntu 20.04.1 LTS**
- App Version: **3.0.1**
- Installation type: **Snap store**

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

App crashed during the opening.

### Current Behavior

![Screenshot from 2020-10-28 14-25-14](https://user-images.githubusercontent.com/40362626/97435706-7a3b6b00-1929-11eb-92a7-86d68514819c.png)

### Expected Behavior

Use app))

**Comment by PSFILM** [comment]
> ## My Setup
> * Operating System:  **Ubuntu 20.04.1 LTS**
> * App Version: **3.0.1**
> * Installation type: **Snap store**
> 
> * [x]  I have tested with the latest version
> * [x]  I can simulate the issue easily
> 
> ## Description
> App crashed during the opening.
> 
> ### Current Behavior
> ![Screenshot from 2020-10-28 14-25-14](https://user-images.githubusercontent.com/40362626/97435706-7a3b6b00-1929-11eb-92a7-86d68514819c.png)
> 
> ### Expected Behavior
> Use app))

Same Issue with our program

**Comment by htatche** [comment]
Same on Ubuntu 20.10

```
➜  ~ rocketchat-desktop                   
[bugsnag] Loaded!
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" setting to invalid value "rocketchat"
[1]    18610 segmentation fault (core dumped)  rocketchat-desktop

```

**Comment by bringmetheaugust** [comment]
Guys!
Has it been fixed?
Cause it already works.

**Comment by tassoevan** [comment]
@bringmetheaugust We've changed our workflow for releasing new versions, and somewhat the snap build was stuck on version 3.0.1; now it's fixed. :tada:

**Comment by bringmetheaugust** [comment]
@tassoevan, bro.
this issue came back again.
still can't open the app this the same error
