### ISSUE TITLE
update.json no longer recognized in 3.0.5 MSI all users

### ISSUE THREAD

**Issue by sagansapien** [RocketChat/Rocket.Chat.Electron#1856]
My Setup

- Operating System: Windows 10 1909 Enterprise build 18363.1139
- App Version: 3.0.5.1729
- Installation type: MSI

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Greetings. I manage an enterprise deployment for Windows. As of .EXE version 2.17.7, the update.json file could be used to disable checking for updates for all users. I installed the MSI version of 3.0.5 for all users and the update.json file seems to have no effect. The installation directory appears to have changed from C:\Program Files\Rocket.Chat to C:\Program Files\rocketchat. I moved my update.json file to C:\Program Files\rocketchat\resources\update.json but this did not affect the user client. I also tried moving update.json to the root program files directory.

### Current Behavior

Check for updates and check for updates at startup is enabled by default for all users and cannot be disabled by using an update.json file.

### Expected Behavior

update.json file should be able to disable check for updates functionality for all users in an enterprise deployment.

my update.json file which worked in version 2.17.7 but not in 3.0.5:

`{
	"canUpdate":false,
	"autoUpdate":false
}`

Thank you!

**Comment by sagansapien** [comment]
By the way, I'm extremely happy to have an MSI version available now. Thank you.

**Comment by ankar84** [comment]
> update.json file should be able to disable check for updates functionality for all users in an enterprise deployment.

Totally agree, this is a must have feature in managed environments.
Related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1491 as manageable settings request.

**Comment by MJPGPleasant** [comment]
This could also be connected to #1838 (possible method for managing settings)

**Comment by klou** [comment]
Same with MacOS.
