### ISSUE TITLE
Question/Future - Open link to jitsi meet in Rocket.Chat.Electron (Win app)

### ISSUE THREAD

**Issue by eragras** [RocketChat/Rocket.Chat.Electron#1857]
## My Setup

- Operating System: Win 10 pro 2004 (19041.572)
- App Version: 3.0.5
- Installation type: msi

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Current Behavior
I dont know it is posible? How open link to exist jitsi meet video conference in windows desktop RocketChat app?
Firefox have problems witch microphone and option to change source audio is allways grey(inactive) In Chrome everything is fine. But it will be perfect to use rocket chat desktop app to everything include open existing videoconference from invitation by links. 

### Expected Behavior
Join to exist video conference by desktop app from link's

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
