### ISSUE TITLE
Newer versions of the client do not connect to the server

### ISSUE THREAD

**Issue by Ustrahan** [RocketChat/Rocket.Chat.Electron#1863]
## My Setup

- Operating System: Windows 10
- App Version: 3.0.6
- Installation type:  rocketchat-setup-3.0.6.exe

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

### Current Behavior

Starting from the third version, it is impossible to connect to the server.
In the server input field I enter - http://10.1.20.11:3000
and I see a message that something like - it is impossible to find a suitable server.
I go through the browser normally
What can be done?

**Comment by UniPAYNINJA** [comment]
same issue here, please support

**Comment by ankar84** [comment]
> In the server input field I enter - http://10.1.20.11:3000

What server version do you have?
Why don't you use HTTPS instead of HTTP?

**Comment by Praphulp** [comment]
I tried with https also, still its not connecting... getting "No valid server found at the URL".

**Comment by ankar84** [comment]
> I tried with https also, still its not connecting... getting "No valid server found at the URL".

What server version do you have?

**Comment by UniPAYNINJA** [comment]
Version | 0.63.1
-- | --

**Comment by ankar84** [comment]
> Version	0.63.1
> still, problem, why there is not support from the rocket team?

Because your server version is too old and not supported anymore.
You need to update to recent maybe 3.7.1 or wait a bit and 3.8.0 version.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
