### ISSUE TITLE
App reload logs the user out from all servers

### ISSUE THREAD

**Issue by johnypeterson** [RocketChat/Rocket.Chat.Electron#1864]
## My Setup

- Operating System: Windows 10
- App Version: 3.0.6
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
If the user makes a reload using Ctrl+Shift+R or presses Reload under the "View" dropdown, he is logged out from all servers he was previously logged in to.

### Current Behavior
Reloading logs the user out from all servers

### Expected Behavior
Reloading shouldn't log the user out from all servers

**Comment by IhorNykyha** [comment]
The same behavior.

**Comment by ankar84** [comment]
@tassoevan Confirm that issue!
`CTRL+SHIFT+R` - logs off user from all configured in desktop client servers
CTRL+R - looks good
