### ISSUE TITLE
Auto Away misbehavior

### ISSUE THREAD

**Issue by levifranzen** [RocketChat/Rocket.Chat.Electron#1866]
## My Setup

- Operating System: Windows 10 1909
- App Version: 3.0.6
- Installation type: EXE

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

### Current Behavior
User Presence (Auto Away) doesn't turn status back to "online"

### Expected Behavior
When user AFK for X time limit, turn status to "away" and when user interacts, turn back to "online".

**Comment by ankar84** [comment]
Confirm that, but it's duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1812

**Comment by levifranzen** [comment]
@ankar84 thanks, as it is duplicated, I'm closing and watching the #1812
