### ISSUE TITLE
Cannot open an application released from source code version 3.0.6

### ISSUE THREAD

**Issue by taihoa** [RocketChat/Rocket.Chat.Electron#1868]
## My Setup

- Operating System: Windows 10, Ubuntu 18.04.5 LTS
- App Version: 3.0.6
- Installation type:  exe, deb

## Description
After I got the latest version 3.0.6 source code on my computer and started the source code with "yarn start" command everything should work fine but then I did a release with "yarn release" command. I get the files I need to install on my desktop. But after the installation is completed and try to open the app, it does not show the app window, the app cannot open at all.

**Comment by IhorNykyha** [comment]
@taihoa Maybe this helps for you https://github.com/RocketChat/Rocket.Chat.Electron/issues/1804

**Comment by taihoa** [comment]
> @taihoa Maybe this helps for you #1804

@IhorNykyha Thanks you! But it am not working on version 3.0.6

**Comment by homberger** [comment]
@taihoa Did you read the mentioned issue? 
Is NODE_ENV set to „production“ before starting `yarn build`?
