### ISSUE TITLE
Rocketchat should minimize to systray when clicking close button in linux

### ISSUE THREAD

**Issue by dlecan** [RocketChat/Rocket.Chat.Electron#1869]
## My Setup

- Operating System: Linux Ubuntu 20.04, Gnome desktop
- App Version:
```
$ snap list | grep rocket
rocketchat-desktop       3.0.6                       255       latest/edge      rocketchat✓       -
```
- Installation type: snap

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

As already written [here](https://github.com/RocketChat/Rocket.Chat.Electron/issues/142#issuecomment-205323265), the application should minimize to systray when clicking close button.

But, the close button really closes the application (exit it).

### Current Behavior

- Open rocketchat-desktop
- Click X to close the window
- Check that the application was exited

### Expected Behavior

The application should be minimized to systray.

**Comment by prigal** [comment]
Same here, ubuntu 20.10 (gnome shell 3.38), Rocket is closed and not minimized.

Moreover I don't have any icon in systray while Rocket.chat is running. Is it expected behavior or a bug on my side ? (Skype, Slack or other electron based app like Upwork have their own icon).

Thanks.

**Comment by senpl** [comment]
Workaround with gnome-extensions not seems to work as well.

**Comment by hkpanchani** [comment]
should minimise on close.. Same with debian 10

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by ValheruPL** [comment]
@jeanfbrito doesn't work. After close window, I've active process in background and no icon in systray.
