### ISSUE TITLE
Italics not working

### ISSUE THREAD

**Issue by yuppox** [RocketChat/Rocket.Chat.Electron#1870]
## My Setup

- Operating System: Windows 10
- App Version: 3.0.7*
- Installation type: exe

\* **NOTE** The website currently links to 3.0.6 but the client reports that 3.0.7 is the latest. I think the website needs to be updated!

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Italics do not work across multiple lines.

Using italics for part of a word/phrase is also problematic. Observe in Rocket Chat:
`You cannot put "_quotes_" around _italics_.`
`Nor can italics be used p_art_ially...`
`...unless there is a _leading sp_ace.`

Repro:
1. Launch Rocket Chat
2. Type in a multi-line message
3. Press Ctrl+a and Ctrl+i to italicize the text
4. Send the message

### Current Behavior
Text appears with an underscore at the beginning and end of the text.

### Expected Behavior
Text is italicized.

**Comment by Maqsyo** [comment]
Please report this here: https://github.com/RocketChat/Rocket.Chat/issues
It has nothing to do with Rocket.Chat.Electron

**Comment by yuppox** [comment]
You're sure it's the server and not the client?

**Comment by Maqsyo** [comment]
Definetly.
The Client just sends the message to the server and the server tries to parse it.

You could try it yourself. Open your server-address in your browser and paste the same message. You will encounter the same problem.

**Comment by yuppox** [comment]
Fair enough. Thanks!

**Comment by tassoevan** [comment]
@yuppox I can't move this issue to the server repository because there we collect more info about the server itself. Please let me know if you're going to open an issue, because our team is reviewing the message parsing/rendering to tackle exactly this kind of problem right now.
