### ISSUE TITLE
Notification not working on Windows Server with GPO "Remove common program groups from Start Menu"

### ISSUE THREAD

**Issue by flauschi** [RocketChat/Rocket.Chat.Electron#1872]
## My Setup

- Operating System: Windows Server 2019
- App Version: 3.0.6
- Installation type: exe

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I have noticed a strange behavior with notifications on Windows Server 2019 (Terminalserver). But I think it is the same on Windows 10.
Users with an applied group policy with the setting "User Configuration/Administrative Templates/Start Menu and Taskbar/Remove common program groups from Start Menu" activated, do not see notifications. All other users see notifications.
This setting prevents that common start menu shortcuts (e.g. C:\ProgramData\Microsoft\Windows\Start Menu\Programs) are merged with the user specific start menu shortcuts (%appdata%\Roaming\Microsoft\Windows\Start Menu\Programs).

The only notification which works for every user, is the minimize to tray notification.

If I disable the GPO for the specific user, login, start Rocket.Chat, logout and enable the GPO. Notifications also work.

### Current Behavior
No notification is shown.

### Expected Behavior
Notification should be shown.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
