### ISSUE TITLE
pdf file upload issue

### ISSUE THREAD

**Issue by udzerkals** [RocketChat/Rocket.Chat.Electron#1873]
upload 
![spin](https://user-images.githubusercontent.com/54497200/98758390-9843a980-23c6-11eb-97e1-cfacac5d7bd4.png)
spinning continousy

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
