### ISSUE TITLE
Chat server is no longe recognised when using RC 3.X versions 

### ISSUE THREAD

**Issue by tudorsss** [RocketChat/Rocket.Chat.Electron#1874]
## My Setup

- Mac OS X Catalina
- 3.0.X

- [X ] I have tested with the latest version
- [X ] I can simulate the issue easily

## Description
1. Install the latest RC app;
2. Setup this server: chat.advinow.com - see if it works;

### Current Behavior
2. It says it doesn't find it. But it works if we use version 2.17.11.

### Expected Behavior
2. I should be able to connect to the chat.advinow.com server.

**Comment by ankar84** [comment]
> 1. I should be able to connect to the chat.advinow.com server.

What version runs that server?

**Comment by lukeproviderpl** [comment]
You need to update the server to 3.x or use an older version of app, we did it on our instance

**Comment by tudorsss** [comment]
Yes, that is the problem. At least, the new version of the RC app should inform the user that the server selected is too old to be used with version 3.X.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
