### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by simplytoast1** [RocketChat/Rocket.Chat.Electron#1875]
## My Setup

- Operating System: 11.0.1
- App Version: 3.0.7
- Installation type: PKG

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description
Due to the electron dependency Rocket.Chat will not open on Apple Silicon (M1) Macs.

### Current Behavior
Success app launch but nothing happens

### Expected Behavior
Ability to use application.

Electron 11 should be used to build Rocket.Chat

**Comment by ankar84** [comment]
> Electron 11 should be used to build Rocket.Chat

Agree that most up-to-date Electron should be a base for RC desktop app.

**Comment by rstockm** [comment]
See:

https://www.electronjs.org/blog/apple-silicon

**Comment by rstockm** [comment]
Actually, it _does work_ now on the real M1 Apple Silicon using Rosetta2 emulation.
Nevertheless it would be great to see a real M1 release.

**Comment by justinGML** [comment]
Is the version in the App Store different?  Using that distribution, I am able to start the app but it fails when attempting to log into a server.  Using version 3.0.7 downloaded from GitHub directly works correctly.

**Comment by fkoehler** [comment]
Any updates on this? 3.1.1 is still running via Rosetta 2

**Comment by Atomzwieback** [comment]
Why still no update on this? Even most single dev open source projects now cover M1 ....  and here is no one really care about it.

**Comment by rstockm** [comment]
Frankly speaking: the Electron app appears to be Abandonware.
The last commit to this repository was three months ago:

https://github.com/RocketChat/Rocket.Chat.Electron/commits/master

I have a bad feeling about this.

**Comment by rainsym** [comment]
> Any updates on this? 3.1.1 is still running via Rosetta 2

@fkoehler how can I using rosetta 2, please give me the guideline, thanks

**Comment by fkoehler** [comment]
Just install the normal intel version and it will work. But not as fast as it could.

**Comment by Atomzwieback** [comment]
> Just install the normal intel version and it will work. But not as fast as it could.
> […](#)
> Am 17.03.2021 um 15:39 schrieb Rainsym ***@***.***>: ﻿ Any updates on this? 3.1.1 is still running via Rosetta 2 @fkoehler how can I using rosetta 2, please give me the guideline, thanks — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

also Apple begins to remove Rosetta 2 already so sometime this year rocketchat will simple not work anymore...

**Comment by vast-z** [comment]
Electron is already compatible with m1. I hope rocketchat can be compatible with m1 and improve the experience. Thank you very much for your efforts.

**Comment by vast-z** [comment]
I tried to compile the project using Electron 11 and updated 'sharp' to 0.28.3. Everything was fine at first, but when the input connection logged in, it was thrown
<--- Last few GCs --->
[6885:0x7100000000]     1882 ms: Scavenge 13.2 (18.2) -> 11.1 (19.4) MB, 0.7/0.0 ms (average mu = 1.000, current mu = 1.000) allocation failure
[6885:0x7100000000]     1904 ms: Scavenge 14.7 (19.9) -> 12.7 (21.6) MB, 0.8/0.0 ms (average mu = 1.000, current mu = 1.000) allocation failure
[6885:0x7100000000]     1937 ms: Scavenge 17.1 (22.1) -> 14.5 (32.1) MB, 1.1/0.0 ms (average mu = 1.000, current mu = 1.000) allocation failure
<--- JS stacktrace --->
I think there are some strange issues and it is possible that the M1 version will not be released anytime soon. Individual users may consider using Electron to encapsulate web pages directly

**Comment by vast-z** [comment]
I have made a simple version, using the latest Electron and remote Web resources, the effect is OK, you can try it.
**https://github.com/vast-z/rocketchat-m1**

**Comment by vladimirschuka** [comment]
Took source code from version 3.2.2 and just changed two rows
 ` "electron": "^11.4.9",`  and `"electron-store": "^7.0.3"`
managed to build it and run with `yarn start`
The problem is only yarn release to make a Package Bundles. for some reason does not work and says something about code sign.
Could you please just make it, to make us more happy with native version.
Thanks.

**Comment by vast-z** [comment]
> Took source code from version 3.2.2 and just changed two rows
> ` "electron": "^11.4.9",` and `"electron-store": "^7.0.3"`
> managed to build it and run with `yarn start`
> The problem is only yarn release to make a Package Bundles. for some reason does not work and says something about code sign.
> Could you please just make it, to make us more happy with native version.
> Thanks.

There are some unknown problems in the native version, which cannot be solved by changing the package, and need to change the reference of the Sharp library, etc. However, after solving all these problems, there is a GC problem. I don't think the authorities can solve this problem in a short time. You can try my Web encapsulated version, the function is OK
[https://github.com/vast-z/rocketchat-m1](url)

**Comment by BJKle** [comment]
I'm not a developer just a user.
But for me it seems this "official client" has been abandoned.
Has there been any kind of announcement, sort of roadmap, etc. or is it just "dead".
On my Apple Silicon Macbook, the app looks like a resource hog. Unfortunately I have to use it.

**Comment by vast-z** [comment]
> I'm not a developer just a user.
> But for me it seems this "official client" has been abandoned.
> Has there been any kind of announcement, sort of roadmap, etc. or is it just "dead".
> On my Apple Silicon Macbook, the app looks like a resource hog. Unfortunately I have to use it.

https://github.com/vast-z/rocketchat-m1
Try a simple encapsulated version for the transition

**Comment by BJKle** [comment]
> 
> https://github.com/vast-z/rocketchat-m1
> Try a simple encapsulated version for the transition

I tried your version before, which doesn't work for me. I have to be logged into 3 servers and need to get notifications. Thanks anyway for yor effort.

It's more a commitment from "officials", if this client is still supported. I can't find anything, like roadmap (e.g. transition period, future functions,...)

**Comment by vast-z** [comment]
> > https://github.com/vast-z/rocketchat-m1
> > Try a simple encapsulated version for the transition
> 
> I tried your version before, which doesn't work for me. I have to be logged into 3 servers and need to get notifications. Thanks anyway for yor effort.
> 
> It's more a commitment from "officials", if this client is still supported. I can't find anything, like roadmap (e.g. transition period, future functions,...)

Well, I have an idea of what you need. If the official support is not available, I will try to support it at a later time.

**Comment by edilsonborges** [comment]
> I have made a simple version, using the latest Electron and remote Web resources, the effect is OK, you can try it.
> **https://github.com/vast-z/rocketchat-m1**

great! Thank you. I've notice that the notification badge is not showing. Is it ok for you?
Another question, is there a way to add more spaces?

**Comment by BJKle** [comment]
Another month, still no reaction from the official maintainers :-(

**Comment by ankar84** [comment]
According to this https://www.electronjs.org/blog/apple-silicon Electron support M1 since 11 version.
Since version 3.4.0 Rocket.Chat Electron application is [based on 13.2.2 electron](https://github.com/RocketChat/Rocket.Chat.Electron/commit/3edba3f474898a3f4f9ce04994d3c22430854033)
So, I guess only one thing is needed from devs team - is to  update the target architecture to `arm64`.
@debdutdeb can you speak with product team about that?

**Comment by debdutdeb** [comment]
I'll talk to them next week.

**Comment by krismatthews** [comment]
@simplytoast1, did you really mean to close this?

**Comment by trx222** [comment]
New release is still intel only on mac, issn't ?

**Comment by BJKle** [comment]
> I'll talk to them next week.

Any results?

**Comment by septs** [comment]
https://1drv.ms/u/s!AkzkQDDwJ0ETr3CIo83C1Gk6LL47?e=dO6XBn (for testing only)

**Comment by edilsonborges** [comment]
> https://1drv.ms/u/s!AkzkQDDwJ0ETr3CIo83C1Gk6LL47?e=dO6XBn (for testing only)
> 
> ![image](https://user-images.githubusercontent.com/3842474/133872226-902baa69-ddb9-45d1-8aad-039984643680.png)

it works perfectly. Thanks!

**Comment by trx222** [comment]
Thank you very much! Works great.
