### ISSUE TITLE
Forcing a version of the windows client

### ISSUE THREAD

**Issue by cdisabatino** [RocketChat/Rocket.Chat.Electron#1877]
## My Setup

- Operating System: Windows
- App Version: 3.0.5
- Installation type: exe
- Server Version: 3.7.1

We regularly encounter problems with new versions of the windows client. Is it possible, from the server (or another solution), to block the version of windows clients installed on all user computers on a version validated by our service. In this case, I would test all new proposed versions and once validated, the update could be installed on all user computers.

Otherwise, from the windows client, is it possible (registry for example) to select the update source ? In this case, I would create my own distribution channel for all my users.

Thank you

**Comment by jeanfbrito** [comment]
Hello @cdisabatino! Nowadays there are some solutions like on the installing you use the option to disable auto updates:
https://github.com/RocketChat/Rocket.Chat.Electron#windows-options

Or you can use the overridden-settings to disable the auto updates. https://github.com/RocketChat/Rocket.Chat.Electron#overridden-settings

But to make the new version be updated on this machines on demand, I think that the only way is installing it by GPO or something like that. 
To create your own distribution channel you would need to fork this project and edit the code to make it get the updates from your repository.
