### ISSUE TITLE
MSI package for 32-bit Windows OS

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1878]
## My Setup

- Operating System: Windows 7 32 bit
- App Version: 3.0.7
- Installation type: MSI

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
MSI package includes only 64-bit version and could not be installed on 32-bit Windows Operation System

### Current Behavior
Installation of MSI package of 3.0.7 version finished with error on 32-bit Windows 7
![image](https://user-images.githubusercontent.com/4023037/98924751-3da16f00-24e6-11eb-83e8-bb5e0b133cc4.png)

### Expected Behavior
MSI package must include both 32-bit and 64-bit application versions.
EXE version includes both
RPM version according to name `rocketchat-3.0.7.x86_64.rpm` includes both

**Comment by ankar84** [comment]
Looks like 3.8.1 have MSI version for 32bit Windows https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.8.1
I will check it

**Comment by jeanfbrito** [comment]
> Looks like 3.8.1 have MSI version for 32bit Windows https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.8.1 I will check it

Yes, finally! I didn't had time to notify the opened issues about this.
I renamed the files with the OS to help with the installers.

**Comment by jeanfbrito** [comment]
Awaiting feedback if this worked.

**Comment by ankar84** [comment]
Fixed since 3.8.1
Tested on 32bit Windows 7 with MSI for 32bit OS.
Thank you, Jean!
