### ISSUE TITLE
Empty file attachments

### ISSUE THREAD

**Issue by stleitner** [RocketChat/Rocket.Chat.Electron#1879]
When downloading a file (e.g. PDF , PNG) from a chat, the downloaded files are often empty (zero bytes) on the harddisk.

## Server Setup Information:

    Version of Rocket.Chat Server:  3.6.2 snap
    Operating System: Ubuntu 18.04
    Deployment Method: snap
    Number of Running Instances: 1
    NodeJS Version: v12.16.1
    MongoDB Version: 3.6.14

## Client Setup Information

    Desktop App: Mac App Store 3.0.3 and DMG 3.0.7
    Operating System: Mac OSX 10.14.6 and 10.15.7

### Current Behavior
File size is 0. After deleting the file and multiple "Reload ignoring cache", the file is downloaded normally. Very annoying. 

### Expected Behavior
Complete file, same file size as uploaded

**Comment by stleitner** [comment]
It has something to do with the "Protect Uploaded Files" option when enabled. 

**Current Behavior**
When you click on the file name, the browser opens and download fails because you are not logged in there. This results in a empty 0 byte file. No Error is displayed. When clicking on the little cloud icon, behind the filename the download starts in the desktop client and the download is succesful.
  
"Reload ignoring cache" does not resolv it. It only seems to work since the cloud icon is clicked unconsciously.

**Expected Behavior**
Open/download the file with the filename link in the desktop client when "Protect Uploaded Files" is enabled, because in the browser the download always fails.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by xsiviso** [comment]
I using the latest MacApp from the Store. Still have this issue. If I am logged in to the browser, the download works.

**Comment by stleitner** [comment]
I still have this issue with DMG 3.9.9
