### ISSUE TITLE
Rocket.Chat turns gray after starting a video conference

### ISSUE THREAD

**Issue by Attack44** [RocketChat/Rocket.Chat.Electron#1881]
#735  My Setup

- Operating System: Windows 10 - 2004 
- App Version: 3.0.7
- Installation type: exe
- Server Version: 3.8.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Currently the surface of Rocket.Chat is always completely gray as soon as you start / join a video conference (Jitsi), this only affects the app, we cannot find the problem in the browsers.

![rocket chat_gray](https://user-images.githubusercontent.com/19206966/99253519-2da0cc80-2811-11eb-9f3e-e6932c0c0a45.PNG)

If the problem occurs, only reloading (Ctrl + R) will help so that the view looks normal again.

Andreas

**Comment by mschering** [comment]
Happens for me too on MacOS. 
Even worse is that my input/output is not working while I do here sounds on events. It works in the browser.

**Comment by AmatorPhasma** [comment]
Happens for me too on Linux/MacOs/Windows 10 Prof. 1909 and 2004

**Comment by sandreddu** [comment]
I reported the same issue many days ago but so far seems to be ignored. This is quite annoying since our users rely heavily on the video call function.
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1841

**Comment by Attack44** [comment]
I installed version 2.17.11 again and wait until the problem is resolved.

**Comment by seppultra** [comment]
We hade a smiliar issue. It appeared after we upgraded Jitsi.
It was not a rocket.chat problem.
We went back to this Version: https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-4857
It was the last where this issue didnt show up.

I know. It's not a solution... but maybe it helps

**Comment by Attack44** [comment]
We have updated our Jitsi version from stable to the current unstable version. 
Up to now the problem with the current Rocket.Chat (3.0.7) version didn’t occur anymore.
