### ISSUE TITLE
Client start at boot not working after update to 3.0.7

### ISSUE THREAD

**Issue by Jonbj** [RocketChat/Rocket.Chat.Electron#1885]
## My Setup

- Operating System: windows 10 PRO
- App Version: 3.0.7
- Installation type: exe

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description
After update client to 3.0.7 version, startup at boot doesn't work. Windows ask to remove link to Rocket.Chat.exe becouse doesn't exist anymore. Installation path change and 

### Current Behavior
Afet client update, Windows ask to remove link to Rocket.Chat.exe becouse doesn't exist anymore. 
Installation path change and the original path is empty (C:\Program Files\Rocket.Chat).

### Expected Behavior
start at boot continue to work after upgraade client to 3.0.7

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
