### ISSUE TITLE
Font in the file manager is broken when save file

### ISSUE THREAD

**Issue by lukeproviderpl** [RocketChat/Rocket.Chat.Electron#1887]
### Description:

When I click the cloud icon to save the file, the file manager window has a broken font, this only happens for Rocket.Chat.Electron, other GTK applications run normally

### Steps to reproduce:

on a linux system using a desktop application try to save any file from the conversation with the help of the cloud icon

### Expected behavior:

a file manager window should open and display fonts correctly

### Actual behavior:

![save_icon](https://user-images.githubusercontent.com/46348462/99547011-5662c680-29b7-11eb-953f-221df6605076.png)
![file_menager](https://user-images.githubusercontent.com/46348462/99547033-5c58a780-29b7-11eb-94fa-985293a362b4.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: Ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 2

### Client Setup Information

- Desktop App or Browser Version: 3.0.1 from snap
- Operating System: KDE neon User Edition 5.20  rel.  20.04

**Comment by lukeproviderpl** [comment]
Edit: the same version installed with flatpack works fine

**Comment by skuehnemundt** [comment]
I have the same problem
I used edge and stable snap with both the error occurs, snap started via console 

Gtk-Message: 11:41:30.389: Failed to load module "xapp-gtk3-module"
Gtk-Message: 11:41:30.418: Failed to load module "colorreload-gtk-module"
Gtk-Message: 11:41:30.418: Failed to load module "window-decorations-gtk-module"

when opening the file manager 
Gtk-Message: 11:41:57.755: GtkDialog mapped without a transient parent. This is discouraged.

System: 
Manjaro / KDE

links to snapcraft.io
https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484
https://snapcraft.io/docs/gnome-3-28-extension

**Comment by raffaelone** [comment]
Same problem with the latest version 3.8.1

**Server Setup Information:**

- Version of Rocket.Chat Server: 4.5.5
- Operating System: Ubuntu Ubuntu 20.04.4 LTS
- Deployment Method: snap

**Client Setup Information**

- Desktop App or Browser Version: 3.8.1 from snap
- Operating System: Ubuntu Ubuntu 20.04.4 LTS

**Comment by finalclass** [comment]
I still have the issue. What was the solution?

**Comment by finalclass** [comment]
I've noticed that I was using a snap version. I've switched to the version that can be found in AUR (3.8.7-1) and it works fine now.

**Comment by TasyDevilsky** [comment]
It's not solution. I have this problem too with snap package `v. 3.8.13` already cleared font cache and didn't helped.
