### ISSUE TITLE
Getting Logged Out On Page Refresh

### ISSUE THREAD

**Issue by TheFrozenDuck** [RocketChat/Rocket.Chat.Electron#1889]
## My Setup

- Operating System: Linux Manjaro
- App Version: 3.0.7
- Installation type: AUR (maintainer: matthias.lisin) 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When forcing a reloading of the Electron application (via Ctrl + R) I get logged with the error message:
`Invalid user [error-invalid-user]` and get immediately logged out.

After logging in again I get a shortly visible message:

`No user with username <base64 string or something similar> was found!` 

### Current Behavior

Getting logged out.

### Expected Behavior

Not getting logged out.

**Comment by ankar84** [comment]
Strange, in my case logoff is only on` Shift+Ctrl+R`
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1864#issuecomment-722870350

**Comment by TheFrozenDuck** [comment]
I'm not entirely sure why, but I guess I just have a different key mapping. I will close this then due to being a duplicate.
