### ISSUE TITLE
Crashes On Win10 Instantly

### ISSUE THREAD

**Issue by starhound** [RocketChat/Rocket.Chat.Electron#1892]
## My Setup

- Operating System: Windows 10 Build 1909
- App Version: Latest as of 11/23/2020
- Installation type: MSI installer & windows unpacked

- [ X] I have tested with the latest version
- [ X] I can simulate the issue easily

## Description

Follow guidelines set in readme.md:
1) git clone
2) yarn
3) yarn release

### Current Behavior

Everything builds fine, no errors or issues (https://imgur.com/1ChH35Y), doing 'yarn start' runs the application fine as well (https://imgur.com/degxluQ).

The MSI installer reads setup failed (https://imgur.com/xzo0d5T), no error log produced or information regarding why. The windows unpacked exe doesn't load anything. 

No logs I can find, nothing in windows event viewer.

### Expected Behavior

App should load/run or produce output regarding why installation/loading failed.

Might be related to: 
> Checking for update
Update for version 3.1.0-snapshot is not available (latest version: 3.0.7, downgrade is disallowed).

Thank you for your time and help.

**Comment by starhound** [comment]
I should also note that both application types (the MSI and unpacked) were ran on a system which has never had any Rocket.Chat software installed on it previous. Same aborted setup issue.

**Comment by IhorNykyha** [comment]
@starhound look at this https://github.com/RocketChat/Rocket.Chat.Electron/issues/1804

**Comment by starhound** [comment]
Thank you, this is a duplicate issue. Closing now.
