### ISSUE TITLE
Feature request: option to hide menu bar icon on mac

### ISSUE THREAD

**Issue by julou** [RocketChat/Rocket.Chat.Electron#1894]
## My Setup

- Operating System: macOS 10.14.6
- App Version: 3.0.7
- Installation type: dmg

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description
It is not possible to hide app icon in the menu bar (aka tray).

### Current Behavior

The icon is always shown (with a rather useless menu)…

### Expected Behavior

Have an app settings allowing to show or not this menu bar icon (when disabled, only the Dock icon could be used).

**Comment by Kamik423** [comment]
I don't get why this is not default behavior

**Comment by lensco** [comment]
Not only is it completely pointless, it also displays a black icon in an otherwise white menu bar. 🤦🏻‍♂️

**Comment by fschuermeyer** [comment]
please Change this Behavior 😄

**Comment by BlkPingu** [comment]
any progress on this? I don't get why this icon exists

**Comment by jeanfbrito** [comment]
On the menu, click on View and then toggle the Tray Icon:
![image](https://user-images.githubusercontent.com/1177482/182957430-d4393bce-bcd6-4ad7-9cec-14099f437ae5.png)
