### ISSUE TITLE
How can I edit some of the style(sheet) of the application ?

### ISSUE THREAD

**Issue by Nono-m0le** [RocketChat/Rocket.Chat.Electron#1895]
## My Setup

- Operating System: Windows 10
- App Version: 3.0.7
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
We basically would like to know: 
1) How to achieve white background for the left menu, in a simple way, without having a custom stylesheet.
2) How to reduce the size of the Left Menu (It seems that it's using percentage, without max value, which end-up using 1/5 of my screen for just displaying the user/chatroom.)
This seems like a good value : 
![image](https://user-images.githubusercontent.com/3726435/100106051-59066580-2e68-11eb-9f26-cf4b47290f6f.png)

**Comment by ali-garajian** [comment]
@Nono-m0le Did you find any solution?

**Comment by Nono-m0le** [comment]
Hi @ali-garajian, no we didn't and basically abandoned the idea. I kept the ticket opened in case someone else find or is interested in a solution.
