### ISSUE TITLE
When highlithing someone, people are shown multiple times

### ISSUE THREAD

**Issue by Nono-m0le** [RocketChat/Rocket.Chat.Electron#1896]
## My Setup

- Operating System: Windows 10
- App Version: 3.0.7
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
when using @ the list show numerous time the same user.

### Current Behavior
When typping `@Sa` it shows three times user1 and two times user2
![image](https://user-images.githubusercontent.com/3726435/100106485-e0ec6f80-2e68-11eb-814c-8335d579ae27.png)

### Expected Behavior
Only showing once, user1 and user2

**Comment by ankar84** [comment]
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/19225

**Comment by Nono-m0le** [comment]
closing as duplicate
