### ISSUE TITLE
exe and msi installer dows not work on Arm64 Windows

### ISSUE THREAD

**Issue by chbwien** [RocketChat/Rocket.Chat.Electron#1897]
3.07 does NOT install correctly on Arm64 Windows editions, because the x64 edition will be installed and Arm64 can only handle the 32 Bit Version.

**Comment by jeanfbrito** [comment]
The .exe installer have the x86 and x64 builds inside. But I cant say if it will work on  Windows Arm64 Edition.
Please tell us if the issue continues. I will be closing the issue for now.

**Comment by chbwien** [comment]
If there was no recent change it still does not work, because the exe installer asks for the system settings and gets 64 bit (because arm64 is a x64 system). Therefore the installer installs the x64 version instead of the x86 (arm is only able to emulate x86 intel). If it helps I can check again with my device...

**Comment by chbwien** [comment]
I am working with Inno Installer. It's a difference if you ask IsWin64 (yes arm64 is Win64) or Is64BitInstallMode (no it is not, because Arm64 can only run in x86 mode).

**Comment by chbwien** [comment]
Just tried the exe installer of 3.7.5. It still installs the x64 version, that can't be run on an arm64 system. Ofcourse a native arm-edition (like teams, also electron based) would be the best solution.

**Comment by jeanfbrito** [comment]
A .msi separated for each architecture would fix your problem?

**Comment by chbwien** [comment]
You could also use one msi with both versions in it. But separated would also be ok. Currently, all Windows arm64 users need to use a tool like 7-zip, unpack the exe installer, get the 7-zip archive of the x86 version and copy it by hand. See our university download page at https://service.it.tuwien.ac.at/swsupport/tools/tuchat/index.html

Also a fix of the exe installer asking the right question would be very welcome.

**Comment by jeanfbrito** [comment]
> Also a fix of the exe installer asking the right question would be very welcome.

Didnt understood that. What is the right question? What do you mean?

**Comment by chbwien** [comment]
The nsis exe installer installs the x64 version on any arm64 system. So it only decides if the system is a 32 or 64 bit system. It does not check, if the 64 bit system is able to run the x64 code (and arm64 is not able to do this)
Maybe this nsis snippet helps: https://github.com/kichik/nsis/blob/master/Include/x64.nsh

**Comment by jeanfbrito** [comment]
Hello @chbwien this is solved with the `ia32` installer? I will close the issue but if needed tell me to open it again.

**Comment by chbwien** [comment]
Hi,
yes, this installer does the trick. A separate Arm64 edition would be nice, a fixed exe with the correct pick of 64/32 would also be appreciated.

But the ia32 edition is a workaround.
