### ISSUE TITLE
GPO deploy msi event ID error %%1603

### ISSUE THREAD

**Issue by Quarr** [RocketChat/Rocket.Chat.Electron#1898]
Hi

## My Setup

- Operating System: Widnwos Serwer 2016 / Widnwos 10 pro 
- App Version: 3.0.2 msi
- Installation type: GPO deploy

- [X] I have tested with the latest version 
- [ ] I can simulate the issue easily

## Description
After deploy In event viewer I can found this error

  **<EventID Qualifiers="0">108</EventID>** 

  **<EventID Qualifiers="0">103</EventID>** 

  **<EventID Qualifiers="0">101</EventID>** 
 

In the same time from this same politics, I deploy microsoft teams, and zoom,they install without problems. Thge all msi package I have in the same shared place.

What I can check more, then I just fount and readed on MS docs?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
