### ISSUE TITLE
Packages of latest client increasingly hard to find

### ISSUE THREAD

**Issue by lproven** [RocketChat/Rocket.Chat.Electron#1899]
Just months ago, I could download native Linux binaries from your website: https://rocket.chat/install

Then they were removed, leaving only the option of a Snap. I am running openSUSE which does not have native Snap support. I added it and tried the Snap version. I encountered issues -- forgetting my login settings, no icon in my launch menu, other relatively small things. 

I went back to the RPM. It installs and runs perfectly on openSUSE if I ignore dependences, and integrates better than the Snap.

Today I checked and discovered I was running an outdated version. So I went to Github to download the latest and meanwhile removed my local installation.

However, you have renamed it. It is now called Rocket.chat.electron. 

So, I thought I would go and give the Snap another try. I did a `snap search rocketchat` command and found only a version much older than the one I was looking for: I wanted 3.0.7 and Snap only offers 3.0.1.

Next I used the link on your site to go to: https://snapcraft.io/rocketchat-desktop

But this still only offers me 3.0.1 and was last updated 2nd October, nearly 2 months ago. You have released **six**  minor versions since then.

If you wish to force users to use the Snap package, OK. I do not like it but it is your choice. I would prefer the native package and a straightforward link to it from your website would be helpful. 

Request 1: If possible, please restore your original site functionality. Offer a link to the latest version.

Request 2: if you make major changes such as renaming it, please _mention this on the download page._ Otherwise you confuse your users, as you just did me. (I initially downloaded the server looking for newer, then the source of the server. An unmentioned name change is very unhelpful.)

Request 3: if you have solid technical reasons for only allowing people to download the Snap, then OK. But if you force people to use the Snap, you really **need** to keep the Snap current!

Request 4: if there are real insurmountable technical reasons why you cannot update the Snap, **say so**. Please keep your users informed. For instance, say "we recommend the Snap package for {this list of reasons}. The latest Snap version is {current Snap version}. If you really need the native package, the latest is {native package version} and you can get it from https://github.com/RocketChat/Rocket.Chat.Electron/releases."

**Comment by ankar84** [comment]
I'm not agree with your topic. **Latest release always available here** https://github.com/RocketChat/Rocket.Chat.Electron/releases/latest

**Comment by lproven** [comment]
No. I am making 2 core points here and you are not responding to either of them.

Point #1: the Github download page should be linked from https://rocket.chat/install but this was recently removed.

Point #2: if https://rocket.chat/install promotes the Snap version then it is essential that the Snap version is kept up to date. It is not. It is currently 6 releases behind.

**Comment by xmedeko** [comment]
Yes, the Snap `stable` channel is far behind current stable release, see https://snapcraft.io/rocketchat-desktop
Furthermore, `beta` and `candidate` releases seems unmaintained. 
The only actual channel seems `edge` but it's unstable.

Please, do some automatic update of Snap `stable` channel after each stable release.
And remove `beta` and `candidate` releases or do update them, too.

**Comment by dlecan** [comment]
Is it possible to update the Snap package?
Thank you

**Comment by xmedeko** [comment]
The Flatpack version seems up to date https://flathub.org/apps/details/chat.rocket.RocketChat
However, the offical recommendation is to use Snapcraft https://rocket.chat/install/

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
