### ISSUE TITLE
Mac App Store

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat.Electron#19]
Depends on https://github.com/atom/electron/issues/249

**Comment by engelgabriel** [comment]
There is light in the end of the tunnel!

http://www.saschawise.com/blog/2015/08/12/electron-for-the-mac-app-store.html

**Comment by engelgabriel** [comment]
https://github.com/atom/electron/pull/2920

**Comment by rodrigok** [comment]
https://github.com/atom/electron/blob/master/docs%2Ftutorial%2Fmac-app-store-submission-guide.md

**Comment by rodrigok** [comment]
\o/
