### ISSUE TITLE
Minimum width in split view on OS X is 600pt

### ISSUE THREAD

**Issue by zzt4** [RocketChat/Rocket.Chat.Electron#190]
## My Setup

- **Mac OS X 10.10.4**: 
- **Rocket.Chat 1.3.1 (15)**: 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

When using the app on OS X in Split View, the smallest width the app supports is 600pt. It seems as though Rocket.Chat is built to support a minimum width of 400pt. I would expect that the electron app would support that same minimum width in Split View mode on Mac OS X. I didn't see any glaring issues with using the app in a 400pt wide Google Chrome window.
#### Current Behavior

App window has a minimum width of 600pt.
#### Expected Behavior

App window has a minimum width of 400pt.
##

**Comment by NitinBhasneria** [comment]
@gdelavald  Can I take this issue?

**Comment by NitinBhasneria** [comment]
@zzt4  Can I take this issue?

**Comment by zzt4** [comment]
@NitinBhasneria sure!

**Comment by NitinBhasneria** [comment]
@zzt4 Thank you. Can you please tell me the prerequisites things that I should learn before contributing.

**Comment by TaimurAzhar** [comment]
Hi, I have fixed this issue and am creating a pull request for it.
