### ISSUE TITLE
Emoji are not displayed in fields

### ISSUE THREAD

**Issue by BorzdeG** [RocketChat/Rocket.Chat.Electron#1900]
## My Setup

- Operating System: MacOS Big Sur
- App Version: 3.0.7
- Installation type: brew

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
send hook JSON:
```
{
	"alias": "Example bot",
	"text":":flag_it: Example message",
	"attachments":[
		{
			"title":"Example message",
			"text":":flag_it: Rocket.Chat, the best open source chat",
			"fields": [
				{
					"title": "Country",
					"value": ":flag_it: Italy",
					"short": true
				}
			]
		}
	]
	}
```

### Current Behavior
![image](https://user-images.githubusercontent.com/2332528/100536310-cf241700-3230-11eb-9f56-6f83f02b5092.png)

### Expected Behavior
The flag will also be shown in the field, as in the rest of the text blocks

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
