### ISSUE TITLE
Can not start camera during call

### ISSUE THREAD

**Issue by jemshid** [RocketChat/Rocket.Chat.Electron#1903]
Webcam is working in the browser, but not in the Linux client.
Clicking on the camera icon gives the following error.

```
Х
Webcam settings
NotFoundError: Requested device not found
Cancel
Start sharing

```

## My Setup

- Linux k 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Ubuntu 20.04.1 LTS
- Version 3.0.1

**Comment by ankar84** [comment]
First try latest version https://github.com/RocketChat/Rocket.Chat.Electron/releases/latest
