### ISSUE TITLE
"Show on unread messages" breaks app silently

### ISSUE THREAD

**Issue by mleczakm** [RocketChat/Rocket.Chat.Electron#1904]
## My Setup

- Operating System: Kubuntu 20.04
- App Version: 3.0.1
- Installation type: snap

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
On new message, if "Window -> Show on unread messages" is checked, when app is not in foreground and new message comes it turns off silently.

### Expected Behavior
It should came into foreground.

**Comment by TazerReloaded** [comment]
Confirmed on Ubuntu 20.04.2 LTS, App disappears completely, could not find any related log entries, it just closes and needs to be restarted manually. That's quite the opposite of what that feature should do.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
