### ISSUE TITLE
[Bug] When application is minimized to tray and user gets new messages, chat opens somewhere in history

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1906]
## My Setup

- Operating System: WIndows 10
- App Version: 3.0.7
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When application is minimized to system tray and user gets new messages, chat opens somewhere in history, but not on recent messages

### Current Behavior
Here is a screencast.
1. I show recent messages (did them from iPhone tapping on predictions)
2. I minimize application to system tray by pressing X sign in right top corner
3. I write 3 more messages same way as in 1
4. Click on application icon in system tray
5. You can see, that first chat appeared somewhere in history and I need to scroll down to recent messages.
![history_on_new](https://user-images.githubusercontent.com/4023037/101322576-52201f80-3878-11eb-8a37-6e58a177a4dc.gif)

### Expected Behavior
New messages should open

**Comment by alireza-salehi** [comment]
#1835

**Comment by ankar84** [comment]
duplicate on #1835
