### ISSUE TITLE
Disk usage increases significantly when dragging client #19799 #19800

### ISSUE THREAD

**Issue by nhh** [RocketChat/Rocket.Chat.Electron#1908]
### Description:

Install rocket chat as a windows app. Move window around. You will see that the window stutters slightly and in Taskmanager you will see an increased disk usage when moving the window.

(My guess is that the window position triggers some handler that writes back logs or tracking things...)

### Steps to reproduce:

1. Install Rocket Chat
2. Open Rocket Chat
3. Open Task Manager
4. Move window slightly and check for increased disk usage.

### Expected behavior:

No tracking of window location AND no disk usage when dragging the window.

### Actual behavior:

Lagging, up to 3MB/s disk usage when moving.

### Client Setup Information

- Desktop App
- Operating System: Windows 10

### Server Setup Information
Does not belong here, its a client only issue

### Version of Rocket.Chat Server
Does not belong here, its a client only issue

![Screenshot 2020-12-08 102327](https://user-images.githubusercontent.com/13472382/101464813-6f6bf100-393f-11eb-8fae-f2fe721d71c0.png)

**Comment by ankar84** [comment]
I don't know. Did try to reproduce that issue without luck. 
In my case disk load was grow up a little bit to 0.5MB/s when I moved application up and down.

**Comment by nhh** [comment]
Okay, even 0.5 MB/s seem like a lot of data to me for simply dragging the client, what do you think?

I would expect zero mb/s unless there is a feature that relies on this behavior

**Comment by nhh** [comment]
Within %appdata%/Rocket.Chat there is a config.json which contains this.

```json
	"rootWindowState": {
		"focused": false,
		"visible": true,
		"maximized": false,
		"minimized": false,
		"fullscreen": false,
		"normal": true,
		"bounds": {
			"x": 30,
			"y": 302,
			"width": 1000,
			"height": 584
		}
	}
```

When dragging the window i see a lot of temporary config files being created and flickering. I guess thats related to the bounds with the json. The is most likely an event handler which updates that json on window move

**Comment by nhh** [comment]
I did a small screenrecording for reproducing the issue:

[2020-12-09 11-55-08_Trim.zip](https://github.com/RocketChat/Rocket.Chat.Electron/files/5665382/2020-12-09.11-55-08_Trim.zip)

**Comment by jcrower** [comment]
We see this issue as well with 3.0.7 (on Win10).

If you look in perfmon you see dozens of config.json.tmpXXXX files appearing.

Also see this in perfmon:

![Clipboard01](https://user-images.githubusercontent.com/66984454/101705016-efc45a80-3ad5-11eb-85f5-8747b3f8e440.jpg)

**Comment by CitizenDev** [comment]
This client has various performance issues, Resizing window also causes my CPU usage to 100% for few seconds
Version 3.1

**Comment by nhh** [comment]
I will take a look today if i can fix this. 

For clarification, what is the expected behavior?

I would specify this as: The client is able to reconstruct its position and size without causing significant cpu or disk consumption. (Debouncing at every 5 seconds so that at a maximum every 5 seconds the new metadata gets written to disk)

**Comment by Zylann** [comment]
This happens to me as well on Windows, using version 3.1.1. When I drag the window, it is extremely laggy, and when I look in the task manager it uses one CPU core to the maximum and writes stuff to disk (about 0.7 Mb per second). Sometimes it seems to drag smoothly, and then eventually freezes completely, maxing out CPU, similarly to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1605

**Comment by mikhey** [comment]
Came across this issue as I experienced dragging a window felt like a Win95 laggolicious throwback.  When you combine the increase in disk I/O with this AV like McAfee - it may even make the experience even worse. 

Is there a way to drop writing to the config file _during_ the move and have it write an update on a `onMoveEnd` type of event? That would certainly cut down on disk I/O and potentially resolve the issue

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by CitizenDev** [comment]
> Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.
> 
> Thank you!

Cmon man. Bugs don't magically disappear. You could have at least tested it yourself before closing the issue. It takes less than a minute.
Issue still persists in latest ver 3.8.5 release WIN 10 PRO.

Moving and/or resizing windows spikes resource use massively (CPU mostly) and slows down entire system.

**Comment by jeanfbrito** [comment]
Hello @CitizenDev we can test when we have the issue, but we have already added a debounce to saving the config file. The disk I/O has been reduced drastically.
If the problem continues after 3.8.5 you need to give us more information to see what is happening on your machine.

**Comment by jeanfbrito** [comment]
@CitizenDev CPU intensive is the rendering of Electron/Chromium and we cant do anything relevant about it. What machine are you using? Please provide information at least.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
