### ISSUE TITLE
rocketchat-v1.3.1-win32-ia32.exe contains x64 binary

### ISSUE THREAD

**Issue by mi-go** [RocketChat/Rocket.Chat.Electron#191]
## My Setup

- **My OS name and version**: Windows 7(32bit), Windows 10 Home(64bit)
- **My current app version**: rocketchat-v1.3.1-win32-ia32.exe 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

rocketchat-v1.3.1-win32-ia32.exe contains amd64 binary.
rocketchat-v1.3.1-win32-ia32.exe should be installed to Windows (x86 32bit), but it could not be.

Then, I tried to install it to Windows (x64 64bit), and succeeded.
So I opened Rocket.Chat+.exe by binary editor to check it, and I found the charactors next to 0x50450000 are 0x64, 0x86.
0x6486 means x64 binary.

#### Current Behavior

rocketchat-v1.3.1-win32-ia32.exe cannot be installed to Windows(32bit)

#### Expected Behavior

rocketchat-v1.3.1-win32-ia32.exe can be installed to Windows(32bit)

##

**Comment by leandroqm** [comment]
I can confirm the bug.

**Comment by leandroqm** [comment]
Hey guys!
Any news on this?
There are some windows users that really need this to be solved! ;)

**Comment by AlexHaxe** [comment]
Same here, Version 1.3.0 works but 1.3.1 (32bit) is broken on Windows 7

**Comment by leandroqm** [comment]
It is still broken, vide https://github.com/RocketChat/Rocket.Chat/issues/3949 .

**Comment by engelgabriel** [comment]
Fixed using electron-rebuild so the installer has both binaries for install.
