### ISSUE TITLE
Rocket.Chat doesnt open after building and installing

### ISSUE THREAD

**Issue by timololipop** [RocketChat/Rocket.Chat.Electron#1917]
Hey,

when I start the App via "yarn start" it opens and it's usable. When I do "yarn release" everything works fine and the exe's are in the dist folder. But when I go through the installer and want to start it after it is installed successfully, nothing happens. Dont got any errors in the CMD window while building.

**Comment by nos03** [comment]
I have the same problem

**Comment by taihoa** [comment]
I have the same problem

**Comment by Luke-CSE** [comment]
I've faced some issues with this aswell, for me the following procedure worked:

- git clone the master branch
- change line 15 of the rollup.config.js from development to production (const NODE_ENV = process.env.NODE_ENV || '**production**';)
- change the "yarn release" command at the package.json at line 27 from onTagOrDraft to never, so the electron-builder does not try to upload any files. ("release": "yarn electron-builder --publish **never** --x64",)
- run "yarn" to build the node modules
- run "yarn build" to build the app
- run "yarn start" or "yarn release" to test or release the app

**Comment by taihoa** [comment]
> I've faced some issues with this aswell, for me the following procedure worked:
> 
> * git clone the master branch
> * change line 15 of the rollup.config.js from development to production (const NODE_ENV = process.env.NODE_ENV || '**production**';)
> * change the "yarn release" command at the package.json at line 27 from onTagOrDraft to never, so the electron-builder does not try to upload any files. ("release": "yarn electron-builder --publish **never** --x64",)
> * run "yarn" to build the node modules
> * run "yarn build" to build the app
> * run "yarn start" or "yarn release" to test or release the app
It worked.
Thank you very much!

**Comment by ValterSilvaJr** [comment]
> 
> 
> I've faced some issues with this aswell, for me the following procedure worked:
> 
>     * git clone the master branch
> 
>     * change line 15 of the rollup.config.js from development to production (const NODE_ENV = process.env.NODE_ENV || '**production**';)
> 
>     * change the "yarn release" command at the package.json at line 27 from onTagOrDraft to never, so the electron-builder does not try to upload any files. ("release": "yarn electron-builder --publish **never** --x64",)
> 
>     * run "yarn" to build the node modules
> 
>     * run "yarn build" to build the app
> 
>     * run "yarn start" or "yarn release" to test or release the app

Same problem here, in addition, i have add package cross-env and create two scripts in package.json:

Dependency for environment variables in script execution.
> "cross-env": "^7.0.3"

Production (I think "start" command run per default after packaging, need confirmation)
>     "start": "run-s clean build:watch"

Development:
>     "dev": "cross-env NODE_ENV=development run-s clean build:watch"

i have tested and the result created two files in:
> C:\Users\YOU_USER\AppData\Roaming

Rocket.Chat and Rocket.Chat(development). Before, the production file has empty.

This was the solution i found, i don't know if it is the best, but it solved it. I hope I have helped you in something. Sorry for the english.

**Comment by kuraga** [comment]
> change line 15 of the rollup.config.js from development to production
> ```javascript
> const NODE_ENV = process.env.NODE_ENV || 'production';
> ```

Which does `NODE_ENV` mean?

1. The environment we are _building in_.
2. The environment we are _packing for_.
