### ISSUE TITLE
Rocket.Chat grey after starting Video Call

### ISSUE THREAD

**Issue by saschawinandy** [RocketChat/Rocket.Chat.Electron#1918]
Hey,

#Setup
- Operating System: Windows 10
- App Version: 3.0.7
- Installation type: msi
- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When I start a new video call (there is a Jitsi-Meet instance behind) the Rocket.Chat window becomes gray and no information is visible. After reload (ctrl+R) everything is visible again. This bug is new with V3.x.x . Older versions (2.x.x) work proper.

![image](https://user-images.githubusercontent.com/76199408/102585556-e4da7d00-4108-11eb-95e8-62191c49825a.png)

Rocket.Chat window:
![image](https://user-images.githubusercontent.com/76199408/102586199-fa9c7200-4109-11eb-8d57-0c7cb2283570.png)

### Current Behavior
Content in Rocket.Chat window is not visible after video call is started

### Expected Behavior
Content in Rocket.Chat window should be visible after starting a video call

**Comment by ankar84** [comment]
fixed in https://github.com/RocketChat/Rocket.Chat.Electron/pull/1902

**Comment by saschawinandy** [comment]
thanks for quick comment. I'll close that issue.
