### ISSUE TITLE
3.1.0 Download Manager lacks "Close" function

### ISSUE THREAD

**Issue by klou** [RocketChat/Rocket.Chat.Electron#1921]
- Operating System: Win 10 1909
- App Version: 3.1.0
- Installation type: exe

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description
When open, the Download Manager doesn't have an easy or obvious way to close and return to the main Conversation window.

### Current Behavior
Open the Download Manager via Menu -> Window -> Downloads.

There isn't a "close" button, or [X] to close the Download Manager and return to the main Conversation.

In addition, Menu -> Window -> Downloads is NOT checked.

The only way to return to the Conversation is Menu -> Window -> <Server Name>.

### Expected Behavior
An [X] button similar to what's seen on the Administration Panel would be much more obvious.  And it should be marked in Window -> Downloads if it is the active view.

**Comment by ankar84** [comment]
Try CTRL+1 or just Windows - Select your server
![image](https://user-images.githubusercontent.com/4023037/102870562-3ad35b80-444e-11eb-92e5-6cf69daa1311.png)

Or another workaround - At View enable Server List, then in a bottom you will see Download manager and you can switch between your server and Download manager easy.
![image](https://user-images.githubusercontent.com/4023037/102870636-576f9380-444e-11eb-85d8-7b3a982af3ce.png)

![image](https://user-images.githubusercontent.com/4023037/102870600-4888e100-444e-11eb-8036-a648e3323bca.png)

**Comment by ggazzo** [comment]
this is not a modal that you can close, try navigate back, or click on another server
