### ISSUE TITLE
[Bug] After upgrade from 3.0.7 to 3.1.0 all servers are logout

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1922]
## My Setup

- Operating System: Windows 10
- App Version: 3.1.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I updated my desktop client with few servers setup from version 3.0.7 to version 3.1.0 and when I launched new version - all servers was on login page, all servers was logged me off.
And I think all other settings was reset to defaults - I use dark mode, and it was set to dark mode - after upgrade I have normal (light) mode set

### Current Behavior
Users are log off from all servers after 3.1.0 update.

### Expected Behavior
All logged in servers should remain logged in.
All users settings should remain.

**Comment by nrenich** [comment]
Same result with Mac client. Connected to three Rocket Chat servers, all reset.

**Comment by pixxelspotter** [comment]
Same on Linux

**Comment by ankar84** [comment]
After upgrade 3.1.0 => 3.1.1 all servers remain logged in.

**Comment by klou** [comment]
3.0.7 -> 3.1.1 servers remain logged in.

**Comment by ankar84** [comment]
Closing that issue because update for 3.1.x to any new 3.X.X versions works without logout.
And updates from more old versions seem to be unfixable.
