### ISSUE TITLE
Não consigo enviar nem receber mensagens

### ISSUE THREAD

**Issue by joaovitor-git** [RocketChat/Rocket.Chat.Electron#1924]
In version 3.0.6 it is not possible to send messages, when you click "Send" they are "gray" and not sent, so you need to reload the server to send and receive messages, I have downgraded from previous versions and the problem continues, can someone please to help?

**Comment by ggazzo** [comment]
this is probably something related with the server and I'm confident we fixed long time ago ;)

**Comment by lidernetworktecnologia** [comment]
Estou com esse problema tambem já tem o erro relatado aqui #1938. Estou usando a ultima versao baixada direto do site. Alguem tem uma solução?
