### ISSUE TITLE
Feature Request: Ability to "Undock" Roster from Chat

### ISSUE THREAD

**Issue by MJPGPleasant** [RocketChat/Rocket.Chat.Electron#1927]
## My Setup

- Operating System: Windows 10
- App Version: 3.0.7
- Installation type: MSI

## Description

I have had several people request the ability to be able to separate the Chat Roster from the Conversation Pane. This could be further expanded to include different windows for different conversations.

I am not sure if this work would be isolated to the client app, or would required coordination / implementation server side.

**Comment by MJPGPleasant** [comment]
In the web interface it is possible to have multiple windows / tabs open in parallel, although each window has its own chat roster.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
