### ISSUE TITLE
Chat looses code indentation

### ISSUE THREAD

**Issue by gmnevton** [RocketChat/Rocket.Chat.Electron#1928]
## My Setup

- Operating System: Windows 10 Home x64
- App Version: 3.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Pasting formatted text into chat and selecting it as code, and posting it, results in indentation lose.

### Current Behavior
Formatted text is not preserved with its formatting.
Posting eg.: 
```
if [A] = '0' {
  if [B] <> '0' {
    '00'
  } else {
    [A]
  }
} else {
  [A]
}  
```
results in:
```
if [A] = '0' {
if [B] <> '0' {
'00'
} else {
[A]
}
} else {
[A]
}
```

### Expected Behavior
Expecting that formatted text will retain its format and maybe even will be presented in some special way easily recognizable as part of structured text/code.

**Comment by ggazzo** [comment]
I could not reproduce, but anyway the right place for this kind of issue is here : https://github.com/RocketChat/Rocket.Chat
