### ISSUE TITLE
Some users using the windows desktop app are not able to download files to their local drive

### ISSUE THREAD

**Issue by yoni-it** [RocketChat/Rocket.Chat.Electron#1930]
## My Setup

- Operating System: Windows 8.1
- App Version: 3.0.3
- Installation type: EXE

## Description

Downloading attached files through the windows desktop client won't work. However, using a browser we see no problem downloading the files.

### Current Behavior

Can not download attached files.

### Expected Behavior

I should be able to download files by clicking the cloud symbol download button or by going through the files button.

I have also attached the server info I downloaded from the administration panel for reference. 
Thank you RocketChat for providing us great tool for free.

[statistics.txt](https://github.com/RocketChat/Rocket.Chat.Electron/files/5741252/statistics.txt)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
