### ISSUE TITLE
Rocket.Chat from the Mac App Store is multiple versions out of date

### ISSUE THREAD

**Issue by andylin2004** [RocketChat/Rocket.Chat.Electron#1931]
## My Setup

- Operating System: macOS Big Sur 11.3.1
- App Version: 3.0.3
- Installation type: Mac App Store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Mac App Store offers Rocket.Chat 3.0.3 as the latest version when Rocket.Chat 3.2.2 is the latest version.

### Current Behavior
Mac App Store offers Rocket.Chat 3.0.3 as the latest version

### Expected Behavior
Mac App Store offers Rocket.Chat 3.2.2 as the latest version

**Comment by compuguy** [comment]
This is still an issue. The app store version is still 3.0.3 when the latest is 3.1.1.

**Comment by Vkat14** [comment]
Can we please get some Eyes on this and PUSH the MAC store app to 3.1.1

**Comment by alexander-potemkin** [comment]
Let's put it the other way: it's half of the year out of date :godmode:

**Comment by AmatorPhasma** [comment]
"Its dead Jim"

**Comment by alexander-potemkin** [comment]
I worked around managing to find Mac app from the site. But, otherwise, considering to switch to MatterMost, as RocketChat is too many bugs out of the properly work instrument.

**Comment by Ein-Tim** [comment]
The App Store also shows version 3.0.0 as the latest version but the version shown in Rocket.Chat is 3.0.3. 🤔

**Comment by compuguy** [comment]
As of this comment, the Rocket.Chat app is still stuck at version 3.0.0....

**Comment by andylin2004** [comment]
Technically 3.0.3, but the fact that it is left as 3.0.0 really reflects on the failure to update rocket.chat.

**Comment by Apfelpom** [comment]
The AppStore Version is the only one with the right macOS security entitlements for accessing video and audio (Jitsi integration or audio recording) but still crash in the actually accessible MAS v3.0.3. The v.3.x DMG/pkg distributions (actually v3.5) are missing them, therefore they crash as soon as audio or video is involved: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1912#issuecomment-877281039

**Comment by felixspitzer** [comment]
Please update! AppStore is still on 3.0.0 and will not receive updates

**Comment by jeanfbrito** [comment]
Apple changed the requirements to be able to update the app on Apple Store.
We will be working on this in the next weeks.

**Comment by andylin2004** [comment]
> Apple changed the requirements to be able to update the app on Apple Store.
> We will be working on this in the next weeks.

Is there anything in specific that prevents the app from being compiled for the App Store?\

**Comment by jeanfbrito** [comment]
I'm investigating yet, but we will need to implement a login with Apple Account if I'm not wrong.
I don't know if they will accept our live update too, maybe we will need to disable it on the Apple Store version too.
But I'm not sure about each requirement yet.

You can install the released DMG from Github that will work right now.

**Comment by andylin2004** [comment]
They will definitely ask you to remove the auto update mechanism.

**Comment by Marx1st** [comment]
> I'm investigating yet, but we will need to implement a login with Apple Account if I'm not wrong. I don't know if they will accept our live update too, maybe we will need to disable it on the Apple Store version too. But I'm not sure about each requirement yet.
> 
> You can install the released DMG from Github that will work right now.

Why don't you link that version on the web page? Using the very outdated "official" App Store version really puts a bad light on Rocket.Chat.

**Comment by jeanfbrito** [comment]
The Apple Store version is updated, you can install it from there right now.
