### ISSUE TITLE
Windows Client does not update automatecaly

### ISSUE THREAD

**Issue by horvan** [RocketChat/Rocket.Chat.Electron#1932]
## My Setup

- Operating System: Windows 10
- App Version: 3.x
- Installation type: 
exe

- [ ] I have tested with the latest version
- [x ] I can simulate the issue easily

### Current Behavior

When a new version comes up, there is an information dialoug about an update. After clikcing the update button there is a new dialoug saying that the user get's informed about the update, wehn it is downloaded. Since several version that is the regular behaviour
### Expected Behavior
After the process above the programm should download the new exe file close itself and start the exe file to update the programm. By now only manual downloads  are working. for since several releases..

I think this should be fixed asap.

**Comment by ankar84** [comment]
Same as 
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1916
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1871
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1876
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1837
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1205
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1788
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1674
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1683
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1665
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1733
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1807
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1865

But most informative IMHO is https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670
@tassoevan maybe some of that issues need to be pinned?

**Comment by ankar84** [comment]
Closing in favor of RocketChat/Rocket.Chat.Electron#1670
