### ISSUE TITLE
Attachments - Clicking on link results in 403 Access Denied error

### ISSUE THREAD

**Issue by MJPGPleasant** [RocketChat/Rocket.Chat.Electron#1933]
## My Setup

- Operating System: Windows 10
- App Version: 3.1.0
- Installation type: MSI

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Clicking on the link above an attachment / image results in a new browser window with a "403: Access Denied" error

![image](https://user-images.githubusercontent.com/73244744/103311760-6c14d400-49d8-11eb-892e-c3e5ba1ddf75.png)

Note the Cloud icon beside the link works as expected, as does clicking on the link through the web interface (in the case above downloads a .png file)

This is likely caused by the fact that the Desktop client is spawning a new browser window that does not have authentication to the server to retrieve the specified file.  

### Current Behavior

New browser window with "403: Access Denied"

### Expected Behavior

File should be download / displayed.

**Comment by lukeproviderpl** [comment]
same here 
App | 3.9.3 from flatpak

after clicking the cloud icon, the file downloads correctly, but clicking on the name takes you to the browser with the error code 403

**Comment by ankar84** [comment]
It's not desktop application problem itself.
It's file security related issue.
![image](https://user-images.githubusercontent.com/4023037/103347468-26274100-4aa8-11eb-867f-62aa0cfc28b1.png)
You can disable that setting and link will work.
Or you can authenticate in your default browser (which opens that link) and you don't get that error - file will open.

**Comment by lukeproviderpl** [comment]
then it makes more sense to show a login page rather than a 403?

**Comment by ankar84** [comment]
> then it makes more sense to show a login page rather than a 403?

Maybe, but 403 means Forbidden and most time it's about access to resource.

**Comment by ER-EPR** [comment]
> then it makes more sense to show a login page rather than a 403?

I hope it can change to login page. It's really not friendly for common users except for a IT expert.
