### ISSUE TITLE
[Bug] When reset zoom, click room/user on sidebar display white screen

### ISSUE THREAD

**Issue by hieule2ntq** [RocketChat/Rocket.Chat.Electron#1936]
## My Setup

- Operating System: Mac
- App Version: 3.0.0-develop
- Installation type: development (yarn start)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

1. Change zoom level (zoom in or zoom out) via hot key or via `View` menu.
2. Reset zoom by press `Ctrl` + `0`
3. Click on room name or user name in sidebar -> show blank screen

![Screen Shot 2021-01-04 at 10 55 57](https://user-images.githubusercontent.com/55223993/103499723-b0422180-4e7b-11eb-9417-3baf95245ab2.png)

4. Change zoom level again, app show normal

### Current Behavior

Show blank screen

### Expected Behavior

Use app normal

**Comment by vuongtaquoc** [comment]
This error occurred on version 3.x.x and it happens with webview. I have resolved the issue in pull request #1946 by just zooming for webview content and it has been working properly!!!

**Comment by ankar84** [comment]
Confirm that issue!

**Comment by ankar84** [comment]
Confirm that issue is fixed by #1947
