### ISSUE TITLE
Rochet.chat não entrega mensagem e omnichannel desliga sozinho antes do horário configurado URGENTE

### ISSUE THREAD

**Issue by laisafcardoso** [RocketChat/Rocket.Chat.Electron#1938]
Prezados Boa Tarde!

Estamos com dois problemas gravissímos com a ferramente do rocket.chat desde do dia 22/12/2020:

1 - Problema de latência na entrega das mensagem: as mensagens não são entregues de forma simultânea entre os usuários, somente quando se atualiza a página. Para ver se um usuário enviou algo também é necessário ficar atualizando a página toda hora. Segue em anexo o vídeo mensagens_nao_entregues.mp4 para exemplificar.

https://user-images.githubusercontent.com/4176370/103573620-4e9aab00-4ead-11eb-85d8-33af9d16f309.mp4

2 - O omnichannel esta desligando as 16h00 (4 p.m), sendo que o mesmo esta configurado para funcionar até as 19h00 (7 p.m).
Na aba Businnes Hours configuramos para que o chat funcione das 9h00 (9 a.m) às 19h00 (7 p.m), mas o mesmo desliga sozinho as 16h00 (4 p.m) e não conseguimos mais ligar. Segue em anexo o vídeo o omnichannel_nao_liga.mp4 para exemplificar.

https://user-images.githubusercontent.com/4176370/103573500-1bf0b280-4ead-11eb-853d-d4d9daf34186.mp4

Estamos em busca de uma solução urgênte, pois o único meio e comunicação dentro da nossa instituição é pelo rocket.chat.
Estamos com toda a comunicação interna da empresa comprometida. TODA.
Nosso negócio depende disso na pandemia, e está comprometido.

Já foi aberto chamados com a rocket.chat e também com a TOTVS, mas até o momento não tivemos nenhuma solução, por isso estamos também tentando através desse canal, pois estamos sendo muito prejudicados com o problema.

Chamado junto a rocket.chat: 24403 
Chamados abertos na TOTVS: 10502505 / 10448427 / 10504970 / 10509566

## My Setup

- Operating System: Linux
- App Version:  3.9.3
--
- Installation type: 

- [ ] I have tested with the latest version - Não. O servidor não é de nossa responsabilidade, é de responsabilidade da rocket.chat em parceira com a TOTVS
- [ ] I can simulate the issue easily

### Current Behavior

1 - Problema de latência na entrega das mensagem: as mensagens não são entregues de forma simultânea entre os usuários, somente quando se atualiza a página. Para ver se um usuário enviou algo também é necessário ficar atualizando a página toda hora. Segue em anexo o vídeo mensagens_nao_entregues.mp4 para exemplificar.
2 - O omnichannel esta desligando as 16h00 (4 p.m), sendo que o mesmo esta configurado para funcionar até as 19h00 (7 p.m).
Na aba Businnes Hours configuramos para que o chat funcione das 9h00 (9 a.m) às 19h00 (7 p.m), mas o mesmo desliga sozinho as 16h00 e não conseguimos mais ligar. Segue em anexo o vídeo o omnichannel_nao_liga.mp4 para exemplificar.

### Expected Behavior

- Mensagens tinha que ser entregues normalmente como era antes de atualizar para versão 3.9.3 (antes era versão 3.6.2)
- Omnichannel deveria respeitar o horário de funcionamento.

**Comment by ggazzo** [comment]
Sorry the delay, I'm closing this issue since the problem its not related with the desktop itself , I hope you got your support

**Comment by geekgonecrazy** [comment]
Seems issue is now opened here: https://github.com/RocketChat/Rocket.Chat/issues/25228
