### ISSUE TITLE
Shift-Clicking in room list causes app to grey out

### ISSUE THREAD

**Issue by MJPGPleasant** [RocketChat/Rocket.Chat.Electron#1939]
## My Setup

- Operating System: Windows 10
- App Version: 3.10
- Installation type: MSI

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Shift-Clicking rooms in the desktop app causes the entire window to revert to the list background color and requires a quit / restart to restore. Our previous chat app used this method to select multiple and initiate group chats so we regularly have people crashing the app this way.

### Current Behavior

![image](https://user-images.githubusercontent.com/73244744/103580591-b7772880-4e97-11eb-9ce8-ff0944c035d3.png)

### Expected Behavior

Ideally open up a new window similar to the web interface. At the very least it should leave the app in a functional state.

**Comment by apaarfus** [comment]
I was just able to replicate this on my installation as well:

- Operating System: `Windows 10 Pro (20H2) x64`
- App Version: `3.1.1`
- Installation Type: `EXE`

With any luck, I've attached a quick clip as an example of the reported behavior, in case it isn't exactly obvious in MJPGPleasant's description/screenshot -- apologies for the blurring.

https://user-images.githubusercontent.com/38731016/105084610-8fc1bc00-5a64-11eb-8548-05b90fe068fb.mp4

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
