### ISSUE TITLE
Messages not immediately visible after sending or retrieving

### ISSUE THREAD

**Issue by BrianTimmermans** [RocketChat/Rocket.Chat.Electron#1940]
## My Setup

- Operating System: Windows 10 Pro
- App Version: 3.1.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

When I send or retrieve messages they sometimes take a minute to become visible. I can hear the sound that I got a message but it's not visible. Also when I send a message it takes a minute to become visible to the other person. This happens for all my co workers.

### Expected Behavior

The message should be vissible immediately after retrieving and sending.

**Comment by ankar84** [comment]
Please test that issue in web client. If it behaves same, that means it's servers issue, but not Electron application issue.
And if your server have few instances, check how they interoperate.

**Comment by BrianTimmermans** [comment]
We have the same issue on the web client. You think our server is the issue?

**Comment by ankar84** [comment]
> We have the same issue on the web client. You think our server is the issue?

I think you do have a problems at server level.
If you have more then 1 instance, check that doc https://docs.rocket.chat/installation/docker-containers/high-availability-install
`INSTANCE_IP` is really important in that case.

**Comment by BrianTimmermans** [comment]
I just learned that we don't have our own RocketChat server. It is hosted by RocketChat. So what can be the problem?

**Comment by ankar84** [comment]
> I just learned that we don't have our own RocketChat server. It is hosted by RocketChat. So what can be the problem?

In that case you must write to support@rocket.chat

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
