### ISSUE TITLE
The Rocket.Chat macOS app icon is too big.

### ISSUE THREAD

**Issue by perteraul** [RocketChat/Rocket.Chat.Electron#1943]
## My Setup

- Operating System: macOS 11.1
- App Version: 3.1.1
- Installation type: .dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The new app icon of Rocket.Chat is way too big, compared to all of the other app icons in the Dock (and not only). I'm attaching a screenshot. 

<img width="548" alt="CleanShot 2021-01-06 at 21 58 33@2x" src="https://user-images.githubusercontent.com/7403338/103814752-e691c380-506a-11eb-97c9-b1ff720bd029.png">

### Current Behavior
The app icon doesn't conform to the Big Sur app icon size.

### Expected Behavior
The app icon conforms to the Big Sur app icon size.

**Comment by andylin2004** [comment]
See: #1941 

Should be merged with master soon
