### ISSUE TITLE
Server after first start not focused

### ISSUE THREAD

**Issue by Luke-CSE** [RocketChat/Rocket.Chat.Electron#1945]
## My Setup

- Operating System: Windows 10 2004 (Build 19041.685)
- App Version: 3.1.1
- Installation type: exe, msi

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
After installing the client and opening it for the first time, the configured server is not selected/focused by the client, so the user only gets a grey screen. When reloading the client (with Windows+r for example) the client crashes. After the client crashes or has been closed manually the the server will be selected as expected for the next starts of the client. Becuase we do not show the side bar with the servers, users cannot select the configured server manually to bypass the focus problem at the first start.

This problem only occurs, when a servers.json is set. I've tested with the official open.rocket.chat server and with a custom server aswell.

![grafik](https://user-images.githubusercontent.com/72247639/103864547-0ce34d80-50c3-11eb-9888-d8f935db63f2.png)

### Current Behavior
The client does not focuse the configured server from servers.json at first start. The client crashes when reloading the empty screen.

### Expected Behavior
The client should focuse the first configured server at the first start already and not from the second start and onwards.

**Comment by Attack44** [comment]
I can confirm this behavior.

**Comment by giterium** [comment]
+

**Comment by Mystikal57** [comment]
same problem for us, very annoying

**Comment by giterium** [comment]
I still didn't understand how to fix it normally, I added it to ServersView/index. ts:
```
  useEffect(() => {
    const simulateClick = function (elem) {
      const evt = new MouseEvent('click', {
        bubbles: true,
        cancelable: true,
        view: window
      });
    };

    const clickInterval = setInterval(() => {
      const el = document.querySelector('#root > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ol > li');
      if (el != null) {
        simulateClick(el);
        clearInterval(clickInterval);
      }
    }, 500);
  }, []);
  ```

**Comment by Mystikal57** [comment]
Any news ?? 
this problem is the only one which blocks us for a wide deployment

**Comment by Luke-CSE** [comment]
For me the last code changes have not helped at all. I have switched to deploy a config.json at the appdata folder to set my server configuration as a workaround, with that methode everything works fine.

**Comment by Luke-CSE** [comment]
Finally the problem seems to be fixed with the newest version of the desktop client! 🎉 🙌

**Comment by jeanfbrito** [comment]
Yep, we fixed this. Thanks for notifying that solved for you.

Em qua, 8 de dez de 2021 10:42, Luke-CSE ***@***.***>
escreveu:
