### ISSUE TITLE
Improve spell check settings

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#195]
![image](https://cloud.githubusercontent.com/assets/51996/15558062/d2218116-229c-11e6-9a5d-71619bcacf8b.png)

This shouldn't be considered invalid.  We need to tweak the spell checker settings
##

**Comment by bgomelsky** [comment]
The contractions is a known issue, https://github.com/electron/electron/issues/1005

**Comment by geekgonecrazy** [comment]
@bgomelsky thanks for the link!

**Comment by bios-ben** [comment]
Is there currently even spell check in the Windows client? I don't see how to enable it if there is?

**Comment by geekgonecrazy** [comment]
@bios-ben no it isn't currently.  Adding to windows was causing the screen to go black randomly.

**Comment by geekgonecrazy** [comment]
Might be worth looking into this: https://github.com/paulcbetts/electron-spellchecker

**Comment by xenithorb** [comment]
Or this? https://github.com/atom/spell-check/pull/120
