### ISSUE TITLE
The app does not start properly if bugsnag is blocked

### ISSUE THREAD

**Issue by gerroon** [RocketChat/Rocket.Chat.Electron#1950]
Hi

I block Bugsnag for privacy reasons and this app seems to fail to start, at least it looks like it is not passing beyond that?

There is  a tray icon but no visible desktop app. Clicking on the tray and choosing "show" does not show anything. No visible app window. I am guessing it is because I block Bugsnag.

```
/opt$ rocketchat-desktop
[bugsnag] Loaded!


```

rocketchat_3.1.1_amd64.deb , Debian Testing

**Comment by Romich777** [comment]
Probably related to this issue - https://github.com/RocketChat/Rocket.Chat.Electron/issues/1935
