### ISSUE TITLE
UI Issue with Group Chats on RocketChat for Windows

### ISSUE THREAD

**Issue by andylin2004** [RocketChat/Rocket.Chat.Electron#1951]
## My Setup

- Operating System: Windows 10 20H2
- App Version: 3.1.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

The issue is that RocketChat does not correctly place white divider between different group chat member profile picture. See this: 
![image](https://user-images.githubusercontent.com/60021592/104782603-7d890a80-5752-11eb-909f-6cbf5f393ca7.png)

edit: seems to be an issue when display is scaled at 125% or 175% (eg high PPI screens). 

### Current Behavior

White divider lines are placed such that part of group chat members' profile picture "bleeds" through the line to the left of the line

### Expected Behavior

White divider line are placed such that it divides profile pictures cleanly and there is no "bleed"

**Comment by apaarfus** [comment]
Does this issue occur on _both_ the desktop & web versions of RC?  If so, this may need to be reported in the [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) repository.
