### ISSUE TITLE
Security alert critical security hotfix for live chat in our latest 3.10.5

### ISSUE THREAD

**Issue by s-saini** [RocketChat/Rocket.Chat.Electron#1958]
My Setup
- Operating System: Windows 10 1909
- App Version: 3.1.1
- Installation type: exe

- [x] I have tested with the latest version

##Description
![Security Alert hotfix (2)](https://user-images.githubusercontent.com/78364943/106489836-7b92ab80-64b5-11eb-9779-893d9a0e1e2c.png)
I'm having this issue where I get this notification that says "Security alert critical security hotfix for live chat in our latest 3.10.5, 3.9.7, 3.8.8. Please upgrade as soon as possible." even tho i'm running the latest 3.1.1 version of the Desktop app.

**Comment by pixxelspotter** [comment]
You have the newest Desktop Client, but the Server u are using is an old version.
You should consider updating your server and not your client

**Comment by s-saini** [comment]
I tried to upgrade my server version but there is also an issue with that as you can see here:
https://forums.rocket.chat/t/update-rocket-chat-when-using-snap/8033/32

**Comment by Loocos** [comment]
Hi there,

I'm getting the same problem. I've updated the server to 3.10.5 and I'm still getting the message using the web app of Rocket.chat.
See the screen below :
![image](https://user-images.githubusercontent.com/26056280/107354345-53ff9c80-6ace-11eb-9272-525e149dcf91.png)

Did you find the cause or a subject which talk about this problem ?

**Comment by s-saini** [comment]
Hi,

I also have the latest server version. I wrote to rocket chat team a week ago but didn't get any reply yet, it could be a bug they are trying to fix...
I'll update you as soon as I get a reply.

**Comment by cazetto** [comment]
Does this still happen? If so, can you check if it also occurs in the web application?

**Comment by ggazzo** [comment]
I'm closing this issue, since its 100% server side, nothing related with Electron/Desktop

if you have updated your server and the message its still there, just dismiss/close
