### ISSUE TITLE
Add to reaction no longer working

### ISSUE THREAD

**Issue by frederic-kneier** [RocketChat/Rocket.Chat.Electron#1961]
Adding to reaction by clicking on an existing reaction icon no long works in almost every case.

## My Setup

- Operating System: Ubuntu Linux 20.10
- App Version: 2.17.7
- Installation type: snap
- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
In the past if someone added a reaction to a message I could easily add to it by clicking on the reaction icon. This no longer works in about 95% of cases.

### Current Behavior
Reaction counter is not incremented and my reaction is not added.

### Expected Behavior
Reaction counter is incremented and my reaction is added.

**Comment by Ashragon** [comment]
+1
### My Setup

- Operation System: Windows 10 Pro (2004)
- App Version: 3.1.1
- Installation type: rocketchat-setup-3.1.1.exe
- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
On click reaction counter is incremented and immedialty decremented.

**Comment by AmatorPhasma** [comment]
Same here on MacOS/Windows/Linux
- App Version: 3.1.1, 3.1.0, 3.0.7
- Server Version: 3.10.5
Works on the web ui and the latest app version 4.14.1 (no other tested)
---

Works again with server version 3.12.0-develop on open.rocket.chat

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
