### ISSUE TITLE
Running rocketchat-setup-3.1.1.exe to upgrade from v2.17.7 logs out user

### ISSUE THREAD

**Issue by amoebav** [RocketChat/Rocket.Chat.Electron#1963]
## My Setup

- Operating System: Windows 10 and Windows 7 x64
- App Version: 3.1.1
- Installation type: rocketchat-setup-3.1.1.exe

- [yes ] I have tested with the latest version
- [yes] I can simulate the issue easily

## Description
User must relogin after update

### Current Behavior
Rocket.Chat 2.17.7 is currently running and user is logged in
I run following commands:
taskkill /F /IM Rocket.Chat.exe
rocketchat-setup-3.1.1.exe /S /allusers
C:\Program Files\Rocket.Chat\Rocket.Chat.exe

Open rocket.chat and user must re-login.

### Expected Behavior

After running new installer, when opening updated Rocket.Chat user should be logged in already to last known server(s).

Unless this is not the proper way to update. Does the msi installer update the app without losing local configurations and cached settings of server(s) and logins?

We only use one server and I currently use the server.json file to keep the server address auto-populated.

**Comment by ankar84** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1922

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
