### ISSUE TITLE
Start hidden not working

### ISSUE THREAD

**Issue by antonioli86** [RocketChat/Rocket.Chat.Electron#1964]
## My Setup

- Operating System: Windows 10
- App Version: 3.1.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Start hidden - set in window-state-main.json - does not work. After 2nd execution, in config.json is set to "maximized": true

`{
  "width": 1000,
  "height": 600,
  "isMaximized": false,
  "isMinimized": false,
  "isHidden": true,
  "x": 140,
  "y": 60
}`

### Current Behavior
In startup, Rocket.Chat window appears maximized

### Expected Behavior
Start hidden, without window (visible only in system tray)

**Comment by antonioli86** [comment]
No updates?

**Comment by teak421** [comment]
Almost an entire month with no communication...

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by antonioli86** [comment]
Issue not solved.
