### ISSUE TITLE
[Security] Disable nodeIntegration

### ISSUE THREAD

**Issue by xmedeko** [RocketChat/Rocket.Chat.Electron#1967]
Disable `nodeIntegration` - see https://github.com/RocketChat/Rocket.Chat.Electron/blob/3b2d0aaa51eaf96442c3084eaeb8621465d40cee/src/ui/main/rootWindow.ts#L31 Together with bug RocketChat/Rocket.Chat#20543 it's a serious security threat!

**Update:** I see the main window has `nodeIntegration` disabled, so it's seems OK https://github.com/RocketChat/Rocket.Chat.Electron/blob/3b2d0aaa51eaf96442c3084eaeb8621465d40cee/src/ui/main/serverView/index.ts#L148

**Comment by xmedeko** [comment]
Note: the attacker has access to `window.RocketChatDesktop` and `window.JitsiMeetElectron`. So, he can e.g. create a desktop notification, and other stuff there. Which is a security issue but do not know it's severity.

**Comment by robbyoconnor** [comment]
Why is this not happening on chat.rocket.chat?

**Comment by xmedeko** [comment]
@robbyoconnor This issue is about security consequences of RocketChat/Rocket.Chat#20543 in Electron app. For the browser, this issue is inconvenient but has not such security implications.

**Comment by robbyoconnor** [comment]
> @robbyoconnor This issue is about security consequences of RocketChat/Rocket.Chat#20543 in Electron app. For the browser, this issue is inconvenient but has not such security implications.

I understand. I'm trying to understand why it doesn't happen on RC's server.
