### ISSUE TITLE
Handle backwards / forwards keyboard shortcuts

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#197]
Handle events like `cmd+[` / `cmd+]` or `cmd+left arrow` / `cmd+right arrow` to move backwards and forward between channels
##

**Comment by rodrigok** [comment]
This should be implemented on Rocket.Chat server, can you move the issue?

**Comment by geekgonecrazy** [comment]
@rodrigok this already works out of the box in most browsers its just a shortcut to navigator history.  Its just the electron app that lacks this.

**Comment by vcapretz** [comment]
As discussed here, I see that it's an Electron issue for not having known shortcuts, but as it's not solved yet I see that we can implement it here by registering global shortcuts (https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md), is that right? 

I can work on it!
