### ISSUE TITLE
Toggle Tray Icon doesn't work in Linux

### ISSUE THREAD

**Issue by tarun8718** [RocketChat/Rocket.Chat.Electron#1972]
## My Setup

- Operating System: Ubuntu 18.04.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description:
When we click on `Tray Icon` present in the menu bar it doesn't destroy the existing tray icon, when it is clicked again a new tray icon is generated.

## Screenshots:

![Screenshot from 2021-02-10 18-06-26](https://user-images.githubusercontent.com/40015660/107512003-3c0e4280-6bcc-11eb-86a8-9c81224f6ebe.png)

**Comment by TazerReloaded** [comment]
Can confirm, the old tray icon still has all options, but does nothing if you click them. Closing Rocket completely removes all icons. Ubuntu 20.04.2 LTS with Dash to Panel.

**Comment by jeanfbrito** [comment]
Just researched about this and its a Electron Issue. We can expect this to be solved in a future Electron update.
