### ISSUE TITLE
Outdated Rocket.Chat version in Mac AppStore

### ISSUE THREAD

**Issue by alexander-potemkin** [RocketChat/Rocket.Chat.Electron#1974]
Rocket.Chat in Mac AppStore is 3 months old... 

<img width="1128" alt="Screenshot 2021-02-12 at 15 09 34" src="https://user-images.githubusercontent.com/2323840/107766314-52d7a500-6d44-11eb-8b4d-06e0b5c20fa8.png">

## My Setup

- Operating System: MacOS 11.2
- App Version: 3.0.3
- Installation type: AppStore (no other options for Mac given!)

- [ X ] I have tested with the latest version
- [ X ] I can simulate the issue easily

## Description
Mac AppStore is not updated for 3 months!!!!

### Current Behavior
No updates

### Expected Behavior
Updates...

**Comment by Vkat14** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1931#issuecomment-815261327

**Comment by Vkat14** [comment]
Bump

**Comment by redRolf** [comment]
I am facing backlash from my userbase, since the status (online, away, offline, ...) is not set correctly. 
As described in this issue https://github.com/RocketChat/Rocket.Chat.Electron/issues/2034 this is fixed in the latest version of 
Rocket Chat. 

So it would be appreciated if you could bump the AppStore Version to the latest version.  So I can roll out the fix to my userbase.

**Comment by felixspitzer** [comment]
Please update! AppStore is still on 3.0.0 and will not receive updates

**Comment by alexander-potemkin** [comment]
Fix found: migrate to Mattermost.
I’m sorry, but after more than a year of the issue, I could not resist…

**Comment by felixspitzer** [comment]
Understandable @alexander-potemkin. I just don't understand why the official download link leads to the AppStore instead of the direct download via GitHub. This would be the least that could be done here

**Comment by jeanfbrito** [comment]
Apple changed the requirements to be able to update the app on Apple Store.
We will be working on this in the next weeks.

**Comment by alexander-potemkin** [comment]
@felixspitzer , don’t know - there are so many bugs that are never picked up by the Rocket.Chat team… By the way, I did indeed switched to Mattermost - not so features rich, but it’s muuuuuch more stable, predictable and much less resources hungry.

@jeanfbrito guess it wasn’t the case when I raised an issue; don’t believe it’s something dramatic as well - have a few apps on the AppStore, updating them without much hassle.

**Comment by jeanfbrito** [comment]
@alexander-potemkin the project is open and you can contribute any time. I started to work in the project this month, you can ask me if need some help.

**Comment by alexander-potemkin** [comment]
@jeanfbrito it’s a commercial open source project, so unless I share some revenue, I’m really not interested.

Also I have no access to the company’s AppStore, neither anyone from the company is reacting on the issue and I really don’t mean to be a rescuer of someone doing what it’s like - it’s an unhealthy behavior pattern.

**Comment by jeanfbrito** [comment]
The Apple Store version is updated, you can install it from there right now.

**Comment by alexander-potemkin** [comment]
Yay! It was just two years old now! :)
Any chance to have this app updated in time, or would it be another two years before the next update?

**Comment by jeanfbrito** [comment]
Always updated. As soon as a new release get out and Apple approves it will
be updated.

Em sex., 25 de mar. de 2022 03:56, Alexander Potemkin <
***@***.***> escreveu:
