### ISSUE TITLE
Bug: Browser-View in Mac-Desktop-App not closeable

### ISSUE THREAD

**Issue by Davidoff22** [RocketChat/Rocket.Chat.Electron#1976]
## My Setup

- Operating System: Mac 11 Big Sur
- App Version: 3.1.1.
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
If i click on an URL inside a thread, the website will open inside Rocket-.Chat. The left navigation bar is gone and the window is completly filled with the content of that website. But there is no "back" button. I cannot close the website to get back to my threats. Mayby I'm to stupid to find it, but even though, it should be easy to find vor everyone to close that view.

**Comment by subesokun** [comment]
Any update on this? Since upgrading to the latest RC version the links are always opened directly inside of the RC app instead of opening the link in the browser. This makes it very hard to work effectively with RC. 

RC verison: 3.11.1
App version: 3.1.1

**Comment by subesokun** [comment]
Maybe it's better to follow this issue here https://github.com/RocketChat/Rocket.Chat/issues/20543

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
