### ISSUE TITLE
Pasting links freezes Rocket.Chat.Electron flatpak

### ISSUE THREAD

**Issue by digitalethics** [RocketChat/Rocket.Chat.Electron#1977]
## My Setup

- Operating System: openSUSE TW
- App Version: 3.1.1 (Flatpak)
- Installation type: flathub.org

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
When pasting links into the text field, the Rocket Chat flatpak freezes. 

### Expected Behavior
Expected behavior is to be able to paste links without any freezes or input lags.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
