### ISSUE TITLE
Jitsi opens many instances when clicking start call

### ISSUE THREAD

**Issue by DASPELLER4** [RocketChat/Rocket.Chat.Electron#1978]
## My Setup

- Operating System: Gentoo
- App Version: 3.1.1
- Installation type: flatpak

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description

How to reproduce: click on start voice call, wait, voila
### Current Behavior

Jitsi is opened multiple times
### Expected Behavior

Jitsi should open once

**Comment by philipprogramm** [comment]
same here

**Comment by ankar84** [comment]
Not experienced that on Windows
@philipprogramm @stasiop please mention your Jitsi server version - it could be very important.

**Comment by philipprogramm** [comment]
> Not experienced that on Windows
> @philipprogramm @stasiop please mention your Jitsi server version - it could be very important.
I don't know the Jitsi version as i'm using the open instance meet.jit.si, but I would say it's the newest version

**Comment by IhorNykyha** [comment]
Probably this is not a desktop issue. Maybe will  helpful to read this #20946

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
