### ISSUE TITLE
Once you click the download button (gif, pdf, mp4,...) you can't close it

### ISSUE THREAD

**Issue by urosino** [RocketChat/Rocket.Chat.Electron#1979]
### Description:
When you want to open/download an attachment inside the Rocket.chat client, you can't close it.
You are forced to quit rocket.chat client and relaunch it again.

### Steps to reproduce:
1. Go in to any room or DM
2. Drag/upload some .gif, pdf, or any other file
3. Click on the download icon
![SubtleAmericancreamdraftTuesday](https://user-images.githubusercontent.com/25570106/108828345-04899800-75c7-11eb-8746-c6f8450d161f.png)
4. Preview appears in full screen, and you can't close it

### Expected behavior:
1. To be able to close it with ESC or some X (close) button

### Actual behavior:
It opens in a full window screen and you cannot close it:
![tbrack7d](https://user-images.githubusercontent.com/25570106/108828387-10755a00-75c7-11eb-9501-faae78a20a70.gif)

### Server Setup Information:
* Version of Rocket.Chat Server: 3.11.1
* Operating System:  Docker image
* Deployment Method: Azure Kubernetes Pod
* Number of Running Instances: 1
* DB Replicaset Oplog: rs0
* NodeJS Version: v12.18.4
* MongoDB Version: 4.0.12 / mmapv1

### Client Setup Information
- Desktop App or Browser Version: Desktop App, 3.1.1

- Operating System: Windows 10

### Additional context
 - No additional context

### Relevant logs:
 - No other logs

**Comment by parannoide** [comment]
Same problem here.

Clicking in the download button do not open the download dialog.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
