### ISSUE TITLE
Favorites list has wrong sorting (by last name + first name instead of first name + last name)

### ISSUE THREAD

**Issue by AlexejNagel** [RocketChat/Rocket.Chat.Electron#1984]
## My Setup

- Operating System: Win 10
- App Version: 2.15.5.2
- Installation type: package manager

- [x] I have tested with the latest version -> I use Rocket.Chat in my client's project and 2.15.5.2 is the latest version there.
- [x] I can simulate the issue easily

## Description
We have about 100 contacts in the chat, so I added 25 people to my favorites, with whom I communicate more often.
The favorites list is sorted by last name + first name. This makes it difficult to search for a contact when this list becomes very long. And it also doesn't match the sorting in the contact list at DMs, where it is sorted by first name + last name.

### Current Behavior
The favorites list is sorted by last name + first name.

### Expected Behavior
The favorites list is sorted by first name + last name.

**Comment by ggazzo** [comment]
if this is still an issue please report your problem here: https://github.com/RocketChat/Rocket.Chat
