### ISSUE TITLE
Yarn release goes successful, however rocketchat is not launching after installing generated artifact i.e racketchat-3.x.x.Setup.exe

### ISSUE THREAD

**Issue by charaneval** [RocketChat/Rocket.Chat.Electron#1987]
## My Setup

Operating System: Windows 10
App Version: Node.js 12.x, visual studio 2017 tools, node-gyp

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description

![image](https://user-images.githubusercontent.com/57132438/110212815-40740580-7ec3-11eb-9bbc-19e29db8ae9e.png)

### Current Behavior
After installing release artifact nothing happens, app not launching.

### Expected Behavior
Application should launch and ask for the server config.

**Comment by charaneval** [comment]
This is what is being logged in the event viewer when i launch the app
![image](https://user-images.githubusercontent.com/57132438/110236070-d65a6f80-7f59-11eb-821b-2b8126d4f747.png)

**Comment by IhorNykyha** [comment]
Please look at this, https://github.com/RocketChat/Rocket.Chat.Electron/issues/1804 maybe will help you.

**Comment by franckadil** [comment]
Hi all,

I can reproduce this error even after respecting` $env:NODE_ENV="production"` and `yarn release` as explained in #1804.
I even tried to build from thee latest release source code, and it still craches just after starting the app.

@tassoevan

**Comment by jeanfbrito** [comment]
I tested in my Windows machine and is working. Please update the code and try again.
