### ISSUE TITLE
Clicking the Users  List will report an error

### ISSUE THREAD

**Issue by 13103049184** [RocketChat/Rocket.Chat.Electron#1989]
## My Setup
-Version of Rocket.Chat Server: 3.1.1
- Operating System:Windows (WSL)
- Number of Running Instances: 1
- Installation type: exe

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![()8OE2{%}08~JMW2RCMATZW](https://user-images.githubusercontent.com/53426810/110567976-4d2b7e80-818d-11eb-82bb-189c838e054c.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
