### ISSUE TITLE
the chief maintainer

### ISSUE THREAD

**Issue by VasiliyMooduckovich** [RocketChat/Rocket.Chat.Electron#1991]
hey there! there was no commits since 25 Dec 2020 - your chief maintainer is sick, so mine guess you should probably consider to change the chief maintainer or what?

**Comment by pixxelspotter** [comment]
Sad to see that there is no progress and more and more bugs get reported. We currently use 2.16.2 as it is the only one working okay for us

**Comment by himpierre** [comment]
I would have put it differently, but it's true, the client has a lot of bugs and desperately needs some updates.

**Comment by pixxelspotter** [comment]
As I looked at his profile here, he is contributing to the Rocket-chat Server repository regularly. So hes is working but not on the client which now is over 4 months old and not usable for us.

**Comment by VasiliyMooduckovich** [comment]
> 
> 
> As I looked at his profile here, he is contributing to the Rocket-chat Server repository regularly. So hes is working but not on the client which now is over 4 months old and not usable for us.

that's cool. and who's gonna commit to this repo?!

**Comment by pixxelspotter** [comment]
> that's cool. and who's gonna commit to this repo?!

That's a good question, currently there are some open pull requests by other users but even does don't get merged etc.

**Comment by Xarkam** [comment]
Hello, since the last server update, I have my 3.1.1 client which no longer works except make a total reset each time.

So I went back to 2.16.2

It's quite deplorable to see that nothing is moving for the customer. I am seriously considering changing the server for another service.

**Comment by VasiliyMooduckovich** [comment]
> It's quite deplorable to see that nothing is moving for the customer. I am seriously considering changing the server for another service.

to be fair, mine guess 90% users of the open source software is not a customers(i mean paid one) not even a contributors but a freeloaders, so what we can do is wait.

**Comment by neonardo1** [comment]
> > It's quite deplorable to see that nothing is moving for the customer. I am seriously considering changing the server for another service.
> 
> to be fair, mine guess 90% users of the open source software is not a customers(i mean paid one) not even a contributors but a freeloaders, so what we can do is wait.

Can you blame them?  When the product is unstable to the point of being unusable as it is right now on Linux/Mac how can you expect people to ever get past the testing phase to the deployment phase where they're more likely to pay for it?

I'm stuck in the testing phase with RC and it's not looking like things will progress past that for my organization any time soon.

**Comment by Xarkam** [comment]
> > It's quite deplorable to see that nothing is moving for the customer. I am seriously considering changing the server for another service.
> 
> to be fair, mine guess 90% users of the open source software is not a customers(i mean paid one) not even a contributors but a freeloaders, so what we can do is wait.

I suggest you contact the developers of rocketchat to offer them to pass their paid application only. So only those who have paid will be able to complain without having a correct follow-up.

Personally, if for June no update of the desktop application is offered, I will migrate my messaging to another paid service.

**Comment by pixxelspotter** [comment]
There have been 2 commits to a performance branch, let's see how it goes

**Comment by Noidart** [comment]
All this is similar to the fact that the free client was seed for identifying a large bugs who were corrected in a paid version. Nobody seemed to be going to bring in accordance with the free version. Further version 3.1.1 seems to not go, but sorry. Our organization apparently will also look for another client.

**Comment by johncrisp** [comment]
Hi,

we know that things have not been great. Rest assured that Rocket is expanding it's dev teams rapidly and reorganising at the same time.

I can assure you as the new Community Manager that Rocket.Chat **is** listening - I have literally just posted a doc with features and issues regular community members would like to see fixed that is escalated up to the programming teams. It isn't going to all  happen overnight, and you may not get everything quite the way you want it, but progress is being made. I hope you will see the results in the coming weeks and months.

I'd love to see people contributing thoughts, ideas, code, documentation and support to fellow community members.

So, please come and talk to me (or complain to me!!) about it on open.rocket.chat and save Issues for actual problems with the code.

Thanks
