### ISSUE TITLE
Audio Playback from uploaded video not working on 3.1.1 

### ISSUE THREAD

**Issue by AureNP** [RocketChat/Rocket.Chat.Electron#1992]
## My Setup

- Operating System: Windows
- App Version: 3.1.1
- Installation type: exe 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Videos uploaded within RocketChat channels are unable to play the sound. The video is playing fine. 

### Current Behavior
When playing a video, audio is not playing. However, when opening the same channels via browser, the sound is playing. 
### Expected Behavior
Listen to the sound of the video :)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
