### ISSUE TITLE
Update your RocketChat Bug/Recommendation

### ISSUE THREAD

**Issue by jwalker5006** [RocketChat/Rocket.Chat.Electron#1993]
Video displaying details about the bug and suggestion
https://youtu.be/CRGAu4wz2UI

## My Setup

- Operating System: Ubuntu running on docker
- App Version:
- Installation type: 
![image](https://user-images.githubusercontent.com/6217843/111328134-f82fb280-863b-11eb-9db9-6dee2b36f706.png)

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
You can see the version notification bar is suggesting we upgrade to is earlier than the version we are on.
![image](https://user-images.githubusercontent.com/6217843/111328301-1eede900-863c-11eb-8ce5-80ab2540f819.png)

Issue occurs in web browser and windows and mac app. This is while I filed here instead of the Electron as it pointed to a content issue from meteor or some other back end tech 

### Expected Behavior
I used inspect in Chrome to moc up how the solution could be worded. Of course in my situation, our RC server is on the latest version, and the notification bar should not even be showing.
![image](https://user-images.githubusercontent.com/6217843/111328814-93288c80-863c-11eb-9f8a-83edae587261.png)

**Comment by ankar84** [comment]
Your issue is not about Electron application, but about server itself.
So right repo in your case is https://github.com/RocketChat/Rocket.Chat/issues

**Comment by cazetto** [comment]
Closing this issue since I understand that it is a Rocket.Chat server issue.
