### ISSUE TITLE
Different scrolling speed UP and Down at contact list

### ISSUE THREAD

**Issue by zaznetkherson** [RocketChat/Rocket.Chat.Electron#1994]
## My Setup

- Operating System:
- App Version: 
- Installation type: 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When scrolling contact list i have the fast speed scroll down and slow speed scroll up
### Current Behavior

Different scrolling speed UP and Down at contact list
### Expected Behavior

Same scrolling speed UP and Down at contact list

**Comment by luitzifa** [comment]
I only notice this when zoomed in, which i usually do to scale up font.

**Comment by cYzzie** [comment]
happening for me also with newest current client (3.5.4) only happens if view is not at 100% but zoomed in at least once, scrolling contact list down is fast, scrolling up is super slow and scrolls just a tiny amount of lines.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Comment by jpele-tis** [comment]
It's fixed, thank you
