### ISSUE TITLE
[Bug] Zooming render issue

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1995]
## My Setup

- Operating System: Windows 10
- App Version: 3.1.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Sometimes (not very often) I get really strange Rocket Chat desktop application behavior. Server not loaded, but whole window flashes and reloads.
CTRL+R don't help - only Exit (CTRL+Q)

## Steps to reproduce
1. Decrease Zoom (`CTRL + -`)
2. Restore zoom (`CTRL + 0`)
3. Switch to another chat
![render-issue](https://user-images.githubusercontent.com/4023037/117967552-da29ba00-b32d-11eb-897c-10dcf6e6d438.gif)

### Current Behavior
![desktop-crazy](https://user-images.githubusercontent.com/4023037/111601875-d96c2000-87e3-11eb-8be2-20f2abd0ccaf.gif)

### Expected Behavior
Server with sidebar and chat history should be open

**Comment by therealZottel** [comment]
Some of my colleagues have seen similar behavior. Does it still happen when you disable the "Server List" display?

**Comment by therealZottel** [comment]
Otherwise you may test "Disable GPU".
But unfortunately the setting is not saved permanently and must be set again after closing and opening the app.
https://github.com/RocketChat/Rocket.Chat.Electron/issues/184#issuecomment-771136990

**Comment by ankar84** [comment]
> Does it still happen when you disable the "Server List" display?

It's a really rare bug, so I can't experiment with that easy. 


> Otherwise you may test "Disable GPU".

I think it could help, because behavior looks like graphic rendering issue.

**Comment by ankar84** [comment]
One of our users find a 100% way to reproduce that bug
1. Zoom In
2. Restore zoom
3. Switch to another chat
![render-issue](https://user-images.githubusercontent.com/4023037/117967552-da29ba00-b32d-11eb-897c-10dcf6e6d438.gif)

**Comment by ankar84** [comment]
Still an issue in 3.2.0

**Comment by ankar84** [comment]
Still an issue in 3.5.0

**Comment by ankar84** [comment]
I guess that issue could be fixed by https://github.com/RocketChat/Rocket.Chat.Electron/pull/1947

**Comment by ankar84** [comment]
I found that my issue it's actually a duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1936
So I'm closing my issue in favor of first one.
