### ISSUE TITLE
Download manager - files names are not fully presented

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.Electron#1996]
## My Setup

- Operating System: Windows 10
- App Version: 3.1.1
- Installation type: exe

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
In downloads manager file names are not fully presented and no option to resize this column. May be good solution will be reduce download progress bar and add more place for file name.

### Current Behavior
In downloads manager file names are not fully presented

### Expected Behavior
Reduce download progress bar and add more place for file name

![image](https://user-images.githubusercontent.com/50440047/112444903-d4acec00-8d4e-11eb-96a7-2bc70619ba01.png)

**Comment by badboyguss** [comment]
Please assign this to me!
