### ISSUE TITLE
Messages not showing correctly in Electron Desktop app

### ISSUE THREAD

**Issue by phlegx** [RocketChat/Rocket.Chat.Electron#1997]
I'm on latest stable Rocketchat Server (3.12.3)  and and latest Electron (3.1.1) for Linux (Ubuntu) . However since upgrading to RC server 3.12.3 In some channels the message  is now showing up correctly/fully (See screenshot)

In the mobile app it is showing just fine.

Any ideas?

![Screenshot from 2021-03-27 16-05-59](https://user-images.githubusercontent.com/111506/113293183-bbc7ac00-92f5-11eb-8b67-527d707896e8.png)

**Comment by ankar84** [comment]
> In the mobile app it is showing just fine.
> 
> Any ideas?

Can you show how that messages looks like in Web version?

**Comment by phlegx** [comment]
In the Web version it looks the  same as in the screenshot above.

In the mobile Android app it shows correctly:

![Screenshot_20210402-111359](https://user-images.githubusercontent.com/111506/113402294-13712080-93a5-11eb-8a86-b0540d2e4a62.jpg)

**Comment by ankar84** [comment]
> In the Web version it looks the same as in Electron app as in the screenshot above.

So, it's **Web version issue** (front end team) **but not specific Electron issue** in that case.

**Comment by phlegx** [comment]
Yes you are right!  I will open a Bug report there and we can close this.
