### ISSUE TITLE
RocketChat does not launch when you clicked on the logo

### ISSUE THREAD

**Issue by Vandeabdou** [RocketChat/Rocket.Chat.Electron#1998]
I compiled RocketChat Desktop with "yarn release" on Windows. When I try to launch the application, nothing happens.
I am a beginner with Electron.

## My Setup
- Operating System: Windows 10
- App Version: 3.1.1
- Node: v12.18.2
- Git: 2.27.0
- node-gyp: v7.1.2
- yarn: 1.22.10

The .exe is successful installed but don't launch when clicked on the logo

**Comment by IhorNykyha** [comment]
Please read this https://github.com/RocketChat/Rocket.Chat.Electron/issues/1804#

**Comment by Vandeabdou** [comment]
> Please read this #1804

Thank you very much. It works
