### ISSUE TITLE
Flatpak client does not open via the link, but does open via terminal

### ISSUE THREAD

**Issue by adelphi23** [RocketChat/Rocket.Chat.Electron#1999]
## My Setup

- Operating System: Fedora 33 (kernel 5.11.11-200), KDE 5.21 (Plasma/Kwin)
- App Version: 3.1.1
- Installation type: Flatpak (Flatpak 1.10.2)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
When trying to open the Rocket.Chat client via regular means (i.e., clicking on the desktop icon), the client opens with a gray screen:
![RocketChatFlatpakClient_failToOpen](https://user-images.githubusercontent.com/2773303/113900774-2cf6db80-979c-11eb-8188-dbfff2f9d897.png)

However, it opens and works without a problem when invoked from the terminal (flatpak run chat.rocket.RocketChat).
The only hint I get from the terminal is the message:
"Gtk-Message          : Failed to load module "xapp-gtk3-module"

![RocketChatFlatpakClient_OpensFromDesktop](https://user-images.githubusercontent.com/2773303/113901153-91199f80-979c-11eb-93ae-374b058b8601.png)

Previous behavior:
The client worked without issues until recent updates. It then started to open the grey screen, but a reset would work. It got worse and resets would not work anymore. Now it only opens via the terminal.

### Expected Behavior
The client should open when its desktop icon is pressed.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
