### ISSUE TITLE
Add Application and Context Menu

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat.Electron#2]
See https://github.com/atom/electron-starter/tree/master/menus

**Comment by engelgabriel** [comment]
https://github.com/szwacz/electron-boilerplate/blob/master/app/vendor/electron_boilerplate/context_menu.js

**Comment by edoardocavazza** [comment]
It seems that context menu requires `node-integration: true` :(

**Comment by rodrigok** [comment]
@edoardocavazza do you know exactly why?

We have a file called preload.js that is loaded by Electron and has access to "node-integration" without necessity to expose node-integration to all application, so I think that we can create an api with this file to handle with the context menu apis.

What do you think about it?

**Comment by edoardocavazza** [comment]
You were absolutely right! I committed a first implementation of menus with some keyword shortcuts!

**Comment by engelgabriel** [comment]
Needed for https://github.com/RocketChat/Rocket.Chat.Electron/issues/32
