### ISSUE TITLE
Need a way to clear cookies when app start

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat.Electron#20]
Github 2FA (and probably others) messes up if session is disconnected in the middle (high probability since it takes so long to look up 2FA code); and subsequent logons will all fail with some broken saved state.  Other 2FA or long auth may have same problem.

Optional cookies clear on start will probably be useful for other 'broken saved state' scenarios as well.
##

**Comment by rodrigok** [comment]
Can this break other things?

**Comment by tassoevan** [comment]
Closing in favor of #1493.
