### ISSUE TITLE
silent installation / .msi support for rocket.chat windows app [$30]

### ISSUE THREAD

**Issue by Xermon** [RocketChat/Rocket.Chat.Electron#200]
frasercarter commented 13 hours ago
Feature Request for an .exe that supports /silent switches, or .msi support to cater for business/enterprise rollouts.

https://github.com/RocketChat/Rocket.Chat/issues/3421

**Comment by engelgabriel** [comment]
@surculus12 are you going to claim the bounty at https://www.bountysource.com/issues/34769819-silent-installation-msi-support-for-rocket-chat-windows-app ?

**Comment by surculus12** [comment]
@engelgabriel Hey. If you can retract the bounty and put it on something else you need done I'd prefer that, since there turned out to be a built-in silent switch. I can also claim and do it if you tell me which issue you want it on.
