### ISSUE TITLE
Opening Downloads segfaults

### ISSUE THREAD

**Issue by fracsi** [RocketChat/Rocket.Chat.Electron#2002]
## My Setup

- Operating System: Ubuntu 20.04
- App Version: 3.2.0-snapshot (2021-04-07)
- Installation type: snap

- [X] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Open the new Downloads Manager from the toolbar: `Window -> Downloads`.

### Current Behavior
The app segfaults.
```
kernel: rocketchat-desk[42265]: segfault at fffffb74bfd64710 ip 000055ad80a1089d sp 00007ffc6c193e30 error 5 in rocketchat-desktop[55ad8091c000+5f9c000]
kernel: Code: c3 cc cc cc cc cc cc cc cc cc cc cc cc 55 48 89 e5 41 56 53 48 83 ec 20 48 8b 87 98 fc ff ff 48 8d b7 98 fc ff ff 48 8d 7d d8 <ff> 90 b8 00 00 00 48 8b 5d d8 4c 8b 75 e0 4c 39 f3 74 1a 48 8b 3b
systemd[3538]: snap.rocketchat-desktop.rocketchat-desktop.d533df71-971e-47f2-8875-4eeb56200674.scope: Succeeded.
```

### Expected Behavior
The download manager opens successfully.

### Note
The Downloads can be opened from under the server list.

**Comment by fracsi** [comment]
The problem is still present on 3.2.2 and 3.3.0-snapshot.

**Comment by jeanfbrito** [comment]
I think that this is solved on our lastest release, I will close it, but if the issue persists, please tell me that I will open it again.
