### ISSUE TITLE
gif autoplay in chat window

### ISSUE THREAD

**Issue by mStirner** [RocketChat/Rocket.Chat.Electron#2003]
## My Setup

- Operating System: Ubuntu 18.04 LTS
- App Version: 2.17.7

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Feature, add support to play gif animations in the chat window.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
