### ISSUE TITLE
Call to bugsnag sending Referer header with SAMLRequest payload

### ISSUE THREAD

**Issue by avoidik** [RocketChat/Rocket.Chat.Electron#2005]
## My Setup

- Operating System: Windows 10
- App Version: 3.1.1
- Installation type: EXE

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

1. Initiate connection to a RocketChat server with the open developer tools window
2. Check HTTP headers on the call to bugsnag
3. Observe SAMLRequest payload

### Current Behavior

When using desktop client `SAMLRequest` being sent in Referer header when HTTP call to bugsnag happens

### Expected Behavior

Call to bugsnag must have no SAMLRequest data in it

**Comment by rcadmin19** [comment]
There should be also install option to avoid sending any data to Bugsnag. I think this feature causes data leakage. I don't get why the desktop client even sends any data outside.  If privacy is important, the Bugsnag feature should be completely removed.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
