### ISSUE TITLE
Zoommtg protocol links do not work in Announcement field

### ISSUE THREAD

**Issue by crogers90** [RocketChat/Rocket.Chat.Electron#2008]
## My Setup

- Operating System: macOS 11.2.3
- App Version: 3.1.1
- Installation type: .pkg file

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

We are attempting to add Hyperlinks using the zoommtg protocol to a channel's Announcement field. 

### Current Behavior

For example, we added `<a href="zoommtg://[COMPANY].zoom.us/join?confno=94175934408">IT Zoom Room</a>` to the announcement - and it does not redirect to the Zoom app, which is installed. Instead a pop up within Rocket Chat appears that just says "IT Zoom Room." HTTPS links do work as expected. These zoommtg links do work from direct messages in Rocket Chat, though.

### Expected Behavior

This link should open in the Zoom app.

**Comment by jeanfbrito** [comment]
This seems to be a link redirection issue on the Rocket.chat and not a problem in the Electron.
Please test if the problem persists and if it happens on the web browser too.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
