### ISSUE TITLE
snap 3.1.1  2021-04-19  segfaults and blank chat 

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat.Electron#2010]
## My Setup

- Operating System: Linux  Mint 19
- App Version: 3.1.1
- Installation type: snap

- [ x ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
After latest update from 2021-04-19 ( snap ), application segfaults a lot.
I can easily replicate if i try to enable/disable tray icon.
Also the first chat opened will be blank and it does not matter if you try to reload, it will be blank.

### Current Behavior
Crashing and mis behaviour UI

### Expected Behavior
Should work as previous version

**Comment by jsalatiel** [comment]
btw, it would be nice If you could have a snap channel "stable-dbg" with debug symbols, so people could send the gdb backtrace.

**Comment by udavx** [comment]
I observe it with the new 3.1.1, too.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
