### ISSUE TITLE
Tray Icon does not hide/show the App window

### ISSUE THREAD

**Issue by udavx** [RocketChat/Rocket.Chat.Electron#2011]
## My Setup

- Operating System: Ubuntu 20.04.2 LTS
- App Version: 3.1.1
- Installation type: snap
- [x] I have tested with the latest version (the latest snap, at least)
- [x] I can simulate the issue easily

## Description
1. Start the app.
2. If the app window does not appear, don't even try using the Tray Icon to have it, just execute it again and it will show up.
3. Ensure the View/"Tray icon" tick in the menu is on. If you switch it on, you will have to restart the app because of https://github.com/RocketChat/Rocket.Chat.Electron/issues/2010 anyway
4. With the app window being there, click on the Tray Icon and select "Hide". Nothing happens.
5. Close the app window, click on the Tray Icon and select "Show". Nothing happens.
6. Start the app explicitly again to have the app window on the screen.

### Current Behavior
Show/Hide of the tray icon does not seem to do anything.

### Expected Behavior
If I get the concept right:
- "Show" shall show the app window.
- "Hide" shall hide the app window.

At least it was working like that before the latest update (last working version for me was 3.0.1).

**Comment by 29ggf** [comment]
probably related to #1935

**Comment by udavx** [comment]
> probably related to #1935

Thanks, @29ggf, confirmed, works correctly in 3.2.0-snapshot.
