### ISSUE TITLE
macOS App: Crashing when a video call is initiated

### ISSUE THREAD

**Issue by strike65** [RocketChat/Rocket.Chat.Electron#2012]
## My Setup

- Operating System: macOS Catalina
- App Version: 3.1.1.
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
macOS App crashes when a video call is initiated

### Current Behavior
Crash - the app is dead

### Expected Behavior
video call should work

**Comment by devi4nt** [comment]
Duplicate of #1965

There is a work around mentioned on this ticket.

**Comment by strike65** [comment]
Thank you! But I can't bring that to my customers. Not everyone knows how to use a terminal.

**Comment by devi4nt** [comment]
Ah fair enough, can't deny thats certainly less than ideal, hopefully it's fixed soon!

**Comment by strike65** [comment]
Are there any news regarding this?

**Comment by strike65** [comment]
It's still open.
