### ISSUE TITLE
[TEAMS] 3.13.2 no video call option in teams channel 

### ISSUE THREAD

**Issue by Cob0ld** [RocketChat/Rocket.Chat.Electron#2017]
My Setup

- Operating System: Ubuntu 18.04.05
- App Version:  3.13.2
- Installation type:  tar

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

![bug](https://user-images.githubusercontent.com/42765891/116382737-8344c080-a816-11eb-81ea-9dde7e21aea6.png)

## Description
After the migration to a teams channel the channel has no option to use the build in jitisi video. the buttion is missing. You can still have video calls in private channels or in dm's 

### Current Behavior
no button to start a video call (jitis) from a team channel

**Comment by Cob0ld** [comment]
wrong repo

**Comment by Cob0ld** [comment]
Version 3.15.0 still the same bug

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
