### ISSUE TITLE
saving pics from chat

### ISSUE THREAD

**Issue by khodge281** [RocketChat/Rocket.Chat.Electron#2020]
It is VERY irritating that i cannot save a file or pic from a chat. When i do save is it tries to go as ALL FILES, which is worthless. I need to be able to save pics and documents from my chat. How can i fix this?

**Comment by ankar84** [comment]
Could be related to https://github.com/RocketChat/Rocket.Chat/issues/20165

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
