### ISSUE TITLE
Message Notification "Default" not playing sounds

### ISSUE THREAD

**Issue by Robin-Brandt** [RocketChat/Rocket.Chat.Electron#2025]
## My Setup

- Operating System: Fedora Release 32
- App Version: 3.1.1
- Installation type: Flatpak

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The message notification sound that is set to default does not play. I've tried all selectable tones and the issue persists for all of them. The "Notifications sound volume" is set to 99/max. Right now I've set "New Message Notification" to "Chime". In the "Notification Preferences" of a conversation, the Sound will not play, neither in preview nor after receiving a message, when the sound is set to "Default". When I manually select a specific sound for the conversation, such as "Chime", it works both in preview and when receiving messages. Resetting the app data, logging out and in, rebooting the system and reinstalling the application did not fix the issue.

### Current Behavior
Sound notifications won't play for conversation where the message tone is set to "Default".

### Expected Behavior
"Default" message sounds should play as intended.

**Comment by AndreySemenov1** [comment]
Hi! the same issue. App Versions tested 3.5.7 - 3.6.0

#2239

ENV: (disable_presence_monitor seems doesn't matter)

Windows 10 Build 19042.1348

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
