### ISSUE TITLE
Citrix VDI Terminalserver Windows 2016 AutoLogon after second Logon

### ISSUE THREAD

**Issue by spkToni** [RocketChat/Rocket.Chat.Electron#2026]
## My Setup

- Operating System: Citrix VDI Terminalserver Windows 2016
- App Version: 3.1.1
- Installation type: .exe - AllUsers

- [x ] I have tested with the latest version
- [ x] I can simulate the issue easily

### Current Behavior
What actually happens?
When Client start after fresh logon of User on Terminalserver the client know the Server but ask first-time for Credentials -> OK!
When client will quit an Start again the client make a Auto-Logon -> VeryGood
When User logoff from Terminal-Server-Session and start new session to Server (randomized Server) and start Client he has again to enter Credentials -> not good
### Expected Behavior

Where or how the credentials are Stored that we can synchronise correctly User Credentials with his Profil to Central-Profile-Store?
We synchronise %appdata%\roaming complete and Parts of %appdata%\local.
P.S.: We have Turn of for Chrome Password Storing with GPO -> Turn off GPOs -> same problem

**Comment by Asgatoril** [comment]
We have a similar problem on a Windows Server 2012 R2 Terminal Server.
App Version: 3.2.2

The users are sent to random servers on login depending on the current load of the servers.
The profiles are synced but every time the users are sent to another server, they get an infinite loading screen in Rocketchat.
The only solution is to rightclick on the servericon and use reload server which presents the user with the login screen.
The user then has to log in again.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
