### ISSUE TITLE
[Bug][Jitsi][Regression] Sharing stop working since 3.7.0

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#2028]
## My Setup

- Operating System: Windows 10 1809
- App Version: 3.2.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
First that bug was described in https://github.com/RocketChat/Rocket.Chat.Electron/issues/1421 (introduced in 2.16.0 and solved in 2.17.3 with https://github.com/RocketChat/Rocket.Chat.Electron/pull/1486)
It reappeared in 3.2.0

## Step to reproduce
1. Start Jitsi call
2. Start desktop sharing

### Current Behavior
![image](https://user-images.githubusercontent.com/4023037/118076857-a85f3480-b3bb-11eb-86f3-37c8cd45638c.png)
![image](https://user-images.githubusercontent.com/4023037/118076873-aeedac00-b3bb-11eb-90df-77e0498f8cb6.png)

### Expected Behavior
Monitor sharing works fine as well as any application sharing

**Comment by strike65** [comment]
Hi!
Same Problem here.
macOS Big Sur 11.3.1
<img width="592" alt="Screenshot 2021-05-13 at 09 49 42" src="https://user-images.githubusercontent.com/2091178/118095620-96d45780-b3d0-11eb-8613-b4c74c12e7bd.png">

**Comment by ankar84** [comment]
> Moreover: There is no version string in the "About"-Window.

Indeed
![image](https://user-images.githubusercontent.com/4023037/118096333-e4a18d80-b3d9-11eb-9743-98e950188159.png)

**Comment by ankar84** [comment]
Confirm that SS works perfect in 3.2.2
![image](https://user-images.githubusercontent.com/4023037/118219807-e70bf200-b482-11eb-9b05-e7bed3be4ed8.png)

**Comment by ankar84** [comment]
That bug come back in 3.7.0
![image](https://user-images.githubusercontent.com/4023037/144789378-23344f3b-ef29-4387-8111-0a6dbc6b2af0.png)
@jeanfbrito can you check in fix https://github.com/RocketChat/Rocket.Chat.Electron/pull/2031 is still in code for 3.7.0?

**Comment by jeanfbrito** [comment]
> That bug come back in 3.7.0 ![image](https://user-images.githubusercontent.com/4023037/144789378-23344f3b-ef29-4387-8111-0a6dbc6b2af0.png) @jeanfbrito can you check in fix #2031 is still in code for 3.7.0?

Sorry for late reply, I'm looking this right now!

**Comment by BSerpent86** [comment]
@jeanfbrito this affects Windows and Linux, too. It's extremely annoying. Could this be fixed in 3.7.1, too?

**Comment by iMiKED** [comment]
Same on 3.7.1 👎

**Comment by molodtsov** [comment]
Same on 3.7.2 :(

**Comment by iMiKED** [comment]
Still not fixed on 3.7.3 👎

**Comment by jeanfbrito** [comment]
> Still not fixed on 3.7.3 👎 @jeanfbrito

Yep, but it will be the fixed in the next release. I'm working on this right now.
