### ISSUE TITLE
The user status is not updated correctly

### ISSUE THREAD

**Issue by redRolf** [RocketChat/Rocket.Chat.Electron#2034]
## My Setup

- Operating System: macOS 11.3.1
- App Version: 3.0.3
- Installation type: App Store app
- Server Version: 3.14.0

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

The user status is not updated correctly. When a user changes their Status from online, to invisible, or something else the rocket chat app does not always reflect this status change. This can result in people being shown as offline who are actually online. Or sometimes people are shown as away who are actually online. To reproduce this issue no special steps are needed, this just happens while using the app normaly.

Schrödingers state: Both Online and Offline, this is very confusing.
![image](https://user-images.githubusercontent.com/42872307/118242169-5393ea80-b49d-11eb-841a-96a5eb5d91a8.png)

### Current Behavior
Status changes of users are not reflected correctly in the UI. After performing a reload using `<cmd>+r` the status is then reflected correctly. This leads me to believe, that this is a refresh problem.

### Expected Behavior

The user status is displayed correctly.

**Comment by redRolf** [comment]
My be related, linked to Issue: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1990

**Comment by ankar84** [comment]
> * App Version: 3.0.3

Try new 3.2.2 version

**Comment by redRolf** [comment]
@ankar84 
Thank you for the tip, unfortunately, the latest version available on the AppStore is 3.0.0 which in reality is (3.0.3)
The last time an update was made on the AppStore was 7 months ago 😱 

![image](https://user-images.githubusercontent.com/42872307/118257176-9d390100-b4ae-11eb-84d5-375783e44734.png)

Since at our company we are reliant on the AppStore to distribute the app to our fleet, it would be really helpful, if the version in the app store could be bumped up :)

For testing, I will download RocketChat manually and give you feedback if the issue persists. 

Should I create a new Issue for updating the AppStore app version?

**Comment by ankar84** [comment]
> For testing, I will download RocketChat manually and give you feedback if the issue persists.

It should help, I think that bug was fixed by https://github.com/RocketChat/Rocket.Chat.Electron/pull/2023 since 3.1.1

**Comment by redRolf** [comment]
@ankar84 😎  
From the first glance, it seems to be working. So what do I need to do, to get the version on the AppStore bumped to the current version, so I can roll this out to all my users.

**Comment by ankar84** [comment]
> So what do I need to do, to get the version on the AppStore bumped to the current version, so I can roll this out to all my users.

That can be done only by repo maintainers and developers

**Comment by redRolf** [comment]
@ankar84 Ok, thank you for your help :) I will open a new Issue then requesting the bump of the Appstore Version.

**Comment by redRolf** [comment]
There is already an issue requesting this 
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1974
