### ISSUE TITLE
Smart Card Log in issues with Win10

### ISSUE THREAD

**Issue by DRLDoom** [RocketChat/Rocket.Chat.Electron#2035]
## My Setup

- Operating System: Windows 10
- App Version: 3.2.x
- Installation type: exe, msi

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Version 3.2.x of the Windows Rocket.Chat client smart card functionality is not working. User is never prompted for PIN.
I have tested 3.2.1 and 3.2.2

### Current Behavior

Click Login > select certificate... no prompt for PIN

### Expected Behavior

Click Login > select certificate > prompt for PIN > enter PIN

**Comment by DRLDoom** [comment]
Just tested v3.2.3 - Issue still on-going.

**Comment by ajkerzner** [comment]
I've also encountered this, and I worked around it by adjusting the runtime properties of all but one certificate to disable the "Client Authentication" and/or "Smart Card Logon" properties from each cert's EKU.
Related to pull request #1511 possibly.

**Comment by ajkerzner** [comment]
Possibly related to #2095 as well

**Comment by sagansapien** [comment]
Thanks @ajkerzner, is that done server or client side?

**Comment by ajkerzner** [comment]
> Thanks @ajkerzner, is that done server or client side?

It's done client-side. If you have a smartcard, you'd go into Control Panel for "Manage User certificates," then go to the Personal\Certificates folder. From there, you would want to look at the certificates with an "Intended Purpose" including "Smart Card Logon" and/or "Client Authentication" (I can't remember which is the critical one... maybe both are).

For all _except_ the one you want to use for authentication: open each certificate, go to the "Details" tab, and click "Edit Properties". From "Certificate Properties", you just want to uncheck those two aforementioned purposes.

To most applications, only certificates with one/both of those purposes are considered. If RocketChat desktop client only sees one certificate that can be used, it won't prompt you to choose. (I've only seen this bug when you have to choose the certificate, so all of this is meant to bypass that certificate choice by limiting RocketChat desktop client to a single certificate choice.)

For certificates linked to a removable smartcard or other removable hardware device, the changes are temporary (I don't know if certs on a nonremovable media are the same) and lost when smartcard is disconnected/reconnected.

**Comment by jeanfbrito** [comment]
Please test if the lastest release (3.7.0) has solved this issue.

**Comment by sagansapien** [comment]
Hi, this still appears to be an issue with 3.7.0. Thank you.

**Comment by jeanfbrito** [comment]
Hello! We had fixed some issues that was happening in Windows that involved the integration with Electron.
Could you test our last release again? If the problem persists, could you help us on how to reproduce the problem locally? Then I can work in the issue more efficiently.

Thanks in advance!

**Comment by sagansapien** [comment]
Hi @jeanfbrito, I just tested the 3.7.5 MSI on two Windows 10 systems (one build 1909 and the other 20H2) with the same result.

To reproduce this issue, you will need a smart card or a least a soft certificate and a chat server that is configured to accept it.

After I add our chat server to the client, I click the "Sign in" (Cas) button which presents me with a "Select certificate" dialogue. Up until this point, everything is normal- all of the expected certificates are available here for selection. After choosing my certificate, the expected behavior is for another dialogue to appear to prompt me for the PIN associated with the certificate's private key. The PIN prompt never appears, so authentication goes nowhere.

I have two chat servers to test with and both behave similarly.

We use a smart-card driver/middleware called ActivClient by HID Global (version 7.2.1). I have tested Rocket.Chat with and without this software installed so I don't think it's a factor with this issue. I wanted to mention it because when ActivClient is installed, the expected PIN prompt comes from the ActivClient software. On a system without ActivClient, Windows 10 handles the PIN prompt natively.

I should also point out that the logon process works as expected when accessing these servers via Chrome/Edge from the same client computer.

Please let me know if there is anything else I can do to assist you. Until this is fixed, my organization is stuck with using the web apps!

Thank you

**Comment by jeanfbrito** [comment]
> Hi @jeanfbrito, I just tested the 3.7.5 MSI on two Windows 10 systems (one build 1909 and the other 20H2) with the same result.
> 
> To reproduce this issue, you will need a smart card or a least a soft certificate and a chat server that is configured to accept it.
> 
> After I add our chat server to the client, I click the "Sign in" (Cas) button which presents me with a "Select certificate" dialogue. Up until this point, everything is normal- all of the expected certificates are available here for selection. After choosing my certificate, the expected behavior is for another dialogue to appear to prompt me for the PIN associated with the certificate's private key. The PIN prompt never appears, so authentication goes nowhere.
> 
> I have two chat servers to test with and both behave similarly.
> 
> We use a smart-card driver/middleware called ActivClient by HID Global (version 7.2.1). I have tested Rocket.Chat with and without this software installed so I don't think it's a factor with this issue. I wanted to mention it because when ActivClient is installed, the expected PIN prompt comes from the ActivClient software. On a system without ActivClient, Windows 10 handles the PIN prompt natively.
> 
> I should also point out that the logon process works as expected when accessing these servers via Chrome/Edge from the same client computer.
> 
> Please let me know if there is anything else I can do to assist you. Until this is fixed, my organization is stuck with using the web apps!
> 
> Thank you

@sagansapien I spend some days researching about this to see if I can found any solution, but without success.
Would be possible to have access to one machine that has this installed so I can debug where is the problem?
I dont have any smartcard that could be used to simulate the workflow.
If you could reach me in open.rocket.chat my user is jean.brito. There we could talk about and try to found a solution.

**Comment by jeanfbrito** [comment]
@sagansapien please, I need more information about your server. What kind of authentication are you using? Is SAML?
I will need to know what are the configurations to reproduce the server here in local.

**Comment by sagansapien** [comment]
@jeanfbrito apologies for the delay. I don't manage the servers, not sure if it's SAML or not. I know one is a KeyCloak server that authenticates against Active Directory.

**Comment by jeanfbrito** [comment]
> @jeanfbrito apologies for the delay. I don't manage the servers, not sure if it's SAML or not. I know one is a KeyCloak server that authenticates against Active Directory.

Could you find info about the server configuration with the manager? I would need to know what configurations are being used to reproduce the server locally.

**Comment by jeanfbrito** [comment]
@sagansapien we fixed a problem on the selection of certificates on the version 3.8.6. Please test if the behavior of the smartcard has changed.
