### ISSUE TITLE
Threads not working sometimes

### ISSUE THREAD

**Issue by W4RH4WK** [RocketChat/Rocket.Chat.Electron#2036]
## My Setup

- Operating System: Windows
- App Version: 3.2.2
- Installation type: .msi

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Sometimes the Threads panel stays empty showing *Error*. There is no error in the developer console. This is not new, I've been encountering this error for a few versions now.

![image](https://user-images.githubusercontent.com/328798/118316037-99c96800-b4f6-11eb-9dd4-1a07b1bffb27.png)

### Current Behavior

Sometimes shows error and no threads.

### Expected Behavior

Always show threads, no error.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
