### ISSUE TITLE
The program window moves very unsteadily.

### ISSUE THREAD

**Issue by berndwa** [RocketChat/Rocket.Chat.Electron#2037]
## My Setup

- Operating System: Windows 10 - 64bit
- AMD Ryzen 7 1700 - 32GB RAM
- App Version: 3.11 to 3.22
- Installation type: .exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When moving the window over the desktop the window moves very unsmooth.

**Comment by Cancer-zern** [comment]
Am confirm it too

**Comment by levifranzen** [comment]
Can confirm it in 3.2.3 too.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
