### ISSUE TITLE
Unable to drag and drop files in 3.2.2

### ISSUE THREAD

**Issue by Drudicta** [RocketChat/Rocket.Chat.Electron#2041]
### Description:

Unable to drag and drop images or files.

### Steps to reproduce:

1. Click and drag file from explorer window to Rocket chat window
2. Rocket chat gives "Restricted" symbol disallowing drag and drop.

### Expected behavior:

Dropping a file uploads it to the chat

### Actual behavior:

Restricted symbol when trying to drag over.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Windows 10 Enterprise
- Deployment Method: Client executable
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Desktop 3.2.2
- Operating System: Windows 10 Enterprise

**Comment by johncrisp** [comment]
Please state the Rocket.Chat version and the deployment type eg snap/docker etc

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
