### ISSUE TITLE
Translation is not used

### ISSUE THREAD

**Issue by CvH** [RocketChat/Rocket.Chat.Electron#2048]
## My Setup

- Operating System: Win10
- App Version: 3.2.2
- Installation type: rocketchat-setup-3.2.2.exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The Interface translation is not working. 
I have german at the OS and german at Rocket.Chat - the Electron Interface stays english all the time.
The Shortcuts are translated for some reason.
![image](https://user-images.githubusercontent.com/1355173/119469844-07239700-bd48-11eb-8a23-b874b75dc84a.png)

### Current Behavior
The Electron App Interface is in english.

### Expected Behavior
The Electron App Interface should be the same as the OS.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Comment by CvH** [comment]
![image](https://user-images.githubusercontent.com/1355173/183143752-8c0555e5-8ae2-48d8-8821-02c80e8e9df0.png)
this is 3.8.7 at windows, still the same problem
basically translations are completly broken even they exist at the repository

for example "Server list" from the screenshot https://github.com/RocketChat/Rocket.Chat.Electron/blob/master/src/i18n/de-DE.i18n.json#L113

**Comment by jeanfbrito** [comment]
@CvH thanks for replying. I will take a look at what is happening.

**Comment by CvH** [comment]
Version 3.8.13, same problem.

**Comment by jeanfbrito** [comment]
> Version 3.8.13, same problem.

This was to be fixed on the 3.8.13. The translations was lacking some items.
Do you have this problem in other computers or just this one?

**Comment by CvH** [comment]
It happens at two different pc with completely different setup (Win11) (1x domain, 1x home pc) with the identical problem.
Removed RC + Appdata and reinstalled it again. Same problem at latest.

![image](https://user-images.githubusercontent.com/1355173/202285079-5b5fc67f-7e85-4270-980f-8cb8d6b3d103.png)

**Comment by CvH** [comment]
Same problem with 3.8.15

**Comment by CvH** [comment]
nearly 2 years later, same general problem still exist at the latest 3.9.14 :( 

![image](https://github.com/RocketChat/Rocket.Chat.Electron/assets/1355173/0bebc02c-b0b9-4ec7-bedb-dcad1600a71d)

**Comment by CvH** [comment]
great 👍 I test as soon there is a build available

**Comment by CvH** [comment]
tested with 4.0.1 at different machines (clean install etc) but still the same issue

![image](https://github.com/user-attachments/assets/f0323779-0fa4-400b-958b-e792cb540eea)
