### ISSUE TITLE
switch between chat windows

### ISSUE THREAD

**Issue by lw-schick** [RocketChat/Rocket.Chat.Electron#205]
I miss the possibility to have each chat in an separate window. 
This will give the possibility to switch between chats via ALT+TAB

Your Rocket.Chat version: Version 1.3.1
##

**Comment by seobullshit** [comment]
foud out that you can search vai CTRL+P (https://rocket.chat/docs/user-guides/keyboard-shortcuts/) also in the desktop client

**Comment by lw-schick** [comment]
ok, that is a way of doing the switching part. But i can still not visit more than one chat...

**Comment by gdelavald** [comment]
Currently we chose to stick with the single window style, so I'll close this issue as this is not going to get implemented in the near future. Thanks for your suggestion.
