### ISSUE TITLE
Yarn release with error: ENOENT: no such file or directory, stat

### ISSUE THREAD

**Issue by aries1906** [RocketChat/Rocket.Chat.Electron#2050]
## My Setup

- Operating System: Windows 10
- App Version: 3.2.2
- Installation type: .exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
<img width="1390" alt="Screen Shot 2021-05-31 at 12 27 04" src="https://user-images.githubusercontent.com/84085568/120144229-c2967080-c20b-11eb-89fa-d765828dd518.png">

### Current Behavior
• building block map  blockMapFile=dist\rocketchat-setup-3.2.2.exe.blockmap
⨯ ENOENT: no such file or directory, stat '....\Rocket.Chat.Electron-3.2.2\dist\__msi-x64'  failedTask=build stackTrace=Error: ENOENT: no such file or 
directory, stat '....\Rocket.Chat.Electron-3.2.2\dist\__msi-x64'

### Expected Behavior
Should run "yarn release" without any error.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
