### ISSUE TITLE
Administration stuck in Integrations page in release 3.15.0

### ISSUE THREAD

**Issue by sergeydeg** [RocketChat/Rocket.Chat.Electron#2051]
## My Setup

- Operating System: CentOs 7.4 
- App Version: 3.15.0
- Installation type: Docker image

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
With Windows desktop app and web interface after viewing Administration -> Integration tab it is stuck. Changint to other tabs does not change details rendering. No error in logs.

### Expected Behavior
Details renderings change  between tabs.

**Comment by changlogi** [comment]
Same here..
Operating System: CentOs 8.0
App Version: 3.15.0

**Comment by ggazzo** [comment]
this is a rocket.chat issue and we already fixed this, any problem let me know.
