### ISSUE TITLE
Does not download the file from the server, but opens it in the browser

### ISSUE THREAD

**Issue by wkipers** [RocketChat/Rocket.Chat.Electron#2052]
## My Setup

- Operating System: Windows 10
- App Version: 3.2.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When you try to download the resulting file, a rocket chat opens in the browser with an access error. If you open the rocket chat in a browser, then everything is fine.

### Current Behavior
User uploads a file. Instead of downloading a file (pdf, Excel), the default browser opens.

### Expected Behavior
When downloading a file, a dialog box opens with a choice of where to save the file.

**Comment by changlogi** [comment]
Same here
My SetupOperating System: CentOs 8
App Version: 3.15.0
Installation type: Docker image

**Comment by jeanfbrito** [comment]
Please test if the issue persists with our latest release. I will be closing the issue, any problem tell me and I will open it again.
