### ISSUE TITLE
App from Mac App Store crashes on launch

### ISSUE THREAD

**Issue by Feuermurmel** [RocketChat/Rocket.Chat.Electron#2054]
## My Setup

- Operating System: macOS 10.13.6
- App Version: 3.0.3 (newest one available when installing via the link on https://rocket.chat/install/)
- Installation type: Mac App Store (https://apps.apple.com/ch/app/rocket-chat/id1086818840?l=en&mt=12)

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When I double-click the app after installing it from the Mac App Store, it bounces in the dock once or twice and then terminates.

When running the main binary from a console, I get the following output:

```
$ /Applications/Rocket.Chat.app/Contents/MacOS/Rocket.Chat
[bugsnag] Loaded!
[76886:0531/144128.080300:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Trace/BPT trap: 5
$
```

I have never gotten it to work (I tried the first time probably three to four years ago and a few times in-between and always got the same result). So I don't think there are any existing configuration files that could mess things up.

What should I try next?

**Comment by Feuermurmel** [comment]
Do you need more information to investigate this issue?

**Comment by jeanfbrito** [comment]
The Apple Store version is updated, you can install it from there right now.
