### ISSUE TITLE
Application don't open after exit and start Windows. (3.2.2)

### ISSUE THREAD

**Issue by DimmoK** [RocketChat/Rocket.Chat.Electron#2055]
Sorry for my bad English.
## My Setup

- Operating System: WIndows 8.1 Prof x64
- App Version: 3.2.2
- Installation type: exe

- I have tested with the latest version
- I can simulate the issue easily.

## Description
Launch Rocket.Chat --> Exit from File - Exit or Ctrl+Q --> Launch again...
Application does not opening. In the Task Manager I see 3 process of Rocket.Chat.

### Current Behavior
Application does not opening.

### Expected Behavior
I see Rocket.Chat application's main window.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
