### ISSUE TITLE
Images won't display on browser

### ISSUE THREAD

**Issue by ChristianCOMMARMOND** [RocketChat/Rocket.Chat.Electron#2057]
Hi,

I have Rocketchat 3.13.3.

we have a problem with images not showing in the browser but working on android app.

The problem looks to ba the same than in bug #517

If I look at the URL of the image on the browser, I get:
https://www.mydomain.dom/**rocketchat/rocketchat**/file-upload/XWvqKXgGopMobRQzr/Clipboard%20-%20June%203,%202021%2011:17%20AM?download

rocketchat is 2 times.

If I open the same in a browser with only one 'rocketchat' in the URL, it works.

How to solve this?

regards,

Christian COMMARMOND

**Comment by johncrisp** [comment]
Hi.

This does not appear to be related to the Electron app which is what this repo is for.

I think this is most likely related to either your web server setup or the possibly Rocket.Chat core though as the Android app works it is hard to see that is the case.

I suggest you first test on latest version of Rocket 3.15 and then ask for someone to look at your setup on https://open/.rocket.chat #support or https://forums.rocket.chat

https://rocket.chat/docs/contributing/reporting-issues
https://rocket.chat/docs/getting-support

Thanks.

**Comment by ChristianCOMMARMOND** [comment]
Hi,

thank you for your answer, after more research with my users, it looks like
a regression after the last update to rocketchat 3.13, two weeks ago. I
will upgrade to the last version tomorrow and if the problem still exists,
I will open a case to the correct place.

Sorry for my error, I did it because I found an identical issue on your
repo, and I did not check correctly where I was.

So, please, close this one.

regards,
Christian COMMARMOND
+33 6 82 33 52 32

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
