### ISSUE TITLE
Channel notification settings not respected

### ISSUE THREAD

**Issue by ThomasKientz** [RocketChat/Rocket.Chat.Electron#2058]
## My Setup

- Operating System: Mac OS 10.15.7
- App Version: 3.2.2
- Installation type:   dmg

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

Channel notification settings are not respected.

### Current Behavior

Enabling "ignore @all and @here" doesn't ignore `@all` and `@here` notifications in channel.

### Expected Behavior

To not receive notification when "ignore @all and @here"  is enable.

<img width="1632" alt="Capture d’écran 2021-06-03 à 10 44 56" src="https://user-images.githubusercontent.com/10157845/120616447-86f0e600-c459-11eb-8f4b-e4210d0bf0e5.png">

**Comment by johncrisp** [comment]
As per the bug template can you please confirm your server version and deployment type eg docker/snap etc - this is really important as often Issues have been fixed on the latest versions (we are currently on 3.15)

Does this happen on a web browsers as well?

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
