### ISSUE TITLE
RocketChat disable Notifications on ubuntu 16.04

### ISSUE THREAD

**Issue by pandaadb** [RocketChat/Rocket.Chat.Electron#206]
Hi,

I am using Ubuntu 16.04 with the rocket chat client downloaded for Linux.

On Unity, the notifications are quite annoying (not to say terrible). Meaning that they are pop-ups that have to be OK'ed to disappear. Getting private messages makes this a tedious task.. 

I have been trying to find a way to disable those notifications. When going to the settings, in the Preference of my account, it says: 

Desktop Notifications are Enabled 

However, there is no option to disable this. Is there a config file that I can change or any other way to disable these notifications? 

Thanks!

Artur 
##

**Comment by JordyMoos** [comment]
Same issue here this is really annoying

**Comment by propertunist** [comment]
how does the browser let you disable them?

**Comment by pandaadb** [comment]
For chrome: 

https://support.google.com/chrome/answer/3220216?hl=en-GB

**Comment by propertunist** [comment]
@pandaadb - thanks, so there's no way to switch it off per site at present? (maybe there is an extension). the reason i am asking is because my friend said that on his phone rocket.chat was putting out notifications constantly, even though he was using the chat in the active window. in the end he found how to turn off all notifications i think.

**Comment by pandaadb** [comment]
The notifications in the browser can be blocked per site (so only rocketchat while e.g. facebook keeps notifying )

**Comment by compuguy** [comment]
Mine are actually broken on 16.04 (instead of using the transparent box, they use that annoying ok box).

**Comment by pandaadb** [comment]
@compuguy thanks - that seems to have fixed it for me. @propertunist see #170

**Comment by engelgabriel** [comment]
Hi @pandaadb @JordyMoos @propertunist @compuguy @alexbrazier is this still a problem on version `2.4.0` or can we close this issue?

**Comment by pandaadb** [comment]
I am still on an old version so can not comment. I am happy for you to close, if I get to do the upgrade and this issue persists, I will get back to you :)

**Comment by pandaadb** [comment]
Ah ... - i clicked on "close". I'll leave it closed for now but please feel free to reopen

**Comment by gesquive** [comment]
I am on v2.8.0 of the linux client, this still seems to be a problem.
