### ISSUE TITLE
Window content not loading after update from 3.2.2 to 3.3.0

### ISSUE THREAD

**Issue by Pschemek** [RocketChat/Rocket.Chat.Electron#2069]
After update to 3.3.0 can't load RocketChat window contents. It stays empty and "reload" actions doesn't help.

## My Setup

- Operating System: Windows 10 21H1
- App Version: 3.3.0
- Installation type: exe and msi
![rocket3 3 0-blank](https://user-images.githubusercontent.com/72245545/122339310-32616680-cf41-11eb-99d7-0a33863705e6.gif)

**Comment by Pschemek** [comment]
Maybe it's good idea to make "Beta" versions before final release. We can check bugs and avoid problems on every workstation inside whole organizations.

**Comment by CvH** [comment]
You didn't looked at the taskmanager yet ? :) https://github.com/RocketChat/Rocket.Chat.Electron/issues/2068
Releasing untested versions as "stable" and ship it at day one by auto update is very likely creating a mess today for a lot users.

So basically everyone who has autoupdate enabled (default at install) is screwed now (likely a lot users hitting that bug).

**Comment by DimmoK** [comment]
Hello.
+1 I have the same problem!
Window is empty and loop loading "..."

**Comment by tassoevan** [comment]
Release 3.3.0 is unpublished while we investigate why Windows builds failed.
