### ISSUE TITLE
duplicate, request .msi installer

### ISSUE THREAD

**Issue by frasercarter** [RocketChat/Rocket.Chat.Electron#207]
hi guys, 

I think it would be a great step forward if we pushed for a .msi installer, or an exe that accepts -silent switches to aid in automated deployments for enterprise.

further to this being able to pre-configure a default or multiple servers so end users are only prompted with a login page would be ideal.
##

**Comment by toddjames** [comment]
Since Rocket.Chat.Electron uses NSIS for installation, you can use /S to perform a silent install/uninstall.

**Comment by compuguy** [comment]
@toddjames That's great, but you need an msi installer if you want to push the application out via Group Policy. I don't believe it will take anything else but a msi.

**Comment by toddjames** [comment]
*shrug* There are better ways to deploy software than Group Policy. SCCM and PDQ Deploy can handle .exe files with silent install switches.

**Comment by graywolf336** [comment]
Looks like msi is possible: https://github.com/electron-userland/electron-builder/wiki/Options#squirrelwindows

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
