### ISSUE TITLE
Problem with 3.3.0 version

### ISSUE THREAD

**Issue by Tasselxof** [RocketChat/Rocket.Chat.Electron#2070]
![Без имени](https://user-images.githubusercontent.com/86041857/122346260-6e9cc300-cf51-11eb-8754-12a9c117938f.png)
Problem with deploying the app to full-screen mode

**Comment by matix42** [comment]
Hello,

Version 3.3.0 is using lot of cpu as well.

**Comment by Tasselxof** [comment]
> Hello,
> 
> Version 3.3.0 is using lot of cpu as well.
The application functionality is not much better than Skype and consumes a huge amount of resources.(corporate computers, on the contrary, require small resources to work with)

**Comment by eldervamp** [comment]
Yep, This version is unusable. Freezes from launch and stays unresponsive. Need to Ctrl-Alt-Del to close.

![rocket](https://user-images.githubusercontent.com/37281419/122369356-a3a71680-cf4d-11eb-90b3-db94ce912822.jpg)

**Comment by Xarkam** [comment]
How do they manage to never have a correct version since 2.17?

**Comment by Tasselxof** [comment]
> How do they manage to never have a correct version since 2.17?
in version 2.17, the screen display via jitsi does not work

**Comment by marcuslayne** [comment]
High CPU on this version for me. Had to roll back

**Comment by mbu147** [comment]
FYI: On MacOS 11.3.1 everything works fine.

**Comment by blacklord049** [comment]
Feedback on Windows:
- High CPU usage and possible high memory usage over time
- Server's list displays on every start (even if you disable in in the menu, it will enable again the next time Rocket.chat is started)
- The "new messages" notification icons don't refresh correctly if a message is read

**Comment by tassoevan** [comment]
Release 3.3.0 is unpublished while we investigate why Windows builds failed.

**Comment by flydvorkin** [comment]
3.3.0 Very slow work and high CPU load

**Comment by christophlsa** [comment]
> Release 3.3.0 is unpublished while we investigate why Windows builds failed.

The cpu usage is also on linux really high. No problems if using directly in the browser.

**Comment by matthias4217** [comment]
Version 3.4.0 was released on Snapcraft yesterday. It has the same intensive CPU consumption than version 3.3.0 (tested on Ubuntu). However, I see no mention of version 3.4.0 on this repository, which confuses me quite a lot.

**Comment by marcuslayne** [comment]
I believe that 3.4.0 is the edge version and looks like it was only released for Linux clients that are using rocket chat electron. 3.4.0 has not hit stable status.

**Comment by marcuslayne** [comment]
> Version 3.4.0 was released on Snapcraft yesterday. It has the same intensive CPU consumption than version 3.3.0 (tested on Ubuntu). However, I see no mention of version 3.4.0 on this repository, which confuses me quite a lot.

I believe that 3.4.0 is the edge version and looks like it was only released for Linux clients that are using rocket chat electron. 3.4.0 has not hit stable status.

**Comment by cazetto** [comment]
I am closing this issue since version 3.4.0 was declined.

**Comment by christophlsa** [comment]
But is there now a fix for this issue except using an old version?
