### ISSUE TITLE
Server list unchecked setting is ignored on the next startup

### ISSUE THREAD

**Issue by urosino** [RocketChat/Rocket.Chat.Electron#2071]
### Description:
Server list is displayed on the next startup of Rocket.chat Windows app, even though it was set to be hidden, last time application was closed.

### Steps to reproduce:
1. Hit the ALT button on Windows
2. Click View
3. Uncheck Server list
4. Quit Rocket.chat
5. Start Rocket.chat, the server list is again showing

### Expected behavior:
1. The server list should be hidden
![LumpySouthernhairnosedwombatThursday](https://user-images.githubusercontent.com/25570106/122413832-fa7d1200-cf86-11eb-9f86-81597a167d1f.png)

### Actual behavior:
This is how information is displayed
![ImportantGreatargusThursday](https://user-images.githubusercontent.com/25570106/122413549-c0137500-cf86-11eb-9705-7b7ca2dfc406.png)

### Server Setup Information:
* Version of Rocket.Chat Server: 3.15.0
* Operating System:  Docker image
* Deployment Method: Azure Kubernetes Pod
* Number of Running Instances: 1
* DB Replicaset Oplog: rs0
* NodeJS Version: Unknown - see rocketchat:3.4.1 image.
* MongoDB Version: 4.0.12

### Client Setup Information
- Desktop App or Browser Version: Desktop App, 3.3.0

- Operating System: Windows 10

### Additional context
 - No additional context

### Relevant logs:
 - No other logs

**Comment by Nono-m0le** [comment]
Same here with : 
Server : 3.15.0 (Snap install)
Client: 3.3.0, win10

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
