### ISSUE TITLE
High number of client config file updates clash with McAfee Antivirus

### ISSUE THREAD

**Issue by ajkerzner** [RocketChat/Rocket.Chat.Electron#2072]
## My Setup

- Operating System: Windows 10
- App Version: 3.3.0, 3.2.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
In regular use, this application updates the `config.json` config file many times a minute. In doing so, it seems to create a new file and replace the original. This clashes with a McAfee antivirus "solution" in spectacular fashion, leading to a client that stutters, freezes, and is otherwise unusable. Additionally, it's a potentially expensive disk operation.
Examples of stuff that would trigger a rewrite:
* change in channels
* window state (this is the big one - window size, position, focus state, visibility, etc.)

### Current Behavior
Config file is updated via "copy and replace" or some other mechanism. This is not ideal even when McAfee is removed from the equation.
Config file updates are slowed down due to McAfee and maybe other contributing factors, slowing down the application.

### Expected Behavior
Application should be writing to the file at most once a minute. Config file changes should be staged and written to disk when optimal, perhaps in a queue.
Alternatively (because I don't know much about where RocketChat stops and Electron starts): reduce the information written to the config file. Perhaps only write the window state when exiting the application, and maybe also write it to a separate file, say `state.json`?

### Other Notes

* Alongside this, I'm also seeing high CPU usage from the application.
* I have made a couple assumptions that these are related:
  * #2068 
  * #1605
  * #1908

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
