### ISSUE TITLE
[macOS] Empty navbar in version 3.3.0

### ISSUE THREAD

**Issue by nodeg** [RocketChat/Rocket.Chat.Electron#2073]
## My Setup

- Operating System: macOS 11.4 (x86_64)
- App Version: 3.3.0
- Installation type: Homebrew (`brew install rocket-chat`)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When using version 3.3.0 you cannot access several functions in the navbar after some time when the app is opened. I have no exact time but when starting the app the first few minutes are fine. Furthermore you cannot close the app with `command + q` anymore.

### Current Behavior
Grayed out elements in navbar that were accessable and not grayed out before.

### Expected Behavior
Accessable elements in the navbar as before with version 3.2.2.

### Screenshots
<img width="335" alt="Screenshot 2021-06-18 at 12 49 09" src="https://user-images.githubusercontent.com/12104291/122550900-92850500-d034-11eb-8c6a-757f88ed12e5.png">
<img width="335" alt="Screenshot 2021-06-18 at 12 49 26" src="https://user-images.githubusercontent.com/12104291/122550908-93b63200-d034-11eb-981f-adbcfba17eb2.png">
<img width="446" alt="Screenshot 2021-06-18 at 12 49 41" src="https://user-images.githubusercontent.com/12104291/122550912-944ec880-d034-11eb-87d3-88b6d30a2fc9.png">

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by nodeg** [comment]
The issue is indeed resolved with version 3.7.5. I tested this a few seconds ago. Thanks @jeanfbrito!
