### ISSUE TITLE
Enter the room directly by just clicking the link on rocket chat alarm

### ISSUE THREAD

**Issue by changlogi** [RocketChat/Rocket.Chat.Electron#2075]
## My Setup

- Operating System: Windows 10
- App Version: 3.2.2
- Installation type:  exe

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

When the alarm shows on the screen, It would be very nice to enter the room directly by just clicking the link on rocket chat alarm

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
