### ISSUE TITLE
Default Server is not connected at First Startup. Prompted for Server Address Instead (open.rocket.chat)

### ISSUE THREAD

**Issue by amoebav** [RocketChat/Rocket.Chat.Electron#2077]
## My Setup

- Operating System: W10
- App Version: 3.2.2
- Installation type: exe

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description
Install fresh rocket.chat install on fresh windows 10 profile. Modify servers.json to add your own default server. Then startup rocket.chat client.

### Current Behavior

I can see my default server is loaded in the sidebar, however the client does not prompt for username and password for my server. Instead the focus is on the the open.rocket.chat server. For me, not a big  deal. I can click on my server in the sidebar and select my default server, but for end users they have no clue. They just click connect and end up registering on open.rocket.chat.

![image](https://user-images.githubusercontent.com/53012340/122798910-bdff2e00-d286-11eb-8e5f-e475721c36cb.png)

### Expected Behavior
When I start Rocket.Chat client it should connect to my default server (set in servers.json) automatically and prompt user for credentials to my server.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
