### ISSUE TITLE
No possibility to open link attached in chat (Anfroid/iOS latest)

### ISSUE THREAD

**Issue by RodionCoach** [RocketChat/Rocket.Chat.Electron#2079]
![photo5375286248689742517](https://user-images.githubusercontent.com/25160654/123076641-03a42e00-d422-11eb-95ac-e7314ac2d9ab.jpg)

## My Setup

- Operating System: Android/iOS
- App Version: 4.17.0.24391
- Installation type: 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I can`t open the attached link in chat

### Current Behavior
when you click on the link in the modal window, nothing happens

### Expected Behavior
the webview should be opened by the link

**Comment by ggazzo** [comment]
I'm afraid you are at the wrong repository, please check https://github.com/RocketChat/Rocket.Chat.ReactNative
