### ISSUE TITLE
Mac App Icon Does Not Match Big Sur Design Language

### ISSUE THREAD

**Issue by rafiv** [RocketChat/Rocket.Chat.Electron#2080]
Currently, the version on the mac App Store does not have an icon appropriate to the Big Sur design language.

### Steps to reproduce:
1. Install app from the mac App Store
2. View icon, e. g., in dock or in the launchpad compared to others.

### Expected behavior:
Having an icon which is compliant with the [guidelines from Apple](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).

### Actual behavior:
The icon looks, compared to the others, out of place.

### Server Setup Information:
multiple, irrelevant in this context.

### Client Setup Information:
Desktop App or Browser Version: App from the mac App Store, 3.0.3
Operating System: macOS Big Sur 11.4

**Comment by rafiv** [comment]
Thanks for moving the issue.

Additionally: Can I expect that the Mac App Store Version will receive the update soon or is this version abandoned and I should just install it manually?

**Comment by andylin2004** [comment]
Bumping on this. I am surprised that whoever handles publishing the MAS app bothered to put in the app privacy info, but didn't bother to update the app binary at all. Is it dead in the water?

**Comment by jeanfbrito** [comment]
We will be working in updating the Apple Store version. 
For now, please keep using the Github releases page for install it.

**Comment by jeanfbrito** [comment]
The Apple Store version is updated, you can install it from there right now.
