### ISSUE TITLE
cannot install rocketchat desktop client on Debian Testing/Unstable and Debian 11 RC2

### ISSUE THREAD

**Issue by harridu** [RocketChat/Rocket.Chat.Electron#2085]
## My Setup

- Operating System: Debian Testing
- App Version: 3.2.3
- Installation type: dpkg

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
The rocketchat Debian package cannot be installed on Debian Testing/Unstable due to a missing dependency:
```
# apt install rocketchat
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rocketchat : Depends: libappindicator3-1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I know there is a snap package, but snaps are not an option.

**Comment by nitmir** [comment]
Debian 11 was released yesterday. This issue is now about Debian Stable.
See https://github.com/signalapp/Signal-Desktop/pull/5031 or https://github.com/vector-im/element-desktop/pull/170 for how it has been fixed for Signal desktop and Element desktop

**Comment by nitmir** [comment]
related to #1975

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
