### ISSUE TITLE
Background of sidebar buttons not fully transparent 

### ISSUE THREAD

**Issue by bubonicfred** [RocketChat/Rocket.Chat.Electron#2086]
## My Setup

- Operating System: Win10
- App Version: 3.2.3
- Installation type: exe, dmg, package manager etc. 

- [x ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![Screenshot 2021-07-04 182416](https://user-images.githubusercontent.com/1294298/124378614-b6fc0500-dcf5-11eb-99a2-1aeb69410eb9.png)
Side bar buttons have slightly opaque background, especially noticeable on add new server button as background is not square.

I've noticed in the style sheet that the alpha for the background colors for these buttons is 0.1 instead of 0 for some reason.

**Comment by ggazzo** [comment]
fixed ;)
