### ISSUE TITLE
Feature request on reduced window of windows client

### ISSUE THREAD

**Issue by BENETNATH** [RocketChat/Rocket.Chat.Electron#2089]
Hi,
I'm using 3.2.2 version of the client and there are two features that I'd be glad to have.
1) when I'm in a discussion in a reduced window, the list of channels and users is not visible as expected. But I would like to be able to display it by clicking on the discussion title (name or channel).
2) it could be great to keep a small blank part on the left part in reduced view wher eyou could just have the ongoing discussion with user, like chats that were active in the last hour, with just the picture to switch quickly between them.

I'm really fond of rocket chat, especially in a tiny window, but that's not fluid when you need to enlarge the window just to switch to another channel or ongoing discussion

thanks for your great product anyway !

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Comment by BENETNATH** [comment]
Yep, it's fixed !
Thanks
