### ISSUE TITLE
Audio & Video chat not working. Neither does desktopsharing.

### ISSUE THREAD

**Issue by roesneb** [RocketChat/Rocket.Chat.Electron#209]
## My Setup
- **My OS name and version**: Linux Mint 17.3
- **My current app version**:  1.3.1
- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

If i want to start Video Chat the a Popup says:

**Error**
There was an error connecting to your microphone.

Cannot use microphone for a unknown reason

Similar Error appears for Desktopsharing.

Permission denied. Screensharing extension could not be installed.
#### Current Behavior

![image](https://cloud.githubusercontent.com/assets/5518190/16042467/1548b006-323b-11e6-997b-43b994f15ad2.png)

![image](https://cloud.githubusercontent.com/assets/5518190/16042476/2b8677c2-323b-11e6-9fee-20fdd69e491a.png)
#### Expected Behavior

Expected behaviour is, that screensharing and audio & video call works.
##

**Comment by gdelavald** [comment]
Desktop sharing is still an issue, but video and audio have been fixed in the latest version.
I'll close this as we already have other issues for desktop sharing and Jitsi bugs overall should be issued on the official Rocket.Chat repo.
