### ISSUE TITLE
Jitsi "open in new windows" does not work anymore after upgrade from 3.1.1 to 3.2.0

### ISSUE THREAD

**Issue by sandreddu** [RocketChat/Rocket.Chat.Electron#2090]
## My Setup

- Operating System: Windows 10
- App Version: 3.2.0 and later
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Self hosted jitsi server, client certificate authentication
Starting a video call, should open a new window.

### Current Behavior
The certificate selection window opens, then select the correct certificate, then nothing happens.
On the browser it works ok

### Expected Behavior
Jitsi window opens

![image](https://user-images.githubusercontent.com/47738900/124590049-fb54e580-de5a-11eb-9741-ddc1121b1ea6.png)

**Comment by sandreddu** [comment]
Works as designed with desktop client 3.2.2 for Linux (dmg install)

**Comment by johncrisp** [comment]
> Works as designed with desktop client 3.2.2 for Linux (dmg install)

And closing.

**Comment by sandreddu** [comment]
Thank you John. As you can see from the "My Setup" section, the problem appears on a Windows 10 client.

Operating System: Windows 10

The line about "working as designed on Linux" just means that the problem is specific to the Windows version, while it works on Linux (I cannot test on a Mac OS client, therefore I have no information about that.)

So please if you would be so kind to reopen this ticket, or should I open a new one with a better description?

Thanks in advance,
