### ISSUE TITLE
Click to notification not open room chat

### ISSUE THREAD

**Issue by korobita** [RocketChat/Rocket.Chat.Electron#2091]
## My Setup

- Operating System: Window 10
- App Version: 3.2.3
- Installation type:  .exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I click to notification new messenge but not open room got new messenge.

**Comment by ArielBenAharon** [comment]
Same here - when I click on the notification window nothing happens.

Windows 10

**Comment by matchsp** [comment]
I'm expericing the same error. I have tested on Windows 10, RC Version 3.2.3 and 3.1.1 both with the same problem. My RC Server version is 3.15.0. 
On the web Client works ok

**Comment by Mystikal57** [comment]
same problem for me with last version

**Comment by ankar84** [comment]
We have that problem too in latest 3.2.3 version
Previous version we use was 3.0.7 and click on notification opened proper chat where notification comes from.

**Comment by Mystikal57** [comment]
i confirm that 3.0.7 works, but not when minimized

**Comment by Mystikal57** [comment]
Problem seems to be fixed in  3.4.0-snapshot

**Comment by Mystikal57** [comment]
not fixed in pre-release 3.2.4 :-(

**Comment by ankar84** [comment]
Tested and confirm that bug on versions of Rocket.Chat Electron 3.1.1 and 3.2.3
Tested on two Windows 10 builds - 1803 and 1809 - both have that bug - nothing happens when I click notification.

**Comment by ankar84** [comment]
@cazetto @gencer actually that issue is not totally fixed in 3.5.0
**If app is minimized to system tray on Windows click on notifications do nothing again.**
But if application is maximized - all now works normal - when you click on notification, then proper chat is open.

**Comment by gencer** [comment]
@ankar84 My PR reverted via https://github.com/RocketChat/Rocket.Chat.Electron/commit/36f683835aa05153a87ab2826708c1808c49bc1d

It is normal to not work as expected I believe.

**Comment by ankar84** [comment]
> @ankar84 My PR reverted via [36f6838](https://github.com/RocketChat/Rocket.Chat.Electron/commit/36f683835aa05153a87ab2826708c1808c49bc1d)
> 
> It is normal to not work as expected I believe.

I get, sorry I mentioned you.

@ggazzo please consider [my comment](https://github.com/RocketChat/Rocket.Chat.Electron/issues/2091#issuecomment-913924722)

**Comment by ggazzo** [comment]
@ankar84 @gencer Sorry guys, yeah I reverted because the event was "duplicated" we already have a another listener doing almost the same... I was planning to edit the pr but it was prematurely merged, I will re open and move the code, thanks for your comments. Btw I hope you notice some improvements since 3.5 in terms of performance, it's small but it's there 🙂

**Comment by ggazzo** [comment]
@ankar84 @gencer could you try the 3.5.1?

**Comment by ankar84** [comment]
Than issue finally fixed in https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.5.2 via https://github.com/RocketChat/Rocket.Chat.Electron/pull/2154

**Comment by ankar84** [comment]
I'm on 3.5.3 now and I'm 100% sure there is some circumstances where click on notification again do nothing.

**Comment by Mystikal57** [comment]
hi,

Notifications still not work on 3.7
