### ISSUE TITLE
Windows Client 3.2.0 and later: Jitsi does not start if the client certificate selection window appears

### ISSUE THREAD

**Issue by sandreddu** [RocketChat/Rocket.Chat.Electron#2095]
My Setup

 -   Operating System: Windows 10

-    App Version: 3.2.0 and later

 -   Installation type: exe

- [x]  I have tested with the latest version

- [x] I can simulate the issue easily

Description

Client 3.2.0 and later on ALL MS WINDOWS CLIENTS
Self hosted jitsi server, client certificate authentication
- If you have more than 1 client certificate installed, a selection window appear (see screenshot)
If you select the correct certificate, nothing happens. Logs on jitsi server show no connection attempt
On the browser it works ok.
- If you have ONLY ONE client certificate installed, the call starts and opens a new window. 

Current Behavior

The certificate selection window opens, then select the correct certificate, then nothing happens.

Expected Behavior

After the correct certificate is selected, Jitsi opens in new window
Ideally, if you select a wrong certificate, it should show an error, but we can live without that.

![image](https://user-images.githubusercontent.com/47738900/131631906-9e1ce632-fd67-4210-a072-46df7c4fd2c3.png)

**Comment by sandreddu** [comment]
Is there any news on this bug? The last working Windows client version for us is still the 3.1.1.
The browser works correctly, therefore this is a Windows client issue

**Comment by sandreddu** [comment]
After more testing with client version 3.4.0, we found out that the error is caused by the client certificate selection window. This works fine in a browser, so it's probably just a minor fix. Could you check? 
I also edited the description of the issue to reflect the actual state.
In our organization we use client certificate authentication with sometimes more than one certificate, so it would be great if this could be fixed. At the moment we cannot upgrade rocketchat for many users....
Thanks!

**Comment by sandreddu** [comment]
Problem still present in release 3.5.0

**Comment by sandreddu** [comment]
release 3.5.1 same problem
release 3.5.2 the video call button does not work anymore, all it does is send me to a private channel (???)

**Comment by ggazzo** [comment]
I was planning to fix this issue properly, but at same time providing a setting that allow us to choose if we want the jitsi on a new browser or not. I cannot promise you that I will do this today, but soon as possible ;)

**Comment by emikolajczak** [comment]
> I was planning to fix this issue properly, but at same time providing a setting that allow us to choose if we want the jitsi on a new browser or not. I cannot promise you that I will do this today, but soon as possible ;)

Hi, sounds like a nice feature. It will be setting per user or server global?

**Comment by ggazzo** [comment]
per user
