### ISSUE TITLE
memory leak when switching chats

### ISSUE THREAD

**Issue by budakovda** [RocketChat/Rocket.Chat.Electron#2097]
## My Setup
- Operating System: Windows 10, 10.0.17763
- App Version: 3.0.7
- Installation type:  exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
memory usage when starting the application for the first time
![Screenshot from 2021-07-14 12-31-50](https://user-images.githubusercontent.com/87418911/125601422-f5e50651-745e-45c1-8d6f-320d4c634058.png)
scroll back chat
![Screenshot from 2021-07-14 12-32-09](https://user-images.githubusercontent.com/87418911/125601591-0f468320-6174-436b-ac6b-73f0436dc7a8.png)
Switching to the same untwisted chat
![Screenshot from 2021-07-14 12-32-19](https://user-images.githubusercontent.com/87418911/125601817-8eaca5b1-8578-4f29-8ed9-88c044d36b91.png)
After switching to the same untwisted chat
![Screenshot from 2021-07-14 12-32-26](https://user-images.githubusercontent.com/87418911/125601923-5b7f7679-4b45-4c37-bf8b-8a62e6f79766.png)
after several switches
![Screenshot from 2021-07-14 13-13-24](https://user-images.githubusercontent.com/87418911/125605519-14585582-0862-40fc-99ba-b8f6a6b95e60.png)

### Current Behavior
Increased memory usage when switching to a previously opened chat.

### Expected Behavior
Optimal memory usage. Message history should be cached, or memory cleared for old scrolling.

**Comment by ankar84** [comment]
Start Rocket.Chat in Chrome
![image](https://user-images.githubusercontent.com/4023037/126258631-c0cf2842-c621-446f-ba11-4bccd41845b0.png)
Scroll chat A history back for a half year
![image](https://user-images.githubusercontent.com/4023037/126258864-44073799-b0d7-4b3c-ba43-9ae6d2723557.png)
Switch to chat B
![image](https://user-images.githubusercontent.com/4023037/126258911-752f6b14-40b2-4d11-a336-ad35a908692e.png)
Switch back to chat A
![image](https://user-images.githubusercontent.com/4023037/126258947-a633ba94-d523-45ca-ac19-e9432337204e.png)
![image](https://user-images.githubusercontent.com/4023037/126258988-feee3521-ec43-4fcc-83d9-dec26bf88ccf.png)
Switch between chat A and chat B about 10 times
![image](https://user-images.githubusercontent.com/4023037/126259085-b9245a21-24f5-4fd9-afbd-f08421ba322c.png)
![image](https://user-images.githubusercontent.com/4023037/126259166-28187f2e-de1a-45cb-8100-1b4b5048a365.png)
![image](https://user-images.githubusercontent.com/4023037/126259206-cf41c012-df24-45c5-b5e4-25c632c45233.png)

When you switch between chats - Chrome freezes for a while (CPU peaks in that moment). And if you don't wait until that load get low, it seems that in that case RAM consuming even more and faster.

So, that memory leak issue is reproducible at Chrome (Web client of Rocket.Chat), that means that it's not only Electron client problem, it's all Rocket.Chat handling cache problem. That thing must be improved.

@johncrisp how can we transfer that issue to main repo?
I can make another issue there and connect that issue as a related.

**Comment by ankar84** [comment]
Related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/2098

**Comment by VimLeSai** [comment]
![image](https://user-images.githubusercontent.com/27373883/126587040-b4f3684a-d1ba-4756-86ce-54ad0babc0d5.png)
I'm using mac os with m1 chip and it is using this much memory which is not good.

**Comment by ggazzo** [comment]
@VimLeSai which version of rocket.chat are you? (server)

**Comment by VimLeSai** [comment]
> ![image](https://user-images.githubusercontent.com/27373883/126587040-b4f3684a-d1ba-4756-86ce-54ad0babc0d5.png)
> I'm using mac os with m1 chip and it is using this much memory which is not good.
> 
> Rocket Chat: 3.2.3
> MacBook Pro (13-inch, M1, 2020)
> Version: 12.0 Beta

This Version

**Comment by ggazzo** [comment]
> > ![image](https://user-images.githubusercontent.com/27373883/126587040-b4f3684a-d1ba-4756-86ce-54ad0babc0d5.png)
> > I'm using mac os with m1 chip and it is using this much memory which is not good.
> > Rocket Chat: 3.2.3
> > MacBook Pro (13-inch, M1, 2020)
> > Version: 12.0 Beta
> 
> @ggazzo This Version

I believe 3.2.3 is the Desktop version (client). I'm wondering which version you use on the server side, you can check accessing `https://your.url/api/info` nowadays the latest server 
version is 3.18.x

**Comment by emikolajczak** [comment]
For sure it is an issue in 3.16.3 server version. And as @ankar84 said is affecting not only desktop client.

**Comment by ggazzo** [comment]
Closing this issue, I'm 100% confident we already have an issue talking about this on the webclient (and assigned to me =/ ) I'm almost done with

**Comment by ankar84** [comment]
> I'm almost done with

Sounds good!

**Comment by emikolajczak** [comment]
Hi,
I have tested on latest 3.5.4 with potential fix https://github.com/RocketChat/Rocket.Chat.Electron/pull/2168 but memeory leaks still there.

![image](https://user-images.githubusercontent.com/50440047/133556154-cc35f408-e631-44d2-b6ff-3bb1fa6ddaef.png)

You can replicate this issue very easy, by navigating dynamically between number of channels.

**Comment by ankar84** [comment]
> Hi,
> I have tested on latest 3.5.4 with potential fix #2168 but memory leaks still there.
> 
> ![image](https://user-images.githubusercontent.com/50440047/133556154-cc35f408-e631-44d2-b6ff-3bb1fa6ddaef.png)
> 
> You can replicate this issue very easy, by navigating dynamically between number of channels.

Confirm that!
![image](https://user-images.githubusercontent.com/4023037/133561677-4a81878a-1e9c-4c0e-8ce9-1107a4b69744.png)


> I'm 100% confident we already have an issue talking about this on the webclient (and assigned to me =/ ) I'm almost done with

I guess we need to wait a fix on webclient
