### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by andrehmuller** [RocketChat/Rocket.Chat.Electron#2098]
## My Setup

- Operating System: Windows 10
- App Version: 3.2.3
- Installation type:  exe
- Server Version: 3.15.0
- Apps Engine: 1.26.0
- Node Version: 12.22.1
- MongoDB: 3.6.14

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
We observed that when changing channels with a high frequency the memory consumption is very high. I have about 300 active users and 50 users with intense chat usage. And it is precisely these users who have a heavy use and switch channels frequently, that I have a problem of high memory consumption. There are some computers that use up to 3GB.
![image](https://user-images.githubusercontent.com/87498533/125941768-45fb452e-6456-4961-8e28-dbe639337a35.png)

![image](https://user-images.githubusercontent.com/87498533/125942216-db5df358-e2c0-4d9d-8426-74c722e8c62f.png)

### Current Behavior
RAM usage is to high.

### Expected Behavior
RAM usage should be reduced.

**Comment by nokaoii** [comment]
Same issue here. Using roughly 2 to 3gb of RAM.

**Comment by marcsoler** [comment]
Same here... also a very high CPU & GPU while the app is just "ideling" there...
![image](https://user-images.githubusercontent.com/1502124/127336448-6ce22e7b-76b2-4232-9d68-35869a4c830e.png)

**Comment by OliverMD15** [comment]
![image](https://user-images.githubusercontent.com/81589421/130309889-06c6c42a-c8c0-4eff-a3e1-87397177bcbd.png)
Same here, RAM usage can spike by quite a bit to say the least. Should note that I only have ONE server, with two channels.

**Comment by Nono-m0le** [comment]
I'm experiencing the same with: 

OS: Windows 10 x64
Server version (snap): 3.17.2
Rocket.Chat.Electron (Desktop): 3.4.0

**Comment by laxxie** [comment]
Yeah i experience the same and it's really annoying. The memory consumptions is getting higher an dhigher until you close/start the app again. At the beginning it consumes just about 200MB and after a while it's about 3GB and more

OS: MacOS 11.15.1
Server version: 3.17.0
Rocket.Chat.Electron: 3.4.0

**Comment by Nono-m0le** [comment]
Hi @ankar84 do you have any ETA or lead time for a fix for that ?
It's really annoying and time consuming everyday and I'm wondering how critical this issue is classified. I've seen already 3 new clients version (hoping that the issue lies in the client side) and still no fix yet ?

**Comment by titrier** [comment]
Unfortunately, we stopped using Rocket chat, the internal pressure in the company was too great, due to the high memory consumption.

**Comment by emikolajczak** [comment]
Is still exists in 3.5.4 with potential fix https://github.com/RocketChat/Rocket.Chat.Electron/pull/2168

**Comment by Nono-m0le** [comment]
fix seems to work at my end, at least it's far better than before. Thanks
