### ISSUE TITLE
Windows 8 Issue ! Menu (Window -> Bring All to Front) and (About Rocket.chat)

### ISSUE THREAD

**Issue by Abdelhamidhenni** [RocketChat/Rocket.Chat.Electron#21]
![zgk8q73fqkhivdtjc](https://cloud.githubusercontent.com/assets/6000419/9250774/de257228-41cf-11e5-9730-5d7372786409.png)
I have a Javascript Error whene send menu to action.
On.Click Menu
{
 Window -> Bring All to Front and 
Rocket.Chat -> About Rocket.chat)
}

**Comment by sampaiodiego** [comment]
I removed all menus throwing errors on windows and linux for now.

**Comment by sampaiodiego** [comment]
duplicated of #9
