### ISSUE TITLE
Empty lines disappear

### ISSUE THREAD

**Issue by LenryNmQ** [RocketChat/Rocket.Chat.Electron#2101]
## My Setup

- Operating System: Arch Linux
- App Version: 3.2.3
- Installation type: package manager (from AUR)

- [X] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Empty lines don't appear. They are there in code blocks, and also there in the editor box, if I edit the message, but does not render in the message window. It also happens on Windows, on macOS and in the webclient, but works perfectly on Android.

![Screenshot_20210720_142413](https://user-images.githubusercontent.com/26275827/126323312-1b22be2c-39cd-495d-9987-9cdb9f208da6.png)

### Current Behavior
Shift+Enter produce a CR/LF in the editor box, but it disappears from the message

### Expected Behavior
Shift+Enter produce a CR/LF and in the message there should be an empty line

**Comment by ankar84** [comment]
I believe it's a new parser behavior.
So, that issue related to https://github.com/RocketChat/Rocket.Chat/issues/22280
It's not duplicate, it's additional information about new parser problems.
