### ISSUE TITLE
After calling via Rocket chat, sometimes I get reminders to connect to the call

### ISSUE THREAD

**Issue by volamy** [RocketChat/Rocket.Chat.Electron#2106]
## My Setup

- Operating System: Windows 10 Pro
- App Version: Rocket.chat 3.1.1 and Rocket.chat 3.2.3
- Installation type: exe

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

![Screenshot_30](https://user-images.githubusercontent.com/88184213/127622819-75a32abc-a8d1-44c2-a5a5-0dcfecb1ac5d.png)

### Current Behavior

After calling via Rocket chat, sometimes I get reminders to connect to the call

### Expected Behavior

Nothing. The starting call with other user.

**Comment by ankar84** [comment]
Это исправлено в сервере начиная, кажется, с версии 3.16.0
Рекомендую обновить сервер до текущей актуальной 3.16.4, там уже очень многое исправлено.

**Comment by ggazzo** [comment]
Confident we fixed that on the server side, thanks
