### ISSUE TITLE
During a call in a room, if you go to another room, then the call ends

### ISSUE THREAD

**Issue by volamy** [RocketChat/Rocket.Chat.Electron#2107]
## My Setup

- Operating System: Windows 10 Pro
- App Version: Rocket.chat 3.1.1 and Rocket.chat 3.2.3
- Installation type: exe

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

### Current Behavior
During a call in a room, if you go to another room, then the call ends

### Expected Behavior
The starting call with other user.

**Comment by ankar84** [comment]
Hello, @volamy 
Can you test that issue on latest 3.5.3 release?

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
