### ISSUE TITLE
Problem with screen sharing during a call

### ISSUE THREAD

**Issue by volamy** [RocketChat/Rocket.Chat.Electron#2108]
## My Setup

- Operating System: Windows 10 Pro
- App Version: Rocket.chat 3.1.1 and Rocket.chat 3.2.3
- Installation type: exe

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
![Screenshot_34](https://user-images.githubusercontent.com/88184213/127629266-4d390f87-6493-4d31-86b8-548155dde9ed.jpg)

1.there is a call between two users
2.the first user shows their screen
3.the second user looks in full screen mode
4.the call ends
5.the second user sees a blank screen in all rooms

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
