### ISSUE TITLE
No desktop notifications on Win7

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat.Electron#211]
## My Setup

- **Win7 x64**: 
- **1.3.1**: 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

Desktop notifications are not shown on Win7
#### Current Behavior

In case of new messages or mentions no desktop notification gets shown. Only the taskbar icon is blinking in case of mentions.
#### Expected Behavior

The app should display a desktop notification upon new messages. Ideally they should look like the browser notifications of Chrome.
##

**Comment by blaf78** [comment]
Same problem here (any notification) !
Same version (1.3.1)!
But I use Windows 10 and Windows 8.1 on my workstations.
Infos: 
- The sound is played on all notification
- On a channel notification (all message notification activated), nothing on screen 
- On a private message notification, The app's icon blink but I don't see a notification with the message like I have with Chrome's extention

**Comment by engelgabriel** [comment]
This have been fixed on version 2.2.0
