### ISSUE TITLE
window not rendered with wayland and nvidia under kde plasma

### ISSUE THREAD

**Issue by infra-monkey** [RocketChat/Rocket.Chat.Electron#2112]
## My Setup

- Operating System: Linux Fedora 34 (KDE Plasma 5.22.4)
- App Version: 3.2.3
- Installation type: flatpak
- Desktop Environment: KDE Plasma 5.22.4 with wayland
- Graphics: NVIDIA GTX1060 with proprietary drivers 470 from rpmfusion

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

My issue occures only with the combination of wayland and the proprietary nvidia drivers. I have another computer with an intel gpu (with same software configuration) and it doesn't show the issue.
When I launch the desktop client, the content of the application is not rendered (just a big black emptiness inside the frame of the window).
If I run the client with the '--disable-gpu' option, the content is rendered. 

### Current Behavior

Window content is not rendered when hardware acceleration is enabled.
I suspect that the version of electron doesn't support nvidia wayland accel. 
It would be nice to confirm this assumption, and upgrade electron version. Other apps with eletron 10 at least work properly.

### Expected Behavior

The content should be rendered even with hardware acceleration.

**Comment by infra-monkey** [comment]
Probably due to https://bugs.kde.org/show_bug.cgi?id=440852
This bug is fixed in plasma 5.22.4, waiting for the update to come and confirm it's fixed

**Comment by jeanfbrito** [comment]
@infra-monkey any news about it?

**Comment by infra-monkey** [comment]
@jeanfbrito I have switched to an amd gpu now so I don't have the issue anymore. If I remember correctly, this was still not fixed with plasma 5.23.5

**Comment by jeanfbrito** [comment]
Maybe now this would work with the newest versions of Electron.
