### ISSUE TITLE
Javascript Error on Windows App Resize

### ISSUE THREAD

**Issue by Zaicon** [RocketChat/Rocket.Chat.Electron#212]
## My Setup

Windows 10
App v. 1.3.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

Any time I move the window in _any_ way, the attached screenshot error pops up. This includes dragging the window, minimizing the window, using the Windows key (Windows + direction), making the window full-sized (or the opposite), or anything else that results in the window moving in any way.

The error doesn't show up when closing the app (to the background/tray), but it does show up when exiting the app (both when the app is active and quitting from the tray icon).

http://i.imgur.com/68r40ZH.png
##

**Comment by jslay88** [comment]
Having the same issues.

We were about to replace Skype for Business with Rocket.Chat, but this has definitely put a hold on that process.

**Comment by wimpers** [comment]
Same issue here alas

Windows 10
App v. 1.3.1

**Comment by reffu42** [comment]
Same issue here, also occurs on a co-workers machine.

Windows  7

App v 1.3.1


![image](https://cloud.githubusercontent.com/assets/1823982/18747907/b9d7ae3c-809d-11e6-93ae-e0da3fdb6877.png)

**Comment by jslay88** [comment]
We have switched over to Mattermost. Much more reliable and production ready. Can't wait 30 days for a response.

**Comment by MMarowiecki** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/issues/187

**Comment by jslay88** [comment]
Definitely do not.

**Comment by stickboy06** [comment]
Is there any update to this?  I'm getting reports of this happening on machines running Windows this week.

**Comment by engelgabriel** [comment]
Guys, can you please try again with the version `2.2.0`?

**Comment by engelgabriel** [comment]
Dub of https://github.com/RocketChat/Rocket.Chat.Electron/issues/181
