### ISSUE TITLE
Change font locally

### ISSUE THREAD

**Issue by AliBayatMokhtari** [RocketChat/Rocket.Chat.Electron#2123]
## My Setup

- Operating System: Os x
- App Version: 3.2.3
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
How can i change the font locally?
Fonts are reserved from company server but i wanna overwrite them locally and use my custom font.

**Comment by ankar84** [comment]
You can try to do what you need in **Admin UI - Layout - Custom CSS** where you can redefine font settings.

**Comment by 73** [comment]
> You can try to do what you need in **Admin UI - Layout - Custom CSS** where you can redefine font settings.

But that is not locally, is it?

**Comment by ankar84** [comment]
> But that is not locally, is it?

It's totally locally in meaning that you make no changes to RC server code nor RC.Electron client code.
It's server wide, yes. But it's now all globe wide.

**Comment by 73** [comment]
I would be interested in a way to make this change in the client only.

**Comment by AliBayatMokhtari** [comment]
> You can try to do what you need in **Admin UI - Layout - Custom CSS** where you can redefine font settings.

I think it is not locally. I have no permission to Admin UI. I just wanna change it in my machine.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
