### ISSUE TITLE
Only source code assets available for 3.2.4

### ISSUE THREAD

**Issue by Forage** [RocketChat/Rocket.Chat.Electron#2126]
I'd love to take the 3.2.4 for a spin to see if the notification issues have been resolved on Linux, but the only two assets to download available are source files instead of e.g. a deb file.
Did @ggazzo miss a step during publication?

**Comment by ankar84** [comment]
All assets in place 
![image](https://user-images.githubusercontent.com/4023037/132302464-2c7cb23b-5d2d-4160-9727-1477712ac5dd.png)
