### ISSUE TITLE
Option to allow client window to be shown when new message is recived while hidden

### ISSUE THREAD

**Issue by SQUIDwarrior** [RocketChat/Rocket.Chat.Electron#213]
## My Setup

- **Windows 7 64-bit**: 
- **Version 1.3.1**: 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

Add the option to allow the client window to be shown when new messages are received and the client is hidden.
#### Current Behavior

Right now when a new direct message or mentioned is received and the client is hidden, the client window does not appear. All that happens is that a sound is played (if enabled) and the tray icon changes color. 
#### Expected Behavior

The problem is that someone that has the client completely hidden so the task bar icon is gone, there isn't any way to get the user's attention that they have a message. There should be an option that allows the user to have the client window appear when a new message is received. Ideally this could be set for any channel or group, as well as for mentions and direct messages. 
##

**Comment by chrism113** [comment]
This is still an issue for our users:  

- App is hidden in the tray, user is away from desk
- Desktop notification comes and goes
- Windows auto hides the rocket.chat icon in the system tray

When they return to their desk, they have no idea they missed a message.  It would be great to have the option that the app exits from being hidden and appears minimized and flashing.

**Comment by engelgabriel** [comment]
can you please test https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.12.1 ?

**Comment by helderam** [comment]
I need this too
