### ISSUE TITLE
Submenu(s) missing in Electron client (vs. web browser client)

### ISSUE THREAD

**Issue by didierm** [RocketChat/Rocket.Chat.Electron#2131]
**Describe the bug**
The `> Administration > Settings > Message` submenu is missing in the Electron client.
(other submenus might be absent too.)

What operating system and which version?
Fedora 33
Which version of Rocket.Chat (Server)?
3.17.1
Which version of Rocket.Chat.Electron (Electron/Desktop)?
3.2.3
Is there any setting relevant changed?

**To Reproduce**
1. Go to 'Administration'
2. Click on 'Settings'
3. Scroll down to '... - Logs - Meta - Mobile - ....'
4. See error : submenu `Message` is missing

**Expected behavior**
The `Message` submenu should be present

**Screenshot 1 : Electron client (v3.2.3)**

![Selection_167](https://user-images.githubusercontent.com/989004/131216526-8eac0da4-1cf1-4719-9d7c-1757c0861769.png)

**Screenshot 2 : Web browser client (Firefox v91)**

![Selection_168](https://user-images.githubusercontent.com/989004/131216535-c6f6e550-445c-414d-8243-8b9ee7bb0a5a.png)

**Comment by ankar84** [comment]
Can you check that issue on latest 3.5.3 version?
I see that menu in my side
![image](https://user-images.githubusercontent.com/4023037/132816524-121ac6a1-1351-493a-b930-7c4b30ed7c4b.png)

**Comment by didierm** [comment]
@ankar84 Checked in v3.5.3, "Message" submenu is now available.
Thanks !
