### ISSUE TITLE
Version 3.5.1 still crashes when one tries to record an audio message (MacOS)

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat.Electron#2132]
**Describe the bug**
When trying to record an audio message the app immediately crashes. Same goes for video conference when configured to use jitsi.

What operating system and which version? MacOS (Big Sur)
Which version of Rocket.Chat (Server)? 3.17.1
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.5.1
Is there any setting relevant changed? No.

**To Reproduce**
1. Go to Messages Window 
2. Click on Audio Record Icon
3. App Crashes

**Expected behavior**
Recording an audio message works.

cheers! t.

**Comment by yuyao110120** [comment]
Me too! Same system and version, also video call crash too.

**Comment by himpierre** [comment]
Adjusted Issue. Bug still present with version 3.5.1.

**Comment by Apfelpom** [comment]
Also with 3.5.2. The problem seems to be related to missing macOS security entitlements for audio (and video too), like here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1912#issuecomment-877281039

**Comment by himpierre** [comment]
@ggazzo @tassoevan are you guys aware of this bug? It's broken since ages now. :)
