### ISSUE TITLE
File upload dialog not rendering characters on snap

### ISSUE THREAD

**Issue by o100ja** [RocketChat/Rocket.Chat.Electron#2140]
When trying to choose a file from the local computer to upload on a chat the rendered dialog displays some invalid encoding:
![image](https://user-images.githubusercontent.com/1793873/131662905-b5ef0f9a-1225-466f-bbfa-cf59f533ae13.png)

** To Reproduce ** 
![image](https://user-images.githubusercontent.com/1793873/131662811-ce2df1d8-a369-44f9-b503-0c0fae8947ac.png)

** Environment **
Rocket.Chat.Electron: 3.2.2
snap: 2.51-1.58
snapd: 2.51-1.58
series: 16
os: opensuse-tumbleweed  20210830
kernel: 5.13.13-1-default

**Comment by raffaelone** [comment]
Same problem with the version 3.8.1

![file-manager-ubuntu](https://user-images.githubusercontent.com/73063127/162419617-c531f911-07d4-4ab6-b02d-d787e595bbcf.png)


**Server Setup Information:**
Version of Rocket.Chat Server: 4.5.5
Operating System: Ubuntu 20.04.4 LTS
Deployment Method: snap

**Client Setup Information**
Desktop App or Browser Version: 3.8.1 from snap
Operating System: Ubuntu 20.04.4 LTS

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
