### ISSUE TITLE
Improve context menu

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#215]
Originally posted by: @pdfforge on https://github.com/RocketChat/Rocket.Chat/issues/3622

The context menu for conversations in RocketChat+ / Desktop client is not particularly useful. Among other things, it has Cut, Copy and Paste when no selection is done after clicking into the history. Cut and Paste never makes sense here, even is something is selected. The copy does work, but when right-clicking a link, it should offer "Copy link address" as well, as it is done by browsers. Right now, the Copy button does not copy anything, when nothing is selected.
##

**Comment by akashnimare** [comment]
Is there any bounty on this issue? I would love to solve this issue.

**Comment by geekgonecrazy** [comment]
@akashnimare currently no doesn't appear to be.
