### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by Mte90** [RocketChat/Rocket.Chat.Electron#216]
Replace the readme with information about how to install, actually contain information about the boilerplate and how to edit.
##

**Comment by Syirrus** [comment]
I second that!

**Comment by jszaszvari** [comment]
It's not their responsibility to teach you how to code. The app is in the standard Electron format/layout and the code is well enough written to be able to step your self through any modifications that you need to make.

**Comment by Syirrus** [comment]
@jszaszvari The title of this thread is "Install Instructions" NOT "Teach me How to code".

**Comment by jszaszvari** [comment]
> @jszaszvari The title of this thread is "Install Instructions" NOT "Teach me How to code".

Seems pretty comprehensive to me

Quick Start-
git clone https://github.com/szwacz/electron-boilerplate.git
cd electron-boilerplate
npm install
npm start

Also, 

Project Structure, Whats in each folder. How to install the Electron runtime, Starting the actual application, Adding Modules, Unit testing, Making a release...

Not sure what else you need. 

I've never done anything with this framework before, and 2 hours later I've go a modified version with the changes I wanted ready to deploy at the company I work for.  Really confused as to where its lacking in instructions.

**Comment by Mte90** [comment]
We are not talking about the electron boilerplate but about this app for rocket chat

**Comment by jszaszvari** [comment]
Go ask in the IRC channel then, Or take the 10 mins to read through the code to understand what it's doing. 

It's written well enough to be able to work out what you need to do.

**Comment by Mte90** [comment]
So every users of rocket chat that have to read the code only to understand how to install that app means that no one can install the app.

I know how to install but I installed rocket chat for my community where they have no knowledge about rocket chat, and I have to say to them "read the code of the app to understand install it"? They will abandon super fast my platform.

We need only a step by step process for the various systems like do the other platform slack inspired.

**Comment by jszaszvari** [comment]
Then what are you doing in the code repository for one of their many desktop clients if you are just looking to understand how to install the app. ?

They have documentation for TONS of platforms in their docs repository here -  https://github.com/RocketChat/Rocket.Chat.Docs/


How about the Main Project at https://github.com/RocketChat/RocketChat ?

**Comment by Mte90** [comment]
I refer to the desktop app that is in this repo

**Comment by jszaszvari** [comment]
Here you go -
https://github.com/RocketChat/Rocket.Chat.Docs/tree/master/4.%20User%20Guides
