### ISSUE TITLE
unable to upload viso or xmind file

### ISSUE THREAD

**Issue by ntvis** [RocketChat/Rocket.Chat.Electron#2161]
Description:

Unable to upload xmind files and viso files.
Steps to reproduce:

    Click and drag a xxx.xmind or xxxx.vsdx file from explorer window to Rocket chat window
    Rocket chat gives "Media Type Not Accepted: undefined" .

Expected behavior:

Dropping a file uploads it to the chat

Actual behavior:

throw error and file not upload.

Server Setup Information:

    Version of Rocket.Chat Server:3.18.1
    Operating System: ubuntu 18.04
    Deployment Method: Client executable
    Number of Running Instances: 1
    DB Replicaset Oplog:
    NodeJS Version: v12.22.1
    MongoDB Version: 4.0.26 / mmapv1 (oplog enabled)

    FileUpload_Enabled: true
    MediaTypeWhiteList: left blank
    MediaTypeBlackList: left blank
     

Client Setup Information

    Desktop App or Browser Version: Desktop 3.5.0
    Operating System: Windows 10 Home

**Comment by cazetto** [comment]
@ntvis did you managed to test it on the web application?

The message "Media Type Not Accepted" probably do not comes from the code in this repository. I am confirming it.

Maybe it is a Rocket.Chat enhancement task.

**Comment by cazetto** [comment]
Yep, confirming that it's on Rocket.Chat. Please, reopen it here: https://github.com/RocketChat/Rocket.Chat
