### ISSUE TITLE
[bug] Jitsi call start in default browser but not in separate windows as it was before

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#2162]
**Describe the bug**
Jitsi call start in default browser but not in separate windows as it was before

What operating system and which version?
Windows 10 1909
Which version of Rocket.Chat (Server)?
3.16.3
Which version of Rocket.Chat.Electron (Electron/Desktop)?
3.5.3
Is there any setting relevant changed?
No.

**To Reproduce**
1. Someone start Jitsi call in chat
2. Click on `Click to Join!` button
3. New tab in default browser is open

**Expected behavior**
New windows in desktop client should open after user click on `Click to Join!` button

**Screenshots**
N/A

**Additional context**
That problem introduced in 3.5.3, because 3.5.2 works correct.
Probably in https://github.com/RocketChat/Rocket.Chat.Electron/commit/4030e34561c6c88d4825106869cea649cfe42c44

**Comment by kundulun** [comment]
macOS,  the same problem with 3.5.3 version (server 3.18.1)

**Comment by tmartincpp** [comment]
Same here.

**Comment by cazetto** [comment]
Yep, I can confirm it on Windows 10. I'll take a look at this.

**Comment by iMiKED** [comment]
Same on Win10 x64 21H1, Rocket Chat 3.5.3, Server 3.16.3.
Waiting for fixes.

**Comment by chrisi51** [comment]
additionally the workarround to close the jitsi window on hangup is not working anymore.

on many mac os systems safari is the standard browser which is one of the least supported browsers of jitsi so this is really a no go.

**Comment by ankar84** [comment]
> on many mac os systems safari is the standard browser which is one of the least supported browsers of jitsi so this is really a no go.

Actually that was true in past, now both Safari and FireFox are considered by Jitsi as supported.

**Comment by tom666-debug** [comment]
Still the same behavior with the new client 3.5.4. RC in combination with Jitsi is really a sad story .... :/

**Comment by ankar84** [comment]
> Still the same behavior with the new client 3.5.4. RC in combination with Jitsi is really a sad story .... :/

Yeap, confirm that 3.5.4 still have that bug.
Look like team a still working on a fix for that.

**Comment by iMiKED** [comment]
Yepp, sadly, 3.5.4 is also affected( Looking forward for fix.

**Comment by Kirill** [comment]
I'm not sure that it's bug, but in 3.4.8 and early when I press join, I see new window in Rocket.Chat with caller, but now when I press join I go to browser for speak to caller.

**Comment by tmartincpp** [comment]
Still an issue with 3.5.5.

**Comment by ankar84** [comment]
@debdutdeb hey!
Can you speak to Prod team to prioritizes that issue, because it's a critical one for a lots of users including me?

**Comment by iMiKED** [comment]
macOS 11.6, RocketChat 3.5.6 force closes when trying to call user - right after Jitsi Meet window appears.
Logs attached.
[rocket_356_fc.txt](https://github.com/RocketChat/Rocket.Chat.Electron/files/7220479/rocket_356_fc.txt)
Please, reopen issue.

**Comment by chrisi51** [comment]
@iMiKED do you have M1 macbook?

**Comment by ankar84** [comment]
> macOS 11.6, RocketChat 3.5.6 force closes when trying to call user - right after Jitsi Meet window appears.
> Logs attached.
> [rocket_356_fc.txt](https://github.com/RocketChat/Rocket.Chat.Electron/files/7220479/rocket_356_fc.txt)
> Please, reopen issue.
> @ankar84 FYI.

Wow, I don't see this on Windows machine.
Ok. I reopen that issue because of behavior on macOS

**Comment by ankar84** [comment]
> macOS 11.6, RocketChat 3.5.6 force closes when trying to call user - right after Jitsi Meet window appears.
> Logs attached.
> [rocket_356_fc.txt](https://github.com/RocketChat/Rocket.Chat.Electron/files/7220479/rocket_356_fc.txt)
> Please, reopen issue.
> @ankar84 FYI.

@iMiKED I just think twice and closing my issue, because actually my issue is fixed and that fix is working correctly on my side (Windows 10)
I'm sure you should make separate issue with your details (maybe it's not a Jitsi issue, but new window issue etc.)

**Comment by SimonSchwendele** [comment]
Reappearing with 3.6.0 :(

**Comment by iMiKED** [comment]
> 
> 
> Reappearing with 3.6.0 :(

You should change setting "Open call in" to "Internal" - everything should be fine

**Comment by SimonSchwendele** [comment]
> > Reappearing with 3.6.0 :(
> 
> You should change setting "Open call in" to "Internal" - everything should be fine

Where is this setting ?
Apparently not in `/admin/Video Conference`

**Comment by iMiKED** [comment]
> Nevermind I found it:
Glad you found it! Take care!

**Comment by chrisi51** [comment]
sadly that is the - in my eyes bad - work arround to not get into trouble with mac os entitlement due to push it further to another app ...

this "feature" should be kinda useless now as the entitlements are handled correctly now by the electron app

**Comment by jeanfbrito** [comment]
@chrisi51 I don't think that is useless to have an option to select what to do. Now we have solved some problems with the entitlements and yet have an option to choose how it will work.

**Comment by chrisi51** [comment]
@jeanfbrito 
at least the default behavior is "wrong" as it always was opening in the app window instead of a browser window until that workarround came up to not get into entitlement problems. so why is this not enabled by default to at least behave as the default was before. 

if somebody need to change that setting, et voila, now its possible but why enforcing the "wrong" behavior? ;)

i guess, rocketchat main developers don't use macos? on a managed macos system you may not be allowed to set entitlements for new apps as you want. so you may stucked on those apps which are already entitled. if you than update your rocketchat app now and your browser have to do the job by default which may not have the entiltes given by an admin, you cant use jitsi for example anymore. just because of a setting, a normal user not even may be aware of.

**Comment by jeanfbrito** [comment]
@chrisi51 I think that I missed the migration setting to force the option to true. I just added it to an old migration.
I will add this to another version like 3.6.1 and force it to be true. If someone wants to use the workaround then it can be chosen on settings again.
Thanks for explaining this. This was a thing that I missed resolving.
And thanks for your entitlements PR, it fixed the problem.

**Comment by Kirill** [comment]
Sorry. But this not correct work. In prior version with open in new windows I have new windows of RC with call. For now I see new window with default browser. Ok. I change setting to this window and what I see?! I see call screen in right side of chat and when I change chat call lost. I can't copy/paste or see information from other chats when I call. Please, when I install OS-client, I want work with client, not browser. If I want use browser, I use browser version. Thank you.

**Comment by chrisi51** [comment]
@Kirill so u set the switch to enabled? probably restart the app
![image](https://user-images.githubusercontent.com/2156760/142508412-c08e0c41-ac8c-43c9-8c9a-4c0e224fb395.png)

**Comment by chrisi51** [comment]
@jeanfbrito dont wanted to blame you :)

if the switch is enabled by default i guess everything is fine. but you dont want to overwrite this setting on an update i guess for ppl who already set the switch on or off for any reason. 
on our site, we. try to enforce the setting with management so i hope it dont hit us hard :)

**Comment by Kirill** [comment]
Sorry for my tone in prior message.

> @Kirill so u set the switch to enabled? probably restart the app ![image](https://user-images.githubusercontent.com/2156760/142508412-c08e0c41-ac8c-43c9-8c9a-4c0e224fb395.png)

Where I can find this setting? I try found, but nothing in account settings and Server settings.
Server Version: 4.1.2
Client version: 3.6.0

**Comment by SimonSchwendele** [comment]
The Problem is reappearing again with 3.7.0, could you please look into it again ?

**Comment by iMiKED** [comment]
> The Problem is reappearing again with 3.7.0, could you please look into it again ?
As for me - everything is fine on both macOS Monterey and Win10.
![изображение](https://user-images.githubusercontent.com/1527992/145386279-82037f5a-f6e9-4ebe-8c03-6d9c403ee465.png)

**Comment by SimonSchwendele** [comment]
> > The Problem is reappearing again with 3.7.0, could you please look into it again ?
> 
> As for me - everything is fine on both macOS Monterey and Win10. ![изображение](https://user-images.githubusercontent.com/1527992/145386279-82037f5a-f6e9-4ebe-8c03-6d9c403ee465.png)

Thats strange.
The problem only appears on my wwindows pc for work.
On my  Linux I dont have this problem either...

Guess its some weird side effect, sorry for disturbing this issue
