### ISSUE TITLE
[Snap]  Released today 3.2.2 (latest/stable) doesn't launch

### ISSUE THREAD

**Issue by kaincenteno** [RocketChat/Rocket.Chat.Electron#2165]
**Describe the bug**
The application doesn't open, I had to switch to a different channel like latest/candidate or latest/edge to be able to use it again.

What operating system and which version? Ubuntu x64 21.10
Which version of Rocket.Chat (Server)? 3.17.2
Which version of Rocket.Chat.Electron (Electron/Desktop)?  Ubuntu Snap Package 3.2.2 (Released today 11SEP2021)
Is there any setting relevant changed?
update today

**To Reproduce**
open application:
```
rocketchat-desktop 
/snap/rocketchat-desktop/416/rocketchat-desktop: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
```

**Expected behavior**
The electron snap application open as usual

**Screenshots**

**Additional context**

**Comment by xmedeko** [comment]
What about Flatpack https://flathub.org/apps/details/chat.rocket.RocketChat ?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
