### ISSUE TITLE
[Discussion] Report errors to developers - default disabled

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.Electron#2169]
**Describe the bug**
I want to start discussion about new setting 'Report errors to developers'. In my opinion this option should be disabled by default or during installation should be a question if user want 'Report errors to developers'.

What operating system and which version all
Which version of Rocket.Chat (Server) all
Which version of Rocket.Chat.Electron (Electron/Desktop) 3.5.4
Is there any setting relevant changed - Settings -> Report errors to developers

**To Reproduce**
1. Install Rocket.Chat.Electron 3.5.4
2. Option 'Report errors to developers' is default enabled

**Expected behavior**
Ask user if want enable this option or make it default disabled

**Screenshots**

**Additional context**

**Comment by ankar84** [comment]
Agree with Emil.
Another good option make that setting configurable via config file to maintain big deployments.

**Comment by tmartincpp** [comment]
Related to #2099.

**Comment by klou** [comment]
@tmartincpp Is this the per-user ```config.json```, or another machine-global config file?

**Comment by tmartincpp** [comment]
@klou this is by user AFAIK, but you might have a way to make it global somehow : https://discourse.appimage.org/t/portable-configuration-data/105/6 (haven't tried it myself).

**Comment by klou** [comment]
Related to #1838.

**Comment by jeanfbrito** [comment]
We created overridden-settings that could help you to solve this. Please take a look and tell me if this resolves for you.
https://github.com/RocketChat/Rocket.Chat.Electron#overridden-settings
