### ISSUE TITLE
Registry Uninstall GUID location keeps changing

### ISSUE THREAD

**Issue by ALvanti** [RocketChat/Rocket.Chat.Electron#2171]
Why does the hive location of the MSI installer keep fluctuating?
These are from a x64bit OS installing the MSI with switches; /qn /norestart ALLUSERS="1" DISABLEAUTOUPDATES="1"

3.2.2 - wow6432node
3.2.3 - "Default" (64 bit hive)
3.2.4 - "Default" (64 bit hive)
3.4.0 - wow6432node
3.5.3 - "Default" (64 Bit hive)
3.5.4 - "Default" (64 Bit Hive)

Can we get this nailed down to be consistent from release to release? It makes it difficult to code and track updates.

**Comment by ALvanti** [comment]
3.7.0 was again in the Wow6432Node. 

Why does this keep changing?

**Comment by jeanfbrito** [comment]
I think thats a issue with Electron installer. Did you have any idea of what could we do to solve this?

**Comment by ALvanti** [comment]
Me? No not a clue. I assume somewhere on the line of the creation of the installer it is "choosing" the wrong registry. The means by which it does that *shrug*

**Comment by ALvanti** [comment]
3.7.1 changed _back... AGAIN_ to "Default" hive (64 bit hive)

Whyyyyyy

**Comment by ALvanti** [comment]
3.7.4 changed back to default hive after having been changed in 3.7.3 or 3.7.2 to "Default" hive (64 bit hive)

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
