### ISSUE TITLE
[Bug] Click on notification not always open Electron application

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#2176]
**Describe the bug**
As I mentioned here https://github.com/RocketChat/Rocket.Chat.Electron/issues/2091#issuecomment-916831144 `click notification problem` not totally fixed by https://github.com/RocketChat/Rocket.Chat.Electron/pull/2154

In some conditions click on notification again do nothing. In that case application relaunch usually helps (but again - not always).

What operating system and which version?
Windows 10 1909
Which version of Rocket.Chat (Server)?
3.18.1
Which version of Rocket.Chat.Electron (Electron/Desktop)?
3.5.5
Is there any setting relevant changed?
No

**To Reproduce**
1. Start RC.Electron client and work with it for a while
2. Click on notification that other user send to you
3. Nothing happens

**Expected behavior**
When user clicks on notification, RC.Electron applications should be open and in that current chat where notification come from

**Screenshots**
![click01](https://user-images.githubusercontent.com/4023037/132846833-e45cc86e-63ef-49ab-b5ae-05c15e666672.gif)

**Additional context**
We need a permanent and consistent fix for that.

**Comment by Mystikal57** [comment]
Hi,
Still not work on 3.6 & windows 11.

**Comment by ankar84** [comment]
I'm on 3.6.0 now and can confirm, that the issue is still here.
But actually I think I have a workaround for that issue - when click on notification doesn't work, I just **Reload client with CTRL+R** and right after that click on notification works fine.

**Comment by ankar84** [comment]
3.7.0 pre release issue is still here!

But there is a pretty [stable workaround](https://github.com/RocketChat/Rocket.Chat.Electron/issues/2176#issuecomment-976295164), just reload once Electron with CTRL+R and notifications work again.

I guess it is some problem with initial application launch, that not load some script or something like that.

**Comment by Mystikal57** [comment]
hi,

Notifications still not work on 3.7

**Comment by Mystikal57** [comment]
Seems resolved for me in 3.7.5
