### ISSUE TITLE
Clicking on images won't enlarge them anymore

### ISSUE THREAD

**Issue by matthiasbernhardt** [RocketChat/Rocket.Chat.Electron#2179]
**Describe the bug**
Someone uploads a large image, say, a screenshot. After uncollapsing and clicking to actually load it, a thumbnail gets displayed. Clicking on the image, a dark transparent overlay and an enlarged version of the image should be shown, instead the image is again the (size of the) tumbnail.

Mac OS 10.15.6 "Catalina"
Rocket.Chat Server 3.18.1
Rocket.Chat.Electron 3.4.x … 3.5.5
Possibly relevant settings:
- Auto Load Images: off
- Save Mobile Bandwidth: on
- Collapse Embedded Media by Default: on

**To Reproduce**
1. uploads a large image, say, a screenshot
2. Click on ">" to uncollapse it
3. Click on "Click to load" to load it
4. Click on the thumbnail to view the entire image as an overlay
5. See the image in the reduced size instead of the original or maximum size

**Expected behavior**
In the web view, I see a large version of the image centered over a black transparent overlay. I expect the same for the Electron client.

**Screenshots**
Sorry, I currently cannot easily make screenshots suitable for publication. I may try later, If this turns out to impede reproduction of that behaviour.

**Additional context**
I believe it was different before 3.4.x, an update to 3.5.5 did not help.

**Comment by ggazzo** [comment]
please check https://github.com/RocketChat/Rocket.Chat/issues/23252

**Comment by matthiasbernhardt** [comment]
While it sounds related to the same feature, that other report describes a different behaviour in a different client version.

My issue concerns the presumably stable client version 3.5.5 and the image _is_ displayed, just not in the right size.

**Comment by matthiasbernhardt** [comment]
Ping @ggazzo, please reconsider ^^

**Comment by matthiasbernhardt** [comment]
Ping @ggazzo

**Comment by matthiasbernhardt** [comment]
It now works again with Client 3.5.7 and Server 4.1.2, no idea which update in the meantime was relevant. I would really have appreciated a hint which release is supposed to fix the issue, at the time this issue was closed.

**Comment by matthiasbernhardt** [comment]
Meanwhile I updated to Client 3.7.5 and the Server has been updated to 4.3.1. It looks as if it has finally been fixed. I would appreciate if someone clarified which change in which component fixed the issue and introduced some regression tests.
