### ISSUE TITLE
Settings gear missing i18n for "Settings flash frame description"

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Electron#2182]
**Describe the bug**
The description for the flash frame toggle is missing.

What operating system and which version? macOS 11.4 (20F71)
Which version of Rocket.Chat (Server)? 3.18.0
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.5.6
Is there any setting relevant changed? No

**To Reproduce**
1. Hit the gear on desktop app

**Expected behavior**
A description for what the enable flash frame does

**Screenshots**

<img width="992" alt="Screen Shot 2021-09-23 at 5 41 39 PM" src="https://user-images.githubusercontent.com/6295044/134601479-4b6f0270-2ade-42ae-ab4e-e2894f958110.png">

**Comment by jeanfbrito** [comment]
Will be fixed on release 3.6.0. Closing it.
