### ISSUE TITLE
Download manager server filter duplicates server names

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Electron#2183]
**Describe the bug**
The download manager server filter isn't useful. It contains the same server name multiple times in the filter. 

What operating system and which version? macOS 11.4 (20F71)
Which version of Rocket.Chat (Server)? 3.18.0
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.5.6
Is there any setting relevant changed?

**To Reproduce**
1. Open download manager
2. Click on server dropdown

**Expected behavior**
Only one option per server should exist.

**Screenshots**
<img width="1406" alt="Screen Shot 2021-09-23 at 6 35 29 PM" src="https://user-images.githubusercontent.com/6295044/134605309-c453cc84-6efc-4a49-98ca-5b533ae81e78.png">

**Comment by jeanfbrito** [comment]
Hey @wreiske I think that this problem is fixed. Just tested and this doesn't happens. I will close the issue but if it persists please tell me to reopen it.
