### ISSUE TITLE
[macOS] RC 3.5.6 force closes after opening Jitsi Meet window

### ISSUE THREAD

**Issue by iMiKED** [RocketChat/Rocket.Chat.Electron#2184]
Describe the bug
RC 3.5.6 & 3.5.7 force closes after opening Jitsi Meet window

What operating system and which version?
macOS 11.6, 12.0.7 @ x86_64 machine
Which version of Rocket.Chat (Server)?
3.16.3
Which version of Rocket.Chat.Electron (Electron/Desktop)?
3.5.6 & 3.5.1
Is there any setting relevant changed?
No.

To Reproduce

Press Call button
Wait for Jitsi Meet window
Get FC

Expected behavior
No FC

Screenshots
N/A

Additional context
That problem probably introduced in 3.5.3
Maybe linked with https://github.com/RocketChat/Rocket.Chat.Electron/issues/2162
[rc_356_fc2.txt](https://github.com/RocketChat/Rocket.Chat.Electron/files/7224016/rc_356_fc2.txt)
[rocket_356_fc.txt](https://github.com/RocketChat/Rocket.Chat.Electron/files/7224017/rocket_356_fc.txt)

**Comment by ankar84** [comment]
I can confirm that issue - tested on mac 11.2.3

**Comment by himpierre** [comment]
Related to #2132

**Comment by himpierre** [comment]
How many different issues do we need for the MacOS Problem? :)

**Comment by ankar84** [comment]
Related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1912
