### ISSUE TITLE
Channel stays highlighted after all messages read

### ISSUE THREAD

**Issue by ThomasKientz** [RocketChat/Rocket.Chat.Electron#2186]
**Describe the bug**
Channels are staying highlighted even if I have read all the new messages inside. 

What operating system and which version? macOS 11.5.2
Which version of Rocket.Chat (Server)?  3.18.1
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.5.6
Is there any setting relevant changed?

**To Reproduce**
1. Receive a new message in current (or closed ?) channel 
2. Focus on the rocket window, scroll if you want inside the channel

**Expected behavior**
The channel to stop being highlighted (like before).

**Screenshots**
Highlighted channel exemple
<img width="268" alt="highlighted channel" src="https://user-images.githubusercontent.com/10157845/134864671-1545f93b-3492-470c-9a42-a6df3a132546.png">

Channel's notifications settings
<img width="1369" alt="channel notifications settings" src="https://user-images.githubusercontent.com/10157845/134864762-a012be56-4a73-43f9-9e7b-64b2baeebf84.png">

**Comment by tailcat** [comment]
A also saw this starting today on MacOS version 11.6 Rocket Chat client 3.0.3 (from app store) Server 3.12.1 was fine yesterday

**Comment by imperatom** [comment]
This is indeed very annoying. I have 3.7.0 and have experienced the issue in earlier versions, too. I'm using a windows64 desktop client. When I scroll down, or even when I click "als gelesen markieren" (mark as read) nothing changes. Somehow this does not occur with all new messages, but whith many. When I hit "answer", scroll down and everything there and back, then very sometimes things are accepted as read finally - but it takes many many tries and seems to follow no sceme.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Comment by giddel** [comment]
Same here with client 3.8.6 on Linux.
Sometimes channel is marked as read, sometimes not.
Sometimes I get the banner "Mark as read", sometimes not.

In the most cases I have to set read by the context menu at the channel. This is really annoying!
