### ISSUE TITLE
Add option to disable popup notification while application is closing to tray

### ISSUE THREAD

**Issue by ComBin** [RocketChat/Rocket.Chat.Electron#2188]
**Describe the bug**
Every day while I close Rocket.Chat to tray I see notification "Rocket.Chat is still running" and application no setting to disable this.

Windows 10 Pro 21H1 19043.1237
Rocket.Chat 3.5.3

**To Reproduce**
1. Start Rocket.Chat
2. Close Rocket.Chat
3. See notification

**Expected behavior**
Nothing noise while closing Rocket.Chat.

**Screenshots**
![image](https://user-images.githubusercontent.com/1571345/134926578-e0e66717-b99f-4df1-8805-139e78a9b1a4.png)

**Additional context**
There have already been several issue about this problem but:
1. Its about notification on every closing (and this fixed, but notification every day still annoying!).
2. No any reactions in its.

**Comment by vaDrn** [comment]
bump.
still not fixed

**Comment by MaxVRAM** [comment]
Getting this on Windows 11 too. Is there really any reason to produce a notification when closing to the tray in the first place?

If RocketChat is closed to the system tray and...

1. Someone sends you a message, it will produce a notification and you'll know it's still open.
2. You try to open RocketChat, it will open the existing RocketChat instance from the tray.

But even so, I feel like people understand the concept of minimising to the tray by now; do we even need a notification that an application is doing this?
