### ISSUE TITLE
Issue with payment and creating new workspace

### ISSUE THREAD

**Issue by postmaximis** [RocketChat/Rocket.Chat.Electron#2189]
Hello everyone,
M trying to make payment for my workspace, I can't make any payment.
As well as I thought it might be because trial version, but same also I cant create a new workspace from any other account.
Urgently I need help for my coworkers, we are going up to 100 people that gonna use the Rocket chat platform.
I would love to contact support, but since they don't answer fast, it's just a waste of time.

+i have attached photos which shows my issue

`https://ibb.co/74PtwpD`
`https://ibb.co/kyBxG6h`

Best Regards!
Maxim

**Comment by dougfabris** [comment]
@postmaximis Thanks for contacting us! I sent your issue to the responsible team on React.Chat Cloud and I suppose they will get in touch with you as soon as possible. As this issue is not related to this project I'm closing it. If you need something else please get in touch with the support team.
