### ISSUE TITLE
Add option to hide server selector

### ISSUE THREAD

**Issue by dbushong** [RocketChat/Rocket.Chat.Electron#219]
## My Setup
 - __My OS name and version__: macOS 10.11.3 El Capitan
 - __My current app version__: 1.3.1 (15)

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

A large check of the left side of the client is dedicated to selecting between multiple servers.

#### Expected Behavior

When the user only has one server (even then optionally?) this column should be hidden; it's the single biggest wasted hunk of screen real-estate.  The huge "+" icon is the most prominent icon in the whole UI - and it's probably the control you'll use the *least* often.

**Comment by graywolf336** [comment]
Currently possible: Click on the `View` menu and then click `Toggle server list`. It does persist through application restarts as well.

**Comment by dbushong** [comment]
Holy crumbs; thanks!

**Comment by tassoevan** [comment]
@Jonathonbyrd You can't, yet. Many users are requesting more administrative control over user settings and this one can be included in our plans.
