### ISSUE TITLE
Exception on right click

### ISSUE THREAD

**Issue by real-or-random** [RocketChat/Rocket.Chat.Electron#2194]
**Describe the bug**
When I right-click, an error message appears. No context menu appears.

What operating system and which version? Arch Liux
Which version of Rocket.Chat (Server)? (How do I find out?)
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.5.6 using https://aur.archlinux.org/packages/rocketchat-desktop/
Is there any setting relevant changed? No, at least not locally. I updated to 3.5.6 a week ago but the bug only appeared today

**To Reproduce**
1. Right-click anywhere in the page

**Expected behavior**
Context menu

**Screenshots**
![image](https://user-images.githubusercontent.com/1071625/135903185-6396ab36-0a45-45d0-935f-268c909cb427.png)

**Additional context**

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
