### ISSUE TITLE
How to access my local rocket.chat instance?

### ISSUE THREAD

**Issue by medvednikov** [RocketChat/Rocket.Chat.Electron#22]
Currently I can only use http://rocket.chat

How do I access http://chat.myserver.com in the app?

Thanks

**Comment by rodrigok** [comment]
Hei @medvednikov, you need to change this line to your url:
https://github.com/RocketChat/Rocket.Chat.Electron/blob/master/app%2Fmain.js#L14

**Comment by sampaiodiego** [comment]
you can do it now with the code in master ( #27 )
