### ISSUE TITLE
Useless footer div?

### ISSUE THREAD

**Issue by Morgy93** [RocketChat/Rocket.Chat.Electron#220]
Hello,

is there any meaning to the footer div below the room list?
Else one could just remove this and expand the room list to have more space:

![unbenannt](https://cloud.githubusercontent.com/assets/7961978/16794707/b7430528-48d9-11e6-9888-24aa2824c242.PNG)
##

**Comment by her** [comment]
The footer does take up an unreasonably large space in my opinion. I've tried doing some simple modifications of size using the administration panel but that doesn't change the actual dimensions, nor does using a 1x1 transparent image for a dimensions change so this will likely need modified in the app's styles. 

Have you found where this is ?

**Comment by Morgy93** [comment]
@her You may want to go for something like:

```
footer {
    display: none;
}
.rooms-list {
    height: 100%;
}
```

For Administration -> Settings -> Layout -> Custom CSS

**Comment by her** [comment]
@Morgy93 thanks for that snippet 

Looks like the footer still remains, though 😭

![screen shot 2016-10-04 at 7 08 33 am](https://cloud.githubusercontent.com/assets/10278096/19077432/76e019e4-8a01-11e6-88f7-90806dd1c92f.png)

**Comment by Morgy93** [comment]
@her Did you reload the application after you've saved the changes? On Windows it's Ctrl+Shift+R, I assume on Mac it's Cmd+Shift+R 

You also may want to toggle the server list (View -> Toggle server list) for additional space. =)

**Comment by her** [comment]
@Morgy93 **Toggle Server list**, oh man, thank you for this, I swear it wasn't there when I went looking for that! 😄🙏

For Mac it's just CMD+R and I did refresh it 😓 but that didn't seem to change it at all. I was using the devtools a bit to tweak the footer and I got some weird behavior when trying to hide it/modify it.  

![screen shot 2016-10-04 at 7 49 30 am](https://cloud.githubusercontent.com/assets/10278096/19079057/257eb816-8a07-11e6-8118-a1e307d169b6.png)

**Comment by Morgy93** [comment]
@her That's odd. I can't really imagine that your source code is different than mine.
Anyway, I found out that the DevTools got a different behaviour than the Custom CSS itself - you cannot apply the code one by one while having the same effect. (Which is pretty weird imho)
Try this one:
```
.side-nav .footer { display: none !important; }
.side-nav .rooms-list { height: 100% !important; }
.side-nav .rooms-list > .wrapper { padding-bottom: 5em !important; }
```

**Comment by alexbrazier** [comment]
You might need to set padding bottom to be slightly more to allow you to scroll further to see all channels, but the above code works for me.
