### ISSUE TITLE
Wrong filenames after uploading several files into chat

### ISSUE THREAD

**Issue by iMiKED** [RocketChat/Rocket.Chat.Electron#2206]
**Describe the bug**
When I'm trying to upload several files into chat, 2nd and 3rd and so on files attached with wrong filename (like it was in 1st file)

What operating system and which version?
Win10 x64 21H1
Which version of Rocket.Chat (Server)?
3.16.3
Which version of Rocket.Chat.Electron (Electron/Desktop)?
3.5.7
Is there any setting relevant changed?
No

**To Reproduce**
1. Go to chat / channel
2. Press Attach button, select "From PC" or just d'n'd files into chat
3. Select several files to attach (>1)
4. On file attach dialogue check for wrong filename
5. After attaching into chat check for wrong filename

**Expected behavior**
Filenames are correct

**Screenshots**
Attached
![files3](https://user-images.githubusercontent.com/1527992/137484119-84adc3f5-8d44-4b46-a38a-b8e4fd7362a1.png)
![files2](https://user-images.githubusercontent.com/1527992/137484124-e7b87a08-0533-46eb-9d5f-3a608ca8c933.png)
![files1](https://user-images.githubusercontent.com/1527992/137484128-00252105-c9df-4db5-9a84-1a255f145ec5.png)
![files](https://user-images.githubusercontent.com/1527992/137484131-f27efcd0-3b62-4ec7-a456-20a3c64497be.png)

**Comment by dougfabris** [comment]
@iMiKED @ankar84 thanks for supporting us, we're going to fix this issue in this PR: RocketChat/Rocket.Chat#23791
As this is not an Electron issue, I'm closing this one!
