### ISSUE TITLE
After updating server to Debian 11 desktop app crash on creating an video call

### ISSUE THREAD

**Issue by mokilcde** [RocketChat/Rocket.Chat.Electron#2207]
**Describe the bug**

What operating system and which version?
Which version of Rocket.Chat (Server)? 4.0.2
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.5.6 on Debian Sid
Is there any setting relevant changed? Update server from Debian 10 to 11

**To Reproduce**
1. Click on  phone sign
2. New window start
3. Then dead

No problem when using Chrome on Debian Sid
No problem with 3.5.7 on WIndows10

Syslog log:
Oct 18 08:22:29 k-c13 chat.rocket.RocketChat.desktop[20762]: focus-change for guestInstanceId: 4
Oct 18 08:22:30 k-c13 kernel: [ 5596.017053] rocketchat-desk[20927]: segfault at 28a0f2fcffff ip 00003b2d5ba169a1 sp 00007ffdd6657fa8 error 6
Oct 18 08:22:30 k-c13 kernel: [ 5596.017061] Code: 00 48 8b 4e 23 03 d0 e9 10 00 00 00 66 0f 1f 84 00 00 00 00 00 0f 1f 40 00 48 8b c6 48 3b 21 0f 86 12 00 00 00 8d 70 01 8b c0 <c6> 04 03 00 3b d6 75 e7 48 8b e5 5d c3 48 89 55 e8 48 89 5d e0 48
Oct 18 08:22:38 k-c13 chat.rocket.RocketChat.desktop[20762]: [bugsnag] Uncaught exception, the process will now terminate…
Oct 18 08:22:38 k-c13 chat.rocket.RocketChat.desktop[20762]: Error: Render frame was disposed before WebFrameMain could be accessed
Oct 18 08:22:38 k-c13 chat.rocket.RocketChat.desktop[20762]:     at Object.n._sendInternal (electron/js2c/browser_init.js:165:558)
Oct 18 08:22:38 k-c13 chat.rocket.RocketChat.desktop[20762]:     at Object.b._sendInternal (electron/js2c/browser_init.js:161:2550)
Oct 18 08:22:38 k-c13 chat.rocket.RocketChat.desktop[20762]:     at BrowserWindow.closedByUser (electron/js2c/browser_init.js:185:2450)
Oct 18 08:22:38 k-c13 chat.rocket.RocketChat.desktop[20762]:     at Object.onceWrapper (events.js:422:26)
Oct 18 08:22:38 k-c13 chat.rocket.RocketChat.desktop[20762]:     at BrowserWindow.emit (events.js:327:22)
Oct 18 08:22:38 k-c13 chat.rocket.RocketChat.desktop[20762]:     at BrowserWindow.EventEmitter.emit (domain.js:467:12)
Oct 18 08:22:38 k-c13 systemd[3265]: app-flatpak-chat.rocket.RocketChat-20741.scope: Consumed 30.229s CPU time.

**Comment by ankar84** [comment]
related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1912

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
