### ISSUE TITLE
Keyboard shortcut: Switch to next channel/chat/etc. with new messages

### ISSUE THREAD

**Issue by sewi-cpan** [RocketChat/Rocket.Chat.Electron#221]
https://rocket.chat/docs/user-guides/keyboard-shortcuts/#keyboard-shortcuts shows some (2) keyboard shortcuts, but nothing to quickly jump to the next interesting chat.

Pidgin uses Ctrl+Tab to jump to the next chat tab or to the next chat tab with new messages (if any). Rocket can't use it as it's a web chat, but anything else would be great to have. Always searching for some highlighted chat, grabbing the mouse, clicking it takes a lot of time if you need to do it very often each day.
##

**Comment by tsdgeos** [comment]
web telegram uses Alt+Up/Alt+Down

**Comment by nabiyllin** [comment]
Cool feature, will be useful have this

**Comment by andrefaria** [comment]
Hi guys, we have just migrated to rocket.chat from matter most, and this is the only feature that I'm missing for now. It's really annoying having to use the mouse to go to the next channel. Congrats for the product and keep on rocking!

**Comment by cmrd-senya** [comment]
I created a PR for this feature  #10366, but I need some feedback from more experience contributors in order to complete it.

**Comment by engelgabriel** [comment]
Closing this issue as the solution needs to be implemented on the main project.

**Comment by evgeni** [comment]
@engelgabriel do you have an issue open for it already? If so, can you please reference it?

**Comment by cmrd-senya** [comment]
@evgeni see https://github.com/RocketChat/Rocket.Chat/issues/4256
