### ISSUE TITLE
no valid server found at the url / selfsigned CA and Server-Certificates

### ISSUE THREAD

**Issue by zenhighzer** [RocketChat/Rocket.Chat.Electron#2215]
**Describe the bug**
- Rocketchat-server is running on raspberry pi
- Created Selfsigned CA & Server Certificate
- Imported CA-Certificate to Workstations and Smartphones to trust the server-certificates
- Adding Server to Desktop-App with https://....  -> no valid server found at the url
- Launching RocketChat via Browser: No problem
- Launching RocketChat via App on Smartphones: no problem
- Problem only occurs on (Windows) Desktop App

What operating system and which version?
Rocket.Chat (Server):  1.3.2 on Raspberry Pi
(Electron/Desktop): 3.5.7

**Expected behavior**
Beeing able to add server to windows desktop app

**Comment by ankar84** [comment]
I believe server version is too old now.
Please try more recent version, at least 3.18.2 and tell if it helps.

**Comment by zenhighzer** [comment]
raspberry pi bash: 

snap list 
rocketchat-server  1.3.2      1397   latest/stable

snap refresh
All snaps up to date.

Seems to be the latest version on raspberry pi

**Comment by zenhighzer** [comment]
is there a way to import (selfsigned) ca-certificates into the desktop app? I just imported "system-wide" on windows

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
