### ISSUE TITLE
Weird Font on Rocket Chat Mac OS App 3.5.7

### ISSUE THREAD

**Issue by cdlp789** [RocketChat/Rocket.Chat.Electron#2218]
## My Setup

- Operating System:  Mac OS 10.5.7
- App Version: 3.5.7
- Installation type: dmg

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
(Isolated Issue) Total users: 100+ 
(1) User reports having this issue after logging into our server. Font UI appears in english when prompting for credentials. After successful login, it goes to this. Can't identify nor replicate issue on my end. Tried to uninstall app. Reset app data. Deleted any "rocket" files in the library under preferences, cache, app support. Reinstalled app. Went to app settings to 
try to change language to English on both app and Macbook preferences. All other apps work fine.

### Current Behavior

![RC Font Issue](https://user-images.githubusercontent.com/93737817/140430367-52617453-7b49-4628-9a23-c5fb06ff1a20.png)

**Comment by jeanfbrito** [comment]
Please test if the lastest release (3.7.0) has solved this issue.
