### ISSUE TITLE
The preview of photos (HEIC format) uploaded from iPhone is not displayed.

### ISSUE THREAD

**Issue by noobbbbb** [RocketChat/Rocket.Chat.Electron#2220]
**Describe the bug**
The preview of photos (HEIC format) uploaded from iPhone is not displayed.

What operating system and which version? : CentOS Linux release 7.5.1804
Which version of Rocket.Chat (Server)? : 3.18.0 (Self Hosted)
Which version of Rocket.Chat.Electron (Electron/Desktop)?: 3.5.7
Is there any setting relevant changed?: 

**To Reproduce**
1. Take a picture with iPhone
2. Upload to RC
3. View with Electron/Desktop client

**Expected behavior**
A preview of the image will be shown.

**Screenshots**
![ScreenShot 2021-11-08 123031](https://user-images.githubusercontent.com/37917355/140680049-5a0519d9-9fa3-4409-96fe-1670900911a6.png)

**Additional context**
Probably related
https://github.com/RocketChat/feature-requests/issues/220

**Comment by dusatvoj** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/23638
