### ISSUE TITLE
Links in embedded posts (for instance tweets) open app in the electron app und leave dark page

### ISSUE THREAD

**Issue by saschafoerster** [RocketChat/Rocket.Chat.Electron#2222]
1. Post a link to a tweet with a link to an external page into a chat so it gets embedded. 
2. Click on the link: NOT of the tweet, but of the link IN the tweet. 
3. Blank page. Only restart of RocketChat-app helps. 

Expected behavior: Open link externally in default browser.

MacOS 12.0.1
RocketChat 4.1.1
Rocket Chat Electron 3.5.7

**Comment by jeanfbrito** [comment]
Please test if the lastest release (3.7.0) has solved this issue.

**Comment by saschafoerster** [comment]
@jeanfbrito I am sorry, but no. Try using any tweet with a link in it, then click on the link in the preview of RocketChat. This time the links opens in the Rocket.Chat-app, not in the browser-window outside of it.

**Comment by jeanfbrito** [comment]
Fixed on version 3.8.11.
