### ISSUE TITLE
(fix) disable GPU crashes on Windows 10 LTSC since 3.5.2

### ISSUE THREAD

**Issue by Bonecurse** [RocketChat/Rocket.Chat.Electron#2223]
**Describe the bug**
If "Disable GPU" is enabled, Rocket.Chat won't start until you terminate the process and start the exe.

What operating system and which version?
Windows 10 LTSC

Which version of Rocket.Chat.Electron (Electron/Desktop)?
3.5.2 upwards

Is there any setting relevant changed?
Disable GPU setting

**To Reproduce**
1. Run 3.5.2 (or higher)
2. Click on 'File'
3. Click on 'Disable GPU'

**Expected behavior**
Rocket.Chat Client should restart in disabled GPU mode

**Additional context**
The problem was introduced with changes in the main.ts file in 3.5.2
(https://github.com/RocketChat/Rocket.Chat.Electron/pull/2153)
The line "await app.whenReady();" was moved from line 41 to 35. 
If I revert this change in Visual Studio it works again.

**Comment by jeanfbrito** [comment]
Please test if the lastest release (3.7.0) has solved this issue.

**Comment by YvvkiRika** [comment]
> Please test if the lastest release (3.7.0) has solved this issue.

It's not fixed yet, app stays on background and need to be ended using task manager, rerunning the app would not disable GPU.

**Comment by Bonecurse** [comment]
I can confirm what YvvkiRika said. The problem still persists.
