### ISSUE TITLE
keyboard shortcut alt+enter for new wordwrap in same message not working anymore

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Electron#223]
## My Setup
-  Windows 10 Pro Version 1511: 
- 1.3.1 
- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
#### Current Behavior

After an update of the rocket.chat server the keyboard shortcut "alt+enter" to insert a new wordwrap in my message is not working anymore, the cursor is jumping in the first line again. (I used this to get a new line for my codeblock "```"
#### Expected Behavior

Shortcut alt+enter jumps to the second line of a message so i can write some text, press alt+enter and insert my code block.
##

**Comment by LXSysadmin** [comment]
Yes, it is not working Windows 10 x64 Desktop client 1.3.1 and Web client.

**Comment by TheReal1604** [comment]
Okay, read through the docks and found that the new keyboard shortcut is "shift + enter". 

https://rocket.chat/docs/user-guides/keyboard-shortcuts/
