### ISSUE TITLE
Avatar External Provider URL is not working on versions later than 3.2.4

### ISSUE THREAD

**Issue by adilshoukat** [RocketChat/Rocket.Chat.Electron#2231]
**Describe the bug**
When I set the `Avatar External Provider URL` from Administrator area and refresh the RocketChat client, the avatars are all broken.

**To Reproduce**
1. Go to 'Administration -> Accounts -> Avatar'
2. Enter a valid avatar Provider URL
3. Click 'Save changes'
4. Go back to RocketChat client and notice the broken avatars

**Expected behavior**
The avatars should be loaded from the provider's URL

**Screenshots**

Administration side:
![Screenshot_235](https://user-images.githubusercontent.com/1608798/141875329-57841631-e432-40ef-919f-6aed910dd8c0.png)

Client side:
![Screenshot_234](https://user-images.githubusercontent.com/1608798/141875338-62d0fef5-3ebc-4442-9b6e-61c046ecfd70.png)

**Additional context**
I have tested version by version. It's working perfectly fine till 3.2.4 and not working on any later version.

**Comment by jeanfbrito** [comment]
On web browser this dont happens? Seems like a server issue to me.

**Comment by adilshoukat** [comment]
> 
> 
> On web browser this dont happens? Seems like a server issue to me.

It doesn't happen on Web Browser. I am able to see Avatars on Web version.

**Comment by jeanfbrito** [comment]
Would you mind in sharing with me the URL that you used?
You can reach me at https://open.rocket.chat/direct/jean.brito

**Comment by adilshoukat** [comment]
> 
> 
> Would you mind in sharing with me the URL that you used? You can reach me at https://open.rocket.chat/direct/jean.brito

The Avatar URL I am using is hosted on a local IP and the URL is mapped in my Windows host file. So the URL is not accessible outside the network.

You can use any online image URL like this one: https://www.winhelponline.com/blog/wp-content/uploads/2017/12/user.png

It will show same avatar for all the users but you can test the broken avatar with this at least.

**Comment by jeanfbrito** [comment]
I couldnt reproduce the problem here. Could you test with our newest release?

**Comment by adilshoukat** [comment]
> I couldnt reproduce the problem here. Could you test with our newest release?

I am sorry. It turned out that my SSL had expired and that was causing this issue. But I am not sure that how it was working fine with older versions even with the expired SSL certificate.
