### ISSUE TITLE
Rocket.Chat window not shown properly

### ISSUE THREAD

**Issue by martii-xx** [RocketChat/Rocket.Chat.Electron#2240]
### Description:

The size of Rocket Chat Desktop app is not big enough to show the whole app. It looks like the app would be in full screen modus but it is not - for example the left menu with users cannot be shown properly. The field where the message is tipped into cannot be shown in the right size.
I tried:
- deinstalling and installing Rocket (old version: 3.5.7 and the new installed version is 3.6.0)
- using F11 to disable full screen modus
- Reload the app with Ctrl + R and Ctrl + Shift + R
- Try to resize window with Ctrl + -, Ctrl + + and Ctrl + 0 in order to bring the app in the right size
I wanted also to reset user data but as long as I cannot see the rocket bar with settings and there is no shortcut for it, I cannot do it.

### Expected behavior:

I expect to see the whole rocket chat properly.

### Actual behavior:
![Bildschirmfoto 2021-11-29 um 12 26 06](https://user-images.githubusercontent.com/92687063/143863917-bf5bb873-b47b-4b9a-a4e0-02a3d5447dfb.png)
See left side of Rocket and bottom side. The issue happens while using intern and extern monitor.

### Client Setup Information

- Desktop App or Browser Version: 3.5.7 and 3.6.0
- Operating System: Windows 10 2009

**Comment by jeanfbrito** [comment]
Please test if the lastest release (3.7.0) has solved this issue.

**Comment by jeanfbrito** [comment]
Please test again using our latest release from Github that can fix it. I will be closing the issue but If it remains an issue, please reopen and update it.
