### ISSUE TITLE
MSI 32bit/64bit flipping

### ISSUE THREAD

**Issue by stroetgen** [RocketChat/Rocket.Chat.Electron#2248]
In the releases, the MSI installer switches unpredictably between 32 and 64 bit. The MSI file does not show which version was created. This makes deployment very troublesome.

Please either build a constant variant (64 bit is preferred from my point of view) or two different variants (this additional effort would not be necessary from my point of view).

Thank you!

Robert

**Comment by ankar84** [comment]
Related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1878
Where did you find MSI for 32bit?

**Comment by stroetgen** [comment]
- MSI in https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.7.0 installes 32 bit
- MSI https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.6.0 installes 64 bit

**Comment by jeanfbrito** [comment]
This behaviour is not intended and seems like a bug on Electron Builder, I'm trying to solve that but if it don't get solved, I will add a package for each version.

**Comment by ankar84** [comment]
> I will add a package for each version.

This is the best solution and will solve this issue https://github.com/RocketChat/Rocket.Chat.Electron/issues/1878

**Comment by jeanfbrito** [comment]
> > I will add a package for each version.
> 
> This is the best solution and will solve this issue #1878

Even so, the MSI package needs to work to install even on x86 and x64. Its not working on 32 bits @ankar84 ?

**Comment by ankar84** [comment]
> > > I will add a package for each version.
> > 
> > 
> > This is the best solution and will solve this issue #1878
> 
> Even so, the MSI package needs to work to install even on x86 and x64. Its not working on 32 bits @ankar84 ?

Exactly!
You can't install MSI x64 package on x86 machine - there will be error!
![image](https://user-images.githubusercontent.com/4023037/145948657-76fbfdb7-1ae6-4923-8fe7-5ff88aa12feb.png)

So one proper way install MSI x64 package on x64 machine and install MSI x86 package on x86 machine.
So we always need two MSI packages for installation catually.

**Comment by stroetgen** [comment]
Still flipping in latest releases ...

**Comment by jeanfbrito** [comment]
Now we have 32 and 64 bits installers separated files. I think that this solves this issue. I will be closing it but any problem tell me.
