### ISSUE TITLE
Screen-sharing macOS

### ISSUE THREAD

**Issue by moell9** [RocketChat/Rocket.Chat.Electron#2249]
The Video Call (Jitsi Meet) Screen-sharing with version 3.7.0 under macOS doesn't work anymore.

**Comment by ankar84** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/2028

**Comment by BSerpent86** [comment]
@jeanfbrito this affects Windows and Linux, too. It's extremely annoying. Could this be fixed in 3.7.1, too?

**Comment by jeanfbrito** [comment]
> @jeanfbrito this affects Windows and Linux, too. It's extremely annoying. Could this be fixed in 3.7.1, too?

Yep, is the priority to fix, we already found the problem. Working in a fix right now.
