### ISSUE TITLE
Tray icon disappears

### ISSUE THREAD

**Issue by sketch242** [RocketChat/Rocket.Chat.Electron#225]
CentOS 7.2, running GNOME 3.14.  Originally running Rocketchat 1.2.0 converted from the deb package via alien, then I tried 1.3.1 converted from the deb package, then I built my own 1.3.1, just in case there was some sort of dependency issue.

In all 3 cases, the tray icon disappears after a day or two.
##

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
