### ISSUE TITLE
Desktop App wont start on windows 10 

### ISSUE THREAD

**Issue by lfischler** [RocketChat/Rocket.Chat.Electron#2253]
**Describe the bug**
Randomly the rocket chat app stopped working, so I made sure to see if I had the latest update. I then updated to version 3.7.0 and it still didnt work.

What operating system and which version?
Windows 10 21H1

Which version of Rocket.Chat (Server)?
3.18.3

Which version of Rocket.Chat.Electron (Electron/Desktop)?
3.7.0 and earlier

Is there any setting relevant changed?
not that I know of

**To Reproduce**
Start the app from start menu or application shortcut and nothing happens.
In task manager numerous rocket chat process spawn but dissapear almost immediately.

**Expected behavior**
Rocket Chat desktop starts as normal.

**Comment by Deviniska** [comment]
Had the same issue with two windows computers. The log says:  The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID System Error.
Reinstallation didn't help

**Comment by jeanfbrito** [comment]
Please test again using our latest release from Github that can fix it. I will be closing the issue but If it remains an issue, please reopen and update it.
