### ISSUE TITLE
Sidebar buttons grayed out on Windows 10

### ISSUE THREAD

**Issue by Clinas** [RocketChat/Rocket.Chat.Electron#2255]
The sidebar buttons appear grayed out no matter what I do. However I can still access the menus via their accelerators. (Ctrl + N for New Server, Ctrl + I for Settings and Ctrl + D for Downloads)

Am I missing something or is this a bug?

**Comment by jeanfbrito** [comment]
Please download the github last release and test it. It was a problem fixed on 3.7.0 early release.

**Comment by jeanfbrito** [comment]
I will close the issue, if it continues, please reopen it.
