### ISSUE TITLE
Error message on Windows shutdown

### ISSUE THREAD

**Issue by imperatom** [RocketChat/Rocket.Chat.Electron#2268]
What operating system and which version? Win 7
Which version of Rocket.Chat (Server)? 3.7.0 and 3.7.1

Not every time, but in some 50% of all cases I get an error message on Windows Shutdown, when RC is reduced to system tray bar. It tells, that Windows cannot be shutdowned correctly due to an error in RocketChat. I need to "force shutdown" then. 

The error did not appear with older versions of RocketChat than 3.7.0.

**Comment by jeanfbrito** [comment]
Hello @imperatom!
Can you test if this happens on a Windows 10 machine? Just to get if is a problem in the Windows 7.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
