### ISSUE TITLE
Desktop app never opens after installation 3.7.0 and 3.7.1

### ISSUE THREAD

**Issue by mohammedragabsoftxpert** [RocketChat/Rocket.Chat.Electron#2269]
## My Setup

- Operating System: Ubuntu 20.04
- App Version: 3.7.0 and 3.7.1
- Installation type: debian "dpkg" installation and same on snap for latest one

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
After installation, i open it for connecting to my rocketchat server, but after closing, the app never start or open again, with below errors in the syslog:

`Dec 24 04:59:59 homepc dbus-daemon[764]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.197' (uid=1000 pid=4015 comm="/opt/Rocket.Chat/rocketchat-desktop --enable-crash" label="unconfined")
Dec 24 04:59:59 homepc systemd[1]: Condition check resulted in Bluetooth service being skipped.
Dec 24 04:59:59 homepc rocketchat-desktop.desktop[2928]: (node:2928) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
Dec 24 04:59:59 homepc rocketchat-desktop.desktop[2928]:     at /opt/Rocket.Chat/resources/app.asar/app/main.js:2398:28
Dec 24 04:59:59 homepc rocketchat-desktop.desktop[2928]:     at Generator.next (<anonymous>)
Dec 24 04:59:59 homepc rocketchat-desktop.desktop[2928]:     at fulfilled (/opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:114:62)
Dec 24 04:59:59 homepc rocketchat-desktop.desktop[2928]: (node:2928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
Dec 24 04:59:59 homepc rocketchat-desktop.desktop[4049]: libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
Dec 24 04:59:59 homepc rocketchat-desktop.desktop[4049]: [4049:0100/000000.635092:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
Dec 24 04:59:59 homepc systemd[1425]: gnome-launched-rocketchat-desktop.desktop-4015.scope: Succeeded.
Dec 24 05:00:00 homepc rocketchat-desktop.desktop[2928]: [bugsnag] Unhandled rejection…
Dec 24 05:00:00 homepc rocketchat-desktop.desktop[2928]: TypeError: Object has been destroyed
Dec 24 05:00:00 homepc rocketchat-desktop.desktop[2928]:     at /opt/Rocket.Chat/resources/app.asar/app/main.js:2398:28
Dec 24 05:00:00 homepc rocketchat-desktop.desktop[2928]:     at Generator.next (<anonymous>)
Dec 24 05:00:00 homepc rocketchat-desktop.desktop[2928]:     at fulfilled (/opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:114:62)
`
That never happens with older versions, my old one 3.1.1 was fine, and also i tried the 3.6.0 works perfect. This issue happens with both 3.7.0 and 3.7.1 versions

### Current Behavior
App never starts

### Expected Behavior
Simply the apps starts

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by nickma82** [comment]
Github: "you cannot re-open your own issues if a repo collaborator closed them".

**Comment by jeanfbrito** [comment]
> Github: "you cannot re-open your own issues if a repo collaborator closed them".

I can open it again if there is any update about the last version having the same issue.

**Comment by mohammedragabsoftxpert** [comment]
> Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.
> 
> Thank you!

The 3.7.3 doesn't have that bug issue, thanks!
