### ISSUE TITLE
Downloading files opens default browser, leading to 403

### ISSUE THREAD

**Issue by tstumm** [RocketChat/Rocket.Chat.Electron#227]
## My Setup
- OS X El Capitan 10.11.6
- 1.3.1
- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

When someone sends me a file and I try to download it, it opens the link in Chrome. Since I'm not authenticated in my browser I get a 403 error and can't download the file.
#### Current Behavior

Download links are opened externally.
#### Expected Behavior

Downloads should be processed internally.
##

**Comment by frdmn** [comment]
A temporary workaround is to download the files via the "attachments" sections in the flexbar on the right side of the screen.

**Comment by LXSysadmin** [comment]
Yes, but this workaround is not good. I have this issue with Windows 10 Desktop client 1.3.1. The workaround is to open RocketChat server link with browser, then session will be active and you will be able to open Desktop Client link. But this must be fixed ASAP!!

**Comment by frdmn** [comment]
I totally agree, would be nice to use the default download method in the Electron client as well.

**Comment by LXSysadmin** [comment]
Yes, because users are confused when trying to open links, there are not so many users that know Desktop Client Files List option.

**Comment by goobersmooch** [comment]
I'm having the exact same problem on macOS 10.11.6.

**Comment by alexandrezia** [comment]
This is at the moment the top 1 complain from my users

**Comment by ericlakich** [comment]
+1 for a fix on this. Our users must authenticate (log in to Rocket.Chat) in the browser before they can view linked attachments because the attachments from the client are redirecting to the browser. Our configuration uses S3 as the file upload location. Our server version is 0.42.0 and our client version is Mac 1.3.1 (15). This symptom seems to be server/client related and showed up with a server version update from 0.23.0 to 0.42.0 with no change to client version.

**Comment by graywolf336** [comment]
We are aware that this is a big issue and we're completely open to people
submitting a pull request to get this fixed. Once we get some time, this
will be one of the first things we look into.

**Comment by philinx** [comment]
ubuntu 16.04; Rocket.Chat 0.44; Client Windows 7; Rocket.Chat+ Version 1.3.1

+1 for a fix on this

**Comment by Nosferous** [comment]
+1 for fix please.

Server: Ubuntu 16.04; Rocket.Chat 0.44 & 0.45; Client OSX (10.9.x-10.11.x); Rocket.Chat.Electron Version 1.3.1

**Comment by mcmdhr** [comment]
+1. 

subscribe this issue : >

**Comment by jsumners** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/4417

**Comment by alexbrazier** [comment]
Is this still happening with the latest version? I'm unable to reproduce this on Windows 10 or macOS.

**Comment by alexbrazier** [comment]
I think this is working in the latest version. Please reopen if not.

**Comment by MajesticGray** [comment]
this is still an issue.

macos sonoma
RocketChat official app store client (version 3.9.7)
RocketChat server version 6.4.5

The attachment link is missing the `?download` part of the URL, thus opening browser
The tiny, cloud, download icon link is working properly

**Comment by flover97** [comment]
same problem on RocketChat server  6.4.5

**Comment by rgoerner** [comment]
Same here, opens in external browser window with 403 error

**Comment by amsnek** [comment]
same Problem, RC 6.5.2 and Client 3.9.11 -> opens in browser, will result in 403 since not authenticated (unless allow access for anyone is set which is not wanted)

**Comment by matxxmat** [comment]
The problem still exists in client 3.9.14

**Comment by georgmay** [comment]
Problem still persists when opening files from rocketchat app. Had to disable file protection so users can actually use it. Which kinda sucks.

**Comment by jeanfbrito** [comment]
> Problem still persists when opening files from rocketchat app. Had to disable file protection so users can actually use it. Which kinda sucks.

It will be fixed for all the file storage options in 6.10. Its a server issue that is fixed and will be released on next update.
