### ISSUE TITLE
Windows Client 404 trying to access server available before and still available in Firefox

### ISSUE THREAD

**Issue by chrisxchrisxchrisx** [RocketChat/Rocket.Chat.Electron#2277]
Version 3.7.4 installed, re-installed, restarted, Windows 10 (edit: Workaround - Help/Reset app data)

**Comment by jeanfbrito** [comment]
Please describe the problem in a better way.

**Comment by chrisxchrisxchrisx** [comment]
> Please describe the problem in a better way.

Thank you for asking Jean:

Action:
- install Rocket Chat 3,7,4 msi under Windows 10.0.19042
- add server URL
- enter server credentials
- chat on server using Rocket Chat client
- attempt to continue chatting as above
- enter server URL into Firefox browser
- chat on server using Firefox browser
Expected results:
- Rocket Chat client responds to chat
- Rocket Chat client continues to respond
- Firefox browser responds to chat
Actual results:
- Rocket Chat client responds to chat
- Rocket Chat client reports http status 404 server unavailable
- Firefox browser responds to chat

Additional actions with similar results:
- restart Rocket Chat client
- restart Windows
- uninstall and reinstall Rocket Chat client
- uninstall and reinstall Rocket Chat client 3.7.2
- re-enter server URL to Rocket Chat client

Additional actions with expected results:
- clear user app data in Rocket Chat client
- add server URL in client
- enter server credentials
- attempt to continue to chat on Rocket Chat client
- Rocket Chat client responds to chat
- Rocket Chat client no longer reports http status 404 server unavailable

I hope that this is clear. In a nutshell, the chat client suddenly started reporting an http 404 status for a server that continued to be available via another browser, and this behaviour was not cleared until the user app data was cleared.

It appears that the user app data was corrupted because clearing it stopped the 404 error, although re-entering the server URL without clearing the data did not.

Possibly this is fixed in Rocket Chat client 3.7.5, but I thought it might be helpful to know.

I hope this is clearer. Thank you for your work.

Love and respect
Chris

**Comment by jeanfbrito** [comment]
Thanks for the explaining. Seems like a corruption in the server config. This is happening on all your clients or just in one that happened?
I want to understand if is a general problem or just a one time bug.

**Comment by chrisxchrisxchrisx** [comment]
Thank you Jean. It appears to have been a one time bug, but I'll post here again if it recurs or I get any further information.

Thank you for all you do.
