### ISSUE TITLE
High cpu usage with Rocket.Chat.Electron client v3.7.5 on Mac

### ISSUE THREAD

**Issue by bekirby** [RocketChat/Rocket.Chat.Electron#2281]
**Describe the bug**
I am using the current Rocket.Chat.Electron client v3.7.5 on Mac and am seeing very high CPU usage. I don't see a lot of other issues or bug reports on this so not sure if maybe I am doing something wrong? The Rocket.Chat Helper (Renderer) process is often above 100% and have seen it as high as 130+%

What operating system and which version?
Mac OS Monterey v12.1

Which version of Rocket.Chat (Server)?
v3.18.0

Which version of Rocket.Chat.Electron (Electron/Desktop)?
Is there any setting relevant changed?
 v3.7.5

**To Reproduce**
1. Install Rocket Chat client v3.7.5 and start
2. Observe CPU usage on Mac using Activity Monitor

**Expected behavior**
CPU usage would be minimal ~10%

**Screenshots**

**Additional context**

**Comment by jeanfbrito** [comment]
If you close it and open again, It will use the CPU again?
Did you know how to reproduce the problem?

**Comment by bekirby** [comment]
I have tried a couple different versions of the client, but yes - if I close the client and restart it - initially the client has lower cpu usage. Within a couple minutes it hits ~20% and continues to climb. I do see it sometimes cleanup around 80% and go down to around 25%, but then climbs back up over 100% in about 10 minutes.

I don't know how to tell you to reproduce it - all I did was install the app on Mac and start it. No special config changes or anything.

![rocket_chat_cpu](https://user-images.githubusercontent.com/33604058/148805579-914adea8-610d-4605-8a67-bde9cc4e42eb.png)

Thanks for the quick reply!

**Comment by jeanfbrito** [comment]
I will need more help to find what's going on with your client.
Could you please test with the open.rocket.chat server if it will happens too? Maybe is a server issue?

I'm using Monterey too in a Macbook M1 Pro and don't get the problem. Look:
![image](https://user-images.githubusercontent.com/1177482/148814593-e2a478ff-7f64-4640-9050-27d836dbd7c1.png)

**Comment by bekirby** [comment]
I am assuming you have let it run for several minutes? I will give it a try later today. Thanks!

**Comment by jeanfbrito** [comment]
> I am assuming you have let it run for several minutes? I will give it a try later today. Thanks!

Yep, its running all the day long.

**Comment by bekirby** [comment]
@jeanfbrito I did as you suggested and installed the client app on a home computer - MacBook Air - and connected to the open.rocket.chat server. It seems fine so it must be something in my workplace environment: server, proxy, network, etc.

Thank you for taking a look.

**Comment by jeanfbrito** [comment]
I will be closing the issue then. But if you could find the where is problem please tell us. Maybe we can found a fix.
Thanks!

**Comment by alexweissman** [comment]
I had a similar problem. Resetting the app data and then signing back into your server(s) seems to alleviate the pressure on client resources.
