### ISSUE TITLE
Check for Update does not work in 3.7.4

### ISSUE THREAD

**Issue by xmedeko** [RocketChat/Rocket.Chat.Electron#2284]
**Describe the bug**

What operating system and which version? Windows 10, installation per user only
Which version of Rocket.Chat (Server)?  4.1.1
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.7.4
Is there any setting relevant changed?

**To Reproduce**
I see a new RC version on GitHub releases.

1. Go to Help > About Rocket.chat
2. Window appears with the Version Number and Check for Updates.
3. Clicking Check for Updates does nothing. The about dialog closes. 

**Additional context**
When I quit the app and start it again, then an upgrade dialog appears and the upgrade process goes well.

**Comment by xmedeko** [comment]
Windows 10, installation per user only.
_(I am sorry I have forgotten to fill that up.)_

**Comment by jeanfbrito** [comment]
Hey @xmedeko this will be fixed on the next release. The fix is already merged on main.
