### ISSUE TITLE
[Bug] Click on notification stop working after refresh in DevTools 

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#2286]
**Describe the bug**
Click on Rocket.Chat Electron notifications stop working after user launch DevTool in menu or  with CTRL+SHIFT+I shortcut, pointing to Network and press CTRL+R to refresh

What operating system and which version?
Which version of Rocket.Chat (Server)?
Which version of Rocket.Chat.Electron (Electron/Desktop)?
Is there any setting relevant changed?

**To Reproduce**
1. Open RC.Electron
2. Test click on notification, it should work fine
3. Open DevTool in menu View - Open DevTools or via CTRL+Shift+I
4. Go to Network tab of DevTools
5. Press CTRL+R
6. Test click on notification again - it do nothing - broken!

**Expected behavior**
Click on notification open chat from where message id come.

**Screenshots**
![devtools-click01](https://user-images.githubusercontent.com/4023037/149287236-c10a334e-d68b-4acb-93fc-fa3ae4649fde.gif)

**Additional context**
I guess when reload with DevTools on top something not loaded properly.

**Comment by jeanfbrito** [comment]
If you dont reload it dont happens? The devtools open is not the issue?
The console log shows something when this happens?

I will try to reproduce it here.

**Comment by ankar84** [comment]
> If you dont reload it dont happens? The devtools open is not the issue?

Exactly. Just launching Devtools not lead to that bug and click on notification works in that case.



> The console log shows something when this happens?

Nope, I didn't find anything.

**Comment by jeanfbrito** [comment]
I think that I could reproduce here, but on console of the server it showed an error.
Please, right click on the server and open dev tools and open console. There has to have an error when it the problem. Can you confirm it to me?
![image](https://user-images.githubusercontent.com/1177482/149529961-2d54ee0c-a8c3-4bf2-9846-43787abd965d.png)

**Comment by ankar84** [comment]
Looks like that issue is fixed in 3.7.8
At least reproduce steps don't lead to problem.
So I'm closing that issue now and will open it if problem come back.

**Comment by ankar84** [comment]
Oh. In fact the issue is much worth now.
@jeanfbrito please take a look.

Steps to reproduce the behavior:

1. Open RC.Electron
2. Test click on notification, it should work fine
3. Press CTRL+R
4. Test click on notification again - it do nothing - broken!

**Comment by jeanfbrito** [comment]
> Oh. In fact the issue is much worth now. @jeanfbrito please take a look.
> 
> Steps to reproduce the behavior:
> 
> 1. Open RC.Electron
> 2. Test click on notification, it should work fine
> 3. Press CTRL+R
> 4. Test click on notification again - it do nothing - broken!
> 
> CTRL+R is a must have combination for our users to resolve lots of little front-end issues and memory consumption, so that new behavior is much more painful for us.

After reload, the notifications shows but when you click on it, the window don't opens, right?
Very frustrated that this doesn't happens to me, but now I tested and happened... :(

**Comment by ankar84** [comment]
> After reload, the notifications shows but when you click on it, the window don't opens, right?

Exactly!
And interesting thing - issue from first post is resolved now, so when you reload from DevTools - notifications works fine.

**Comment by ankar84** [comment]
3.7.9 issue is still here.

**Comment by ankar84** [comment]
Version 3.8.0 issue is still here.
And I'm 100% sure there is another steps to make notification click inactive, and I'm investigating it right now.

**Comment by ankar84** [comment]
> And I'm 100% sure there is another steps to make notification click inactive, and I'm investigating it right now.

Yeap. Regular reload of server via CTRL+R brakes click on notification activity.
![devtools-click05](https://user-images.githubusercontent.com/4023037/159416058-67183a37-1c45-47c2-bb9f-f27af125e1b0.gif)

**Comment by Kyogre** [comment]
same here (3.8.1), very annoying. Only workaround is to fully close RC desktop app and launch it again.

**Comment by ankar84** [comment]
> same here (3.8.1), very annoying. Only workaround is to fully close RC desktop app and launch it again.

confirm all that.

**Comment by jeanfbrito** [comment]
We are already investigating this. It's the priority now, it's the same problem that makes the right click stop to work. After reload.
