### ISSUE TITLE
Start hidden not working 

### ISSUE THREAD

**Issue by antonioli86** [RocketChat/Rocket.Chat.Electron#2287]
Issue closed in https://github.com/RocketChat/Rocket.Chat.Electron/issues/1964 but not solved.

## My Setup

- Operating System: Windows 10
- App Version: 3.7.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Start hidden - set in window-state-main.json - does not work. After 2nd execution, in config.json is set to "maximized": true

`{
  "width": 1000,
  "height": 600,
  "isMaximized": false,
  "isMinimized": false,
  "isHidden": true,
  "x": 140,
  "y": 60
}`

### Current Behavior
In startup, Rocket.Chat window appears maximized

### Expected Behavior
Start hidden, without window (visible only in system tray)

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
