### ISSUE TITLE
RocketChat 3.7.6 msi installer: marked as 'infected' by symantec endpoint protection

### ISSUE THREAD

**Issue by Mathiasdm** [RocketChat/Rocket.Chat.Electron#2296]
## My Setup

- Operating System: Windows 10
- App Version: 3.7.6
- Installation type: msi

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
If I retrieve the msi installer and try to run it, the file is put in quarantine.
I realize this might be a Symantec issue, rather than a RocketChat issue.

### Current Behavior
Installer is quarantined.

### Expected Behavior
Installer runs.

**Comment by Mathiasdm** [comment]
The file is marked as WS.Reputation.1, which can apparently be related to false positives: https://knowledge.broadcom.com/external/article/191764/endpoint-protection-detects-known-good-a.html

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
