### ISSUE TITLE
Open video call in application window by default

### ISSUE THREAD

**Issue by jahohu** [RocketChat/Rocket.Chat.Electron#2299]
This is rather a feature request, but a bug in the sense that the default behavior of the desktop client regarding video calls has changed in version 3.6.0. The idea is to set the then introduced switch (allowing to set opening video calls in an application window or the default browser) in Window -> Settings to the opposite default value by default (without the user setting it explicitly), so to "Open Video Chat using Application Window", which is switched off by default now.

Thank you very much, contributors - all this is excellent work and is running perfectly!

**Describe the bug**
By default, the desktop app now opens new video calls in the default browser instead of a new application window, as it was before version 3.6.0.

What operating system and which version? Debian Server
Which version of Rocket.Chat (Server)? Currently 4.3.2, was the same before on 4.2.x
Which version of Rocket.Chat.Electron (Electron/Desktop)? All versions from 3.6.0 upwards.
Is there any setting relevant changed?

**To Reproduce**
1. With video server configured, In any chat or channel in the desktop app, click the call button
2. A new tab or window in the default browser opens
3. This can be changed (it works) by clicking Window -> Settings -> Activate the switch "Open Video Chat using Application Window"

**Expected behavior**
Honor what setting had been implemented before client version 3.6.0, open video calls in application window by default

**Comment by jeanfbrito** [comment]
Hello @jahohu I didnt get what is happening. 
Opening video call is enabled by default. I didn't get if you are having problem with this or what.
Any new installation start with it enabled.

Could you please test the lastest release?

**Comment by jahohu** [comment]
Hello, thanks for reaching out. Yes, video calls do open outside the Chat window. The thing in our setup is that we would like to have the default handling of the video call in the way that it opens an application window and not the browser window. The switch for that (Desktop app -> Window -> Settings), introduced in v. 3.6.0, leaves it to "browser window" when you don't switch manually. Sorry for the weird setup, but we cannot rely on our users to do this on their own, so they would end up with video calls in the browser. We want to avoid this because the video/audio device handling creates support question all the time. In the built-in application window of the Rocket client, so in the Chromium window that handles the Jitsi meeting, this works fine.

**Comment by jeanfbrito** [comment]
Thats the weird thing, by default the option is enabled and by default it opens on an Electron/Chromium window. Only if the user turned it off the option will be off.
Are you using the 3.7.6 version?

Sorry for the recurring questions, it that I want to really understand and help you.

**Comment by jahohu** [comment]
Well, apparently that was my test setup where I once installed version 3.6.0 and didn't entirely delete all profile settings after I played around with that switch. Now with an actual fresh installation, even in our setup situation in the upgrade path from 3.5.7, the default in 3.7.6 is as expected.
Sorry and thank you!

**Comment by jeanfbrito** [comment]
Perfect! I thought that was the issue. Thank you!
