### ISSUE TITLE
Mensagem de erro no início (windows/linux)

### ISSUE THREAD

**Issue by wesleycoder** [RocketChat/Rocket.Chat.Electron#23]
Nos aplicativos para Windows e Linux é apresentada a seguinte mensagem em vermelho na tela:
"Couldn't find a template named "error" or "error". Are you sure you defined it?"
![Imgur](http://i.imgur.com/lq0DhSy.png)

**Comment by rodrigok** [comment]
@wesleycoder Qual versão você baixou?
Chegou a testar a versão para OS X?

**Comment by sampaiodiego** [comment]
corrigido no 0.0.6
