### ISSUE TITLE
Popups for downloaded files

### ISSUE THREAD

**Issue by kkachura** [RocketChat/Rocket.Chat.Electron#230]
## My Setup

- **My OS name and version**:  Windows 8.1
- **My current app version**:  Developer branch

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
#### Expected Behavior

When file is attached, popup info is shown empty. (it is desirable to specify at least the name of the file).

**Comment by alexbrazier** [comment]
When uploading a file the name now appears in the name field by default
