### ISSUE TITLE
The application shows blank page on empty attachment

### ISSUE THREAD

**Issue by gundamew** [RocketChat/Rocket.Chat.Electron#2301]
**Describe the bug**
If the user opens any channel that contains at least a message with an empty attachment. The messages of the channel are displayed as expected at first. Then the app shows a blank window rapidly.

The OS is Ubuntu 20.04.3 LTS.
The issue was found on Rocket.Chat app version 3.7.3, also on 3.7.6.
Don't know the Rocket.Chat server version.

**To Reproduce**
1. Create a Rocket.Chat channel (e.g. `foo`).
2. Add a bot account (e.g. `rocket.bot`) to the channel.
3. Create an incoming webhook.
    * **Enabled** checked
    * **Post to Channel**: `#foo`
    * **Post as**: `rocket.bot`
    * No custom script
4. Save the webhook and copy the webhook URL.
5. Send a message to the webhook URL:
```shell
$ curl -X POST \
    -H 'Content-Type: application/json' \
    --data '{"attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","fields":[{"title":null,"value":null,"short":true}]}]}' \
    <WEBHOOK_URL>
```
6. Back to the Rocket.Chat app and go to the `foo` channel.
7. The Rocket.Chat app shows blank window.

**Expected behavior**
A channel window with some messages and the channel/user list on the left side as normal.

**Screenshots**
![blank-window](https://user-images.githubusercontent.com/2278214/151154101-db3a473b-5fac-4a10-bbbb-56566048312c.jpg)

**Additional context**
I guess the `fields` array in the message payload caused the blank page. But I didn't received any error message.
Everything is OK if I remove the `fields` array from the JSON string.

**Possible solution**
To get rid of the blank page. Please right click on the server icon and click "**Reload server**".
Or check the "**Collapse Embedded Media by Default**" option in account preferences.
![workaround-option](https://user-images.githubusercontent.com/2278214/151152704-842d4846-7f72-4108-b2ae-e5e2a6dfdd9e.png)

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Comment by gundamew** [comment]
![2022-08-05_11-28-28](https://user-images.githubusercontent.com/2278214/182995442-8df4b694-eeea-45db-b305-5a083b91c360.png)

Now there will be an error message. Thanks for your effort. :pray:
