### ISSUE TITLE
macOS client v3.7.6 is not code signed

### ISSUE THREAD

**Issue by tw-wfreitas** [RocketChat/Rocket.Chat.Electron#2309]
**Describe the bug**
 rocketchat-3.7.6.pkg (macOS client) is not code signed.

Previous versions (such as 3.7.5) were code signed using the following developer certificate:
Developer ID Installer: Rocket.Chat Technologies Corp. (S6UPZG7ZR3)

What operating system and which version? macOS Monterey 12.2
Which version of Rocket.Chat (Server)? N/A
Which version of Rocket.Chat.Electron (Electron/Desktop)?  3.7.6
Is there any setting relevant changed? No.

**To Reproduce**
1. Download `rocketchat-3.7.6.pkg`
2. Open Terminal (or iTerm)
3. Run: `pkgutil --check-signature ~/Downloads/rocketchat-3.7.6.pkg`

**Expected behavior**
If the package was signed you'd see the developer's code signing certificate.

**Screenshots**
![image](https://user-images.githubusercontent.com/84393533/152012564-b7b738c3-3bf5-4c73-b835-dd6fcaa0fed8.png)

**Additional context**
We use an automated pipeline to import new versions of software for software deployment, as part of this we check the package code signing certificate, due to the latest package not being signed, the import fails every day. This is likely also happening at other companies.

**Comment by BenGrenoble** [comment]
Same thing with the snap package on Ubuntu 20.04:

![image](https://user-images.githubusercontent.com/59471182/152191051-53e2b0b3-28ef-486a-8d8a-3ecae58105cd.png)

**Comment by jeanfbrito** [comment]
We are investigating what happened in this last release. This was not
intended to happen.

Em qua, 2 de fev de 2022 13:06, Ben ***@***.***> escreveu:

**Comment by jeanfbrito** [comment]
Hello @tw-wfreitas and @BenGrenoble 
We had a certificate expired and that was giving this problem.
Release 3.7.7 that is out today has this problem fixed. 
Please confirm if the issue is solved.

**Comment by BenGrenoble** [comment]
> Hello @tw-wfreitas and @BenGrenoble We had a certificate expired and that was giving this problem. Release 3.7.7 that is out today has this problem fixed. Please confirm if the issue is solved.
Hi,

It seems ok on Ubuntu 20.04 using snap. 

Thanks

**Comment by tw-wfreitas** [comment]
Yup, working here as well for macOS versions. Thanks @jeanfbrito!
