### ISSUE TITLE
Feature: filter/sorting of Users list under Administration panel

### ISSUE THREAD

**Issue by chovy** [RocketChat/Rocket.Chat.Electron#231]
I manually approve users and its a bit cumbersome that I can't sort by account creation date.
A filter would be ideal if I could just filter the list by accounts that are pending "activation".

**Comment by gdelavald** [comment]
Closing this as this is not related to Electron. Please check the [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) repository for more information.
