### ISSUE TITLE
2 Rocketchat accounts 

### ISSUE THREAD

**Issue by Amitisp** [RocketChat/Rocket.Chat.Electron#2312]
Hello, I have 2 accounts in Rocketchat and I only need the one that is linked with email amitis.partovi@freshworks.club - All my previous messages and texts are with the mentioned account. However, I am stuck in the account that is linked to amitis.partovi@gov.bc.ca which I do not use. Please help. 

## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by jeanfbrito** [comment]
Hello @Amitisp this kind of stuff is the server manager that will need to help you. What server are you talking about? open.rocket.chat?

**Comment by Amitisp** [comment]
@jeanfbrito I am not sure which server. I access the tool via web https://chat.developer.gov.bc.ca/home

**Comment by jeanfbrito** [comment]
> @jeanfbrito I am not sure which server. I access the tool via web https://chat.developer.gov.bc.ca/home

You will need to talk with the administrators of the server. Only them can change users and stuff like that.
https://developer.gov.bc.ca/
