### ISSUE TITLE
Desktop client 1.3.1 new channels font size

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat.Electron#232]
## My Setup

- **My OS name and version**: Windows 10
- **My current app version**: Desktop client 1.3.1

- [ X] I have tested with the latest application version
- [ X] I can simulate the issue easily
## Description

When you add new Channel, as example "MyOfficePublic", the channel is added without Caps and it looks "myofficepublic". So, only admin can rename channel after that with correct Caps font size.

**Comment by alexbrazier** [comment]
It is not possible to use capital letters in a channel name. If you want to request this feature please open an issue in the [main repository](https://github.com/RocketChat/Rocket.Chat/issues) as the electron app is not responsible for channel names.
