### ISSUE TITLE
BigBlueButton can't share screen

### ISSUE THREAD

**Issue by Karting06** [RocketChat/Rocket.Chat.Electron#2324]
**Describe the bug**
It's impossible to share the screen when using Electron (enabling screensharing).

What operating system and which version? Windows 10
Which version of Rocket.Chat (Server)? 4.4.2
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.7.8
Is there any setting relevant changed? No

**To Reproduce**
1. Join a BigBlueButton Meeting or start a new one
2. Try to share your screen

**Expected behavior**
Screensharing works

**Screenshots**
Error shown on BigBlueButton:
![2022-02-25 23_31_39-BBB](https://user-images.githubusercontent.com/1096435/155812970-5e96e317-b2c4-4242-931a-f4cbf3feccc0.png)

**Additional context**
/

**Comment by jeanfbrito** [comment]
This didn't happen on version 3.7.7?
If you change to use the browser instead of the application window in settings, it works?

**Comment by Karting06** [comment]
Hi,
It never worked for me on Electron. I tested it with 3.1.1 an hour ago, didn't work either.
In a browser, it works (but not with Firefox).

Thanks for looking into it,

**Comment by jeanfbrito** [comment]
> Hi, It never worked for me on Electron. I tested it with 3.1.1 an hour ago, didn't work either. In a browser, it works (but not with Firefox).
> 
> Thanks for looking into it,

Ok, that information helps a lot. I thought that the PR that you said about it has done this.
I will take a look at this. Thanks for reporting.

**Comment by Karting06** [comment]
Ah, no sorry.
I just thought that because it get worked on Jitsi, it would maybe work on BigBlueButton. But it didn't ;)

**Comment by jeanfbrito** [comment]
> Ah, no sorry. I just thought that because it get worked on Jitsi, it would maybe work on BigBlueButton. But it didn't ;)

No problem. I didn't know that BBB has this problem. See if there is a way to make it work inside the application window like Jitsi.

**Comment by fcecagno** [comment]
Related to https://github.com/electron/electron/issues/4432

**Comment by jeanfbrito** [comment]
Please test with Rocket.chat 5.2 version that will be available soon. With version 5.0 we introduced the Video Conference that changed all the way that we handle video chat.

**Comment by Karting06** [comment]
Hello,

I tried today with Rocket.Chat 5.2 and Rocket.Chat.Electron vers 3.8.12 and I have the same error.
