### ISSUE TITLE
On notification click the window not open on maximized state if it was on it.

### ISSUE THREAD

**Issue by jestrmn** [RocketChat/Rocket.Chat.Electron#2330]
Issue with the notification popup in version 3.7.x. When the OS notification appears and Rocket.Chat is not in focus, and the user clicks on the popup, the focus switches to Rocket.Chat and the window becomes windowed instead of staying in the maximized state it was in.

What operating system and which version? Windows 10 21h2
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.7.8 This last worked as expected in 3.0.7 from what I can tell in testing.
Is there any setting relevant changed? No.

**To Reproduce**
1. Have Rocket.Chat in a maximized view and minimize it to the taskbar.
2. Wait for notification from OS that you have a message when Rocket.Chat is minimized.
3. Click on the popup.
4. Focus switches to Rocket.Chat and the window is now windowed instead of maximized.

**Expected behavior**
When focus switches, the window should move to the front maximized if that's the way the user has their app setup.

**Comment by mben42** [comment]
Can confirm this issue happens in version 3.7.9

**Comment by jeanfbrito** [comment]
Thanks for reporting. We already know about this and will take a look in the window states persistence. Seems like a problem with the maximized/fullscreen state.

**Comment by mben42** [comment]
Hi @jeanfbrito. It works, thank you!
