### ISSUE TITLE
Not able to build the client on Linux

### ISSUE THREAD

**Issue by kshitij86** [RocketChat/Rocket.Chat.Electron#2336]
**Describe the bug**
The client application cannot be built using the instructions mentioned in the README.

What operating system and which version? Manjaro 5.15.25-1
Which version of Rocket.Chat (Server)? NA
Which version of Rocket.Chat.Electron (Electron/Desktop)? Latest 
Is there any setting relevant changed? NA

**To Reproduce**
1. Clone repo
2. cd into folder
3. yarn
4. yarn start

**Expected behavior**
Open Rocket.Chat desktop client 

**Screenshots**
![image](https://user-images.githubusercontent.com/26821140/158061427-eeaaae9d-c728-4c38-837a-89bafdc349e4.png)

**Comment by kassemz** [comment]
Getting the same error on Windows 10 as well.

**Comment by jeanfbrito** [comment]
This start happening on Electron 17, dont know why. But you could try fix it too.
