### ISSUE TITLE
Javascript Error os is not defined

### ISSUE THREAD

**Issue by Akiren** [RocketChat/Rocket.Chat.Electron#234]
Windows 10
Latest Rocket Chat Electron

I clone a brand new instance of Rocket.Chat.Electron
I run NPM install .... get no errors
I run NPM start .... I get Uncaught Exception: ReferenceError: os is not defined  \build\background.js:222:5

I can even run NPM run release... it will deploy an executable... I can install it. When I try to run the application i get the same exact error. I havent made a single change and I am running the exact instructions from the homepage besides of course the rocket-chat-electron repo.... 

I am also getting AppData\Roaming\Rocket.Chat+ Dev\certificate.json' cannot be found. Has anyone else experienced this?

> git clone https://github.com/szwacz/electron-boilerplate.git
> cd electron-boilerplate
> npm install
> npm start
> ... and boom! You have running desktop application on your screen.

**Comment by jtbrush56** [comment]
I can confirm this bug.

**Comment by Merryfurr** [comment]
This is caused by the "toaster check" to see if the user is running on an OS that doesn't support notifications. A temporary fix is to remove line 39 to 47 in ./app/background.js (Remember to back it up!) After doing this, notifications will not work on Windows 7 due to toaster being disabled.

**Comment by engelgabriel** [comment]
Fixed on the latest versions.
