### ISSUE TITLE
When trying to connect with the Rocket.Chat windows client, it is not possible to select the required certificate from the list

### ISSUE THREAD

**Issue by alarkip** [RocketChat/Rocket.Chat.Electron#2340]
**My Setup**
Windows 10
Rocket.Chat.Electron 3.7.8
Rocket.Chat Server 4.5.1
The Rocket.Chat server is behind another server (Nginx + OpenSSL) that provides TLS authentication with a client certificate

1. Start connecting to the server and enter the address of the Nginx server
2. A window appears with a list of certificates installed on the system
3. Select the desired certificate, click Select

The window with the list of certificates closes, but the connection to the server does not occur, the selected certificate is not transferred to the server.
But if there is only one certificate installed in the system, then this certificate is applied automatically and the Rocket.Chat client works fine.
This happens only with the windows client, in the android client and web client the certificate is applied correctly.

![rcktcht](https://user-images.githubusercontent.com/101806572/158811172-60997739-7cf7-446f-a165-93abf4527864.png)

**Comment by jeanfbrito** [comment]
Hello @alarkip, I will need help to create a server like yours to reproduce the issue and fix it. Can you explain more about the server configurations?

**Comment by alarkip** [comment]
Hello @jeanfbrito.
The proxy server can be configured following this manual.
https://www.ssltrust.com.au/help/setup-guides/client-certificate-authentication
Or I can create a test stand and grant access.

**Comment by jeanfbrito** [comment]
@alarkip I will try to reproduce locally the issue, but a test stand with access would help to accelerate the fix. You can find me in the open.rocket.chat. My user is jean.brito

**Comment by jeanfbrito** [comment]
Hey @alarkip! Any news? I didnt have time yet to create a server using certificates, but it's gone be one of the next thing that I will do.

**Comment by alarkip** [comment]
Hey @jeanfbrito. I've been busy too, I'll try to deploy a stand this week

**Comment by alarkip** [comment]
Hello @jeanfbrito, I wrote the details in open.rocket.chat
