### ISSUE TITLE
Image Video Preview on Windows app

### ISSUE THREAD

**Issue by furuzi84** [RocketChat/Rocket.Chat.Electron#2344]
Dear all,
we had seen that from 3.7.0 version of windows application all preview message not see

**Comment by ankar84** [comment]
> Dear all, we had seen that from 3.7.0 version of windows application all preview message not see

Try recent 3.7.9 version

**Comment by jeanfbrito** [comment]
Please try the newest version, but it seems like a Rocket.chat issue and not an issue on the desktop app.
Please provide more information about it.

**Comment by jeanfbrito** [comment]
I cant understand what exactly is the message preview that you are talking about. The images don't show on the chat?
Please give some screenshot samples.

**Comment by furuzi84** [comment]
See the attached file, when we sent on windows desktop all image or video not see preview.

DZ

**Comment by jeanfbrito** [comment]
> See the attached file, when we sent on windows desktop all image or video not see preview. DZ

I think that attached files are not showed here. I tried sending image from windows and from mac and seeing in the windows desktop application and all work. I will need more information to help to fix it.
![image](https://user-images.githubusercontent.com/1177482/159061539-189c76df-8a5e-4853-bff7-502f53c1136b.png)

**Comment by jeanfbrito** [comment]
@furuzi84 we need more info about your problem. Please provide some screenshots.
