### ISSUE TITLE
[Bug] `Minimize on close` feature don't work

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#2345]
**Describe the bug**
`Minimize on close` feature, that was introduced in version 3.7.9 don't work.
It makes no difference if that feature enabled or disabled in `Windows - Settings` - application always minimizing to system tray.

What operating system and which version? Windows 10 21H2
Which version of Rocket.Chat (Server)? 4.3.3
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.7.9
Is there any setting relevant changed? `Minimize on close` feature

**To Reproduce**
1. Go to `Windows - Settings` and disable `Minimize on close` option
2. Click on X sign in right top corner of application (Close button)
3. Application should be closed, but it minimizing to system tray

**Expected behavior**
If feature `Minimize on close` enabled (default) - app should minimize to tray on clicking X close button
If feature `Minimize on close` disabled  - app should quit on clicking X close button

**Screenshots**
No

**Additional context**
Did try to restart app after change of that setting

**Comment by jeanfbrito** [comment]
It will only make difference of the trayIcon is disabled. If trayIcon is enabled the behavior will always be minimize to tray.
But if not, then that setting will do the difference.
Before, even with the trayIcon inactivated it will minimize.

**Comment by ankar84** [comment]
> It will only make difference of the trayIcon is disabled. If trayIcon is enabled the behavior will always be minimize to tray.

Hey, Jean! Thank you for such quick response!
I disabled tray icon in `View - Tray Icon`
Relaunch app
Tested with both `Minimize on close` enabled and disabled - result is the same app is minimized in task bar clicking on both minimize and close buttons.

**Comment by jeanfbrito** [comment]
I missed a thing and was released without it... Now is fixed, will release soon.

**Comment by ankar84** [comment]
Yes, it work perfect in 3.8.0!

**Comment by jeanfbrito** [comment]
![yay-minions](https://user-images.githubusercontent.com/1177482/159192715-bd1367c0-f734-4f0f-ade6-3e4f1e18c9f6.gif)
