### ISSUE TITLE
Channels notification configuration

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat.Electron#235]
## My Setup

Windows 10 64 bit, Rocket.Chat+ V1.3.1

- [x] Checked Item
- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

 Is it possible to configure Channels notification the same as Direct Messages? I mean, if some one in Channel post some new message, other users get the same visual and sound notification (blinking task-bar icon). Because, if I don't use @all tag, no one know, that there are some new message. So, can I configure Channels notification the same as Direct Messages?

**Comment by LXSysadmin** [comment]
In other words, is there possibility to notify desktop user about new message in channel with blinking icon in task bar? 
![image](https://cloud.githubusercontent.com/assets/19779209/18985669/b3a30e20-8701-11e6-9e15-664dedba1d77.png)

**Comment by drasbeck** [comment]
+1 one for the suggestion. An indicator for new channel messages would be very useful.

**Comment by pvalarezo** [comment]
Please your help whit this issue.
And with this I can completely replace skype...

**Comment by LXSysadmin** [comment]
Yes, it would be SUPERB!

**Comment by seth-c-stenzel** [comment]
Yeah this is a really important feature for my team. So that either a desktop notice, or a sound is played when there is a new channel message on any of your joined channel. That way if there is pressing information for a team, everyone is notified even if they are on multiple teams / channels.

**Comment by rodrigok** [comment]
The desktop notifications implemented on version 2.2.0 solves this problem?

**Comment by LXSysadmin** [comment]
How can i configure in version 2.2.0 to get a notification in public channel? Like Skype group. Many users want to taskbar icon start blinking when someone writes in public channel. Yes, i can use @all tag, but taskbar icon is not blinking anyway. In other words, can notifications be the same as in private chat? When i write in private chat, taskbar icon change to orange, so, i want to get the same effect if some write in public channel. Do you get my idea? :)

**Comment by mbraun01** [comment]
2.2.0 has not resolved the problem of group channels not flashing in the taskbar.  Is anybody working on this?

**Comment by alexbrazier** [comment]
You can configure the notifications for channels in the notifications settings on the right hand side, which should alert you when you receive a message.

There is also a pull request [Rocket.Chat#4339](RocketChat/Rocket.Chat#4339) that will allow you to set a default for all channels.

@LXSysadmin @mbraun01 Do notifications work when you enable them for a channel?

**Comment by LongShanksBraveHeartKiller** [comment]
This is exactly the feature we are looking for(browser icon flashing would be ideal so we don't have to roll client). I am somewhat confused about the responses given in this thread. Can somone confirm this is working? Thanks

![image](https://cloud.githubusercontent.com/assets/17896650/23473649/f659e87a-fe7e-11e6-839a-2fe9b704360b.png)

**Comment by monspid** [comment]
@LongShanksBraveHeartKiller it blinks when it is direct message or you are tagged in room.

**Comment by alexbrazier** [comment]
I'm closing this issue as flash notifications are working in the latest version, and you can change your settings to enable notifications for channels/groups. Notification settings are related to the main application rather than the desktop app, and there a pull request to enable notifications for all messages RocketChat/Rocket.Chat#433

**Comment by LittleNo** [comment]
I'm running v 2.4.2 and have the same issue (red flash of task bar icon works for direct messages but not for channels / rooms). Is this a new bug? or am I missing a setting?
