### ISSUE TITLE
Feature Request - Add "Save As Origninal Image' 

### ISSUE THREAD

**Issue by lawipac** [RocketChat/Rocket.Chat.Electron#2354]
When saving an Image in Desktop App, it saves Thumbnails.    It's always better to save the original resolution instead of the thumb-nail version. 

I understand that there is a download button, but it's kinda hard to spot for new users would it be good if We add a context menu item "Save As Original..."   when right-click and save an Image?

**Comment by Palanikannan1437** [comment]
> Hi Thank you for your prompt reply, I think save as thumbnail is also a good solution.
> 
> Cos sometimes we need both thumbnails and originals.
> 
> By click the thumbnail we can get enlarged image and save as give us the original.
> 
> It offers user flexibilitiesz

Hey, could you please try updating to the latest version i.e. 3.8.8 and try this again?

This is exactly how it works now,
- By right clicking on the thumbnail and clicking on "save as image", the thumbnail resolution is downloaded
- By enlarging the image and then right clicking on the image and clicking on "save as image", the original resolution is downloaded

https://user-images.githubusercontent.com/73993394/187064523-a791ee19-9a6e-4728-8d69-0d9a4611f9da.mov

If this was the intended behaviour that you wanted, please consider closing this issue @lawipac 😄

**Comment by lawipac** [comment]
Hi @Palanikannan1437 

Thank you for your excellent screencast.

**Comment by Palanikannan1437** [comment]
> Hi @Palanikannan1437 
> 
> Thank you for your excellent screencast.

You're welcome!😃
