### ISSUE TITLE
Overlay system for games

### ISSUE THREAD

**Issue by JohnnyKing94** [RocketChat/Rocket.Chat.Electron#237]
Is it possible to add an overlay system for the games (like Discord or Overwolf for TS3)? It would be a great feature request and it will provide a great consensus among gamers... An overlay system which will give you the chance to chat and interact with the chatroom you're currently on it etc... At least this very basic request... then if you have more ideas, be my guest...

**Comment by JohnnyKing94** [comment]
Is it been considered at least? 😄

**Comment by gdelavald** [comment]
Thank you for the suggestion. Currently we have no plans for this feature so I'll close the issue.

**Comment by JohnnyKing94** [comment]
Indeed it was a suggestion... no need to close it and be forgotten... it should have been stayed open... that's a shame!

**Comment by gdelavald** [comment]
My bad, I'll leave it open then :)

**Comment by Sparkfiber** [comment]
This would be a phenomenal feature - as JohnnyKing94 mentioned Overwolf could be used if not part of the actual rocketchat desktop app. They have overlays for other chat applications http://developers.overwolf.com/documentation/sdk/overwolf/
