### ISSUE TITLE
codesign problems

### ISSUE THREAD

**Issue by Akiren** [RocketChat/Rocket.Chat.Electron#239]
## My Setup

Mac OSX
## Description

Has anyone successfully signed an app for distribution without external users getting the "Unidentified Developer" notification upon signing? Using the default release codesign.

Even using the --deep flag the cosign doesnt appear to work correctly. I have downloaded and used numerous certs from apple dev dashboard.

**Comment by engelgabriel** [comment]
Fixed on version 2.1.0 using electron-rebuild
