### ISSUE TITLE
Dock notification counter doesn't show the number of unread message in a thread

### ISSUE THREAD

**Issue by InjustFr** [RocketChat/Rocket.Chat.Electron#2390]
**Describe the bug**
When someone responds in a thread, the badge counter on the Rocket.Chat dock icon display a dot instead of the number of unread message. I can see next to the name of the person messaging me the counter of unread message being increased properly so I'm guessing it's an issue with the Electron app itself. The counter works fine if messages are sent in the "normal" conversation thread. It might be related to this https://github.com/RocketChat/Rocket.Chat.Electron/issues/1395 but as it's on another platform

Operating system: MacOs 12.3.1
Version of Rocket.Chat (Server): 4.6.2
Version of Rocket.Chat.Electron (Electron/Desktop): 3.8.4

1. Send a direct message from personA to personB. 
2. Notice that the counter of personB works fine
3. Send a message in the thread of the previous message.
4. Notice that the counter of personB still says 1 instead of 2. If you had read the previous message, it would display a dot instead of 1.
5. Notice that the number of unread message in the sidebar is displaying the correct number

**Expected behavior**
The number of unread messages should increase, regardless of the origin of the notification (thread or not)

**Comment by jeanfbrito** [comment]
The counter only shows the DM or mentions count. Unread messages on other channels are not counted because you would get a huge number on crowded channels.
We only count the direct messages and when you was mentioned on the badge.

**Comment by InjustFr** [comment]
Hi

Maybe my previous message was unclear
I'm talking about messages in a thread in a DM, not in group chats

It would be very handy to have these increase the counter and I'm certain the number would stay reasonable, unless you're having hundreds of parallel DM conversations
