### ISSUE TITLE
Jitsi Screenshare support

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#240]
Brave browser is built using electron they have figured out how to implement extensions - https://github.com/brave/browser-laptop/blob/master/app/common/actions/extensionActions.js

We need to be able to find out from the rocket.chat instance what extension jitsi will be calling for.  Then register an extension handler for it.  

The jitsi extension code is super simple: https://github.com/jitsi/jidesha/blob/master/chrome/background.js

We would need to modify that to call electrons desktop-capture api instead of chrome's: https://github.com/electron/electron/blob/master/docs/api/desktop-capturer.md

**Comment by frdmn** [comment]
My coworkers noticed the same: +1 from us :)

**Comment by didierm** [comment]
It seems I am misinterpreting https://github.com/RocketChat/Rocket.Chat/issues/3919 .

Does this issue #240 imply that currently, Screenshare is only possible with Firefox or Chrome, and not with the native Rocket.Chat client ?

**Comment by seriouz** [comment]
@didierm yes you are correct. Only FF and Chrome do the screenshare and WebRTC stuff.

**Comment by bluenevus** [comment]
+1  We love rocket chat, installed the client on all desktops, hosted our own rocket chat server and jitsi and have everything working like a dream.  However, only FF and Chrome will screenshare.  The client does not.  It would be a amazing to have the client do screensharing.

**Comment by jszaszvari** [comment]
@geekgonecrazy  Here's a simple working example of screensharing working in Electron with JITSI 

https://github.com/jitsi/jitsi-meet-electron/

**Comment by geekgonecrazy** [comment]
Wow!  This looks like it might actually be pretty straight forward.

https://github.com/jitsi/jitsi-meet-electron/blob/master/windows/jitsi-meet/render.js#L75
and then
https://github.com/jitsi/jitsi-meet-electron/blob/master/modules/screensharing/index.js#L29

Looks dead simple, if I get that chance to try this out i'll give this a shot.  Unless someone else beats me to it.  :grin:

**Comment by TomaszKorwel** [comment]
We are in the process of evaluating rocket.chat to implement in our company, but the inability to screenshare from the desktop client may break things. is there any way I can help get that implemented soon?

**Comment by gdelavald** [comment]
@TomaszKorwel Hey, we have a PR to fix some the issues but this was delayed a bit due to a change that is needed in the server as well. This is in the backlog and should be worked on in the next month, so you can expect this to be released in version 2.11.0 that should be released in November.

**Comment by TomaszKorwel** [comment]
Any word on when 2.11 will be released?

**Comment by saroff** [comment]
Any news on this?

**Comment by arteislt** [comment]
Hi guys! I've installed 2.11 and as I can see, screensharing still doesn't work. How's the roadmap for this feature?
