### ISSUE TITLE
Disable automatic updates for msi installer

### ISSUE THREAD

**Issue by ultego** [RocketChat/Rocket.Chat.Electron#2402]
## My Setup

- Operating System: Windows 10
- App Version: 3.8.1
- Installation type: msi via GPO

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description

I deploy the RocketChat application via GPO (msi) and I would like to disable automatic updates of the application, because I want to control application version centrally.

### Current Behavior

RocketChat checks for updates and asks to update, if an update is available. Users cannot start an update due to limited permissions.

### Expected Behavior

It is possible to create custom transformation file with property autoupdate = 0.

**Comment by ankar84** [comment]
@ultego just use [overridden-settings](https://github.com/RocketChat/Rocket.Chat.Electron#overridden-settings) `"isUpdatingEnabled": false,` and `"doCheckForUpdatesOnStartup": false,`

**Comment by jeanfbrito** [comment]
@ultego we already have the option to disable auto update, did you already tested it?
https://github.com/RocketChat/Rocket.Chat.Electron#windows-options

I will close the issue, but any problem you can reply here and we open it again, right?
