### ISSUE TITLE
Windows Terminal Server 2019 - only one user can start rocketchat client

### ISSUE THREAD

**Issue by maxik18** [RocketChat/Rocket.Chat.Electron#2404]
From 3.8.3 only one user can run Rocketchat client on remote desktop. There is no errors in event logs.

Windows Terminal Server 2016-19
Rocketchat server 4.6.2

**Comment by compdemon** [comment]
Terminal Server 2008-2012 - the same.
RocketChat Server 3.18.3 (just for infromation, issue most likely on client side)

RocketChat client installed for all users in Program Files.
