### ISSUE TITLE
Image uploads not showing

### ISSUE THREAD

**Issue by jsumners** [RocketChat/Rocket.Chat.Electron#241]
## My Setup
- OS 10.11.6
- 1.3.1 (15)
- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

If someone uploads an image (png and jpg tested) then they do not show up in the client. However, if I open the website, that same image upload shows correctly. Clicking on the download icon in the client simply opens a blank web page in the default browser.

My install is configured to authenticate users against Active Directory.
#### Current Behavior

![2016-10-11_08-34-36](https://cloud.githubusercontent.com/assets/321201/19270376/b649a4b0-8f8d-11e6-9ad2-d2e3cd66ec8c.png)
#### Expected Behavior

![2016-10-11_08-35-16](https://cloud.githubusercontent.com/assets/321201/19270381/c21d6d62-8f8d-11e6-9607-277cd5f130eb.png)

**Comment by TheReal1604** [comment]
Same with integrated user account management in use.

**Comment by brandborg** [comment]
Still a problem with os 10.12 and client 1.3.1 (15)
We don't get a blank page on the server though. We get an error message that says "<fileurl> image can not be displayed because it contains errors"

**Comment by clobrano** [comment]
Same problem with:
- server installed as a snap
- browser client

**Comment by admin-crowd-iugo** [comment]
same here. 0.46 and 1.3.1 client and browser. happens occasionally and clearing cache seems to fix it temporarily.

**Comment by engelgabriel** [comment]
This is fixed with version Server 0.49 and Desktop Client 2.1.0
