### ISSUE TITLE
Release 3.8.6 does not finish starting after update

### ISSUE THREAD

**Issue by ajmaske** [RocketChat/Rocket.Chat.Electron#2410]
**Describe the bug**
After applying the latest release v3.8.6 Rocket.Chat will not completely start up, it's in the task list but never comes up 100%.  Tried rebooting and still the same.  I ended up having to completely remove RC and reinstall the prior version, v3.8.5.

What operating system and which version?
Windows 10 

Which version of Rocket.Chat (Server)?
Not sure, I don't have access to the server.

Which version of Rocket.Chat.Electron (Electron/Desktop)?
Latest release v3.8.6

Is there any setting relevant changed?
No.

**To Reproduce**
After applying the new release, v3.8.6, RC failed to completely start, it shows in the task list and after waiting a few minutes nothing, that's as far as it got.

**Expected behavior**
As with all prior releases I expected the app to fully startup.

**Screenshots**
n/a.

**Additional context**

**Comment by jeanfbrito** [comment]
Hey @ajmaske please try to clean the cache if don't work, try to clear the storage.
Right click on the server icon on the sidebar:
![image](https://user-images.githubusercontent.com/1177482/166487167-bcf69835-8b9a-4499-9b16-cb2c0cefde79.png)

**Comment by ajmaske** [comment]
Just tried both (Clear Cache & Clear Storage Data) from v3.8.5 and then attempted the update and the same behavior, it sits there in the task list and never finishes loading.

I tried one more time.  However, this time I completely uninstalled RC and then installed it (v3.8.6) from scratch using the same rocketchat-3.8.6-win-x64.msi file, this seemed to work.  So it appears the issue is updating to v3.8.6 on top of a pre-existing install (in this case v3.8.5) is where it fails to load.

**Comment by jeanfbrito** [comment]
Its very weird, because if I test exactly like you said, it works for me. You are using an administrator user?

**Comment by ajmaske** [comment]
No, I'm just a normal user.  By the way, this same behavior occurred on two separate PC's.

**Comment by jeanfbrito** [comment]
The installation was done by you using this user? Seems like a problem in the update when you are not the administrator.

**Comment by ajmaske** [comment]
I just duplicated the exact thing on the 2nd windows 10 PC. v3.8.6 is now installed **and** running but only after completely uninstalling the prior version and installing v3.8.6 fresh.

**Comment by ajmaske** [comment]
> The installation was done by you using this user? Seems like a problem in the update when you are not the administrator.

Yes, myself.

**Comment by ajmaske** [comment]
To be clear, I'm not a Rocket chat Admin, but I am an admin on both PCs.

**Comment by jeanfbrito** [comment]
That was the administrator that I was asking about. 
Then, after installing 3.8.6 it stopped with the problems?
The update from 3.8.5 to 3.8.6 that was not working properly?

**Comment by ajmaske** [comment]
> Then, after installing 3.8.6 it stopped with the problems? 
Once I completely removed rocket chat and installed it (3.8.6) from scratch (clean) then it loaded completely.

> The update from 3.8.5 to 3.8.6 that was not working properly?
Yes, when I tried installing 3.8.6 as an update on top of the existing 3.8.5 is when the problem happened, that is, the install happened but when starting it failed to completely load and just hung in the task list.

**Comment by PelleHanses** [comment]
I have tha same problem. I use to install the new MSI package and never had problems but with 3.8.6 we have the same problems on all computers.

**Comment by jeanfbrito** [comment]
Even after reboot the problem persists? I'm thinking that the problem is a old process open on the machine.

**Comment by ajmaske** [comment]
For myself, even after checking the task list and/or rebooting.

**Comment by jeanfbrito** [comment]
Any news @ajmaske ?

**Comment by ajmaske** [comment]
Going to close this, I got the update installed. However, I had to remove RC and do a clean install instead of performing an update.
