### ISSUE TITLE
Rocket.Chat 3.8.6 startup failed

### ISSUE THREAD

**Issue by cospeedster** [RocketChat/Rocket.Chat.Electron#2417]
**Describe the bug**

What operating system and which version? Windows 10
Which version of Rocket.Chat (Server)? don't know (self hosted at company)
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.8.6 Desktop
Is there any setting relevant changed? no

**To Reproduce**
1. start Rocket.Chat

**Expected behavior**
Rocket.Chat starting and opens the window.

**Screenshots**
![image](https://user-images.githubusercontent.com/52749645/168980856-f76d7563-b45b-4ebd-8a0f-4edc97c468d4.png)

**Additional context**
On other devices it still works fine.
I've found no `config.json` like mentioned in #2266.

**Comment by cospeedster** [comment]
Additional Information: Reinstalling has no effect

**Comment by ankar84** [comment]
I have at least one computer with same issue for now.

**Comment by cospeedster** [comment]
@jeanfbrito Great News! Can‘t wait for the next release :)

**Comment by jeanfbrito** [comment]
@cospeedster the fix didnt solved your problem then, but I have another fix that will be released this week. For now, you can go to `~\Users\<username>\AppData\Roaming\Rocket.Chat\` and delete the `config.json` to make it stop crashing.
Or you can open the `config.json` and find the `bounds` key and edit the `x` that has a `-0` number. This is the problem probably.

**Comment by cospeedster** [comment]
Thank you so much @jeanfbrito ! It worked well :-)

**Comment by jeanfbrito** [comment]
It will be solved definitely on the next release. It's a problem with
infinity numbers. The fix is already done and will be released soon

Em ter., 21 de jun. de 2022 02:36, cospeedster ***@***.***>
escreveu:
