### ISSUE TITLE
Incorrect aspect ratio of images

### ISSUE THREAD

**Issue by D34DC3N73R** [RocketChat/Rocket.Chat.Electron#2426]
**Describe the bug**
The aspect ratio is not displayed correctly on desktop apps for images and gifs.

What operating system and which version?
Window 11
Which version of Rocket.Chat (Server)?
4.6.3
Which version of Rocket.Chat.Electron (Electron/Desktop)?
RocketChat client v 3.8.6
Is there any setting relevant changed?
no

**To Reproduce**
1. use tenor or giphy to post a gif
2. observe incorrect aspect ratio

**Expected behavior**
The aspect ratio of the posted image should be adhered to.

**Screenshots**
![image](https://user-images.githubusercontent.com/9123670/171805008-3ea3b3a5-7a85-4c26-bb9b-669bdaf52dde.png)

![image](https://user-images.githubusercontent.com/9123670/171805044-22c69488-caf9-467e-8f88-7795a4185b81.png)

![156946745-99359ca4-dc38-40a2-9ce0-5c1b017f057e](https://user-images.githubusercontent.com/9123670/171805199-acf8fec8-ff12-464e-9f19-44b70fae93cb.gif)

**Additional context**
Reported in rocketchat/rocketchat https://github.com/RocketChat/Rocket.Chat/issues/20546

**Comment by jeanfbrito** [comment]
@D34DC3N73R this is duplicated from the rocketchat/rocketchat repo. Is a issue from the web client, not the desktop layer. I will de closing and we can track the issue using that issue, ok?

**Comment by D34DC3N73R** [comment]
@jeanfbrito I know this issue doesn't happen with mobile clients so I thought it may be able to be fixed for desktop clients.

**Comment by jeanfbrito** [comment]
@D34DC3N73R the desktop is just a layer of Electron and loads the webclient. In the mobile the client is totally separated, another code, the application is totally redone.

**Comment by D34DC3N73R** [comment]
Ok, thanks for the info.
