### ISSUE TITLE
Windows Installation - support silent mode

### ISSUE THREAD

**Issue by Deepakkothandan** [RocketChat/Rocket.Chat.Electron#243]
## Description
Add ability to perform silent installation on Windows machines with a default configuration, so the installation can be automated through scripts.

Optionally, the ability to override the default configs, would be nice to have

#### Current Behavior
Executing the downloaded executable file, opens the windows and waits for user Action

#### Expected Behavior

For example, executing the following command on powershell / cmd should install rocket chat silently in the background, without waiting for user input

 .\rocketchat.exe /quiet

**Comment by graywolf336** [comment]
Currently possible via https://github.com/RocketChat/Rocket.Chat.Electron/pull/208
