### ISSUE TITLE
Recover deleted Channel

### ISSUE THREAD

**Issue by TesterKAY** [RocketChat/Rocket.Chat.Electron#2431]
Hi! 

Working on Version 3.8.7 and accidentally deleted a channel. Anyway to recover it?

Thank you!

## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by jeanfbrito** [comment]
@TesterKAY hello, you will need to talk with the server administrator. Here we cant help you about this.
