### ISSUE TITLE
[Feature request] Notification on download complete

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#2435]
**Describe the bug**
Now, when user download some file - there is no any notification.
I would be so nice if some notification pop-up with choices like `open file` and `open folder` appeared on download finish

**To Reproduce**
1. Download file
2. Download finished
3. User don't know about that and need to open Downloads windows to check
4. Pop up notification about finished download would be nice.

**Expected behavior**
No indication of download is finished

**Screenshots**
User need to open downloads to get status
![image](https://user-images.githubusercontent.com/4023037/174226464-2f342807-6b50-4e1e-8244-f6bb4261f3e5.png)

**Additional context**
WhatsApp and Telegram have similar feature

**Comment by MrPoint1400** [comment]
+1

**Comment by ankar84** [comment]
Tested 3.8.8 - works perfect!
