### ISSUE TITLE
Cannot Login to Two Severs with Different Google Accounts

### ISSUE THREAD

**Issue by cpitman** [RocketChat/Rocket.Chat.Electron#244]
## My Setup

Windows 7
RocketChat+ 1.3.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

1. Login to the first server using a google account
2. Attempt to add a single server, using a different google account
3. When the google sign in pop up appears, attempt to add a second google account
#### Current Behavior

User is redirected to a google account selection page, but it is loaded in the default browser. After selecting an account, the browser is the redirected to an empty page with the token in the url. There is no way to then get this token back to RocketChat.
#### Expected Behavior

Account selection appears in RocketChat application, or otherwise redirect form browser communicates with app.

**Comment by tassoevan** [comment]
Does this still holds true?

**Comment by Raboo** [comment]
@tassoevan yes.

- Operating System: MacOS
- App Version: 2.17.9
- Installation type: App Store
- [x] I have tested with the latest version
- [x] I can simulate the issue easily
I get this message

```
Couldn't sign you in

This browser or app may not be secure. Learn more

Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```

<img width="375" alt="Screenshot 2020-04-15 at 11 17 57" src="https://user-images.githubusercontent.com/1148206/79321317-73a85180-7f0b-11ea-97c8-2378b4d68b9d.png">

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
