### ISSUE TITLE
Pressing "Enter" too soon preventing Ctrl+V pic publication

### ISSUE THREAD

**Issue by landergate** [RocketChat/Rocket.Chat.Electron#245]
## My Setup

- **My OS name and version**: Windows 7 Pro x64
- **My current app version**: 1.3.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

Small user experience issue regarding pasting an image from a clipboard right into the Rocket.Chat.

I've got used to press "Enter" right after Ctrl+V to send image. This is working as expected on most messaging clients.
However, if I paste some image and press "Enter" right after that, it would just close popup window and not send anything at all.
#### Current Behavior

You need to wait until "popup appear" fade-in animation would finish (around ~300-800ms?), and only then you can press "Enter" to send your image. Otherwise it would just close and not send anything at all.
#### Expected Behavior

You can press Ctrl+V and then press "Enter", right after your client would show that it got your pic, without needing to wait for popup animation to finish (as it clearly shows that it's already got your picture, while drawing the fade-in animation).

**Comment by Frenjon** [comment]
I've been annoyed by this as well.. Thanks for the workaround @landergate - I'd normally just paste again to retry.

**Comment by Frenjon** [comment]
Still a problem on version 2.4.0

**Comment by graywolf336** [comment]
This is an issue with rocket.chat itself and not limited to electron, as it happens on the web browser. Do you mind recreating this issue over on that repository?

**Comment by Frenjon** [comment]
Searching the Rocket.Chat issues I can see it's already created over there:
https://github.com/RocketChat/Rocket.Chat/issues/3156

Seems to be related to some external plugin..

**Comment by gdelavald** [comment]
Closing this as this is not related to Electron. Please check the [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) repository for more information.
