### ISSUE TITLE
rocketchat-desktop.desktop: ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:188 (ClearErrors): Preexisting GL error 0x00000507 as of ../../third_party/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:256

### ISSUE THREAD

**Issue by mxchist** [RocketChat/Rocket.Chat.Electron#2459]
### Description:
A syslog on client's machine constantly filled with messages like `rocketchat-desktop.desktop[PID]: [PID:0802/112259.573038:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:188 (ClearErrors): Preexisting GL error 0x00000507 as of ../../third_party/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:256`. For example, there is syslog lines counts where `Preexisting GL error` is presenting : 364,739; syslog lines where `Preexisting GL error` is NOT presenting: 25,530. 

### Steps to reproduce:
Not found a special conditions when it goes. Time by time when Rocket.Chat Client is runnig

### Server Setup Information:

- Version of Rocket.Chat Server: 4.7.4
- Operating System: `4.19.0-18-amd64 RocketChat/Rocket.Chat#1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux`
- Deployment Method: k8s
- Number of Running Instances: 11
- DB Replicaset Oplog: oplog Disabled
- NodeJS Version: v14.18.3
- MongoDB Version: 4.4.13

### Client Setup Information

- Desktop App Version: 3.8.7. Installed from Ubuntu repository
- Operating System: `5.15.0-41-generic RocketChat/Rocket.Chat#44~20.04.1-Ubuntu SMP`

### Additional context
There is an apps where the same issue was found and solved already: Chromium and Firefox. Look how the Firefox had adjusted to the NVidia driver requirments: https://forums.developer.nvidia.com/t/prime-offloading-unable-to-run-chrome/81600/8

### Relevant logs:
Logs available from client application only (because issue relates only to client video driver): https://pastebin.com/7G2A2nj3

**Comment by jeanfbrito** [comment]
I think that updating the Electron will solve this. The next release will include the latest chromium.

**Comment by Palanikannan1437** [comment]
> A syslog on client's machine constantly filled with messages like `rocketchat-desktop.desktop[PID]: [PID:0802/112259.573038:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:188 (ClearErrors): Preexisting GL error 0x00000507 as of ../../third_party/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:256`. For example, there is syslog lines counts where `Preexisting GL error` is presenting : 364,739; syslog lines where `Preexisting GL error` is NOT presenting: 25,530.

Hey @mxchist! Could you please try upgrading to the latest version(3.8.8) and let us know if the issue still persists ? 

Since electron has been updated to v19.0.11 in the latest release!

**Comment by mxchist** [comment]
Hmmm... I  looked in syslog a few times for a past three weeks, but I haven't had noticed error 0x00000507 there. A rocketchat client still 3.8.7. I checked the syslog for a last 9 days, but haven't found Preexisting GL error. I suppose that updating client have a no sense at this time because I cannot compare a "before" and "after" condition.

**Comment by jeanfbrito** [comment]
The there is no issue any more @mxchist ?

**Comment by mxchist** [comment]
I see this issue no reproduced even on the same (3.8.7) version.

**Comment by jeanfbrito** [comment]
@mxchist I will close it then. If it happens again, please tell us here to reopen it.
