### ISSUE TITLE
Moving client's window spawning an error

### ISSUE THREAD

**Issue by landergate** [RocketChat/Rocket.Chat.Electron#246]
## My Setup

- **My OS name and version**: Windows 7 Pro x64
- **My current app version**: 1.3.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

Moving Rocket.Chat window anywhere could spawn this error:
![2016-10-14_18-55-35](https://cloud.githubusercontent.com/assets/904839/19398978/d92e496e-9257-11e6-8771-aedb681f8156.png)

It could be related to Windows gestures, like "shake window" (although I have this feature disabled through GPO).
#### Current Behavior

You can't move a window without this error appearing.
#### Expected Behavior

Ability to move client's window without errors appearing.

**Comment by jbeauvois** [comment]
+1

**Comment by jbeauvois** [comment]
when i disable my antivirus the issue do not appear.
I use Kaspersky Endpoint Security 10.2.5.3201(mr3)

**Comment by engelgabriel** [comment]
Can you test this again with version 2.1.0?

**Comment by engelgabriel** [comment]
Please reopen if the problem persist in the new version.
