### ISSUE TITLE
Windows Client third-party login fail show "No matching login attempt found"

### ISSUE THREAD

**Issue by yatounoneko** [RocketChat/Rocket.Chat.Electron#2466]
### Description: 
Windows Client third-party login fail show "No matching login attempt found"

### Steps to reproduce:

1. Input site domain
2. Use any third-party login
3. Show Fail and open third-party login page
![](https://oxo.hk/index.php?explorer/share/file&hash=ab3cS3rI_CFToJQSqBlPGEiBahxP7KGZyZfo4x9QIMn5NTddu3SNw_P5VJeQa-N3upreYQ)
Whether it's Google, Facebook, Github problem the same.
But website or android client is work, no error messages and normal access login.

### Expected behavior: 
Access third-party page success login for windows client

### Actual behavior: 
Access third-party page success login but client fail and tips: "No matching login attempt found"

### Server Setup Information: 

- Version of Rocket.Chat Server: 5.0.2 - 5.0.3 (Problem persist after updated)
- Operating System: Debain 11
- Deployment Method: Rocketchatctl
- Number of Running Instances: 1
- NodeJS Version: 14.19.3 - x64
- MongoDB Version: 5.0.10
- MongoDB Engine: wiredTiger
- Platform: linux
- Process Port: 3000
- Site URL: https://website.com (Nginx SSL reverse proxy)
- ReplicaSet OpLog: Enabled

### Client Setup Information

- Desktop App or Browser Version: 
	- iOS: 4.29.0.34197
	- Android: 4.29.0.34199
	- PC: 3.8.7
- Operating System: 
	- iOS: 15.3.1
	- Android: 12
	- PC: Windows 11 22H2

### Additional context
Off-topic: When setting up third-party login, Google and Facebook both need to add the `?close` parameter as the redirect_url, except that GitHub does not need to add the ?close parameter. Otherwise, the redirect_url will be incorrect or unauthorized when enabled. FYI~

### Relevant logs:
{"level":50,"time":"2022-08-09T04:20:21.771Z","pid":7387,"hostname":"RocketChat-HK","name":"System","msg":"Exception while invoking method login 'No matching login attempt found [145546287]'"} 
{"level":50,"time":"2022-08-09T04:20:26.227Z","pid":7387,"hostname":"RocketChat-HK","name":"System","msg":"Exception while invoking method login 'No matching login attempt found [145546287]'"} 
{"level":50,"time":"2022-08-09T04:20:30.822Z","pid":7387,"hostname":"RocketChat-HK","name":"System","msg":"Exception while invoking method login 'No matching login attempt found [145546287]'"} 
{"level":50,"time":"2022-08-09T04:21:02.488Z","pid":7387,"hostname":"RocketChat-HK","name":"System","msg":"Exception while invoking method login 'No matching login attempt found [145546287]'"} 
{"level":50,"time":"2022-08-09T04:21:36.517Z","pid":7387,"hostname":"RocketChat-HK","name":"System","msg":"Exception while invoking method login 'No matching login attempt found [145546287]'"} 
{"level":50,"time":"2022-08-09T04:21:55.239Z","pid":7387,"hostname":"RocketChat-HK","name":"System","msg":"Exception while invoking method login 'No matching login attempt found [145546287]'"}

**Comment by jeanfbrito** [comment]
Hello, just tested the Github login on the open.rocket.chat server and it works. This seems to be a server configuration problem and not a Electron one. Could you please test it? Then I will transfer this issue back to the server repository.

@dudanogueira JFYI.

**Comment by mlongmiresqa** [comment]
I'm getting this too after an upgrade from 4.7.something (i forget) to 5.0.3 today. Browsers, Phone clients, and the Mac Client all work fine. But windows clients cannot connect due to this error. I did check the open.rocket.chat server and Oauth works. Anyway we can verify that server is running the the latest?

**Comment by dkatsariotis** [comment]
> Hello, just tested the Github login on the open.rocket.chat server and it works. This seems to be a server configuration problem and not a Electron one. Could you please test it? Then I will transfer this issue back to the server repository.
> 
> @dudanogueira JFYI.

After upgrading to 5.0.3, no problem anymore.

I was using 5.0.2 image rocket.chat from hub.docker.com
Now using 5.0.3 image

**Comment by jeanfbrito** [comment]
> I'm getting this too after an upgrade from 4.7.something (i forget) to 5.0.3 today. Browsers, Phone clients, and the Mac Client all work fine. But windows clients cannot connect due to this error. I did check the open.rocket.chat server and Oauth works. Anyway we can verify that server is running the the latest?

Yes, open.rocket.chat always runs the nightly version.
Are you sure that you are using 5.0.3? Seems to be a problem in your configurations and not a general issue. Lets try to debug this.

**Comment by mlongmiresqa** [comment]
I am using 5.0.3 unless the Info screen is wrong. Here's a screenshot of that along with the dev ID and whatnot.
![image](https://user-images.githubusercontent.com/8139065/184682185-ca3805be-26cb-432b-8b83-d3933dcba562.png)

I did had to add a 'directConnection=true' to my 'MONGO_URL' and 'MONGO_OPLOG_LOG' environment vars to my docker-compose file to make everything work with with 5.x. I think if that was the issue the issue there'd be issues with the other clients.

**Comment by mlongmiresqa** [comment]
Here are some logs when I click the Google button from a windows client.  When I use another client, i.e. Mac, Android or the webapp on Windows, the same user is logged straight away like normal. I don't see anything odd in the logs when that happens.

```
{"level":30,"time":"2022-08-15T17:16:18.315Z","pid":9,"hostname":"b1011c02f46b","name":"System","msg":"Failed login detected - Username[unknown] ClientAddress[xx.xx.xx.xx] ForwardedFor[xx.xx.xx.xx] XRealIp[xx.xx.xx.xx] UserAgent[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.7.7 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36]"}
{"level":40,"time":"2022-08-15T17:16:18.615Z","pid":9,"hostname":"b1011c02f46b","name":"System","msg":"Automatically added ?close to 'redirect_uri' for google, this behavior will be removed in v5.0.0.\nPlease update your OAuth config to accept both with and without ?close as the 'redirect_uri'."}
```

I currently have both `https://domain.tld/_oauth/google` and `https://domain.tld/_oauth/google?close`  set like the message suggests. The warning message still appears after setting that.

i tried downgrading the app to older versions. Same issue there as well. I went back as far 4.6.x.

**Comment by dkatsariotis** [comment]
> > Hello, just tested the Github login on the open.rocket.chat server and it works. This seems to be a server configuration problem and not a Electron one. Could you please test it? Then I will transfer this issue back to the server repository.
> > @dudanogueira JFYI.
> 
> After upgrading to 5.0.3, no problem anymore.
> 
> I was using 5.0.2 image rocket.chat from hub.docker.com Now using 5.0.3 image

After reinstalling Windows App today, I got the same error again.
Server version 5.0.3

**Comment by dkatsariotis** [comment]
UPDATE:

If it go to "Window / Settings" and disable "Open Video Chat usign Application Window", it allows me to login.
But when I recieve a new message, I cannot see it in chat windows on the left but can see it on the right when i click the user that sent me the message.

**Comment by yatounoneko** [comment]
> UPDATE:
> 
> If it go to "Window / Settings" and disable "Open Video Chat usign Application Window", it allows me to login. But when I recieve a new message, I cannot see it in chat windows on the left but can see it on the right when i click the user that sent me the message. If I refresh the page (broswer) or quit and open the app again, I can see the new message indicator

It's strange, I did follow your settings and clicking on 3rd party login no longer brings up "No matching login attempt found" immediately, but will keep load the white screen after login to the 3rd party. until I close this window and it will bring up "No matching login attempt found" again.
![](https://oxo.hk/index.php?explorer/share/file&hash=1379YtwzwQUSSjXqgv8Sn15EX-vkLhc5kCb5Mcw9-l2mDwhBE8tcYA9KEN8FsSOGbN2cWA)
![](https://oxo.hk/index.php?explorer/share/file&hash=6769HrYsnccwTzqGront2laE9OK1snaDSG0eYUzslTgF6vqk8DunAPFqnHo_ZhKgsv4QEg)

**Comment by daurpam** [comment]
Thank you for the tip. Now I can login in Windows Desktop application. In mobile I'd have to try several times and finally I could.
In my case we are using Google and after login in webpage the Rocket Chat app doesn't reload or do login.

**Comment by mlongmiresqa** [comment]
Confirming that disabling the setting `Open Video Chat usign Application Window`  allows us to log back in using Google's Oauth.

**Comment by mlongmiresqa** [comment]
@jeanfbrito -- This looks to affect SSO login in general. I only have Google on our companies, but using the latest desktop app and trying to use any of the SSO options I get the 'No Matching Login Attempt Found' alert popup there as well.

**Comment by yatounoneko** [comment]
> The issue then is with Google Login? The Github login is working in 5.0.3? The Facebook too?

@jeanfbrito Confirmed if disabled the setting `Open Video Chat usign Application Window` then facebook and github will load the white screen after login to the 3rd party, but google can be login normally. 

If not disabled All 3rd party login function will direct show `No matching login attempt found`.

**Comment by yatounoneko** [comment]
Please check: [video](https://oxo.hk/#s/8bC_2SlA)
I can't reproduce the white screen issue, it seems to be an isolated case.
But interestingly enough I tried to log in to a third party and then close `Open Video Chat using Application Window` then browser isolation appeared.
Could it be caused by not being able to pick up content from other windows?

If you use open.rocket.chat there is no isolation.
WTF, if I try to login to GitHub once using open.rocket.chat, my own site will work normally ....... ???
I couldn't even reproduce the original question after trying ...... ??????

**Comment by ankar84** [comment]
I have same issue with KeyCloak OAuth provider configured.
Disabling `Open Video Chat using Application Window` option fixed `No matching login attempt found` error.
@jeanfbrito please fix that issue. It could be a blocker for update to 5.X server releases for us.

**Comment by jeanfbrito** [comment]
I'm not able to reproduce it on the servers that we are running. Could someone provide a connection to a server that has the problem? Every test that I do, it just works with the version 3.8.7 of the client.

**Comment by jeanfbrito** [comment]
@yatounoneko your server is public available? If I could test it would be great. You can reach me on open.rocket.chat, my user is jean.brito.

**Comment by yatounoneko** [comment]
> @yatounoneko your server is public available? If I could test it would be great. You can reach me on open.rocket.chat, my user is jean.brito.

Send your messages, thanks for your help.

**Comment by sketch242** [comment]
I was getting the same error after updating from 4.8.x to 5.0.3 and using Custom OAuth against Office 365.  However, I only got it on the Mac and Linux app, Windows was working fine.  In my case, changing the Custom OAuth's Login Style from Popup to Redirect appears to have solved the problem.

Just wanted to mention it here in case it's related, or helps someone else getting the same error.
