### ISSUE TITLE
Cancelled Download Instance seen in Downloads Tab, When Save Dialog Dismissed.

### ISSUE THREAD

**Issue by henit-chobisa** [RocketChat/Rocket.Chat.Electron#2469]
**Cancelled Download Instance Seen in Download, even if the download save dialog is dismissed.**
---
- When the user tries to download a file, the save dialog pops up.
- Then, if the user dismiss the save dialog.
- There should not be any instance of the file in the downloads section but the file is shown in the downloads tab in cancelled state.

What operating system and which version : MacOS 12.5
Which version of Rocket.Chat (Server) : demo Server
Which version of Rocket.Chat.Electron (Electron/Desktop): latest
Is there any setting relevant changed : No

**To Reproduce**
1. Click on the download button of any file.
2. When the savepath dialog pops up asking for the file path, cancel it.
3. Now you can see the file you were trying to download in the downloads, in the cancelled state.

**Expected behavior**
When the savepath dialog is dismissed, no file should exist in the downloads tab of the App.

**Screenshots**
<img src="https://res.cloudinary.com/ddglxo0l3/image/upload/v1660591591/OpenSource/ezgif-4-2a45eb204a_xnnsnm.gif"></img>

**Comment by jeanfbrito** [comment]
What happened with the another PR?

**Comment by henit-chobisa** [comment]
> What happened with the other PR?

Hey Jean, While I working on the previous PR, I could see that it was continuously failing some tests and during the process, I made a mistake pushing some unnecessary conflicting commits.

Hence, I decided to keep the process clean, ran all the tests in my local machine provided in the GitHub workflow, and hence created a new fresh PR.
