### ISSUE TITLE
magnifier on windows 11

### ISSUE THREAD

**Issue by p-migda** [RocketChat/Rocket.Chat.Electron#2471]
Rocket is turned off instantly when you turn on magnifier on Win 11

**Comment by Palanikannan1437** [comment]
Hey there @p-migda!, could you please be a bit specific about the version of the app (both the electron app and the server). 

It would be helpful if you could maybe provide a demo/recording of the bug you're facing along with the steps to reproduce it! 

It would help us help you better! 😄
