### ISSUE TITLE
A javascript error at startup

### ISSUE THREAD

**Issue by drodriganez** [RocketChat/Rocket.Chat.Electron#2473]
**Describe the bug**
A javascript error occurred in the main process

![imagen](https://user-images.githubusercontent.com/111491942/185339475-78317626-78b0-4006-987b-75dd61bbfd3a.png)

What operating system and which version?
Edition	Windows 11 Enterprise
Version	21H2
Installed on	‎28/‎04/‎2022
OS build	22000.856
Experience	Windows Feature Experience Pack 1000.22000.856.0

Which version of Rocket.Chat (Server)?
Don't know
Which version of Rocket.Chat.Electron (Electron/Desktop)?
3.8.7 windows
Is there any setting relevant changed?

**To Reproduce**
1. At startup, i've startup at windows start

**Comment by drodriganez** [comment]
the problem is in the config.json file located in %user%\AppData\Roaming\Rocket.Chat, I have deleted the entries that were in download and I have restarted the process and it has been solved

**Comment by jeanfbrito** [comment]
Nice that you found it. We already fixed this issue on the code and will release it soon. It's a bug of chromium with infinity number.
