### ISSUE TITLE
`Open Video Chat using Application Window` option broken for server 5.0

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#2480]
**Describe the bug**
If one use recent app version 3.8.8 with latest server version like 5.0.4, option `Open Video Chat using Application Window` do not work. Jitsi call is opened in default browser window.

What operating system and which version? Windows 10
Which version of Rocket.Chat (Server)? 5.0.3
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.8.8
Is there any setting relevant changed? Update from 4.x to 5.x of server version

**To Reproduce**
1. Setup Jitsi app with new Video Conf system in 5.X server version
2. Turn on option `Open Video Chat using Application Window` in Settings of Desktop app 
3. Test Jitsi call
4. See that call opens in default browser

**Expected behavior**
Jitsi call opens in desktop app sub window even on server version 5.X

**Screenshots**
No

**Additional context**
On pre 5.0 versions of server with same 3.8.8 version of Desktop app Jitsi call starts in Desktop app sub window.

**Comment by artlive89** [comment]
Same problem

**Comment by amsnek** [comment]
same issue since update rocketchat electron 3.8.8 (it worked on 3.8.6)

This option in settings is ignored, it always uses default browser sind app version 3.8.8
![image](https://user-images.githubusercontent.com/73526449/186631564-5102889c-f66f-4c3e-aa02-1fa8f476a89f.png)

**Comment by jeanfbrito** [comment]
Yes, the server version 5.x introduced the video conference adding multiple video call providers as apps. This changed the way this feature works and we don't have a solution yet for working in 5.x. For now this option will work properly on 4.x and behind but in 5.x it will only open in the browser.
I'm already  in touch with the video conference team to solve that. 
Now that we have a whole new number of providers, there are security issues that need to be handled on Electron that the browser already does by default.
