### ISSUE TITLE
Update: Rocket Chat App (Windows) doesn't work properly

### ISSUE THREAD

**Issue by schwerdtj** [RocketChat/Rocket.Chat.Electron#2481]
My Desktop App of Rocket chat offers the newest update on Operating System Start. 
I'm choosing "update now". 
The app stops without any error warning.

- Version of Rocket Chat Desktop App: 3.8.7
- Windows 10, 1809

**Comment by ankar84** [comment]
Not confirm that issue on my side.
Just updated from 3.8.7 to 3.8.8 automatically on Windows 10.

**Comment by jeanfbrito** [comment]
I tested it in various machines and worked. You will need to provide more info. Just don't works don't help to figure out what's happening.

Did you tried on another machine? Are you the computer administrator?
