### ISSUE TITLE
Paused downloads after cancellation do not reflect changes on the UI 

### ISSUE THREAD

**Issue by Palanikannan1437** [RocketChat/Rocket.Chat.Electron#2483]
- **Describe the bug:-**
Once a download in progress is paused, though we are able to cancel it, the changes aren't reflected on the UI

- What operating system and which version - MacOS Monterrey Version 12.5 (21G72)
Which version of Rocket.Chat (Server) - 5.0.2
Which version of Rocket.Chat.Electron (Electron/Desktop) - 3.8.8

- **To Reproduce:-**
1. Start downloading a file
2. Go to the Download View using the sidebar
3. Now pause the file that's downloading.
4. Cancel the download
5. The UI doesn't reflect that the download has been cancelled yet

- **The bug:-**
1. On starting a new download, when we pause the download and then cancel the download, the UI doesn't reflect that the download has been cancelled

2. As a result the user isn't able to  perform: 
- `Remove Item from list` 
- `Retry`
Operations on the download!

![downloadErrorGIF](https://user-images.githubusercontent.com/73993394/186724763-4e1a8674-46fe-4b50-b864-ee29fedb7d3e.gif)

- **Expected behaviour:-**
On starting a new download, when we pause the download and then cancel the download, the UI should reflect that the download has been cancelled!

**Comment by jeanfbrito** [comment]
Please make better titles for issues.

**Comment by Palanikannan1437** [comment]
> Please make better titles for issues.

Hey there @jeanfbrito, That was a mistake from my side, it didn't publish back then, I've fixed it now!
