### ISSUE TITLE
Open Rocket.Chat.exe from Command Line

### ISSUE THREAD

**Issue by postwarbreakout** [RocketChat/Rocket.Chat.Electron#2492]
I am deploying updates silently and would like to start the client after the update is finished. But when I just run a command with "%PROGRAMFILES%\Rocket.Chat\Rocket.Chat.exe", a terminal with a Bugsnag log opens and if I close it, Rocketchat gets closed too. How I can I just start the .exe without that?

**Comment by jeanfbrito** [comment]
You will need to make it run in the background from the CMD. Because if not, you will have the execution attached to the opened CMD and it will close then.

**Comment by postwarbreakout** [comment]
Well, how do I do that? I haven't found a working switch.
