### ISSUE TITLE
Publish to Windows Package Managar (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal2009** [RocketChat/Rocket.Chat.Electron#2496]
## My Setup

- Operating System: Windows 11
- App Version: Latest
- Installation type: Package Manager

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
With every new release of RocketChat, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

Existing projects which use the action: https://github.com/search?q=vedantmgoyal2009%2Fwinget-releaser+path%3A.github%2Fworkflows%2F+language%3AYAML&type=Code&s=indexed&o=desc

I can create a PR to implement the action in the repository.

### Current Behavior
N/A

### Expected Behavior
N/A

**Comment by jeanfbrito** [comment]
You could create the PR if you want. I don't know if we have enough users for this, but if you are willing to contribute, you are welcome.

**Comment by Kornejew** [comment]
I would love to have this feature. Since the implementation is already done, it would be great to see it integrated.
