### ISSUE TITLE
Strange popup on start

### ISSUE THREAD

**Issue by Sigurs** [RocketChat/Rocket.Chat.Electron#2504]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Ubuntu 22.04.1 LTS

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.9

### Rocket.Chat Server Version

5.1

### Describe the bug

When I launch the client I get the popup below.
Only happens once after a boot, but not if I close and re-open the application.

Channels load in the background normally while the popup is visible.

I keep pressing the three squares assuming it's "yes" to something, but I see no difference if I press the two squares.
Maybe some fonts are missing in the snap package?

I'm using the client from the snap store.

![image](https://user-images.githubusercontent.com/10909187/189862753-5319d8c8-c1b3-4811-8769-d7653ad816db.png)

### How to Reproduce

1. Start PC
2. Launch client

### Describe your Expected behavior

No popup, or a popup with text in it.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Hey @Sigurs I couldn't reproduce this. Did you have this problem with another machines or is only on this one?

**Comment by Sigurs** [comment]
@jeanfbrito I sadly currently only have one Linux machine.
I haven't heard my other Linux using colleagues complain about this though.

Same issue is actually also present in the save file dialogue when I try to save a picture from chat.
![image](https://user-images.githubusercontent.com/10909187/195327150-f0a1dac9-2d90-4ed1-bf48-95cda6e627c2.png)

Outside of the rocket chat snap, everything is working without issues.

**Comment by jeanfbrito** [comment]
Could you try installing the .Deb from our releases here on GitHub? Just to see if is snap related.

**Comment by Sigurs** [comment]
@jeanfbrito Tried the latest .deb and no issues with it.
Sounds like it might be related to the snap.
