### ISSUE TITLE
No sound notification on some channels

### ISSUE THREAD

**Issue by llagardeOSE** [RocketChat/Rocket.Chat.Electron#2505]
### Search before asking

- I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- Windows

### Operating System Version

Windows 10

### It happens on the web browser too?

Yes, it happens on the web browser too.

### Rocket.Chat Desktop App Version

3.8.9

### Rocket.Chat Server Version

3.0.4

### Describe the bug

I have no sound notification on some channels.
It works on other channels so the global settings are OK.
The notification settings of the channels where there is no beep on new message are OK (using the global settings).
I don't know where to look for the per channel notification settings. Some configuration file or some database must exist but I can't find it.
I have the problem on 'discussions', 'channels', 'private groups' and 'direct messages' channels.
I tried to reset the client to default settings without success.

**Comment by jeanfbrito** [comment]
![image](https://user-images.githubusercontent.com/1177482/194596467-c5be17f4-1589-449c-899f-2212c69e79d1.png)
![image](https://user-images.githubusercontent.com/1177482/194596512-07895c69-7a6b-43c1-b271-2e64cb07b1dd.png)
Looking at this screenshots you will find the configurations of notification for each channel.
