### ISSUE TITLE
Application is not muted even when the machine is muted!

### ISSUE THREAD

**Issue by Atinjanki** [RocketChat/Rocket.Chat.Electron#2509]
I am using RocketChat application on Debian 10.

Even when I mute my machine I keep hearing sound of RocketChat messages!

Why doesn't the application get muted as well?

**Comment by jeanfbrito** [comment]
Hello @Atinjanki 
How could you mute the machine and keep listening it? We need more information on what exactly are you doing and is happening.

You can configure what will notify you on the chat. But we don't touch system audio.
