### ISSUE TITLE
Unable to record video (MacOs)

### ISSUE THREAD

**Issue by kakawait** [RocketChat/Rocket.Chat.Electron#251]
## My Setup

- **My OS name and version**: MacOsX 10.11.6
- **My current app version**: `1.3.1 (15)` but tested trough `develop` branch (last rev: 7e187ae795a5b226703956e916abd630975f5676) 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

Unable to record video 
#### Current Behavior

Open video recorder

![screen shot 2016-10-28 at 14 50 46](https://cloud.githubusercontent.com/assets/275609/19806924/ed134c92-9d1d-11e6-9370-eebae4562eeb.png)

Video recorder open successfuly and webcam preview works perfectly but when I try to record using button

![screen shot 2016-10-28 at 14 51 27](https://cloud.githubusercontent.com/assets/275609/19806943/06ce19a0-9d1e-11e6-923b-a0f106383675.png)

Does not work (even `Ok` button does not work, only possibility `Cancel`)
#### Expected Behavior

Enable to record and post video like on web version

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
