### ISSUE TITLE
[Regression] Client authentication does not respect redirect and opens a browser window

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat.Electron#2511]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10, MacOS 12.6

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.10

### Rocket.Chat Server Version

5.1.2

### Describe the bug

Custom Oauth login style has been set to `Redirect` instead of `Popup` in RC config.

The latest version 3.8.10 of RC client executes popup instead of redirect, which causes the authentication flow to fail for the desktop client users. The browser client still operates as it should.

This issue does not exist in the client version 3.8.9.

Popup method has a bigger footprint for deceiving the users so the Redirect is the preferred method.

### How to Reproduce

1. Create a custom Oauth config on RC server.
2. Set the Login Style as Redirect.
3. Log in with the RC client.
4. Observe authentication to fail as it opens up a Popup window instead of redirecting

### Describe your Expected behavior

User session should get redirected in the existing client window to the location of authentication.

**Comment by jeanfbrito** [comment]
Hello, this kind of redirect was tested to not be affected. Could you show
what settings are you using on the custom oauth?

Em sex., 23 de set. de 2022 04:42, Gummikavalier ***@***.***>
escreveu:

**Comment by mddvul22** [comment]
We aren't using Oauth, but we are using SAML.  We just got a report from an employee that they upgraded their desktop Rocket Chat app this morning, and is getting very similar behavior.  He clicks the SAML login button in the desktop app and rather than get a login window, the desktop app is sending his login request to his web browser, which then tries to load our SAML login page.  That will obviously fail.  His web browser gets a "Stale Request".  The desktop app sits there with a "Logging in...please wait" on the screen.

**Comment by jeanfbrito** [comment]
@Gummikavalier @mddvul22 could you please take a look inside the `config.json` file and see if there is a key inside the server key called `allowedRedirects` and if there are the URLs for your authentication servers?

Are you using another server for the Oauth? Could you please explain how it is configured?

**Comment by mddvul22** [comment]
I just installed the newest version of the desktop app to check this. (By the way, I can confirm what our employee had reported to us.  But what he reported was slightly incorrect.  The desktop app _does_ load our SAML login window.  However, after entering your username and password, the act of clicking on the "Login" button is when the desktop app sends the request to the web  browser.

To answer your question, this is what I see in my config.json:

`"allowedRedirects": [],`

**Comment by jeanfbrito** [comment]
> I just installed the newest version of the desktop app to check this. (By the way, I can confirm what our employee had reported to us. But what he reported was slightly incorrect. The desktop app _does_ load our SAML login window. However, after entering your username and password, the act of clicking on the "Login" button is when the desktop app sends the request to the web browser.
> 
> To answer your question, this is what I see in my config.json:
> 
> `"allowedRedirects": [],`

That makes sense. Thanks for reporting.

**Comment by Gummikavalier** [comment]
In case the Custom Oauth setup is still needed we have it like this:

```
URL:
(Path ending in ... /idp/profile/oidc)

Token Path:
/token

Token Sent Via:
Header

Identity Token Sent Via:
Same as "Token Sent Via"

Identity Path:
/userinfo

Authorize Path:
/authorize

Scope:
openid profile email offline_access

Param Name for access token:
access_token

Login Style:
Redirect

Username:
(Oauth provider account ID is used here)

Name field:
displayName

Merge users:
on

Key Field:
Username
```

I don't have a chance to install the client for myself currently, the issue was reported and replicated by users. Sorry for that!

**Comment by Gummikavalier** [comment]
Thanks a lot! :+1:

**Comment by mddvul22** [comment]
Yes, thank you!

**Comment by Gummikavalier** [comment]
We confirm that the version 3.8.11 works ok now.

**Comment by mddvul22** [comment]
Yes, this is working with SAML auth, also. Thanks!
