### ISSUE TITLE
Video calls open again on Electron window isn't working for server version 4.8.3

### ISSUE THREAD

**Issue by moell9** [RocketChat/Rocket.Chat.Electron#2512]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10, macOS 12.6

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.10

### Rocket.Chat Server Version

4.8.3

### Describe the bug

The web browser window is starting instead of the Electron window in a video call.

### How to Reproduce

Start a new video call and the browser window is opening.

### Describe your Expected behavior

An extra Electron window should open (like in older versions).

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
@moell9 already found the issue and fixed. Will be released today yet. Thanks!
