### ISSUE TITLE
 Flipped RTL Text When Mixed with LTR Text

### ISSUE THREAD

**Issue by molaeiali** [RocketChat/Rocket.Chat.Electron#2526]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Arch Linux

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

3.8.12

### Rocket.Chat Server Version

5.0

### Describe the bug

 The issue is when mixing RTL text with LTR text in the same line, after sending the message it is considering the LTR order and flipping the words written in RTL.

There are issues open on the https://github.com/RocketChat/Rocket.Chat project, I just reference them here as I think they are related to the electron project. (The issue doesn't exist on the Android application for example)

Please take a look at https://github.com/RocketChat/Rocket.Chat/issues/26857 and https://github.com/RocketChat/Rocket.Chat/issues/26499 issues for more information 

### How to Reproduce

1. Write an RTL text (E.g. Arabic text)
2. Write some LTR text  in between (E.g. English text)
3. Send the message

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Hello @molaeiali, the Android is made in React Native, that's why it works differently of the web and desktop.
The desktop app is just a wrapper with a browser inside. Then if the problem occurs on the web browser (chrome) too, this is a problem of the Rocket.Chat server. 
I know that the devs are working on an issue of RTL/LTR text on the message parser engine.

I will be closing this issue because is not a Electron issue, ok?

**Comment by molaeiali** [comment]
> Hello @molaeiali, the Android is made in React Native, that's why it works differently of the web and desktop.
> The desktop app is just a wrapper with a browser inside. Then if the problem occurs on the web browser (chrome) too, this is a problem of the Rocket.Chat server. 
> I know that the devs are working on an issue of RTL/LTR text on the message parser engine.
> 
> I will be closing this issue because is not a Electron issue, ok?

Ok thanks for the response ❤
