### ISSUE TITLE
DROP FILES TO UPLOAD UI overlay appearing from nowhere, will not go away no matter what

### ISSUE THREAD

**Issue by jaakkopaakkonen** [RocketChat/Rocket.Chat.Electron#253]
## My Setup

 - __My OS name and version__: Windows 7 Professional version 6.1 SP1 
 - __My current app version__: RocketChate version 1.3.1

- [x] I have tested with the latest application version
- [ ] I can simulate the issue easily

#### Current Behavior

From time to time I see "drop files to upload" ui overlay appearing on top of my chat essentially blocking my chat window. I don't have faintest idea where this comes from.

There is no button to get rid of it. Pressing esc does nothing. If I exit the application and reopen it, the overlay is there. Only way to get rid of it is to have an empty file inplace which I can actually drag on top of the application. (yeah. Really.)

#### Expected Behavior

No "DROP FILE TO UPLOAD" overlay screens blocking the chat appearing from nowhere without my specific action please.
And if you DO change the ui state, there always has to be a way to go "back". Just a key shortcut is not enough. It has to be obvious from the ui where you have to click or what you have to do to go back from the currrent state.

**Comment by alexbrazier** [comment]
@jaakkopaakkonen Is this still an issue for you with the latest version?

This might be an issue with Rocket.Chat rather than the electron app, do you get the same thing in the browser?

**Comment by alexbrazier** [comment]
Closing this as I'm unable to recreate and haven't heard back. Please reopen if you are still having issues with the latest version.
