### ISSUE TITLE
General Settings are not scrollable in Desktop App (on Windows 10)

### ISSUE THREAD

**Issue by vkuhnde** [RocketChat/Rocket.Chat.Electron#2530]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10 Pro 21H2

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.12

### Rocket.Chat Server Version

5.1

### Describe the bug

The General Settings tab does not show all options on small screens. It is not possible to scroll down or otherwise move more options into the viewport.

This does not apply to Rocket.Chat in web browsers, because the web version does not have these settings.

### How to Reproduce

1. Open Settings (gear icon on the bottom left)
2. Can't scroll --> can't see all options of the "General" tab on small screens

### Describe your Expected behavior

I would like to see all settings even on small screens. The probably easiest solution is to make the settings scrollable.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by thepranays** [comment]
I would like to work on this issue as this seems a beginner friendly one.Can i ?

**Comment by jeanfbrito** [comment]
Hello @thepranays, you don't need to ask permission. Just make it and open a PR. I will review it as soon as possible.

**Comment by thepranays** [comment]
@jeanfbrito Hey,Can you please review my PR on this issue.
