### ISSUE TITLE
Windows 10 Notification

### ISSUE THREAD

**Issue by TobiasTimm** [RocketChat/Rocket.Chat.Electron#255]
## My Setup

 - __My OS name and version__:  Windows 10
 - __My current app version__:  1.3.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

You will get a notification, if you receive a message. When you click on this notifictation, while the app is in tray, nothing happens.

#### Current Behavior

The notification just vanishs.

#### Expected Behavior

After I click on the notification in Windows 10, the app should show up

**Comment by SteveOnorato** [comment]
I also see this in Windows 8 (once I apply the fix in #290).

**Comment by engelgabriel** [comment]
Can you try again with version `2.2.0`?

**Comment by graywolf336** [comment]
Confirmed is still an issue with development version `2.3.0-develop` on windows 7.
