### ISSUE TITLE
critical error at Windows shutdown

### ISSUE THREAD

**Issue by trash739** [RocketChat/Rocket.Chat.Electron#2552]
critical error at Windows shutdown appears again in RC 3.8.13, see the screenshot attached
![221125_RC_error_ret](https://user-images.githubusercontent.com/45266374/203922951-285ee690-9b72-4443-959d-f51fecf734dc.jpg)

**Comment by jeanfbrito** [comment]
@trash739 We need more information. When this happens? 
Again? When did it happened before?

@dudanogueira we need to improve the main repo bug report template, we cant accept so empty bug reports.

**Comment by dudanogueira** [comment]
Hum. 

Just realized that it's not ideal to transfer issues from one repo to another, as we'll miss the new issue template bit.
I'll start closing and pointing to the [proper URL](https://github.com/RocketChat/Rocket.Chat.Electron/issues/new/choose).

@trash739 I will close this issue. Please, can you open up [following this link](https://github.com/RocketChat/Rocket.Chat.Electron/issues/new/choose)? With more information (link windows versions, logs, etc) we can better understand and fix the issue in our App.

Thanks!
