### ISSUE TITLE
No avatar Rocket Chat

### ISSUE THREAD

**Issue by Sivka123** [RocketChat/Rocket.Chat.Electron#2553]
We can`t load or update our user profile. This issue in any devices win 7 win 10 and in different users. Can u check this problem

## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by jeanfbrito** [comment]
Please open a new bug report adding the requested information.
