### ISSUE TITLE
Rocket.Chat crashes after attempt to open link

### ISSUE THREAD

**Issue by bulkinav** [RocketChat/Rocket.Chat.Electron#2560]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Operating System Version

macOS 13.0.1

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.14

### Rocket.Chat Server Version

5.4.0

### Describe the bug

After upgrade Rocket.Chat Server to the version 5.4.0, desktop app crashes after attempt to open external links from Incoming WebHook. In my case, I use GitLab incoming webhook: https://docs.rocket.chat/guides/administration/admin-panel/integrations/gitlab

### How to Reproduce

1. Push someone to repo -> GitLab incoming webhook posted push event to the channel
2. Click by the commit link -> app crashed

### Describe your Expected behavior

The link opens correctly in an external browser.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

https://user-images.githubusercontent.com/1636367/205948076-d2f3c1ec-ef58-4278-8de6-02a5a19a3d94.mov

**Comment by jeanfbrito** [comment]
Hello, can you test on another operational system and on web what happens?
On web it will redirect the chat tab or open a new tab?
Since when it started happening? Just on 3.8.14?
I don't have a github integration now to test it easily.

**Comment by bulkinav** [comment]
> on web what happens?

On web the link opens in a CURRENT tab (accordingly, we are leaving Rocket.Chat). This is, of course, incorrect behavior.

The problem was also in previous Electron builds, not just in 3.8.14, and appears after upgrade Rocket.Chat Server to the version 5.4.0.

I think, that any links should be forced to open in new tabs (target="_blank"), because the GitLab incoming webhook (for example) does't add target="_blank":

```
<ul>
   <li>
      <a href="https://gitlab.com/..../commit/03858866....">03858866</a>
   </li>
</ul>
```

**Comment by hugocostadev** [comment]
Hi @bulkinav  this is a known issue and already has an open PR, thanks! 

Pull Request: https://github.com/RocketChat/Rocket.Chat/pull/27554

**Comment by hugocostadev** [comment]
Fixed

**Comment by jeanfbrito** [comment]
Thank you @hugocostadev
