### ISSUE TITLE
"MediaRecorder is not defined" when trying to capture a webcam video

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.Electron#257]
## My Setup

 - __My OS name and version__: macOS Sierra 10.12.1
 - __My current app version__: 1.3.1

- [X] I have tested with the latest application version
- [X] I can simulate the issue easily

#### Current Behavior

When you click on the camera icon right besides the message input box, a client side error pops up in the console:

```
Uncaught ReferenceError: MediaRecorder is not defined
```

#### Expected Behavior

No error, since it's working fine when trying to reproduce in the browser.

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.

**Comment by Rajarathinamsoft** [comment]
Hi i faced this error on Microsoft Edge Browser. The Error is " ReferenceError 'MediaRecorder' is not defined". Please how to resolve the error.
