### ISSUE TITLE
Rocket Chat appears as “Google Chrome” in list of status notifiers (XFCE Status Tray Plugin)

### ISSUE THREAD

**Issue by sebalis** [RocketChat/Rocket.Chat.Electron#2576]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Arch Linux with XFCE 4.18

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.15

### Rocket.Chat Server Version

n/a

### Describe the bug

I use the Status Tray Plugin in XFCE to show icons for those programs that announce themselves to it. The plugin’s properties window has a list of all items it has encountered and offers this list for manual sorting. In that list, rocketchat-desktop appears as Google Chrome with a Chrome icon. Other Electron apps such as Element or Signal manage to announce themselves with their own name and icon. Seems like something is missing.

### How to Reproduce

Run XFCE and include the status tray plugin in some panel. If it is not there yet, open XFCE’s Panel preferences, go to the Items tab, select the desired panel and add the Status Tray Plugin, and close. Start rocketchat-desktop. Now open the Panel preferences again and find the status tray plugin in the list of items for the appropriate panel. Double-click it to open its properties and inspect the list of status notifiers. Find “Google Chrome” and by moving it around using the arrow icons verify that the item being moved is in fact Rocket Chat.

### Describe your Expected behavior

Rocket Chat should not appear disguised as Google Chrome :-)

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Hello, this happens with the version 3.8.14?

**Comment by sebalis** [comment]
Hi, is this a statement or a question (“Does this happen …”)? I can try to find out.

**Comment by sebalis** [comment]
I have started trying to find out and can now report that it seems to depend on the details of the Arch User Repository package I am using. Have not tried 3.18.4 but compared [rocketchat-client-bin](https://aur.archlinux.org/packages/rocketchat-client-bin) 3.18.5-1 (where the problem does occur) with [rocketchat-desktop](https://aur.archlinux.org/packages/rocketchat-desktop) 3.8.15-4 (where it does not: the app shows up with a Rocket Chat icon under the name Rocket.Chat1). Seems that I should not have bothered you with a problem that probably depends on the packaging, not the actual source. In that case, my apologies. If you’re interested, I can try installing an older version of either of these two packages.

**Comment by jeanfbrito** [comment]
> Hi, is this a statement or a question (“Does this happen …”)? I can try to find out.

Sorry, the interrogation in the end disguised the question. Sorry for my language error.
