### ISSUE TITLE
App crashes on selecting pinned messages in a channel.

### ISSUE THREAD

**Issue by sidharthkumar2019** [RocketChat/Rocket.Chat.Electron#2579]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Ubuntu 22.04.1 LTS

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

5.4.0

### Rocket.Chat Server Version

6.0

### Describe the bug

On selecting pinned messages in a channel, the app crashes instead of showing the pinned messages.
![Screenshot from 2023-01-08 21-35-22](https://user-images.githubusercontent.com/53421109/211206837-22a2b808-355e-48a9-b501-a8cf65fb4149.png)
![Screenshot from 2023-01-08 21-35-02](https://user-images.githubusercontent.com/53421109/211206843-9a6f4110-14eb-4c66-b2a9-e4f8141d2c9b.png)

### How to Reproduce

1. Join the channel chat.rocket.com.
2. Go to "# how to get started" channel.
3. From the menu, select "pinned messages". 
4. You will now see the error. 
Haven't confirmed on mac and windows yet.

### Describe your Expected behavior

It should show a list of pinned messages of the channel in the right hand side bar.

### Anything else

No.

### Are you willing to submit a code contribution?

- [X] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Hello, version 6.0 is not released yet. Please dont use it on production yet.
