### ISSUE TITLE
"No valid server found at the URL"

### ISSUE THREAD

**Issue by GeoDirk** [RocketChat/Rocket.Chat.Electron#258]
## My Setup

 - __My OS name and version__: 

Server side: Ubuntu 16.04 x64 built with https://github.com/Munroenet/rcInstaller 
Client Side: Both Mac OSX & Window's Rocket.Chat desktop clients (latest version)

- [X] I have tested with the latest application version
- [X] I can simulate the issue easily

Two servers have been built using the same script (https://github.com/Munroenet/rcInstaller).  Both servers install the Let's Encrypt SSL certificate.  The desktop clients can connect to one of the servers without any issue.  However, the client on both Mac & Windows reports the "No valid server found at the URL" error.

Working server: https://rc.enjen.net
Problem server: https://chat.crossconnect.tech

Both servers can be accessed just fine through a browser and respond fine to DNS calls.

Looking at another closed ticket about a similar issue: https://github.com/RocketChat/Rocket.Chat.Electron/issues/141 this error doesn't seem to be the same.  

Ideas?

**Comment by GeoDirk** [comment]
Appears to be the same issue as this one:

https://github.com/RocketChat/Rocket.Chat/issues/4742

**Comment by GeoDirk** [comment]
Solution is to disable http2 in your /etc/nginx/conf.d/rocket.chat.conf:

`server {
    #listen 443 ssl http2 default_server;
        listen 443 ssl default_server;
    #listen [::]:443 ssl http2 default_server;
`

**Comment by banrieen** [comment]
When start the rocket.chat server on the lan 172.19.5.x/24 ，and I can open the rocket.chat by chrom with http://172.19.5.x:3000,
But when I open the rocket.chat ios app by enter the url string "http://172.19.5.x:3000"  . It prompt: "Oop! The URL you entered is invalid . Check it and try ading,please ！”

**Comment by brightball** [comment]
I'm also running into this issue running Ubuntu 19.04. Everything works from the web with Chrome and the API url is accessible with a valid response too.

**Comment by tassoevan** [comment]
@brightball Is your issue related to HTTP2 too?

**Comment by brightball** [comment]
I'm not sure. I was about to open an issue for the "No valid server found at the URL" message but just picked this one because there were several. I'm not in control of the server, but a group that I'm working with on a project is using it and I was just trying to setup the desktop client for a better experience.
