### ISSUE TITLE
Links in Channel desciption, accouncements open in app..

### ISSUE THREAD

**Issue by b90g** [RocketChat/Rocket.Chat.Electron#2581]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

### Operating System Version

Debian Snap  & Windows 11

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.15

### Rocket.Chat Server Version

5.4.1

### Describe the bug

When i have a weblink in a channel description which is shown above the chat, or the channel announcment, links are opened inside the app.

### How to Reproduce

1. Have a weblink in channel announcement or description
2. Open that link by clicking it.

### Describe your Expected behavior

My prefered Webbrowser handles the displaying of the clicked link

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Hello, this was a bug on the server. The links is not with a `target="_blank"` href. Could you check if this is the case please?

**Comment by b90g** [comment]
thanks for pointing it out, will open an issue there.
