### ISSUE TITLE
Version >3.8.15 jitsi screen sharing doesn't work

### ISSUE THREAD

**Issue by alsmer13** [RocketChat/Rocket.Chat.Electron#2585]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 11

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.15

### Rocket.Chat Server Version

4.5

### Describe the bug

After updating app to 3.8.15 jitsi screen sharing doesn't not work. There is a preloader that spins endlessly.

### How to Reproduce

1. Install version 3.8.15
2. Start a jitsi call in the Rocket.Chat Desktop app
3. Click "Start / Stop sharing your screen"
4. Look at a preloader
 
![image](https://user-images.githubusercontent.com/32704558/212104836-3e660edc-5cc7-4643-90ef-5c40f77495d1.png)

### Describe your Expected behavior

Choosing a screen that I want to share

### Anything else

It works perfect in version 3.8.14

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by BoJackBR** [comment]
The same issue in version 3.8.16

**Comment by SamirSaidani** [comment]
same here, reverting back to 3.8.14

**Comment by jeanfbrito** [comment]
Fixed on version 3.8.17
