### ISSUE TITLE
Ability to start a recording with Jitsi Meet in the Rocket.Chat Video Chat Application Window

### ISSUE THREAD

**Issue by moell9** [RocketChat/Rocket.Chat.Electron#2598]
Currently, only Google Chrome allows you to start a recording with Jitsi Meet in Rocket.Chat. 
Since the Electron is based on Google Chrome, I would expect that to work. Unfortunately it doesn't.
Is there any way to change this in Rocket.Chat Electron ?

**Comment by jeanfbrito** [comment]
Hello, Electron is based on Chromium.
I need more informations about what you need.
Please test the last version 3.8.17.
