### ISSUE TITLE
Let users know when there is a new release

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#26]
I wouldn't think this would happen very often.

Could just have it check on start for a new release using github's api

`https://api.github.com/repos/RocketChat/Rocket.Chat.Electron/releases`

**Comment by rodrigok** [comment]
@geekgonecrazy cool, do you have plans to start this issue?

**Comment by geekgonecrazy** [comment]
If I can think of how to display it.  Could always use a html prompt  :wink:

**Comment by rodrigok** [comment]
Maybe we can wait for @sampaiodiego changes related to multiple servers. He is implementing view split using iframes, so we can move the iframe down to show one colored bar at the top almost like spotify.

**Comment by geekgonecrazy** [comment]
Ah sweet!  This is exactly as I invisioned doing multiple servers with electron.  :+1:  Sweet that works for me.

**Comment by rockneverdies55** [comment]
@geekgonecrazy - I don't know much about electron stuff. Is it also possible to push the update somehow? 

Ideally, we push users a notification saying a new release is available and at the bottom of the dialog says "UPDATE" on a button? User clicks update to upgrade to the newer version available automatically... 

Did I ask for too much? :-)

**Comment by geekgonecrazy** [comment]
@rockneverdies55 I'm not aware of any push notification framework in place for it.  But its possible there is.  

The easiest would be to check every x amount of time.  

Need to look into this.. But its possible the rocket.chat server could emit an event which could be received by the electron app.  This might also be a way of effecting the app its self.

**Comment by engelgabriel** [comment]
On the Mac version, it may all be taken care when we get the app into the Mac App Store
https://github.com/RocketChat/Rocket.Chat.Electron/issues/19

But it would be good to have the app to check the url mentioned by @geekgonecrazy

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat.Electron/issues/98
