### ISSUE TITLE
Timestamp in Citations Might Be Misleading

### ISSUE THREAD

**Issue by bixel** [RocketChat/Rocket.Chat.Electron#260]
## My Setup

 - __My OS name and version__: macOS 10.12.1
 - __My current app version__: 1.3.1 (15)

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

When I cite someone via the `/direct/USERNAME?msg=MESSAGEID` link, the timestamp only shows the time, but not the date. This is no problem if the citation is from the same day but might be quite confusing if the citation is from another day.

This is probably a minor thing, but I thought its worth sharing.

**Comment by alexbrazier** [comment]
This is a issue with the main Rocket.Chat application, rather than the electron app.

I have recreated it in the main repo so this can be closed.
