### ISSUE TITLE
Channels are still shown in app while having been deleted on the server

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat.Electron#261]
## My Setup
My OS name and version: Elementary OS Loki (Ubuntu 16.04 Spin-Off) x64
My current app version: 1.3.1

[x] I have tested with the latest application version
[x] I can simulate the issue easily

## Description

I recently experimented a little with the slack import. I imported dumps from slack, rolled back the complete mongodb (with mongorestore). So of course, after the restore, some channels that were present when the slack import was done, were not present anymore after the rollback. So far that is expected behaviour.

#### Current Behavior

The electron app still shows these channels as being present and when I try to join a channel (that obviously can't exist anymore because mongodb has been rolled back), the following error is shown:
![screenshot](https://cloud.githubusercontent.com/assets/179595/20383841/a1faf130-acb1-11e6-8ea2-b984ae76324a.png)

#### Expected Behavior

Somehow, the channels must have been cached in the app, so I guess this cache has to be adjusted to update the list of channels that are being cached. One would expect channels that are not present on the server anymore would not be shown to users of the electron app.

Cheers
Thomas

**Comment by engelgabriel** [comment]
This is a cache issue on the main app, so I close this in favor of https://github.com/RocketChat/Rocket.Chat/issues/5306
