### ISSUE TITLE
duplicate "productName" in package.json

### ISSUE THREAD

**Issue by selfisekai** [RocketChat/Rocket.Chat.Electron#2616]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Alpine Linux edge

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.17

### Rocket.Chat Server Version

n/a

### Describe the bug

package.json contains a value for the key `productName` twice. this leads to an error in some JSON parsers (namely, serde_json)

### How to Reproduce

`tasje pack --config electron-builder.json`
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("duplicate field `productName`", line: 136, column: 15)', src/main.rs:88:84
```

### Describe your Expected behavior

`productName` defined once, package.json parsing properly anywhere

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Fixed, thank you!
