### ISSUE TITLE
"no such file or directory (certificate.json)" console error on Mac OSX

### ISSUE THREAD

**Issue by svfx** [RocketChat/Rocket.Chat.Electron#262]
## My Setup

 - __My OS name and version__: Mac OS X 10.10.5
 - __My current app version__: Version 1.3.1 (15)

- [ x] I have tested with the latest application version
- [ x] I can simulate the issue easily

#### Current Behavior
When executing the Rocket.Chat client program via Terminal on Mac, we get the following output in the Terminal window:

_{ [Error: ENOENT: no such file or directory, open '/home/[user]/Library/Application Support/Rocket.Chat+/certificate.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/steve/Library/Application Support/Rocket.Chat+/certificate.json' }
{ [Error: ENOENT: no such file or directory, open '/home/[user]/Library/Application Support/Rocket.Chat+/certificate.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/steve/Library/Application Support/Rocket.Chat+/certificate.json' }_

We do not see this error occuring when executing version 1.2.0 nor does the certificate.json file exist in the ~/Library/Application Support/Rocket.Chat directory for the 1.2.0 version.

The application does seem to load up fine without any adverse reactions so far, but I would rather resolve the issue so that our users are not presented with the error.  Any advice would be greatly appreciated.  Thanks!

#### Expected Behavior
The expected behaviour (and what happens when running the 1.2.0 version) is no text returned to the Terminal window at all - save for process information if run with an appended '&'.

**Comment by engelgabriel** [comment]
fixed on 2.1.0
