### ISSUE TITLE
Settings lost when app replaced on Mac

### ISSUE THREAD

**Issue by jelockwood** [RocketChat/Rocket.Chat.Electron#2627]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Operating System Version

13.2.1

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.0

### Rocket.Chat Server Version

4.8

### Describe the bug

Rocket.Chat desktop app for macOS does have a built-in update mechanism and this works fine. However it leaves you at the mercy of users utilising this mechanism.

In enterprises patching apps is regarded as something that needs to be more rigorously managed and therefore is often done under centralised control via various IT tools. In my case I am using two widely used open source tools commonly used in the Mac world.

The first is [AutoPkg](https://github.com/autopkg/autopkg) which is responsible for checking authors websites and downloading new updates and then subsequently adding those updates to a IT managed repository. AutoPkg is controlled via a series of 'recipes'.

In my case my repository is managed by the second tool called [Munki](https://github.com/munki/munki). The Munki client installed on each Mac regularly checks the repository for new updates and makes them available to users. Munki also allows defining settings to enforce updates by a particular deadline.

For Rocket.Chat I am using an AutoPkg recipe which monitors the Rocket.Chat Electron for Mac GitHub repo and downloads new releases and then uploads them to my Munki repo. The recipe is downloading the DMG (Disk Image) from the GitHub release page. Munki supports Apple Installer Packages, drag and drop installs usually provided in the form of a disk image containing just the app and some other install mechanisms. As mentioned in this case AutoPkg is downloading the disk image which Munki would 'drag and drop' the contained app into the client Mac's Applications folder.

Munki on the client Mac is _successfully_ downloading the disk image from the repo, mounting it, and dragging and dropping the app in to the Applications folder. This works fine for the initial deployment, the resulting app runs fine.

However I am finding that when a new version is deployed to the client Mac the drag and drop mechanism obviously will be completely overwriting the entire app. This normally _should not_ cause any problems. I have noticed that when the newer Rocket.Chat app is launched it asks the user to once more enter the server name and login as if this was the first time. Whilst I can understand the user having to login again it should not be necessary to re-enter the server address. I would be expecting it to default to the previous server address which again I would expect to be stored in a Rocket.Chat preference file on the Mac.

The (mis)behaviour implies that either the server address is not stored anywhere which is clearly not true since quitting and relaunching the app does show that Rocket.Chat  _does_ remember the server address and login, or what I believe to be the case that this information is being stored _inside_ the app itself. I believe that apps storing settings _inside_ themselves is incorrect behaviour. All settings should be stored _outside_ the app either in /Library/Preferences or in each users individual home directory e.g. /Users/username/Library/Preferences aka ~/Library/Preferences

Since the way Munki is 'updating' the app is replacing the entire /Applications/Rocket.Chat.app/ folder any settings store in that are also getting lost.

I therefore consider this to be incorrect behaviour i.e. a _bug_.

### How to Reproduce

How to reproduce.

1. Install Rocket.Chat on a Mac by dragging to the /Applications folder
2. Launch Rocket.Chat enter server address and login
3. Quit Rocket.Chat
4. Relaunch Rocket.Chat - confirm it remembers the server address and login
5. Now quit Rocket.Chat again
6. Drag a new updated copy of Rocket.Chat to the /Applications folder
7. Launch the new Rocket.Chat app

### Describe your Expected behavior

Expected result -

Rocket.Chat to remember the server address and login

Actual result -

On launching the new Rocket.Chat it does not remember the server address or login and asks for both these details again.

### Anything else

This problem happens every time the app is replaced.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Hello @jelockwood, we dont have experience with this two tools.
But the user data path is `/Users/username/Library/Application Support/Rocket.Chat`.
Inside that it stores the `config.json` file that stores the server data and stuff.
The login is done and stored on the browser storage, them if you delete the data of the application it of course will delete the session.

I dont have this problem on my tests. What versions you had this problem?

**Comment by jeanfbrito** [comment]
No problem, if this happen again please mention me and lets fix it.
