### ISSUE TITLE
Cannot be opened because it is from an unidentified developer

### ISSUE THREAD

**Issue by thinhcnb297** [RocketChat/Rocket.Chat.Electron#2634]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Operating System Version

mac os ventura 13.1

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.9

### Rocket.Chat Server Version

4.8.2

### Describe the bug

Cannot be opened because it is from an unidentified developer

### How to Reproduce

build release

### Anything else

<img width="355" alt="Screenshot 2023-04-07 at 17 53 12" src="https://user-images.githubusercontent.com/49717831/230597395-9cb4c252-9dad-4399-a39b-5d2e1bfbb599.png">

### Are you willing to submit a code contribution?

- [X] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Hello, you need to sign the build with Apple Certificates to this work.
