### ISSUE TITLE
Unread messages count not updated on server icon - 3.9.2

### ISSUE THREAD

**Issue by mgadek007** [RocketChat/Rocket.Chat.Electron#2640]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.2

### Rocket.Chat Server Version

4.8

### Describe the bug

After reading all unread messages the server icon still shows the number of unread messages.
![image](https://user-images.githubusercontent.com/39486541/231698818-f2521123-242c-4411-b722-99150fc02bb3.png)

Refresh server and restarting the application and clear cache do not help

### How to Reproduce

1. Instal desktop version 3.9.2
2. Have an unread message
3. Read the message 
4. Check the server icon status 

### Describe your Expected behavior

The count of unread messages will be updated

### Anything else

Downgrade to 3.9.1 resolve problem

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by coleman-rik** [comment]
I've got a similar problem, the tiny red dot, with the white dot in the center, in the tray icon that signifies unread messages never goes away. Also version 3.9.2 Windows 10.

**Comment by mgadek007** [comment]
Works in 3.9.3 😄 
Thanks
