### ISSUE TITLE
Open Video Chat using Application Window setting not obeyed in 3.9.2

### ISSUE THREAD

**Issue by eyck** [RocketChat/Rocket.Chat.Electron#2641]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.2

### Rocket.Chat Server Version

4.8.2

### Describe the bug

After upgrading the desktop client to 3.9.2 the setting of 'Open Video Chat using Application Window' does not make any difference anymore, the vido chat is always opened in the systems default browser.

Maybe  #2638 causes this.

### How to Reproduce

1. Go to settings
2. Swith on 'Open Video Chat using Application Window'
3. Start a video call

### Describe your Expected behavior

The video call should be opened in an application window and not a web browser

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
We fixed it on 3.9.3. Please update and tell us if it continues.

**Comment by eyck** [comment]
Works now as expected. THX!

**Comment by stylefish** [comment]
this occurs again on windows and linux platform with 3.9.9 since rocket.chat 6.4 upgrade (6.4.5 in our case)
