### ISSUE TITLE
New official release

### ISSUE THREAD

**Issue by Mte90** [RocketChat/Rocket.Chat.Electron#265]
## Description

The last stable release is 1.3.1 but there is the 3.0.0 as zip

#### Current Behavior

For the 1.3.1 there is a new version with packages for all the OS

#### Expected Behavior
Release a new ones with the packages for all the main OS

**Comment by graywolf336** [comment]
Those aren't releases, those are tags which come from the upstream project if I am not mistaken.

**Comment by Mte90** [comment]
Ok so the question remain, what is the latest version? there are other packages?
I downloaded the repo and tried to generate a new build but is only a folder without a deb package as example.

**Comment by graywolf336** [comment]
Whichever version is on our home page is the latest. I don't know the build process, so you would have to look into how to generate that yourself.

**Comment by Mte90** [comment]
I talk about the latest version of the electron package, if you go on release page there is the 1.3.1 but as I said the latest is 3.0.0 but there are no package for install it.

**Comment by graywolf336** [comment]
And as I said, those are just tags of the upstream branch. We don't have a v3 release.

**Comment by Mte90** [comment]
Ah okay I was thinking that is the latest release, usually when there is a new tag there is also a release especially with big jump of the major version like this one.
Thank you for the patience, I will wait for a new official release :-)

**Comment by graywolf336** [comment]
Yes, but we have an upstream repository we branched off of and we get their tags as a result of merging down thus unless it says "latest release" on the releases page and not "tags", then that's not a release from us. 👌
