### ISSUE TITLE
Ctrl + k user / group search reloads the page

### ISSUE THREAD

**Issue by dazoot** [RocketChat/Rocket.Chat.Electron#2653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10, latest Mac

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

3.9.3

### Rocket.Chat Server Version

6.1.4

### Describe the bug

Ctrl + k fast search reloads the page when selecting the matched user / group.

### How to Reproduce

I hit Ctrl + K to search a user / group. 
Seems arrows are not working.
I am trying to select the user (one match).
Enter on the user (i think).
Client reloads (also in browser mode, page reloads).

### Describe your Expected behavior

I would like to hit ENTER on the user and switch to that conversation (used to work before).

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by beschoenen** [comment]
This is happening since 6.0.0 for me.

**Comment by aadarsh-nagrath** [comment]
Yes this happens sometimes, not mostly, but it happended when i tried this after reading this issue

**Comment by preeesha** [comment]
@dazoot, thanks for report the issue. I would suggest you to upgrade the server version to the latest 6.6.0.
I have tried almost 30-35 times, it's not there now.

Let me know if you still face this.
Thanks.

**Comment by dazoot** [comment]
Seems true for 6.6.0. No more reloads.
