### ISSUE TITLE
How to pre-define server list?

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Electron#267]
I want to predefine server list and disable connect screen for client. How can I do it?

**Comment by djmha** [comment]
I also need this one.

**Comment by Nosferous** [comment]
I may have a solution for you on the OSX side: 
I added the server my end-users were supposed to connect to and hid the server list on a clean account/install of Rocket.Chat.Electron. 

I then copied this directory from that configuration:
~/Library/Containers/chat.rocket/

I then pushed that to the same path of all other home users on existing machines, as well as I set that up in the User Template folder so any new user account will pull the settings.

It has worked successfully on all 80 or so machines I have applied this strategy to. We are mostly an OSX environment so I do not have any experience tips with other deployments.

**Comment by dcbell** [comment]
I'd love to push this out to all my users, but until we have this feature, its kinda dead in the water. Too confusing for your average user. Needs to be something we can deploy, then they can just click to run with no more thought. If you combined this function (pre-defined servers) with a deployable MSI, it would be perfect.

**Comment by al1k** [comment]
We can build MSI (according to building [manual](https://github.com/electron-userland/electron-builder/wiki/Options), but we can't add serverlist into it.

**Comment by engelgabriel** [comment]
Ref: https://github.com/electron-userland/electron-builder/wiki/Options#SquirrelWindowsOptions

**Comment by graywolf336** [comment]
Wonder if we could check for a file (servers.json) in the installation directory of Rocket.Chat on first load and if that is defined then use that? That file would have to be pushed with Group Policy or something like that.
