### ISSUE TITLE
Server 0.48.1. file sending in Rocket.Chat.Electron does not working, at all!

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat.Electron#268]
With server 0.48.1 with Rocket.Chat.Electron 1.3.1 you cannot download file any way, this stop to work at all. Totally useless desktop client..... for now.
Of course workaround, you must open WEB and login to chat server, then why we need this client?!? 👎

**Comment by Nosferous** [comment]
Same issue - Also having download issues with server 0.48.1 and Electron 1.3.1

Previously the download icon in the attachments list right-side bar would work (in-line message download icon wouldn't, there is an open issue ticket for that one). Now the attachments list no longer works. The download options have further reduced.

Only solution in-app is to drag attachment out from message, only tested with images so far. But the file name link and download icon do not work message in-line or attachments list. This is going to halt my deployment I was about to do unfortunately.

**Comment by LXSysadmin** [comment]
Really sad.... people are very angry about this.

**Comment by alexandre-zia-movile** [comment]
Having this issue also, please fix this with priority, we have hundreds of users complaining

**Comment by engelgabriel** [comment]
Closed on https://github.com/RocketChat/Rocket.Chat/issues/5236
