### ISSUE TITLE
file extension

### ISSUE THREAD

**Issue by kertiskz** [RocketChat/Rocket.Chat.Electron#2688]
When saving a file from an application, the file extension disappears.

<a href="https://ibb.co/qy3Xfzp"><img src="https://i.ibb.co/1vth53T/2023-06-21-211730.png" alt="2023-06-21-211730" border="0"></a>
When working through a browser, this problem does not arise.

<a href="https://ibb.co/tKdK1pD"><img src="https://i.ibb.co/JthtSjH/2023-06-21-211925.png" alt="2023-06-21-211925" border="0"></a>
Operating system Windows 11

**Comment by kertiskz** [comment]
this is true for windows 7/10/11, on which the "show file name extension" attribute is not set

**Comment by jeanfbrito** [comment]
Nice catch! I always use enable to show them, I will raise as a Bug and take a look asap.
Thanks for reporting it!
