### ISSUE TITLE
Cannot connect to server from electron app

### ISSUE THREAD

**Issue by petermezei** [RocketChat/Rocket.Chat.Electron#269]
## My Setup
Ubuntu 16.04 desktop
rocket chat 1.3.1

Hi guys,
just created a rocket chat server on ubuntu 16.04 server, you can find it here: http://40.85.99.126:3000/

I can manage it online, but after downloading your desktop app, i cannot connect to it.

Desktop app version is 1.3.1. I add the server url: http://40.85.99.126:3000/, and nothing. You demo account works, but when I click the registered new server, nothing happens, the screen freezes and displays the previous account, but not responsive.

Its like having a server connection issue somewhere, but not sure.

On the screen the first server is your public demo server, the second is our demo server. You can see, the second is selected and nothing happens, the app body displays the content from your demo server.

![image](https://cloud.githubusercontent.com/assets/18461114/21307363/77d4885c-c5d5-11e6-98b1-937f1e3cfb00.png)

**Comment by petermezei** [comment]
in console there is a warning:

![image](https://cloud.githubusercontent.com/assets/18461114/21310371/5580bd04-c5e2-11e6-8e8f-e2a284f221b4.png)

**Comment by petermezei** [comment]
Haho, anyone?

**Comment by petermezei** [comment]
Guys why dont you reply? Anybody? I am stacked with the trial period.

**Comment by petermezei** [comment]
Anyone please? Could you help me? We just try to evaluate rocket chat for our company, but till now its not working, and we dont have any help from your side for 2 days.

**Comment by petermezei** [comment]
Wohooooooo

**Comment by petermezei** [comment]
Wohooooo

**Comment by engelgabriel** [comment]
Please try again with the latest version of the server and the version 2.1.0 of the electron app.
