### ISSUE TITLE
2.0.0 doesn't have binaries for download

### ISSUE THREAD

**Issue by LFCavalcanti** [RocketChat/Rocket.Chat.Electron#272]
Hello everyone!

I see a new release with the Electron version updated, but the binaries on the site are still in the old version.

**Comment by LFCavalcanti** [comment]
@engelgabriel , this should not be closed yet, since the Windows Binaries are not signed as per #273

**Comment by engelgabriel** [comment]
We have never signed windows binaries, this is still a work in progress.
