### ISSUE TITLE
How to automatically update Rocketchat clients on computers that don't have internet connection?

### ISSUE THREAD

**Issue by MarkVorkosigan** [RocketChat/Rocket.Chat.Electron#2755]
I want to automatically update Rocketchat clients on computers that don't have internet connection. Is this possible to do it stealthily for users?

**Comment by 72tlukas72** [comment]
If you can edit DNS record used by clients and issue a valid certificate (for example from company CA), You can override github.com hosting and point to local server.

**Comment by jeanfbrito** [comment]
You will need to configure some update automation for the users.
