### ISSUE TITLE
rocket chat will not load

### ISSUE THREAD

**Issue by jonasjwilson** [RocketChat/Rocket.Chat.Electron#2758]
## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by jonasjwilson** [comment]
rocketcht willnot load

**Comment by erebion** [comment]
Meaning what exactly?

**Comment by tom666-debug** [comment]
Maybe he is expiring the same issue as I do after applying the latest updates on server side. Right after I have updated RC on server side, all connected (Windows Desktop) clients become dysfunctional. 

All I can see than on client side is a grey screen with the "3 dot animation". The fix is easy, just do a "clear cache" followed by a "reload server". But as not all users understand how to get it fixed, I consider this as a big Issue ...

**Comment by ra1qcw** [comment]
> Maybe he is expiring the same issue as I do after applying the latest updates on server side. Right after I have updated RC on server side, all connected (Windows Desktop) clients become dysfunctional. 
> 
> All I can see than on client side is a grey screen with the "3 dot animation". The fix is easy, just do a "clear cache" followed by a "reload server". But as not all users understand how to get it fixed, I consider this as a big Issue ... 
> 
> I have observed this behaviour for the first time after I have updated RC to version 6.4.1. Mobile clients seems not to be affected by this.

Same problem.

**Comment by paulchen** [comment]
> Maybe he is expiring the same issue as I do after applying the latest updates on server side. Right after I have updated RC on server side, all connected (Windows Desktop) clients become dysfunctional.

This problem is not limited to the Electron client: RocketChat/Rocket.Chat#30717

**Comment by jonasjwilson** [comment]
ive got on rc seekingalpha chat

**Comment by da-avidid** [comment]
> Maybe he is expiring the same issue as I do after applying the latest updates on server side. Right after I have updated RC on server side, all connected (Windows Desktop) clients become dysfunctional.
> 
> All I can see than on client side is a grey screen with the "3 dot animation". The fix is easy, just do a "clear cache" followed by a "reload server". But as not all users understand how to get it fixed, I consider this as a big Issue ...
> 
> I have observed this behaviour for the first time after I have updated RC to version 6.4.1. Mobile clients seems not to be affected by this.

Our team is experiencing the same issue as well. 

    Operating System: Mix of Windows (10/11) and Ubuntu (22.04) machines.
    App Version: 6.4.5
    Installation type: Snap install (Ubuntu 22.04)

This "constant refresh" affects both the Desktop Application as well as the Webapp (Firefox/Brave).

The "clear cache and server refresh" does fix the issue temporarily but the problem comes back.

**Comment by MartinSchoeler** [comment]
This is issue is not specific to the electron app, it is a core issue, so let's move the conversation to https://github.com/RocketChat/Rocket.Chat/issues/30990

Closing this for now, thanks!
