### ISSUE TITLE
Issue with interface scaling

### ISSUE THREAD

**Issue by CyberStranger** [RocketChat/Rocket.Chat.Electron#2761]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

### Operating System Version

Windows 10, Debian 12 Bookworm XFCE

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.9

### Rocket.Chat Server Version

6.4.2

### Describe the bug

I have encountered an issue with the interface scaling in RocketChat.Electron. When I attempt to adjust the scaling by using keyboard shortcuts such as **Ctrl +** or **Ctrl -** or **Ctrl + mouse scroll wheel**, the scaling of both the text and interface remains unchanged.

### How to Reproduce

1. Launch RocketChat.Electron.
2. Attempt to increase or decrease the scaling of the interface. By hotkeys.
3. Notice that the scaling of the text and interface does not change accordingly.

### Describe your Expected behavior

I would expect that when using the mentioned keyboard shortcuts or mouse scroll wheel, the scaling of the text and interface would adjust accordingly.

### Anything else

In the previous version of the RocketChat.Electron client (3.9.6), which was installed prior to the current version, all of these functionalities related to interface scaling were working correctly. However, after updating to the new version, the mentioned issue with interface scaling occurred. 

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by AK4266** [comment]
Hey, I would like to work on this issue. Can you assign it to me

**Comment by jeanfbrito** [comment]
Fixed on version [3.9.10](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.9.10)
