### ISSUE TITLE
Rocketchat Windows Client  3.9.9 File Attachments 403 Error

### ISSUE THREAD

**Issue by rgoerner** [RocketChat/Rocket.Chat.Electron#2764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.9

### Rocket.Chat Server Version

6.4.5

### Describe the bug

Error 403 when clicking on a received file on the chat,
only getting this error on Windows App, but not in browser / Android App

### How to Reproduce

Just ask a meeting-partner to send you a file,
clicking on it, will result in 403 error

### Describe your Expected behavior

Download should work

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by rgoerner** [comment]
I found a workaround:
Go to Admin, Settings, File uploads,
then, protect uploaded files (was on), toogle it to off, and on again, and voila, it works,
seems, the trigger here re-changed something, I am not sure what in detail, but this helped and solved the issue.

**Comment by rgoerner** [comment]
Something to add:

- Clicking on received attachments will result in 403 error
- if you login to rocketchat using the normal browser, and go back to the windows client, then, the downloads works
- seems to be a kind of cookie issue or that, I suppose, the client does not collect / send full cookieset
- we tried to reset app data and reload on the client, but not working

**Comment by rgoerner** [comment]
Also to mention, we did an upgrade from 3.0.7 to 3.9.9 on the client-side.

**Comment by rgoerner** [comment]
Seems similar to: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2723

**Comment by 72tlukas72** [comment]
Same as [#30737](https://github.com/RocketChat/Rocket.Chat/issues/30737)

**Comment by EEFYURR** [comment]
For statistics, I've got this behaviour too when updated from server v6.2.2 to 6.4.4 without clients changing

**Comment by rrmt23** [comment]
We have exactly the same problem.
Unfortunately, she is being ignored.

Each user needs to be explained that they need to press "cloud"

**Comment by als999** [comment]
The convenience of working with attached files is really lacking. Currently, to open a file, you need to download it (by specifying the location), open the desired folder, find the file and double-click it to open it in the associated application. For comparison, try performing a similar operation in Telegram.
Ease of working with attachments is an important functionality. Please don't ignore it.

**Comment by bilel** [comment]
![image](https://github.com/RocketChat/Rocket.Chat.Electron/assets/291110/bdf3a957-0589-4429-86cc-bd10b464cb93)

The client version should keep the link target inside the app
Otherwise we should login in the default browser ! Which is not cool.

**Comment by jeanfbrito** [comment]
Please update the server to version 6.6.0, there was fixes made on this.

**Comment by rgoerner** [comment]
@jeanfbrito I did an upgrade to 6.6.0
still opening in browser, not in chat, client is 3.9.12 on Windows
any ideas ?
