### ISSUE TITLE
Endless reload

### ISSUE THREAD

**Issue by dnl-jst** [RocketChat/Rocket.Chat.Electron#2766]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 11, macOS Ventura

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.9

### Rocket.Chat Server Version

multiple, latest stable

### Describe the bug

Multiple different RocketChat instances infinitely reload the content of the window. The interface shortly appear, then directly vanishes and reloads everything forever again.

### How to Reproduce

start the app

### Are you willing to submit a code contribution?

- [X] Yes, I am willing to submit a Pull Request!

**Comment by aachekalov** [comment]
Got the same. Fixed by resetting app data ('Help' Menu)

**Comment by CvH** [comment]
that problem exist still today at 6.4.4 at the Webui and at the Electron client so likely yet another core RC issue that is unfixed - so nothing particular to the client

**Comment by MartinSchoeler** [comment]
Indeed, this is a core issue, let's move the conversation to https://github.com/RocketChat/Rocket.Chat/issues/30990

I'll be closing this one, thanks!
