### ISSUE TITLE
Get Link appears to be broken due to a lack of permission

### ISSUE THREAD

**Issue by Loki-Afro** [RocketChat/Rocket.Chat.Electron#2769]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Fedora 38

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.9

### Rocket.Chat Server Version

5.4.8

### Describe the bug

Get Link appears to be broken due to a lack of permission on chromium and desktop app.
You will not be able to get a Link to a message using the 3 dots menu on a message -> more -> Get Link

### How to Reproduce

1. Go to any message
3. GetLink

### Describe your Expected behavior

Link is copied to the clipboard

### Anything else

it worked in 3.9.3, now with 3.9.9 it doesn't

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by Christopher-fr** [comment]
Hi, we have the same problem with the Windows app (v 3.9.9) and server 6.4.4.

**Comment by ebyrne242** [comment]
Same issue here on the Mac app 3.9.9 and server 6.4.5.  Works fine in browsers or mobile client.

Someone opened a ticket on the server as well, though it seems more likely to be a client issue since it only affects the desktop apps.  https://github.com/RocketChat/Rocket.Chat/issues/30724

**Comment by caskelly** [comment]
@jeanfbrito - can you take a look at this issue and provide your assessment?

**Comment by jeanfbrito** [comment]
@Loki-Afro please test the version 3.9.10 of Desktop client.

@ebyrne242 Yes, this can be a cache issue on the update to 6.4.5.
I just checked and no issues happened on 3.9.9 and 6.4.5 for me, but if the issue continues, please remove the server and add again, this must fix it.

If not yet, please mention me.

**Comment by Loki-Afro** [comment]
@jeanfbrito working here on 3.9.10 right now, thank you!

what was the issue?

**Comment by jeanfbrito** [comment]
I really think that it was the cache issue that happened on server update. But if it happens again please reach me, I will be closing the issue then.
