### ISSUE TITLE
Right Click and Quit/Show Gone From Tray Icon in v2

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Electron#277]
The right click and quit is gone from the tray icon along with the show.

**Comment by rodrigok** [comment]
@graywolf336 can you test again?

**Comment by engelgabriel** [comment]
It is working on the Mac.
@sampaiodiego can you test this on linux?

**Comment by sampaiodiego** [comment]
they're gone!
![image](https://cloud.githubusercontent.com/assets/8591547/21846066/6e1c6fc8-d7dc-11e6-9316-5b7a02a69f3d.png)

**Comment by rodrigok** [comment]
Closed by #288
