### ISSUE TITLE
Desktop screen sharing in Jitsi has poor resolution

### ISSUE THREAD

**Issue by KodoGit** [RocketChat/Rocket.Chat.Electron#2785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.9

### Rocket.Chat Server Version

6.4.5

### Describe the bug

Desktop screen sharing in Jitsi has poor resolution when a demonstrator uses Electron version of Rocketchat client.
Broadcasting resolution can be 720p or 360p or even less. With text blured  and unreadable.
No problems with Web client of Rocketchat.

### How to Reproduce

1. Open Electron version of Rocketchat 
2. Start Jitsi conference
3. Start desktop sharing in Jitsi conference
4. Demonstrate some text like web page, tables or text editor.
5. Connect to that Jitsi conference from another RC client.
6. See blured, low resolution image.
7. Move your mouse cursor over connection quality of screen sharing tile in Jitsi
8.  See exact resolution numbers.

### Describe your Expected behavior

1. Open Electron version of Rocketchat 
2. Start Jitsi conference
3. Start desktop sharing in Jitsi conference
4. Demonstrate some text like web page, tables or text editor.
5. Connect to that Jitsi conference from another RC client.
6. See non blured, readable text with resolution of broadcaster's monitor.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by KodoGit** [comment]
Fixed by upgrading to 3.9.10 Rocketchat Electron client

**Comment by KodoGit** [comment]
Happend again. Looks like conference with only 2 users is not affected 
Three and more - even webcameras give poor resolutions.

**Comment by MichaelErmer** [comment]
We are experiencing the same; if you use Rocket Chat in the browser, all videos/screens share in 4k/HD; if the Electron app is used, its only allows 320p for videos and screen shares...

**Comment by moell9** [comment]
Please have a look here, we have more or less the same: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2808

**Comment by Killbunny** [comment]
We're having the same problem with the electron client when more than 2 people join a call.
Both Client and Server up-to-date + locally hosted Jitsi server ( We had the same problem with public jitsi too).
As a temporary work around we've sent a notification to our users to disable "Open Video Chat using Aplication Window"

**Comment by moell9** [comment]
Same problem with client 3.9.12.

**Comment by moell9** [comment]
Same problem with client 3.9.13. That's very frustrating.

**Comment by jeanfbrito** [comment]
I opened an issue in Jitsi repo, awaiting their reply to see what we can do. https://github.com/jitsi/jitsi-meet/issues/14396
For now, you can disable `Open Video Chat using Application Window` on the settings, making it open on the web browser.
