### ISSUE TITLE
Screen share not working

### ISSUE THREAD

**Issue by brf153** [RocketChat/Rocket.Chat.Electron#2787]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Ubuntu 22.04

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.9

### Rocket.Chat Server Version

6.5.0-rc.18

### Describe the bug

![Screenshot from 2023-12-02 08-40-33](https://github.com/RocketChat/Rocket.Chat.Electron/assets/107868772/ba1519b1-2a49-462f-a338-6a96a86791d9)

Just showing this loader for the past 20min. I am not being able to share my screen.

### How to Reproduce

Just make a video call in any group and try to share screen.

### Describe your Expected behavior

I should be able to share my screen.

### Are you willing to submit a code contribution?

- [X] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Please try our latest version 3.9.11. 
There is a button on configurations to clean permissions for screen sharing that you can try too:
![image](https://github.com/RocketChat/Rocket.Chat.Electron/assets/1177482/50e5ed08-36bf-4efa-a36f-fc7622f2c297)

**Comment by brf153** [comment]
@jeanfbrito There is only a 3.9.9 version available in the Ubuntu software store. Also when I check your docs it tells me to install using the command `sudo snap install rocketchat-desktop`. It will also install the same version as 3.9.9. How do I install the version 3.9.11? Never mind I have cloned the repo and running the server using yarn start. The screen sharing works there with a minor issue. I will raise an issue related to it.

**Comment by brf153** [comment]
Shall we close this issue?

**Comment by pitwegner** [comment]
same thing happens on Mac OS, no matter if I install App Store version or via home-brew. Clearing Screen Capture Permissions does not do anything. Manually allowing screen capture in settings also doesn't help. Colleagues on Linux and Windows are experiencing the same issue.

**Comment by jeanfbrito** [comment]
@pitwegner can you share a screen capture of what is happening? Maybe opening a new issue would be good as the author of this one said to closed this one. I need more information to help you.
