### ISSUE TITLE
Drag&drop to channel not working

### ISSUE THREAD

**Issue by msklywenn** [RocketChat/Rocket.Chat.Electron#280]
Windows 10 64bits
Rocket chat client : 2.0.2 (latest)
Rocket chat server : 0.48.2 (latest)

Just try to drag & drop a bmp, gif, png, jpg, psd or whatever to a channel, it just displays a forbidden icon. It should just appear as a copy/paste and upload to channel, as it was doing on 1.3.1.

**Comment by rodrigok** [comment]
@msklywenn Can you test the latest beta? https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.1.0-beta.2

**Comment by msklywenn** [comment]
Same thing :/

**Comment by rodrigok** [comment]
@msklywenn Is the upload working if you click on upload button and select that file?

**Comment by msklywenn** [comment]
Oh that was already working. Although a bit randomly and gif upload was insanely slow. That was going to be the next issue I wanted to open... (one thing at a time :D)

Just tested, gif upload works fine & nice now ! Through the upload button.

Only the original issue remains to be fixed :)

**Comment by rodrigok** [comment]
@msklywenn And the drag and drop works via web browser?

**Comment by msklywenn** [comment]
Yes. It also works with rocket chat 1.3.1

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
