### ISSUE TITLE
in RC Desktop i have message "Workspace unsupported".What will happen to the application when the deadline expires?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.Electron#2809]
Hi all!

in RC Desktop i have message "Workspace unsupported".What will happen to the application when the deadline expires?
Will I be able to continue using the app?

I have community version and dont uses cloud services.

**Comment by jeanfbrito** [comment]
https://docs.rocket.chat/customer-center/support-center/premium-support-plans/support-prerequisites-and-version-durability
