### ISSUE TITLE
Is it possible to turn off spell check?

### ISSUE THREAD

**Issue by pzgz** [RocketChat/Rocket.Chat.Electron#281]
Most of time, we are using rocket.chat to discuss about codings, and spell check is really annoying for adding underwave to words. Uncheck the language setting in the right popup menu doesn't work, and there's no menu for disable the spell check.

**Comment by rodrigok** [comment]
@pzgz The next release will allow you to uncheck all languages (and will not highlight all words).

Can you test our latest beta? https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by pzgz** [comment]
@rodrigok Thanks a lot, just tested with `Version 2.1.0 (2.1.0.175)`, and confirmed that uncheck all languages will disable the spell check.

**Comment by pzgz** [comment]
Looks like the issue was back again in `2.2.0`, check is still there even uncheck all spell checks. I revereted to `v2.1.0` without no issue.

And there's another issue, this selection was not persisted between each launch, have to set the flags again if quit and re-enter the app.

**Comment by fenjen** [comment]
@rodrigok Bug revived. It seems I'm not able to permanently disable spell check, again :-(  (Version 3.9.6.) I need to disable spell check each time I start RocketChat.
