### ISSUE TITLE
No Notification of new messages in Rocket Chat Client 3.9.11

### ISSUE THREAD

**Issue by ultimatebash** [RocketChat/Rocket.Chat.Electron#2815]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [x] Linux

### Operating System Version

Ubuntu 22.04.3 LTS

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.11

### Rocket.Chat Server Version

6.5

### Describe the bug

When I receive new messages in Rocket Chat, I no longer get notifications in my Linux taskbar or in the Linux app itself. The only way I know I've received a new message is to check for a new message in each channel or check my phone since that's where the notifications are visible

### How to Reproduce

1. Open the Rocket Chat application
2. get a message

### Describe your Expected behavior

to get a notification for new messages, i havent read

### Anything else

everytime

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by ultimatebash** [comment]
seems like the notification works again, after waiting a few minutes, i was able to get the desktop notification, and the app notification, but the rocket chat icon in the task bar is missing?

**Comment by ultimatebash** [comment]
![image](https://github.com/RocketChat/Rocket.Chat.Electron/assets/143268383/e5ec7d28-7a11-44ef-aefa-0def9171203c)

**Comment by ultimatebash** [comment]
![image](https://github.com/RocketChat/Rocket.Chat.Electron/assets/143268383/9007b586-39b3-4fcc-94df-34efa00e2660)

**Comment by k3tiv** [comment]
#2767 I think its the same problem

**Comment by shoei101** [comment]
this is happening to us with version 3.9.12 desktop application. I know it was working with 3.9.11

**Comment by jeanfbrito** [comment]
Please update the server to 6.6.0.

**Comment by shoei101** [comment]
I know this is closed, but just letting you know server is already 6.6.0

**Comment by jeanfbrito** [comment]
@shoei101 can you provide a video showing what happens?

**Comment by shoei101** [comment]
> @shoei101 can you provide a video showing what happens?

not sure how to provide a video of not receiving an audio/visual notification? when I to to my preferences and test notifications (on desktop app), both audio and video work. Even on iOS app and Web, we're not getting notified it's like the presence info isn't working? I may have been mistaking linking it to only the desktop app

**Comment by jeanfbrito** [comment]
> > @shoei101 can you provide a video showing what happens?
> 
> not sure how to provide a video of not receiving an audio/visual notification? when I to to my preferences and test notifications (on desktop app), both audio and video work. Even on iOS app and Web, we're not getting notified it's like the presence info isn't working? I may have been mistaking linking it to only the desktop app

I cant say precisely, but seems to be something with the user configuration. Like disabled notifications or if the user is on busy status it will not receive notifications too. 
I would say to test on another server and other machine to see if is a user configuration on the chat or on the OS.

**Comment by shoei101** [comment]
> > > @shoei101 can you provide a video showing what happens?
> > 
> > 
> > not sure how to provide a video of not receiving an audio/visual notification? when I to to my preferences and test notifications (on desktop app), both audio and video work. Even on iOS app and Web, we're not getting notified it's like the presence info isn't working? I may have been mistaking linking it to only the desktop app
> 
> I cant say precisely, but seems to be something with the user configuration. Like disabled notifications or if the user is on busy status it will not receive notifications too. I would say to test on another server and other machine to see if is a user configuration on the chat or on the OS.

We are seeing the same problem across all apps and the web portal where presence info is not updating and users Direct Message presence will show a user "online" when another app or the web will show them "away". Once a reload occurs on any of the specified methods, the presence info for them is updated.

**Comment by shoei101** [comment]
As an example, I can be logged into just one of those methods and I will not receive any notifications if someone sends me a message, even though I have been away for quite a while, much longer than the set value for the app, and I will not get any notifications at all. That includes push, desktop, or emails.

**Comment by shoei101** [comment]
This is NOT something that a lone user is complaining about. Us IT people are seeing the issue first hand and we know without a doubt we should be receiving notifications cause we have not changed anything.

**Comment by sdostanko** [comment]
I have a similar problem (version 3.9.14), the default sound is selected in the Direct messages and it does not work when I select any other sound it it starts working. In previous versions default sound was Chime as I understand, now nothing...
![Screenshot from 2024-04-04 18-23-47](https://github.com/RocketChat/Rocket.Chat.Electron/assets/40056437/26118eb2-6b0c-405c-830c-862d270506ea)
