### ISSUE TITLE
Notification problem with Release 2.1.0-Beta1

### ISSUE THREAD

**Issue by blaf78** [RocketChat/Rocket.Chat.Electron#282]
## My Setup

 - __My OS name and version__: Windows 8.1 Professional 64 Bits and Windows 10 Enterprise 64 Bits
 - __My current app version__: Release 2.1.0-Beta1

- [X ] I have tested with the latest application version (version 2.0.2 and 2.1.0-Beta1)
- [X ] I can simulate the issue easily

## Description

On a notification: The Rocket.chat's icon, in the traybar, is turning red but any notification's bubble appeared like the one I receive when I am connected trough a browser.

N.B. In the beta version, the **Test Desktop Notifications** button from the **preferences** page is not working (only tested on Windows 10)

**Comment by rodrigok** [comment]
@blaf78 Can you test the latest beta? https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.1.0-beta.2

**Comment by blaf78** [comment]
Here is my result with 2.1.0-beta.2:
with the **Test Desktop Notification**:
Sound: No
Rocket Icon in Traybar: Not Blinking 
Rocket Icon in Notification zone of the traybar: Black
Message's popup from notification zone: no

with a mention in a channel or with a personnal message:
Sound: Yes
Rocket Icon in Traybar: Blinking 
Rocket Icon in Notification zone of the traybar: Red
Message's popup from notification zone: no

**Comment by blaf78** [comment]
If I can do more to help, please let me know, I am logged to your demo server with the user: b.laflamme

**Comment by Sing-Li** [comment]
@blaf78  I've just tested on Window 10 with Beta 2 as well.

After installation, the cert error still shows.

However, I did get native notifications bubble when:

1) status is away (amber)
2) app is minimized or out of focus

THEN upon
either an @ mention from a channel
or a DM message

Could it be that some of your System -> Notifications & actions Settings in Windows 10 is off ?

Thanks.

**Comment by blaf78** [comment]
I didn't see any cert error but you were right for the notification restriction. It is in Windows, and now that's enabled, it's working fine ! 

So, excuse me for this "false" problem, I am grateful for the support I received.
