### ISSUE TITLE
"Reload" reloads wrong workspace

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.Electron#2843]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.13

### Rocket.Chat Server Version

6.6.0

### Describe the bug

Under certain circumstances, the functionality "View" -> "Reload" reloads the wrong workspace.

### How to Reproduce

1. Set up at least two workspaces in the desktop app.
2. Open the first one and click "View" -> "Reload". The workspace will be reloaded.
3. Open the second workspace and click "View" -> "Reload". The workspace will not be reloaded.
4. Navigate back to the first one and notice that it is being reloaded.

### Describe your Expected behavior

In step 3, I would expect the second workspace to be reloaded.

In step 4, I would expect the first workspace to be reloaded.

### Anything else

After reloading the first workspace, I did not find any way to reload the second workspace besides restarting the desktop app.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Nice catch! Thank you!
