### ISSUE TITLE
Menu options not available after adding server

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.Electron#2849]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Arch Linux

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.14

### Rocket.Chat Server Version

6.6.0

### Describe the bug

After adding a server to the desktop app, many options from the "View" menu are not available (i.e. they are greyed out). After a restart of the desktop app, the options become available.

### How to Reproduce

1. Add a server to the desktop app.
2. Click on the "View" menu.

https://github.com/RocketChat/Rocket.Chat.Electron/assets/404840/1e56ec28-4410-4742-8ce4-4b112c0391a8

### Describe your Expected behavior

The options "Reload", "Reload ignoring cache", "Open DevTools", "Open DevTools on all windows", "Back" and "Forward" are available.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by thesynthax** [comment]
It works on my system

**Comment by Ishanv5** [comment]
Same It works on my system as well as

**Comment by paulchen** [comment]
I can confirm that this issue does not occur in the current version of the Rocket.Chat Electron client (4.1.2).
