### ISSUE TITLE
Rocket.Chat.Electron could not yarn start

### ISSUE THREAD

**Issue by yaoyi601131548** [RocketChat/Rocket.Chat.Electron#2860]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Operating System Version

macOS 14.2.1

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.14

### Rocket.Chat Server Version

3.9.14

### Describe the bug

I can run "yarn start" successfully on Rocket.Chat.Electron 3.9.11, but when I upgrade to Rocket.Chat.Electron 3.9.14 and execute "yarn start," it throws an error.

[!] SyntaxError: Unexpected token 'with'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:117:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:218:14)
    at link (node:internal/modules/esm/module_job:67:21)

### How to Reproduce

yarn.
yarn start.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by RomeoIndiaJulietUniform** [comment]
Hii @yaoyi601131548  can you please specify which Node version you are using. Can you share the full error log please

**Comment by milux** [comment]
Updated: Fixed by switching to latest node.js LTS (20.11.1).

**Comment by Dark-Kernel** [comment]
This issue is fixed i guess and should be closed too.
