### ISSUE TITLE
Only main chat window is re-opened on launch on macOS

### ISSUE THREAD

**Issue by Feuermurmel** [RocketChat/Rocket.Chat.Electron#2862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Operating System Version

macOS 12.7.3 (21H1015)

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.14

### Rocket.Chat Server Version

6.7

### Describe the bug

After opening multiple chats in separate windows by shift-clicking on them in the chat list, closing and re-launching the app will only restore the main window, but not the chats opened in separate windows. I created this screen recording showing the current behavior:

https://github.com/RocketChat/Rocket.Chat.Electron/assets/50332/9ce35e73-b87d-4b79-91c6-e799f622b2a7

### How to Reproduce

1. Open Rocket.Chat.app.
2. Open some chats in separate windows e.g. shift-clicking on them in the chat list on the left.
3. Quit Rocket.Chat.app.
4. Open Rocket.Chat.app again.
5. Only the main window is restored, but not any of the other windows.

### Describe your Expected behavior

IMHO all chat windows should be restored when the application is opened.

### Anything else

The current behavior appears every time.

I have "Close windows when quitting an app" turned off in "General" in System Preferences.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Hey @Feuermurmel this is not a bug. We don't intend to reopen all the windows after quitting.
