### ISSUE TITLE
Back / Forward navigation slow and unresponsive

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat.Electron#2864]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Operating System Version

macOS 14.2.1

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.14

### Rocket.Chat Server Version

6.6.1

### Describe the bug

Since one of the last few RC upgrades the Forward / Back action in the desktop client reacts very sluggishly or even not at all (sometimes pressing the shortcut 2 - 3 times is necessary).

Both the shortcuts as well as clicking the menu items result in the same behaviour.

### How to Reproduce

1. Install the given versions
2. Navigate between a few channels
3. Try to use the Back / Forward actions

### Describe your Expected behavior

Back / Forward to work without delay and every time, like it did for years prior.

### Anything else

Happens every time

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by ulope** [comment]
@jeanfbrito Yes, Apple Silicon (Macbook Air M2)

I'll have to check with colleagues if they also experience this.

**Comment by jeanfbrito** [comment]
> @jeanfbrito Yes, Apple Silicon (Macbook Air M2) I'll have to check with colleagues if they also experience this.
> 
> > Can't the process get lagged?
> 
> Not sure what you mean by that

Sorry, slowed I mean. Did you have any customization on the server?
Can you say if this happens on our server `open.rocket.chat` too?
Its the first time I see this kind of report.
