### ISSUE TITLE
Rocket.Chat crashes after opening a chat

### ISSUE THREAD

**Issue by binse03** [RocketChat/Rocket.Chat.Electron#2874]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10 Enterprise

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.14

### Rocket.Chat Server Version

6.6.2

### Describe the bug

A work colleague of mine opens a chat with a specific employee. The program then freezes and you can no longer do anything. The toolbar at the top still works, but there are fewer clicks than before. (For example, "Help > Reload" is then grayed out. The problem can only be solved with a new installation or with "Help > Reset app data". But the chat still cannot be opened. But then other Chats are working again. No files were shared in the chat, only plain text and basic images.

### How to Reproduce

I don't know how he did it or how to reproduce it. The chat with the person still works for me on my PC.

### Describe your Expected behavior

The Chat opens without a crash.

### Anything else

When u need something (logs) please say me where i find it and i can post it for you. 

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Can you test our v4.0?
If it keeps crashing you should send us more information of whats going on?

**Comment by binse03** [comment]
> Can you test our v4.0? If it keeps crashing you should send us more information of whats going on?

We will try.
