### ISSUE TITLE
Ver 2.1.0 of Windows application is laggy and almost unusable 

### ISSUE THREAD

**Issue by adirwilliamson** [RocketChat/Rocket.Chat.Electron#289]
## My Setup

 - __My OS name and version__: Windows 10 x64 fully patched
 - __My current app version__: 2.1.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

With version 2.1.0 the Electron application is super laggy and almost unusable for me. Text entered into the chat window takes seconds to appear (for example a sentance can take upto ten seconds to appear). Copy pasting a URL into the chat window, selecting text etc all suffer the same. I have reproduced this on two difference Windows 10 machines (interesteling on one Windows 10 machine I tried it seemed fine).

If I go back to version 1.3.1 of the application everything is fine again. So this issue seems to be related to version 2.1.0 of the application.

**Comment by rodrigok** [comment]
What happens if you disable the spell checker?

To disable it you can right click on text field and unselect all languages.

**Comment by adirwilliamson** [comment]
Okay - so disabling the spell checker makes it work. I checked the settings on the machine that was working okay and the language that is enabled is en_US, on mine en_GB was enabled.

If I select only en_US then the spell checker works and the app performs as expected. It seems that having anything other that en_US selected as the language causes the bug.

**Comment by ZedTheYeti** [comment]
@adirwilliamson On your machine, was only en_GB enabled? I'm able to reproduce the issue by enabling multiple spell checking languages so there is definitely an issue here, but I don't have the en_GB dictionary to try and reproduce your issue.

**Comment by adirwilliamson** [comment]
@ZedTheYeti - yes the only language enabled was en_GB. 

It seems that enabling any of the en_* languages (with the exception of en_US) causes the issue for me - I tried with a few of the ones on my machine including en_NZ and en_AU and they all caused the same issue. When I tested there was only the one language enabled at a time.

**Comment by rodrigok** [comment]
@ZedTheYeti Which OS are you using?

**Comment by adirwilliamson** [comment]
A little update: we are seeing this issue on just about all our clients that are using version 2.2 of the app. For most of us the default selected language is en_GB and only some of us have en_US available to use, which fixes the issue, others don't have en_US so just have to disable the spell checker altogether to get the app usable.  Would be great to have a fix :)

**Comment by adirwilliamson** [comment]
@engelgabriel @alexbrazier @rodrigok 

We have just tested the 2.4.0 release and this does not seem to fix the issues we are having with the spellchecker. If we have any en_* language other than en_US selected typing in the message box is slow and laggy. The only solution is to either use en_US (which not all of our users have), or disable the checker.

**Comment by alexbrazier** [comment]
I think the bottleneck is calling `setDictionary` every time a word is checked. Maybe we could avoid this by setting the dictionary once if you only select one, however it will still have to be slower if using multiple dictionaries. Only other solution I can think of would be to detect languages and only switch if it detects a change e.g. if loads of words are being spelt wrong it can check for a change.
