### ISSUE TITLE
Rocket.Chat.Electron depends on outdated Electron version 22

### ISSUE THREAD

**Issue by buzo-ffm** [RocketChat/Rocket.Chat.Electron#2893]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Arch Linux rolling release

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.14

### Rocket.Chat Server Version

any

### Describe the bug

Please update to a recent Electron version.
Rocket.Chat.Electron still depends on the outdated version 22 (`"electron": "22.3.27"` in `package.json`). Arch Linux recently has dropped support for this old version, which renders the [AUR package rocketchat-desktop](https://aur.archlinux.org/packages/rocketchat-desktop) unusable. (I am the maintainer of that package.)

### How to Reproduce

Try to build this on Arch Linux.

### Describe your Expected behavior

Ideally always depend on one of the stable releases [listed here](https://releases.electronjs.org/).

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Hey @buzo-ffm thanks for the reminder.
I'm working on upgrading to Electron 30 already, and want to release this week.

**Comment by jeanfbrito** [comment]
Updated to v29 on https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/4.0.0

Now we can keep updating sooner. Please tell me if there is any problem. I will close for now.

**Comment by buzo-ffm** [comment]
Building 4.0.0 with Electron 29 still fails during `yarn install`:
```
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 202ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ prettier is listed by your project with version 3.2.5, which doesn't satisfy what @rocket.chat/prettier-config (p68591) requests (~2.7.1).
➤ YN0060: │ react is listed by your project with version 18.2.0, which doesn't satisfy what @rocket.chat/fuselage-hooks (p1eae0) and other dependencies request (^17.0.2).
➤ YN0060: │ react-dom is listed by your project with version 18.2.0, which doesn't satisfy what @rocket.chat/fuselage (p1a71d) and other dependencies request (^17.0.2).
➤ YN0060: │ react-virtuoso is listed by your project with version 4.6.2, which doesn't satisfy what @rocket.chat/fuselage (pa8ede) requests (1.2.4).
➤ YN0002: │ rocketchat@workspace:. doesn't provide @rocket.chat/fuselage-tokens (pc9598), requested by @rocket.chat/fuselage-hooks.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0066: │ typescript@patch:typescript@npm%3A5.4.5#optional!builtin<compat/typescript>::version=5.4.5&hash=e012d7: Cannot apply hunk #8
➤ YN0013: │ 1657 packages were added to the project (+ 165.39 MiB).
➤ YN0000: └ Completed in 13s 257ms
➤ YN0000: ┌ Link step
➤ YN0007: │ electron@npm:28.1.1 must be built because it never has been before or the last one failed
➤ YN0007: │ electron@npm:29.4.1 must be built because it never has been before or the last one failed
➤ YN0007: │ puppeteer@npm:21.7.0 must be built because it never has been before or the last one failed
➤ YN0007: │ sharp@npm:0.29.3 must be built because it never has been before or the last one failed
➤ YN0007: │ puppeteer@npm:13.7.0 must be built because it never has been before or the last one failed
➤ YN0009: │ sharp@npm:0.29.3 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-6da72578/build.log)
➤ YN0007: │ rocketchat@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 23s 185ms
➤ YN0000: · Failed with errors in 36s 952ms
```

**Comment by buzo-ffm** [comment]
The referenced sharp build.log contains:
```
  CXX(target) Release/obj.target/sharp-linux-x64/src/common.o
In file included from ../src/common.cc:24:
/usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory
   35 | #include <glib-object.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```
It is installed though: `/usr/include/glib-2.0/glib-object.h`

**Comment by jeanfbrito** [comment]
Seems to be another thing than Electron version this error. Did you installed `vips`?

**Comment by buzo-ffm** [comment]
Yes, I did.
