### ISSUE TITLE
Desktop notifications not working for Windows 8.

### ISSUE THREAD

**Issue by SteveOnorato** [RocketChat/Rocket.Chat.Electron#290]
## My Setup
Windows 8 Enterprise
2.1.0
- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description
No desktop notifications appear for Windows 8.
This was also reported as #107 and closed without a fix.  I'm unable to reopen that issue.

#### Current Behavior
Go to My Account, Preferences, click "TEST DESKTOP NOTIFICATIONS".
Nothing pops up.

#### Expected Behavior
Desktop notification should pop up.

#### Solution
I built my own version and it worked.  The only fix needed was to add one line to src/app.js, before start():
app.setAppUserModelId('chat.rocket');

I learned that we should do this from https://www.npmjs.com/package/electron-windows-notifications

**Comment by kkachura** [comment]
Same effect!!!

**Comment by rodrigok** [comment]
Thanks by this report, I will fix it ASAP

**Comment by rodrigok** [comment]
@SteveOnorato  I don't have a windows 8 machine to test.

I just need add `app.setAppUserModelId('chat.rocket');` before `start();` on `src/app.js`?

Is this issue happening only on windows 8? Or on windows 7 too? Windows 10 is ok.

**Comment by SteveOnorato** [comment]
I don't have Windows 7 to test, but I believe that it's using a different mechanism, based on https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md?ts=2#windows

Yes, the bottom of src/app.js looks like this for me:
```
window.$ = window.jQuery = require('./vendor/jquery-1.12.0');

// Required for native notifications in Windows 8.
app.setAppUserModelId('chat.rocket');

start();
```
I don't know if it's possible to programmatically get 'chat.rocket' from package.json (it's under build.appId).  I think these two constants always need to stay in-sync for notifications to work in Windows 8.

Thanks!

**Comment by engelgabriel** [comment]
Refs:
https://github.com/RocketChat/Rocket.Chat.Electron/issues/309
https://github.com/felixrieseberg/electron-windows-notifications
