### ISSUE TITLE
Can the icon in the Start menu be set to default to red?

### ISSUE THREAD

**Issue by TEAMO909** [RocketChat/Rocket.Chat.Electron#2903]
![Clipboard - June 12, 2024 3_24 PM](https://github.com/RocketChat/Rocket.Chat.Electron/assets/172482352/2b4c44cd-a247-4430-984f-e9e83a6ca281)

Every time Rocketchat is opened, the icon in the Start menu is always gray. I always thought my Rocketchat was disconnected. Can this be set to default to red?

Thank you!
i'm chinese ,my english is poor . The above words were translated by translation software. If there are any unclear areas, please communicate promptly

**Comment by jeanfbrito** [comment]
Hello, its the default color.
