### ISSUE TITLE
Multiple services make desktop client disconnect when not focused.

### ISSUE THREAD

**Issue by florisvangeel** [RocketChat/Rocket.Chat.Electron#2914]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Operating System Version

Windows 10, OSX 12.6.8, Ubuntu 22.04

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

4.0.0

### Rocket.Chat Server Version

6.6.6 and below

### Description:

Adding multiple services to a client restricts update of connection and notifications to the active (highlighted service)

### Actual behavior:
Non focused services stuck in toaster trying to connect.
No communication until hard reload Shift+CMD+R or SHIFT+CTRL+R

https://github.com/RocketChat/Rocket.Chat/assets/1267925/955a7485-7f3a-4db0-9516-04cca2668eba

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.6
- License Type: Community
- Number of Users: N
- Operating System: Ubunti 22.04
- Deployment Method: Ansible
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 5.x

### Client Setup Information

- Desktop App or Browser Version: 4.0.0 (master) or any version below.
- Operating System: OSX ( problem happens in any OS )

### How to Reproduce

1. Install Desktop client from app store or build latest 4.0.0
2. Add multiple services besides open. and demo.rocket.chat
3. focus and highlight one service
4. Wait 15-60 minutes not touching or minimising the app.
5. Click to one of the not focused services.

### Describe your Expected behavior

Not focused services should maintain connection up and refresh notification etcetera.

### Additional context
Tested with transparent proxy in Caddy and Nginx as well as running RC directly behind NAT routing on dedicated IP number. 
All have the same issue.

Hypothesis is it must be the client not polling / connecting properly?

### Relevant logs:
No Errors, just the usual warnings.

### Are you willing to submit a code contribution?

- [X] Yes, I am willing to submit a Pull Request!

**Comment by reetp** [comment]
Ran this on Linux with Electron 3.9.15 against 2 x 6.9.3 servers and open.rocket on 6.10.x and left it overnight.

No timeouts at all.

**Comment by florisvangeel** [comment]
i specifically stated all but open and demo.rocket.chat
those are multi instances behind cloudflare proxy
i don't use or trust cloudflare.

This issue can be closed since its actually a server issue that is open [here](https://github.com/RocketChat/Rocket.Chat/issues/17748#issuecomment-2049835952) 

The good thing it has a patch to work with.

**Comment by florisvangeel** [comment]
closing issue
