### ISSUE TITLE
Desktop Notification Problem with http (+workaround)

### ISSUE THREAD

**Issue by binse03** [RocketChat/Rocket.Chat.Electron#2922]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10 Enterprise

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

4.0.1.

### Rocket.Chat Server Version

i think the lastet

### Describe the bug

Whats the problem:
![No Notification](https://github.com/user-attachments/assets/137d38eb-9cc2-468d-8667-052eb484744e)

Enabling in Chrome the notificationsettings didnt work out because Chrome is blocking http:// Website Settings.
![Google Chrome blocking the Settings for notifications](https://github.com/user-attachments/assets/abe962c3-f476-4e30-8e18-1cf624cd86cf)

### How to Reproduce

Use Rocket.Chat Server and Client with HTTP and install lastet Version from Google Chrome. Then Restart the Computer.

### Describe your Expected behavior

This:
![Button is back](https://github.com/user-attachments/assets/19b0db2f-0d37-4002-80c6-a3c9868c6462)

### Anything else

I found a workaround for my issue: 
1. GoTo [Google Support](https://support.google.com/chrome/a/answer/7650032?hl=de&ref_topic=7649835&sjid=6056454773963322960-EU) and download the 64-bit bundle
2. Extract the files
3. Go to `PathToDownloadedFiles\GoogleChromeEnterpriseBundle64\Configuration\admx` and copy `google.admx` and `chrome.admx` to `C:\Windows\PolicyDefinitions`
4. Go Back to downloaded files and search for your language (for me: de-DE) and go into the folder `PathToDownloadedFiles\GoogleChromeEnterpriseBundle64\Configuration\admx\de-DE` and copy both files to `C:\Windows\PolicyDefinitions\de-DE` (look for your language in the Policy Folder)
5. Open gpedit.msc on your device 
6. Go To `Computer Configuration > Administrative Templates > Google > Google Chrome > HTTP Authentication` 
7. Activate `Allow Basic HTTP Authentication`
8. Restart your Rocket.Chat (or reload)
9. Now the Desktopnotifications work for me

Also would fix this problem to run Rocket.Chat with HTTPS, i know. But for the ppl who want to use http....

ALSO ALSO.... why does chrome overwrite Rocket.Chat Settings? 

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Notification
