### ISSUE TITLE
[4.0.2] PDF get not shown and download does not work

### ISSUE THREAD

**Issue by CvH** [RocketChat/Rocket.Chat.Electron#2939]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 11

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

4.0.2

### Rocket.Chat Server Version

6.9.3

### Describe the bug

Clicking at the PDF redirects me into some wired view and offers the download without any preview.
![image](https://github.com/user-attachments/assets/ef50f8bc-3031-4908-ab0f-6413892443fa)

To download the same pdf again (for example if you clicked cancel at the save dialog) you need to exit the RC client or click at a different PDF before it offers the download again. It just redirects to the pdf view linked above with no download.

### How to Reproduce

upload two pdfs, clicking at the first multiple times offers the download just one time
clicking at the second pdf the download works
clicking at the first pdf again the download works again one time

### Describe your Expected behavior

- PDF gets previewed
- PDF could get downloaded multiple times
- do not redirect to empty views

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
Please update to the latest server version.
