### ISSUE TITLE
Grayscale anti-aliasing has replaced subpixel anti-aliasing (Windows 8/10)

### ISSUE THREAD

**Issue by SteveOnorato** [RocketChat/Rocket.Chat.Electron#294]
## My Setup
Windows 8 and Windows 10
2.1.0 and 2.2.0
- [X] I have tested with the latest application version
- [X] I can simulate the issue easily

## Description
Version 1.3.1 displayed the text with subpixel anti-aliasing, as expected (since ClearType is enabled, with RGB pixel structure).
Version 2.1.0 and 2.2.0 now display the text with grayscale anti-aliasing.  This doesn't look as sharp on my LCDs.

#### Current Behavior
Zoomed text captured from 2.1.0 (2.2.0 is the same):
![rc2 1 0](https://cloud.githubusercontent.com/assets/25069709/21920901/f0238050-d918-11e6-8557-5e1a4741e4fc.png)

#### Expected Behavior
Zoomed text captured from 1.3.1:
![rc1 3 1](https://cloud.githubusercontent.com/assets/25069709/21920905/f4cc6fa4-d918-11e6-9ea2-2f5c26c364cd.png)
Note that Rocket Chat also displays like this in Chrome (version 55.0.2883.87 m) and Firefox (50.1.0) - those both respect my system settings.  Only the Electron-based version seems to be different.

**Comment by engelgabriel** [comment]
@SteveOnorato this may be due to the fact that we are using a newer version of electron.

@rodrigok is this a Electron issue? Is it even configurable?

**Comment by rodrigok** [comment]
Maybe related with https://github.com/electron/electron/issues/6344

**Comment by engelgabriel** [comment]
@rodrigok but this was fixed on https://github.com/electron/electron/pull/6606

Are we using that version of Electron already?

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
