### ISSUE TITLE
2.1.0 and 2.2.0 - Ctrl-Enter doesn't insert a newline in post

### ISSUE THREAD

**Issue by drq883** [RocketChat/Rocket.Chat.Electron#296]
## My Setup
- macOS Sierra 10.12.1
- Rocket.Chat+ Version 2.2.0 (2.2.0.206)
- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

When trying to insert a newline in a post before sending, I used to be able to press Ctrl-Enter and it would insert one. Now it does nothing.

#### Current Behavior

Pressing Ctrl-Enter does nothing.

#### Expected Behavior

Pressing Ctrl-Enter should insert a newline in the post.

**Comment by engelgabriel** [comment]
shift+enter still works

**Comment by engelgabriel** [comment]
this is a bug with the core app, not just Electron.

**Comment by engelgabriel** [comment]
Closed in favor of https://github.com/RocketChat/Rocket.Chat/issues/5673
