### ISSUE TITLE
Russian translation i18n is not applied (4.0.2 and above)

### ISSUE THREAD

**Issue by rze0** [RocketChat/Rocket.Chat.Electron#2960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

windows 10, windwos 11

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

4.1.1

### Rocket.Chat Server Version

6.12.0

### Describe the bug

Russian translation i18n is not applied (4.0.2 and above)
I think it's related to https://github.com/RocketChat/Rocket.Chat.Electron/pull/2856
If you change in Rocket.Chat.Electron\src\i18n\resources.ts 'ru' to 'ru-RU' then the translation is applied.

![1](https://github.com/user-attachments/assets/8a6e96b7-02ff-4c20-ac08-08f55cd1ba0a)
![2](https://github.com/user-attachments/assets/fa5cb0f0-1303-4bf1-9fdb-17599d5f3e3d)
yarn start with modified resources.ts
![3](https://github.com/user-attachments/assets/6a8270cf-94ca-42a3-8b78-5eae82223cfa)

### How to Reproduce

1. Install 4.1.1 ( 4.0.2 and above)
2. switch system language to Russian or Russia-Russian (not sure what it looks like exactly)
3. launch rocket chat desktop app
4. see translation not applicable

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jeanfbrito** [comment]
@rze0 can you please test this new version and tell us if is fixed?

**Comment by rze0** [comment]
@jeanfbrito Hi. I confirm, the translation works. Thank you!
![Rocket Chat_2024-11-14_10-08-08](https://github.com/user-attachments/assets/5759d7be-49dd-4bf8-bf94-82c8bae2083e)

**Comment by jeanfbrito** [comment]
Thank you @rze0 
Congratulations @rique223
