### ISSUE TITLE
Notification are appearing behind other windows on windows 7

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat.Electron#297]
## My Setup

 - __My OS name and version__: Windows 7 Enterprise X64 SP1
 - __My current app version__: 2.2.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

Notification appearing behind other windows

#### Expected Behavior

Notifications should appear in front of all other windows

**Comment by graywolf336** [comment]
@alexbrazier I just tried with windows 7 and a development version of Rocket.Chat Electron (2.3.0) and it doesn't appear behind windows:

![image](https://cloud.githubusercontent.com/assets/850391/22118999/f9acbbda-de60-11e6-962d-2cbc5f5306bf.png)

**Comment by alexbrazier** [comment]
@rodrigok  I've just tried updating to the latest version of rocket chat (0.49.3), still running 2.2.0 of the electron app and notifications are still appearing behind some windows (for some reason it is appearing in front of some, but not others). It is also appearing below the taskbar (i.e. in the very bottom corner, not like your image where it is above the taskbar).

Has something changed since 2.2.0 that will make a difference?

**Comment by alexbrazier** [comment]
@rodrigok I have just tried this again in a vm running Windows 7 Enterprise x64 SP1 and I am getting similar results
![image](https://cloud.githubusercontent.com/assets/5689874/22126492/c1ef3fea-de8f-11e6-8967-f41bfda9cb5f.png)

It appears above some windows, and behind others, and also appears slightly below the taskbar
