### ISSUE TITLE
Open the Rocket.Chat+ App with one taskbar-icon click

### ISSUE THREAD

**Issue by ST-KW** [RocketChat/Rocket.Chat.Electron#298]
## My Setup
Windows 10 Pro (1607)
Rocket.Chat+ 2.2.0

## Description
As a Windows user, I want to click on the Rocket.Chat+ taskbar icon so that Rocket.Chat window open for a better usability.

#### Current Behavior
To open the Rocket.Chat+ App I have to context-click / right mouse click on the taskbar icon. Than I have to click on "Show" in the context-menu.

![image](https://cloud.githubusercontent.com/assets/25076997/22023625/373854dc-dcc7-11e6-8fbc-1a83cd513ba0.png)

#### Expected Behavior
To open the Rocket.Chat+ App I can click (one time, left mouse button) on the taskbar icon.

_It's not necessary to remove the current behavior._

**Comment by vrooze** [comment]
I just spotted this issue after investigating this myself.
Your fix is almost spot on for #299 but the understore is wrong.
```javascript
_tray.on('click', () => {
    mainWindow.show();
});
```
Is what I have locally.
It's probably easier you fixing your PR than me making a new one.

**Comment by ST-KW** [comment]
Thanks guys! Makes my life better. <3
