### ISSUE TITLE
Clicking on a notification does not bring App to foreground on Windows 10

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat.Electron#301]
## My Setup

On Windows 10 32-bit.  Clicking on a notification does not bring Rocket.Chat desktop app to foreground, even if it is running in the background.

Other apps, such as Skype, will switch to foreground when a notification is clicked, and open in the correct (channel , conversation) context.

Thanks to @joshua.w for reporting this.

**Comment by graywolf336** [comment]
Was fixed via https://github.com/RocketChat/Rocket.Chat.Electron/pull/299

**Comment by radsdau** [comment]
I'm running RC 3.1.1 in Win10 (20H2) and clicking on a notification does not bring the app forward, or open up the associated message. Is there a setting that affects this?

**Comment by xtvjxk123456** [comment]
same issue

**Comment by idhowardgj94** [comment]
same issue, any udptae?
