### ISSUE TITLE
Server input box shows briefly every time application loaded

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat.Electron#303]
## My Setup

 - __My OS name and version__: Windows 7 x64 SP1
 - __My current app version__: 2.2.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

When the application loads it should remember your previous server straight away, however it currently shows the server input box for a couple of seconds until it loads, and takes you to the server

#### Current Behavior

Text box to fill in server url is shown briefly every time the application starts up.

#### Expected Behavior

A loading animation should be shown, until the app determines whether or not a server exists, then it either shows the server screen, or it takes you directly to the previous server.

**Comment by flauschi** [comment]
I have a similar problem (Windows 7 x64, Windows Server 2008 R2). It still exists with version 2.2.1.

Reproduce:
1. Delete the folder %AppData%/Roaming/RocketChat+.
2. Start Rocket.Chat+. Enter the server URL, credentials and toggle the server list. Quit Rocket.Chat.
3. Start Rocket.Chat+ again. The app has forgotten everything (server URL, credentials/cookie, status of toggled server list). Enter everything again. Quit Rocket.Chat+.
4. Start Rocket.Chat+ one more time. The app remembers the server URL but has forgotten everything else (credentials/cookie, status of toggled server list).

Step 3 and 4 could be repeated forever. It only remembers the server URL.

**Comment by Nosferous** [comment]
Have the same issue consistently on all client machines in my environment.

RocketChat Server hosted on Ubuntu 16.04.1 LTS. 
RocketChat Server version 0.49.3

Most clients are on OSX 10.9.5 a few on 10.11.6

Verified the issue is consistently present in RocketChat Electron app versions:
2.2.0.206
2.2.2.222 (latest)
