### ISSUE TITLE
Server list on right side of app is unnecessary for many users

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat.Electron#304]
## My Setup

 - __My OS name and version__: Windows 7 x64 SP1
 - __My current app version__: 2.2.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

The server list should not be shown by default unless the user adds a second server. I expect a majority users only connect to one server, so the user has to click toggle server list to hide the sidebar where you can select servers.

#### Current Behavior

After adding a server, the server list is shown on the left side, even though the user only has one server

#### Expected Behavior

By default the server list should not be visible unless the user has 2 or more servers, or if the user has chosen to toggle the server list

**Comment by graywolf336** [comment]
How would someone easily add another server then?

**Comment by alexbrazier** [comment]
Could an item be added to the menu to add a server, then once you have 2 or more servers the default view will be to show the server list?

At the moment, you would have to click `View->Toggle server list` then click the add button as usual.

I may be wrong, but I imagine a majority of users have a single server, so it is more effort for most people to click `toggle server list` to hide it than it is for the odd person to do it to add a server, as it does take up a significant amount of space.

**Comment by ttepatti** [comment]
The changes outlined in #312 appear to have been merged in #490. As such, I believe this issue can be closed.

**Comment by tassoevan** [comment]
Sidebar/server list still need some rework (e.g. when removing all servers), but the original issue doesn't apply anymore.
