### ISSUE TITLE
Pasting text takes a long time to appear in chat box.

### ISSUE THREAD

**Issue by oliver-bowman** [RocketChat/Rocket.Chat.Electron#306]
## My Setup

 - __My OS name and version : Fedora 25 
 - __My current app version__: 2.2.2

- [X] I have tested with the latest application version
- [X] I can simulate the issue easily

## Description

When text is pasted into the chat e.g. code greater than 5 lines it takes a long time for it to load and appear. This makes it look like the client has hung when in fact it hasn't. This was reported by many of my colleagues who can also replicate this issue. 
#### Current Behavior
Takes a long time to paste text to chat.

#### Expected Behavior

Should not take the length of time it does, even with node being single threaded etc.

**Comment by theoryshaw** [comment]
Same problem.
2.2.1

**Comment by Rumbles** [comment]
Same issue here on F25 with rocket chat 2.3

**Comment by jamesridgway** [comment]
I have the same issue running version 2.2.0

**Comment by paul-ridgway** [comment]
+1

**Comment by menkow** [comment]
Same on Win7
