### ISSUE TITLE
No back button in the menu bar.

### ISSUE THREAD

**Issue by oliver-bowman** [RocketChat/Rocket.Chat.Electron#308]
## My Setup

 - __My OS name and version__: Fedora 25 
 - __My current app version__: 2.2.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior
With the current build of the app, If you accidentally drag a link into anywhere on rocket chat it opens  that page in the app this would be fine if there was a way in which you could go back, like a back button in nearly every other electron app in the menu bar. 

There is no back or forward button in the menu bar.
#### Expected Behaviour
There should be a back and forward button in the menu bar.

**Comment by alexbrazier** [comment]
@oliver-bowman Will the back button be useful for any other purpose? It seems the solution might be to stop it from following links dragged in if that's possible?

**Comment by oliver-bowman** [comment]
It is one of the things that is stopping my company from moving over from slack. It would be useful not just for the above issue but also for the ability to use key board shortcuts to better navigate the app something which a lot of other instant messaging solutions have.

**Comment by graywolf336** [comment]
@oliver-bowman Please open an issue with the keyboard shortcuts you would like to see inside the electron client, that'll help us know which ones. :+1:

**Comment by oliver-bowman** [comment]
I will do but that wont solve the issue of URL's being accidentally being dragged into anywhere in rocket chat that isn't the chat box and there being no way to  solve this other than to restart the client.

**Comment by graywolf336** [comment]
@oliver-bowman I'm aware of that, but that's what this issue is for. :)
