### ISSUE TITLE
Use electron-windows-notifications for Windows 8, 8.1, and 10

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Electron#309]
https://github.com/felixrieseberg/electron-windows-notifications

**Comment by engelgabriel** [comment]
From https://slack.engineering/building-hybrid-applications-with-electron-dc67686de5fb#.4weuelp5c

**Comment by tassoevan** [comment]
I'm closing it because Electron integrated the HTML5 Notifications API since May 2017 and there are no plans to add advanced notifications (quick reply, actions etc.) for now.
