### ISSUE TITLE
Reoccurring java script popup

### ISSUE THREAD

**Issue by oliver-bowman** [RocketChat/Rocket.Chat.Electron#318]
## My Setup

 - __My OS name and version__: OSX Sierra + Linux
 - __My current app version__: Latest 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

The issue one of my colleagues is experiencing comes after the commit: RocketChat/Rocket.Chat.Electron@4f361bc he is expriencing multiple popups wit the message 

![jsbug](https://cloud.githubusercontent.com/assets/7502243/22205991/277d2032-e171-11e6-8c87-bb518c300f39.png)
This message constantly appears when zooming in or out of the client. It also apears everytime a user wakes their computer up after sleeping.
#### Expected Behavior
The shouldn't happen

**Comment by rodrigok** [comment]
@oliver-bowman I can't reproduce, can you help me?

Which exactly version of the app are you using?
Is this happening when you connect to `https://demo.rocket.chat` too?

**Comment by alexbrazier** [comment]
@rodrigok #322 Appears to be the same error
