### ISSUE TITLE
Right click -> copy / paste

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#32]
I keep trying to do this out of habit and it doesn't work.

This could potentially be difficult.  I know it was an issue that nodewebkit had.  But I know atom now has it.  So it should be possible.

**Comment by engelgabriel** [comment]
It would be nice to turn the "spell checker"one too :)

**Comment by engelgabriel** [comment]
Is this related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/2 ?

**Comment by geekgonecrazy** [comment]
It could be.  I'd kinda hope that we wouldn't have to pass through like that.  I'll look into the documentation and find out.

**Comment by geekgonecrazy** [comment]
An example of copy and paste being implemented in the top menu.  http://electron.atom.io/docs/v0.27.0/api/menu/

Might need used with:

https://github.com/atom/electron/blob/master/docs/api/clipboard.md

**Comment by rodrigok** [comment]
Should be fixed

**Comment by geekgonecrazy** [comment]
@rodrigok on windows v1.0.0 right click brings up the menu with copy and paste, but they do not function.

**Comment by rodrigok** [comment]
Now it's fixed in develop
