### ISSUE TITLE
When doing an application reload/refresh it breaks some things

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat.Electron#322]
## My Setup

 - __My OS name and version__: macOS 10.12.2
 - __My current app version__: 2.3.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

When reloading application using `View->Application - Reload` or `View->Current Server - Reload` various errors occur.

#### Current Behavior

Errors occurs e.g. when closing application after application reload:
```
Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: app.js:1136:16.
    at BrowserWindow.callIntoRenderer (/Users/alexbrazier/Code/Rocket.Chat.Electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:199:19)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)
```

#### Expected Behavior

Should not error.

I think this is due to old event listeners still attached, and trying to make changes to old objects.

**Comment by alexbrazier** [comment]
https://github.com/electron/electron/issues/3778

**Comment by rodrigok** [comment]
I can't reproduce :(

**Comment by rodrigok** [comment]
Now I can reproduce 😄
