### ISSUE TITLE
User only appears online when they interact with the app

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat.Electron#327]
## My Setup

 - __My OS name and version__: Windows 7 x64
 - __My current app version__: 2.3.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

A user appears as away if they haven't been using the app for a while, but they have been using their computer.

#### Current Behavior

User appears away, even if they are active on their computer.

#### Expected Behavior

User should appear online if they are still active on the computer, regardless of whether they have been on the app or not

**Comment by alexbrazier** [comment]
I assume there is a reason why this is commented out at the bottom of `preload.js`?

```
/* userPresence away timer based on system idle time */
// function getSystemIdleTime () {
//     return ipcRenderer.sendSync('getSystemIdleTime');
// }

// setInterval(function (){
//  try {
//      if(getSystemIdleTime() < UserPresence.awayTime) {
//          UserPresence.setOnline();
//      }
//  } catch(e) {
//      console.error(e);
//  }
// }, 1e3);
```

**Comment by engelgabriel** [comment]
@rodrigok do you know what was the reason for commenting this out? What error was this causing us?

**Comment by rodrigok** [comment]
@alexbrazier @engelgabriel Idk why this code is commented. We can try to uncomment and see if it is working.
