### ISSUE TITLE
Tray icon not showing there is unread message

### ISSUE THREAD

**Issue by kreuzman** [RocketChat/Rocket.Chat.Electron#329]
## My Setup

 - __My OS name and version__: Ubuntu 16.04
 - __My current app version__: 2.3.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

I don't see unread message notification icon (!) in notifications area when there is a unread message.

#### Expected Behavior

I expect to see unread message notification icon (!) in notifications area when there is a unread message.

**Comment by oliver-bowman** [comment]
Same here as well as one of my colleagues both running fedora 25

**Comment by kreuzman** [comment]
This problem is gone with latest RC server release. So I suppose that is not problem of client.

**Comment by kreuzman** [comment]
I have to reopen this issue. I'm now using client version 2.4.0 and have same problem as described below. RC version on server is 0.53.0.

**Comment by oliver-bowman** [comment]
Experiencing same issue too

**Comment by Nepoxx** [comment]
The taskbar icon also does not become bright as it used to. Like this: ![img](https://cloud.githubusercontent.com/assets/5293889/16509621/6f41701e-3f71-11e6-9bc2-ea7f79afbb7b.png)

**Comment by dark-penguin** [comment]
I've just tried it on Ubuntu 16.10 with Xfce and it works. It does not work in Debian Jessie with MATE, however. I'm not an expert on this, but I think it may be a problem with GTK2 which will soon be relevant no longer as everyone moves on to GTK3 ([in Ubuntu 17.04, even MATE will be GTK3-based](http://www.omgubuntu.co.uk/2017/03/mate-1-18-desktop-released-now-gtk3)). I doubt anyone would want to backport this to GTK2. (See also #172 )

**Comment by oliver-bowman** [comment]
XFCE 4.12 is GTK2 only, it will not be gtk+3 based till 4.14 which isnt out yet not even in devel repos fully. Gnome which I am running uses the latest version of GTK3+ and is still broken.

**Comment by gdelavald** [comment]
I'll close this issue as this seems to be fixed in the latest versions, please create a new issue with updated info if you are still running into this bug.
