### ISSUE TITLE
@paulcbetts/system-idle-time@1.0.4 Node Gyp Rebuild error

### ISSUE THREAD

**Issue by ihd2911** [RocketChat/Rocket.Chat.Electron#335]
## My Setup

 - __My OS name and version__: Ubuntu 14.04
 - __My current app version__: 2.4.0

## Description

On electron app, when i run npm install i am getting error in @paulcbetts/system-idle-time@1.0.4

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "@paulcbetts/system-idle-time"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! @paulcbetts/system-idle-time@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @paulcbetts/system-idle-time@1.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @paulcbetts/system-idle-time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @paulcbetts/system-idle-time
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @paulcbetts/system-idle-time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/lampp/htdocs/Rocket.Chat.Electron/npm-debug.log

**Comment by alexbrazier** [comment]
@ihd2911 Have you installed build-essential?
`sudo apt-get install build-essential`

You may also need libkrb5-dev - `apt-get install libkrb5-dev`

If that doesn't work, you could try to update your node to 7.4.0

**Comment by alexbrazier** [comment]
I have got this working on Ubuntu 16 by installing
```
build-essential
libevas-dev
libxss-dev
```

**Comment by ihd2911** [comment]
Working now. Thanks

**Comment by ihd2911** [comment]
How to make it working on windows 7?

**Comment by alexbrazier** [comment]
https://github.com/nodejs/node-gyp#installation
I had to use option 2 to get it to work on Windows 7

**Comment by engelgabriel** [comment]
Can we add this steps to the README.md?

**Comment by alexbrazier** [comment]
@ihd2911 Did you manage to get this working?

I did a clean install on Windows 7 and installed Visual Studio Express 2013 and got it working.

**Comment by angelscat** [comment]
I got this error,either.
Anyone who can help me? 
Thanks!

My OS is Win 7.
Current app version is 2.4.0 release.

I download the source code , and run npm install, and the got this error.

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\wangzufang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'rebuild',
1 verbose cli   '@paulcbetts/system-idle-time',
1 verbose cli   'spellchecker' ]
2 info using npm@4.2.0
3 info using node@v6.9.5
4 info readInstalled object
5 verbose rebuild path, id [ 'D:\\workspace\\labs\\rocket.chat\\Rocket.Chat.Electron-2.4.0\\node_modules\\@paulcbetts\\system-idle-time',
5 verbose rebuild   '@paulcbetts/system-idle-time@1.0.4' ]
6 verbose rebuild path, id [ 'D:\\workspace\\labs\\rocket.chat\\Rocket.Chat.Electron-2.4.0\\node_modules\\spellchecker',
6 verbose rebuild   'spellchecker@3.3.1' ]
7 silly rebuild set [ 'D:\\workspace\\labs\\rocket.chat\\Rocket.Chat.Electron-2.4.0\\node_modules\\@paulcbetts\\system-idle-time',
7 silly rebuild set   'D:\\workspace\\labs\\rocket.chat\\Rocket.Chat.Electron-2.4.0\\node_modules\\spellchecker' ]
8 info build D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modules\@paulcbetts\system-idle-time
9 info lifecycle @paulcbetts/system-idle-time@1.0.4~preinstall: @paulcbetts/system-idle-time@1.0.4
10 silly lifecycle @paulcbetts/system-idle-time@1.0.4~preinstall: no script for preinstall, continuing
11 info linkStuff @paulcbetts/system-idle-time@1.0.4
12 silly linkStuff @paulcbetts/system-idle-time@1.0.4 has D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modules as its parent node_modules
13 verbose linkBins @paulcbetts/system-idle-time@1.0.4
14 verbose linkMans @paulcbetts/system-idle-time@1.0.4
15 verbose rebuildBundles @paulcbetts/system-idle-time@1.0.4
16 info lifecycle @paulcbetts/system-idle-time@1.0.4~install: @paulcbetts/system-idle-time@1.0.4
17 verbose lifecycle @paulcbetts/system-idle-time@1.0.4~install: unsafe-perm in lifecycle true
18 verbose lifecycle @paulcbetts/system-idle-time@1.0.4~install: PATH: C:\Users\wangzufang\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modules\@paulcbetts\system-idle-time\node_modules\.bin;D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modules\.bin;C:\Users\wangzufang\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modules\.bin;d:\Program Files (x86)\BigAntSoft\IM Console\im_webserver\php;C:\Program Files (x86)\Common Files\NetSarang;C:\ProgramData\Oracle\Java\javapath;D:\Python27\;D:\Python27\Scripts;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\Brackets\command;D:\Program Files\gradle-2.4\bin;D:\Program Files\Java\jdk1.8.0_45\bin;C:\Program Files\Java\jre1.8.0_45\bin;D:\Program Files\TortoiseGit\bin;D:\Program Files\mysql\bin;D:\Program Files\TortoiseSVN\bin;D:\nwjs-v0.16.0-win-x64;D:\Squirrel.Windows-1.4.0;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Yarn\bin;C:\Users\wangzufang\AppData\Local\Android\Sdk\tools;C:\Users\wangzufang\AppData\Local\Android\Sdk\platform-tools;C:\Users\wangzufang\AppData\Roaming\npm;C:\Users\wangzufang\AppData\Local\Yarn\.bin;D:\Program Files\nodejs\;C:\Users\wangzufang\AppData\Local\Yarn\.bin;C:\Users\wangzufang\AppData\Local\.meteor\;C:\Users\wangzufang\AppData\Roaming\npm
19 verbose lifecycle @paulcbetts/system-idle-time@1.0.4~install: CWD: D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modules\@paulcbetts\system-idle-time
20 silly lifecycle @paulcbetts/system-idle-time@1.0.4~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
21 silly lifecycle @paulcbetts/system-idle-time@1.0.4~install: Returned: code: 1  signal: null
22 info lifecycle @paulcbetts/system-idle-time@1.0.4~install: Failed to exec install script
23 verbose stack Error: @paulcbetts/system-idle-time@1.0.4 install: `node-gyp rebuild`
23 verbose stack Exit status 1
23 verbose stack     at EventEmitter.<anonymous> (C:\Users\wangzufang\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
23 verbose stack     at emitTwo (events.js:106:13)
23 verbose stack     at EventEmitter.emit (events.js:191:7)
23 verbose stack     at ChildProcess.<anonymous> (C:\Users\wangzufang\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
23 verbose stack     at emitTwo (events.js:106:13)
23 verbose stack     at ChildProcess.emit (events.js:191:7)
23 verbose stack     at maybeClose (internal/child_process.js:877:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
24 verbose pkgid @paulcbetts/system-idle-time@1.0.4
25 verbose cwd D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0
26 error Windows_NT 6.1.7601
27 error argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wangzufang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "@paulcbetts/system-idle-time" "spellchecker"
28 error node v6.9.5
29 error npm  v4.2.0
30 error code ELIFECYCLE
31 error errno 1
32 error @paulcbetts/system-idle-time@1.0.4 install: `node-gyp rebuild`
32 error Exit status 1
33 error Failed at the @paulcbetts/system-idle-time@1.0.4 install script 'node-gyp rebuild'.
33 error Make sure you have the latest version of node.js and npm installed.
33 error If you do, this is most likely a problem with the @paulcbetts/system-idle-time package,
33 error not with npm itself.
33 error Tell the author that this fails on your system:
33 error     node-gyp rebuild
33 error You can get information on how to open an issue for this project with:
33 error     npm bugs @paulcbetts/system-idle-time
33 error Or if that isn't available, you can get their info via:
33 error     npm owner ls @paulcbetts/system-idle-time
33 error There is likely additional logging output above.
34 verbose exit [ 1, true ]

**Comment by angelscat** [comment]
This is the console log.

> rocketchat@2.4.0 postinstall D:\workspace\labs\rocket.chat\Rocket.Chat.Electro
n-2.4.0
> install-app-deps && electron-rebuild

Rebuilding native production dependencies for win32:x64
Error: D:\Program Files\nodejs\node.exe exited with code 1
Output:

> @paulcbetts/system-idle-time@1.0.4 install D:\workspace\labs\rocket.chat\Rocke
t.Chat.Electron-2.4.0\node_modules\@paulcbetts\system-idle-time
> node-gyp rebuild


D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modules\@paulcbett
s\system-idle-time>if not defined npm_config_node_gyp (node "C:\Users\wangzufang
\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-
gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

Error output:
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 52.216.32.8:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:1
4)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wangzufang\\A
ppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.j
s" "rebuild"
gyp ERR! cwd D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modul
es\@paulcbetts\system-idle-time
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wangzufang\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "@paulcbetts/sy
stem-idle-time" "spellchecker"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @paulcbetts/system-idle-time@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @paulcbetts/system-idle-time@1.0.4 install script 'node-g
yp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @paulcbetts/system-id
le-time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @paulcbetts/system-idle-time
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @paulcbetts/system-idle-time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\wangzufang\AppData\Roaming\npm-cache\_logs\2017-02-15T01_5
8_31_956Z-debug.log

    at ChildProcess.childProcess.once.code (D:\workspace\labs\rocket.chat\Rocket
.Chat.Electron-2.4.0\node_modules\electron-builder-util\src\util.ts:134:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modu
les\electron-builder-util\src\util.ts:97:3)
    at D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modules\ele
ctron-builder\src\yarn.ts:118:11
From previous event:
    at rebuild (D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_mo
dules\electron-builder\out\yarn.js:87:22)
    at D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modules\ele
ctron-builder\src\yarn.ts:16:11
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at installOrRebuild (D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.
0\node_modules\electron-builder\out\yarn.js:33:21)
    at D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modules\ele
ctron-builder\src\cli\install-app-deps.ts:31:2
    at next (native)
From previous event:
    at main (D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.4.0\node_modul
es\electron-builder\out\cli\install-app-deps.js:35:21)
    at Object.<anonymous> (D:\workspace\labs\rocket.chat\Rocket.Chat.Electron-2.
4.0\node_modules\electron-builder\out\cli\install-app-deps.js:71:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.0.3 (node_modu
les\7zip-bin\node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-
linux@1.0.3: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"
x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_module
s\7zip-bin\node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-
mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x
64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wangzufang\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! rocketchat@2.4.0 postinstall: `install-app-deps && electron-rebuild`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the rocketchat@2.4.0 postinstall script 'install-app-deps &&
electron-rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rocketchat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-app-deps && electron-rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rocketchat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rocketchat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\wangzufang\AppData\Roaming\npm-cache\_logs\2017-02-15T01_5
8_32_071Z-debug.log

**Comment by alexbrazier** [comment]
@angelscat Have you installed node-gyp globally, and installed the Windows build tools?
Look at the quick start guide here https://github.com/RocketChat/Rocket.Chat.Electron#quick-start and follow the instructions to install node-gyp

**Comment by Damon-Huang** [comment]
@angelscat  , have you fixed your issue? I just met the same issue as you, any hints?
@alexbrazier , I had followed the guide https://github.com/RocketChat/Rocket.Chat.Electron#quick-start but still failed, may I know the versions you used(e.g. the node, npm, msvs )?

**Comment by jdashn** [comment]
I'm having a similar issue with openSUSE, i'm guessing there is something i'm missing as well.  Any ideas?
