### ISSUE TITLE
Invisible "dead area" from old notifications

### ISSUE THREAD

**Issue by vrooze** [RocketChat/Rocket.Chat.Electron#352]
## My Setup
 - __My OS name and version__: Windows 7 Pro 
 - __My current app version__:  2.50-develop (happened on 2.4.0 so built the latest develop to check)

- [X] I have tested with the latest application version
- [ ] I can simulate the issue easily

## Description

Not easy to replicate but has happened multiple times.
The bottom right area where the notifications appear sometimes becomes a dead zone for mouse clicks.
Anything in the area does not respond to mouse clicks until Rocket.Chat process is closed and reopened.

I'm a web developer so only noticed as a colleague was unable to click a button located in the bottom right corner. After moving the element around the page I was able to get a rough idea of the shape of the dead zone which made me realise what it was.

#### Current Behavior

Old notifications sometimes will not fully disappear. visually they are gone but they block mouse clicks to the area they occupied.

#### Expected Behavior

Notifications to fully release the space occupied once dismissed or time out.

**Comment by vrooze** [comment]
This just happened again. I have captured a short video of my using paint in the bottom right corner.
You can see by the cursor changine the dead zone. I
I used black dots to roughly trace the outline shape of the deadzone.

[dead area.webm (zipped)](https://github.com/RocketChat/Rocket.Chat.Electron/files/787662/dead.area.zip)

**Comment by z3rogate** [comment]
I have the same issue 

![image](https://user-images.githubusercontent.com/578303/28169251-04eed8e2-67e2-11e7-943a-eb28e8de45eb.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
