### ISSUE TITLE
Request to have Tray Icon, Windows title change for active notifications

### ISSUE THREAD

**Issue by thehutman** [RocketChat/Rocket.Chat.Electron#353]
## My Setup

 - __My OS name and version__: Windows 10 64bit (1607 - 14393.693)
 - __My current app version__:  2.4.0

- [X] I have tested with the latest application version
- [X] I can simulate the issue easily

## Description

Say I am away from my desk and a new message arrives.  In Windows 10, the toast notification appears, but only for about 5 seconds and then disappears.  No entry is left in the Action Center (I think this is a bug too -- would be nice for notifications to remain in Action Center).

When I return back to my PC, there isn't anything obvious by looking at the task tray icon or the action center icon that I have pending messages to review.  So unless I open Rocket.Chat+ to work with it, I don't know I have messages waiting.

#### Current Behavior

Currently the tray icon, application text and icon, are all static.

The tray icon should change to something specific to indicate pending messages to review.  Also, the main window icon and title should also indicate this as well.

FWIW, running the client in a Chrome Browser shows the title and icon change when messages are pending.  Be nice to do the same in the actual client.

**Comment by thehutman** [comment]
Looks like I can fix this by setting the tray member on mainWindow in tray.js.  It is never set, and thus the check in showTrayAlert check for the tray member always fails.

`function createAppTray () {
    const _tray = new Tray(_iconTray);
    mainWindow.tray = _tray; \\ This needs to be placed onto mainWindow for future reference`

**Comment by billtt** [comment]
Definitely need this.

**Comment by jdashn** [comment]
Thehutman .. if you can fix can you put in a pull request? 

I know how important this would be to my Org to have some notification that there is an unread message pending when the come back to their desk from time away.
