### ISSUE TITLE
Rocketchat client doesn't show jitsi login popup

### ISSUE THREAD

**Issue by lsavio** [RocketChat/Rocket.Chat.Electron#355]
## My Setup
 - windows 7 - 8
 - Rocket.Chat Version: 2.2.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description
I installed Rochetchat (client on windows) version 2.2.0. In rocketchat, i did link to jitsi (with openfire meet plugin). When i open a videoconference by click on the icon of jitsi, the popup about login/password appears when the browser it's used, but if instead of browser i use the client of rocketchat, the popup don't appear, and this cause an unautorizated access (because login and password there aren't)
There is the possibility to show/enable the popup in rocketchat client?

thanks,
Luigi

**Comment by dan-chris** [comment]
+1

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
