### ISSUE TITLE
Bug: Adding private conversations missing

### ISSUE THREAD

**Issue by ST-KW** [RocketChat/Rocket.Chat.Electron#356]
## My Setup

 - __My OS name and version__: Windows 10 Pro (1607)
 - __My current app version__: Rocket.Chat+ 2.4.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Adding private conversations is missing.

#### Current Behavior

It's not possible to create a new chat with a user because there is no "+" or search function for users.

![20170213-rocket chat-privatemsg](https://cloud.githubusercontent.com/assets/25076997/22886201/22eb757c-f1fd-11e6-9b7b-28183a53361e.jpg)

#### Expected Behavior

A possibility to search users and start a private conversation (not channels).

**Comment by ST-KW** [comment]
OK, I learned: I can type a username into the search bar on the top. Is there any way to search for realnames? We have connected our active directory, but its not possible to search for anything about usernames.

**Comment by graywolf336** [comment]
This is not an issue with Electron and this is an intended feature of newer versions of Rocket.Chat. There was a discussion about this being an issue [in demo.rocket.chat #dev](https://demo.rocket.chat/channel/dev?msg=o5yNSWe8mwAwRBXHn) and the place it was added is: https://github.com/RocketChat/Rocket.Chat/pull/5846
