### ISSUE TITLE
Message received in background doesn't stay in Notification Center

### ISSUE THREAD

**Issue by OrdinaryGuy** [RocketChat/Rocket.Chat.Electron#357]
## My Setup
 - Windows 10, 1607 14393.693
 - 2.4.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

When you remove focus from the application, minimize it, let screensaver run or lock the workstation - there will be message received notification passed to Windows Notification Center(NC). 

#### Current Behavior

Whenever message is received, it is shown as a balloon popup and NC icon number increases the its number. However, after 5 seconds(default time in w10) the balloon disappears, the number in NC decreases back and there is no message stays in NC as well.
![image](https://cloud.githubusercontent.com/assets/4233017/22919874/b23fc53a-f2ab-11e6-9f93-0ee39e948301.png)
![image](https://cloud.githubusercontent.com/assets/4233017/22919889/be143c56-f2ab-11e6-99de-9bb77602aa06.png)

Right now there is no way you can see if app has unread messages via NC although it is being passed there in the first place.
I have seen #353, this one is related to NC integration in particular.

#### Expected Behavior

The message should stay in Notification Center until user checks it.

**Comment by thehutman** [comment]
I have the same issue.  Also verified that the Notification Setting "Show notifications in action center" is enabled for Rocket Chat (by default it isn't).  Didn't seem to change anything when enabled.  Messages appear for a few seconds and then go away.

FWIW, a simple app I built in electron seems to do the same thing when making notifications -- notifications disappear after a few moments of being displayed and never retain themselves in the action center.

**Comment by ScOut3R** [comment]
I can confirm the same issue on Linux. There is no indication on the taskbar icon when there are unread messages. It worked fine up until 2.3.

**Comment by linaMeneses** [comment]
Good  day

SomeOne has been able to solve this problem????????????????

**Comment by engelgabriel** [comment]
can you please test https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.12.1 ?

**Comment by mpbg** [comment]
I confirm in version 2.14.0 I have still this issue.

Any ideas?
