### ISSUE TITLE
Ability to use your own RC server

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat.Electron#36]
It would be useful if we were able to add an option in context menu, or in a sub-menu somewhere, to be able to use our own Rocket Chat server via this client.

**Comment by graywolf336** [comment]
This was added in the newest commits. :smile:

**Comment by sampaiodiego** [comment]
yep.. will be released on v0.0.7

**Comment by k0nsl** [comment]
Great! :+1:
