### ISSUE TITLE
Server Reload doesn't work

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#360]
## My Setup

 - __My OS name and version__: Linux / Fedora also saw behaviour on Ubuntu
 - __My current app version__: Latest as well as from develop branch

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Add at least one server to the app, then right click on its icon and select reload.

#### Current Behavior

It seems to actually reload, the logs indicate that its reloaded and notifications are generated but the view shows this:

![image](https://cloud.githubusercontent.com/assets/51996/22958945/18e4a566-f2f8-11e6-9f7b-8701ab383b32.png)

I've also seen this happen when the server goes down for a new version deployment.  It'll come up stuck like this.  Seems to be something related to the webview.

#### Expected Behavior

To reload.

**Comment by alexbrazier** [comment]
I believe this is an issue with the webview being empty, meaning you can see the server box behind. I have opened a PR that should fix this.
