### ISSUE TITLE
Building a pre-configured client

### ISSUE THREAD

**Issue by Nepoxx** [RocketChat/Rocket.Chat.Electron#362]
Is there a way to build a pre-configured client that will not show the server list and will already connect to a pre-configured server?

I've dug around the source code to make those changes and couldn't figure it out. This would be very useful in a business environment where the software is installed with group policies.

**Comment by Nosferous** [comment]
I know one method of how to do this on OSX by setting up the application fresh with the server settings you need. Quitting the app. Then take the folder that was created in ~/Library/Application Support/Rocket.Chat+ and then copy that to the same location on all home folders of the client machines as well as template user account.

My business environment for clients is mostly OSX so I do not have any tips on other platforms.

This is still not ideal, though and it would be nicer if the installer or app package could have an admin config file that is setup for this purpose for deploys.

**Comment by alexbrazier** [comment]
@Nosferous would a solution be to have a `servers.json` file in the application data that the application will read the first time it loads? That way you wouldn't have to copy across everything.

Do you know if it is possible to add a config directly to an installer for both windows and mac without having to rebuild the installer everytime?

Another option might be to have a command line option to run the installer.

**Comment by Zerocool56** [comment]
Msi app + mst file

This is very needed function
