### ISSUE TITLE
Dragging YouTube Links into RockeChat Turn RocketChat into a browsing session

### ISSUE THREAD

**Issue by jprone** [RocketChat/Rocket.Chat.Electron#363]
## My Setup

 - __My OS name and version__: macOS 10.12; 10.11.6 ; 10.10.5 ; 10.9.5
 - __My current app version__: 2.2.2.222

- [X ] I have tested with the latest application version
- [ X] I can simulate the issue easily

## Description
When dragging a Youtube link within a Rocket.Chat+ window on macOS 10.9.5 - 10.12 the Rocket.Chat+ window turns into a regular lookin' Chrome window.  (Not a copy and paste of the URL in the chat field, but literally a drag and drop).

One has to manually delete the server that was in view / selected and then setup the server additionally to resolve the behavior.  Quitting Rocket.Chat+ doesn't resolve the behavior consistently, as the video will load up additionally after quitting and reopening or the audio will continue to play even after quitting.

#### Expected Behavior

YouTube video URL is pasted into the chat field like any other link, possibly a preview from the header description and the focus frame for the video appear instead of just the link.

**Comment by alexbrazier** [comment]
@jprone Please could you test this with the latest version (2.4.0) as this issue should have been resolved

**Comment by lukasbisdorf** [comment]
This is not only with youtube links. We have the same Issue with all sort of dragged in URIs

**Comment by lukasbisdorf** [comment]
Same Issue:
https://github.com/RocketChat/Rocket.Chat.Electron/issues/351

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
