### ISSUE TITLE
File upload stuck at 100% 

### ISSUE THREAD

**Issue by oliver-bowman** [RocketChat/Rocket.Chat.Electron#366]
## My Setup

 - __My OS name and version__: Fedora 25 
 - __My current app version__: 2.4.0

- [x ] I have tested with the latest application version
- [ x] I can simulate the issue easily

## Description

When I drag any file into the rocket chat client it gets stuck at 100% and never sends. This happens with a few of my colleagues all the time.  

#### Expected Behavior

This issue doesn't happen when uploading files from accessing rocket chat within a browser.

**Comment by geekgonecrazy** [comment]
@oliver-bowman what version on the server side?

**Comment by oliver-bowman** [comment]
I am using version 0.50.1 on 4 instances over 2 VM's

**Comment by oliver-bowman** [comment]
Can someone close this as I believe it has been fixed

**Comment by geekgonecrazy** [comment]
@oliver-bowman awesome!  Yes I think it was related to the server version.
