### ISSUE TITLE
New messages notification should show mainwindow and/or add an overlay Image 

### ISSUE THREAD

**Issue by fcoppolani** [RocketChat/Rocket.Chat.Electron#367]
OS: Windows 7 and Windows 10
Current app version : 2.3.0

- [x ] I have tested with the latest application version
- [x ] I can simulate the issue easily

## Description
Hi,

During test phase in our company we add several issues with notifications. Part of them seems to be solved by #353 , but most users still miss some features.

#### Current Behavious : 
If the app is still visible in the taskbar and a new message fireup, no visual effect indicate this information (part from flashing which doesn't work on 2.4.0).
If the app is in the tray, no information is visible in the taskbar, so it is mainly invisible.

#### Expected Behavior

One of them is to have a visual effect on the taskbar icon (not only tray).
The second one is to have the main window show up without focus.

To do that (I worked on 2.3.0 src code), I changed tray.js : 

Taskbar visual effect : 

Adding an image : `const _iconTBAlert = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconAlert || 'changes.png');`
And in `showTrayAlert` adding an overlay : `mainWindow.setOverlayIcon(_iconTBAlert,  "new message");`
and resetting it if `showAlert` is false : ` mainWindow.setOverlayIcon(null,"saved changes");`

Show mainwindow : 
in `showTrayAlert` adding  `mainWindow.showInactive();`

For now I didn't fill up a pull request, since I would like to have your point of view and I cannot test my modifications on linux and OSX. Moreover the overlay image may not fit the global design of Rocket.Chat.

If validated I can add a pull request on the current branch, I would need a validated overlay image.

Regards,

**Comment by chrism113** [comment]
Looks similar to [#213](https://github.com/RocketChat/Rocket.Chat.Electron/issues/213)

Would love to see this added.

**Comment by chrism113** [comment]
mainWindow.showInactive() will bring the window back over whatever you're working on.

mainWindow.minimize() seems more appropriate and inline with other messaging services.  ie. it appears in the taskbar and just flashes until you're ready to check it.

so something like:

if window is closed to tray {
mainWindow.minimize()
}

**Comment by fcoppolani** [comment]
Yes indeed, much better, I would like to add that in this case the  `mainWindow.showInactive();` is useless `mainWindow.minimize();` only is enough.

I have included the code for 2.5.0, if I have enough time I will create a pull request on develop.

**Comment by chrism113** [comment]
In my testing, showInactive was needed.

When using only minimize, the window would appear minimized and have focus.  This meant the program would only stay orange in the taskbar for a few seconds before stopping.  After adding in the showInactive, it would stay orange until i clicked on it.

**Comment by chrism113** [comment]
After yet more testing, i think i've found the best solution.  With show inactive, you could get a brief "flash" of the window appearing before being minimized.  The blur() method will remove focus from the minimized window so that the "taskbar flash" won't go away.

```
	if (!mainWindow.isVisible()) {
		mainWindow.minimize();
		mainWindow.blur();
	}
```

**Comment by fcoppolani** [comment]
Changes made here  : https://github.com/fcoppolani/Rocket.Chat.Electron

**Comment by gdelavald** [comment]
@fcoppolani Hey, please check the current changes made to the notification, if your code still improves it, please open a PR. Thank you.

**Comment by fcoppolani** [comment]
Hi @gdelavald, sorry for the delay, I tried out the last version. It looks good enough to me, I still believe an overlay image on the icone in the taskbar will still be an improvement (the best would be with a number of message, like on the tray icone).

**Comment by engelgabriel** [comment]
can you please test https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.12.1 ?
