### ISSUE TITLE
Black window after a couple of minutes of not using the app

### ISSUE THREAD

**Issue by juanrhino** [RocketChat/Rocket.Chat.Electron#369]
## My Setup
 - __My OS name and version__:  MacOS 10.12.3
 - __My current app version__: Version 1.3.1 

- [X] I have tested with the latest application version
- [ ] I can simulate the issue easily

## Description

When I'm using the desktop app, after a couple of minutes of not using the app (show on screen) when I come back to do something the screen is completely black. I looks like that it is receiving the messages (the are notifications) but it doesn't render anything, and the only option is to restart the app.

**Comment by lmanzurv** [comment]
+1

**Comment by lmanzurv** [comment]
Sometimes it happens even if I'm in the screen doing something

**Comment by klatys** [comment]
+1 here macOS 10.12.4 app version 1.3.1

**Comment by luigibertaco** [comment]
I used to have the same problem but not anymore after updating to version 2.6+

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
