### ISSUE TITLE
Tagging, Notiffication Error - App is not responding

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat.Electron#370]
## Tagging, Notiffication Error - App is not responding #370

 - __My OS name and version__: Windows 7 64-bit
 - __My current app version__: 2.4.0

- [x] I have tested with the latest application version
- [ ] I can simulate the issue easily

#### Current Behavior
Desktop application crashes many times, but not always, when someone is tagging me. There is pop up window with information about Rocket chat is not responding.

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
The issue has been fixed in the latest version.
