### ISSUE TITLE
Windows 7 task bar icon not blinking in 2.4.0

### ISSUE THREAD

**Issue by bugy** [RocketChat/Rocket.Chat.Electron#371]
## My Setup
 - __My OS name and version__: Windows 7
 - __My current app version__: 2.4.0
- server version: 0.39.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description
When a new message comes (private message in my case), I see a toast with the new message, however there are no other signs about new message in the application icon. Neither in the task bar (it's not blinking), nor in tray icon (it stays white with 3 dots).

I've tested it in versions 2.2.3 and 2.3.0 also, the notification icons worked good (but there are problems with toasts).

**Comment by alexbrazier** [comment]
@bugy This has been resolved in the develop branch, which will be released as 2.5.0 later this week.
