### ISSUE TITLE
Video Recording is not working (start button doesn't work)

### ISSUE THREAD

**Issue by juanrhino** [RocketChat/Rocket.Chat.Electron#373]
## My Setup
 - __My OS name and version__:  MacOS 10.12.3
 - __My current app version__:  1.3.1

- [X ] I have tested with the latest application version
- [ X] I can simulate the issue easily

## Description

When I click the recording the button nothing happens, it doesn't start recording (but it works in Google Chrome)

**Comment by alexbrazier** [comment]
Tested this on the latest version and it works, so closing
