### ISSUE TITLE
Screen sharing not working with meet.jit.si [30$]

### ISSUE THREAD

**Issue by amenk** [RocketChat/Rocket.Chat.Electron#375]
## My Setup

Ubuntu 16.04 (also for Windows)
Latest app

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Screen sharing does not work via Jit.Si - in the browser it works.
I think the plugin is missing.

#### Current Behavior

Not working

#### Expected Behavior

Screen sharing plugin for Jit.Si should be bundled or it should be possible to install it in the desktop app.

**Comment by amenk** [comment]
Not sure if it is even possible... 
https://github.com/electron/electron/issues/1498

What we could do it to open Jit.Si always in a new window?

**Comment by LorneMalvoX** [comment]
Screen Sharing isn't working on Windows desktop client version 2.15.1.

How can we fix this? My company needs this freature very much.
