### ISSUE TITLE
WIth 2 images upload (png) is lagging

### ISSUE THREAD

**Issue by Mte90** [RocketChat/Rocket.Chat.Electron#378]
## My Setup
 - Linux: 
 - 1.3.1: 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description
We uploaded 2 and other 2 images with a low resolution (under 2000x) but the client is lagging while the browser don't have this issue.

#### Expected Behavior
No lagging

**Comment by ttepatti** [comment]
I'm unable to re-create this issue on the latest client version (2.14.1) on Debian Stretch 9.5

I believe this has been worked out since 2017, though I'm not sure exactly where :)

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
