### ISSUE TITLE
Clicking on image or web links doesn't do anything

### ISSUE THREAD

**Issue by gerli** [RocketChat/Rocket.Chat.Electron#379]
## My Setup

 - __My OS name and version__: Ubuntu 14.04
 - __My current app version__: Rocket.Chat+ 2.5.0 (also broken on 2.4.0)

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description - scenario 1

In a chat (direct message or channel), post an http/https link. Click on the link.

#### Current Behavior

Nothing happens.
#### Expected Behavior
The link opens in a browser.

## Description - scenario 2

Upload an image in a chat (direct message or channel). Click the "File Uploaded: ..." text.

#### Current Behavior

Nothing happens.
#### Expected Behavior
Either the image is shown (as happens when you click on the image preview) or a dialog pops up to browse a location where to download the file.

**Comment by LXSysadmin** [comment]
+1

**Comment by jbguerraz** [comment]
Same here on Mint (works on on Fedora)

**Comment by dfffffff** [comment]
Same here, what about using xdg-open for external stuff ?

**Comment by bagasse** [comment]
Hi, same here on CentOS7 Rocket.Chat+ 2.5.0

**Comment by tgoetheyn** [comment]
Same problem here.

**Comment by bagasse** [comment]
Hi, this problem is steel here, after upgrading from 2.50 to 2.6.1 and now to 2.7.0 (CentOS 7 x86_64)

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
