### ISSUE TITLE
Being able to hide servers list pane on the left

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat.Electron#38]
With multiple servers support now we have a list of numbers on the left side representing the connected servers.

There should a way to close/hide that pane...

![rocket-chat-servers-pane](https://cloud.githubusercontent.com/assets/4588562/9583946/17030e24-4fdc-11e5-8eb4-95808640f23b.PNG)

**Comment by kakawait** [comment]
:+1: some toggle button will be nice!

**Comment by sampaiodiego** [comment]
wow.. this issue was created too long ago :(

it seems easy to do.. for the UI, maybe we have a menu option like: `View > Show/hide servers panel`

**Comment by mhkeller** [comment]
+1. Adding a way to do this through the UI and not just the menus would be great as well.
