### ISSUE TITLE
RocketChat Client saves position even if monitor is disconnected

### ISSUE THREAD

**Issue by willihelm** [RocketChat/Rocket.Chat.Electron#380]
## My Setup

 - __My OS name and version__: Windows 10 64bit
 - __My current app version__: 2.4.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

If I open the client on the second monitor and then disconnect the monitor, the window stays there and can´t be moved to the main monitor.

#### Expected Behavior

If I disconnect the second monitor the client window should position itself on the main monitor.

**Comment by thehutman** [comment]
A coworker here has this issue.  His application is open on monitor #2 at the office, but when at home he only has the single screen and can't see the app (although the icon appears in the tray).  Would be nice if this didn't occur at all (if opens on missing monitor, at least fall back to a default location on an existing one).

As a workaround, you can move it via:

- **Shift**+**Right-Click** and select **Move** on the taskbar icon.
- Press any of the 4 arrow keys on your keyboard once.  The mouse is now locked to the window and will move with it.
- Move your mouse on your screen to the new position and left-click once its where you need it.

This actually works for any windows application (I've had apps in the past do the same thing).

**Comment by chrism113** [comment]
I'm also seeing this issue a lot.  User has the program on a 2nd monitor at work, they RDP in from home, and the program is off screen.

This is on 2.6.0

**Comment by kau210** [comment]
I believe we have a fix for this.

Quit rocket chat (not just close the window, but quit using the taskbar icon). Edit this file: C:\Users\USERNAME\AppData\Roaming\Rocket.Chat+\window-state-main.json . It may look like: 

{
"width": 1000,
"height": 600,
"x": -1219,
"y": 320,
"isMaximized": false,
"isMinimized": false,
"isHidden": false
}


Edit the " x" coordinate to 0. Restart. Fixed.

**Comment by clintlalonde** [comment]
@thehutman Brilliant tip! Thank you.

**Comment by arb-rasmus** [comment]
I'm having this issue as well.
Using laptop and when disconnecting from the dock, it doesn't reset, it stays on the secondary screen which isn't there anymore.

Did the same thing as @kau210 but it's annoying that you have to do it.

**Comment by MauriceBrg** [comment]
This issue still exists on the **2.9.0** Client and is really annoying, but the workaround works as well...

**Comment by pohlmarcus** [comment]
Problem still exists in version 2.10.5

**Comment by chrootLogin** [comment]
I also have this problem in 2.10.5

**Comment by emk888** [comment]
This is still an issue. Pls fix.

**Comment by BradleyUffner** [comment]
This is a serious issue, please fix.

**Comment by tassoevan** [comment]
@fuss86 We close the issues when the `develop` branch has the resolution merged to keep our milestone goals clear. In no way that means a "won't fix".

By the way, there is a beta release for `2.14.2`: https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.14.2-beta.1
