### ISSUE TITLE
Cannot disable "Desktop Notifications" windows 8.1

### ISSUE THREAD

**Issue by swvajanyatek** [RocketChat/Rocket.Chat.Electron#381]
## My Setup
Windows 8.1
Rocket Chat Version 2.4.0
I just upgraded to Version 2.4.0, and I can see in "Preferences --> Messages --> Desktop Notifications are enabled", but I do not see any way to disable them, only button for testing them (and they work).  I'm guessing that I'm missing something obvious here, but I'm lost as to what.

**Comment by alexbrazier** [comment]
@swvajanyatek You need to set your notification preferences on a per channel basis.
![image](https://cloud.githubusercontent.com/assets/5689874/23824411/07f249e6-066e-11e7-8cc9-fdfb89c28fbe.png)
There is also a PR to set a default options RocketChat/Rocket.Chat#4339

**Comment by swvajanyatek** [comment]
so, would I also need to set it for every person/direct message too?  That would obviously be very tedious (and a poor choice for default behavior).

**Comment by alexbrazier** [comment]
@swvajanyatek That is the current situation, until the pull request mentioned in my previous comment gets merged.

**Comment by swvajanyatek** [comment]
Gotcha.  Thanks for the insight.
