### ISSUE TITLE
Can't download files from channels in mac client

### ISSUE THREAD

**Issue by tqkruger** [RocketChat/Rocket.Chat.Electron#382]
macOS 10.12.3
Rocket.chat+ 2.50

When a file is uploaded to a channel, DM og private groups, you can't download the file through the client

I have testet it against the my own server (ubuntu 16.04, rocket.chat 0.52.0) and against demo.rocket.chat. The problem occurs in both places

**Comment by thehutman** [comment]
Can confirm we have this issue in the Windows client as well (2.5.0).  Looks like the attached fix does solve our problems.

**Comment by tqkruger** [comment]
Thanks for the quick fix. It works
