### ISSUE TITLE
Bug: link to media posted on channel = Server Failed to Load

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat.Electron#385]
## My Setup
 - __My OS name and version__: OS X or any other...
 - __My current app version__: 2.5.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Bug while pasting media link to public channel (for ex. youtube movies) - "Server Failed to Load" - ONLY in Rocket app client. Just can't join again to this channel until the post with link is removed. No errors in server logs. This happens only in public/private channels, priv msg working just fine. Refreshing/clearing cache app doesn't help.

In server dev tools:

Uncaught ReferenceError: Meteor is not defined
    at /Applications/Rocket.Chat+.app/Contents/Resources/app.asar/app/public/preload.js:19
12/Applications/Rocket.Chat+.app/Contents/Resources/app.asar/app/public/preload.js:75 Error getting system idle time: ReferenceError: Meteor is not defined

In app dev tools:

webview.js:75webview: Uncaught TypeError: Cannot read property 'style' of null
webview.js:75webview: Uncaught ReferenceError: Meteor is not defined
13webview.js:75webview: Error getting system idle time: ReferenceError: Meteor is not defined
webview.js:75 webview: Error getting system idle time: ReferenceError: Meteor is not defined

#### Current Behavior
![screen](https://cloud.githubusercontent.com/assets/3985913/23653469/f8d9d6a2-032c-11e7-97e6-8c655985a2ac.jpg)

**Comment by krnlde** [comment]
I'm getting the same error on Win10 64bit with Rocket.Chat 2.5.0

![image](https://cloud.githubusercontent.com/assets/1087002/23901029/d2ea8826-08bb-11e7-93dd-028bad03a1b8.png)

**Comment by jbguerraz** [comment]
Facing the same issue with youtube video embed on electron app only (OK on web app)

**Comment by Venomen** [comment]
Any update on this? Verry annoying bug :(

**Comment by mdesign83** [comment]
same here (works from browser, not from windows app): 
` webview: Uncaught ReferenceError: Meteor is not defined webview.js:75`
(win10, rocket.chat windows app)

**Comment by alexbrazier** [comment]
@mdesign83 What version of the desktop app are you using?

**Comment by mdesign83** [comment]
@alexbrazier 2.5.0

**Comment by alexbrazier** [comment]
@mdesign83 Please can you upgrade to [2.6.1](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.6.1), as this bug has been resolved.

**Comment by mdesign83** [comment]
@alexbrazier Thx, it seems fixed now. (I downloaded the "latest" from the website, but it linked to the 2.5.0 yet)

**Comment by alexbrazier** [comment]
@rodrigok Are you able to update the links on the website to 2.6.1?
