### ISSUE TITLE
Severe input delay with en_GB spellchecking enabled

### ISSUE THREAD

**Issue by timcooper** [RocketChat/Rocket.Chat.Electron#387]
## My Setup

Windows 10 Pro
2.5.0 (was the same in 2.4.0)

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

When typing a message there is a severe delay between keystrokes after the first word and the characters rendering in the box (in fact the entire application hangs during this time). There are some older closed issues reporting this with PRs/commits supposedly fixing but this issue is still very much there on the latest version.

Same/similar closed issues:
#289
#358 

Quite often this also results in the app freezing completely requiring a restart.

I can always reproduce this by enabling spell checking then starting to type (begins after first word/space). Currently I can't use the app because of this issue and just have rocket.chat open in a chrome window.

#### Current Behavior

Unusable input delay:
![test](https://cloud.githubusercontent.com/assets/456151/23704365/6c1b5526-03fc-11e7-8dff-e2a147e4996f.gif)

#### Expected Behavior

Works as expected after disabling spellchecking for en_GB:
![test2](https://cloud.githubusercontent.com/assets/456151/23704506/2c7de3f6-03fd-11e7-9e92-24be594520bf.gif)

**Comment by andyshilton** [comment]
We can confirm this too. Our Windows 10 users have been experiencing the exact same issue. After turning off the spell checking, it works ok.

**Comment by thehutman** [comment]
Windows 10 EN-US spelling isn't quite as bad, but the lag gets progressively worse the more text we write.  Doing a performance CPU profile on a long string already in the message box (adding just two words to a 20 word sentence) shows a huge amount of time going on within a few scripts:

![image](https://cloud.githubusercontent.com/assets/4375809/23783064/4d72953a-051e-11e7-8851-d2326e96c1a3.png)

This was done from the server dev-tools within the application.

Turning off spell-check removes the lag.

**Comment by LXSysadmin** [comment]
+1

**Comment by thehutman** [comment]
I'm trying to understand some recent code changes in /src/public/lib/SpellCheck.js I think are causing this problem.

```
    isCorrect (text) {
        if (!this.enabledDictionaries.length || this.contractions[text.toLocaleLowerCase()]) {
            return true;
        }

        if (this.muliLanguage) {
            for (let i = 0; i < this.enabledDictionaries.length; i++) {
                checker.setDictionary(this.enabledDictionaries[i]);
                if (!checker.isMisspelled(text)) {
                    return true;
                }
            }
        } else {
            return !checker.isMisspelled(text);
        }
        return false;
    }
```

The part `if (this.multiLanguage)` seems suspect.  In our case only one language is enabled .. so why check multiple?  If we modify the check to be something like `if (this.enabledDictionaries.length > 1)` then the performance seems much better -- when only one dictionary is enabled.  If we enable TWO dictionaries, then performance becomes drastically slower when we go into this mode.  Seems like repeatedly calling the `setDictionary` method is a performance killer.

Not really sure how to combat this for anyone using multiple languages (we aren't).  Maybe a limitation of the spellcheck library.

**Comment by thehutman** [comment]
Ok, looking at how multiLanguage is assigned, it appears to want to indicate TRUE when running on a non-windows platform.  However, the code doesn't work like that I believe:

```
    loadAvailableDictionaries () {
        this.availableDictionaries = checker.getAvailableDictionaries().sort();
        if (this.availableDictionaries.length === 0) {
            this.muliLanguage = false;
            // Dictionaries path is correct for build
            this.dictionariesPath = path.join(remote.app.getAppPath(), '../dictionaries');
            this.availableDictionaries = [
                'en_GB',
                'en_US',
                'es_ES',
                'pt_BR'
            ];
        } else {
            console.log(isWindows);
            this.muliLanguage = !isWindows;
            this.availableDictionaries = this.availableDictionaries.map((dict) => dict.replace('-', '_'));
        }
    }
```

In the `else` block, there is `!isWindows` -- but this is assigned via:
`const isWindows = ['win32', 'win64'].indexOf(os.platform());`

This returns a -1 when not a win32/win64 platform.  Seems like the multiLanguage needs to be `this.muliLanguage = (isWindows < 0)` but I am only making an assumption here based on how the spellcheck library appears to operate on my systems here (Win10 64 bit -- which report as os type win32 for some reason).  This causes in the original code to turn on the multiLanguage flag, causing slowness by constantly changing the available dictionaries.

**Comment by alexbrazier** [comment]
@thehutman good spot. The `isWindows` variable was just missing `!== -1` to make it a bool. I have opened a PR that fixes the issue.

**Comment by brandborg** [comment]
I had the same issue and I can verify after installing the build artifact from the merge request here:
https://ci.appveyor.com/project/RocketChat/rocket-chat-electron/build/1.0.289/artifacts
