### ISSUE TITLE
File download not working anymore 2.5.0

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat.Electron#388]
Windows 10 64 bit;
RocketChat server 0.53.0;
Rocket.Chat.Electron 2.5.0;

File download not working. File download links and icon don't work. You can't download files.

**Comment by oliver-bowman** [comment]
Having the same issue with a few of my colleagues, server is set to accept any file type and uses GridFS, permissions of files have been double checked, issue still occurs.

**Comment by zookah** [comment]
Same thing on Mac app (2.5.0).
Server 0.54.0.
macOS 10.12.4 Beta

**Comment by ecoitsolutions** [comment]
Same here from Mac, Windows and Linux.

**Comment by LXSysadmin** [comment]
When will 2.6.0 version will be released????????? You know, that this is f-king extra MEGA big bug and 99,9% user all telling everyone, that you client sux. This must be fixed not after 666 days but this fix should be released after 1 day after your failing 2.5 version! SO, please turn on your heads and do it now!!!!!

**Comment by Ri100** [comment]
I can't confirm that... RocketChat+ Client v2.5.0 on Windows 10 is working fine for us.

**Comment by LXSysadmin** [comment]
You can download files from client? In what way?

**Comment by LXSysadmin** [comment]
Ri100 - what server version do you have?

**Comment by Ri100** [comment]
Download works as expected by clicking on the dl icon (the highlighted one in the pic).
I will need to check about the server version with my colleague, who will be back in office tomorrow.
![image](https://cloud.githubusercontent.com/assets/13216315/24398305/50382b74-13a9-11e7-8151-848de4e5a921.png)

--Best

**Comment by LXSysadmin** [comment]
There is very important what server version do you have. From 0.53.0 version 2.5.0 client can´t download files. Workaround is to use 2.4.0 client, but then why to release 2.5.0? :)

**Comment by willihelm** [comment]
I´ve seen that the bug is allready fixed in dev. could you please release a subversion like 2.5.1 with this bugfix.

**Comment by oliver-bowman** [comment]
I agree, for me and my company this bug is really annoying.
