### ISSUE TITLE
Closing/Removing a connection to a connected server

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat.Electron#39]
Currently we can only right click over the number for server on the left pane and click Remove Server from the context menu to remove or close the connection to a server.

I don't think it's visually very intuitive.

I personally think a red X button appearing when hovered on the top right corner of the server number would be a nice idea.
##

**Comment by mide** [comment]
Oh, wow. I didn't even know this was an option. I think that proves your point... A red X button or a gear icon might be more inviting.

**Comment by marceloschmidt** [comment]
Also, when you remove a server from the server list, the shortcut numbers are not reassigned until you reload the app

![image](https://cloud.githubusercontent.com/assets/1986378/13881167/88206254-ecfe-11e5-832c-9d1401f68561.png)

**Comment by rodrigok** [comment]
@marceloschmidt this is not relative to this issue.

**Comment by engelgabriel** [comment]
Slack and Discord work the same way. I do think it is clear enough. Having the X button is far too much highlight for this action.
