### ISSUE TITLE
Clients fails to reconnect when using iframe login - Exception in delivering result of invoking 'login': TypeError: e is not a function

### ISSUE THREAD

**Issue by tqkruger** [RocketChat/Rocket.Chat.Electron#392]
## My Setup

 MacOS/windows: 
 2.5.0: 

- [X ] I have tested with the latest application version
- [X ] I can simulate the issue easily

## Description

We use Iframe Integration to handle login. The problem is when connection to the server is cut do to laptop sleep, it wont properly reconnect. I have experienced three errors:

1. fail to load server screen
2. the three dots loads for ever, but sidebar is visible. You can receive messages and notification but not use the application
3. you are redirected to the login screen

If I reload the application in all there errors operations resumes to normal.

**Comment by tqkruger** [comment]
I'm also experience when connecting to demo.rocket.chat

![skaermbillede 2017-03-20 kl 16 25 29](https://cloud.githubusercontent.com/assets/21054876/24107085/21c4f044-0d8a-11e7-994c-d74007ccd7bc.png)

**Comment by tqkruger** [comment]
The problem in v2.6.

<img width="777" alt="skaermbillede 2017-04-04 kl 16 58 32" src="https://cloud.githubusercontent.com/assets/21054876/24666645/38ed5ac6-1961-11e7-8227-4faa71465ea2.png">
<img width="780" alt="skaermbillede 2017-04-04 kl 16 58 21" src="https://cloud.githubusercontent.com/assets/21054876/24666644/38eda486-1961-11e7-9763-0cfd164183fd.png">
<img width="759" alt="skaermbillede 2017-04-04 kl 16 58 14" src="https://cloud.githubusercontent.com/assets/21054876/24666646/38ef3d6e-1961-11e7-9c1c-d49f9aeed754.png">
<img width="1192" alt="skaermbillede 2017-04-04 kl 16 58 00" src="https://cloud.githubusercontent.com/assets/21054876/24666643/38ec16f2-1961-11e7-8df1-efea5191783e.png">

**Comment by tqkruger** [comment]
![skaermbillede 2017-04-05 kl 10 57 24](https://cloud.githubusercontent.com/assets/21054876/24697852/eda7736a-19ee-11e7-8fb3-c68aa11bcbb8.png)

**Comment by graywolf336** [comment]
This looks like an issue for rocket.chat itself and not the Electron client.

**Comment by tqkruger** [comment]
@graywolf336 any idea where to look? Rocket.chat v0.54.2 with iframe login

**Comment by tqkruger** [comment]
Solved see https://github.com/RocketChat/Rocket.Chat/issues/6839#issuecomment-308388890
