### ISSUE TITLE
Rocket.Chat+ Helper crashes

### ISSUE THREAD

**Issue by kainjow** [RocketChat/Rocket.Chat.Electron#394]
## My Setup
- OS: macOS Sierra 10.12.3 
 - App version: 1.3.1 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

I installed the program from the App Store, and after launching I got some crashes of the helper process. Seems to occur every time I launch the app.

Maybe a new Electron version will fix it?

[crashes.zip](https://github.com/RocketChat/Rocket.Chat.Electron/files/842632/crashes.zip)

**Comment by compuguy** [comment]
Install the latest release on github (for some reason they have not updated the app store release in quite some time): https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by kainjow** [comment]
Thanks, no more crashes with 2.5. I opened a new issue for the old MAS version.
