### ISSUE TITLE
"Server failed to load" - "Reload" button isn't working

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Electron#395]
## My Setup

 - __My OS name and version__: Ubuntu 16.04, Windows 10
 - __My current app version__: 2.5.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

User need VPN to connect to our server. RocketChat is starting at logon, tries to connect.
Before user log into our VPN message "Server failed to load" appears. After VPN connection is estabilished, "Reload" button does nothing, message still appears, so user can't log in. The only fix is ctrl+alt+r.

#### Current Behavior

After connecting to VPN, RocketChat still shows message "Server failed to load". "Reload" button does nothing.
#### Expected Behavior
After clicking "Reload" button RocketChat should work as ctrl+alt+r works.

**Comment by alexbrazier** [comment]
This is working for me in the develop version, please reopen if it's still an issue
