### ISSUE TITLE
unattended installs no longer working

### ISSUE THREAD

**Issue by JDEKnox** [RocketChat/Rocket.Chat.Electron#396]
## My Setup

 - Windows 10: 
 - 2.5.0, 2.4.0: 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Since moving to 2.4.0 and 2.5.0 unattended installs are no longer working
rocketchat-Setup-2.5.0.exe /S
rocketchat-Setup-2.5.0.exe /S /allusers
rocketchat-Setup-2.4.0.exe /S
rocketchat-Setup-2.4.0.exe /S /allusers
all of the above have been tried as well as the reverse of /S and /allusers

#### Current Behavior

Installer kicks off, runs the uninstall-old, and then exits.
#### Expected Behavior

Installer kicks off, runs the uninstall-old, kicks off new-installer

**Comment by Levesque7** [comment]
I second this issue. Trying to deploy to 1500+ users but currently when using the /s switch, it still asks to confirm the install directory.

Where can I download 2.3.0 in the meantime?

**Comment by adesimonepeak6** [comment]
I third this issue.  /S works in 2.8 but /ALLUSERS does not

**Comment by gdelavald** [comment]
Hey guys, for this issues:
- Make sure you are using /S (capitalized), for some reason the lowercase doesn't trigger the same as the uppercase;
- For /ALLUSERS make sure you are running the cmd with elevated rights as this requires admin power.

**Comment by gdelavald** [comment]
I'll close this issue for now, if any of you run into more issues please re-open this one or open a new issue. Thanks.
