### ISSUE TITLE
Unable to change google account when not registered with the server

### ISSUE THREAD

**Issue by richardborder** [RocketChat/Rocket.Chat.Electron#398]
## My Setup

 - __My OS name and version__: Fedora 25 
 - __My current app version__: 2.5.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

Accidentally attempted to log in with a google account other than the registered with the server. I have no option to change the google account and repeatedly receive a "User is not activated" notification. Restarting the application, readding the server, and forgetting trusted certificates do not solve the problem

#### Expected Behavior

I should have the opportunity to log in with a different google account if the current one does not work.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
