### ISSUE TITLE
Unable to leave a channel when I'm the only owner

### ISSUE THREAD

**Issue by slavashvets** [RocketChat/Rocket.Chat.Electron#399]
## My Setup

**OS:** Windows 7 64bit and Windows 10 64bit (My PC and laptop)
**Appliction version:** Rocket.Chat+ Version 2.5.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Steps to reproduce:
1. Create a channel
2. Add people to the channel
3. Make sure that you are the only owner of the channel
4. Press button "Leave channel"
5. See message something like "You can't leave the chat, because you are last owner"

#### Current Behavior

The channel is removed from the left panel. If I try to open the channel in preview mode, I see "Join" button, but when I press it there is no reaction because I still a member of the channel.

#### Expected Behavior

The channel is not removed from the left panel until I'am owner. Also it would be nice to have some feedback if I press "Join" button without success. I mean some error message, for example: "You can't join to the channel because you're already here".

**Comment by gdelavald** [comment]
Closing this as this is not related to Electron. Please check the [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) repository for more information.
