### ISSUE TITLE
OAuth not working

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat.Electron#4]
See 
http://iamemmanouil.com/blog/electron-oauth-with-github/
http://stackoverflow.com/questions/30281732/electron-reactjs-use-browserwindow-for-github-oauth-authentication

**Comment by rodrigok** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat.Electron/commit/5cbb7846f152cd61080d7b956a3a8c673b55345a
