### ISSUE TITLE
Rocket Chat programs is missing user logos before user text

### ISSUE THREAD

**Issue by randbret** [RocketChat/Rocket.Chat.Electron#400]
## My Setup

 - __My OS name and version__:  Windows 10
 - __My current app version__: Rocket.Chat+ Version 2.4.0

- [ ] I have tested with the latest application version
- [ ] I can simulate the issue easily

## Description

Steps:
1.) open programs: Rocket.Chat+ version 2.4.0;
2.) open channels or users chat.

#### Current Behavior
Missing user logos before user text. It's happen only then is computer wake up to sleep. Other time when I open programs when are before user text to user logos.

![rocket](https://cloud.githubusercontent.com/assets/5684590/24093256/9bd29f8c-0d5b-11e7-9b61-e90adf473b23.jpg)

#### Expected Behavior
Before user text is user logos.

**Comment by litewhatever** [comment]
+1

**Comment by compuguy** [comment]
I've seen this happen on older versions of app on MacOS. Haven't seen this on 2.6.1 yet.

**Comment by gdelavald** [comment]
Closing this as this is not related to Electron. Please check the [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) repository for more information.
