### ISSUE TITLE
Mac App Store version is very old

### ISSUE THREAD

**Issue by kainjow** [RocketChat/Rocket.Chat.Electron#403]
The Mac App Store version, which is linked to on the [download](https://rocket.chat/download) page, is 1.3.1 while the latest is 2.5.

Either the MAS version should be consistently updated, or it shouldn't be used at all if it's serving a very out of date version.

**Comment by Prakharsvnit** [comment]
@rodrigok @engelgabriel Fix for this issue could be updating the version number to 2.5 if MAS is serving version 2.5

**Comment by compuguy** [comment]
@Prakharsvnit MAS still has 1.3.1 (very old). If its not kept up, it may be better just to use sparkle to push updates (or something similar).

**Comment by gregs007** [comment]
Agreed. This cause a lot of confusion across my org when we deployed. Confirmed app store version is 1.3.1

**Comment by adeviadoug** [comment]
What is involved in updating the MAS version?

**Comment by kainjow** [comment]
@adeviadoug someone who has access to the Rocket.Chat Mac App Store account needs to upload and submit a new version to Apple. It's been years since I did this but I don't think it can be automated. IMO I think it'd be better to remove it and just use normal hosted downloads once the auto-updater starts working.
