### ISSUE TITLE
Inset design

### ISSUE THREAD

**Issue by t40mas** [RocketChat/Rocket.Chat.Electron#404]
Love rocket chat and your client. 
It would be great to have a modern inset design in the next release. 

Let me know, if I should carry out a pull request.

**Comment by marceloschmidt** [comment]
Hi @t40mas what do you mean by inset design? Do you have an example of that? Thanks.

**Comment by t40mas** [comment]
Sorry for that late response. 
I meant the title-bar:hidden-inset option.

But it works perfectly with the new version 2.6.0.

First I thought I ran my fork the whole time :)

**Comment by gdelavald** [comment]
Looks like this is already solved, so I'll close the issue. Thanks.
