### ISSUE TITLE
Can't switch channels by clicking them on the left pane

### ISSUE THREAD

**Issue by OrdinaryGuy** [RocketChat/Rocket.Chat.Electron#405]
## My Setup

 - __My OS name and version__: w10 1607
 - __My current app version__: 2.5.0
 - __My current server version__: 0.53.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Upgraded 2.4.0 client app to 2.5.0.
Tried to uninstall the app cleaning user data and reinstalled new version - didn't help.

#### Current Behavior

Can't switch the channel thru the sidebar.
Although can do it by searching for a channel and selecting it.

#### Expected Behavior

Click the channel name on the left pane to switch it.

**Comment by gdelavald** [comment]
@OrdinaryGuy can you check if this is still happening?

**Comment by OrdinaryGuy** [comment]
@gdelavald, this has been fixed a long ago. 
The issue should be long time closed.
