### ISSUE TITLE
Image won't display since 0.54.0 upgrade

### ISSUE THREAD

**Issue by avignat** [RocketChat/Rocket.Chat.Electron#406]
## My Setup

Tested on : macOS, Windows 10
Rocket Client : 2.5.0

- [X] I have tested with the latest application version
- [X] I can simulate the issue easily

## Description

Image won't display since 0.54.0 upgrade : 

![capture d ecran 2017-03-23 a 18 31 43](https://cloud.githubusercontent.com/assets/1545450/24261456/46bbfa7c-0ff7-11e7-9566-a7312a1b1f0e.png)

**Comment by graywolf336** [comment]
This was fixed via https://github.com/RocketChat/Rocket.Chat/pull/6424 and a hotfix for 0.54 will be out later today sometime.

**Comment by dkoryavov** [comment]
I have the same problem with Rocket.Chat 2.8.0 on Ubuntu 16.04. Server version: 0.57.3. Should I open a new issue?

**Comment by gdelavald** [comment]
@dkoryavov Yes please do, this way we can track with updated info. Thanks.
