### ISSUE TITLE
unable to select text in chat window with mouse

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat.Electron#410]
Rocketchat 0.54.1
Electron: 2.6.0
MacOSX 10.12.4

Hi Devs.

I'm not able anymore to select text from the chat window with mouse. If i press the left mouse button and hold it to select text the entire rocketchat window is pinned and moving if i move the mouse. Is this a know bug of this version?

thanks and cheers

**Comment by MrLukeSmith** [comment]
I'm also experiencing this issue since updating the client to 2.6.0.

**Comment by himbeere** [comment]
2.6.1 works for me. Thanks!

**Comment by kainjow** [comment]
This was fixed with 2.6.1. Issue should be closed.
