### ISSUE TITLE
Active Directory Fields on userpage (new feature)

### ISSUE THREAD

**Issue by ST-KW** [RocketChat/Rocket.Chat.Electron#418]
## My Setup

 - __My OS name and version__: Windows 10
 - __My current app version__: 2.5.0

## Description

As a user I want to see some active directory fields like phone number, mobile number or position at the user page in the app.

![image](https://cloud.githubusercontent.com/assets/25076997/25004788/567c2e90-2056-11e7-97e3-3a603b942555.png)

#### Current Behavior

It's not possible to show aditional Information at the user page.

#### Expected Behavior

It's possible to select some (existing) active directory fields in the rocket.chat config and these fields are shown at the user page e.g. phone number, mobile number or position.

**Comment by alexbrazier** [comment]
Reopened in RocketChat/Rocket.Chat#6757 as this is related to the main Rocket.Chat app
