### ISSUE TITLE
Social Media Links on userpage (new feature)

### ISSUE THREAD

**Issue by ST-KW** [RocketChat/Rocket.Chat.Electron#419]
## My Setup

 - __My OS name and version__: Windows 10
 - __My current app version__: 2.5.0

## Description

As a user I want to add my social media links (github, xing, linkedin, twitter, facebook, instagram, flickr, youtube, google+) to the user page in the app / web.

![image](https://cloud.githubusercontent.com/assets/25076997/25004788/567c2e90-2056-11e7-97e3-3a603b942555.png)

#### Current Behavior

It's not possible to add / show social media links at the user page.

#### Expected Behavior

It's possible to add social media links (github, xing, linkedin, twitter, facebook, instagram, flickr, youtube, google+) in the profile. If a field is empty it's not shown, if there is a valid link in a field the appropriate Icon (e.g. https://lipis.github.io/bootstrap-social/) is shown at the user page.

**Comment by alexbrazier** [comment]
Reopened in #6756 As this is related to the main Rocket.Chat app
