### ISSUE TITLE
No notif sound on channels

### ISSUE THREAD

**Issue by BigPapoo** [RocketChat/Rocket.Chat.Electron#420]
## My Setup
 - Mac OS X 10.11.6 - El Capitan: 
 - Rocket.Chat+ 1.3.1: 

## Description

I can get notification sounds + notification badge (1) on private messages but no sound and a dot (.) badge on other channels...

**Comment by alexbrazier** [comment]
@BigPapoo what are your notification preferences for the channel?

![image](https://cloud.githubusercontent.com/assets/5689874/25773882/6f9b6dd0-327d-11e7-85e6-8a0fb1435f18.png)

**Comment by krisgermann** [comment]
Is there any way to make these setting here default? Ie. automatically enable mobile and desktop 'all messages' for any subscribed user?

The current alternative being that they must manually select for each one...

**Comment by alexbrazier** [comment]
This has now been added
