### ISSUE TITLE
Rocket Chat+ Does not work behind a proxy

### ISSUE THREAD

**Issue by jomach** [RocketChat/Rocket.Chat.Electron#421]
## My Setup
 - __My OS name and version__:  latest
 - __My current app version__: latest

Hi all, 

So I installed the last version from rocketchat, I'm using a vpn and I need to go over a proxy. I have defined the proxy on mac system preferences. Over Chrome I can get to my rooms. 

On the local app it just says that the url was not found. 

Regards

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

**Comment by sscholl** [comment]
I use docker behind a reverse proxy and Rocket.Chat+ is also not working. The login screen is just loading forever. 
Anyone has an idea?
Thanks

**Comment by jomach** [comment]
They are Probally not getting the System proxies.

**Comment by sscholl** [comment]
Duplicate to https://github.com/RocketChat/Rocket.Chat/issues/6465
I found my solution in https://github.com/RocketChat/Rocket.Chat/issues/1061
This config worked
```
            <Location />
            Require all granted
            Options -Indexes
        </Location>

        ProxyPass /websocket ws://localhost:3000/websocket
        ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:3000/sockjs/$1/websocket
        ProxyRequests Off
        ProxyPass / http://127.0.0.1:3000/
        ProxyPassReverse / http://127.0.0.1:3000/
```

**Comment by jomach** [comment]
So for me using a client I need to install a proxy ?

**Comment by sscholl** [comment]
OKOK, there are 2 kinds of proxys. I assumed you talk about an reverse proxy. My Config I posted is the apache config for an reverse proxy to enable websockets through the proxy.

But if you talk about an proxy between you and the internet, I cant help you. Especially, if you are not able to configure it. In this case, please close this issue, because nobody can do anything for you.
If you are able to configre the proxy, I assume, that this proxy blocks the websocket connection - which are required for Rocket.Chat+.

**Comment by jomach** [comment]
Hey, I don't really think so.  Rocket chat should have the possibility to Say hey please use this proxy with this username and password. After all on the browser it works without any problem.

Regards

**Comment by gdelavald** [comment]
Some of the discussion here is related to Server Proxy which should be discussed in Rocket.Chat repository, for the actual app proxy please see #407 .

**Comment by FaizanZahid** [comment]
Also having same issue, when i try to open rocket chat demo using my chrome browser VPN extension, all i see is a blank screen, and JS console showing following errors.

![image](https://user-images.githubusercontent.com/9073066/45679476-a708db80-bb30-11e8-9f18-b04b077bb157.png)



48
XHR finished loading: GET "<URL>".
c029a6b……js_resource=true:57 WebSocket connection to 'wss://open.rocket.chat/sockjs/298/5rlku7vm/websocket' failed: Error in connection establishment: net::ERR_NOT_IMPLEMENTED
43
XHR finished loading: POST "<URL>".
VM2746:1 POST https://open.rocket.chat/sockjs/298/5ri2u4yk/xhr_send 404 ()
28
XHR failed loading: POST "<URL>".
18
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
VM2746:1 POST https://open.rocket.chat/sockjs/222/6zysg7nn/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/518/a1z1epbl/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/112/c883vc6h/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/067/ryo1nlde/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/596/1v2ymqmo/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/726/nlg_g95q/xhr_send 404 ()
c029a6b……js_resource=true:57 WebSocket connection to 'wss://open.rocket.chat/sockjs/924/jssq49qa/websocket' failed: Error in connection establishment: net::ERR_NOT_IMPLEMENTED
VM2746:1 POST https://open.rocket.chat/sockjs/877/_ck0arof/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/219/z5vjk_bu/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/885/r2s67oid/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/940/ts0fdrj1/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/492/g_81hxn9/xhr_send 404 ()
c029a6b……js_resource=true:57 WebSocket connection to 'wss://open.rocket.chat/sockjs/950/5kacdjzf/websocket' failed: Error in connection establishment: net::ERR_NOT_IMPLEMENTED
VM2746:1 POST https://open.rocket.chat/sockjs/950/l4k70pcs/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/684/n88ywln_/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/021/qseap1b8/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/336/kx8x0hp2/xhr_send 404 ()
c029a6b……js_resource=true:57 WebSocket connection to 'wss://open.rocket.chat/sockjs/887/7x5tjvx1/websocket' failed: Error in connection establishment: net::ERR_NOT_IMPLEMENTED
VM2746:1 POST https://open.rocket.chat/sockjs/887/2epk86y6/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/772/urucsw9g/xhr_send 404 ()
VM2746:1 POST https://open.rocket.chat/sockjs/500/wm8ot37x/xhr_send 404 ()
c029a6b……js_resource=true:57 WebSocket connection to 'wss://open.rocket.chat/sockjs/544/t0ddlkcv/websocket' failed: Error in connection establishment: net::ERR_NOT_IMPLEMENTED

**Comment by tassoevan** [comment]
@FaizanZahid Your issue is related to the Rocket.Chat server, please reopen it in the [server repository](https://github.com/RocketChat/Rocket.Chat). Thanks!

**Comment by Noman5237** [comment]
location / {
                proxy_pass https://https-backend;
                proxy_set_header Host $host;
                proxy_set_header        X-Real-IP $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;
                client_max_body_size 0;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
