### ISSUE TITLE
If a user is logged in to a server and then tries to connect to the same server nothing happens from their point of view

### ISSUE THREAD

**Issue by Rumbles** [RocketChat/Rocket.Chat.Electron#422]
## My Setup

 - __My OS name and version__: openSUSE/Fedora
 - __My current app version__: 2.4/2.6.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

One of our users (running on openSUSE with 2.4) just reported an issue where he told me "I've been kicked out of rocket chat and can't get back in". When I went up the rocket chat electron app was sat on the "Add new server" page. The server list on the left was hidden (we use one server, we advise people to hide it).

When the user typed in the URL for our server to connect, it just showed the same page again with the server name removed (basically reloaded the page and did nothing)

The reason the user had this issue, was that he was logged in to our rocketchat server, so when he tried to connect to the server the app must have decided no action was necessary as he was already connected. I don't know he got in to this state, maybe there is a keyboard shortcut to get to the "Add new server" dialogue that I don't know about and he hit accidentally.

I opened up the server list and clicked on our server and everything was fine.

When I got back to my desk I reproduced the issue on my machine (Fedora/2.6.1)

#### Current Behavior

The app doesn't tell you anything if you try to connect to a server you are already connected to.

#### Expected Behavior

The app should either take you to that rocketchat server, or pop up a message telling you you are already connected, to avoid confusion.

**Comment by alexbrazier** [comment]
@Rumbles I've made a change so that if you type the server name again it will load it, rather than ignoring. Will that resolve your issue?

There is a shortcut `Ctrl+N` to add a new server, so that may be how it happened. It is also possible to switch servers using `Ctrl+1` etc and you can manually select them from the Window menu, without having to open the server list.
