### ISSUE TITLE
Bug on open About

### ISSUE THREAD

**Issue by willihelm** [RocketChat/Rocket.Chat.Electron#427]
## My Setup

 - __My OS name and version__: Windows 7
 - __My current app version__: 2.7.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

When I open the about page I get an Error.
![2017-04-26 08_56_50-error](https://cloud.githubusercontent.com/assets/16389803/25421707/5abefc82-2a5e-11e7-965e-4040748a3427.png)

#### Expected Behavior

Show about page.

**Comment by kkachura** [comment]
On Windows same result!

**Comment by himbeere** [comment]
MacOSX too.

**Comment by Zerocool56** [comment]
On Win7 Pro and Mint 18.1 Xfce

**Comment by thehutman** [comment]
Windows 10 -- ditto (see #431)

**Comment by JVijsma** [comment]
Screenshot of the error on OSX 10.11.6 (15G1421):
<img width="518" alt="about rc osx error" src="https://cloud.githubusercontent.com/assets/13855815/25519881/f1b1150c-2bf9-11e7-9fe0-0cc341b98ca1.png">
