### ISSUE TITLE
Issue with updating the desktop rpm from 2.6.0 to 2.7

### ISSUE THREAD

**Issue by ohaessler** [RocketChat/Rocket.Chat.Electron#428]
On RHEL 7, updating the Desktop rpm from 2.6.0 to 2.7 gives the following error:

sudo rpm -Uhv rocketchat-desktop-2.7.0.rpm 
Preparing...                          ################################# [100%]
	file /opt/Rocket.Chat+/libffmpeg.so from install of rocketchat-desktop-2.7.0-1.x86_64 conflicts with file from package rocketchat-2.6.0-1.x86_64
	file /opt/Rocket.Chat+/libnode.so from install of rocketchat-desktop-2.7.0-1.x86_64 conflicts with file from package rocketchat-2.6.0-1.x86_64
	file /opt/Rocket.Chat+/resources/app.asar from install of rocketchat-desktop-2.7.0-1.x86_64 conflicts with file from package rocketchat-2.6.0-1.x86_64
	file /opt/Rocket.Chat+/resources/electron.asar from install of rocketchat-desktop-2.7.0-1.x86_64 conflicts with file from package rocketchat-2.6.0-1.x86_64

Uninstalling 2.6.0 and installing 2.7 does work.

**Comment by gdelavald** [comment]
Sounds like the package name change caused this, but looks like the solution is at hand.

> Uninstalling 2.6.0 and installing 2.7 does work.
