### ISSUE TITLE
Install from source should leave some .desktop files

### ISSUE THREAD

**Issue by malevolent** [RocketChat/Rocket.Chat.Electron#43]
Perhaps I'm doing something wrong, but installation from source it's a bit unfinished. It compiles and starts perfect, but for a graphical application, it should be executable without the need of a shell. 
The installation script should move the application folder to any proper place (/opt at least) and a .desktop file in order to call the application from any desktop environment.

**Comment by engelgabriel** [comment]
You need to use the `npm release` command
