### ISSUE TITLE
Suggestion - Highlight the "Mentions" and other icons on right side bar 

### ISSUE THREAD

**Issue by Chripallo** [RocketChat/Rocket.Chat.Electron#432]
Hello! I'm sorry if this isn't the right place. I had a suggestion for the right vertical bar with the icons. Sometimes, going through scrollback can be a pain, especially with hundreds/thousands of messages.

I was curious if it was feasible to have the Files List, Mentions, Starred, and Pinned icons become highlighted whenever a new, unread entry appears in those lists. The main goal here was for the Mentions list, but I thought it might be great to have highlights for the other 3 as well. 

With this way, one could just check to see if any of the icons are highlighted and then look at those lists to read the scrollback relevant to them!

Anyways, thank you for reading.

**Comment by vmoutoussamy** [comment]
Correct me if I'm wrong but the side bar in 2017 is not the same in 2019.  And we already have icons for Mentions and Highlight on the "left side" where we can see the list of channels.

**Comment by jeanfbrito** [comment]
Please checkout the current state of Rocket.Chat and reopen this issue if you think that something is missing yet.
Thanks.
