### ISSUE TITLE
ScreenSharing doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by crazysoldier** [RocketChat/Rocket.Chat.Electron#433]
## My Setup

 - __My OS name and version__: ubuntu 16.04/unity
 - __My current app version__: 2.7.0

- [x ] I have tested with the latest application version
- [ ] I can simulate the issue easily

#### Current Behavior

I cant choose every screen/ one screen/application and after i start i sometimes see my own screen but never everyone else. 
So Bugs are: 
1. Preparation window is empty
2. Screenshare doesnt get sent to others.
Screenshot:

![screen](https://www2.pic-upload.de/thumb/33078584/screensharingdoesntwork.png)

If you wanna help directly, join my channel at https://crypto.rocket.chat

Cheers
Crazysoldier

**Comment by developherr** [comment]
Same behavior on OSX 10.11.6 w client v.2.8.0

**Comment by seancharlton** [comment]
We are facing the same Problem.

System: Ubuntu 16.04 with v.2.8.0.

Inbuild WebRTC gives me the Message "ScreenSharing Extension needs to be installed" ..
Jitsi-Meet WebRTC doesn't show me any Windows to share.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
