### ISSUE TITLE
Cache Modus for Offline

### ISSUE THREAD

**Issue by ruppo68** [RocketChat/Rocket.Chat.Electron#434]
Hi,

my users are requesting an offline modus for the client.

I have seen that a cache exist, but it is not usable.

How about a offline Function, which stores the last accesses local and store them. So if you don't hava a connection to the server you still can view the chats.

P

**Comment by engelgabriel** [comment]
This is a bit harder than it sounds. We are working on building this on the mobile clients first, and we copy this functionality to the desktop too, but this is done on the HTML client part of the project.
https://github.com/RocketChat/Rocket.Chat
