### ISSUE TITLE
Repeated install path changes

### ISSUE THREAD

**Issue by karlis-vitols** [RocketChat/Rocket.Chat.Electron#435]
## My Setup

 - __My OS name and version__:  Windows 10 x64, 1607
 - __My current app version__: 2.7.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

When installing application to a machine (deploying via SCCM, for example, via setup.exe /S /allusers), the folder name in Program Files has been changed two times. 
First was **Rocket.Chat+** folder back in 2.0, then it was changed to **rocketchat** somewhere around 2.2 and now it is **rocketchat-desktop**

#### Current Behavior

If, assuming, computer has version 2.5.0 installed, Rocket.Chat will be updated and keep install path to Program Files\rocketchat. If the computer does not have Rocket.Chat install, it will install to Program Files\rocketchat-desktop.

#### Expected Behavior

Install path should stay consistent during program's lifecycle, to ease the mass deployment (detection rules) and makes it less confusing as to why the install location is different between computers.

**Comment by engelgabriel** [comment]
Did not work :(

![image](https://cloud.githubusercontent.com/assets/1000217/25751987/40952b34-318d-11e7-8da9-0ee2a061dc4e.png)
