### ISSUE TITLE
EXE Silent Switch

### ISSUE THREAD

**Issue by alexandrebgagne** [RocketChat/Rocket.Chat.Electron#436]
## My Setup
Windows 10 Pro
Tried with 2.5 and 2.7

- [x] I have tested with the latest application version
- [x ] I can simulate the issue easily

## Description

EXE lunches as silent but prompt for the directory to finish the installation.

Tried with the Client installer 2.5 and 2.7.

Thank you

#### Current Behavior

Prompt to choose the installation path.

![image](https://cloud.githubusercontent.com/assets/5943830/25530581/c1dc34e2-2bf4-11e7-937a-386e6d1686bc.png)

#### Expected Behavior

Install without any prompt

**Comment by jstafford19713** [comment]
2.8 the issue reoccurs.  Will have to build as a msi to get around the issue.  It is accepting either the ?S switch or the /alluser switch, not both, when you have UNC turned on like most companies do

**Comment by gdelavald** [comment]
> 2.8 the issue reoccurs. Will have to build as a msi to get around the issue. It is accepting either the ?S switch or the /alluser switch, not both, when you have UNC turned on like most companies do
--

I just tested the 2.8.0 version, the /S is working as expected, notice that `/S /allusers` only works if you are running the commands as administrator, since it requires elevated permissions.
Please do test again and let me know if it is still going on.
