### ISSUE TITLE
Left click on tray icon should do something

### ISSUE THREAD

**Issue by adocampo** [RocketChat/Rocket.Chat.Electron#44]
As the title says, left clicking on the tray icon does nothing. At least on (Arch) linux. Right click shows the context menu and you can then hide/show the main window just fine, like quitting the application, but a one-click action would be faster, if the main window is hidden, one (or two) click shows it and brings it to front, and vice versa, if it is shown, then one left click on the tray icon should hide it. 

Speaking about the context menu, it would be nice to disable the uneeded option, i.e: hide option disabled when the main window is hidden, and show option hidden when the window is opened, or bring it to front.
##

**Comment by vbogdanov** [comment]
+1

**Comment by giray** [comment]
+1

**Comment by Hacksore** [comment]
+1

**Comment by alexbrazier** [comment]
The tray icon changes depending on the operation system, but on Windows if you left click the app will always open if not already, if you right click you get a menu with quit and show/hide (depending of if its open or not).
On mac you just get the menu show/hide & quit if you left or right click.

Is there anything else that is needed, or could be improved?

**Comment by vcapretz** [comment]
hey @alexbrazier take a look on https://github.com/RocketChat/Rocket.Chat.Electron/pull/544, I added some extra validation, but it already works just fine.

on Mac/Linux there's no difference between left or right clicks, it always will pop the context menu
