### ISSUE TITLE
W10 App: Javascript error main process

### ISSUE THREAD

**Issue by Maggew** [RocketChat/Rocket.Chat.Electron#441]
Just downloaded the desktop app, and when I clicked about

![image](https://cloud.githubusercontent.com/assets/1291364/25779327/6694220c-32e3-11e7-9142-e3bbbe73f3ac.png)

This was the error I received:

![image](https://cloud.githubusercontent.com/assets/1291364/25779317/4f392c4c-32e3-11e7-9810-56e393a5cc0b.png)

**Comment by nabiyllin** [comment]
This bug already solved https://github.com/RocketChat/Rocket.Chat.Electron/issues/427

**Comment by engelgabriel** [comment]
This bug already solved #427
