### ISSUE TITLE
Can't download uploaded file

### ISSUE THREAD

**Issue by alexandrebgagne** [RocketChat/Rocket.Chat.Electron#447]
## My Setup

 - Windows 10 and 7
 - 2.7 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Can't download a file that was uploaded. Clicking the file don't work and using the Attached file tabs don't work either. There is no error message in the log.

**Comment by alexbrazier** [comment]
@alexandrebgagne Could you provide more details on the types of file that this is happening with, and also check if this is an issue in the browser as well?

**Comment by alexandrebgagne** [comment]
@alexbrazier As far as I can see, every file types is doing that. I tried excel, jpeg, txt, csv. It works with the browser but my end users don't even know that there is a web interface.

**Comment by alexandrebgagne** [comment]
Fixed with last version
