### ISSUE TITLE
Text entered in the message box also appears in the top-left side of the window

### ISSUE THREAD

**Issue by UsmanArbisoft** [RocketChat/Rocket.Chat.Electron#448]
## My Setup
 - __My OS name and version__: macOS Sierra (10.12.2)
 - __My current app version__: 2.7.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

When you type a message in the message box, the text seems to reappear in the top-left side (in the sidebar), where the window control buttons (fullscreen/maximize, minimize, close) are located.
<img width="638" alt="rc-270-bug" src="https://cloud.githubusercontent.com/assets/6113194/26143609/208c7934-3aff-11e7-8916-109ce9b318a4.png">

#### Current Behavior

See description above.

#### Expected Behavior

The text being entered in the message box shouldn't appear anywhere else

**Comment by alexbrazier** [comment]
@UsmanArbisoft Could you confirm if this is an issue with the rocketchat desktop app, or if it happens in chrome or in another browser as well?

**Comment by UsmanArbisoft** [comment]
@alexbrazier I tried it on Safari 10.0.3 on the same computer, and the bug wasn't there. Seems like it's exclusive to the desktop app. Also, I logged this bug yesterday after updating from version 2.5.0. Let me know if you want me to test further.

Just found another bug in this version, guess I should start a new issue for it.

**Comment by alexbrazier** [comment]
Is this still an issue? I'm unable to reproduce it, and it doesn't seem like anyone else has mentioned it.

If its still broken then reopen
