### ISSUE TITLE
Disable update reminder

### ISSUE THREAD

**Issue by flauschi** [RocketChat/Rocket.Chat.Electron#449]
## My Setup

 - __My OS name and version__: Windows Server 2008 R2
 - __My current app version__: 2.7.0

- [ ] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

When I start the app, a window appears to remind me to install the new version of the client.
I have installed Rocket.Chat on a Terminal Server and every user is getting this reminder. But they don't have the permission to install updates. They are really confused. :-)

There should be a possibility to disable this reminder for all users on a certain workstation/server (By registry key or global config file (could be related to #139)?).

**Comment by karlis-vitols** [comment]
Additionally, it would be even better if there was an installation/registry switch to disable this centrally, not per each computer.

**Comment by skfin** [comment]
If you choose to skip the update, a json file is created in the user's appdata folder - if you push this file to all users with a script or group policy you can suppress the update check

**Comment by flauschi** [comment]
That is correct. This is a temporary workaround. But it only works until the next version is released (or I guess the future version numbers).

**Comment by alexbrazier** [comment]
@flauschi you can also disable permanently updates using the update file:

```
{
  "autoUpdate": false
}
```

I have also create a PR which will allow this file to be created in the install directory for all users.

**Comment by flauschi** [comment]
@alexbrazier Thanks, it works!

**Comment by johnyb0y** [comment]
@alexbrazier Thanks for your pr! Where do i need to put the file ? Inside the "resources" folder, like the servers.json ? Or in the root folder of rocketchat ?

**Comment by alexbrazier** [comment]
@johnyb0y you can either put the file in the app data directory (in the rocket chat folder) or in the install directory.

This is a runtime config, and is currently not built with the installer. This may change (see #523)

**Comment by johnyb0y** [comment]
Thank you. Yeah, i was talking about the "All Users" installation in %Program Files%\rocketchat+.
