### ISSUE TITLE
Remove legacy tray icon for GNOME

### ISSUE THREAD

**Issue by kwill** [RocketChat/Rocket.Chat.Electron#450]
## My Setup

 - __My OS name and version__: Ubuntu 17.04
 - __My current app version__: 2.7.0 (installed via Snappy)

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

* Start Rocket Chat desktop in GNOME

#### Current Behavior

* Icon appears in legacy icon tray

#### Expected Behavior

* No icon in the legacy tray.
* Still receive notifications through GNOME notifications. (This works.)
* ~~Closing the app with the X button should instead minimise it.~~

This is more in line with expected app behaviour on the GNOME desktop.

**Comment by kazens** [comment]
"Add option to hide tray icon" #343 did this, but only for mac.  I would like the ability to hide the tray icon for Linux as well.

Other chat programs only show a tray icon when there is an active notification.

**Comment by kwill** [comment]
Removed "Closing the app with the X button should instead minimise it." from the original description, because this is not expected behavior for a GNOME app. X always closes. The user can minimise in the usual way.

**Comment by kwill** [comment]
Other GNU/Linux shells still use legacy tray icons for notifications. You could make appearance of this icon optional/configurable.

**Comment by subjectdenied** [comment]
i'd like to inform you that legacy tray will be removed with gnome 3.26, i'm running gnome beta now, and electron apps starting in "tray" mode as pushbullet-for-desktop for an example now have no possibility to be displayed to the user. popular topicons-extension (moves icon inside the legacy tray to the panel area in the upper-right corner) also doesn't help here or works at the moment, as it is depending on the legacy tray functionality
