### ISSUE TITLE
Clicking on links does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat.Electron#454]
## My Setup

 - __My OS name and version__: Ubuntu 14.04
 - __My current app version__: 2.7.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description
On Ubuntu 14.04 links acts like they are normal text - they are only blue, but they are not clickable. I tested it on two machines with Ubuntu 14.04
On Windows 7 and Ubuntu 16.04 it works.

**Comment by WibbleNZ** [comment]
in Cent)S7 i get a link, and the preview of the webpage, and if i click the little gear a select copy I get the URL in my buffer , but actually clicking - left or right , does nothing .. when i run about it gives me a java error ..

**Comment by WibbleNZ** [comment]
[root@lap01-bdavis ~]# rpm -qa | grep -i rocket
rocketchat-desktop-2.7.0-1.x86_64

**Comment by localguru** [comment]
Same here with Rocket.Chat+ Version 2.8.0

**Comment by richardallred** [comment]
+1

**Comment by alexbrazier** [comment]
I can confirm that links don't work in 2.8.0, but they have now been fixed in the latest develop version (2.9.0-develop), so should be fixed in the next release

**Comment by phlegx** [comment]
I have the same problem.

**Comment by geekgonecrazy** [comment]
@monspid did you install the snap?

**Comment by monspid** [comment]
snap?
I tested it on a clean Ubuntu 14.04 too.

**Comment by alexbrazier** [comment]
@monspid Are you using the 2.8.0 release or the current development version, as they have been fixed in development, and should be released soon?

**Comment by geekgonecrazy** [comment]
> snap?

Yes just verifying you installed from download or via: `snap install rocketchat-desktop`. 

If installed via snap there is an issue where some platforms you have to install snapd-xdg-open

**Comment by alexbrazier** [comment]
Closing this as is was fixed in 2.9.0. If there is still an issue please reopen
