### ISSUE TITLE
servers.json and /allusers setup

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Electron#455]
Hi,

I'd like to deploy a /allusers setup on Windows. Is it possible to place a servers.json file as a kind of template globally, which is copied then to the user's folder?

"The servers.json file needs to be placed in the %APPDATA% folder for the User not the System wide one."

This is a problem in a /allusers setup. How could I copy the  servers.json file to the %APPDATA% folder if the program is started first time.

Ciao
Marcus

**Comment by alexbrazier** [comment]
@localguru Would the solution be to check the install location for a `servers.json` as well as the user dir?

**Comment by localguru** [comment]
@alexbrazier yes, loading a `servers.json` file in the install location would be perfect, if a user doesn't define a own `servers.json` file in %APPDATA% folder. If deploying rocket.chat client with /allusers, my deployment tool in a last step would copy a preconfigured `servers.json` into the global install location. So if a user starts the rocket.chat client the server URL is preconfigured to the own server.

**Comment by localguru** [comment]
Hi,

any idea why 
```
jetpack.cwd(remote.app.getAppPath());
```
in ```src/srcipts/server.js``` is not working?

Ciao!

**Comment by localguru** [comment]
see PR https://github.com/RocketChat/Rocket.Chat.Electron/pull/471
