### ISSUE TITLE
"Add users" list keep disappearing

### ISSUE THREAD

**Issue by TomasHofman** [RocketChat/Rocket.Chat.Electron#458]
## My Setup

 - Fedora 25
 - rocketchat-desktop 2.7.0-1 from RPM from your site

- [ ] I have tested with the latest application version
-> tested with latest available RPM
- [x] I can simulate the issue easily

## Description

When adding users to a private channel, when I write user name into "Add users" box, list of users appears, but then it disappears quickly (sometimes less then a second). It doesn't matter if I have mouse pointer on the list or not, or browsing through it via arrow keys.

This really makes adding users difficult.

Also happens in web client (tested with Firefox 53.0.2 and Chrome).

#### Current Behavior

List of users to add keeps disappearing.

#### Expected Behavior

List stays visible until I click and press [enter].

**Comment by alexbrazier** [comment]
@TomasHofman If it happens in the browser as well then it is an issue with the web app, rather than the electron app, so you are probably best reopening your issue there instead.

**Comment by alexbrazier** [comment]
Closing, as it's not an issue with the desktop app

**Comment by TomasHofman** [comment]
Thanks, I will reopen the original issue in Rocket.Chat repo.
