### ISSUE TITLE
webrtc not worky

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat.Electron#459]
## My Setup
 - MacOSX 10.12.5
 - 2.8.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

Hello Devs.

It seems WebRTC is not working in version 2.8.0. When i open a videocall i can see me but the person i try to connect to gets never connected. Is that a known issue? I tried Firefox and there it works as expected.

#### Expected Behavior

Working WebRTC.

thanks and cheers

**Comment by TriPhoenix** [comment]
Did you use the Mac App Store version or the download version? I haven't found enough to pinpoint it to a direct problem yet but in our deployment we noticed that the Jitsi video chat integration doesn't work properly in the MAS version either but seems to be fine in both browser and direct download versions.

**Comment by seancharlton** [comment]
What kind of WebRTC do you mean? Jitsi-Meet or the inbuild one?

If it's the inbuild one, check the dns settings to and from the rocketchat server. This was a small Problem I had.

If it's Jitsi-Meet on your own Server, be sure the ssl certs are accepted in your browser. After i switched to a valid SSL-Cert it worked flawless. ( Let's Encrypt or create a cert with your ca ). ( Try a Jitsi Meet Server with a Debian 9 Server + unstable ppa repo )

**Comment by himbeere** [comment]
It was about WebRTC not jitsi. Currently it works again so I guess the problem was in my side. Thanks for the answer though.

cheers
