### ISSUE TITLE
Desktop notifications?

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat.Electron#46]
Is this a planned feature? It would be great to get an OS X system notification with the person chatting and a preview of what they wrote.

**Comment by rodrigok** [comment]
It's already working

![captura de tela 2015-10-03 as 17 13 40](https://cloud.githubusercontent.com/assets/234261/10264925/2965644c-69f2-11e5-88aa-84d5ef2daf87.png)
