### ISSUE TITLE
Feature request: count badges on instruments channel sidebar

### ISSUE THREAD

**Issue by OrdinaryGuy** [RocketChat/Rocket.Chat.Electron#460]
I would love to have object count badges on instrument bar icons like:
- number of users online in selected channel
- number of starred messages here
- number of attachments
- number of pinned messages
Surely not all badges will really be useful and it may have sense to let user or admin decide which ones to have displayed.

**Comment by alexbrazier** [comment]
@OrdinaryGuy Please could you reopen this request on the main Rocket.Chat app, as this is a feature that will be implemented there, rather than just for the desktop app.
https://github.com/RocketChat/Rocket.Chat
