### ISSUE TITLE
Attachemnt in format '*.patch' are changed to '*.patch.bin' during download.

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat.Electron#461]
## My Setup

 - __My OS name and version__: Windows 7
 - __My current app version__: 2.8

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description
Attachments, which are ended with `.patch` during download change to `.patch.bin`

**Comment by alexbrazier** [comment]
I'm unable to recreate this. Is it just any file renamed to *.patch that doesn't download?
I've tested this and it seems to be working.
I'm closing this issue for now, but can you reopen it if it's still a problem. - It could have/still be a problem with the rc app, and not electron
