### ISSUE TITLE
About Rocket.Chat+ causes JavaScript error

### ISSUE THREAD

**Issue by mscfadmin** [RocketChat/Rocket.Chat.Electron#462]
## My Setup
 - __My OS name and version__:  Windows 10
 - __My current app version__: 2.7

- [X] I have tested with the latest application version
- [X] I can simulate the issue easily

## Description

Just installed version 2.7 on my Surface Pro 4 running Windows 10 with the latest updates. When clicking Rocket.Chat+ > About Rocket.Chat+ in the toolbar, I get a JavaScript error:

![capture](https://cloud.githubusercontent.com/assets/29168172/26757431/85f58ce6-4880-11e7-894e-bbf0c9471cf2.PNG)

#### Expected Behavior

Should show the current version, etc.

**Comment by alexbrazier** [comment]
This error was fixed in 2.8.0 by #440
