### ISSUE TITLE
Restoring by clicking the notification tray icon does not respect maximized window state

### ISSUE THREAD

**Issue by admsteck** [RocketChat/Rocket.Chat.Electron#469]
## My Setup
- Operating System: Windows 7 Enterprise
- App Version: 2.8.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
Clicking on the icon in the notification tray restores the RocketChat client to a windowed (non-maximized) state no matter what the state was when it was minimized.

### Expected Behavior
If the client was maximized, then minimized, clicking the notification tray icon should restore the application maximized.

**Comment by admsteck** [comment]
After a little more experimenting, I don't think the app is saving it's current window state when the windows state is changed via the OS features (clicking the icon on the taskbar to minimize, or minimize with the button at the top right of the window).  

Using the hide and show options on the notification icon context menu works correctly.

**Comment by gdelavald** [comment]
I'll mark this as enhancement since I don't think this is a breaking bug, but closer to a quality of life type of change.

**Comment by alexbrazier** [comment]
Fixed by #512
