### ISSUE TITLE
Refreshing sends user back to home page

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat.Electron#47]
It would be nice if refreshing kept the user on that page instead of sending them back to the home page.

**Comment by Bekt** [comment]
I don't think there's any obvious way to get around this since an `iframe` is being used to show the app. This would go away automatically if the instance URL is loaded with `loadUrl` directly on the main window.

**Comment by geekgonecrazy** [comment]
@mhkeller @Bekt we are working to switch this to webview's that will allow you to switch between servers with out loosing your place.

Some beta code is in the webview's branch :)

**Comment by Bekt** [comment]
Oh nice thanks, I've been trying to figure this out as well. I'll look into the code.

**Comment by geekgonecrazy** [comment]
@bekt it works, I use it daily.  But it is a bit buggy so for sure want to get it ironed out a bit

**Comment by Bekt** [comment]
@geekgonecrazy, that doesn't solve the problem this issue describes though.

1. Go to some view (#general, for example)
2. Hit `cmd+r`

Expected behavior is that I want #general (or whatever the view I was on before refresh) to be loaded on page refresh. Currently the root URL shows on every refresh.

**Comment by geekgonecrazy** [comment]
@Bekt I believe a refresh refreshes the entire view the application is in.  So it would reset everything.  We probably need to intercept cmd+r and direct it to reload the frame.

**Comment by Bekt** [comment]
Hm. What do you think about listening to either `did-start-loading` or `did-frame-finish-load` on the webview and saving the new src URL in localStorage?

**Comment by rodrigok** [comment]
Version 1.0.0 has this feature
