### ISSUE TITLE
How to reset rocket.chat to default settings?

### ISSUE THREAD

**Issue by ssjbrady** [RocketChat/Rocket.Chat.Electron#473]
Your Rocket.Chat app version: 2.6.1
Your Rocket.Chat server version: 0.56
Device (or Simulator) you're running with: Mac OS X 10.10.5

Hey, I was wondering if there was a way to reset rocket.chat to the default settings in Mac OS?
I have tried uninstalling it and reinstalling it but that just keeps the old settings.

Thanks

**Comment by localguru** [comment]
Yes, interesting question. All settings are stored in mongo. Remove rocketchat db to start from fresh. If that isn't an option, I guess there is no solution for that at the moment, unless you reset all changes by hand via administration interface.

**Comment by ssjbrady** [comment]
Is there anyway to change the default settings in version 2.8 of the RocketChat client on a Mac OS X.

**Comment by localguru** [comment]
Which default settings do you want to change?

**Comment by ssjbrady** [comment]
We want to do a "factory reset" as our client is missing the area to type.

**Comment by ssjbrady** [comment]
When the user goes into locked mode the area to type becomes unreachable.

**Comment by gallamor** [comment]
I am also having the same issue. Sierra 10.12.5, Rocket Chat 2.8.0.

There appears to be a bug between window resizing and text resizing. It exhibited when I hit Command-+ to increase the size of text. After this point, the window size and the data in the window panes are disassociated, and you are unable to see the chat box unless you shrink the window to the smallest size allowed at that text size. Even with this, half the chat  box is below the window and not visible.
<img width="827" alt="screen shot 2017-07-28 at 11 18 40" src="https://user-images.githubusercontent.com/30523330/28711073-8fe57cda-7386-11e7-9abe-2bc169fe0c4e.png">

**Comment by gallamor** [comment]
Being able to return to installed defaults would resolve the issue, but it's a bit less than obvious where settings for Rocket Chat are stored. I've uninstalled, removed all references to Rocket Chat and chat.rocket in the Library; but the local settings persist upon reinstall (including knowing the server I attach to). 

So, there is a settings or preferences file that is somewhere in /Library or ~/Library that I have yet to find. I believe that it is this file that is mildly corrupted. Any help in identifying this file would be very welcome- this bug is REALLY irritating. :)

**Comment by gallamor** [comment]
So, my resolution was as follows:
Open a Finder window on ~/Library
Search for 'rocket'
Delete the following directories:
~/Library/Application Scripts/chat.rocket/
~/Library/Containers/chat.rocket/
/Library/Containers/chat.rocket/Data/Library/Application Support/Rocket.Chat+/
~/Library/Group Containers/[uniqueID].chat.rocket/

This seems to have reset the windowing back to being able to see everything.

**Comment by alexbrazier** [comment]
This duplicates #60
