### ISSUE TITLE
Desktop notifications not appearing on Windows 10

### ISSUE THREAD

**Issue by cameron314** [RocketChat/Rocket.Chat.Electron#474]
I have desktop notifications enabled, but they do not appear. The 'Test Desktop Notifications' button does not do anything for me (though it works for my co-workers with a similar set-up). I have tried rebooting, upgraded from 2.7 to 2.8, using only a single monitor, and using only one virtual desktop, all to no avail. The only visual indication of new messages is that the tray icon changes colour.

OS: Windows 10 x64
Rocket.Chat client: 2.8.0 (latest release from GitHub as of writing)

Anything I could do to help debug this?

**Comment by alexbrazier** [comment]
@cameron314 Is it possible that you disabled notifications on Windows 10 either for all apps, or for Rocket.Chat?

Are there any other cases of it not working?

**Comment by cameron314** [comment]
Hmm, didn't know this could be enabled/disabled per app. In any case, they seem to be enabled:

![image](https://user-images.githubusercontent.com/116235/28126218-db01ed26-66f6-11e7-8f7c-9d68368dba87.png)

**Comment by cameron314** [comment]
For what it's worth, I don't think this is specific to RocketChat anymore. I upgraded to Office 2013 and I don't receive notifications from Outlook either.

**Comment by gdelavald** [comment]
@cameron314 Interesting... any way we'll keep investigating the issue. Thanks for the feedback.

**Comment by cameron314** [comment]
AHA! I had somehow enabled 'Quiet Hours' in the Action Center. This was nearly impossible to find since you have to a) know that the Action Center is responsible for showing the notification banner thingies, and b) I had hidden the Action Center icon thinking it was useless, so this setting was out of sight.

**Comment by ankar84** [comment]
> AHA! I had somehow enabled 'Quiet Hours' in the Action Center. This was nearly impossible to find since you have to a) know that the Action Center is responsible for showing the notification banner thingies, and b) I had hidden the Action Center icon thinking it was useless, so this setting was out of sight.

Had the same problem on one of user computers. **Quiet Hours** was enabled, but **Action Center** was disabled by Group Policy.
In modern Windows 10 MS changed it to **Focus assist** and user do not need **Action Center** to manage this.

**Comment by sarathkurup87** [comment]
![image](https://user-images.githubusercontent.com/5821676/128994217-349497fb-2da7-47f5-a648-deb6eb84c200.png)
