### ISSUE TITLE
npm install fails while configuring rocket chat electron codebase

### ISSUE THREAD

**Issue by dan-chris** [RocketChat/Rocket.Chat.Electron#475]
Rocket.Chat Version: 2.8.0(Electron)
Running Instances: Windows 8.1
DB Replicaset OpLog:
Node Version: v6.9.2

I am trying to setup the rocketchat electron latest codebase (master branch) in visual studio. I have successfully checked out the code. Then I opened the command prompt and navigated to the code base and executed the "npm install" command. I am getting the following the error:

C:\Users\dan_chris\Documents\Git\Dev\Rocket-Chat\Rocket.Chat.Electron\node_modules\spellchecker

node-gyp rebuild
C:\Users\dan_chris\Documents\Git\Dev\Rocket-Chat\Rocket.Chat.Electron\node_modules\spellchecker>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "node C:\Users\dan_chris\AppData
\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) module.js:471
throw err;
^

Error: Cannot find module 'C:\Users\dan_chris\Documents\Git\Dev\Rocket-Chat\Rocket.Chat.Electron\node_modules\spellchecker\node C:\Users\dan_chris\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:509:3
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spellchecker@3.4.1 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spellchecker@3.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\dan_chris\AppData\Roaming\npm-cache_logs\2017-06-30T06_51_20_440Z-debug.log`

Seems the spell checker dependency is creating this error. Please advise me how to resolve this

**Comment by alexbrazier** [comment]
@dan-chris Have you installed node-gyp correctly, following these instructions? https://github.com/nodejs/node-gyp#installation
