### ISSUE TITLE
In windows 8.1: npm install asks the binding.gyp and .vcxproj file

### ISSUE THREAD

**Issue by dan-chris** [RocketChat/Rocket.Chat.Electron#476]
- Operating System: MS Windows 8.1 
- App Version: 2.8.0
-Code branch: master

while running the npm install command, it asks the binding.gyp/.vcxproj file. However I am unable to see this file these files in our codebase. Can someone tell me where this file is present in code base. Please share your thoughts

**Comment by alexbrazier** [comment]
I think these files come with visual studio build tool. Also, we've had more luck using yarn over npm.
If it's still not working try following the install instructions for windows in the readme, and if that doesn't work, reopen this issue
