### ISSUE TITLE
Links in chat opens blank page

### ISSUE THREAD

**Issue by mchvila** [RocketChat/Rocket.Chat.Electron#479]
## My Setup
- Operating System: Windows 10
- App Version: 2.8.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

There is a problem with opening links that have same URL as our Rocketchat server.
Example: 
- Rocketchat server runs on https://abc.def.de/
- I want to open https://abc.def.de/page1.html

Clicking on those links in chat won't open them in browser but opens blank page covering the chat window. 

### Current Behavior
Clicking on problematic link opens blank page covering chat.

### Expected Behavior
Open link in browser as usual.

**Comment by gdelavald** [comment]
This happens because `page1.html` is considered a channel, this is reproducible on the web as well so please file an issue on the [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) repo.
