### ISSUE TITLE
Spotify embeds try to open a new Electron window

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat.Electron#48]
The error says `Invalid csrf token`. Sometimes this window can be closed and, other times it pops up again after being closed. Even tho the timer is counting, no music is being played. 

![spotify](https://cloud.githubusercontent.com/assets/498744/10290664/7086acc8-6b73-11e5-9740-7d6c79d2c164.gif)

**Comment by graywolf336** [comment]
Fixed by #73.

**Comment by mhkeller** [comment]
@graywolf336 See https://github.com/RocketChat/Rocket.Chat.Electron/pull/73#issuecomment-173750598 as to why opening up a new window is not technically the desired behavior.
