### ISSUE TITLE
servers.json file not compiled with the exe

### ISSUE THREAD

**Issue by JohnnyKing94** [RocketChat/Rocket.Chat.Electron#480]
## My Setup
- Operating System: Windows 10
- App Version: 2.9.0-develop, git source
- Nove Version: 8.1.3
- NPM Version: 5.1.0

- [X] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I'm trying to attach the `servers.json` file to the compiled `.exe`. According to docs, i need to attach the file in `%APPDATA%/Rocket.Chat+/servers.json`. As i changed the name of the app, i tried first with `%APPDATA%/<app-name>/servers.json` and then with `%APPDATA%/<app-name (development)/servers.json`, but none of these seem to be working. So I even tried to use the default path used in the doc `%APPDATA%/Rocket.Chat+/servers.json`. Nothing! When i install the app, i do not have any `servers.json` extracted there. Am I missing something?

**Comment by alexbrazier** [comment]
@JohnnyKing94 How are you adding it to the exe?

Maybe it will be easier once #471 is merged?

**Comment by JohnnyKing94** [comment]
As stated in the description of the issue... i add the json file in the path (tried all those path above) and then i run `npm run release`... when i try to install it with a fresh setup, no servers.json is extracted.

**Comment by alexbrazier** [comment]
Ah, the servers.json wont be compiled with the installer. For it to work you have to install the app then before manually adding any servers you need to copy the servers.json file into the appdata location. This could be done with one of the Windows group policy install tools.


If you want to have it compiled with the exe you could try copying it in `build/win/installer.nsh`, or just hardcoding the default servers in `src/scripts/servers.js`.

**Comment by JohnnyKing94** [comment]
Need to extend/change the docs, cause it's not quite clear what it's explained. In this way ppl won't get confused when reading it.
