### ISSUE TITLE
Upload Dialogue Auto Scaling Box Size Not Workingin RC Desktop Client for Linux 2.8.0 AMD64

### ISSUE THREAD

**Issue by ml48603** [RocketChat/Rocket.Chat.Electron#482]
Upload Dialogue Auto Scaling Box Size Not Working in RC Desktop Client for Linux 2.8.0 AMD64.  The Application Window must be expanded to see the complete dialogue box

Auto Sizing was working in v2.7.0

![image](https://user-images.githubusercontent.com/17936105/28177775-eb9180a6-67c9-11e7-9437-026a634ceaf0.png)

**Comment by alexbrazier** [comment]
@ml48603 could you check if this happens if you open it in the browser, as this sounds like an issue with the main server rather than the desktop app?

**Comment by gdelavald** [comment]
I think web had a fix for this merged for 0.57 or 0.58.
See https://github.com/RocketChat/Rocket.Chat/issues/7369

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
