### ISSUE TITLE
Localization of Rocket.Chat.Electron

### ISSUE THREAD

**Issue by JohnnyKing94** [RocketChat/Rocket.Chat.Electron#483]
I noticed that every string in the application is hard-injected with the code and doesn't allow any way to localize in multiple languages the app. I propose to split in a localization file all the language strings. In this way you can install the app according to system language or edit manually.

**Comment by gdelavald** [comment]
Hey @JohnnyKing94, most of the strings that are used come directly from the web version, which has localization for all it's content, however, you are correct in mentioning that any string that is specifically from the Electron App is hardcoded. I think adding localization would be a big factor in making the app more universally adopted.
We also encourage anyone to work on this and open a PR so we can discuss this further.
