### ISSUE TITLE
Android app does not work with secp384r1 curve preferred by server

### ISSUE THREAD

**Issue by Majkl578** [RocketChat/Rocket.Chat.Electron#485]
## My Setup
- Operating System: Android 7.0
- App Version: 1.0.16
- NGINX as reverse TLS-terminating proxy

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

1) install Rocket.Chat on the server
2) install NGINX
3) configure NGINX reverse proxy for Rocket.Chat
4) obtain and configure ECDSA certificate for the server (i.e. from Let's Encrypt or try hack with signed)
5) configure preferred ECDSA cipher and prefer secp384r1 curve
6) start NGINX

### Relevant configuration should look like this

in http {}:
```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_stapling on;
ssl_stapling_verify on;
ssl_session_cache builtin:1000 shared:SSL:10m;
ssl_dhparam ssl/dhparams.pem;
ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH EDH+aRSA !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !RC4";
ssl_ecdh_curve secp384r1;

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' '';
}
```
in server {}:
```
location / {
    proxy_pass http://127.0.0.1:3000/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forward-For $remote_addr; #$proxy_add_x_forwarded_for;
    proxy_set_header X-Forward-Proto $scheme;
    proxy_set_header X-Nginx-Proxy true;
    proxy_redirect off;
}
```

This will make NGINX prefer ECDSA over RSA (as long as you have ECDSA certificate of course). Let's Encrypt supports both ECDSA and RSA and NGINX allows multi-use, so both could be used in parallel and legacy clients should fall back to RSA.

The `ssl_ecdh_curve` will make NGINX use secp384r1 curve for handshake. This will make Rocket.Chat+ fail hard, completely break connection to the server. Note that using prime256v1 curve works fine.

### Current Behavior
Error: _There's a connection error. Please try later._

### Expected Behavior
No error, successful connection. Fallback to RSA if curve is not supported.

**Comment by gdelavald** [comment]
Hey @Majkl578, this looks like a support issue rather than a bug, so could you please check on the #support channel inside our [open chat](https://demo.rocket.chat)? If you feel this is a bug, please open this issue on the [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) repository as this doesn't look related to the Electron app.

**Comment by geekgonecrazy** [comment]
Related: [msg](https://demo.rocket.chat/channel/support?msg=6xxwtg8c4tjwfsTAS)
Please follow up here: https://github.com/RocketChat/Rocket.Chat.Android
