### ISSUE TITLE
RocketChat Electron 2.9.0 slow switching channels with CPU at 100%

### ISSUE THREAD

**Issue by monty241** [RocketChat/Rocket.Chat.Electron#486]
## My Setup
- Operating System: Windows 10 Enterprise
- App Version: 2.8.0 and 2.9.0
- Hardware: Dell Precision 7510 Xeon(R) CPU E3-1535 v5 @ 2.9 GHZ, 32 GB memory.

- [X] I have tested with the latest version -> There is no new version.
- [X] I can simulate the issue easily

## Description
When I switch to RocketChat client or switchbetween channels, it can takes upto 1 minute of 1 core 100% active to become reactive. It seems to only download new messages when in the front. Once became active again, switch back/forth with other windows application, normally responds within 2 seconds.

Estimated daily volume of messages: 1.000 - 2.500. Number of users: 10. Total volume: 376K messages.

Problem also occurs on other devices, running Windows 7, Windows 10, Windows 2008R2. There seems to be little to no load on the private server running RocketChat (no CPU load, no waiting I/O).

### Expected Behavior
On the same device Slack and rocketchat through website was responsive to the user within 1 second.

**Comment by monty241** [comment]
Updated situation with 376K messages in store, close to 0% CPU and waiting I/O on linux server.

Problem also appears switching channels.

Switching between channels in web browser is instantly.
Switching between channels in RocketChat 2.9.0 client takes 35 seconds with 100% load on one core. Memory consumption of rocket chat electron client is approximately 1 GB.

**Comment by gdelavald** [comment]
Thanks for the detailed information, we'll start looking into performance problems for next release.

**Comment by herrlado** [comment]
Have the similar problems with rocket chat client on linux  (Same machine).

**Comment by hupptechnologies** [comment]
We have the same issue with Windows.

**Comment by tassoevan** [comment]
@hupptechnologies Which server version?

**Comment by neonardo1** [comment]
+1

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
