### ISSUE TITLE
Blink tray icon on notification

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#487]
This comes over as a request from main repo, but specific for desktop client:
https://github.com/RocketChat/Rocket.Chat/issues/4461

**Comment by chrisaudet** [comment]
+1 for this.

I've been training employees to keep the window minimized as a workaround, but having the tray icon blink even if the RocketChat window is closed out would be a better solution.

**Comment by LXSysadmin** [comment]
+1

**Comment by zipper2110** [comment]
+1

**Comment by kkachura** [comment]
+1

**Comment by AlexDRiVER** [comment]
+1

**Comment by djm266** [comment]
+1

**Comment by 77cc33** [comment]
+ 1 guys, it's very useful feature

**Comment by blodone** [comment]
+1 + the ability to toggle blinking and re-notify intervals

**Comment by jcatarino** [comment]
+1 needed its very useful

**Comment by jparcell** [comment]
Anything to make that icon more visible. If a user is not looking at the screen for the three seconds when a notification appears then all they get is a very tiny red circle on the task tray icon. Completely unnoticeable. Rocketchat is not used much here because users don't notice that they have messages.

**Comment by homberger** [comment]
Any progress on this?

**Comment by blodone** [comment]
also it would be nice if you receive an "incoming call" like a jitsi conference it would be nice to notify the user to respond quickly

**Comment by baiking** [comment]
+1 this is the must have feature

**Comment by baiking** [comment]
This is a very important feature that is missing now

**Comment by MrPoint1400** [comment]
+1

**Comment by henit-chobisa** [comment]
We have already added features for enabling `flash frame` on Windows and `dock bounce` in OSX, for now I think that there is no feature in any of the OS like blink tray icon, but surely if this feature releases in later versions of any of the OSs, we would definitely work on it.

Please consider closing the issue.
Thank You 😊

**Comment by jeanfbrito** [comment]
Hello, we will be tracking the blinking icon feature request here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2525
I will be closing this issue because there are duplicated ones.
