### ISSUE TITLE
Notifications workspace corrupted

### ISSUE THREAD

**Issue by gueeme** [RocketChat/Rocket.Chat.Electron#492]
## My Setup
- Operating System:
Nome do host:                              CR0013135_00
Nome do sistema operacional:               Microsoft Windows 7 Professional
Versão do sistema operacional:             6.1.7601 Service Pack 1 compilação 7601
Fabricante do sistema operacional:         Microsoft Corporation
Data da instalação original:               05/07/2017, 12:14:50
Tempo de Inicialização do Sistema:         01/08/2017, 08:34:18
Fabricante do sistema:                     Hewlett-Packard
Modelo do sistema:                         HP Compaq 8100 Elite SFF Brazil PC
Tipo de sistema:                           x64-based PC
Processador(es):                           1 processador(es) instalado(s).
                                           [01]: Intel64 Family 6 Model 37 Stepping 5 GenuineIntel ~3333 Mhz
Versão do BIOS:                            Hewlett-Packard 786H1 v01.13, 14/07/2011
Localidade do sistema:                     en-us;Inglês (Estados Unidos)
Localidade de entrada:                     pt-br;Português (Brasil)
Fuso horário:                              (UTC-03:00) Brasília
Memória física total:                      3.895 MB
Memória física disponível:                 1.844 MB
Memória Virtual: Tamanho Máximo:           7.789 MB
Memória Virtual: Disponível:               5.151 MB
Memória Virtual: Em Uso:                   2.638 MB

- App Version: 2.8.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![2017-08-01 09_05_06-rocket chat](https://user-images.githubusercontent.com/19538568/28825808-1cd7de34-769e-11e7-8e97-bb3d51dc2854.png)

### Current Behavior

Desktop notifications should display the complete information with a preview of the message.

### Expected Behavior

Often notifications do not display anything, just a blank box with no messages.

**Comment by gdelavald** [comment]
Hey @gueeme, can you check if this is not the same issue that happens in #491 ? On that issue, the problem seem to happen because of a Windows theme. Please let me know what you find.

**Comment by gueeme** [comment]
That other issue was me that I opened too.
I thought it was the theme, I changed it in one of the stations that was in trouble and for a short period did not present the problem anymore.
Today it happened again with the settings adjusted to get the best look.

**Comment by alexbrazier** [comment]
@gueeme Does this happen for all messages or just some? How often?

Is there anything different about the messages being sent? (e.g. special chars, size, an image)

**Comment by gueeme** [comment]
@alexbrazier 
They are not all messages and do not have a frequency.
These are plain text messages with no special characters. We almost do not send pictures.
