### ISSUE TITLE
Tray icon still not showing there is an unread message

### ISSUE THREAD

**Issue by dark-penguin** [RocketChat/Rocket.Chat.Electron#493]
## My Setup
- Operating System: Debian Jessie x64
- App Version: 2.8.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
The tray icon is always gray, it does not turn red, and does not indicate there is an unread message.

### Expected Behavior
The tray icon in supposed to be not gray, but blue (? I don't remember which color exactly) or red with an unread message notification.

#329 was just closed, but the problem is not fixed, so I'm creating a new one.
We could not deduce what is the source of the problem; I've seen it working on Ubuntu Yakkety with Xfce and Windows 7, but I've never seen it working on Debian Jessie with MATE. Some people report it not working on Ubuntu Xenial and Fedora 25, and I have once seen it stop working on a Windows machine where is usually worked (I think a reboot helped that).

In #329, someone suggested it may be a problem with Rocket.Chat server and not the desktop app. I have upgraded my Rocket.Chat server (in a Docker container) to the current version (0.57.2), and it still did not help.

**Comment by zipper2110** [comment]
works fine on my setup

**Comment by vcapretz** [comment]
hey @dark-penguin are you still having trouble with it? I've been using RC Electron for a while and I didn't have problems with the alerts. 

When I have some direct message it shows a red tray icon with the messages count.
When there are messages on public channels it's green, and with no messages it's gray 

(I'm using Ubuntu and RC Electron v2.9.0)

**Comment by dark-penguin** [comment]
For me, it works fine on Ubuntu, but I've never seen it work on Debian Jessie. And I have multiple boxes running Debian Jessie. All of them just show the gray icon (which looks kinda bad on the default gray MATE theme).

**Comment by vcapretz** [comment]
hey @dark-penguin, I was looking for possible causes and I saw that some users reported issues with the tray icon on electron (on Debian Jessie), but their problem was that the tray icon was not visible at all. 

On your case the tray icon does appear, but only the notifications are not working, right? 

Can you please check your user preferences this setting? 

![image](https://user-images.githubusercontent.com/14620121/30751767-a8c6b918-9f90-11e7-9cea-d254612675da.png)

**Comment by dark-penguin** [comment]
Okay, now this is fixed (in 2.9.0, at least build 538). Thank you!
