### ISSUE TITLE
Missing Services menu in application menu on macOS

### ISSUE THREAD

**Issue by phidlipus** [RocketChat/Rocket.Chat.Electron#496]
## My Setup
- Operating System: macOS Sierra 10.12.6
- App Version: 2.8.0

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description
I use "Services" for some predefined actions.

Missing Services menu in Rocket.Chat+ application menu:
![rocketchat](https://user-images.githubusercontent.com/2934244/28907612-4f7270c0-781f-11e7-988f-282b78f662fc.png)

How it looks correctly for example in Finder:
![finder](https://user-images.githubusercontent.com/2934244/28907686-b89dac22-781f-11e7-9cad-26f266a6db22.png)

### Current Behavior
I can't run my predefined action while the Rocket.Chat+ application is in the foreground.

### Expected Behavior
It should be there, so I can use the Services like in any other application.

**Comment by tomasgatial** [comment]
+1 I would appreciate this to be added. Its kind of a OSX standard, even Slack supports services.
