### ISSUE TITLE
3+ lines messages are not visible

### ISSUE THREAD

**Issue by jjetrifork** [RocketChat/Rocket.Chat.Electron#497]
## My Setup
- Operating System: MacOS 10.12.6
- App Version: 2.8.0 (from appstore)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Writing long messages or messages that span 3+ lines in length is a problem and remains out of view and cannot be scrolled to.

Writing 4 lines:
<img width="780" alt="screen shot 2017-08-07 at 19 41 02" src="https://user-images.githubusercontent.com/25224830/29039048-0e9fafac-7baa-11e7-81f5-8b2cfdabd727.png">

Writing about 8 lines (I cannot see them :)):
<img width="774" alt="screen shot 2017-08-07 at 19 43 04" src="https://user-images.githubusercontent.com/25224830/29039057-1208feaa-7baa-11e7-9387-7690489e81cb.png">

### Current Behavior
Only the first 3 (point something) lines are visible in the writable area.

### Expected Behavior
I would expect the lines around the cursor to remain visible while writing and to be able to scroll in the writable area.

**Comment by gdelavald** [comment]
I noticed this today, but since this is a problem with the web version as well I would recommend opening a ticket over [there](https://github.com/RocketChat/Rocket.Chat/issues). This is also already fixed in our redesign branch, so this should getting closed in a few days.

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
