### ISSUE TITLE
O projeto não sobe no windows

### ISSUE THREAD

**Issue by nicolasdezena** [RocketChat/Rocket.Chat.Electron#501]
## My Setup
- Operating System: Windows 10
- App Version: 2.9.0-develop

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description
Não consigo subir o projeto, ja fiz de tudo e o erro que me da é esse:

![captura de tela 2017-08-10 as 12 01 18](https://user-images.githubusercontent.com/14208388/29176930-b82b5916-7dc3-11e7-913c-f772b9a24de1.png)

Saberiam me ajudar?

**Comment by gdelavald** [comment]
@nicolasdezena Oi, pelo visto o problema é com o `node-gyp`, você tentou instalar o [window-build-tools](https://www.npmjs.com/package/windows-build-tools)?

**Comment by nicolasdezena** [comment]
@gdelavald sim mei amigo, ja fiz tudo isso. De qualquer forma resolvi já jogando dentro de um electron novo, com uma simples tag html(webview).

Obrigado

**Comment by gdelavald** [comment]
Certo, se foi resolvido vou fechar a issue. Obrigado.
