### ISSUE TITLE
File menu disappears on window change

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#502]
## My Setup
- Operating System: Fedora 25 Gnome
- App Version: Latest

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

https://giphy.com/gifs/26n6FNMKUkMfPhkVq

### Current Behavior

Switching windows causes app menu to disappear

### Expected Behavior

It shouldn't go away

Just extra notes.. this doesn't seem to be happening on Fedora 26 I'm not sure why it is happening on Fedora 25.  Maybe the version of Gnome?

**Comment by alexbrazier** [comment]
@geekgonecrazy Are you able to check if this occurs when you click View -> Toggle Menu Bar?

I think the issue may be that the menu bar should also be hidden at startup when it has been hidden with the above setting.

**Comment by geekgonecrazy** [comment]
@alexbrazier this sounds very plausable.  Passing on to original bug reporter.

**Comment by jeanfbrito** [comment]
This is very old and seems to be resolved, I will close this issue then, ok?
