### ISSUE TITLE
ScreenSharing doesn't work in popup Jitsi mode

### ISSUE THREAD

**Issue by jaboko** [RocketChat/Rocket.Chat.Electron#504]
## My Setup
- Operating System: Mac OS 10.11.6
- App Version: 2.9.0-develop

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![image](https://user-images.githubusercontent.com/8984221/29248850-f18b7542-802a-11e7-8c0e-a16256905610.png)

### Current Behavior

The window should show a list of possible windows for sharing.

### Expected Behavior

The list of windows for sharing is not displayed.

**Comment by jasonfah** [comment]
Having the same issue with the Windows client. I recall having a popup prompting to install the plugin. After that - nothing. Same as screenshot above.

V2.8.0

**Comment by chrisgns** [comment]
This issue is also discussed in the Rocket.Chat queue, I think using the PR should help a lot of us

https://github.com/RocketChat/Rocket.Chat/issues/9099
