### ISSUE TITLE
Sending multiple files leads to duplicates and omissions

### ISSUE THREAD

**Issue by schoellpat** [RocketChat/Rocket.Chat.Electron#511]
## My Setup
- Operating System: Ubuntu 16.04
- App Version: 2.8.0

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

When dragging multiple files at once into a chat window, a dialog pops up for every file to be sent. After just confirming every window, the right number of files is sent, but some files are sent two times, while others are omitted.

### Current Behavior
When sending e.g. the files 1.txt, 2.txt, 3.txt, ... 9.txt the file 1.txt appears two times in the chat window (also with the content associated with 1.txt), but 9.txt is missing. The popups for the name correctly show all files. It seems that the first file is sent twice while the last is omitted.

### Expected Behavior
All files should be sent correctly.

**Comment by gdelavald** [comment]
@schoellpat Hey, could you please test this on the Web Version as well? Since this could be a bug on RC and not the electron app directly. Thank you.
