### ISSUE TITLE
Sidebar styling

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat.Electron#513]
## Description
The current sidebar is quite wide and the buttons doesn't quite fit correctly in there.
![image](https://user-images.githubusercontent.com/6303966/29433818-183461be-8377-11e7-80bb-ca752536362a.png)

Also, the background color is fixed and with the updated layout it doesn't fit at all (what probably happens to everyone who changes the RC color scheme)
![image](https://user-images.githubusercontent.com/6303966/29433959-94898e24-8377-11e7-8138-4c754cfbd37f.png)

### Proposed
We should make it thinner and have a dynamic background according to the primary background color of the webview.

**Comment by HLFH** [comment]
![rocketchat-win](https://user-images.githubusercontent.com/2359059/29537504-e92ccd02-86b9-11e7-93aa-52ab5bed536a.png)

This is what I have on Windows 10, using 2.8.0.

**Comment by gdelavald** [comment]
@HLFH yeah that is supposed to be the hotkey for selecting the server, doesn't make much sense alone...

**Comment by vcapretz** [comment]
hey @gdelavald I reduced the sidebar width in 20%, it's much better, what do you think? 

**Before:**
![before](https://user-images.githubusercontent.com/14620121/30172323-ec6c4ae2-93ca-11e7-9e14-712c8582eec1.png)

**After:**
![after](https://user-images.githubusercontent.com/14620121/30172334-f3b6becc-93ca-11e7-8184-acee8391c848.png)

now I'm going to work on the background color

**Comment by vcapretz** [comment]
for the background color I got the variables from Rocket.Chat server, I used the darker one on the sidebar so it is not equal to the webview color, as you can see here:

![sidebar_closed](https://user-images.githubusercontent.com/14620121/30173418-f4f41282-93cd-11e7-9e2d-bddda2943da1.png)

![sidebar_open](https://user-images.githubusercontent.com/14620121/30173420-f89cf192-93cd-11e7-95ac-419affbaba51.png)
