### ISSUE TITLE
[Feature] Pre/Post-Release Configuration for Auto Update Check

### ISSUE THREAD

**Issue by TheSharpieOne** [RocketChat/Rocket.Chat.Electron#523]
It would be nice to have a way to disable automatic update checks. Why? In an enterprise environment more control over versions and updates are needed (and all settings in general). Some testing needs to be done to ensure the validity of the updates as well as to ensure users have the same version. Also, if things are sufficiently locked down, the app may not actually be able to update itself (due to lack of permissions for the user). This last thing causes a bad experience when attempting to auto update where it would be best to not prompt the user to update.
I propose there be a config file, similar to the servers.json, which can control things. Specifically the ability to toggle the ability to automatically check for updates.

I found (undocumented) a `update.json` file which is where the user's update settings are stored (from the "about" window's checkbox), and a temporary workaround is to default it to `false`, but users can still enable it. It would be nice to able to disable the feature completely.

**Comment by johnyb0y** [comment]
Yes, beeing able to use the "update.json" like the "servers.json" to force some basic rollout configuration would be great.

**Comment by gdelavald** [comment]
Thanks for the suggestion, unifying deploy and client configuration for mass users is something we are looking into implementing in the next release(s).

**Comment by johnyb0y** [comment]
For example Firefox has a great implementation of this feature. 
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Enterprise_deployment

You can decide whether a certain setting is forced and not changeable or just preset in a certain way.
