### ISSUE TITLE
Allow Multiple Instances of Electron App

### ISSUE THREAD

**Issue by arnonuem** [RocketChat/Rocket.Chat.Electron#527]
I want to suggest to allow multiple instances of the same app.

Background:
I am on Windows 10 and i have 4 virtual desktops. I also have multiple monitors. I want to permantently see a rocket chat client instance on a specific monitor when switching virtual desktop. I Could use the browser window as workaround but i want to use the electron app.

Could you please investigate whether it is just an electron property which has to be switched on?
Please make this possible ;)

**Comment by alexbrazier** [comment]
@arnonuem Is this what you want to do?
https://www.addictivetips.com/windows-tips/how-to-pin-an-app-window-to-all-virtual-desktops-in-windows-10/

**Comment by arnonuem** [comment]
Yes this is sufficient! Thanks for the pointer. Ticket can be closed :)
