### ISSUE TITLE
handshake error in 2.9.0

### ISSUE THREAD

**Issue by DanielRuf** [RocketChat/Rocket.Chat.Electron#529]
After the update Rocket.Chat+ does not react anymore, even in the browser where it throws `websocket' failed: Error during WebSocket handshake: Unexpected response code: 400`.

I'll buy a Macbook in the next weeks and test it with my own server, provide full logs from the testing instance and try to identify the cause with bisect.

**Comment by gdelavald** [comment]
@DanielRuf can you explain a little bit more about the 'Rocket.Chat+ does not react anymore', it's just not working after throwing the error? Usually WebSocket errors get thrown but the connection is not closed, which cause the app to recover after a short while. Have you checked the web version on the same server to check if it's not related to the server instance?
Thanks.

**Comment by DanielRuf** [comment]
The error was from the web version which also did not react, consumed much memory and made it almost impossible to close the tab.

The app and webapp did not work anymore. A downgrade to 2.8.0 / installation of a 2.8.0 client was the only working solution so far. The problem is not new afaik and happened also in other releases on macOS.

**Comment by DanielRuf** [comment]
I guess we can close this as it does not occur anymore?

**Comment by gdelavald** [comment]
Sounds good, thanks @DanielRuf
