### ISSUE TITLE
Clients of Rocket.Chat works incorrectly, if url of RC instance contains context path

### ISSUE THREAD

**Issue by konovalcev** [RocketChat/Rocket.Chat.Electron#537]
Android client and Desktop client for Windows works incorrectly, if url address of Rocket Chat instance contains context path (like https://rc.instance.com/myproject). We checked tcp dump and it looks like clients cut off context path in url and tries to log to https://rc.instance.com without context, that certainly doesn't work.
Android client doesn't connect to url with context path at all (just stuck during login forever, because according to tcpdump, it is cuts off context and tries to connect to url without it), Windows client works fine, but doesn't show preview of attached pictures and users avatar from Active Directory.
Web Client works fine. We tried to use the latest versions of clients.

Server Setup Information:

Version of Rocket.Chat Server: 0.58.1
Operating System: CentOS Linux release 7.3.1611 (Core)
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 4
DB Replicaset Oplog: yes
Node Version: v4.5.0

**Comment by konovalcev** [comment]
Hello team.
Is there any update? I just want to know, is this a known bug or we have problems with deployment.
Thanks.

**Comment by gdelavald** [comment]
@konovalcev Hey, we'll test this and update you on this issue. Thanks for your patience.

**Comment by konovalcev** [comment]
@gdelavald Great! Thanks. I will wait for your response.

**Comment by konovalcev** [comment]
@gdelavald Hello Gabriel. Is there any update?
Thanks.

**Comment by konovalcev** [comment]
@gdelavald Hello Gabriel. Looking forward to your reply!)

**Comment by gdelavald** [comment]
Hey @konovalcev I'll update the issue as soon as I have a response. Thanks for your patience.

**Comment by konovalcev** [comment]
@gdelavald Got it. Thank you!

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
