### ISSUE TITLE
No action for click or double click on the icon in KDE tray

### ISSUE THREAD

**Issue by Romich777** [RocketChat/Rocket.Chat.Electron#538]
OS: Mint KDE 18.2 x64 (KDE 5.8.7)
Rocket.Chat client 2.8.9

When clicking on icon in system tray no window appears.
Right click menu show/hide works OK.

**Comment by vcapretz** [comment]
@Romich777 we are discussing it on https://github.com/RocketChat/Rocket.Chat.Electron/issues/44, so I think we can close this one!
