### ISSUE TITLE
Snap application icon doesn't appear under Wayland

### ISSUE THREAD

**Issue by lofidevops** [RocketChat/Rocket.Chat.Electron#541]
## My Setup
- Operating System: PureOS (Debian) + GNOME 3.25.92 + libwayland 1.14.0
- App Version: 2.7.0 (installed via snap)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
"Rocket.Chat" icon does not appear after installation.

### Current Behavior
* `sudo snap install rocketchat-desktop`
* No application icon
* (Application icon does appear if I log in with X11)

### Expected Behavior
* Application icon should appear (like it does in X11)

_This could of course be an Electron issue, Snap issue or Electron+Snap issue_

**Comment by kelmes** [comment]
Setting DISABLE_WAYLAND=1 works, this is probably the same issue as here: https://github.com/vladimiry/ElectronMail/issues/104#issuecomment-463803534

**Comment by vladimiry** [comment]
See some details here https://github.com/electron-userland/electron-builder/issues/4007

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
