### ISSUE TITLE
Displays improper branding in notification

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#545]
## My Setup
- Operating System: OSX Sierra
- App Version: 2.9.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![image](https://user-images.githubusercontent.com/51996/30617619-7fb22700-9d5c-11e7-9c62-4125d20a9f07.png)
Displays only Rocket

### Current Behavior
Displays Rocket

### Expected Behavior

Should show Rocket.Chat or Rocket.Chat+ or the title of the server its from

**Comment by gdelavald** [comment]
Did this start happening after an update (osx or app) or was it a recent change?

**Comment by geekgonecrazy** [comment]
I believe it came as of 2.9.0 I only recently installed on OSX.

I did notice Rocket in some of the branding when I installed 2.9.0 on Fedora though.  I had to actually uninstall and reinstall to upgrade to 2.9.0.  So I think something changed.

**Comment by engelgabriel** [comment]
@geekgonecrazy can you please test https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.12.1 ?

**Comment by geekgonecrazy** [comment]
best I can tell this looks fixed
