### ISSUE TITLE
Reply from notification not working

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#547]
## My Setup
- Operating System: OSX Sierra
- App Version: 2.9.0
- Rocket.Chat Server: 0.59.0-rc.7

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Seems to only be an issue with 0.59.0 replying does nothing

### Current Behavior
It just doesn't work

### Expected Behavior
It should send message in response

**Comment by gdelavald** [comment]
I can't reproduce this issue. If someone else encounter this issue please add your setup so we can track it down.
