### ISSUE TITLE
[NEW] Add a linter to the project

### ISSUE THREAD

**Issue by vcapretz** [RocketChat/Rocket.Chat.Electron#548]
It would be great for the project to have a linter (like eslint) so we can have consistency when multiple people are adding and replacing code. 

I would suggest that the rules should be the same as https://github.com/RocketChat/Rocket.Chat/blob/develop/.eslintrc so Rocket.Chat can have its own pattern across projects

**Comment by gdelavald** [comment]
See https://github.com/RocketChat/Rocket.Chat.Electron/pull/494
