### ISSUE TITLE
Desktop notification does not work on windows 7

### ISSUE THREAD

**Issue by hosseinsmart** [RocketChat/Rocket.Chat.Electron#55]

**Comment by scottlilo** [comment]
Also getting this issue on windows 8.1 pro - Desktop notifications are not working with the windows app, although they do work through chrome.

**Comment by rodrigok** [comment]
@hosseinsmart @scottlilo can you try the latest release? https://github.com/RocketChat/Rocket.Chat.Electron/releases?ts=2

**Comment by mariuszjamro** [comment]
I tried the beta-2 and it's stil not working on Win 8.1 home.

**Comment by rodrigok** [comment]
Strange, it is working for me on Wind 10. I do not have the Win 8 here to test :(

**Comment by jcardila** [comment]
Tried the beta 2 on win7 and win10. The taskbar icon changes color, but no message is shown as when using chrome.

**Comment by flauschi** [comment]
I also tried beta2.
For me notifications work under Windows 10. They seem to come from the Windows 10 notification center.
Under Windows Server 2008 R2 (which should be similar to Windows 7) they do not work for me. Only the taskbar icon blinks as @jcardila already said.

**Comment by rodrigok** [comment]
As you can see here https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md?ts=2#windows notifications for Windows 10 should work out of the box, for Windows 8 it is more complicated and for Windows <= 7 it is inexistent.

But, maybe we can try to use this lib https://github.com/mikaelbr/node-notifier?ts=2 to improve notifications and use balloons for Windows <= 7

**Comment by flauschi** [comment]
Oh, I didn't knew that. Sounds good. The lib also has a Growl fallback. It shouldn't be a problem to install this for Windows <= 7 if balloon tips are not enough.

Btw: really great work!

**Comment by hosseinsmart** [comment]
hi
i test it on win 7 but it not work!

**Comment by cbajohr** [comment]
Any news on this issue? The Problem is still existing on windows 7 and makes it hard to use

**Comment by cbajohr** [comment]
May be this helps fixing the problem @rodrigok: https://github.com/electron/electron/issues/262#issuecomment-210208791

Seems pretty easy to implement but I can't test it myself, 'cause I'm not getting the node stack up on windows 7.

**Comment by cbajohr** [comment]
@rodrigok I finally got the node stack up on win7 and got the notifications up and running with toaster and notification-shim in the rocket.chat electron app. 
It looks currently like this:

![bildschirmfoto 2016-05-31 um 15 14 29](https://cloud.githubusercontent.com/assets/1948433/15675458/687946e0-2742-11e6-858b-ab2b3651b509.png)

What do you think?

**Comment by rodrigok** [comment]
Awesome, can you submit a PR with this fix?

**Comment by LFCavalcanti** [comment]
Notifications also don't work in Windows 10.

**Comment by compuguy** [comment]
Odd, I'm now having issues with notifications with latest client + rocket chat 0.31.

Sent using Boxer

On Jun 10, 2016 3:29 PM, Luiz Fernando Cavalcanti <notifications@github.com> wrote:

Notifications also don't work in Windows 10.

**Comment by motofix** [comment]
Any news for the PR acceptance?

**Comment by LFCavalcanti** [comment]
Nope and the current version of the Windows Client also doesn't work properly on Windows 7.

Lot's of PR being accepted for integrations but the native clients... not a word.

**Comment by yurykats** [comment]
Any ETA on when this could be released?

**Comment by geekgonecrazy** [comment]
next release it will be there.  We are trying to finish and upgrade of another piece before this.

**Comment by virtualwatt** [comment]
is it gonna finally work? :(

**Comment by LFCavalcanti** [comment]
@virtualwatt , it is already working, look at #224 ,
Also here: https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by virtualwatt** [comment]
Yeah you are right :) just waited for it some time and didn't take a look, sorry... But now there is a regression - double click on the tray icon doesn't open the chat window and it doesn't display the red dot if new messages are present :)

**Comment by LFCavalcanti** [comment]
@virtualwatt , do you have the commit on that?
Because here, both on Windows 10 and Windows 7 the Tray is working just fine...
