### ISSUE TITLE
Livechat and desktop notifications not working on Mac OS

### ISSUE THREAD

**Issue by G00mbah** [RocketChat/Rocket.Chat.Electron#550]
## My Setup
- Operating System: MacOs 10.12.6
- App Version: 2.9

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
When a new live chat on on of our sites is initiated, there is no notification of this fact. 

### Expected Behavior
I would like to get notified when a new live chat is being initiated, so I can respond immediately and not lose that conversation.

**Comment by monty241** [comment]
Same on my macbook.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
