### ISSUE TITLE
alluser does not work?

### ISSUE THREAD

**Issue by simakmak** [RocketChat/Rocket.Chat.Electron#553]
Good afternoon guys. I wanted to roll out the client rocket.chat in the domain, and wrote a simple script. But I ran into the fact that the / allusers switch does not work. How so? Maybe I'm doing something wrong? The / S switch works fine. But I wanted to put on all users in the domain, on each machine, and shove pre-cooked servers.json, that would determine the server on the network.

**Comment by gdelavald** [comment]
You do need administrator rights to use /allusers, make sure you have that when running the command
