### ISSUE TITLE
Projeto nao sobe no windows

### ISSUE THREAD

**Issue by nicolasdezena** [RocketChat/Rocket.Chat.Electron#554]
Estou tentando subi o projeto no WIN 10, mas n consigo de forma alguma.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle teste@2.10.0-develop~prestart: teste@2.10.0-develop
6 silly lifecycle teste@2.10.0-develop~prestart: no script for prestart, continuing
7 info lifecycle teste@2.10.0-develop~start: teste@2.10.0-develop
8 verbose lifecycle teste@2.10.0-develop~start: unsafe-perm in lifecycle true
9 verbose lifecycle teste@2.10.0-develop~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\ndeze\Desktop\teste-Mac\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\ndeze\AppData\Local\Microsoft\WindowsApps;C:\Users\ndeze\AppData\Roaming\npm;C:\Users\ndeze\AppData\Local\Yarn\bin
10 verbose lifecycle teste@2.10.0-develop~start: CWD: C:\Users\ndeze\Desktop\teste-Mac
11 silly lifecycle teste@2.10.0-develop~start: Args: [ '/d /s /c', 'gulp start' ]
12 silly lifecycle teste@2.10.0-develop~start: Returned: code: 1  signal: null
13 info lifecycle teste@2.10.0-develop~start: Failed to exec start script
14 verbose stack Error: teste@2.10.0-develop start: `gulp start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid teste@2.10.0-develop
16 verbose cwd C:\Users\ndeze\Desktop\teste-Mac
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error teste@2.10.0-develop start: `gulp start`
22 error Exit status 1
23 error Failed at the teste@2.10.0-develop start script 'gulp start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the teste package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs teste
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls teste
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by gdelavald** [comment]
Hey @nicolasdezena, please check the troubleshooting guide on the repository README to try and fix this issue.

**Comment by nicolasdezena** [comment]
Oi meu amigo, eu ja fiz de tudo, instalei o python, node-gyp e não sobe de jeito nenhum, no MAC o projeto subiu lindo, porém no windows não e se eu tento buildar para o windows o mesmo acusa que o .exe não é um win32 válido.

**Comment by gdelavald** [comment]
Did you try to run with `yarn` instead of `npm`?

**Comment by nicolasdezena** [comment]
Sim, tentei com o Yarn e com o NPM, tem alguma forma de buildar para o windows usando o mac? Da forma que eu tentei ele buildo só que no windows deu erro falando que não era um arquivo válido.

**Comment by gdelavald** [comment]
You would have to run a Virtual Machine with Windows installed to make the proper Windows build. :/

**Comment by nicolasdezena** [comment]
Então, fica difícil se o projeto não sobe haha, tentei buildar na VM mesmo não o projeto não subindo, ele fez o build porém quando executo o .exe ele fala que não é válido. haha

**Comment by gdelavald** [comment]
Did you try https://github.com/felixrieseberg/windows-build-tools ?

**Comment by nicolasdezena** [comment]
SIm, já estou a 3 semanas tentando resolver isso hahha

**Comment by engelgabriel** [comment]
We are using Appveyor to build our Windows binary, and everything works. Please look at the config for clarity and reopen this issue if this is still a problem.
