### ISSUE TITLE
Notification not working in Windows 8.1

### ISSUE THREAD

**Issue by simakmak** [RocketChat/Rocket.Chat.Electron#558]
Good afternoon. I decided to install your client on several machines, and I ran into an annoying mistake. Windows 8.1 notifications do not work. And on 7 and 10 work perfectly. How to deal with this? (

**Comment by simakmak** [comment]
Hello. Do not tell me, is there any chance to correct the error notifications in the next version? And if so, about what time is the next update? Otherwise, thanks for a great product =)

**Comment by gdelavald** [comment]
Hey, this will be added to the backlog for next version.
