### ISSUE TITLE
Automatic logoff

### ISSUE THREAD

**Issue by OtavioCapila** [RocketChat/Rocket.Chat.Electron#559]
## My Setup
- Operating System: Windows 7 Pro x64
- App Version: 2.9.0

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

![capturar](https://user-images.githubusercontent.com/29285724/31247531-41961304-a9e7-11e7-8a0f-371c60a2b333.PNG)

### Current Behavior

Alguns usuários na empresa onde trabalho,reclamaram que o Rocket.Chat desconectou suas contas sem motivo algum.
Alguns usam a versão 2.8.0,outros usam a versão 2.9.0
Isso acontece quando a máquina entra em modo de suspensão após algum tempo sem utilizar.

### Expected Behavior

Não finalizar sessão automaticamente.

**Comment by gdelavald** [comment]
@OtavioCapila can you provide the server version as well? This was an issue which was fixed in the latest version of the server.

**Comment by OtavioCapila** [comment]
@gdelavald We are using version 0.58.3.
This issue was fixed in the last stable or beta version?

**Comment by gdelavald** [comment]
It should have been fixed on 0.58.3, were you able to reproduce the issue after the update?

**Comment by OtavioCapila** [comment]
@gdelavald Happened to me only once. But this week the employees complained a few times about this problem.

**Comment by timbobishop** [comment]
@gdelavald I've got about 20 people on Mac OS X using both 2.8 * 2.9, server version 0.58.3 and I've been getting complaints of people being logged off multiple times a day.

**Comment by phriedrich** [comment]
I think this should be fixed with today's Rocket.Chat 0.58.4: https://github.com/RocketChat/Rocket.Chat/pull/8420/commits/3a90df3f30003f4a414570c1ef853635a7a8d768

**Comment by localguru** [comment]
I'm using 2.9.0 on Android (battery optimized off) and 0.58.2. The Android client goes to offline after some time. Shouldn't is be just "away"? See some stats:

![image](https://user-images.githubusercontent.com/8544984/31319530-47397a0a-ac65-11e7-9cf2-5ca0c91dd957.png)

**Comment by gdelavald** [comment]
@localguru are you using electron for Android? By the way, you should update for 0.58.4 for security reasons and I fix the offline bug was fixed in hotfix .3

**Comment by localguru** [comment]
@gdelavald I'm using this client on my Android 7 phone: 

https://play.google.com/store/apps/details?id=com.konecty.rocket.chat&hl=de

"you should update for 0.58.4 for security reasons": hmmm ... didn't realise that 0.58.4 was  a security update, I thought it was about dependencies. Is there a list of fixed security bugs?

**Comment by gdelavald** [comment]
@localguru As far as I know, 0.58.3 was a security fix by some dependencies, since you mentioned you were running 0.58.2 that's why I recommended the update.

Let me know if the issue was fixed in .3 so we can close this issue. Thanks!

**Comment by localguru** [comment]
@gdelavald Upgraded to 0.58.4 now and my cellphone user changes to offline after 15 minutes.

**Comment by gdelavald** [comment]
@rafaelks Can you clarify about how the mobile app is working with away/offline status?
@localguru Since we're on the Electron repository, I would ask to test on the desktop version regarding the issue mentioned above.

**Comment by rafaelks** [comment]
@gdelavald @localguru Yes. In our [native Android app](https://play.google.com/store/apps/details?id=chat.rocket.android) it works like this:

1. You open the app, it'll use your latest status;
2. You go to background, it'll change your status to **away**;
3. Android kills the app, it'll change your status to **offline**;
4. You close the app, it'll change your status to **offline**;

**Comment by localguru** [comment]
@gdelavald Gabriel, the desktop version works fine. The electron client never goes offline as log as my notebook is online and the electron client is running. The status changes from online to away, see this stats:

![image](https://user-images.githubusercontent.com/8544984/31755757-601dc7a4-b4a0-11e7-8120-e7b23ee91f8b.png)

The client on the Android cell phone is offline after some time, see this stats of my status from last night, were the cell phone was connected via WLAN and the RC client was running:

![image3](https://user-images.githubusercontent.com/8544984/31755847-f612b648-b4a0-11e7-9f03-d900d2ae2d2b.png)

Ciao!

**Comment by gdelavald** [comment]
Ok, I think the issue was resolved then, please let me know if something related comes up or if anyone is still having this issue.
Thanks.
