### ISSUE TITLE
Desktop Client - Option to toggle server column on/off , also manually adjustable column widths?

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat.Electron#56]
Some feedback from the test groups was that maybe we can have an option to toggle the server column on or off (if only one server connected probably doesn’t need to be shown?)

An on a per user basis manually adjustable column widths to suit their specifics?

**Comment by engelgabriel** [comment]
We already have the first, and the second would be a nice to have, but not a priority.

![image](https://cloud.githubusercontent.com/assets/1000217/11095549/bb557088-887c-11e5-85c8-49652fbaea26.png)

**Comment by engelgabriel** [comment]
I'll update the compiled binaries with the latest version.

**Comment by Megatronic79** [comment]
Great, thanks for the update.
