### ISSUE TITLE
Cannot see the new message text box.

### ISSUE THREAD

**Issue by swvajanyatek** [RocketChat/Rocket.Chat.Electron#564]
## My Setup
- windows 8.1:
- 2.9.0:

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

I can't see the "message" text box at the bottom.  I've tried zooming way in and way out, but no luck.  This seems to have happened after a basic Windows reboot, but might also coincide with a recent update to chrome 61.

**Comment by rborder** [comment]
Same bug in Ubuntu 17.04.

**Comment by h-kaiser** [comment]
Same bug on MacOS 10.13.4

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
