### ISSUE TITLE
If you upload two files with the same name but different extension, all file extensions are changed to last one uploaded file extension. 

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat.Electron#567]
My Setup
- Operating System: Windows 10
- App Version: 2.9.0

- [X ] I have tested with the latest version
- [X ] I can simulate the issue easily

When two files are sent with the same name, but different extension, both file extension are renamed to last file extension. 
Example:
If i send two files: abc.jpg and abc.dat, recipient get two files abc.dat and abc.dat. The same with three or more files, with the same name but different extension. 

If you do this using Web browser, everything is ok, this issue is only in Electron client.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
