### ISSUE TITLE
almost invisible scrollbar

### ISSUE THREAD

**Issue by c0m4r** [RocketChat/Rocket.Chat.Electron#571]
## My Setup
- Operating System: Ubuntu 16.04.3 LTS
- App Version: Rocket.Chat+ Version 2.9.0

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description
https://i.imgur.com/fE3B4tm.png

### Current Behavior
almost invisible scrollbar

### Expected Behavior
handy, visible scrollbar

**Comment by gdelavald** [comment]
@c0m4r This is related to the design, so please report the issue on the Rocket.Chat main repository. Thanks.

**Comment by Chealer** [comment]
Rocket.Chat ticket #13892 tracks this: https://github.com/RocketChat/Rocket.Chat/issues/13892
