### ISSUE TITLE
unintuitive on-hover and on-click effect on channels / users

### ISSUE THREAD

**Issue by c0m4r** [RocketChat/Rocket.Chat.Electron#572]
## My Setup
- Operating System: Ubuntu 16.04.3 LTS
- App Version: Rocket.Chat+ Version 2.9.0

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description / Current Behavior
on-focus effect: https://i.imgur.com/OfWIgNy.png - clear, contrast background
on-hover effect: https://i.imgur.com/s2AqghJ.png - only "3 dots" showing up, no background change
on-click: while the channel / conversation is loading at the right side of the app there's really no on-click effect

### Expected Behavior
better, clear on-hover effect and on-click reaction

**Comment by gdelavald** [comment]
@c0m4r This is related to the design, so please report the issue on the Rocket.Chat main repository. Thanks.
