### ISSUE TITLE
Close/Min/Max buttons on OSX will overlap the profilepicture if serverlist is closed.

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.Electron#573]
@ausminternet commented on [Mon Oct 23 2017](https://github.com/RocketChat/Rocket.Chat/issues/8600)

![image](https://user-images.githubusercontent.com/5732325/31875845-3b96987e-b7d0-11e7-921e-b35095ec4e91.png)

This can be fixed by adding more `padding-top` to `.sidebar__account` if serverlist is closed.

**Comment by dzienisz** [comment]
@gdelavald could you close this issue?
