### ISSUE TITLE
Uploaded .wav files are not playable from message

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat.Electron#578]
Hello Devs.

Rocketchat Server 0.59.1

Running 2.9.0 on MacOS High Sierra. Unfortunately uploaded wav files do not play back. The playback button is not clickable.

Any ideas?

**Comment by gdelavald** [comment]
@himbeere Hey, thanks for the report. Does the voice messages play when sent? You can send one by clicking on the + of the message box and on the Audio Message item (then click again when you're done).

**Comment by himbeere** [comment]
>Does the voice messages play when sent?

Yes they do. 

cheers
t.

**Comment by gdelavald** [comment]
Issue moved to [RocketChat/Rocket.Chat #8995](https://github.com/RocketChat/Rocket.Chat/issues/8995) via [**ZenHub**](https://www.zenhub.com/)
