### ISSUE TITLE
Filenames with umlauts cause broken upload

### ISSUE THREAD

**Issue by emign** [RocketChat/Rocket.Chat.Electron#579]
On rocketchat+ on iOS when you upload a file (eg pdf) with an umlaut the file seems to upload correctly and is shown in the message stream. But clicking it does not open it but only shifts the text up and down a bit

**Comment by gdelavald** [comment]
@emign Sorry, is this mobile or on a Mac computer?

**Comment by emign** [comment]
It is on iOS mobile (iPad and iPhone) with version 1.6.0. the same (umlaut-titled file) can be downloaded via a browser on the device just fine btw.

**Comment by gdelavald** [comment]
Issue moved to [RocketChat/Rocket.Chat.iOS #851](https://github.com/RocketChat/Rocket.Chat.iOS/issues/851) via [**ZenHub**](https://www.zenhub.com/)
