### ISSUE TITLE
Would like support for multiple organizations/servers/accounts in the same client at the same time.

### ISSUE THREAD

**Issue by bgupta** [RocketChat/Rocket.Chat.Electron#58]
It would be really helpful if the desktop client supported multiple servers at the same time. In my use case I could see wanting the multiple server accounts open at the same time, in a single client. (This would be like slack where you can authenticate with multiple "slack domains" from the same client. The slack client has a third column to the left of the channel chooser, that allows you to pick your account/domain. It doesn't take up much space. Another analogy would be an IRC client that can simultaneously connect to multiple IRC networks.)
 
Example use case would be simultaneous connections to the following:
1) Default Demo account, so I can access support, and what not.
2) Local Computer Club account (Think something like the http://www.nyctechslack.com/)
3) Company account #1
4) Company account #2

**Comment by engelgabriel** [comment]
We already have this:

![image](https://cloud.githubusercontent.com/assets/1000217/11095517/75d4f8bc-887c-11e5-9451-73aa82889c19.png)

Can I close the issue?

**Comment by engelgabriel** [comment]
It will work better when this is merged

https://github.com/RocketChat/Rocket.Chat.Electron/pull/52

**Comment by elvise** [comment]
how can do it from web ? @engelgabriel
