### ISSUE TITLE
Deprecated Link to KaTex formatting

### ISSUE THREAD

**Issue by zedar187** [RocketChat/Rocket.Chat.Electron#589]
## My Setup
- Operating System: Win 10 Prof.
- App Version: 2.9.0
- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The link of the KaTeX formatting is deprecated. If you click the format in the desktop app, the browser opens the url: https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX

The page states, that one should use the following link with more examples: https://khan.github.io/KaTeX/function-support.html

**Comment by mritunjaygoutam12** [comment]
i am working on it.

**Comment by gdelavald** [comment]
This should be fixed in the main repository, please check RocketChat/Rocket.Chat

**Comment by mritunjaygoutam12** [comment]
I have changed the link from [https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX
](url) to [https://khan.github.io/KaTeX/function-support.html](url) in Rocket.Chat in my fork(ready for PR).

@gdelavald is it fine to change only link in rocket.chat?
