### ISSUE TITLE
Sidebar redesign and dynamic background color doesn't work

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Electron#595]
## My Setup
- Operating System: Ubuntu 16.04
- App Version: 2.10.0, 2.14.3, 2.15.0-develop

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

Sidebar redesign and dynamic background color doesn't work properly. After starting the sidebar colors are set correctly but when changing between the servers the sidebar color hangs and doesn't change any more.

### Expected Behavior

Sidebar redesign and dynamic background color should change when selecting different servers.

See  #556 #534

**Comment by gdelavald** [comment]
@localguru Thanks for the feedback. If possible, could you try and reproduce the issue with the developers console open? This way if any exception pops up we can track it down.
Thanks!

**Comment by localguru** [comment]
Problem still exists, client version 2.13.3

After the second server has been added, the left navigation bar for the first server no longer returns to "green" when switching back and forth between the two servers.

**First server:**

![bildschirmfoto_2018-10-04_11-35-45](https://user-images.githubusercontent.com/8544984/46465947-46cd9700-c7ca-11e8-9282-17627fdb042f.png)

**Second server:**

![bildschirmfoto_2018-10-04_11-37-15](https://user-images.githubusercontent.com/8544984/46465956-4b924b00-c7ca-11e8-8cf2-ad0a1ee61028.png)

**Comment by localguru** [comment]
Still an issue in 2.14.3.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
