### ISSUE TITLE
2.10.0 does not start because mainWindowState.x is NaN

### ISSUE THREAD

**Issue by mahkoh** [RocketChat/Rocket.Chat.Electron#598]
## My Setup
- Operating System: Arch Linux
- App Version: 2.10.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
* Remove $XDG_CONFIG_DIR/Rocket.Chat+/window-state-main.json
* Start rocketchat

### Current Behavior
* The following error occurs: 
![2017-11-10-091039_509x268_scrot](https://user-images.githubusercontent.com/1882250/32648633-0a772c4c-c5f7-11e7-9c9d-749134a281c3.png)
* The rocketchat window is empty

### Expected Behavior
Rocketchat should work.

### The problem

The problem is 5accb58a419255264bca869879d8366c9637d7d1 which calls Math.floor on state.x. If window-state-main.json does not exist or does not have "x" set, state.x is undefined and Math.floor returns NaN.

**Comment by artrmz** [comment]
Duplicated #594

**Comment by ranjith0** [comment]
:+1: Also seeing this error on Window 7 SP1 32/64

**Comment by gdelavald** [comment]
Hotfix 2.10.1 was released to fix this issue, please update when possible and report if it still occurs.
