### ISSUE TITLE
Open menu on Alt+Shift

### ISSUE THREAD

**Issue by hartois** [RocketChat/Rocket.Chat.Electron#599]
## My Setup
- Operating System: Fedora 26 x86_64
- App Version: rocketchat-2.10.0-650.x86_64

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When I type message and switch keyboard layout by Alt+Shift combination, application menu opens.
On rocketchat-2.9.0-538.x86_64 there is no problems.

### Current Behavior
Application menu opens.

### Expected Behavior
Only keyboard layout switched or nothing (if Alt+Shift does not configured).

**Comment by ozeas** [comment]
Can I help here?

**Comment by ozeas** [comment]
Maybe I can send a PR to this issue. Can I try?

**Comment by hartois** [comment]
I think, if you can make PR - do this!

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
