### ISSUE TITLE
Option to clear all the cache, cookies and localstorage.

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat.Electron#60]
##

**Comment by popiolek** [comment]
As quick fix before some real fix, I've created simple batch script that deletes cookies and local storage files before starting app. Maybe someone will find it helpful:
```
@echo off

:: Set Rocket.Chat path here (path to exe file)
set chat="%ProgramFiles(x86)%\Rocket.Chat\Rocket.Chat.exe"
:: Files to delete
:: GitLab login is stored in cookies
set file[0]=%USERPROFILE%\AppData\Roaming\Rocket.Chat\Cookies
set file[1]=%USERPROFILE%\AppData\Roaming\Rocket.Chat\Cookies-journal
:: Rocket.Chat login is stored in local storage
set file[2]=%USERPROFILE%\AppData\Roaming\Rocket.Chat\Local Storage\https_yourdomain.com_0.localstorage
set file[3]=%USERPROFILE%\AppData\Roaming\Rocket.Chat\Local Storage\https_yourdomain.com_0.localstorage-journal

:: For each file
for /F "tokens=2 delims==" %%s in ('set file[') do (
	:: If sosmething already was marked then delete
    if exist "%%s.toDelete" del "%%s.toDelete"
    :: Check if file is locked if not mark to delete
    if exist "%%s" move "%%s" "%%s.toDelete" || goto onerror
    :: Delete marked file
    if exist "%%s.toDelete" del "%%s.toDelete"
)

:: Run Rocket.Chat app and finish script
start "" %chat%
exit

:onerror
:: Show error message (should work for most systems)
mshta javascript:alert("Files are locked.\n\nCheck if there is no Rocket.Chat running in the backgroud.");close();
```

You need to provide your domain in there `https_yourdomain.com_0.localstorage`, and any path if it differ. Sorry for code quality but I don't have any experience with Batch scripting (and time;).

**Comment by popiolek** [comment]
UPDATE: remote part of my office told me, that this script breaks the ability to start a voice chat. I don't know how it's possible as all files are recreated on app start, but be aware of that if you use that script. Gave as a real headache to debug that.

**Comment by JafryD2** [comment]
that script effects all notifications(in app), not just voicechat btw. We haven't tested it with the browser version.

**Comment by ddoron** [comment]
For anyone who needs a stopgap solution on OS X (aka macOS), this worked for me, but I'm no developer, though I doubt I'm doing any "harm":

- close the Rocket Chat app.
- delete the directory "chat.rocket" that in the following path:
`~/Library/Containers/chat.rocket/`
- open the Rocket Chat app.

**Comment by bhathiya** [comment]
For the record: In Ubuntu, deleting below directories cleared the cache. 
`/home/<user>/.config/Rocket.Chat+/Cache`
`/home/<user>/.config/Rocket.Chat+/GPUCache`
`/home/<user>/.cache/Rocket.Chat+`
