### ISSUE TITLE
Application is just crashing

### ISSUE THREAD

**Issue by CodedInk** [RocketChat/Rocket.Chat.Electron#600]
## My Setup
- Operating System: MacOS High Sierra Version 10.13.2 Beta (17C67b)
- App Version: Rocket.Chat.Electron

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

### Current Behavior

I installed it and it crashed right away and yes I installed it correctly :)
It is not an issue between the head and shoulders.

### Expected Behavior

It should get fixed!

**Comment by reinerj** [comment]
same here. Latest release just crash direct after start

**Comment by gdelavald** [comment]
Hotfix 2.10.1 was released to fix this issue, please update when possible and report if it still occurs.

**Comment by reinerj** [comment]
Looks like it iOS fixed,

thanks
