### ISSUE TITLE
Update.json not recognised in install directory

### ISSUE THREAD

**Issue by skfin** [RocketChat/Rocket.Chat.Electron#603]
## My Setup
- Operating System: Windows 10
- App Version: 2.9, 2.10.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I'm trying to disable update notifications using the update.json file with:

`{  "autoUpdate": false
}`

This works in the appdata folder but not in the install directory. 
I've tried it in both the root folder and resources folder but neither work.

**Comment by johnyb0y** [comment]
Same for me. This feature would be great for my deployment. We are using Rocketchat in an virtualized enviroment and users cannot update the client on their own.

**Comment by gdelavald** [comment]
Thanks for the feedback, it should be an easy fix since we already do that for the servers.json file so if anyone wants to give it a try, PRs welcome.

**Comment by krispayne** [comment]
Can this also be made to work for MacOS? Using #523, #449, #603, and #822 as rough guides, and my own installation, I placed `{ "autoUpdate": false }` in an update-info.json file at `~/Library/Application Support/Rocket.Chat/__update__/update-info.json` but was still greeted with an update dialog on first open (to 2.17.0 which does not open on MacOS currently.)

Happy to open another Issue if it's better!

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
