### ISSUE TITLE
Node version security issue

### ISSUE THREAD

**Issue by JorisVanEijden** [RocketChat/Rocket.Chat.Electron#604]
## My Setup

 - Windows 10
 - Rocket.Chat+ 2.10.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Windows version comes with node.dll v8.2.1.0 which has a security issue with zlib (https://nodejs.org/en/blog/vulnerability/oct-2017-dos/)

#### Current Behavior

Node version with known security vulnerabilities used.

#### Expected Behavior

Node version with no known security vulnerabilities used.

## Disclaimer
I am not personally aware of specific ways to abuse this vulnerability. I just get alerts from our security software when users install Rocket.Chat.

**Comment by gdelavald** [comment]
Thanks @JorisVanEijden, we'll update this asap.

**Comment by gdelavald** [comment]
Closed by #615

**Comment by JorisVanEijden** [comment]
Maybe use https://nodesecurity.io/opensource to check the code for vulnerable npm dependencies before release?
