### ISSUE TITLE
Compile client code to asm.js

### ISSUE THREAD

**Issue by Romich777** [RocketChat/Rocket.Chat.Electron#605]
Are this possible to compile client code to asm.js to improve performance?

**Comment by alexbrazier** [comment]
“asm.js is an intermediate programming language designed to allow computer software written in languages such as C to be run as web applications while maintaining performance characteristics considerably better than standard JavaScript, the typical language used for such applications“ - [Wikipedia](https://en.wikipedia.org/wiki/Asm.js)

Unless I’m not understanding correctly, this would require a complete rewrite of the app in C/C++, so it is very unlikely to happen.

**Comment by gdelavald** [comment]
It doesn't make a lot of sense since we are using electron, which already connects directly to c++ afaik.
We are looking into ways to optimize the app and we thank you for the suggestion.
