### ISSUE TITLE
Message window quickly opened and closed while installing with silent switch /S

### ISSUE THREAD

**Issue by diegocortassa** [RocketChat/Rocket.Chat.Electron#607]
## My Setup
- Operating System: Windows 7
- App Version: 2.10.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

I'd like to deploy the Rocket.Chat Desktop app with a startup script in my GPO. This is the script I'm currently testing:

`@ECHO OFF`

`%SystemDrive%`
`cd %ProgramFiles%`
`if exist "rocketchat" goto end`
`\\\\fileserver\\rocketchat-setup-2.10.1.exe /S /allusers`
`echo. {>rocketchat\resources\servers.json`
`echo.   "Animoka Bar Chat": "https://chat.myserver.com">>rocketchat\resources\servers.json`
`echo.}>>rocketchat\resources\servers.json`

`:end`
`cd \\`

This script works if I run it (as administrator)  but I can see the installer quickly opening and closing an "installing" message window, I thinks this prevents the script to work in GPO because you can't open any gui during a startup script. 

### Current Behavior

A window is quickly opened and closed while installing with silent switch /S

### Expected Behavior

When installing with silent switch /S no windows should be opened

**Comment by gdelavald** [comment]
@diegocortassa are you running the script with admin rights? Usually the window pops up if you don't have admin privileges to use /allusers

**Comment by diegocortassa** [comment]
Hi @gdelavald, thanks for your answer.
Yes, when run manually, from a cmd, with admin rights, the installation does work but the window opens anyway. I just tried again, I can't take a screenshot because it closes very quickly but this time I could read the message: "please wait while setup is loading"

**Comment by gdelavald** [comment]
Thanks, we'll investigate the issue.

**Comment by diegocortassa** [comment]
Just a quick update I tried the /S option with the new 2.14.7 but the "please wait while setup is loading" message window still briefly opens preventing automated installation via script.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
