### ISSUE TITLE
My People support on Windows 10

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat.Electron#608]
As per my [tweet](https://twitter.com/hammyhavoc/status/930889689887854594):
[https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/my-people-support](
https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/my-people-support)

I would love to see support for My People come to RocketChat; seems to be a great way to integrate the chat with Windows 10, and integrates quite happily alongside other chat programs such as Skype.

**Comment by Kenya-West** [comment]
Would love to see this.

**Comment by HammyHavoc** [comment]
Additional info regarding it: https://github.com/shenchauhan/MyPeople

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
