### ISSUE TITLE
Electron interface blank after server goes offline

### ISSUE THREAD

**Issue by mide** [RocketChat/Rocket.Chat.Electron#61]
## Problem

When a client is opened and tries to connect to it's last known server and that server is no longer online, the client interface is broken. This can happen if the server has just been shut off, or even if the server changed addresses or ports.

I am running the Rocket.Chat OS X Electron Client (Version 0.0.9).

I was looking to remove all my user data (see #60), but the comments in that thread are Windows specific. I tried deleting `~/Library/Application\ Support/Rocket.Chat`, but that didn't solve my problem.

## To Reproduce

1. Start a new Rocket.Chat server, say on `192.168.1.100:3000`.
1. Download and install the Rocket.Chat OS X client.
1. Register new account and login like normal.
1. Close Rocket.Chat OS X client.
1. Stop Rocket.Chat server (on `192.168.1.100:3000`)
1. Open Rocket.Chat OS X client again and observe the interface is now broken. See screenshot below.

![screen shot 2015-12-09 at 2 19 35 pm](https://cloud.githubusercontent.com/assets/546518/11696303/a5a7d1a2-9e81-11e5-8f13-e6b8c9503d3a.png)

**Comment by rodrigok** [comment]
Please try the version 1.0.0

**Comment by mide** [comment]
I can confirm this problem is now fixed. Thanks! :relieved:
