### ISSUE TITLE
quoted text not visible on some clients

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Electron#611]
Hi Devs.

MacOS High Sierra, Rockchat Server 0.59.3, 2.10.1 Desktop Client.

On some clients the quoted text is not visible. Only the name of quotee and the time is shown. Other does not have this issue although the use the same environment.

![bildschirmfoto 2017-11-20 um 10 47 01](https://user-images.githubusercontent.com/631865/33016717-e392da76-cdef-11e7-999a-b36d4256be34.png)

thanks and cheers

**Comment by himbeere** [comment]
Issue still present with 2.10.5.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
