### ISSUE TITLE
Windows Client App settings in a file

### ISSUE THREAD

**Issue by hasop** [RocketChat/Rocket.Chat.Electron#614]
## My Setup
- Operating System: Windows
- App Version: Latest

- [X ] I have tested with the latest version
- [ X] I can simulate the issue easily

## Description
Is it possible to create settings file (prefs.json by example) for hiddenMenu or no spellchecking options in Windows App ?
That would be really convenient for mass deployment.

### Current Behavior
This settings are stored in LocalStorage i think.

### Expected Behavior
Settings are in prefs.json and can be mass deployed like update.json and servers.json

**Comment by gdelavald** [comment]
Thanks for the suggestion, this is something we have in mind for the next release so stay tuned 😄

**Comment by jeanfbrito** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron#overridden-settings
