### ISSUE TITLE
Cannot click with Wacom pen

### ISSUE THREAD

**Issue by akrabat** [RocketChat/Rocket.Chat.Electron#617]
I Use a Wacom table for accessibility reasons and can no longer click on anything in RocketChat 1.9.0 for OS X.

I suspect that it's an Electron issue as the Slack app had the same problem. Their latest released fixed this issue so maybe integrating the latest Electron will solve it for Rocket.Chat.Electron too.

**Comment by gdelavald** [comment]
Related to https://github.com/electron/electron/issues/7815

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
