### ISSUE TITLE
Better notification

### ISSUE THREAD

**Issue by klesky** [RocketChat/Rocket.Chat.Electron#618]
## My Setup
- Operating System: Windows 10
- App Version: Version 2.9.0

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description

Taskbar icon for the application doesn't blink when you're in private group chat with notification settings enabled

### Expected Behavior

Should be able to show blinking taskbar icon in private group chat

**Comment by jeanfbrito** [comment]
Hello, we will be tracking the blinking icon feature request here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2525
