### ISSUE TITLE
Update Process deletes All-Users servers.json config

### ISSUE THREAD

**Issue by johnyb0y** [RocketChat/Rocket.Chat.Electron#619]
## My Setup
- Operating System: Windows 7 
- App Version: 2.10.1

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description

Updating Rocket.Chat Electron deletes the servers.json in resources folder inside the Install Directory. 
I guess this happens, because before updating the install directory is completely purged?
This doesn't happen with per-user Installs, because Rocket.Chat Electron doesnt't remove Appdata\Roaming\Rocket.Chat+ while updating.

### Current Behavior
servers.json in All-Users install directory Rocket.Chat+\resources gets deleted.

### Expected Behavior
servers.json should survive the update process, since it's a custom file which is only manually created.

Kind regards

**Comment by gdelavald** [comment]
Thanks for the report, we'll investigate and check how we can make sure the customisation from servers stay through updates.

**Comment by nitmir** [comment]
I guess all the content of the resources get deleted as servers.json is deleted but also update.json

**Comment by johnyb0y** [comment]
@nitmir yup. Still happening. I just documented it in my update workflow.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
