### ISSUE TITLE
Automatically attempt to reconnect after failure

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat.Electron#621]
As per my tweet on [https://twitter.com/hammyhavoc/status/935595873656098816](https://twitter.com/hammyhavoc/status/935595873656098816), I've been asked to open an issue here regarding it.

> @RocketChat If the desktop client can't connect to a RocketChat server and you're presented with the 'Reload' button and error, does it ever automatically attempt to reconnect? If not, that needs addressing; been trying to ping colleague but their RC client had that.

**Comment by gdelavald** [comment]
Hey @HammyHavoc, thanks for the suggestion. That would actually be pretty cool, we can't focus on it right now but we'd love if someone from the community could work on this.

**Comment by netzwerch** [comment]
I'd also love to see this feature. I've also got the same problem when using autostart, meaning that the client gets started without having a wifi/vpn connection yet.

**Comment by netzwerch** [comment]
So I now got something that works for me.
In the file `/src/public/loading-error.html`
I added the following line somewhere in the \<html\>
`<script>setInterval(() => { document.getElementById("reload").click() }, 10000)</script>`
Quick and simple... opinions?
