### ISSUE TITLE
Really bad user experience with new message notifications

### ISSUE THREAD

**Issue by Anguel** [RocketChat/Rocket.Chat.Electron#622]
I have not expected so bad user experience with the Rocket Chat Client (Windows 10 used here). We spent much time installing a rocket chat server and users just don't notice that new messages have arrived. We are even thinking about switching to another chat program for that reason. And I see that other users have the same issue here.

This is not an enhancement request, this is a request for essential functionality missing in a chat app. Make this thing blink not only the tray, but also the taskbar (even when minimized) or even make it display its own notifications so that we don't depend on OS notifications which are not configurable at all.

Also please add an option to make users that sent a new message appear on top of the user list and blink so that we know where to look in the chat app. If users are further down in the list there is no way to see that they have sent a new message even if the main window of the app is open...
Please don't let this horrible user experience destroy this really nice chat. Thanks in advance.

**Comment by alexbrazier** [comment]
@Anguel Sorry to hear that. We will investigate notification issues on Windows 10 and see how they can be improved.

As for new messages appearing on top, there is a setting in user preferences to enable this:
![image](https://user-images.githubusercontent.com/5689874/33686087-95c8a526-dacb-11e7-8c10-9329f0176985.png)

**Comment by Anguel** [comment]
Thanks a lot for the information. I will immediately change it. However I still think that a blinking option is the best as people immediately know where to look at, the small numbers can still easily be missed. Also a global server setting for this is more than welcome, so that we don't have to make the users configure this.

**Comment by jeanfbrito** [comment]
Hello, we will be tracking the blinking icon feature request here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2525
I will be closing this issue because there are duplicated ones.
