### ISSUE TITLE
main window is not displaying 

### ISSUE THREAD

**Issue by tsesliv** [RocketChat/Rocket.Chat.Electron#623]
## My Setup
- Operating System: Windows 7 Pro x64
- App Version: 2.10.1.598

- [ X] I have tested with the latest version
- [ X] I can simulate the issue easily

## Description

Message: Windows client 2.10.1.598, on Win7 – main window is not displaying, chat still is active in taskbar and pop-ups appear on new messages, but chat window is not displaying (for less than second it flashes and then hides).

### Current Behavior

I'm starting application, it "flashes" (only canvas of the window are visible for some short time), then it completely disappears, meanwhile icon in the tray is running, pop-up notifications are working, and tray icon considers main window is visible.

https://youtu.be/S6Fm40DgndE
here on the video of chat behaviour 

### Expected Behavior

window to be shown

**Comment by gdelavald** [comment]
Thanks for the report, this seem like a regression bug and we'll investigate and fix it as soon as possible.

**Comment by jaypea** [comment]
steps to reproduce:
 - open chat
 - press "ctrl+w" in a chat window
 - gui closes
 - entry `"isHidden": false` will change to `"isHidden": true` in `~/.config/Rocket.Chat+/window-state-main.json`
 - gui will not come up again

**Comment by jaypea** [comment]
i've found this discussion which might help with closing and hiding the window: https://discuss.atom.io/t/how-to-catch-the-event-of-clicking-the-app-windows-close-button-in-electron-app/21425/8

**Comment by tsesliv** [comment]
window-state-main.json editing helps, thanks! 
x and y positions were set to "-32000" something. after setting to 0 window opens correctly.

**Comment by stopal** [comment]
Thank you @jaypea.
But why is this issue closed? It is so annoying on Fedora... every time when i want to start RocketChat i have to set `isHidden: false` first.

**Comment by helderam** [comment]
Thanks

Solve my problem too !!!

**Comment by tassoevan** [comment]
@stopal Your Fedora desktop don't have a system tray, right? The default behavior of Rocket.Chat app is just to hide the window on close and keep the tray icon; in the next run, the program starts with the window hidden. Some users have reported this and we are working to fix the experience for users at desktops without a systray.

**Comment by mathiasbosman** [comment]
Even with a "system tray" the icon isn't showing, but that's probably a Fedora thing.

@tassoevan 
Is there an issue we can follow for the fix?
Currently I just overwrite the config file with a batch whenever I login.

**Comment by tassoevan** [comment]
@mathiasbosman There are some issues like #878, but the reports are somewhat specific despite the standard "solution".

**Comment by mathiasbosman** [comment]
@tassoevan alright, thanks!

For those interested: I created a new file in the .config folder of Rocket.Chat called `window-state-reset.json` with the contents:
```json
{
  "width": 1650,
  "height": 1500,
  "isMaximized": false,
  "isMinimized": false,
  "isHidden": false,
}
```

in my `.bash-profile` (usualy located in your home directory) I simply added:
```batch
# Reset Rocket.chat+ window settings
cp ~/.config/Rocket.Chat/window-state-reset.json ~/.config/Rocket.Chat/window-state-main.json
```
