### ISSUE TITLE
Broken layout for macOS when toggled server list

### ISSUE THREAD

**Issue by JannikZed** [RocketChat/Rocket.Chat.Electron#624]
Description:

The layout for the macOS client has a broken layout with Rocket.chat server version 0.59.3:
<img width="607" alt="33241933-23d3d824-d2cd-11e7-8578-8083c127830f" src="https://user-images.githubusercontent.com/7526174/33477779-40732422-d687-11e7-858d-3aa970471719.png">

Server Setup Information:

Version of Rocket.Chat Server: 0.59.3
Operating System: macOS 10.13.1
Deployment Method(snap/docker/tar/etc):
Number of Running Instances:
DB Replicaset Oplog:
Node Version:
Steps to Reproduce:

On macOS click VIEW -> toggle server list

The view looks perfect with opened server list:
<img width="504" alt="33241978-018c9200-d2ce-11e7-86f0-065718cb70f2" src="https://user-images.githubusercontent.com/7526174/33477787-48393dcc-d687-11e7-869b-0ea859e673e3.png">

**Comment by gdelavald** [comment]
Hey @JannikZed, can you confirm which version of Rocket.Chat+ are you using? The electron version 2.10.1 already fixed this with the sidebar redesign.

**Comment by JannikZed** [comment]
Yep, updating to the newest version fixed the bug! Thank you.
