### ISSUE TITLE
System Tray Icon Issues in KDE/Fedora.

### ISSUE THREAD

**Issue by rbland** [RocketChat/Rocket.Chat.Electron#625]
Howdy,

I'm having some trouble with the system tray icon even with the latest RocketChat version. 

## My Setup
- Operating System: Fedora 21
- Desktop Environment: KDE 4.14.9
- App Version: 2.10.1

## Description
There are really two issues:

The first is all icons displayed in the tray are not being scaled to fit the space:
![rocket_system_tray](https://user-images.githubusercontent.com/1904076/33496215-fbc79a94-d68e-11e7-912e-d173de7af12a.png)

The second issue is that left clicking the icon still has no effect. It sounded like this was fixed by: #44 but I'm still having the same behavior in 2.10.

**Comment by Kamilko47** [comment]
Hi. If You still have this problem try this solution. It's working on plasma 5.
http://www.webupd8.org/2017/04/fix-appindicator-not-working-for.html
`env XDG_CURRENT_DESKTOP=Unity rocketchat`

**Comment by rbland** [comment]
So I WAS still having this problem and the specific suggestion did NOT work; however, it put me on the path to a solution which was to set XDG_CURRENT_DESKTOP to "GNOME".

**Comment by XecKiE** [comment]
Howdy,
Me and my coworkers (on Kubuntu) have the exact same issue (truncated icon + left clic not working). The fix that @rbland  worked, but I think it should be fixed deeper (the client seems to be bot working properly on every KDE version).

In addition, I'm forced to launch it from a console which is not very handy.

What do you think ?
