### ISSUE TITLE
Client doesn't run on Debian Stretch

### ISSUE THREAD

**Issue by Romich777** [RocketChat/Rocket.Chat.Electron#627]
After updating client to version 2.10 and 2.10.1 I get white page.
Clean reinstalling doesn't help.

**Comment by ttepatti** [comment]
I'm running Debian Stretch version 9.5 and don't run into any issues opening the latest version of RocketChat (2.14.*). I'm running the most up-to-date packages available in the official Debian apt repository. I think this issue can be closed, it seems to have just been sitting open for a while.
