### ISSUE TITLE
Multiple files upload have all the same name

### ISSUE THREAD

**Issue by menkow** [RocketChat/Rocket.Chat.Electron#629]
- Version 2.10.1
- Windows 7
- I can simulate the issue easily

When I select several files in Windows Explorer and then drag and drop it on RocketChat conversation there is all files with same file name.
![screenshot_1](https://user-images.githubusercontent.com/1929460/33760023-6c520598-dc15-11e7-8738-c1208a6fe30b.png)
![screenshot_2](https://user-images.githubusercontent.com/1929460/33760026-6ee09004-dc15-11e7-8517-70f3ee167a48.png)
![screenshot_3](https://user-images.githubusercontent.com/1929460/33760031-71996348-dc15-11e7-8bab-4445520b5e4c.png)
![screenshot_4](https://user-images.githubusercontent.com/1929460/33760033-733fdb96-dc15-11e7-94fb-f7fd88391b82.png)

**Comment by graywolf336** [comment]
Duplicate of RocketChat/Rocket.Chat#7291
