### ISSUE TITLE
Hide Unread Room Status toggle hides mentions too

### ISSUE THREAD

**Issue by AndreiLopatenco** [RocketChat/Rocket.Chat.Electron#632]
## My Setup
- Operating System: macOS High Sierra 10.13.2
- App Version: 2.10.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Steps to Reproduce:

1. Join a room
2. Open notifications settings side panel
3. Set Hide Unread Room Status to Enabled

### Expected behavior:

I expect to not see an unread count on the room list and an icon badge with a counter **unless** I am mentioned in that room

### Actual behavior:
I do not see an unread count on the room list and an icon badge with a counter even when I am mentioned in that room.

### Server Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: macOS
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v4.8.4

If my expectations are wrong - can someone explain me how I can obtain what I'm trying to? 
Many thanks.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
