### ISSUE TITLE
[Windows App:Rocket.Chat+]New avatar won't be applied in my own's pc.

### ISSUE THREAD

**Issue by T-Motodate** [RocketChat/Rocket.Chat.Electron#634]
## My Setup
- Operating System: Windows 10 Home
- App Version: 2.10.1

## Description
At the windows app(the Rocket.Chat+).
New avatar, that uploaded in the "Avatar" pane in the my account section, won't be applied in my own's PC.
However, in the other PC's Rocket.Chat+, new avatar was applied.

### Steps to reproduce
1.Moves to "My Acount" section.
2.Moves to "Avatar" Pane in the left side bar.
3.Selects the image file, and click upload button.
4.Appears the message that applied the new avatar in green box.
5.However, new avatar won't be applied in my own pc. The old avatar is still applied.
6.After application reload or current server reload, new avatar won't be applied.

### Current Behavior
Additional, the change applied after few days.

### Expected Behavior
Avatar should be updated immediately in own pc's app.

**Comment by woulf** [comment]
Hello,
i have a user with a similar problem.

RocketChat Windows App: 2.15.0 
OS: Windows 10 Pro

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
