### ISSUE TITLE
Leaving private room loses the room

### ISSUE THREAD

**Issue by jarro2783** [RocketChat/Rocket.Chat.Electron#635]
## My Setup
- Operating System: Arch Linux
- App Version: 2.10.1

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description

If I am the last owner of a private room to leave, I get a warning saying that I can't leave the room without assigning a new owner, and app forgets that the room exists.

### Current Behavior

When I am the last to leave a private room I get a message saying that I have to assign the ownership of the room to someone else (which is expected), but then the room goes away forever. I can't find the room in the room list either.

I don't think that this is a server bug because I connected to the server with Chrome and was still able to access the room.

### Expected Behavior

I should see the room still in my room list since I am still a member of the room.

**Comment by jarro2783** [comment]
I also discovered that if I set the room to public in the web UI it comes back. I can then reproduce the exact problem again in the desktop app.

**Comment by geekgonecrazy** [comment]
Please open or locate an issue on the Rocket.Chat repo: https://github.com/rocketchat/rocket.chat/issues

This issue doesn't apply to the desktop client

**Comment by jarro2783** [comment]
This is *only* a bug on the desktop client, so I don't see how it doesn't apply.

**Comment by geekgonecrazy** [comment]
If you browse to your server via the website do you not get the same issue?  Based on the description I can't see how you wouldn't

**Comment by jarro2783** [comment]
No, the bug does not appear on the web UI, only the desktop client. In my follow up comment I stated that I can recover the room with the web UI.

**Comment by gdelavald** [comment]
Hey, we'll investigate the issue and check how we can solve that, if through a fix on the app or in the web ui.
Thanks!

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
