### ISSUE TITLE
Desktop: Red badge with dot ("."), when no new messages.

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat.Electron#638]
@seriyvolk83 commented on [Sun Dec 03 2017](https://github.com/RocketChat/Rocket.Chat/issues/9001)

When there are no new messages the app icon shows red badge with a dot ("."). This is really confusing. It should not show badge at all.

**Comment by jwallet** [comment]
i think RC tries to mimic slack behavior, and that's what they do when there is new activity in your channels but no one has mentioned you

**Comment by gdelavald** [comment]
@seriyvolk83 could you please add some images with the problem so we can troubleshoot it better?
Thanks!

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
