### ISSUE TITLE
Chromium Error ? -> Couldn't set selectedTextBackgroundColor from default ()

### ISSUE THREAD

**Issue by samgos** [RocketChat/Rocket.Chat.Electron#639]
`[19:22:52] Using gulpfile ~/Desktop/Rocket.Chat.Electron/gulpfile.js`
`[19:22:52] Starting 'bundle'...`
`[19:22:52] Starting 'less'...`
`[19:22:52] Starting 'environment'...`
`[19:22:53] Finished 'environment' after 48 ms`
`[19:22:53] Starting 'watch'...`
`[19:22:53] Finished 'watch' after 10 ms`
`[19:22:53] Finished 'bundle' after 568 ms`
`[19:22:53] Finished 'less' after 806 ms`
`[19:22:53] Starting 'build'...`
`[19:22:53] Finished 'build' after 25 μs`
`[19:22:53] Starting 'start'...`
`[19:22:53] Finished 'start' after 49 ms`
`Checking for update`
`2017-12-15 19:23:00.677 Electron Helper[56876:940134] Couldn't set selectedTextBackgroundColor from default ()`
`Update for version 2.11.0-develop is not available (latest version: 2.10.1, downgrade is disallowed.`

I can install the rocket.chat mac installer perfectly also to note, but when i try to build it from the source it won't work. Tried versions 2.11.1 , 2.10.1 and 2.10 all give the same error. I've updated chrome-driver and nothing either. 

Tried using npm and yarn, the dropscreen just hangs there and gives off this error. Any suggestions, I know there was afew with electron but i can't seem to get any of them to work. I tried 
`<style> ::selection { background: white; /* WebKit/Blink Browsers */ } </style>`
 in all of the .html files but nothing. It's a an error regarding user selection of text from what i read?

**Comment by samgos** [comment]
gave up

**Comment by jayprakashsah21** [comment]
@samgos, How did you solve the above issue? I am getting the same error in mac ios. Could you please help me to resolve the issue?

**Comment by samgos** [comment]
@jayprakashsah21 from what I know it's a chromium web error, unfortunately, I didn't peruse the project any further due to some circumstances. From what I remember it was because of text selection/highlighting that caused it to crash. 

Try this -> https://bugs.chromium.org/p/chromium/issues/detail?id=641509

Sorry I can't be any more help.
