### ISSUE TITLE
Incoming messages do not appear often

### ISSUE THREAD

**Issue by rex4539** [RocketChat/Rocket.Chat.Electron#642]
## My Setup
- Operating System: macOS 10.13.3 (17D25b)
- App Version: 2.10.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
1. Have Rocket Chat running in the background.
2. Leave it running for a while and start receiving messages in various channels.

### Current Behavior
Very often the messages do not appear and it seems like you have not received anything. Refreshing the server makes the messages appear.

### Expected Behavior
All incoming messages should appear immediately upon receiving.

**Comment by helderam** [comment]
I have the same problem.
I sugest have an option when new message comes, activet the application in foreground.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
