### ISSUE TITLE
Build native GUI clients

### ISSUE THREAD

**Issue by rex4539** [RocketChat/Rocket.Chat.Electron#644]
The current situation with the Electron ports appears convenient, I can understand, but performance is slooooowwww...

I propose native GUI clients using a modern, fast and cross platform language. I suggest the use of [Swift](https://swift.org/about/#swiftorg-and-open-source).

The result is a modern looking and responsive client with feature parity that runs on Linux, macOS and [Windows](https://github.com/apple/swift/blob/master/docs/Windows.md).

[Rocket Chat for iOS](https://github.com/RocketChat/Rocket.Chat.iOS) is already built natively with Swift so I don't see why you have to do extra work and use Electron since the code is already in Swift anyway.

**Comment by gdelavald** [comment]
Hey @rex4539, we are always open to contributions from the community. If you think this could be a good project, we can try and gather some contributors to work on it.
Thanks!
