### ISSUE TITLE
Though "Compact" view mode is set, when a user visit "Account Preference" view mode "Normal" is chose

### ISSUE THREAD

**Issue by loloiccl** [RocketChat/Rocket.Chat.Electron#648]
## My Setup
- Operating System: mac OS High Sierra
- App Version: 2.9.0

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

### Current Behavior

Though "Compact" view mode is set, when a user visit "Account Preference" view mode "Normal" is chose.

### Expected Behavior

"Compact" is chose.

**Comment by gdelavald** [comment]
Closing this as this is not related to Electron. Please check the [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) repository for more information.

**Comment by loloiccl** [comment]
Sorry for my mistake.
Thanks.

**Comment by gdelavald** [comment]
@loloiccl No problem, I moved the ticket to the appropriate repository [here](https://github.com/RocketChat/Rocket.Chat/issues/9476)
