### ISSUE TITLE
SRPMs missing from release 

### ISSUE THREAD

**Issue by bby-bishopclark** [RocketChat/Rocket.Chat.Electron#649]
## Description
RPM release does not include Source RPM

### Current Behavior
https://github.com/RocketChat/Rocket.Chat.Electron/releases shows binary RPM releases, but no Source-RPM

### Expected Behavior
I expected an SRPM to be present, with which one could quickly inspect the build process or rebuild the binary RPM.

**Comment by tassoevan** [comment]
At this time, there is no way to include a source RPM as `electron-builder` uses prebuilt binaries.

**Comment by bby-bishopclark** [comment]
Okay, so we admit that we can't validate the content of the binary RPM, then, which means we can't prove consistency.  Thanks.
