### ISSUE TITLE
Add screen sharing support

### ISSUE THREAD

**Issue by fabiogermann** [RocketChat/Rocket.Chat.Electron#65]
It would be great to have a desktop app that could share the screen.
(Like the chrome/firefox extension) (possible inspiration: https://github.com/maxogden/screencat)
##

**Comment by giray** [comment]
+1

**Comment by rchikballapur** [comment]
+1

**Comment by k2xl** [comment]
+1

**Comment by shellster** [comment]
Would really like to see this feature added.  The desktop application is the only application that consistently does webcam/voice calls well in my testing.  Unfortunately the screenshare feature isn't there, so we still end up going back to the buggy webapp versions.

**Comment by litewhatever** [comment]
+1

**Comment by tuudik** [comment]
:+1:

**Comment by miscs** [comment]
+1 especially users ask what they do wrong having the screen share button and not being able to use this very important feature.

thanks!

**Comment by fabiogermann** [comment]
The main difference between other chat solutions currently available and rocketchat is the working screenshare functionality - it is basically the only issue preventing us from switching to RocketChat. Besides that it seems to me that having that button without the working functionality is somewhat a bug.

**Comment by goobersmooch** [comment]
+1

**Comment by Againstreality** [comment]
+1

**Comment by cahi** [comment]
+1

**Comment by skizzors** [comment]
+1 !!!

**Comment by christig** [comment]
+1! echoing @fabiogermann

**Comment by artifactdev** [comment]
+1

**Comment by philinx** [comment]
+1

**Comment by RomanKisilenko** [comment]
+1

**Comment by shellster** [comment]
May want to consider partnering with a service like talky.io for this, since they've already done all the heavy lifting.

**Comment by sebastientaggart** [comment]
+1

**Comment by engelgabriel** [comment]
This can help https://github.com/maxogden/screencat

**Comment by amenk** [comment]
Ehrm, why don't we use meet.jit.si which has screen sharing, just in like in the browser app ?

**Comment by hartois** [comment]
Fedora 26 x86_64
rocketchat-2.9.0-538.x86_64
screensharing does not work - request extension

**Comment by dxas90** [comment]
+1
