### ISSUE TITLE
Meteor is undefined

### ISSUE THREAD

**Issue by samrg472** [RocketChat/Rocket.Chat.Electron#652]
## My Setup
- Operating System: Mac 10.13.2
- App Version: 2.10.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I receive a `Server Failed to Load` error from this issue. The console reports the following log:

```
/Applications/Rocket.Chat+.app/Contents/Resources/app.asar/app/public/preload.js:59 Uncaught ReferenceError: Meteor is not defined
    at /Applications/Rocket.Chat+.app/Contents/Resources/app.asar/app/public/preload.js:59
(anonymous) @ /Applications/Rocket.Chat+.app/Contents/Resources/app.asar/app/public/preload.js:59
```

**Comment by gdelavald** [comment]
@samrg472 Hey, this is somewhat expected when the server failed to load since the server is the one who provides the Meteor reference. Did this cause any other issue or a reload solved it?

**Comment by samrg472** [comment]
It only seems to be an issue on this particular server for me: https://steemit.chat
The server on the website works without issues: https://open.rocket.chat

**Comment by samrg472** [comment]
I'm closing this as this is most likely due to Cloudflare blocking the app from accessing the server.
