### ISSUE TITLE
Hidden Character Count when Using Chinese Input Method with Radicals

### ISSUE THREAD

**Issue by vertimus** [RocketChat/Rocket.Chat.Electron#653]
## My Setup
- Operating System: MacOS 10.13.1
- App Version: 0.60.4

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Using Chinese input methods with radicals (such as MacOS Bopomofo, Boshiamy, etc), hitting backspace to correct/delete all radicals before a complete Chinese character is built will appear to clear all radicals but in fact leaves a hidden character in chat box. When a message with a leftover character is sent, it appears fine on MacOS or the iOS native app, but on Windows clients the extra, hidden character will show up as a symbol.
![01](https://user-images.githubusercontent.com/35421366/35261411-f8988258-004a-11e8-9577-10bc6b72c28d.png)

When using the browser version (with Safari) this issue is not observed.

### Current Behavior

In the typing box, if you move the cursor manually by keyboard, where there are leftover radicals will count as additional characters and requires multiple arrow keys to move over to the next word since these hidden characters are taking up space.

### Expected Behavior

When backspacing to clear radicals, all radicals should actually be deleted and not forming hidden characters which result in abnormal message display.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
