### ISSUE TITLE
Start minimized?

### ISSUE THREAD

**Issue by kviolka** [RocketChat/Rocket.Chat.Electron#654]
How can I start the rocketchat client on Linux in minimized to tray mode?
thank you! :)

**Comment by gdelavald** [comment]
Hey @kviolka I don't think there is an option for this at the moment. If you want to work on this please fork and open a PR for us 😄  Thanks!

**Comment by ArchitaDesai** [comment]
@gdelavald, I would like to work on this issue. Thanks :)

**Comment by ArchitaDesai** [comment]
If you wanna start it minimized to tray mode, then you need to close the app while it's minimized, @kviolka.
Is that right, @gdelavald?

**Comment by oneiros-de** [comment]
IMHO this is a security problem, as (at least on KDE) the client starts in the foreground and *grabs the focus*, thus potentially leaking passwords.

**Comment by asheroto** [comment]
Wow I'm surprised this hasn't been added. Nearly every communication app has this option. Discord, Signal, Facebook Messenger, Telegram, Slack, etc.
