### ISSUE TITLE
Files preview and download not working

### ISSUE THREAD

**Issue by agustinventura** [RocketChat/Rocket.Chat.Electron#656]
## My Setup
- Operating System:
Windows 7 Professional Service pack 1
- App Version:
2.10.1

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description
Files upload works but preview and downloads don't. 

### Current Behavior
Whenever a file is uploaded to the server, preview and download doesn't work, see screenshot below:
![preview and download in rocket chat](https://user-images.githubusercontent.com/490045/35323759-f8f5bc12-00ee-11e8-880c-6f3ca9ffff33.png)

But, it works in web browser:
![preview and download in web browser](https://user-images.githubusercontent.com/490045/35323806-2130b4ac-00ef-11e8-9107-e0cd8b15ca98.png)

Besides, when you download the file using Rocket.Chat+ it is always corrupted, but everything is fine using the web browser.

### Expected Behavior
Rocket.Chat+ behavior should be the same as web browser.

Thank you!

**Comment by gdelavald** [comment]
Hey @agustinventura, is this from the open.rocket.chat server? Or are you testing on a private one?
Thanks for reporting this.

**Comment by agustinventura** [comment]
hi @gdelavald this is a private server. 
Our current configuration is Rocket.Chat 0.60.4 running on Node.js 8.9.3 with MongoDB 3.6 on a different server. Both servers are Debian 8.9.
We are storing files on FileSystem (instead of GridFS) and seems to be ok there, that's why I suspect of a client issue.
Thanks for this wonderful tool :)

**Comment by agustinventura** [comment]
Hi @gdelavald, any news about this? Is something related to our deployment? Has anyone been able to reproduce it?
Thanks!

**Comment by mbendix** [comment]
Are there any updates?
Similar issue here: the preview and download of uploaded files dos not work.
Self hosted as Docker Container (rocket.chat:0.71.0) and mounted Docker volume on /app/uploads

**Comment by tassoevan** [comment]
@mbendix Only fails on the desktop app? Or via browser interface too?

**Comment by mbendix** [comment]
@tassoevan both: via browser i got a HTTP 403 and on the Mac App it shows only the "Save as" dialog, but nothing happens when you try to save it. I'm using the local file storage instead of GridFS. I can also see the uploaded files in /app/upload

**Comment by tassoevan** [comment]
@mbendix Your issue is related to the Rocket.Chat server; I think I've seen some similar reports there. Please, could you open a new issue in the [server repository](https://github.com/RocketChat/Rocket.Chat)?
