### ISSUE TITLE
macOS build missing for 2.10.2

### ISSUE THREAD

**Issue by rex4539** [RocketChat/Rocket.Chat.Electron#658]
https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.10.2

https://rocket.chat/download

**Comment by gdelavald** [comment]
@rex4539 Thanks for the report, we are running the build process again as it seems that Travis had a problem uploading the MacOS artifacts.

**Comment by jbkalla** [comment]
@gdelavald, thanks for that answer.  I was looking as well.  :)

**Comment by gdelavald** [comment]
Hey folks, sorry about the delay on this. You can find the macOS installer [here](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.10.2) or directly in the [rocket.chat/download](https://rocket.chat/download) page
