### ISSUE TITLE
Node.dll insecure version

### ISSUE THREAD

**Issue by JorisVanEijden** [RocketChat/Rocket.Chat.Electron#659]
## My Setup

 - Windows 10
 - Rocket.Chat+ 2.10.2

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Windows version comes with node.dll v7.9.0 which has a security issue (https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/)
Fixed version is 7.10.1

#### Current Behavior

Node version with known security vulnerabilities used.

#### Expected Behavior

Node version with no known security vulnerabilities used.

## Disclaimer
I am not personally aware of specific ways to abuse this vulnerability. I just get alerts from our security software when users install Rocket.Chat.

**Comment by gdelavald** [comment]
Thanks @JorisVanEijden I'll check the necessary updates to fix this.

**Comment by engelgabriel** [comment]
@JorisVanEijden can you try the version 2.10.3?

**Comment by JorisVanEijden** [comment]
2.10.3 ships with 7.9.0 too. 😞 
2.10.4 contains node 8.2.1 👍

**Comment by engelgabriel** [comment]
@JorisVanEijden please try version `2.10.5`

**Comment by JorisVanEijden** [comment]
2.10.5 also has node 8.2.1
