### ISSUE TITLE
Downloading uploads causes a second window to open that doesnt close after download

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat.Electron#66]
Downloading uploads causes a second window to open that doesnt close after download

![2015-12-22 10_34_34-microsoft edge](https://cloud.githubusercontent.com/assets/11317247/11958074/8b3e84f0-a8bd-11e5-9b00-d55fe594778c.png)

**Comment by graywolf336** [comment]
This was fixed by #73.
