### ISSUE TITLE
Reduce the delay when opening a channel for the first time?

### ISSUE THREAD

**Issue by martinvonwittich** [RocketChat/Rocket.Chat.Electron#660]
## My Setup
- Operating System: Ubuntu 17.10
- App Version: 2.10.2

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When opening a channel for the first time since starting the app (also when opening it after not having opened it for some time, I believe), Rocket.Chat takes 1-2 seconds to load the channel while displaying a loading animation. IMHO this i pretty annoying. Could this delay be reduced, e.g. by loading the channels in the background?

### Current Behavior

Opening a channel for the first time takes 1-2 seconds while it is loading.

### Expected Behavior

Channels should load instantly.

**Comment by ggazzo** [comment]
we have been working on this issue on the main repo ;)
