### ISSUE TITLE
macOS Text Replacement not working on the desktop app

### ISSUE THREAD

**Issue by auyongtc** [RocketChat/Rocket.Chat.Electron#665]
## My Setup
- Operating System: macOS 10.13.3
- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
macOS (like iOS) have this Text Replacement feature on the OS-level where the user can specify custom text replacement that will be replaced when the keyword is typed in any textbox. For example, user can type "omw" (without quotes) and it will be replaced with "On my way!"

### Current Behavior
Text replacement doesn't work on any user-defined keywords on the desktop app on macOS, even on the latest version. Nothing happens to the text.

### Expected Behavior
Text replacement should happen immediately after typing user-defined keywords on the desktop app on macOS. 
Testing on the Rocket.Chat web app displayed the expected behavior. Testing on the iOS Rocket.Chat app displayed the expected behavior too.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
