### ISSUE TITLE
TextBox is missing after Zoom Out the view

### ISSUE THREAD

**Issue by RandyHBH** [RocketChat/Rocket.Chat.Electron#668]
## My Setup
- Operating System: Mac os Sierra 10.12.6
- App Version: 2.10.5

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

![screen shot 2018-02-16 at 10 38 05 am](https://user-images.githubusercontent.com/14900734/36315959-9ad12c9e-12fe-11e8-8d02-a839faead1db.png)

After press Ctrl + - for Zoom out the view, the Textbox disappears and I can't see it anymore

### Current Behavior

the Textbox disappears and I can't see it anymore

### Expected Behavior

the Textbox should keep his place

**Comment by jeeringsole** [comment]
I am also experiencing this same issue. When zooming in and then zooming back out the text box vanishes. 

Mac version High Sierra v 10.13.3

**Comment by gdelavald** [comment]
Thanks for the report guys, we'll be looking at a fix for this issue in the next version.
I'll be closing the issue in favour of #564. Please continue any discussion on the other issue.
