### ISSUE TITLE
Custom oauth not working in desktop client

### ISSUE THREAD

**Issue by Hupka** [RocketChat/Rocket.Chat.Electron#669]
## My Setup
- Operating System: Windows / MacOS
- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When using the RocketChat+ desktop client I cannot the a custom oauth provider, because the provider's login page is not presented and the javascript console throws `"Uncaught ReferenceError: Meteor is not defined"` in file `preload.js` in `line 59` of the RocketChat+ app.

Blank popup when clicking "authenticate using custom oauth"
![image](https://user-images.githubusercontent.com/6577198/36386562-693506d4-1596-11e8-9295-92a5a2e80c25.png)

Javascript logs from RocketChat+ developer console:
![image](https://user-images.githubusercontent.com/6577198/36386495-350154f8-1596-11e8-8a40-3e0539095b94.png)

### Steps to Reproduce:

1. Setup RocketChat (Snaps) and custom Oauth2 provider and get it up and running using the webbased access ✔️ 
2. Download and install RocketChat+ version 2.10.5
3. Login using custom oauth2 provider

### Current Behavior
Window popps up but no login website is shown - page is left blank

### Expected Behavior
Popup window showing up displaying oauth-provider's login page to user.

## Relevant logs:

Console logs from RocketChat+:
```
Uncaught ReferenceError: Meteor is not defined
    at C:\Users\UN\AppData\Local\Programs\rocketchat\Rocket.Chat+\resources\app.asar\app\public\prelo…:59
(anonymous) @ C:\Users\UN\AppData\Local\Programs\rocketchat\Rocket.Chat+\resources\app.asar\app\public\prelo…:59
```

This logs point to `preload.js` file in the RocketChat+ client. The code snipped there is missing a defined Meteor variable -- no imports on top the file regarding meteor.

```javascript
window.addEventListener('load', function () {
    Meteor.startup(function () { //<<<< this line is highlighted
        Tracker.autorun(function () {
            const siteName = RocketChat.settings.get('Site_Name');
            if (siteName) {
                ipcRenderer.sendToHost('title-changed', siteName);
            }
        });
    });
    userPresenceControl();
})
```

Another error is thrown which I did not yet investigate:
```
Uncaught TypeError: Cannot read property 'Constructor' of undefined
RESTLoginHelper.js:114 
    at RESTLoginHelper.js:114
    at RESTLoginHelper.js:114
    at Object.execCb (requirejs-2.1.14-min.js:29)
    at Z.check (requirejs-2.1.14-min.js:18)
    at Z.enable (requirejs-2.1.14-min.js:23)
    at Object.enable (requirejs-2.1.14-min.js:27)
    at Z.<anonymous> (requirejs-2.1.14-min.js:23)
    at requirejs-2.1.14-min.js:8
    at v (requirejs-2.1.14-min.js:7)
    at Z.enable (requirejs-2.1.14-min.js:22)
(anonymous) @ RESTLoginHelper.js:114
(anonymous) @ RESTLoginHelper.js:114
execCb @ requirejs-2.1.14-min.js:29
check @ requirejs-2.1.14-min.js:18
enable @ requirejs-2.1.14-min.js:23
enable @ requirejs-2.1.14-min.js:27
(anonymous) @ requirejs-2.1.14-min.js:23
(anonymous) @ requirejs-2.1.14-min.js:8
v @ requirejs-2.1.14-min.js:7
enable @ requirejs-2.1.14-min.js:22
enable @ requirejs-2.1.14-min.js:27
(anonymous) @ requirejs-2.1.14-min.js:23
(anonymous) @ requirejs-2.1.14-min.js:8
v @ requirejs-2.1.14-min.js:7
enable @ requirejs-2.1.14-min.js:22
enable @ requirejs-2.1.14-min.js:27
(anonymous) @ requirejs-2.1.14-min.js:23
(anonymous) @ requirejs-2.1.14-min.js:8
v @ requirejs-2.1.14-min.js:7
enable @ requirejs-2.1.14-min.js:22
enable @ requirejs-2.1.14-min.js:27
(anonymous) @ requirejs-2.1.14-min.js:23
(anonymous) @ requirejs-2.1.14-min.js:8
v @ requirejs-2.1.14-min.js:7
enable @ requirejs-2.1.14-min.js:22
init @ requirejs-2.1.14-min.js:17
(anonymous) @ requirejs-2.1.14-min.js:26
```

**Comment by icereed** [comment]
+1 same for me

**Comment by jorgecoca** [comment]
Experiencing the same issue.

**Comment by EddEdw** [comment]
Hey @icereed and @jorgecoca, what is your setup? Are you also working behind a corporate (non-transparent) proxy?

**Comment by jorgecoca** [comment]
Yep, that is exactly the issue

**Comment by EddEdw** [comment]
Okay, I reposted this issue on Rocket.Chat server because I think the issue sits in the Meteor interface provided by the server. Let's see if this gets more attention on the main project. This really sucks...

**Comment by icereed** [comment]
Yep, http proxy. Thanks for your action.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
