### ISSUE TITLE
links open empty browser

### ISSUE THREAD

**Issue by motherboard1999** [RocketChat/Rocket.Chat.Electron#672]
## My Setup
- Operating System: macOS 10.13.3
- App Version: 2.10.5

- [ X ] I have tested with the latest version
- [ - ] I can simulate the issue easily

## Description
If I click on a URL inside a chat, the browser opens a empty site.
A few weeks ago all worked perfect, but now it doesn't.

**Comment by russmack** [comment]
I have the same issue.  It comes and goes with no apparent reason.  Last week my links were opening empty chrome windows, yesterday they were working correctly, today they're back to opening empty windows.

**Comment by gdelavald** [comment]
We are investigating the issue to be certain if this is a bugfix needed on our application or if this bug is coming from electron or another third party library. 
Thanks for the reports and for your patience.

**Comment by vassyz** [comment]
This seems to happen when Chrome releases a new update. Restarting the browser will install the update and fix this issue. I'm not sure it's related to Rocket.Chat.
