### ISSUE TITLE
Impossibility to leave the fullscreen with jitsi post-message in case if you leave the videocall while fullscreen

### ISSUE THREAD

**Issue by msva** [RocketChat/Rocket.Chat.Electron#673]
## My Setup
- Operating System: Gentoo 2017 (Applicaton installed from amd64 deb package )
- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![Screenshot](https://i.imgur.com/81WwNVA.png)
Steps to reproduce:
1) Start Video call
2) Click "Full screen" Button
3) Click "leave" button (without exiting fullscreen)
4) You're here. You can't back to chat until perform "Reload server" on the server icon.

### Current Behavior

You see the jitsi message and can't back to the chat
### Expected Behavior

Possibility to still exit the fullscreen and back to the chat.

**Comment by dhayab** [comment]
We're also experiencing the same issue.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
