### ISSUE TITLE
The attached file loses the extension if it is renamed when it is downloaded

### ISSUE THREAD

**Issue by criduvero** [RocketChat/Rocket.Chat.Electron#681]
## My Setup
- Operating System: Windows 10 1709 16299.248
- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When downloading an attached file, the File Name input doesn't show the extension, the Type input shows 'All Files', so, if I change the filename, it saves without extension.

Web version hasn't the problem, only Eectron. Thanks

![image](https://user-images.githubusercontent.com/13077575/37062234-d75142bc-2163-11e8-800c-bfb6a1418453.png)

### Current Behavior

If I change the attached filename, it saves without extension.
### Expected Behavior

Change the file name normally

**Comment by GoetheG** [comment]
When I see all the open source software it gets me thinking why some of those companies do not work together. For example Nextcloud and Rocket.Chat. It diesn’t have to be Nextcloud, that is just an example. ownCloud is fine by me. And also Rocket.Chat.

**Comment by criduvero** [comment]
Fixed on 0.64.2 server version. At least it shows the file extension when downloading:
![image](https://user-images.githubusercontent.com/13077575/40499599-0c00b688-5f48-11e8-9945-f651c384478f.png)
