### ISSUE TITLE
Release latest version to Snap Store

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.Electron#682]
Currently the latest version for `rocketchat-desktop` is 2.7.0:

```
ubuntu@ubuntu:~# sudo snap search rocketchat-desktop
Name                Version  Developer   Notes  Summary
rocketchat-desktop  2.7.0    rocketchat  -      Rocket.Chat+
```

**Comment by bittner** [comment]
Fun fact: The [Snapcraft community](https://rocket.ubuntu.com/channel/snapcraft) seems to use RocketChat for communication. Maybe they want to help maintaining the snap.

See also: [Auto-build and publish software
for any Linux system or device](https://build.snapcraft.io/)

**Comment by tassoevan** [comment]
Hey @geekgonecrazy, do you know how can we automate the snap publishing?

I was expecting electron-builder to do this for us, but I can't find anything in its docs, and even the building step is somewhat buggy (I'm considering doing [this](https://github.com/electron/electron/blob/master/docs/tutorial/snapcraft.md)).

**Comment by geekgonecrazy** [comment]
Yeah basically when I was looking at it... Electron builder wasn't ready to handle it yet.  So I had to do a build and then snap up manually.

But.. it might be easiest for now to take the .deb already reliably produced and snap it up.  Just like the doc you linked suggests

**Comment by extraymond** [comment]
Hi! Any updates on this. The snap released in github seems to operate normally. Would be nice to receive automatic updates from the snap channel.

As for CI/CD, you can check out travis support for [snapcraft](https://tutorials.ubuntu.com/tutorial/continuous-snap-delivery-from-travis-ci).

**Comment by tassoevan** [comment]
Done.
