### ISSUE TITLE
Clicking a link to an embedded layout URL breaks display

### ISSUE THREAD

**Issue by itskenny0** [RocketChat/Rocket.Chat.Electron#683]
## My Setup
- Operating System: Ubuntu 18.04
- App Version: latest

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Send yourself a message containing a link to a rocketchat channel with embedded layout, e.g.:
https://my.rocketchat.instance/channel/support?layout=embedded
Now click this link within Rocket.Chat.Electron.

### Current Behavior
The embedded layout page will display, hiding the sidebar, but there is no way to exit back to the regular sidebar layout mode.

### Expected Behavior
The embedded layout page should open in the browser or there should be a way to exit it without deleting and readding the Rocket.Chat instance.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
