### ISSUE TITLE
Is the windows-app signed?

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat.Electron#684]
As per one of our users, he couldn't install the Windows-version since it was not signed. Also, it's not available in the all-time-favorite-best-store windows-store.

Since I'm on Mac I cannot verify that, so leaving it as a simple question: Is the current version of the windows-app signed?

**Comment by gdelavald** [comment]
@mrsimpson currently we do not sign the Windows Version. However, the plans for signing it and releasing on Windows Store are on our short term plans.

**Comment by GoetheG** [comment]
Very good, looking forward to signing!
