### ISSUE TITLE
iOS videos do not play

### ISSUE THREAD

**Issue by boblmartens** [RocketChat/Rocket.Chat.Electron#687]
## My Setup
- Operating System: macOS 10.13.3
- App Version: 2.10.5

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description
Video uploaded from iOS device does not play on desktop app or in a desktop browser. The video is loaded up through the Rocket.Chat+ app, and playback works in the iOS app, but it does not work in a desktop browser not the Rocket.Chat+ desktop app.

### Current Behavior
1) upload video from iOS app
2) see the ability to download, but not play

### Expected Behavior
1) upload video from iOS app
2) can play the video directly in the desktop app or the browser without needing to download the video first

**Comment by gdelavald** [comment]
Thanks for the feedback, we'll look into what is going on, most likely this is an encoder issue or the format is not in the accepted list for the web app.
@boblmartens have you tested this in the web app through a web browser? If this happens to the web as well we should move this issue to the official Rocket.Chat repository.

**Comment by boblmartens** [comment]
I just tested it on Safari on macOS 10.3.3 and have the same issue here as in the desktop app on the same device.

**Comment by helmut72** [comment]
Have also the same problem. Using all latest version from today (iOS, Rocket Server, iOS App, macOS, macOS client). Files are stored in file system. It's not possible to enable/disable any proxy in the server for file system storage. Only in WebDAV, which I don't use.

- playing Video in Desktop App (Mac) and Browser (Safari) works
- playing Video on iOS (iPhone, iPad) doesn't work

Video was taken from iPhone, it's under 2MB. Max file size is 100MB

**Comment by xgdgsc** [comment]
@gdelavald I tested it on web browser, also doesn' t work.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
