### ISSUE TITLE
Show download status

### ISSUE THREAD

**Issue by thiesschneider** [RocketChat/Rocket.Chat.Electron#688]
Hey there,

I would love to have something like a progressbar for the file I download in the Electron app also.
It would also be nice to open the downloaded file or the folder where the file is stored.

Thanks for this great app... you rock!

**Comment by abicur** [comment]
Progress bar is very needed. Sometimes users may have a slow internet connection. For example a few day ago I tried to download file (60mb) on 4g connection. After I clicked to download button then download is started and there was only one way to detect that download is finished - open downloads folder and refreshing a file size (and this is in the case that I know it size).

**Comment by ggazzo** [comment]
please check if the download page cover all your needs
