### ISSUE TITLE
Uploading PSD files not working.

### ISSUE THREAD

**Issue by DCauldy** [RocketChat/Rocket.Chat.Electron#690]
## My Setup
- Operating System: Mac OS 10.13.3
- App Version: 0.62.1

- [x ] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description

I am trying to use the file upload for .psd files to share with our team. I can see that the upload was successful, but it does not put the file within the chat history. I can see the file in the file list within the conversation, but am unable to down the files.

Other file types work just fine. I have the upload types as empty to allow all, it just doesn't like .psd files.

How can we resolve this issue on our end.

### Expected Behavior

Uploading a .psd file should work as a normal file upload.

**Comment by tassoevan** [comment]
I'm closing it since it's a Rocket.Chat core (server) problem.
