### ISSUE TITLE
Notification alert preference for toast popup should also affect taskbar blink

### ISSUE THREAD

**Issue by zaus** [RocketChat/Rocket.Chat.Electron#693]
## My Setup
- Operating System: Win10
- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

* Chat room / channel preference set to "Mentions only"
* User in chat mentions me
  * Notification popup ("toast") behaves appropriately - does show
  * Taskbar icon (not tray icon) should blink
* Another user types plain text in chat
   * Notification popup ("toast") behaves appropriately - doesn't show
  * Taskbar icon (not tray icon) blinks anyway

### Expected Behavior

* Chat room / channel preference set to "Mentions only"
* User in chat mentions me
  * Notification popup ("toast") behaves appropriately - does show
  * Taskbar icon (not tray icon) should blink
* Another user types plain text in chat
  * Notification popup ("toast") behaves appropriately - doesn't show
  * Taskbar icon (not tray icon) *should not blink*

**Comment by zaus** [comment]
Other "blinking" issues? #628 #618

**Comment by brandonanderson20** [comment]
Having no blinking really starting me to miss a lot of messenges

**Comment by ankar84** [comment]
My users ask for opposite option - they want to taskbar icon always blink on any new message in users channels if Desktop Notification preferences set to All messages.
We are currently on 2.17.9 and taskbar icon blinks only on mentions and DM.
@tassoevan please take a look at that feature

**Comment by xgdgsc** [comment]
Or just separate the tray icon setting.

**Comment by jeanfbrito** [comment]
Hello, we will be tracking the blinking icon feature request here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2525
I will be closing this issue because there are duplicated ones.
