### ISSUE TITLE
Sidebar keeps blank in "last activities" mode

### ISSUE THREAD

**Issue by chabbster** [RocketChat/Rocket.Chat.Electron#694]
Environment:
Windows 10 Pro Workstations with Rocket.Chat Client Version 2.10.5 installed. Server version 0.60.4

After the last client update, when the user had selected "Sort by Activity" in the Sidebar Channel List Mode setting, no contacts will be listed in the sidebar. When the user enters something in the search field, contacts will appear.
If you change the mode to "Unread Rooms Mode", everything is fine.

Users with Client Version for example 2.5.0 have no problems.

**Comment by chabbster** [comment]
![rocket-chat-bug-2-10-5](https://user-images.githubusercontent.com/6264248/37831159-c8ebf962-2ea4-11e8-8206-2827b897a643.png)

**Comment by gdelavald** [comment]
@chabbster Hey, thanks for the report. This issue was fixed on the web client, will probably be included in the next release, please check your server version and update accordingly.
