### ISSUE TITLE
More intrusive notifications

### ISSUE THREAD

**Issue by ftoledo** [RocketChat/Rocket.Chat.Electron#695]
I research if is possible to get more "intrusive" notificacions for the desktop client (at windows OS for now).

    Permanent/Sticky popup notifications.. (just stay visible until user get click)
    Flash icon / on bottom panel/toolbar
    Popup the main window?

Or some else.

The idea is to ensure to user must be notified even if leave and back from the computer for some little time.
thanks!

**Comment by ged-nn** [comment]
+1
Permanent/Sticky popup notifications.. (just stay visible until user get click)

**Comment by tassoevan** [comment]
> Permanent/Sticky popup notifications.. (just stay visible until user get click)
As I discovered when trying to implement permanent notifications on Windows, this need to be some kind of custom undecorated window like https://github.com/blainesch/electron-notifications#introduction.

> Flash icon / on bottom panel/toolbar
What do you mean by "flash"?

> Popup the main window?
It can be activated via `Window > Show on unread messages`.

All these features depend on implementing a functional (and already planned) Preferences screen.

**Comment by ged-nn** [comment]
In Windows 10 not activate window application. Only blinked in task panel.

**Comment by henit-chobisa** [comment]
According to me, I think that the issue has been resolved, please try updating to the latest version...

These are the PRs that fixed this issue, please go through these and consider **closing** the issue.
https://github.com/RocketChat/Rocket.Chat.Electron/pull/2122
https://github.com/RocketChat/Rocket.Chat.Electron/pull/2465
