### ISSUE TITLE
System Tray Icon Issues in KDE

### ISSUE THREAD

**Issue by XecKiE** [RocketChat/Rocket.Chat.Electron#696]
Good afternoon,

I have some issues with the system tray icon, that were not fixed by the previous issues #625 and #44 .

## My Setup
- Operating System: Kubuntu 16.04 / Kubuntu 16.10
- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
There are two issues :
- The system tray icon is truncated
- The left clic has no effect : in the issue #44 it was told that it should be the same as right clic, but it's not.

This can be fixed as told in #625 by using the Unity or Gnome version : `env XDG_CURRENT_DESKTOP=GNOME rocketchat`, but it's kind of a hack, and it doesn't work for a new user, or with the desktop launcher.
In addition I noticed that by starting the application this way, the browser used to open link is not the default browser of my system, which is kind of annoying. I guess it use the gnome default browser, but as gnome is not installed I have no idea where this information is fetched

**Comment by rodrigondec** [comment]
Same here

# My Setup
- Operating System: Kubuntu 16.04 / Kubuntu 16.10
- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

**Comment by tassoevan** [comment]
@XecKiE Still truncated in 2.14.3?

**Comment by XecKiE** [comment]
Yes, it's still truncated, and the solution proposed in #625 doesn't work anymore : with it the icon become blurry, as shown here :
![screenshot_20181119_101947](https://user-images.githubusercontent.com/2796399/48725264-e97f8f00-ec2b-11e8-8845-7d4673b4b8d8.png)

As for the solution proposed by @rodrigondec , it doesn't work on Kubuntu (the package libappindicator3-1 was already installed).

**Comment by tassoevan** [comment]
I think I'll have to guess a size for the icon based on `XDG_CURRENT_DESKTOP`. It's an awful solution, but tray icons in Linux are a mess and I'm glad we're able to render these icons on-the-fly right now. [I'm using 22 pixels now](https://github.com/RocketChat/Rocket.Chat.Electron/blob/8edfe345e24b1e7f39addda24bb80b449db5c312/src/background/tray.js#L13) due to Ubuntu's Gnome.

**Comment by tassoevan** [comment]
I'm postponing the resolution of this issue since it depends of a Chromium patch not present in the newest Electron versions yet.

**Comment by andy-partington** [comment]
I have issues with the snap of it with the tray icon too, not sure if you want a separate issue or to add to here. This is under Solus with KDE, but also had similar issue running on Ubuntu Mate but I'm afraid I didn't take a screen shot.

![screenshot_20181121_212935](https://user-images.githubusercontent.com/968384/48869343-c80dd700-edd4-11e8-8bec-25b3bee34d5a.png)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by SDAdham** [comment]
hello @jeanfbrito i'm on opensuse tumbleweed kde, and i have the same issue (i just installed rocket.chat)

**Comment by jeanfbrito** [comment]
> hello @jeanfbrito i'm on opensuse tumbleweed kde, and i have the same issue (i just installed rocket.chat)

Thanks! I will reopen this and take a look on the future

**Comment by SDAdham** [comment]
Sorry @jeanfbrito i later discovered that there was a button that I needed to click to tick it and enable the tray icon, it was hidden under the "view", tbh, this checkbox is generally useless considering that who wouldn't want tray icon

![Screenshot_20220119_193620](https://user-images.githubusercontent.com/11182824/150093942-e35bb189-f9db-4fdf-b57f-cee627a9433e.png)

**Comment by jeanfbrito** [comment]
> Sorry @jeanfbrito i later discovered that there was a button that I needed to click to tick it and enable the tray icon, it was hidden under the "view", tbh, this checkbox is generally useless considering that who wouldn't want tray icon. it should be enabled by default. Even when it was off, if i close rocket chat, it would still stay in the background even the tray icon wasn't there, i had to kill the process to start it up again and bring up the window.
> 
> ![Screenshot_20220119_193620](https://user-images.githubusercontent.com/11182824/150093942-e35bb189-f9db-4fdf-b57f-cee627a9433e.png)

The default is enabled. Maybe if you was using a old version it didnt catch the new default value.
I will take a look in closing the window on linux, how its working, but if the menu bar is enabled, I think that it will stay on background to the notifications work.

**Comment by SDAdham** [comment]
@jeanfbrito , short answer is nope

details: the operating system is brand new (installed 2 days ago), I came in here after installing rocket.chat via snap and being inable to find tray icon to bring it up or reopen it by accessing it from the apps menu (because it's already running process), i had to kill it in order to be able to launch it and see the window.

**Comment by SDAdham** [comment]
Thank you for all the help @jeanfbrito :+1:
