### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by capecape** [RocketChat/Rocket.Chat.Electron#697]
## My Setup
- Operating System: openSUSE Leap 42.3
- App Version: rocketchat-2.10.5-686.x86_64

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Trying to install latest version I am experiencing the following error:
### Current Behavior
`zypper install ./rocketchat-2.10.5.x86_64.rpm `
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libXScrnSaver needed by rocketchat-2.10.5-686.x86_64
 Solution 1: do not install rocketchat-2.10.5-686.x86_64
 Solution 2: break rocketchat-2.10.5-686.x86_64 by ignoring some of its dependencies
However it is installed:
No update candidate for 'libXScrnSaver-devel-1.2.2-13.3.x86_64'. The highest available version is already installed.
### Expected Behavior
I should get installed.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
