### ISSUE TITLE
PDF file transferring corruption

### ISSUE THREAD

**Issue by drweb86-work** [RocketChat/Rocket.Chat.Electron#700]
## My Setup
- Operating System: Windows 10x64
- App Version: 2.10.5

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
1. Take PDF file.
2. Press on contact
3. Drag and Drop file to Contract
4. Send

### Current Behavior
 After loading of file on other client it is
a. Locked
b. Contains invalid data.

### Expected Behavior
File should not be locked after download completion. File content should not be corrupted.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
