### ISSUE TITLE
Could you please use Windows Notifications API for notifications about messages

### ISSUE THREAD

**Issue by drweb86-work** [RocketChat/Rocket.Chat.Electron#702]
This API can be easily configured by user and all messages of certain types can be easily disabled

**Comment by gdelavald** [comment]
This would require a refactor on our notifications, it's doable, might be in the roadmap when we focus on the Windows Store features. Thanks for your suggestion!

**Comment by angelorodem** [comment]
Current notifications are easy to overlook, the taskbar icon should blink, it would help a lot.

**Comment by tassoevan** [comment]
Duplicate of #775.
