### ISSUE TITLE
Order Contacts in Direct Messages Group by Last Message Date

### ISSUE THREAD

**Issue by drweb86-work** [RocketChat/Rocket.Chat.Electron#705]
In a company i have huge amount of contacts with whom im contacting rarely.

Could you please make by default order of Direct Messages by Last Message date? So whenever i open chat i will see without scrolling who wrote me and people with whom i talked recently.

Could you please also add fuzzy string search for contact names on the right of Direct Messages which will search for contact names and then by message archive.

**Comment by gdelavald** [comment]
@drweb86-work you can order the contacts list by Last Message through the UI. These kind of suggestions are more suited for the Rocket.Chat main [repository](https://github.com/RocketChat/Rocket.Chat). Make sure to search for similar suggestions before posting it in that repo.
