### ISSUE TITLE
[BUG] notification indicator should not signal when group messages are unread

### ISSUE THREAD

**Issue by theorenck** [RocketChat/Rocket.Chat.Electron#707]
@bizzbyster commented on [Wed Mar 21 2018](https://github.com/RocketChat/Rocket.Chat/issues/10188)

On every other chat application I use, I only see this type of "unread messages" indicator...

![image](https://user-images.githubusercontent.com/4001792/37729572-b98b200c-2d13-11e8-9a64-fd6480609507.png)

When either I have a message in a 1-on-1 chat or if someone does "@myusername" in group chat. But in Rocket.chat desktop, I see the above indicator any time there are unread messages in any channel I have open. So, for instance, since the #general channel has a lot of activity in open.rocket.chat, my icon is pretty much always signaled. Can we fix this?

---

@theorenck commented on [Wed Apr 11 2018](https://github.com/RocketChat/Rocket.Chat/issues/10188#issuecomment-380529682)

Hi @bizzbyster, tanks for your feedback but I suppose this would be a discussion to have inside the Rocket.Chat.Electron repository.

**Comment by gdelavald** [comment]
@bizzbyster you can always go for the room you want muted and check (or uncheck) the notifications options.
We are working on improving the notifications, but this case is more related to your configurations than the actual functionality (as users expect to be notified when they got new messages on channels)
