### ISSUE TITLE
Backspace can not erase the last one character during Japanese IME conversion (macOS)

### ISSUE THREAD

**Issue by aslend** [RocketChat/Rocket.Chat.Electron#709]
## My Setup
- MacOS Siera
- 2.10.5

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

Backspace can not erase the last one character during Japanese IME conversion (macOS)

[Same Issue] https://github.com/electron/electron/issues/9173#issuecomment-303219349
### Current Behavior

![image](https://user-images.githubusercontent.com/7589870/39049844-0d8eff0c-44de-11e8-91cc-8ef14bc10e73.png)

**Comment by aslend** [comment]
I think the version of Electron has risen and the symptoms have been improved.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
