### ISSUE TITLE
RocketChat starts in the system control but no window appears

### ISSUE THREAD

**Issue by RAPPER23** [RocketChat/Rocket.Chat.Electron#712]
## My Setup
- Operating System: Windows10 Home
- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

No showing window or system tray, Program starts, but not showing up.
### Expected Behavior

Correct registry entry during registration?

**Comment by Seuchenatter** [comment]
Iam not sure but maybe this can help #623

**Comment by kaiiiiiiiii** [comment]
Hi @RAPPER23,

is this still a thing with the latest release?

Thanks,
Kai

**Comment by RAPPER23** [comment]
Hi Kai.

 

Thanks for the answer. There is a little improvement with the latest release. It starts! But even if it is in Autostart it does not starts automatically. I always have to start the program manually. Any idea?

 

Best regards.
Ralph

 

Von: Kai <notifications@github.com> 
Gesendet: Donnerstag, 14. Juni 2018 20:06
An: RocketChat/Rocket.Chat.Electron <Rocket.Chat.Electron@noreply.github.com>
Cc: RAPPER23 <r_piater@arcor.de>; Mention <mention@noreply.github.com>
Betreff: Re: [RocketChat/Rocket.Chat.Electron] RocketChat starts in the system control but no window appears (#712)

 

Hi @RAPPER23 <https://github.com/RAPPER23> ,

is this still a thing with the latest release?

Thanks,
Kai

**Comment by kaiiiiiiiii** [comment]
Did you install the client for you only or for all users on the system? I experienced the behavior you described, when I installed the client only for the current (me only) user.

Cheers,
Kai

**Comment by RAPPER23** [comment]
Thanks Kai. Indeed, only me. Would you recommend to reinstall or change preferences to admin rights?
Best regards,
Ralph

**Comment by kaiiiiiiiii** [comment]
I would recommend to reinstall it for all user on the system. That's how I "fixed" the problem in our company. The only thing that's anoying when you choose that option is, that users without admin rights need an admin to update the app. But I don't see any other work-a-round atm.

**Comment by pagnmickie** [comment]
I tried to reinstall for all users, it did not help in my case. I had to change the isHidden to False.

**Comment by RAPPER23** [comment]
Thanks, this works for me.

**Comment by tlyoder57** [comment]
This problem may have been resolved once, but it is occuring with 2.15.3.  At least two users have report seeing this bug.  Perhaps the code that fixed this problem was reverted by mistake?

**Comment by GCHPX** [comment]
i can confirm that this is happening wirh 2.15.3 and 2.15.5. If you reopen the client, it starts in hidden mode.
