### ISSUE TITLE
Rocket.Chat Desktop app uses an executable stack in Version 2.10.5

### ISSUE THREAD

**Issue by 0x00rick** [RocketChat/Rocket.Chat.Electron#718]
## My Setup
- Operating System: Ubuntu 18.04 XFCE
- App Version: Version 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

The prebuilt packages for Linux (deb/rpm) contain a version of Rocket.Chat that marks the stack as Read,Write,eXecute for each Rocket.Chat process.  

### Reproduction:
Binary installed e.g. via latest provided .deb package.
```
➜  ~ for i in $(pidof rocketchat); do cat /proc/$i/maps | grep stack; done                                   
7ffd2e6a2000-7ffd2e6c3000 rwxp 00000000 00:00 0                          [stack]
7ffcc9bd7000-7ffcc9bf8000 rwxp 00000000 00:00 0                          [stack]
7ffd2e6a2000-7ffd2e6c3000 rwxp 00000000 00:00 0                          [stack]
7ffe2289d000-7ffe228be000 rwxp 00000000 00:00 0                          [stack]
```

### Current Behavior

Stack of desktop application is executable!

### Expected Behavior

Stack is not executable!

**Comment by tassoevan** [comment]
This was [a Electron bug](https://github.com/electron/electron/issues/11628). We have updated Electron version in Rocket.Chat from `1.8.*` to `2.0.*`, therefore this should be fixed.
