### ISSUE TITLE
"Close Window" on OS X minimizes

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat.Electron#72]
On OS X all commands that normally close a window instead minimize it. Namely those are:

- `Window -> Close` in the Menu
- Pressing `⌘ W`
- Clicking the red 'bubble' in the top left

**Comment by ulope** [comment]
Addition:
In case it would be difficult to close the window and still keep the app running in the background (which I could easily imagine for this kind of webapp) the best solution would probably be to map the close button to perform the "Hide Window" action (a standard OS X feature, that is even now available in the 'Window' menu). This appears to be what Slack does for example.

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat.Electron/issues/89

**Comment by ulope** [comment]
This behaviour is still present in the latest 1.1.0 release. Please reopen this issue.
