### ISSUE TITLE
WinClient is detected as a trojan

### ISSUE THREAD

**Issue by lukas116gse** [RocketChat/Rocket.Chat.Electron#721]
After the installation and restart the virus scanner recognizes the client of Rocketchat as a Trojan.

![grafik](https://user-images.githubusercontent.com/39271858/40012779-007a4214-57ac-11e8-9edb-f50ee0c7fe8d.png)

The computer is administered by companies, so I can not put the client on the whitelist
Kaspersky: 10.3.0.6294
Windows: W10 Version 1709 (Build 16299.371)

**Comment by lukas116gse** [comment]
Is there any solution?

**Comment by jschirrmacher** [comment]
The problem still persists. Why did you close the issue?

**Comment by tassoevan** [comment]
Hi @jschirrmacher. Is this happening in the latest release too? Could you provide the info collected by Kaspersky?

**Comment by jschirrmacher** [comment]
The problem came up here with just after updating the app, so yes, it's the lastest release. Server version is 0.70.4, if that's relevant. I'll try to get more info about the message from Kaspersky and post it here (I don't have that personally, but know several people who do)

**Comment by FreeTheTech101** [comment]
I can confirm that the latest release (2.14.5 at the time of writing) is still being detected by Kaspersky Endpoint Security as malicious.

![image](https://user-images.githubusercontent.com/7614507/49649167-58affe00-f9f6-11e8-840f-abb633e5ddf5.png)


```
Event name: Malicious object detected
Severity: Critical event
Application: Unknown
Version number: 11.0.0.6499
Task name: Behavior Detection
Device: <Removed>
Group: <Removed>
Time: 07Dec2018 7:52:16 AM
Result: Detected: PDM:Trojan.Win32.Generic
User: <Removed>
Object: <Removed>
Reason: Behavior analysis
Database release date: 07Dec2018 2:19:00 AM
Hash: 5c177f0e99aafa9f6b7db2f37e433084dbebe6e96b5d4b07c70d3580389d6394
```

**Comment by tassoevan** [comment]
Thanks a lot! Just to confirm: no action is required to Kaspersky heuristics catch it other than just start the app, right?

**Comment by FreeTheTech101** [comment]
That would be correct. A short period of time after starting the application, Kaspersky will remove the application from the computer via deleting all related files, including the application installer. No notifications or anything came in during this time period while I was testing.

**Comment by jschirrmacher** [comment]
![kaspersky-message](https://user-images.githubusercontent.com/2821879/49717801-7ed4d880-fc58-11e8-9fda-94e25fb4927b.png)
![kaspersky-message-2](https://user-images.githubusercontent.com/2821879/49717813-885e4080-fc58-11e8-8ed3-24ae4ba48d6f.png)
<img width="337" alt="defender" src="https://user-images.githubusercontent.com/2821879/49717829-97dd8980-fc58-11e8-8eef-e9fe2f166b46.png">

**Comment by jschirrmacher** [comment]
![kaspersky-message](https://user-images.githubusercontent.com/2821879/49717913-d83d0780-fc58-11e8-8801-687642762ae7.png)
![kaspersky-message-2](https://user-images.githubusercontent.com/2821879/49717914-d83d0780-fc58-11e8-8f05-63dddf802701.png)
<img width="337" alt="defender" src="https://user-images.githubusercontent.com/2821879/49717915-d83d0780-fc58-11e8-8f83-1c17f7bc795b.png">

**Comment by robingoth** [comment]
Same issue happened to me today after the update. This is what I did:
1. Started rocket chat
2. Retrieved an "Upgrade" Notification within RocketChat
3. Updated Rocketchat
4. Saw the Kaspersky Security Warning

Any updates on this?

**Comment by mcsage** [comment]
The Problem still persists with autoupdate function on Win 10 with Kaspersky.
![clipboard - 15 januar 2019 07-57](https://user-images.githubusercontent.com/6553776/51165650-3e90f780-18a1-11e9-95ff-4b4252e0d422.png)

**Comment by mcsage** [comment]
Kaspersky does not complain about 2.14.6.exe which was downloaded directly via the website
https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.14.6/rocketchat-setup-2.14.6.exe

**Comment by tassoevan** [comment]
@mcsage Which versions (from and to) where blocked during autoupdate? I'm starting to believe that Kaspersky is acting against the [event-stream infection](https://snyk.io/blog/a-post-mortem-of-the-malicious-event-stream-backdoor/) (see #1025).

**Comment by mcsage** [comment]
@tassoevan 2.14.4 --> 2.14.7

**Comment by tassoevan** [comment]
I received another report about 2.14.7 being detect as a trojan by Kaspersky on a clean setup as well, therefore I'm discarding the event-stream infection as a root cause.

**Comment by jschirrmacher** [comment]
Is there anything we can do to help prevent these annoying reports?

**Comment by ikatod** [comment]
I confirm. My remote employees are scared. This should not be repeated! Is there a solution to this problem?

**Comment by nbartels** [comment]
Same problem here. 2.14.7 downloaded from your website was running flawlessy. After upgrading to 2.15.0 via the update in the client I get a message from Kaspersky 10. Trojan.Win32.Generic is the detected problem.

According to Kaspersky the problem is triggered by many delete actions in the temp folder. The antivirus things this is a suspicious behavior ...

**Comment by ikatod** [comment]
This is good, but what do you do to avoid it? My staff antivirus deleted roketchat. What to do so that the antivirus does not delete the program? Will you release an update?

**Comment by hasuino** [comment]
Current version (2.15.1) is still recognized as carrier of generic trojan (Windows 10):
![Trojan_Generic](https://user-images.githubusercontent.com/14343848/54347225-dfecbd80-4646-11e9-9f81-cab90cef0b9c.png)

**Comment by D3athCycle** [comment]
> 
> 
> Current version (2.15.1) is still recognized as carrier of generic trojan (Windows 10):
> ![Trojan_Generic](https://user-images.githubusercontent.com/14343848/54348102-a74de380-4648-11e9-9da9-4d1bc5a040ac.png)

Same problem here: windows 10, kaspersky endpoint security 11.0.0.6499, rocketchat version 2.15.1

![image](https://user-images.githubusercontent.com/48591929/54431976-9c598880-4706-11e9-8a1e-3838719c9b07.png)

**Comment by alexdatsko** [comment]
Verified this is still an issue, had several reports of this today using Kaspersky Endpoint Security 10/11 (KES).  Workaround currently is to download the newest client from the web.  

However, on my machine running Windows 10 1803 and KES 11, I excluded %AppData%\RocketChat from being scanned in Kaspersky.  I removed Rocketchat completely, deleted everything in Appdata\roaming\Rocket.Chat, used a 2.14.7 installer, then updated to 2.5.1 successfully within the application, and did not get a warning from KES after the update.  

Then I did basically the same thing as a test though on Kaspersky 10 on a Windows 8 machine, excluded %AppData%\RocketChat, and upgraded from 2.13.0 to 2.15.1, and after the installation was complete and the new Rocketchat started up, I still got the W32.Generic disinfect message shown above.  This could be due to Kaspersky 10 not parsing %AppData% variable correctly, or some other reason.

**Comment by tassoevan** [comment]
Still happening in 2.15.2?

**Comment by D3athCycle** [comment]
> 
> 
> Still happening in 2.15.2?

Not anymore:
![image](https://user-images.githubusercontent.com/48591929/56377768-847f9380-61e1-11e9-9b01-505b839e910f.png)


Thanks

**Comment by jcatarino** [comment]
Is this solved from 2.15.2 onwards? thanks

**Comment by hitthenorth** [comment]
We have seen some strange behaviour for a user downloading and installing 2.15.1 on their PC. When the installer asked to install a newer version (2.15.3), Trend Apex One flagged it up as a Trojan as below.

![Rocketchat trojan](https://user-images.githubusercontent.com/47143693/57872116-df1d0700-7802-11e9-80a0-434f4e82c6e2.JPG)

I believe Trend will have removed the install at that point.

He installed 2.15.1 again and logged in, then fully exited and restarted it. He was then prompted again to install the 2.15.3 version and that installed fine without any alerts from Trend.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
