### ISSUE TITLE
Message box out of bounds

### ISSUE THREAD

**Issue by EwgB** [RocketChat/Rocket.Chat.Electron#723]
## My Setup
- Operating System: Windows 10 Professional
- App Version: 2.10.5

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description
The message box (and some other UI elements) are always out of bounds.

![Schreenshot](https://user-images.githubusercontent.com/853635/40054088-e8d9e8d8-5843-11e8-8d4d-8d3210affacb.PNG)

The behavior is consistent and repeatable

### Current Behavior
As is visible in the screenshot, the window is maximized, but the message box is not visible. Depending on the size of the window, small parts of it might appear on the bottom of the window, but not enough to actually be able to type in it.

### Expected Behavior
The message box should appear inside the visible area of the program window.

**Comment by gdelavald** [comment]
@EwgB thank you for your report.
I'll be closing the issue in favour of #564. Please continue any discussion on the other issue.
