### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by CrimsonAndrew** [RocketChat/Rocket.Chat.Electron#724]
Long story short. Ukrainian translation is very bad. I need xsl file with English-Russian-Ukrainian to correct these mistakes. I have HUGE experience in app translating so pretty sure that can deal with it. And yes, I didn't know that mobile and desktop versions are separated so at first bothered guys from mobile version.

**Comment by kaiiiiiiiii** [comment]
Hi @CrimsonAndrew,

please have a look at the Rocket.Chat LingoHub project to contribute:
https://github.com/RocketChat/Rocket.Chat#translations

**Comment by CrimsonAndrew** [comment]
I see only

Oops! Something went wrong here.
global.server_errors.illegal_argument


>Среда, 16 мая 2018, 19:29 +08:00 от Kai <notifications@github.com>:
>
>Hi  @CrimsonAndrew ,
>please have a look at the Rocket.Chat LingoHub project to contribute:
>https://github.com/RocketChat/Rocket.Chat#translations
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С наилучшими пожеланиями,
Евгений

**Comment by perchibald** [comment]
I also did not find

**Comment by kaiiiiiiiii** [comment]
@CrimsonAndrew

Sorry, here’s a working link:

https://github.com/RocketChat/Rocket.Chat/blob/develop/README.md#translations

As far as I know the RC LingoHub Project is just for the server component, not for the desktop and mobile apps.

And to be honest, I’m not really sure if there’s even a ukrainian translation for the desktop cloent available.

**Comment by kaiiiiiiiii** [comment]
//CC: @TwizzyDizzy I think this can be closed, as there’s not really an issue with the electron app.
