### ISSUE TITLE
Windows 10 ver 1803 and Rocket.Chat+ 2.10.5.628 incompatible

### ISSUE THREAD

**Issue by noloader** [RocketChat/Rocket.Chat.Electron#728]
### Description:

Windows 10 ver 1803 and Rocket.Chat+ 2.10.5.628 are reported as incompatible. The program does not finish launching and does not show its main screen.

### Server Setup Information:

* Version of Rocket.Chat Server: 
  - Unknown at the moment.

* Operating System: 
  - Windows 10 Pro x64 version 1803 (OS Build 17134.48)

* Deployment Method(snap/docker/tar/etc): 
    - Downloaded Windows installer, ran installer

* Number of Running Instances: 
    - Unknown. The best I can tell something starts but no main Window is displayed. So maybe 1 instance?

* DB Replicaset Oplog: 
    - Unknown. Whatever version is bundled with RocketChat+ 2.10.5.628.

* Node Version: 
    - Unknown. Whatever version is bundled with RocketChat+ 2.10.5.628.

* mongoDB Version: 
    - Unknown. Whatever version is bundled with RocketChat+ 2.10.5.628.

### Steps to Reproduce:

1. Upgrade to latest version of Windows, which was released circa May 18, 2018
2. Download the latest version of Rocket.Chat+, from circa May 18, 2018
3. Install Rocket.Chat+ for all users
4. Attempt to run Rocket.Chat+ after Windows 10 upgrade.

Prior to the Windows 10 ver 1803 upgrade I had a lesser version of Windows 10. I also had RocketChat+ 2.10.2.610. They worked fine together.

After upgrading neither RocketChat+ 2.10.2.610 nor 2.10.5.628 would run. They seem to launch or partially start, but no main window is drawn. There is an icon in the taskbar and it is underlined. Clicking the icon does not display the main window.

There are no events registered in the Windows Application or System logs. I also tried to run in *Windows 8 compatibility mode* but the same problem surfaced.

Running a Windows Compatibility Test seems to indicate Microsoft knows there is a problem. But searching through the issue reporter I don't see a squawk for Windows 10 version 1803. I'm guessing Microsoft failed to tell anyone about it.

We probably cannot share the logs with the project. The organization is a defense contractor and they are uber paranoid. My sincere apologies for that.

![brick-chat](https://user-images.githubusercontent.com/3538226/40255010-935b9948-5ab3-11e8-9c1b-11b1bd552f98.png)

**Comment by kaiiiiiiiii** [comment]
Hi @noloader,

is this still a thing with the latest release?

Thanks,
Kai

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
