### ISSUE TITLE
Windows client stop working. App can't be opened

### ISSUE THREAD

**Issue by manuelmsoria** [RocketChat/Rocket.Chat.Electron#730]
## My Setup
- Operating System: Microsoft Windows 10 Home. Versión 10.0.17134 compilation 17134

- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
If I try to start app it tries to show main window but it's closed inmediately. If I try to open it in console it shows an error:

> C:\Program Files\rocketchat\Rocket.Chat+>
> module.js:487
>     throw err;
>     ^
> 
> Error: Cannot find module '../dialog'
>     at Module._resolveFilename (module.js:485:15)
>     at Function.Module._resolveFilename (C:\Program > Files\rocketchat\Rocket.Chat+\resources\electron.asar\common\reset-search-paths.js:35:12)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.get [as dialog] (C:\Program > Files\rocketchat\Rocket.Chat+\resources\electron.asar\browser\api\exports\electron.js:11:16)
     at process.<anonymous> (C:\Program > Files\rocketchat\Rocket.Chat+\resources\electron.asar\browser\init.js:54:31)
>     at emitOne (events.js:115:13)
>     at process.emit (events.js:210:7)
>     at process.emit (C:\Program > Files\rocketchat\Rocket.Chat+\resources\app.asar\node_modules\source-map-support\source-map-> support.js:453:21)

### Current Behavior
Application doesn't run.

### Expected Behavior
Application should run and show main screen.

**Comment by tassoevan** [comment]
Is this still happening in the recent versions?

**Comment by iprok** [comment]
Issue has gone away for me. Can't understand what has happened.
