### ISSUE TITLE
Online-Status changes on mouse move

### ISSUE THREAD

**Issue by Maqsyo** [RocketChat/Rocket.Chat.Electron#731]
## My Setup
- Operating System: Windows 10 + Mac OS
- App Version: 2.10.5

- [x] I have tested with the latest version
- [] I can simulate the issue easily -> we can't bring the bug to work on a different system with different or the same accounts

## Description

![image](https://user-images.githubusercontent.com/19644698/40344910-427ce2ac-5d97-11e8-8c8c-fab795ad7242.png)
![image](https://user-images.githubusercontent.com/19644698/40344930-532fa3fa-5d97-11e8-99e1-c75d34875577.png)

### Current Behavior

![ezgif com-crop](https://user-images.githubusercontent.com/19644698/40344862-05ce5764-5d97-11e8-95af-2236300c6f5b.gif)

The Bug is related to the App. In our working environment 3 guys have these bug. It appears on Windows 10 and Mac.

The user is always 'away' instead of 'online', except he moves his cursor in the Rocket.Chat App

### Expected Behavior

The User should stay 'online' :)

**Comment by Maqsyo** [comment]
A reinstall doesn't help.
The only thing that helped was:
- uninstalling rocketchat
- delete all files in C:\Users\username\AppData that are found with "Rocket"

I think that isn't a good fix for this bug

**Comment by Maqsyo** [comment]
In our configuration we had setted the Idle Time Limit to 300 seconds
Now with the update of the server it had the value "0.3 ms"
So we changed it to 300000 ms and now this bug is gone.

We dont know what the problem was exactly, but it is gone...

**Comment by icerootsvw** [comment]
From my understanding this Bug an #1147 are different

This one is talking about that the time value is handled incorrectly but the option is set to "true". So going to the away status is wanted

On ##1147 the option is set to "false" and its switching to away but its not wanted
