### ISSUE TITLE
[Windows] Add Multiple Files Drag'nd'Drop Support from Explorer

### ISSUE THREAD

**Issue by drweb86-work** [RocketChat/Rocket.Chat.Electron#732]
Hello

Could you please add support for dropping multiple files from Windows Explorer to Electron Chat. It could be more convinient to transfer documents.

Thank you.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
