### ISSUE TITLE
Consider using TinyMCE and send html instead of wiki markup in messages

### ISSUE THREAD

**Issue by drweb86-work** [RocketChat/Rocket.Chat.Electron#733]
Hello

Could you please consider using HTML instead of wiki markup upon chat writing. And consider using one of the good html editors for writing messages - TinyMCE.
https://www.tinymce.com/

I doubt anyone want to know that special characters to easily format text. And there're already good editors on the market such as this tool.

**Comment by Maqsyo** [comment]
i think this should be a feature-request for https://github.com/RocketChat/Rocket.Chat, because this isn't a feature for the app

**Comment by drweb86-work** [comment]
Thanks. I created an issue there.
