### ISSUE TITLE
Toggle Menu Bar

### ISSUE THREAD

**Issue by Maqsyo** [RocketChat/Rocket.Chat.Electron#734]
## My Setup
- Operating System: Windows
- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

It is not possible to toggle the menu bar if it is hidden
The shortcut [Alt] + [V] isn't working
I think it isn't an electron-bug, because in Atom this shortcut works

### Current Behavior

The menu-bar is hidden for ever :(

### Expected Behavior

I'd like to get my menu-bar back.. sometimes..

**Comment by pminf** [comment]
Just hit [alt] once (not [alt gr]) and the menu bar will show up temporary. Now you able to show it permanent via _Toggle Menu Bar_.

**Comment by Maqsyo** [comment]
Thank you so much!
