### ISSUE TITLE
macOS High Sierra energy consumption too high #10854

### ISSUE THREAD

**Issue by smnbbrv** [RocketChat/Rocket.Chat.Electron#735]
## My Setup
- Operating System: macOS High Sierra
- App Version: 2.10.5

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

### Current Behavior

See https://github.com/RocketChat/Rocket.Chat/issues/10854#issuecomment-391274158

### Expected Behavior

Should not consume that much

**Comment by jrozelle** [comment]
Same problem here, with 2.11.

**Comment by jbrokamp** [comment]
Same on my machine. Running consistently with Energy Impact around 12 in Activity Monitor: macOS Mojave, app version 2.15.5

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
