### ISSUE TITLE
Add an option to hide disconnected users and sort by name (ignoring case)

### ISSUE THREAD

**Issue by cg666** [RocketChat/Rocket.Chat.Electron#738]
## My Setup
- Operating System: Linux 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux

- App Version:2.10.5

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

I have a lot of discussion with my collegues and it would be great if disconnected user can be hidden and user sort by name by ignoring case.

### Current Behavior

Disconnected user discussion are shown and there is no option to hide it. User are sort by alpha order but name with capital case are sorted prior to lower case user name.

### Expected Behavior

Disconnected user shall be hidden depending on system settings and user shall be sort by name case insensitive.

**Comment by drweb86-work** [comment]
As for me its better to show them right after connected users.

**Comment by kaiiiiiiiii** [comment]
Hi @cg666,

I think you’re in the wrong repository, as the electron app is just a simple wrapper of the web page. Your feature request sounds like it belongs in the Server repository.

Feel free to open an issue over there (may use the search first) :)

https://github.com/RocketChat/Rocket.Chat

//CC: @TwizzyDizzy
