### ISSUE TITLE
Livechat room is not removed from list when db entry have been deleted

### ISSUE THREAD

**Issue by tammon** [RocketChat/Rocket.Chat.Electron#739]
## My Setup
- Operating System: macOS 10.13.4
- App Version: 2.10.5
- Server Version: 0.65.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Livechat rooms that have been cached in the desktop app are not being invalidated when db entries for this LiveChat session is removed. The room keeps popping up in the open LiveChat view of the desktop app while it doesn't when I access rocket.chat via browser.

In my specific case I came along this problem after restoring the mongoDB to a prior backup. 

### Steps to reproduce
1. Create a backup of your current rocket.chat mongoDB
1. Open a new LiveChat session via the LiveChat widget on the site you have it embedded
1. Go to the Rocket.Chat Desktop app and accept the new incoming LiveChat Session (mode: Guest Pool)
1. write sth in the session's chat, DON'T CLOSE IT!
1. restore the mongoDB to the prior created backup, restart rocket.Chat server
1. Reload the server in the desktop app.

### Current Behavior

After doing this steps, you still see the old LiveChat session in the desktop app. Even when you "hide" the session it keeps popping up. The LiveChat is essentially broken in this case because you can't handle any new LiveChat sessions anymore in the desktop app (it keeps jumping to the old one and then hangs on loading). In the web view though, the "old" liveChat session is gone. It's also not listed in the LiveChat admin pane (web and desktop).

I also tried the following with no difference:
- removed the server from the desktop app and re-login
- removed caches from `/Users/[myUser]/Library/Containers/chat.rocket/Data/Library/Caches/chat.rocket.electron.helper` and `/private/var/folders/...`

### Expected Behavior

I'd expect the desktop app to not show this old LiveChat session, if the database entry doesn't exist anymore.

### (Kind of a) Quick fix
After removing the rocket.chat desktop app completely with all files and folders related to it and doing a fresh install, it works as expected. (I assume it's a caching problem)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
