### ISSUE TITLE
Make tray(menubar) icon optional

### ISSUE THREAD

**Issue by Sugaroverdose** [RocketChat/Rocket.Chat.Electron#74]
On OS X tray icon after click allows to switch window state which is duplication of standard os controls also it duplicate notification info from dock icon, in result it's not so useful for OS X users.
##

**Comment by frdmn** [comment]
:+1

**Comment by mischah** [comment]
Yeah. Pretty useless and spamming my menu bar

![image](https://cloud.githubusercontent.com/assets/441011/17962876/3149a1d8-6ab3-11e6-8a3d-faf429adb883.png)

😂

**Comment by tedpearson** [comment]
Make it go away :(
