### ISSUE TITLE
No Sets on Windows 10

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat.Electron#741]
Almost every program I use supports Sets, it's really irritating to not have that on RocketChat.

This was moved here as per https://github.com/RocketChat/Rocket.Chat/issues/11047#issuecomment-395576834

**Comment by engelgabriel** [comment]
Can you explain how do you think this would work on Rocket.Chat? I am not a Windows user, so I am a bit lost here.

**Comment by HammyHavoc** [comment]
Sets outside of a few first-party apps is currently not in the latest Windows Insider build as they're restructuring how third parties will be integrating it into their apps.

But why you would want it: you can have one window, but with tabs. Within that window, you can have multiple applications, i.e. browser tabs, a note taking application etc.

Why would you want to do this you ask? You can save it as a "Set", which is a workflow that can roam from machine to machine.

For example, I could have a "Split An Atom" set (my main business), and within it, I could have the SAA RC server running in one tab, our project management system on another, the SAA email on one, and the SAA social media in other tabs.

Think of them like sandboxed sessions/workflows, but you can resume them time after time. So if you have your windows and tabs set in a particular way, you can resume it as you left off, time and time again, and via the Microsoft Graph, you can roam the sessions between machines. Very useful.

**Comment by tassoevan** [comment]
This looks great, but firstly we need to understand better how Windows will handle some Electron's window events. We ran into a lot of problems dealing with the tray icon like, e.g., not restoring the right window state after hide it.

**Comment by jeanfbrito** [comment]
Is this an issue yet? I never used windows sets, its a thing nowadays?
