### ISSUE TITLE
Black screen!!!

### ISSUE THREAD

**Issue by perchibald** [RocketChat/Rocket.Chat.Electron#743]
- Operating System: Windows 2008 R2
- App Version: 2.10.5

- [ yes ] I have tested with the latest version
- [ yes ] I can simulate the issue easily

## Description

Very often when you open the browser (chrome or firefox)

### Current Behavior

Black screen!!!

![error_rocket_chat](https://user-images.githubusercontent.com/847633/41147149-0c99a1a8-6b1f-11e8-989f-1594c02f64c8.png)

**Comment by drweb86-work** [comment]
This happens to Chrome itself. Issue is linked sometimes with a) old video card drivers b) automatic video drivers installation.

Solution is to install latest drivers if you dont have Windows 10, reboot PC

**Comment by drweb86-work** [comment]
Check how Chrome works. If it fails, then its a chromium or vmware issue

**Comment by perchibald** [comment]
This is a terminal server, there is no GPU acceleration.
Is it possible to do both in slack.exe --disable-gpu ??

**Comment by drweb86-work** [comment]
VMWare also has settings about GPU acceleration. So its worth to play with it.

**Comment by perchibald** [comment]
ok

**Comment by Monolithys** [comment]
Rocket.chat 2.16.2
Windows 7 x64
Intel HD 2500
Same problem

Solution - change Direct3D to software mode.
I use DirectX SDK [**Link**](https://www.microsoft.com/en-us/download/details.aspx?id=6812)

**Comment by leeanh2612** [comment]
Dear Monolithys!

Can you explain more details about your solution for the problem! Thanks you so much

**Comment by Monolithys** [comment]
ok, i write how i solve it.
If you see same picture as at top. Download DirectX SDK [**Link**](https://www.microsoft.com/en-us/download/details.aspx?id=6812) You need it, be course Windows 7, 8, 8.1, 10 do not give you choices to turn on/off DirectX Acceleration, it alway on if possible.
Next use "DiretX Control Panel" - for 32 bit OS systems or "DiretX Control Panel(64-bit)" for 64 bit OS systems. 
![image](https://user-images.githubusercontent.com/32746979/70301766-52707f80-180c-11ea-9dbd-35bd698bdc28.png)
Just set "Software Only" mode and apply. (Must set in right version utility x32/x64 - or nothing changes).
Next time you run Rocket - all working fine.
Of couse you lost some performance, but i did not feel anything...
