### ISSUE TITLE
Searchbox selfcloses/not works

### ISSUE THREAD

**Issue by 0x6c** [RocketChat/Rocket.Chat.Electron#745]
## My Setup
- Operating System: Mac OS 10.13.4
- App Version:  2.11.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When trying to search someone with CMD+K or by direct click on search icon - search field doesn't performs any actions and there is no requests to server(checked nginx logs and tcpdump).

### Current Behavior

Instead of searching, sometimes search input disappearing or just not searching anything(doesn't matter if entering email/username/full name).
### Expected Behavior

At least username search should work.

NOTE: I am using LDAP integration.
Would be great if we will have some docs on client side problems debugging, so diagnose would be much more simple.

Thanks.

**Comment by 0x6c** [comment]
And yes, same was with previous version of client.
Tried to delete client data(~Library/../chat.rocket)

**Comment by 0x6c** [comment]
After some debugging I found that Search page closes when it starts to search on serve(not locally cached records). Debugging further, but can't find the exact wss connection to perform some dump.
Any advice?


Thanks.

**Comment by engelgabriel** [comment]
Do you see any errors on the console when you enable dev debug tools? Can you share the logs?

**Comment by 0x6c** [comment]
Not really, there is no errors in relation to connection or any JS.
I using dev build now and watching for an event, but unfortunately I can't even repeat the problem with it :( Will observe and let you know further.

**Comment by engelgabriel** [comment]
What is the version of the server?

**Comment by 0x6c** [comment]
![image](https://user-images.githubusercontent.com/19513737/41269716-7d22db72-6e0f-11e8-84b1-074d30083e53.png)

**Comment by 0x6c** [comment]
Will try.
Huge amount of users requires to be careful with updates.
Anyway, after digging in debug for 2 days, I didn't found anything related to that issues, so I assume it's absolutely related to our setup.
