### ISSUE TITLE
Corrupted artwork on server selection pane

### ISSUE THREAD

**Issue by bettaa** [RocketChat/Rocket.Chat.Electron#748]
## My Setup
- Operating System: Windows 10 (OS build 15063.1088)
- App Version: 2.11.0

- [ X] I have tested with the latest version
- [X ] I can simulate the issue easily

## Description

I have a user who has reported that the artwork in the server selection area on the left-hand side of the window, comes up with corrupted artwork
![screenshot_061318_101252_am](https://user-images.githubusercontent.com/5728525/41367331-913d0472-6ef3-11e8-9231-6eeb94812596.jpg)

### Current Behavior

When the user mouses over the area, the artwork looks all broken up.
### Expected Behavior

The artwork should remain static.

**Comment by cinderblock** [comment]
Interestingly, I have a similar issue after upgrading to 2.11.0. However, for me, the artwork is not messed up. It is just displayed a couple times (as above) when I expect it to be displayed once.

![image](https://user-images.githubusercontent.com/419955/41388420-b18edaf0-6f40-11e8-945b-9e812aa200c9.png)

When I mouse over the server selector or the "+" at the top, the extra icons go away and the UI looks as expected.

**Comment by kaiiiiiiiii** [comment]
IMHO this looks like an issue related to #744.

**Comment by Maqsyo** [comment]
Hey Guys!
What's going on here? :D
still a bug ♥

**Comment by Maqsyo** [comment]
With the new version it is gone. Thanks!

**Comment by kaiiiiiiiii** [comment]
@gdelavald This issue can be closed :)
