### ISSUE TITLE
Focus emoji search field when opening

### ISSUE THREAD

**Issue by azgul** [RocketChat/Rocket.Chat.Electron#755]
## My Setup
- Operating System: macOS
- App Version: 2.11.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Pressing the smiley or reaction button should open & focus search field

### Current Behavior
It opens, but search field is not focused, requiring to click in the search field to gain focus

### Expected Behavior
It opens with focused search field

**Comment by gdelavald** [comment]
Closing this as this is not related to Electron. Please check the [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) repository for more information.
