### ISSUE TITLE
<alt>+H doesn't open Help menu because of a shortcut conflict with History

### ISSUE THREAD

**Issue by adipose** [RocketChat/Rocket.Chat.Electron#756]
## My Setup
- Operating System: Windows 10
- App Version: 2.11.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Hit alt+H and History menu opens.  Hit again and it stays in History. No shortcut works to open Help menu.

### Current Behavior
You can only open the History menu with alt+H

### Expected Behavior
If you hit alt+H a second time, it should open "Help."  This is the normal windows behavior when a shortcut key is repeated.  However, it is considered bad practice to reuse the same alt shortcut in the first place.  Since alt+H most commonly opens Help in other applications, History should probably use alt+i.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
