### ISSUE TITLE
Permalink to direct message shows 404 error page

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.Electron#758]
## My Setup
- Operating System: MacOS 10.13
- App Version: 2.11.0

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Clicking a permalink to a direct message shows a 404 error page.

Here's a screen capture: https://up.frd.mn/FvXJoCpK8W.mp4

### Current Behavior
Client shows 404 error page

### Expected Behavior
Client should follow the link and open the direct message conversation.

**Comment by theorenck** [comment]
I discussed the subject a little with @sampaiodiego and it seems to be a problem with DM permalink's structure, specifically the lack of a proper room name **e.g**:
- **Group:** https://open.rocket.chat/channel/general?msg=gxsHQx2cYfQjboWRF 
- **Direct message:** https://open.rocket.chat/direct?msg=QdqwXuafvjn8aQ4sc

The "direct" token is in place of the room name for DM permalinks, which makes the link invalid. We probably need to change this if we want to change the 404 behavior / response.

**Comment by theorenck** [comment]
Issue moved to [RocketChat/Rocket.Chat #11400](https://github.com/RocketChat/Rocket.Chat/issues/11400) via [**ZenHub**](https://www.zenhub.com/)
