### ISSUE TITLE
Feature Request: improve handling of lost session

### ISSUE THREAD

**Issue by markusstoll** [RocketChat/Rocket.Chat.Electron#764]
## My Setup
- Operating System: OSX 10.13.5
- App Version: 2.11.0

- [x] I have tested with the latest version
- [~] I can simulate the issue easily 

Unfortunately I do not yet know how to force losing the session - sometimes after upgrading the server, everything keeps on going, sometimes not.

## Description
Sometimes upgrading RocketChat server ends in a lost session in your native client, you have to relogin by reentering credentials

### Expected Behavior
The user does not get a notification or visual hint about the lost session. Having such information would be great to hint the user to relogin. Having the credentials auto stored like when using rocket chat with a web browser would be great, too

**Comment by markusstoll** [comment]
After updating the rocketchat server to 0.67 the problem seems to appear less.

However, I forgot to mention the most important problem: If you lose the session with the server, the user does not get a notice. I would suggest notification just like when a new message appears. Currently the user thinks, everything is fine but no messages arrive, while he might miss important messages

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
