### ISSUE TITLE
Create Flatpak package

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#770]
We have ubuntu snap, would be great to have flatpak also

**Comment by geekgonecrazy** [comment]
It appears someone in the community already has!

https://flathub.org/apps/details/chat.rocket.RocketChat
https://github.com/flathub/chat.rocket.RocketChat

**Comment by engelgabriel** [comment]
https://github.com/flathub/chat.rocket.RocketChat/issues/1
