### ISSUE TITLE
Help/ReportIssue reports an issue for a different package.

### ISSUE THREAD

**Issue by petersilva** [RocketChat/Rocket.Chat.Electron#771]
## My Setup
- Operating System:  Ubuntu Linux 18.04
- App Version: 2.10.5-686  

- [X ] I have tested with the latest version
I do not know if it is the latest. When I click on Help, there is no "about" item I do:

blacklab% dpkg -l | grep rocket
ii  rocketchat                                 2.10.5-686                                  amd64        
blacklab% 
don't really know how I would know.

- [x] I can simulate the issue easily

yes trivially.

## Description
The reportIssue link in the help menu points to  Rocket.Chat/Issues, and not the one for this client.
See this: https://github.com/RocketChat/Rocket.Chat/issues/11401

### Current Behavior

you activate the help menu then select the ReportIssue item

It brings up the ReportIssue URL for the Rocket.Chat application.
And when you submit a bug, you are told you are in the wrong place.

### Expected Behavior
It should open https://github.com/RocketChat/RocketChat.Electron/Issues
instead.

**Comment by jeanfbrito** [comment]
Hello @petersilva, the main way to register an issue is on Rocket.Chat repository. Thats why we use it for the Report Issue.
If the issue is really a Electron thing, It will be moved to the Electron Repository. 
Thats it. Thanks for noticing it.
