### ISSUE TITLE
Notification Handling in Windows

### ISSUE THREAD

**Issue by skullchap** [RocketChat/Rocket.Chat.Electron#775]
## My Setup
- Operating System: Windows 7,10
- App Version: 2.11.0

## Description
 Not much of and issue but a feature request for handling Notifications 

### Current Behavior
Notifications (toastNotifications) stays only for 7 seconds. Changing registry (or settings in control panel/accesibility) to 5 min extends them only by 20 seconds

### What i would like to have
I used Openfire/Spark before in my environment and Spark had one nifty feature - you would able to toggle Spark Main window to pop up after receiving a DM. With current notifications handling its so easy to miss DM, even icon on tray doesnt pop up and blink. Also i would like to have an option for notification to stay on screen until the message is read. Maybe there is workaround i would like to know about. Thank you.

**Comment by Maqsyo** [comment]
We used Spark before too, but Rocket.Chat is better in so many points.
But this little blinking icon was really great!
 +1 for this request!

**Comment by Anguel** [comment]
This problem has actually been discussed in so many threads but still no fix. It makes the software unusable for our company... At least the developers should add an option to prevent the main window from being closed, this way the program will stay in taskbar and will not disappear in tray. This should not be so hard to do.

**Comment by kaiiiiiiiii** [comment]
> This should not be so hard to do.

Feel free to submit a PR for that issue mate :)

**Comment by engelgabriel** [comment]
Can you please try the https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.13.0-develop ? The ICON on the tray now has a badge and the notification system has been updated.

**Comment by Anguel** [comment]
Unfortunately, I don't see any improvement if the Rocket.Chat window is closed and sitting in the tray the new message is still missed.

**Comment by tassoevan** [comment]
> Notifications (toastNotifications) stays only for 7 seconds. Changing registry (or settings in control panel/accesibility) to 5 min extends them only by 20 seconds

I can't reproduce this in 2.13.3 under Windows 10.

**Comment by crazy-max** [comment]
I think we should use the [advanced notifications of Electron](https://electronjs.org/docs/tutorial/notifications#advanced-notifications) on the Windows desktop app. This will allow custom templates, images, and other flexible elements. What do you think @tassoevan ?

**Comment by tassoevan** [comment]
@crazy-max I have considered the `electron-windows-notifications` library. However, it introduces a new problem solved by Electron's Brightray: image handling. Rocket.Chat notifications have a avatar image encoded as a data URI, unsupported by Windows notifications. Brightray (and I believe Chrome too) handles that by storing the avatar as a temporary file, generating a shorter URI to the notification payload. Also, this library don't try to use the same web-based Notifications API. To develop something good will take some effort...

**Comment by crazy-max** [comment]
@tassoevan Okay, thanks for your clarifications!

**Comment by Bellamonte** [comment]
Neither notifications nor unread messages badge on tray icon works for me.

OS: Windows 7
Rocket.Chat version: 2.14.1

**Comment by Anguel** [comment]
@Bellamonte Did you try the new menu option:
https://github.com/RocketChat/Rocket.Chat.Electron/pull/895#issuecomment-433838248
At least it works on Windows 10.

**Comment by tassoevan** [comment]
I did some experiments with `electron-windows-notifications` and `electron-windows-interactive-notifications` and other libraries for notifications in  Node.js today and it was disappointing. Besides have to hack Electron even more (`electron-builder` is enough headache), there is no reliable way to keep the notifications in Action Center and track actions over them at the same time. The needed amount of work is way bigger than I was expecting or there is a totally different way to handle toast notifications in Windows that I not aware of.

**Comment by Anguel** [comment]
@tassoevan Tasso, just an idea: If the Windows notifications disappear to fast, how about adding a simple feature to **resend** a reminder notification every X minutes if there are still unread messages? Something like "You still have 3 unread messages". Just an idea. Would that help?
