### ISSUE TITLE
When adding a server, the trailing / gets stripped

### ISSUE THREAD

**Issue by angusvb** [RocketChat/Rocket.Chat.Electron#779]
## My Setup
- Operating System: Windows 10
- App Version: 2.11.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When adding a server like 'https://myserver.com/rocketchat/', the trailing / gets stripped. The reverse-proxy settings of nginx and running in a subfolder do not allow the url to open without the trailing /.

Going into the app devtools and adding the trailing slash manually in the code does make the client connect.

### Current Behavior
RocketChatClient tries to connect to 'https://myserver.com/rocketchat' and fails

### Expected Behavior
RocketChatClient tries to connect to 'https://myserver.com/rocketchat/' and gets connected.

**Comment by gdelavald** [comment]
Hey @angusvb thanks for the report, we'll look into fixing it for the next release.
