### ISSUE TITLE
allow accessing servers with self-signed certificates

### ISSUE THREAD

**Issue by taybin** [RocketChat/Rocket.Chat.Electron#78]
I believe this is the problem I am currently running into with the hybrid apps.

Maybe a checkbox in the preferences?

**Comment by taybin** [comment]
Was this closed accidentally?  The commit doesn't seem related to it at all.

**Comment by engelgabriel** [comment]
Yes... because of the merge.. the commit form upstream had a entry like:
`Improve bundle error reporting with updated rollup. Fixes #78`

**Comment by rodrigok** [comment]
You can access servers with self sign certificates by adding your CA to your system (I tried in OS X installing the CA in Keychain).

Adding an option to allow insecure connections can be dangerous.

You should do the something for our mobile apps too.

So you have 2 options:
1. Create a valid certificate via an bug CA
2. Use your own certificate and install your CA
