### ISSUE TITLE
Allow launching of application via rocketchat://

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#79]
It would be cool for someone to be able to put something like Join us on rocket.chat with a link and it open the app.

So links like maybe rocketchat://demo.rocket.chat
##

**Comment by floriangoeldi** [comment]
Seems like this would be a way to go: http://stackoverflow.com/a/19771330/2775493
Why not the electron protocol?

> The protocol module only works for requests made within your Electron application. This stackoverflow question has some suggestions for registering OS level protocols. http://stackoverflow.com/a/19771330/2775493

Maybe this has to be deployed with the installer?
