### ISSUE TITLE
Localization of the Rocket.Chat.Electron

### ISSUE THREAD

**Issue by cadetmsv** [RocketChat/Rocket.Chat.Electron#793]
## My Setup
- Operating System: Windows 7
- App Version: 2.12.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

In the panel menu and context menu in Rocket.Chat Electron there is no translation into Russian. English only.

### Current Behavior

![snapshot_180806_100307](https://user-images.githubusercontent.com/34961483/43701769-1ccd0794-9960-11e8-8841-ef79f9efb9a4.jpg)

---------------------------------------------------
![snapshot_180806_100316](https://user-images.githubusercontent.com/34961483/43701776-26dc4a7e-9960-11e8-8f2c-54d2e48c216e.jpg)
---------------------------------------------------
### Expected Behavior

Maybe he is present, but I can not activate it?

**Comment by jmledantec** [comment]
Hello,
#562 this pr can solve this ?

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
