### ISSUE TITLE
macOS dock icon badge not clearing anymore

### ISSUE THREAD

**Issue by TriPhoenix** [RocketChat/Rocket.Chat.Electron#794]
## My Setup
- Operating System: 10.13.6
- App Version: 2.12.0
- Running self-hosted rocketchat 0.66.2 right now

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Since the app upgrade to 2.12.0 the macOS badge icon does not reset anymore, when you read the last notification, nor does it seem to include the "dot" indicator anymore when you have channel activity but no mention.

This seems to be related to the change in https://github.com/RocketChat/Rocket.Chat.Electron/commit/e5be5bbba278aef8f2f522540a29291322636230#diff-5fa1a718496c993410f8c51b3e7a2bab
By hacking around this to set the badge icon always and depending on the count to title or count, I could make this behave in the existing way again:
```
    if (process.platform === 'darwin') {
        if (badge.count > 0) {
            remote.app.dock.setBadge(badge.count.toString());
        } else {
            remote.app.dock.setBadge(badge.title);
        }
    }
````

As I'm not familiar with the project or the patch in question yet, I don' thave any idea if this is the "right way" to handle this. ~I'll be happy to make a proper pull request though if this would be an acceptable patch.~ Attached pull request in case this is the right fix.

Alternatively if this is a protocol change with RC server (which we haven't included in our current self-hosted version yet due to not having upgraded), feel free to close as solved issue; it seems odd on a first look though that only the count and not any other status (for the "dot" indicator) is taken into account anymore.

### Current Behavior
Badge notification updates as long as you have mentions but stays stuck on the last value.

### Expected Behavior
Dock badge should clear after the last message has been read.

**Comment by engelgabriel** [comment]
Thanks for the fix. I'll release later tonight.

**Comment by G00fY2** [comment]
@engelgabriel any news? The issue is quite annoying.

Keep up the great work!

**Comment by himpierre** [comment]
Yeah, what happend to "I'll release later tonight." :-)

thanks and cheers
