### ISSUE TITLE
Changelog for latest versions is missing

### ISSUE THREAD

**Issue by der-eismann** [RocketChat/Rocket.Chat.Electron#796]
Dear devs, I am still waiting for the changelogs or release notes on your latest releases. The download page on GitHub only mentions `bump version to 2.12.0` and [HISTORY.md](https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/HISTORY.md) was abandoned 9 months ago.
I think you understand that I am not going to read every commit that happened in the past, but I want to know what changed before I update all clients in the company.

**Comment by dzienisz** [comment]
this is very important to update changelogs!
