### ISSUE TITLE
2.12.0 macos notification in dock stays at "1" although no unread message

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat.Electron#797]
## My Setup
- Operating System: Mac OS High Sierra
- App Version: 2.12.0

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Since upgrading to 2.12.0 the dock notification shows i have one unread message although all messages are read.

### Current Behavior
Notification of 1 unread message.

### Expected Behavior
No notification should be shown.

![bildschirmfoto 2018-08-06 um 14 44 17](https://user-images.githubusercontent.com/40269193/43717273-4a2e49a6-9987-11e8-8c6a-bac7e3c604a7.png)

**Comment by TriPhoenix** [comment]
See also #794 :-)

**Comment by himpierre** [comment]
close in favour of #794
