### ISSUE TITLE
Message notification on app drawer doesn't vanish [macOS High Sierra]

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat.Electron#801]
_From @diggamies on August 6, 2018 10:41_

### Description:

Even after i have read all unread messages within my chats the notification counter in the app drawer remains to show 1 unread message.

### Steps to reproduce:

1. Get a message after you started the desktop application
2. Read all the unread messages
3. Look into your app drawer

### Expected behavior:

After i have read all the messages, there should not be an unread message left.

### Actual behavior:

![screen shot 2018-08-06 at 12 38 06](https://user-images.githubusercontent.com/25078320/43712171-9b62b7c4-9975-11e8-8e98-5378a71a6ee0.png)

### Server Setup Information:

- Desktop app version: 2.12.0
- Version of Rocket.Chat Server: 0.66.3
- Operating System: macOS High Sierra
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 8.9.3
- MongoDB Version: 3.6.5

### Additional context

Until i got the update this morning, everything was working as expected

_Copied from original issue: RocketChat/Rocket.Chat#11680_

**Comment by foraern** [comment]
Same issue with 2.12.0

**Comment by DerUser** [comment]
a reboot of the app seems to update der app drawer in 2.12.0.

I guess only the clear code at startup is working?

**Comment by TriPhoenix** [comment]
Not having looked at the surrounding code too much, I assume after a restart the app starts "clean" and then updates with the current state. The clear code is never run, just that after a restart no badge is set. PR #795 fixes this by always updating the state (either setting a badge or resetting the badge)

**Comment by engelgabriel** [comment]
Can you please try the https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.13.0-develop ?

**Comment by DerUser** [comment]
Tried it and works again.

**Comment by c-hoeger** [comment]
2.13.0 still shows the same behavior to me. Last version without was 2.11.0.

**Comment by a1dutch** [comment]
2.13.0 still shows the 1 unread notification for me too

**Comment by himpierre** [comment]
2.13.0-dev works for me. @a1dutch and @c-hoeger are you guys sure you use 2.13.0-dev? Maybe you have both version (2.12.0 and 2.13.0-dev) installed? They renamed the app back to Rocketchat so if you installed 2.13.0-dev it's possible 2.12.0 is still there.

**Comment by remofritzsche** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.13.0-develop works for me. As @himpierre stated, I had to rename the executable as the names did not match. Thanks for your work 👍

**Comment by a1dutch** [comment]
it was using the wrong app as you suggested, still seeing the unread badge and unread message on the chat window, event though it read

**Comment by engelgabriel** [comment]
The reason we have not released yet, as we are trying to make a migration script to rename the executable to remove the + from the name.

**Comment by engelgabriel** [comment]
I have just released 2.12.1, please reopen this issue if the problem persists.

**Comment by compuguy** [comment]
@engelgabriel Looks like 2.12.1 fixed this issue for me.

**Comment by c-hoeger** [comment]
unfortunately that version does not show any new message indication in the app icon at all.

**Comment by c-hoeger** [comment]
> unfortunately that version does not show any new message indication in the app icon at all.

Reinstallation with AppCleaner solved that issue.

**Comment by c-hoeger** [comment]
> Reinstallation with AppCleaner solved that issue.

only for some time... now it stopped working again :(

**Comment by taliesinb** [comment]
I get no badge count in 2.13.3.

**Comment by taliesinb** [comment]
@c-hoeger this issue is closed. I opened a new one: https://github.com/RocketChat/Rocket.Chat.Electron/issues/906

**Comment by taliesinb** [comment]
@c-hoeger this issue is closed. I opened a new one: https://github.com/RocketChat/Rocket.Chat.Electron/issues/906
