### ISSUE TITLE
New all-white tray icon difficult to see on light taskbar

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat.Electron#804]
_From @chowbok on August 7, 2018 18:41_

I have a light-grey taskbar. The new white tray icon in 2.12.0 is nearly impossible to see on there. Can it be made to have a black outline so that it's visible regardless of one's color scheme?

_Copied from original issue: RocketChat/Rocket.Chat#11695_

**Comment by tassoevan** [comment]
_From @kaiiiiiiiii on August 7, 2018 18:56_

Wrong repository mate :)

Fix which should be pushed with the next release:
https://github.com/RocketChat/Rocket.Chat.Electron/pull/791

// CC: @TwizzyDizzy

**Comment by tassoevan** [comment]
_From @chowbok on August 7, 2018 19:3_

Sorry about that. This is where the app sent me when I selected "report an issue" from the menu. I'm on Linux, by the way. Guess I should have mentioned that, sorry.

**Comment by engelgabriel** [comment]
@chowbok can you please share a screenshot so we can see how it looks and how other icons are being rendered too?

**Comment by wrosenauer** [comment]
Since I guess I have the same issue.
![grafik](https://user-images.githubusercontent.com/1312102/44535897-75e8e700-a6fb-11e8-9546-393b9db4fe3a.png)

**Comment by engelgabriel** [comment]
Ok, we will add a shadow

**Comment by HappyTobi** [comment]
I think on windows a colored Logo is more commo

**Comment by engelgabriel** [comment]
Even on windows 10?

**Comment by engelgabriel** [comment]
Or we can add an option for people to choose from BW or Colored

**Comment by HappyTobi** [comment]
On Windows 10 there are some in color and some in white.
I think also that we need a switch to toggle the icon colors (also for the osx menu bar)
