### ISSUE TITLE
Windows notification icon changed from 2.11.0 to 2.12.0

### ISSUE THREAD

**Issue by jswolf19** [RocketChat/Rocket.Chat.Electron#805]
## My Setup
- Operating System: Windows 10
- App Version: 2.11.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

In 2.11.0, the system tray icon had logically 3 visible states.

- No unread messages
- unread messages
- some number of unread messages directed at the current user

In 2.12.0, the icons were changed from png to ico files, but all the ico files are the same, so that there are only two logical states

- No unread messages
- unread messages

### Current Behavior

The user cannot differentiate between unread messages and unread messages directed at themself without displaying the app's main window.

### Expected Behavior

The user should be able to see the number of unread messages directed at themself (1 - 9+), or no number if the unread messages are all not directed specifically at the current user. (Personally, the number of unread direct messages is not as important as whether there are any vs. all undirected unread messages).

**Comment by HappyTobi** [comment]
See also the discussion from [#769](https://github.com/RocketChat/Rocket.Chat.Electron/pull/769)
Right now there are only one icon for all states and unread message count

**Comment by engelgabriel** [comment]
We will update the icons on the next release

**Comment by ccfiel** [comment]
I still got this problem. Any solutions on this?

**Comment by tassoevan** [comment]
Closed by #959.
