### ISSUE TITLE
VideoChat on OSX without Camera is unusable

### ISSUE THREAD

**Issue by markusstoll** [RocketChat/Rocket.Chat.Electron#810]
## My Setup
- Operating System: OSX 10.13.6
- App Version: 2.11.0

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
opening a video call without having a camera installed (so actually its a voice call and meant to be a voice call), the controls are hidden by some messages of the video call UI and you cannot remove these messages -> so the controls are nor usable!
![bildschirmfoto_2018-08-10_um_11_18_00](https://user-images.githubusercontent.com/1909884/43949911-31d96ee8-9c8f-11e8-9d6b-85d1aa26f5d9.png)

**Comment by eduplessis** [comment]
Same here but 
Windows 10
App version 2.14.7

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
