### ISSUE TITLE
Incorrect notifications count on the Dock Icon

### ISSUE THREAD

**Issue by nohorbee** [RocketChat/Rocket.Chat.Electron#811]
## My Setup
- Operating System: MacOS Sierra 10.12.6 (16G1510)
- App Version: 2.12.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
After updating to the version 2.12.0, The notifications count on the Dockbar Icon is wrong. Some of the read messages actually work (notifications--), and some of them don't. I can't find a pattern (yet)

### Current Behavior
Notifications count on the Dock icon is wrong

### Expected Behavior
The notifications count should match to the unread messages/notifications count

**Comment by kaiiiiiiiii** [comment]
Duplicate of #801

//CC: @tassoevan

**Comment by nohorbee** [comment]
Thanks! I'll close it right now
