### ISSUE TITLE
Fix tab completion when typing someone's name.

### ISSUE THREAD

**Issue by bgupta** [RocketChat/Rocket.Chat.Electron#82]
If I am directing a message at "bgupta", I should be able to type @b and then tab, to get a list of names that start with "b" (Like most IRC clients.) It currently has a weird behaviour when I use it now on the Mac desktop client. Hitting tab repeatedly should cycle through those that start with the substring already typed. For example if there is another user called "brothers", @b then tab should first highlight bgupta, and if I hit tab again cycle to @brothers.

**Comment by graywolf336** [comment]
Does this happen on the browser version? Or is the browser version handled differently?

**Comment by rodrigok** [comment]
This is not related with the Desktop Client. The `tab` acts as the `enter` key in this case
