### ISSUE TITLE
is it possible to have the downloading progress status on Windows/Mac Electron

### ISSUE THREAD

**Issue by edisonchen1985** [RocketChat/Rocket.Chat.Electron#826]
Hi guys, we are using RocketChat a lot everyday, and it is amazing. But we will always encounter an issue when we try to download the file from RocketChat with the Mac Election version, that we do not know if the file has finished downloading or not. It will be failed to open if the downloading has not completed. If we open the RocketChat through a Chrome tab page, we can see the downloading progress. 

So is it possible for Electron to have that? Thanks a lot!

**Comment by engelgabriel** [comment]
Good point, we will investigate.

**Comment by ggazzo** [comment]
We have developed the download page, I you can see the progress there
