### ISSUE TITLE
macOS application from pkg crashes on launch because codesign

### ISSUE THREAD

**Issue by MichalMMac** [RocketChat/Rocket.Chat.Electron#828]
macOS version of RocketChat 2.12.1 from dmg works fine.
However pkg installer installs app which crashes during lauch probably because of codesigning related problem. See attached crashlog.

```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```

[Rocket.Chat+_2018-08-20-153426_HungryHippo.crash.zip](https://github.com/RocketChat/Rocket.Chat.Electron/files/2302565/Rocket.Chat%2B_2018-08-20-153426_HungryHippo.crash.zip)

**Comment by engelgabriel** [comment]
The last working version was before `rocketchat-2.10.2.pkg`

**Comment by engelgabriel** [comment]
The Develop is also broken

![image](https://user-images.githubusercontent.com/1000217/44469798-a5fe9000-a5fe-11e8-9839-bf25f7a95312.png)

**Comment by engelgabriel** [comment]
Seems to be trying to upload the .pkg file twice

![image](https://user-images.githubusercontent.com/1000217/44470106-4ce32c00-a5ff-11e8-9d73-320864e14f80.png)

**Comment by tassoevan** [comment]
@engelgabriel 

I didn't see the same error about unsigned pkg (probably because I was installing it via `installer` command in terminal), just the crash reported by @MichalMMac. It isn't the package file which is corrupted, but the Electron executable itself.

Also, the file name changed due to electron-builder fix for `artifactName` property (from `rocketchat-${version}` to `Rocket.Chat-${version}`. I saw this happening in Windows builds yesterday, I'm going to patch it.

**Comment by MichalMMac** [comment]
I see the crash again with 2.13.1.

**Comment by tassoevan** [comment]
@MichalMMac Are you installing `rocketchat-2.13.1.pkg` or `rocketchat-2.13.1-mas.pkg`?

**Comment by MichalMMac** [comment]
@tassoevan I am installing ocketchat-2.14.pkg. I looks it works OK. This issue can be probably closed.

**Comment by tjanson** [comment]
Just FYI: I upgraded to 2.17 (using the auto-updater, which prompted me) and it crashed with termination reason `CODESIGNING`. I did not keep a crash log or anything; I just downgraded to 2.16.2.

**Comment by tassoevan** [comment]
@tjanson What MacOS version are you running?

**Comment by tjanson** [comment]
@tassoevan latest Catalina: `macOS 10.15.1 (19B88)`
