### ISSUE TITLE
Selecting menu item View -> Toggle Tray Icon crashes app when turning toggling tray icon off

### ISSUE THREAD

**Issue by martinky24** [RocketChat/Rocket.Chat.Electron#829]
## My Setup
- Operating System: macOS 10.13.6
- App Version: 2.12.1

- [X] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

1. Go to menu item View -> Toggle Tray Icon to turn tray icon off. (assuming it is on by default)
2. Go to menu item View -> Toggle Tray Icon to turn tray icon on again.
3. Go to menu item View -> Toggle Tray Icon to turn tray icon off again. This crashes reliably.

### Current Behavior

After turning tray icon on, next instance of turning it off crashes the app.

### Expected Behavior

No crash.

Here is the macOS generated crash report:

[Rocket.Chat+_2018-08-20-170214_Kyles-MacBook-Pro.crash.zip](https://github.com/RocketChat/Rocket.Chat.Electron/files/2304076/Rocket.Chat%2B_2018-08-20-170214_Kyles-MacBook-Pro.crash.zip)

**Comment by tassoevan** [comment]
Looks like [a bug in Electron](https://github.com/electron/electron/issues/9982), but maybe we can work around it.

**Comment by tassoevan** [comment]
Removing the tray icon's context menu hides the problem. It can be a memory leaking issue.

**Comment by senid231** [comment]
still not working

```
$ flatpak info chat.rocket.RocketChat 

Rocket.Chat - Open Source Team Communication

          ID: chat.rocket.RocketChat
         Ref: app/chat.rocket.RocketChat/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.7.8
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 227.7 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: c386b676ebfcf6f7e892b02fbfdd6f2117e90b57036cd33b0f1c8e5f7a1198d5
      Parent: e894fa7674c337c6cdc77273cd6888b8aa98341c4856e07d7b083a18ff7966a1
     Subject: Update to v3.7.8 (c22b3c02)
        Date: 2022-02-25 12:25:28 +0000
```
