### ISSUE TITLE
With firefox on the mac, it's really hard to hit the gear next to a message

### ISSUE THREAD

**Issue by bgupta** [RocketChat/Rocket.Chat.Electron#83]

**Comment by engelgabriel** [comment]
Is this only on the Electron App?

**Comment by lvh1** [comment]
Do you mean this? https://github.com/RocketChat/Rocket.Chat/issues/1985

**Comment by pcn** [comment]
It's approximately that.

**Comment by graywolf336** [comment]
Closing, as it's an issue with the Rocket.Chat project and not Electron.
