### ISSUE TITLE
Integrate standard macOS menu

### ISSUE THREAD

**Issue by c-hoeger** [RocketChat/Rocket.Chat.Electron#830]
Please integrate the standard macOS menu containing useful stuff like looking up words in the dictionary or in the internet.
See attached screenshot.
![screen shot 2018-08-21 at 7 57 49](https://user-images.githubusercontent.com/4416051/44383314-a3296f80-a518-11e8-8ad2-d923f31c2d14.png)

**Comment by tassoevan** [comment]
Related to #215.

**Comment by c-hoeger** [comment]
JFYI: I created a basic integration in my own fork. That's how it would work for me: https://github.com/c-hoeger/Rocket.Chat.Electron/commit/37d38b86c32b79c9c84546781bd971af9d67be43

**Comment by c-hoeger** [comment]
Unfortunately the macOS services Menu integration of Electron isn't really satisfying. Most interesting stuff doesn't seem to work. See also https://github.com/electron/electron/issues/8394

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
