### ISSUE TITLE
Dock notification not showing on macOS

### ISSUE THREAD

**Issue by tonyjames** [RocketChat/Rocket.Chat.Electron#831]
I am running Rocket.Chat 2.12.1 on macOS 11.1.2 and am not seeing the notification dot on the Rocket.Chat icon on the dock.

**Comment by engelgabriel** [comment]
Can you please try the version Version 2.12.2 from the Mac App Store?

**Comment by isdneuroimaging** [comment]
Issue remains in 2.13.1

**Comment by c-hoeger** [comment]
Did you by chance toggle the tray icon? Then you might have the same problem as I reported via https://github.com/RocketChat/Rocket.Chat.Electron/issues/855

**Comment by isdneuroimaging** [comment]
Nice! c-hoeger identified the source of the problem. But this is still unexpected behaviour, right? Hiding the tray (menu bar) icon should not disable the dock notifications.

**Comment by c-hoeger** [comment]
> Nice! c-hoeger identified the source of the problem. But this is still unexpected behaviour, right? Hiding the tray (menu bar) icon should not disable the dock notifications.
That's why I opened https://github.com/RocketChat/Rocket.Chat.Electron/issues/855

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
