### ISSUE TITLE
Desktop client: unread channels are bad highlighted

### ISSUE THREAD

**Issue by tuxmartin** [RocketChat/Rocket.Chat.Electron#841]
Please improve highlight of channels with unread messages. Bold font/color/number/...

#general has unread messages but looks almost the same as channels without unread messages.

![rc](https://user-images.githubusercontent.com/1219067/44645926-b6858080-a9d9-11e8-9092-d648708884c0.png)

Look at Slack client for comparison:
![slack](https://user-images.githubusercontent.com/1219067/44645927-b6858080-a9d9-11e8-9edc-b244252da4a5.jpeg)

**Comment by engelgabriel** [comment]
Thanks for the report @tuxmartin but you have to open this issue on the main project https://github.com/RocketChat/Rocket.Chat as this is an in-app design, and cannot be changed on the Electron wrapper app level.
