### ISSUE TITLE
Add "All Unreads"

### ISSUE THREAD

**Issue by tuxmartin** [RocketChat/Rocket.Chat.Electron#843]
Please add `All Unreads` feature as in Slack. It is very useful.

![slack_all_unreads](https://user-images.githubusercontent.com/1219067/44666851-9aa1cf00-aa19-11e8-9104-b270109e09b8.png)

**Comment by engelgabriel** [comment]
Thanks for the report @tuxmartin but you have to open this issue on the main project https://github.com/RocketChat/Rocket.Chat as this is an in-app design, and cannot be changed on the Electron wrapper app level.
