### ISSUE TITLE
32-bit version of Windows is not supported in 2.13.0

### ISSUE THREAD

**Issue by abicur** [RocketChat/Rocket.Chat.Electron#845]
## My Setup
- Operating System: Windows7 32-bit version
- App Version: 2.13.0

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description
Installer with 2.12. * version of application supported the 32-bit version of Windows. Installation 2.13.0 does not work on the 32-bit version of Windows.
![image](https://user-images.githubusercontent.com/40180391/44701572-cd46d880-aaa8-11e8-9d5d-31cd4141431a.png)

### Current Behavior
Can't install 2.13.0 version of application on 32-bit version of Windows.

### Expected Behavior
Have the opportunity to install 2.13.0 version of application on 32-bit version of Windows.

**Comment by bkraul** [comment]
I know I do not have a whole lot of clout when it comes to decisions for the project 😿 . We use Rocketchat in our organization, where Windows 7, 32bit is a requirement for the foreseeable future. I'm just curious what is the reasoning behind no longer supporting 32bit?

**Comment by abicur** [comment]
@bkraul, we are in the same situation. We have a lot computers with Windows-7 32-bit. So we cant update or install Rocket.Chat app on them. Rocket.Chat app supports 32-bits installation on Linux distr, so I think supporting 32-bit Windows system will be the right decision.

**Comment by tassoevan** [comment]
@bkraul `electron-builder` issues introduced when we tried new build targets. It's near to impossible to build all targets without breaking at least one of them. The Windows was neglected due to some error when signing the AppX. I expect to fix everything ASAP, but testing will be harder now.

**Comment by abicur** [comment]
@tassoevan as I understand problem not exactly in 32-bits build?
if return previous state of release command: 
`"gulp.task('release:win32', () => build({ publish, ia32: true, x64: true, win: [ 'nsis', 'appx' ] }));"`
And run it  then in the output I recived executable that work in 32-bit Windows.

**Comment by tassoevan** [comment]
@abicur This configuration was causing this error: https://ci.appveyor.com/project/RocketChat/rocket-chat-electron/build/1.0.745

**Comment by abicur** [comment]
@tassoevan Hm.. I am build it in Windows 10 x64 with:
`
gulp.task('release:win32', () => build({ publish, ia32: true, x64: true, win: [ 'nsis', 'appx' ] }));
`
Result:
```
E:\git-repos\Rocket.Chat.Electron>git status
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   tasks/release.js

no changes added to commit (use "git add" and/or "git commit -a")

E:\git-repos\Rocket.Chat.Electron>yarn release
yarn run v1.9.4
$ gulp release --env=production
[22:16:58] Using gulpfile E:\git-repos\Rocket.Chat.Electron\gulpfile.js
[22:16:58] Starting 'public'...
[22:16:58] Starting 'i18n'...
[22:16:58] Starting 'bundle'...
[22:16:58] Starting 'less'...
[22:16:58] Starting 'environment'...
[22:16:58] Starting 'release:win32'...
  • electron-builder version=20.28.2
Circular dependency: src\scripts\sidebar.js -> src\scripts\webview.js -> src\scripts\sidebar.js
Circular dependency: src\scripts\sidebar.js -> src\scripts\menus.js -> src\scripts\menus\view.js -> src\scripts\sidebar.js
[22:16:59] Finished 'bundle' after 834 ms
  • loaded configuration file=E:\git-repos\Rocket.Chat.Electron\electron-builder.json
[22:16:59] Finished 'environment' after 973 ms
[22:16:59] Finished 'less' after 992 ms
[22:16:59] Finished 'i18n' after 1.16 s
  • writing effective config file=dist\builder-effective-config.yaml
[22:17:02] Finished 'public' after 4.22 s
[22:17:02] Starting 'build-app'...
[22:17:02] Finished 'build-app' after 70 μs
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=spellchecker
  • rebuilding native dependency name=@paulcbetts/system-idle-time
  • packaging       platform=win32 arch=x64 electron=2.0.8 appOutDir=dist\win-unpacked
  • building        target=AppX arch=x64 file=dist\rocketchat-setup-2.14.0-develop.appx
  • rebuilding native production dependencies platform=win32 arch=ia32
  • rebuilding native dependency name=spellchecker
  • AppX is not signed reason=Windows Store only build
  • rebuilding native dependency name=@paulcbetts/system-idle-time
  • packaging       platform=win32 arch=ia32 electron=2.0.8 appOutDir=dist\win-ia32-unpacked
  • building        target=AppX arch=ia32 file=dist\rocketchat-setup-2.14.0-develop.appx
  • building        target=nsis file=dist\rocketchat-setup-2.14.0-develop.exe archs=x64, ia32 oneClick=false
  • AppX is not signed reason=Windows Store only build
  • building block map blockMapFile=dist\rocketchat-setup-2.14.0-develop.exe.blockmap
[22:18:13] Finished 'release:win32' after 1.25 min
[22:18:13] Starting 'release'...
[22:18:13] Finished 'release' after 6.33 μs
Done in 77.85s.
```

The resulting installation files work in windows 32-bit:

![image](https://user-images.githubusercontent.com/40180391/44739298-cfdd1880-ab10-11e8-9da9-711d616a92f5.png)

**Comment by tassoevan** [comment]
I believe there was a corrupted cache in CI server. `2.13.1` should bring back the 32-bit build.
