### ISSUE TITLE
Multiple, weirdly rendered instance of Rocket in Windows Volume Mixer

### ISSUE THREAD

**Issue by richkeenan** [RocketChat/Rocket.Chat.Electron#85]
Hi team,

Rocket Chat has added a bunch of instances of itself to the Windows Volume mixer. Check out the attached image for details, it'll be much clearer than me trying to explain it because it looks really odd!

![rocket_audio](https://cloud.githubusercontent.com/assets/1126680/12582460/2c398fc0-c435-11e5-981c-9f24db91a408.PNG)

When I plug in a USB headset (Logitech USB Headset) I get another Rocket instance in the Volume Mixer so it seems related to the devices I have plugged in.

I'm running Windows 7 Pro SP 1.

Let me know if you need any more details

**Comment by graywolf336** [comment]
Please try the latest beta version, I haven't experienced it any today.

**Comment by richkeenan** [comment]
Thanks @graywolf336, 1.0.0-Beta 1 has resolved the issue.
