### ISSUE TITLE
Feature Request: Add option to add file path instead of real file

### ISSUE THREAD

**Issue by Anguel** [RocketChat/Rocket.Chat.Electron#850]
It would be very nice to have the option to add/drag&drop only the **file path** instead of the complete file in the chat. Often colleagues only need the path to a file. This is great especially for large files or files that may change. Maybe this feature can be added as an option in the upload file dialog.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
