### ISSUE TITLE
nap repo is not updated for rocketchat-desktop. It still has 2.7.0 for rocketchat-desktop while 2.13 is available elsewhere

### ISSUE THREAD

**Issue by icerootsvw** [RocketChat/Rocket.Chat.Electron#853]
I hope this time i pickud up the correct play to open a bug

Initial i opened this one but as it seems it was not the right place
https://github.com/RocketChat/Rocket.Chat/issues/11912

My issue is that the snap repo does have an old rocketchat-desktop version (2.7  https://uappexplorer.com/snap/ubuntu/rocketchat-desktop ) while the rocket chat website itself is offering already 2.13 for the desktop

From my point of view this is a bug because snap is not refreshed anymore but related to the answers from my initial bug report i am not sure anymore if i am understanding it correctly how to install the client on GNU/Linux the right way or if i just mixed up the places where to open bugs

**Comment by icerootsvw** [comment]
Hi tassoevan,
thank you very much for your feedback. That would mean that in the future snap can be used to have a valid and up to date source to install rocketchat-desktop on GNU/Linux systems?

**Comment by dacrome** [comment]
@tassoevan but why do you recommend to install it via snap in your documentation if it is not up-to-date? https://rocket.chat/docs/installation/mobile-and-desktop-apps/#linux
Hope you publish new snaps soon, because we need the auto-update feature.

**Comment by icerootsvw** [comment]
Any Updates on this topic?
I see in the Release lists there is always also a *.snap file (https://github.com/RocketChat/Rocket.Chat.Electron/releases)
But my snap repo still shows 2.7 instead if 2.14.x 

So is the push to snap still missing? Or will there be no further snap updates? Maybe then the snap repo should be removed completely to not confuse users?

At the moment i have to visit the release page by hand, download the deb file and install it. A deb repo (or snap) would be prefered to always get the newest (security) updates

**Comment by tassoevan** [comment]
Version 2.14.6 was pushed to snapcraft and the next releases should be published automatically.
