### ISSUE TITLE
Windows - Rocketchat should exit not minimize when clicking the X in the upper right corner.

### ISSUE THREAD

**Issue by cgahlon** [RocketChat/Rocket.Chat.Electron#854]
## My Setup
- Windows 7, 10
- App Version: 2.13.0

- [X ] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When clicking the X in the upper right corner the expected and normal behavior is for a program to exit.  Can you please add the option to EXIT instead of corrupting the UI experience al. a. Discord?

### Current Behavior
Program hangs around in the system tray.

### Expected Behavior
The program actually exits.

**Comment by jmledantec** [comment]
#847 same issue ?

**Comment by Anguel** [comment]
I think it is the exact opposite. The other user wants the program to **go to the task bar** and not to the tray as it does now - this is great to make RocketChat blink in taskbar when new messages arrive and I would love to see this feature too.
In contrast, this user wants to **close** the program completely.

**Comment by bkraul** [comment]
It is a UI common behavior with resident programs to have the X minimize to tray, with an option to exit from the program menu or the tray icon. This is not "corrupted" behavior. If anything, an option could be added to the program to allow "X" to completely close the program. I have seen this on other systems.

**Comment by aba-rechsteiner** [comment]
The problem for my clients is that nothing happens when the chat client is minimized and the user clicks on the desktop icon.

**Comment by bkraul** [comment]
Then I would guess that would be where the correction would be needed, to make sure to activate the app when the desktop icon is clicked. Right now the app comes right up with you click on the systray icon, or when you click on the taskbar button.

**Comment by aba-rechsteiner** [comment]
@engelgabriel @tassoevan can you have a look at this?

**Comment by stopal** [comment]
I can reproduce this behaviour on on my Linux Client:
Client Version 2.13.0
running on Fedora 28

**Comment by cgahlon** [comment]
This issue has squirreled off from the original request to have an option added to actually close the program when clicking the X.  This feature would not have changed the default behavior.  I am closing this isuse.

**Comment by bkraul** [comment]
Actually, the original request came in as a bug. The option came as the discussion of whether this was a feature to add instead of a bug. Granted, if the feature to have the option to close with X is not added, this remains a bug.
