### ISSUE TITLE
Disabling Tray Icon also disables App Icon new message notifications

### ISSUE THREAD

**Issue by c-hoeger** [RocketChat/Rocket.Chat.Electron#855]
## My Setup
- Operating System: macOS High Sierra
- App Version: 2.13.1

When the Tray Icon is toggled to off, the App Icon no longer indicates new messages.
As soon as it is toggled on again, new messages are also indicated in the App Icon.
This problem starts with Rocket.Chat versions newer then 2.11.0.

![screen shot 2018-09-03 at 9 25 56](https://user-images.githubusercontent.com/4416051/44973015-6a978600-af5b-11e8-8127-4fea51df9292.png)

**Comment by isdneuroimaging** [comment]
You are absolutely right. Dock icon badges work when the tray (menu bar) icon in macOS is visible.

**Comment by HappyTobi** [comment]
I‘ve fixed it already, i will send the pr later
