### ISSUE TITLE
Desktop notifications not working after updating to 2.13.1

### ISSUE THREAD

**Issue by Jasonoro** [RocketChat/Rocket.Chat.Electron#856]
## My Setup
- Operating System: Windows 10 1803
- App Version: 2.13.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

After installing 2.13.0 desktop notifications work fine and the "Test desktop notifications" button gives the test message. Updating with the build-in updater to 2.13.1 breaks both the test button and normal notifications. Trying the notifications in Chrome works fine.

### Current Behavior

After pressing the "Test desktop notifications" button nothing happens.

### Expected Behavior

A test message should display.

If you've got any more questions feel free to ask. I've tried on 2 computers and both have the same issue.

**Comment by alireza-salehi** [comment]
same issue on version 2.13.1
windows 10 1803 (17134.228),
desktop notification completely broken (tested on 5 computers.) no notification on new messages.

**Comment by robcalewar** [comment]
Same problem here as well. It's a problem with about 100 endpoints.

**Comment by dbenz04** [comment]
Same problem for me on Win10 1803 with RocketChat 2.13.1 or 2.13.2. I then went back and installed 2.13.0 and notifications work fine on that version.

**Comment by bkraul** [comment]
This might have to do with #868. I used to have notifications not work as well. Came to find out that I had 2 installations of RocketChat on the box. Once I uninstalled all existing RocketChat installations and reinstalled 2.13.2 from releases, the notifications came back.

**Comment by bkraul** [comment]
Granted, I had to clear all user data and re-login to the server.

**Comment by dbenz04** [comment]
You are correct, I had two versions installed. After uninstalling both, clearing user data, and reinstalling 2.13.2, my desktop notifications worked again.

Thanks!

**Comment by Jasonoro** [comment]
Updating to 2.13.2 seems to have fixed the issue. Closing issue as the problem is fixed.
