### ISSUE TITLE
Old version of RocketChat not uninstalled - Rocket 2.13.1

### ISSUE THREAD

**Issue by francoisa43** [RocketChat/Rocket.Chat.Electron#857]
## My Setup
- Operating System: Windows 10 1803
- App Version: 2.13.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
After installing the latest version of rocketchat, we realized that the old version of the software was not uninstalled.
Attached a screenshot of the windows application manager
What can we do ?

### Current Behavior
Do not uninstall old versions of rocketchat

### Expected Behavior
Uninstall old versions of rocketchat

![capture](https://user-images.githubusercontent.com/42959074/45017044-cf6be280-b026-11e8-9101-a3af68d302ad.JPG)

**Comment by shellster** [comment]
I've also validated this at least as far as 2.13.0 and 2.13.1 are concerned.

**Comment by icerootsvw** [comment]
I also had the issue that the client had 2 different names after the Update
![image](https://user-images.githubusercontent.com/40857785/45251163-d0ac5080-b341-11e8-9fb0-f125671f08f0.png)

Only RocketChat+ was able to start, the other (old) entry "Rocket.Chat" could not be started anymore under windowsd (no error message, just nothing happened".

Workaround was to remove "Rocket.Chat" but at the end we removed both installations and started with a clean installation.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
