### ISSUE TITLE
Cannot clean-up userdata via Application or Uninstall

### ISSUE THREAD

**Issue by shellster** [RocketChat/Rocket.Chat.Electron#859]
## My Setup
- Operating System: Windows 10
- App Version: 2.13.0 (Updated to 2.13.1 and still have the same issue)
- Server Version: 0.69.0 (Using Snap container, so it should be staying up to date)

- [ X ] I have tested with the latest version
- [ X ] I can simulate the issue easily

## Description
Today, while chatting with another user, Rocket Chat logged me out in the middle of my conversation.  I cannot log back in.  As soon as I log in, I briefly see the bar on the left, including missed messages, then it kicks me back to the login screen.  I've successfully continued to use a web browser and my Android app without any problems. 

Things I've tried to resolve the problem:
1) Uninstalled Rocketchat from my computer, and ticked the "Remove User Data" option and reinstall.
Incidentally the "Remove User Data" does not remove user data, because after reinstalling, it still took me to the login page for my server. 

2) Reboot the RocketChat server.

3) Delete the server in the application and uninstall, then reinstall.

4) Go to Help -> Reset AppData

So far, I am the only user experiencing this problem out of three on the server, and at least one other user is also using the Windows App on their Windows 10 machine.

## Finally Figured Out a Solution But It Shows a Couple Bugs:

Turned out the fix was to delete the Rocket.Chat folder under %Appdata% then relaunch the app and sign in.  Therefore I see two bugs.  First there is the issue of whatever state my cache got into where I couldn't log in, in the first place.  Then, more importantly, there is the issue, that all the things I tried above to delete the cache were not sufficient.  All three of which should have resulted in all of the local user data being cleaned up.  Possibly related, I have Rocket.Chat installed for "All Users on the System".  I'm guessing the uninstall and clean-up code is not checking %appdata% for every user on the machine, or even the current running user in that case.

Other relevant information:
I'm using the default authentication within RocketChat (not OpenID/SAML/LDAP or something else).

### Current Behavior
See above

### Expected Behavior
When I log in with credentials I know are valid, I expect to be logged in, and stay logged in, not immediately get booted back to the auth screen when using the Windows App.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
