### ISSUE TITLE
Track user status based on OS session

### ISSUE THREAD

**Issue by asmartin** [RocketChat/Rocket.Chat.Electron#86]
Hello,

I am very excited about the Rocket Chat desktop application, however it is unclear to me how it determines if a user is Online, Away, etc. Traditional desktop clients track if the OS is currently logged in or locked or mouse movement and update Online/Away based on that data, which is a lot more powerful and accurate. It seems that a lot of web-based chat programs just track if the chat programs webpage is currently in focus, which isn't as good of a status indicator. Does the Rocket Chat desktop app support deeper integration of user status, or how does it work?

Thanks!

**Comment by rodrigok** [comment]
We just track the web page, but, it's a good idea to improve

**Comment by vitamindck** [comment]
+1

this would be fantastic. I would also like to see the status of a person and how long they have been in that status in relative time.
