### ISSUE TITLE
chocolatey package for Rocket.Chat.Electron is deprecated

### ISSUE THREAD

**Issue by chantisnake** [RocketChat/Rocket.Chat.Electron#860]
I was the maintainer for the [chocolatey](https://chocolatey.org/) package for Rocket.Chat.Electron.
  I am deprecating the chocolatey package for Rocket.Chat.Electron because I no longer have time to maintain it.

  I have requested for another package maintainer here: https://github.com/chocolatey/chocolatey-package-requests/issues/414
  The chocolatey package page for Rocket.Chat.Electron : https://chocolatey.org/packages/rocketchat

  Sorry for all the inconvenience I have caused.

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
