### ISSUE TITLE
Downloading files with empty name (for example .gitignore)

### ISSUE THREAD

**Issue by Amomum** [RocketChat/Rocket.Chat.Electron#861]
## My Setup
- Operating System: Windows 7
- App Version: 2.13.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
1. Go to administration properties, enable file uploads and remove filters in "accepted media types".
1. Upload a file with empty name and extension - e.g. `.gitignore`.
1. Try to download it.

### Current Behavior
Download window appears after several minutes after clicking on the file.

### Expected Behavior
Download window should appear in the usual manner.

This issue doesn't seem to occur in the browser but that may be related to the list of allowed extensions on the server.

**Comment by reitzig** [comment]
I see something similar with a file called `payload`.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
