### ISSUE TITLE
main window is not displaying

### ISSUE THREAD

**Issue by Torhiss** [RocketChat/Rocket.Chat.Electron#862]
## My Setup
- Operating System:
Windoiws 10 Professionnel
- App Version:
rocketchat-setup-2.13.0
rocketchat-setup-2.13.1

- [X ] I have tested with the latest version
- [ X] I can simulate the issue easily

## Description

Same as issue #623 
Message: Windows client 2.13.1, on Win 10 Pro – main window is not displaying, chat still is active in taskbar and pop-ups doesn't appear on new messages, but chat window is not displaying (for less than second it flashes and then hides).
### Current Behavior

I'm starting application, it "flashes" (only canvas of the window are visible for some short time), then it completely disappears, meanwhile icon in the tray is running, pop-up notifications are working, and tray icon considers main window is visible.

### Expected Behavior

window to be shown
![rocket_windows_dont_show](https://user-images.githubusercontent.com/43041165/45168132-e19e7a00-b1fa-11e8-956d-8e08ad40426d.png)

**Comment by Torhiss** [comment]
Way to solve : 

1 - Uninstall Rocket client (keep data)
2 - Goto: C:\Users\[Username]\AppData\Roaming\Rocket.Chat
And Delete all following files : 

__installer.exe
certificate.json
Cookies
Cookies-journal
lockfile
Preferences
QuotaManager
QuotaManager-journal
Window-state-main.json (perhaps deleting this file only, works)

3 - Re-install Rocket client
Rocket main windows appear

**Comment by tassoevan** [comment]
Purging `window-state-main.json` should be enough for now.

**Comment by piotrkochan** [comment]
Hello, some teammates have same problem on Windows 10 and it returns almost every day https://github.com/RocketChat/Rocket.Chat.Electron/issues/878

**Comment by tassoevan** [comment]
@piotrkochan Is it really the same issue? Just deleting the `window-state-main.json` instead of the whole user data directory makes the window appear?

**Comment by piotrkochan** [comment]
We will try on monday. Still, even if purging `window-state-main.json` helps, is there a chance to fix that permanently in Rocket.Chat.Electron?
