### ISSUE TITLE
OSX Do Not Disturb mode is not respected with audio notifications

### ISSUE THREAD

**Issue by tomneedham** [RocketChat/Rocket.Chat.Electron#873]
## My Setup
- Operating System: OSX 10.13.6
- App Version: 2.13.0

- [ ] I have tested with the latest version
 - I can't do this, as the update fails to install
- [x] I can simulate the issue easily

## Description
When OSX is in Do Not Disturb mode, the notifications still make a audio sound. Very frustrating when in a call.

### Current Behavior
Noise still made when in DoNotDisturb Mode
### Expected Behavior
It shouldnt make a noise

**Comment by tomneedham** [comment]
I guess a filter needs to be added in here https://github.com/RocketChat/Rocket.Chat.Electron/blob/7cc3275680ceaca1272c5831f8749d392aa3f747/src/public/lib/Notification.js which extends the notification object used by the HTML client, and could check something like this to find the do not disturb status https://github.com/felixrieseberg/electron-notification-state

Or - PR upstream to the notification library you use, to check for this status and `error` the notification.

**Comment by tomneedham** [comment]
Hmm, actually the notification is blocked, but it is just the sound that isnt blocked. What code is responsible for the noise?

**Comment by tassoevan** [comment]
@tomneedham It is configured on server side. I'll check if we can enable/disable it based on the notification block.

**Comment by NiklasScheid** [comment]
Are there any future plans to fix this?

**Comment by sandover** [comment]
Problem here as well.

**Comment by sandover** [comment]
Still finding the bouncing Dock to be a problem.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by Feuermurmel** [comment]
I would like to re-open this issue.

I noticed this issue just yesterday with Rocket.Chat 3.8.4 on macOS 12.3.1. I was in some video call when an alert channel started triggering notifications every few seconds. This included Notification Center banners as well as audio. I quickly enabled Do Not Disturb. The banners stopped appearing but the notification sound still played for every new message.
