### ISSUE TITLE
Error while resizing or moving the window of the app (Windows 10)

### ISSUE THREAD

**Issue by slnblizzard** [RocketChat/Rocket.Chat.Electron#876]
## My Setup
- Operating System: Windows 10
- App Version: 2.13.2

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When you try to resize or move the window of the app (via mouse - drag and drop), a javascript error occurs:
![image](https://user-images.githubusercontent.com/42200965/45414335-60703880-b67b-11e8-8096-68a6a63eeab2.png)

### Current Behavior
Exception occurs

### Expected Behavior
The Windows should resize and move normally.

**Comment by tassoevan** [comment]
Are you using a commercial antivirus software?

**Comment by BradleyUffner** [comment]
I'm also having this problem in Windows 7.

**Comment by bestog** [comment]
I'm also having this problem in Windows 10. And antivirus software kaspersky 10

**Comment by slnblizzard** [comment]
@tassoevan 
we using kaspersky endpoint security 10

**Comment by tassoevan** [comment]
Is this error present in 2.13.3 too?

**Comment by OlivierCollin** [comment]
Not anymore at least on my machine (Windows 10 version 17134 with Kaspersky 10).

**Comment by BradleyUffner** [comment]
2.13.3 seems to have fixed the error for me also.

**Comment by slnblizzard** [comment]
2.13.3 also fixed the error for me
