### ISSUE TITLE
Tray icon does not show number of un-read messages anymore

### ISSUE THREAD

**Issue by tendo256** [RocketChat/Rocket.Chat.Electron#877]
## My Setup
- Linux and Windows :
- 2.13.xxx:

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

get the lastest version of rocket.chat app (from 2.12.xxx) let some-one send you a message and check the rocket.chat  system tray icon it will remain red but with no number of the un-read or new message(s) 
### Current Behavior

all the latest version (from 2.12.0 ) of rocket.chat app doesn't allow you to see the number of pending
### Expected Behavior

it has to show the number of pending, un-read or new message on the rocket-chat app at the system tray icon as it's in the old version  http://i.imgur.com/wTOcp91.png

**Comment by HappyTobi** [comment]
the tray icons are changed so the image count isn't shown anymore.
What can be done is to add a hover text if the rocket chat team want's that.

**Comment by micw** [comment]
> the tray icons are changed so the image count isn't shown anymore.

When and why exactly was that changed? I could not see anything about it in the release notes and our users complain about the missing badge.

**Comment by micw** [comment]
@tendo256 Bug title should probably changed to something like "Tray icon does not show number of un-read messages anymore"

**Comment by HappyTobi** [comment]
See the discussion here: https://github.com/RocketChat/Rocket.Chat.Electron/pull/769
