### ISSUE TITLE
Password change in RocketChat - Electron client does not start

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat.Electron#878]
## My Setup
- Operating System: Windows 10
- App Version: 2.13.2 

- [ x ] I have tested with the latest version
- [ ? ] I can simulate the issue easily

## Description
We are using domain account sync in our RocketChat. Some Windows users in our team reports problem, when they change their password in domain and run rocket chat, it does not start.

### Current Behavior

The problem happens when they were authenticated before and looks like Electron client have trouble to logout locally user and display login page.

### Expected Behavior

When user changed his password and was authenticated before then it should forget session and display login page.

## More info

Removing `AppData/Local/Rocketchat` directory helps but it is not fix forever ;)

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
