### ISSUE TITLE
[BUG] Status on the tray icon is always online, not equal to my current status

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Electron#883]
## My Setup

- Operating System: macOS
- App Version: 2.13.2

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

- When I open the app, my status is busy and the menu bar shows a green dot;
- If I change the status (only for my first server, 2+ never works) the color changes correctly;
- After a while the dot changes again to green;

Screenshots:

![screen shot 2018-09-17 at 09 54 40](https://user-images.githubusercontent.com/551004/45624109-b9671480-ba5f-11e8-9b89-372c39dc9f14.png)
![screen shot 2018-09-17 at 09 54 37](https://user-images.githubusercontent.com/551004/45624110-b9671480-ba5f-11e8-8424-a504a3e25cca.png)

### Expected Behavior

- It should always respect the user status;
- It should also works for the other users (not only the first server);

**Comment by HappyTobi** [comment]
It only works if you have the correct Server version

**Comment by rafaelks** [comment]
@HappyTobi What you mean by correct server version? I'm on 0.69.2.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
