### ISSUE TITLE
[2.13.3] Every letter adds a line to the writing chatbox. 

### ISSUE THREAD

**Issue by openseasite** [RocketChat/Rocket.Chat.Electron#886]
## My Setup
- Operating System: Windows 10 1803
- App Version: 2.13.3
- [ X ] I have tested with the latest version
- [ X ] I can simulate the issue easily

## Description
Every letter you type, adds a new line in the chatbox while writing.

**Comment by tassoevan** [comment]
This can be a known issue inside the Rocket.Chat server. @ggazzo Can you confirm it?

**Comment by kaiiiiiiiii** [comment]
#11904 That’s the one you looking for @tassoevan :)
