### ISSUE TITLE
Close Now Closes the Application

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Electron#89]
Previously closing the application would result in the application being put to the notifications area, that no longer happens with the 1.0.0 beta 1.

**Comment by flauschi** [comment]
+1 I have the same problem. Tried it under Windows 10 and Windows Server 2008 R2.

**Comment by sampaiodiego** [comment]
confirmed on linux

**Comment by giray** [comment]
+1 on ubuntu 15.10

**Comment by rodrigok** [comment]
Closed via #116
