### ISSUE TITLE
[huge bug] user is not activated, even if he is after activation

### ISSUE THREAD

**Issue by jwallet** [RocketChat/Rocket.Chat.Electron#891]
## My Setup
- Operating System: windows 10
- App Version: 2-11.0 and upper

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![rc](https://user-images.githubusercontent.com/23088305/45823348-7acd9600-bcbb-11e8-8ad2-73f0d48b5595.gif)
Admin changed the rules for authentication to use only gmail account with two way authentication, after that many users tried to logged in, but got the error above. 

then, the admin activated the users manually. 

but the error was still being displayed. 

we tried to reinstall rocket.chat, it did not work either.

we had to manually remove the appdata/local folder for rocket.chat, looks like it does not update the user status once the user is flagged has "not activated", after removing the folder and reinstalling RC everything works.

### Expected Behavior
that i don't need to remove manually rc local temp folder

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
