### ISSUE TITLE
Feature Request: Allow grouping users by Team or Project

### ISSUE THREAD

**Issue by Batlan** [RocketChat/Rocket.Chat.Electron#892]
Being in contact via direct messages with many people using Rocketchat results in a very long scrollable unsorted list of people. Most times I cannot find the person without the search function and o' dear when I do not remember the name of somebody that contacted me a couple of days ago with a question and now finally I got the answer.
Therefore it would be nice to be able to assign people to different "groups" e.g. team, project, ... and then display those users grouped using these collapsable "groups".

**Comment by tassoevan** [comment]
Issue moved to [RocketChat/Rocket.Chat #12119](https://github.com/RocketChat/Rocket.Chat/issues/12119) via [**ZenHub**](https://www.zenhub.com/)
