### ISSUE TITLE
Animation s

### ISSUE THREAD

**Issue by x8-999-github** [RocketChat/Rocket.Chat.Electron#893]
## My Setup
- Operating System:
Linux
- App Version:
2.11.0

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

People send animated gif

### Current Behavior

I get distracted by the gif/ can not concentrate as the gif keeps moving

### Expected Behavior

I would like a way to stop or hide the animations or play them only once or on hover.

**Comment by tassoevan** [comment]
Issue moved to [RocketChat/Rocket.Chat #12125](https://github.com/RocketChat/Rocket.Chat/issues/12125) via [**ZenHub**](https://www.zenhub.com/)
