### ISSUE TITLE
[Windows] Desktop Notifications Not Appearing

### ISSUE THREAD

**Issue by busches** [RocketChat/Rocket.Chat.Electron#897]
## My Setup
- Operating System: Windows 10 
- App Version: 2.13.3
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When I get a direct message or a message in a channel where I have notifications turned on, I get no notification popup.

### Current Behavior
Nothing.

### Expected Behavior
I get a notification for the specified duration length.

Note: Using the `Test Desktop Notifications` does work.
I changed the `Notification Duration` from default (0) to 10 and changed `Show Desktop Notifications For` to `All Messages`

After changing all of these settings, a different user who DMed me did generate a notification, but the original user I was testing with is not. I confirmed the notification settings for both users were the same.

**Comment by tassoevan** [comment]
Is this issue **not** reproducible in the web client?

**Comment by busches** [comment]
I hadn't tried, but it appears to be consistent in both. If I get a notification, I get it in both or don't in both. Looks to be a server issue. 👎
