### ISSUE TITLE
blank window when running rocket chat on macos

### ISSUE THREAD

**Issue by bbrendon** [RocketChat/Rocket.Chat.Electron#898]
## My Setup
- Operating System: macOS 10.13.6
- App Version: 2.13.3
- Installation type: dmg

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description

Install and load rocket chat. Screen is blank as described below. 
I tried:
* Uninstalling and reinstalling (sudo rm -rf /Applications/Rocket.Chat.app/)
* Cleaning out "find ~/ | grep -i rocket" files and directories and re-running the app

When I run it from the cli this is the output. I'm not sure if this is normal or not.
```
 /Applications/Rocket.Chat.app/Contents/MacOS/Rocket.Chat
2018-09-27 10:17:19.734 Rocket.Chat[67583:2828020] *** WARNING: Textured window <AtomNSWindow: 0x7fdf474aa310> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
Checking for update
Update for version 2.13.3 is not available (latest version: 2.13.3, downgrade is disallowed).
```

### Current Behavior

![image](https://user-images.githubusercontent.com/6364477/46162832-4703ea80-c23e-11e8-81d0-a5c5ae697866.png)

### Expected Behavior

The UI appearing.

**Comment by tassoevan** [comment]
Are you able to click the menu `View` > `Application - Toggle DevTools`?

**Comment by bbrendon** [comment]
Yes. that works but I'm not sure what to do next.

**Comment by tassoevan** [comment]
A small update on this topic for myself:
I discovered that this weird Chromium-related behavior happens if something is blocking the page loading and there is a certain amount of already parsed DOM elements. Removing a simple `<div>` element in the app page caused this blank window until all files were loaded. My new guess is that a blocking operation is not completing for some reason and blocking the page rendering.

**Comment by tassoevan** [comment]
@bbrendon Any change in 2.14.1?

**Comment by nodje** [comment]
I seem to have encountered this bug after trying to register on the Rocket Cloud page form the client.
Opening dev tools Console tells me:
```
webview: TypeError: Cannot read property 'userData' of undefined
webview: Uncaught TypeError: Cannot read property 'userData' of undefined
webview: Uncaught ReferenceError: Meteor is not defined
```
All coming from `webView.js:73`

All good but I'm really stuck! How do I re-init or revert back to normal? Restarting the client doesn't help.
Using `2.14.7`

**Comment by nodje** [comment]
Actually, opening Rocket chat today on a Wifi connection with a login portal, I realized that Rocket was stuck on a non-loading/blank webpage. 
So the issue in my case is: Rocket seems stuck on a webpage after clicking on a link with no apparent way to go back to the chat mode.

**Comment by bbrendon** [comment]
This issue was closed awhile back. Probably best to open a new one
