### ISSUE TITLE
Desktop version don't launch after server input

### ISSUE THREAD

**Issue by flpn** [RocketChat/Rocket.Chat.Electron#903]
So, after I enter the server URL the application dives into an infinite loading. After checking the devops tools I found this error:

> Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
C:\Users\felipe.netto\AppData\Local\Programs\Rocket.Chat\resources\app.asar\app\public\preload.js:75 
Uncaught ReferenceError: Meteor is not defined
    at C:\Users\felipe.netto\AppData\Local\Programs\Rocket.Chat\resources\app.asar\app\public\preload.js:75

Because of that I'm not able to use the desktop version of the Rocket. Any of you guys know what's happening?

**Comment by dwings** [comment]
Same for me. It seems that this is occuring in the desktop client as well as any web browser. Started after upgrading Windows to 1803.
Other clients in our company (most of them without the october upgrade) are not affected

**Comment by dwings** [comment]
> Same for me. It seems that this is occuring in the desktop client as well as any web browser. Started after upgrading Windows to 1803.
> Other clients in our company (most of them without the october upgrade) are not affected

This seems to be fixed with 2.14.3

**Comment by tassoevan** [comment]
@dwings Thank you for the feedback! Probably it was fixed by 01f6dcce361f5720930901dbd8975c69db623f69.
