### ISSUE TITLE
Badge count has dissappeared on macOS

### ISSUE THREAD

**Issue by taliesinb** [RocketChat/Rocket.Chat.Electron#906]
## My Setup

- Operating System: macOS
- App Version: 2.13.3
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Get a new message from a friend or colleague (or both!). The badge in the dock does not contain a "1", it used to in previous versions of RocketChat. This is quite an essential feature for knowing whether you need to check the app after being away from your computer. 

<img width="374" alt="image" src="https://user-images.githubusercontent.com/365157/46433343-e64e4380-c750-11e8-8d97-af8b33bca20e.png">

### Current Behavior

You don't get a badge count. 

### Expected Behavior

You should get a badge count.

**Comment by tassoevan** [comment]
I couldn't reproduce it in 2.13.3 and 2.14.0.

@taliesinb Is this happening for messages received in **any** Rocket.Chat server? I've tested it using https://open.rocket.chat, which is in the latest version.

**Comment by HappyTobi** [comment]
> I couldn't reproduce it in 2.13.3 and 2.14.0.
> 
> @taliesinb Is this happening for messages received in **any** Rocket.Chat server? I've tested it using https://open.rocket.chat, which is in the latest version.

On my client it also work as expected! Everything is fine 
Client: 2.14.0 
Server: 0.70.0

**Comment by javi076** [comment]
I still have this problem in ubuntu.
Client: 2.14.0

**Comment by tassoevan** [comment]
@javi076 Ubuntu versions with Gnome instead of Unity don't support badges anymore. Is that your case?

**Comment by javi076** [comment]
I'm using Ubuntu with Unity. The badge count worked with previous clients (2.11)

**Comment by nw-git** [comment]
I also have this problem on Windows, latest version, 2.14.1. The icon changes color, but doesn't show how many new messages have arrived. I'm reverting back to an old version until a fix is released.

**Comment by nw-git** [comment]
hey @tassoevan yep, this beta release fixed it. thanks. 

https://i.imgur.com/h0z6j5H.jpg

**Comment by taliesinb** [comment]
Sounds like this is solved... should I close it?
