### ISSUE TITLE
password is not deleted after the server is deleted from server list

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Electron#908]
## My Setup
- Operating System: Xubuntu 18.04 LTS
- App Version: 2.13.2, 2.15.0-develop
- Installation type: [dpkg package](https://github.com/RocketChat/Rocket.Chat.Electron/releases)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

After a server has been deleted from the "Server List", the password is still stored locally.

### Current Behavior

1. add a server
2. log on to the server with a local user
3. delete the server from the "server list" in the left navigation
4. terminate the client
5. restart the client
6. add the server again
The password still exists. The user is logged in immediately without having to authenticate.

### Expected Behavior

When deleting a server, the cached password should also be deleted.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
