### ISSUE TITLE
You can't drop MacOS Mojave screenshot into conversation.

### ISSUE THREAD

**Issue by dzienisz** [RocketChat/Rocket.Chat.Electron#910]
## My Setup
- Operating System: MacOS Mojave
- App Version: 2.13.2

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

I make screenshot with new MacOS Mojave tools. It appear in right down corner and you can't take this screenshot and drop into conversation.

### Current Behavior

I can't drop it.

### Expected Behavior

You should be able to drop it.

**Comment by damian-centrone** [comment]
This is now working as expected.
