### ISSUE TITLE
Flatpak Rocket.Chat.Electron freezes after some time

### ISSUE THREAD

**Issue by andrevmatos** [RocketChat/Rocket.Chat.Electron#917]
## My Setup
- Operating System: Arch Linux Testing
- App Version: 2.13.3
- Installation type: flatpak 1.0.3-1

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
I'm the creator and maintainer of the [Flathub's chat.rocket.RocketChat](https://github.com/flathub/chat.rocket.RocketChat) package. Since a couple of versions (not sure when, maybe 2.11 or 2.12), noticed that after some random time (from a couple of minutes to a couple of hours after app's startup), the Electron app simply freezes. Not even hover animations working, completely frozen. Killing the window through the DE tool (I use Plasma) isn't enough to kill all processes, requiring going to the htop or alike to kill all the remaining processes in tree before restarting. I've cleaned flatpak's and app's caches and files, and it didn't help.

Initially, I thought that could be due to some incompatibility with the electron distribution which used the pre-compiled package (from deb), which made me go into the more complex than anticipated process of doing the actual full compilation/packaging in the flatpak package here (just merged it on master): https://github.com/flathub/chat.rocket.RocketChat/commit/2c1c9bbd7e6270f9f3f5100d72294a5528b8baea
But, unfortunately, that didn't solve the problem, still got the freezes on current version.
No useful info in console/stdout/stderr either.
Any hint on how to debug it, to get the flatpak'd app running smooth again?
Thank you

**Comment by tassoevan** [comment]
I don't know exactly what could be happening, but when I dug into the snap building configuration I noticed that some dependencies changed, specially GTK libraries, on updating the Electron version.

**Comment by andrevmatos** [comment]
Ok, since the build for `2.14.0`, also using the sources, I didn't see it happening again. Besides, the `--enable-logging` option for electron started working, and despite a lot of warnings, the freeze didn't occur, and if does, I can check the logs now. Closing this. Thank you.
