### ISSUE TITLE
Displays jpg in Rocket.Chat Windows app and download the file in standard browser

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Electron#92]
Hey Guys,

i am using the windows client 1.0.0 (beta1).

If i wanna download a file uploaded by a user to a room, the downloaded jpg displays correct in my rocket.chat application but it starts a file download in my standard browser, too.

My standard browser is chrome.

Greetings
TheReal

**Comment by rodrigok** [comment]
How do you start the image download? We don't have an option to download, at least, I can't see any option in OS X
