### ISSUE TITLE
OSX client fails to remember position after reboot

### ISSUE THREAD

**Issue by ahayes** [RocketChat/Rocket.Chat.Electron#923]
## My Setup
- Operating System: OSX 10.13.6
- App Version: 2.14.0
- Installation type: dmg
- Hardware: 27" 5K Retina iMac, single display with resolution set to "More Space".

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

1. Place Rocket.Chat in Login Items list to automatically start when logging in.
2. Open Rocket.Chat desktop client and reduce to smallest possible size.
3. Position in bottom right corner of screen.
3. Restart computer and log in again. (Logging out and back in will work, rebooting will not.)

### Current Behavior

Desktop client opens in the middle of the screen. Size appears to be preserved but not position.

### Expected Behavior

Should open in position it was left in.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
