### ISSUE TITLE
It is impossible to re-open a hidden rocketchat window after minimization

### ISSUE THREAD

**Issue by martinpoliak-goodai** [RocketChat/Rocket.Chat.Electron#925]
## My Setup
- Operating System: Win 10
- App Version: 2.14.0
- Installation type: exe

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description
It is impossible to re-open a hidden rocketchat window after minimization.

How to reproduce:
Minimize rocket chat to taskbar by using the minimize button on the main application window. Then click the rocket chat icon in the notification area of the taskbar. RocketChat window gets hidden from the taskbar. The window cannot be shown again by left-clicking on the RocketChat icon in the notification area. I need to restart RocketChat to be able to see the main window again.

Note: this may be related to fixes from issue https://github.com/RocketChat/Rocket.Chat.Electron/issues/847 (just guessing).

### Current Behavior
Main app window cannot be re-shown.

### Expected Behavior
Main app window should be re-shown after left-clicking on the RocketChat icon in the notification area of  the taskbar.

**Comment by martinpoliak-goodai** [comment]
Sorry, seems I posted this to an incrorrect part of the repository. Closing.

**Comment by martinpoliak-goodai** [comment]
I am not sure if this is the right place for this bug - if not, feel free to close it or move around. As a side note, it would help if I saw "Electron" keyword written somewhere in the desktop application, for instance in the about dialogue. As it is not stated there (but the repository claims that Electron is the official desktop client), I am a bit confused.

**Comment by ledainam** [comment]
+1 same issue.

**Comment by martinpoliak-goodai** [comment]
Thanks!
