### ISSUE TITLE
Error during 2.14.0 installation by snap - cannot install this package

### ISSUE THREAD

**Issue by Inscure** [RocketChat/Rocket.Chat.Electron#928]
## My Setup
- Operating System: Ubuntu 18.04
- App Version: currently installed 2.11.0 by deb, I've tried to install 2.14.0 by snap

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

```
sudo snap install ~/Downloads/rocketchat_2.14.0_amd64.snap 
error: cannot find signatures with metadata for snap
       "/home/pzegardlo/Downloads/rocketchat_2.14.0_amd64.snap"
```
I've downloaded the package from here - https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.14.0/rocketchat_2.14.0_amd64.snap

Are you sure that this package is fine? or this is my system case?

**Comment by ttepatti** [comment]
I have also reproduced this issue on Debian 9.5

I actually already have 2.14.0 installed from deb, but decided to try installing the package via Snap to see if I could re-create your bug. I got almost identical output:

`sudo snap install rocketchat_2.14.0_amd64.snap 
error: cannot find signatures with metadata for snap
       "rocketchat_2.14.0_amd64.snap"`

I was utilizing the exact same package from the Releases URL you provided.

**Comment by davidgut1982** [comment]
I just want to confirm that I am having the same issue here.

`$ snap install rocketchat_2.14.3_amd64.snap`
`error: cannot find signatures with metadata for snap "rocketchat_2.14.3_amd64.snap"`

`$ snap version`
`snap    2.35.5`
`snapd   2.35.5`
`series  16`
`ubuntu  14.04`
`kernel  4.4.0-138-generic`

**Comment by tassoevan** [comment]
To install a *.snap file **without downloading it from snapcraft**, you need to pass a parameter `--dangerous`:

    # snap install rocketchat_*.snap --dangerous

Also, the latest version was published, therefore this should be available:

    # snap install rocketchat-desktop
