### ISSUE TITLE
Try to connect on private server in  https

### ISSUE THREAD

**Issue by darkjeff99** [RocketChat/Rocket.Chat.Electron#93]
Hi

I try to connect to a server in https with a certificat not signed by a big CA compagny but by an private not recognized by browser.

When I choose https the client change to http and failed the validation.

Why replace https by http ? 

`                    // If the url begins with HTTPS, fallback to HTTP
                    if (/^https:\/\/.+/.test(host)) {
                        hostField.value = host.replace('https://', 'http://');
                        return execValidation();
                    }`

**Comment by rodrigok** [comment]
We fallback to try to find one accessible server.

Which version are you using?

**Comment by darkjeff99** [comment]
Hello

You can close the issue, we can't use self signed certificat with electron. 

I use let's encrypt for have a valide certificate.
