### ISSUE TITLE
Download uploaded attachment prompts twice

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat.Electron#930]
Description:
Problem occurs always when I download attachment uploaded by someone in chat window.
System prompts me to select target directory, I click save and after that same window displays again.

Steps to reproduce:

1. Click download file
2. Select location
3. Click choose
4. File is saved and window opens again.

Expected behavior:
One propmpt

Actual behavior:
Two prompts

Server Setup Information:
Client version: 2.13.3-1024
Version of Rocket.Chat Server: 0.69.1
Operating System: Ubuntu 18
Deployment Method: tar
Number of Running Instances: 1
DB Replicaset Oplog: 0
NodeJS Version: 8.11.4
MongoDB Version: 4

**Comment by piotrkochan** [comment]
I've updated client to 2.14.0 and for now it looks good. I will give a feedback after some time.

**Comment by ttepatti** [comment]
Unable to recreate this on Client 2.14.0 running on Debian 9.5 - File downloading appears to work correctly now.
