### ISSUE TITLE
Audio record doesn't work in Electron client

### ISSUE THREAD

**Issue by awilkins** [RocketChat/Rocket.Chat.Electron#94]
Platform 
* Linux x86_64 (Ubuntu 15.10)

Reproduce 
* Clicked mic button
* Nothing happened

Expected
* Click mic button
* Same stuff as browser version happens

---

This is on a docker instance... this works for the Electron client connected to https://demo.rocket.chat - so I have no idea now.... the browser client works fine for the same server.

**Comment by rodrigok** [comment]
Which version are u using? Can you download the latest version and try again? Is working for me on OS X and Linux Ubuntu 15.10.

I will close the issue, please reopen if the problem persists
