### ISSUE TITLE
A centralized update feature

### ISSUE THREAD

**Issue by Mexonizator** [RocketChat/Rocket.Chat.Electron#940]
Hi all!

Is there any way to make clients update themselves from the local Rocket.Chat server automatically? So that they won't show any alerts to the users and just seamlessly update?

Thanks.

**Comment by tassoevan** [comment]
The update process is detached from any Rocket.Chat server; since you can connect to multiple servers, there is no way to determine which one would provide an update to the desktop app). There are plans for a less intrusive update process, but some restart will be required anyway.

**Comment by cswsupport** [comment]
Currently i use WSUS Package Publisher to deploy to our workstations and deploy servers.json file with GPO to set the default server.
Don't have a good way to auto start for each new user on the computer however.

**Comment by cswsupport** [comment]
Is there a list of all the parameters we can set in the server.json file?

**Comment by Mexonizator** [comment]
I'd like to hear about that too.

**Comment by tassoevan** [comment]
The format for `servers.json` is pretty simple: https://github.com/RocketChat/Rocket.Chat.Electron#default-servers

**Comment by Mexonizator** [comment]
Yes, but does it mean there's only one possible parameter?

**Comment by Mexonizator** [comment]
So. I discovered that in the newest version a key added that disables the auto-update feauture:

/disableAutoUpdates

But I hope that the client will have a feature for pointing to needed server/share for updating in the future. How do I request that?

**Comment by tassoevan** [comment]
I think a better approach is to disable the auto-updates and rely in a third-party solution to provisioning the updates because of some issues like the need to do a privilege escalation when updating an all-users install. However, it would be better to bring this feature request to [the forums](https://forums.rocket.chat/c/feature-requests) and get more opinions about this could be done.

**Comment by Mexonizator** [comment]
Ok, thanks.

**Comment by tassoevan** [comment]
@Mexonizator I'll be watching your topic there, thanks.
