### ISSUE TITLE
Rocket.Chat notification questions

### ISSUE THREAD

**Issue by djordjy25** [RocketChat/Rocket.Chat.Electron#945]
Hello.
We use Rocket.Chat 2.14.0 on Windows 7.

1. The picture on the program tray icon is not always displayed.
2. Is it possible to increase the display time for notifications more 5 sec?
3. Is it API to get the count of unread messages of a particular user?

**Comment by tassoevan** [comment]
Duplicate of (1) #804 and (2) #775.

For (3), take a look at [API documentation for Rocket.Chat server](https://rocket.chat/docs/developer-guides/rest-api/) or ask for help in [our community forum](https://forums.rocket.chat/c/community-support).
