### ISSUE TITLE
Rocket.Chat Linux desktop - ability to change tray icon

### ISSUE THREAD

**Issue by Skygge666** [RocketChat/Rocket.Chat.Electron#946]
In Rocket Chat Linux with KDE desktop the tray icon is almost invisible.
Please add an ability to change the icon, or at least two (light and dark) options.

This is how it looks like. Quite ugly, isn't it?
![rocket_chat_ugly_tray_icon](https://user-images.githubusercontent.com/32511161/47496423-06a48600-d857-11e8-93b3-c31d7d4e3c81.png)

**Comment by tassoevan** [comment]
Looks like a bug in libappindicator: https://github.com/electron/electron/issues/10163

**Comment by tassoevan** [comment]
@Skygge666 What about in 2.14.3?

**Comment by Skygge666** [comment]
Perfect! Thank you!
