### ISSUE TITLE
Help / Reset App data not working on Windows 2.14.1

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Electron#947]
## My Setup
- Operating System: Windows 10
- App Version: 2.14.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
1. Install latest 2.14.1 Rocket.Chat for Windows
2. Add a server
3. Go to "Help" and then "Reset App Data" then click "Yes"
![image](https://user-images.githubusercontent.com/6295044/47525348-07471780-d86b-11e8-815a-90131e244170.png)
4. Nothing happens. 

I've tried restarting Rocket.Chat, but it still is logged in. If I remove the server manually, then re-add it, it logs in without asking for credentials (thus it's not clearing the app data).

### Current Behavior
Does not clear App Data

### Expected Behavior
Clear App data

**Comment by tassoevan** [comment]
Related to #908.

**Comment by tassoevan** [comment]
I can confirm that removing the server is not logging out the user.
