### ISSUE TITLE
RIght click on URLs doesn't work cleanly in a cross-platform way.

### ISSUE THREAD

**Issue by bgupta** [RocketChat/Rocket.Chat.Electron#95]
The right click action for URLs should be the same across all three desktop platforms, and not just re-purpose the OS/browser native option menu. IE: I want a context sensitive right-click menu with "open link" and "copy link". It kinda does this by luck on the Mac Electron Client, but not so much on Linux or Windows. (You have to highlight the link first on those, and then select copy, and then paste it into a new tab.) Again Skype and Slack do the right thing here.

**Comment by rodrigok** [comment]
Now the behavior is the same across all platforms, we open the menu with (edit, copy, paste, etc).

There is a new issue to create better menus for links https://github.com/RocketChat/Rocket.Chat.Electron/issues/106
