### ISSUE TITLE
2.14.1 tagged on wrong commit

### ISSUE THREAD

**Issue by ml-** [RocketChat/Rocket.Chat.Electron#950]
Hi,

The newly created Tag 2.14.1 is was created on this commit: https://github.com/RocketChat/Rocket.Chat.Electron/commit/fad346350b7265f6f7b532275f07c45380a76b81

This is the same commit as 2.14.0. Means the archives of the source code on the releases page are identical.

**Comment by tassoevan** [comment]
Ouch! Thank you very much, it was fixed.
