### ISSUE TITLE
Clicking on URL to PDF destroys the app

### ISSUE THREAD

**Issue by slajerek** [RocketChat/Rocket.Chat.Electron#952]
## My Setup
- Operating System: MacOS 10.12.6
- App Version: 2.13.3
- Installation type: App Store

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When I go to selected chat server screen and then in some conversation I click on an URL that points to a PDF file, then chat screen becomes empty immediately (see screenshot). After restarting the RocketChat it is not possible to access chat anymore, it's always empty, even after another restarting of the application. Removing the chat server and adding the same resolves the issue.

Edit: note that the PDF file is empty and can't be accessed, ie. Safari displays empty screen too.

### Current Behavior
1. When I click on URL that points to not accessible PDF file this destroys the application chat server screen, and it is not possible to access chat anymore, even after restarting the application.

<img width="1003" alt="screen shot 2018-10-26 at 12 14 06" src="https://user-images.githubusercontent.com/1021783/47560667-27351480-d919-11e8-8904-68a3236b5898.png">

### Expected Behavior
1. The chat server screen should not be affected, PDF should be displayed, or application to show PDF should be run instead.

**Comment by krystiangorecki** [comment]
Confirmed on Windows 10 version 2.14.1. Reinstallation with removing user data didn't help. Removing remaining files from AppData/Roaming was necessary.

**Comment by tassoevan** [comment]
This is not a desktop app issue; I reproduce it in the web client of Rocket.Chat and reported here: RocketChat/Rocket.Chat#12437. As a workaround, you can activate the menus `View > Back` and `View > Reload`.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
