### ISSUE TITLE
Auto-upgrade doesn't upgrade

### ISSUE THREAD

**Issue by entonio** [RocketChat/Rocket.Chat.Electron#953]
## My Setup
- Operating System: macOS 10.14
- App Version: 2.14.0
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

This has happened in every mac I have since always (I started using the app with 2.12):
- When checking for an update on start, I'm told there is a newer version
- By clicking download, it starts the download
- When ready, it asks to install
- By clicking install, the app quits and does nothing more and the update is not installed

### Current Behavior

The update is not installed and the app doesn't start again.
On next run, it still says there is a newer version.

### Expected Behavior

The update should be installed and the app should open again.

**Comment by tassoevan** [comment]
I'm closing this issue since it was solved for 2.14.1 in #936, but: 

> Unfortunately, autoupdate fixes can't be applied backwardly. Therefore, versions listed in #894 will fail on update regardlessly; we advise users to click the "Install later" button to update.
