### ISSUE TITLE
No spell checker

### ISSUE THREAD

**Issue by tendo256** [RocketChat/Rocket.Chat.Electron#958]
## My Setup
- Operating System: Windows and Linux
- App Version: 2.14.1
- Installation type: 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
No spell checker to check typos

### Expected Behavior
We must have a spell  checker for checking typos

**Comment by tassoevan** [comment]
@tendo256 When you right-clicks something, a menu is open with a list of supported messages to enable spell checking. Do you see it?

**Comment by ssmorris** [comment]
Same issue reported here from multiple users after updating to 2.14.1 (worked on 2.14.0).  Right clicking in the "Message" area doesn't open a menu for me.

**Comment by tassoevan** [comment]
@ssmorris Stay tunned for updates about this in #956.
