### ISSUE TITLE
Possibility to install without creating shortcuts

### ISSUE THREAD

**Issue by flauschi** [RocketChat/Rocket.Chat.Electron#96]
Hello,

it would be great if the Rocket.Chat client would support some options to simplify deployment:
(Other parts of this task #139, #140)

* possibility to install without creating shortcuts (desktop and start menu in Windows).

I have to say it again: great project, guys!

**Comment by rodrigok** [comment]
- [x] possibility to install without creating shortcuts (desktop and start menu in Windows). (via #116)
- [ ] possibility to deploy a config file for the first connection (e.g. server address, username, toggled server list status, ...)
- [ ] command line option to start the client in hidden mode (tray icon) or remember this setting when closing the app

**Comment by rodrigok** [comment]
@flauschi can you split this issue in small issues? And rename this to the first one? So we can close this and set more details and priorities for each item.

Best.

**Comment by flauschi** [comment]
@rodrigok Done. New issues are #139 and #140. This one could be closed. I have already tested it. :)

**Comment by rodrigok** [comment]
Thanks
