### ISSUE TITLE
screenshare not working properly

### ISSUE THREAD

**Issue by lona0618** [RocketChat/Rocket.Chat.Electron#963]
## My Setup
- Operating System:windows 10 pro 64 bit
- App Version:2.14.1
- Installation type: exe

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

i have integrated "Dead simple screen share" but i am not getting the link when i send the message "sharescreen"

### Current Behavior

should get a join meeting link

### Expected Behavior

nothing

### additional info

Data Passed to Integration
{
  "token": "s8FsXefttKSnTD2yxGD5Cbbh",
  "bot": false,
  "trigger_word": "screenshare",
  "channel_id": "DruSPcwMZvenC2iAmbKqDsNjHBRTcxEXLc",
  "channel_name": null,
  "message_id": "NhnLGW83ZoDcbkxHR",
  "timestamp": "2018-10-31T10:21:14.433Z",
  "user_id": "DruSPcwMZvenC2iAm",
  "user_name": "lokesh.nayak",
  "text": "screenshare",
  "alias": "Lokesh Nayak"
}
Data Passed to URL
{
  "token": "s8FsXefttKSnTD2yxGD5Cbbh",
  "bot": false,
  "trigger_word": "screenshare",
  "channel_id": "DruSPcwMZvenC2iAmbKqDsNjHBRTcxEXLc",
  "channel_name": null,
  "message_id": "NhnLGW83ZoDcbkxHR",
  "timestamp": "2018-10-31T10:21:14.433Z",
  "user_id": "DruSPcwMZvenC2iAm",
  "user_name": "lokesh.nayak",
  "text": "screenshare",
  "alias": "Lokesh Nayak"
}

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
