### ISSUE TITLE
[BUG]: Context menu does not work (right mouse button) ver. 2.14.1

### ISSUE THREAD

**Issue by cadetmsv** [RocketChat/Rocket.Chat.Electron#965]
## My Setup
- Operating System: Windows 7
- App Version: 2.14.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
Missing context menu.

### Expected Behavior
Return back.

**Comment by tassoevan** [comment]
Duplicate of #956.
