### ISSUE TITLE
Auto Install Rocket.Chat Client on All Windows PCs

### ISSUE THREAD

**Issue by SammyMR** [RocketChat/Rocket.Chat.Electron#970]
Rocket.Chat Version:  Version 2.6.1
Running Instances: MongoDB V3.2.9
DB Replicaset OpLog: 
Node Version: v0.10.26

Please add a setup (.msi) with group policy object (GPO) for Windows Domain Controller to auto install Rocket.Chat client on all Windows PCs in a company network. And it would be cool when the .msi file could be installed for all users (not only one user or admin on a pc)-

**Comment by tassoevan** [comment]
Forgive my ignorance, but does the MSI option replace flawlessly some options of the EXE setup? AFAIK some command-line flags will not be available.

**Comment by crbreingan** [comment]
An MSI can fully replace an EXE. You create the GUI for MSI, and name each field in the UI. MSI has a built in headless mode that will use default values for all options on the GUI, or default options can be over-ridden on the command line by specifying the field name.

**Comment by tassoevan** [comment]
To be honest, we have to think more about it. I believe we have to fully support enterprise setups and our dependency on `electron-builder` and `electron-updater` was proven to be a huge miscalculation in this context. Keep all current options available and up to date is hard; I think [this little section](https://github.com/felixrieseberg/electron-wix-msi#should-i-use-this) expose all my concerns about supporting a new setup option.

**Comment by LittleNo** [comment]
same here, would love to see this feature

**Comment by gennari-dkt** [comment]
Hello,
any news about MSI installer for deploying in a Windows domain?

Very kind regards.

Ale

**Comment by nexidus** [comment]
I hope the MSI will be there soon. It would make our job as sysadmin a lot easier.
