### ISSUE TITLE
Can not log in with an existing account

### ISSUE THREAD

**Issue by bepcho** [RocketChat/Rocket.Chat.Electron#972]
## My Setup
- Operating System: Windows 7 x64 SP 1
- App Version: 2.14.1
- Installation type: .exe 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behaviour

When trying to log in with already existing account it returns that the entered credentials are incorrect
When use "Forgotten e-mail function" it doesn't send me an e-mail
When try to create a new account with this e-mail it returns that an account with such e-mail already exists
### Expected Behaviour

To be able to log in successfully

**Comment by tassoevan** [comment]
@bepcho Accessing your Rocket.Chat server via web browser works?

**Comment by bepcho** [comment]
No, it doesn't. It is the same thing whether you try from your desktop or web. Already tried re-installing the app, bu as I said it doesn't work neither from the web nor desktop

**Comment by tassoevan** [comment]
Please fill a issue in the [Rocket.Chat server repository](https://github.com/RocketChat/Rocket.Chat/issues/new), since it looks the problem lies there.
