### ISSUE TITLE
Feature Request "Forward" Message(s)

### ISSUE THREAD

**Issue by chenrylee** [RocketChat/Rocket.Chat.Electron#973]
Current way to forward a message to others is:
1. Click the 3-dot behind a message; 
2. Click **Permalink** and copy the link to this message;
3. Send the link to others.
  
Is there a plan that adding a more friendly way to forward a message? For example:
1. Select the message(s), and then a button appears, float or at the top of frame;
2. Click the button, and it asks user to select a destination;
3. Click the destination, complete.
It's like Telegram.

**Comment by tassoevan** [comment]
Your issue is related to the Rocket.Chat server, please reopen it in the [server repository](https://github.com/RocketChat/Rocket.Chat). Thanks!
