### ISSUE TITLE
A JavaScript error occurred in the main process. TypeError: this.notification.show is not a function

### ISSUE THREAD

**Issue by shotanoniashvili** [RocketChat/Rocket.Chat.Electron#974]
I have just updated rocketchat to latest version (2.14.2). And looks like there is some issues with it. When new message arrives, rocketchat client throws the javascript error.

Operating System: Windows 7
App version: 2.14.2

![capture](https://user-images.githubusercontent.com/26275106/48468735-24d22600-e806-11e8-88c9-7cf626458a0b.PNG)

**Comment by evant89** [comment]
I have this error too
Rocket chat Electron 2.14.2 on Windows7
Rocket Chat Server 0.71.1

![2018-11-14 10-11-41](https://user-images.githubusercontent.com/36101287/48468989-209e0c80-e7f6-11e8-9061-368172158763.png)

**Comment by artem-levashov** [comment]
Same error  Windows 2.14.2  on Windows  10

**Comment by artem-levashov** [comment]
For me  it happens after i run apllication GoToMeeting . if i do restart of  RC after GTM is started then problem is gone  all is ok till the restart of  GTM. But i know 2 people who didnt  use  GTM but have same problem. So it looks  like some other application has a conflict  with RC

**Comment by priaJuli** [comment]
same here, after update to new version, it get error always

**Comment by Nono-m0le** [comment]
my colleague (who has to revert) also had this issue on win7 x64 (I don't on windows 10 x64, same as a third colleague on win7 x64).

**Comment by CH1PSET1** [comment]
Same

**Comment by tassoevan** [comment]
@artem-levashov Could you confirm if the error message shown is the same?

**Comment by artem-levashov** [comment]
> 
> 
> @artem-levashov Could you confirm if the error message shown is the same?

yes same

**Comment by chandrahasan** [comment]
Having same issue, Please advise,
![clipboard - november 15 2018 12-49 pm](https://user-images.githubusercontent.com/7067054/48537308-35060600-e8d7-11e8-81d5-9659d0199ef0.png)
