### ISSUE TITLE
JavaScript error in the main proccess

### ISSUE THREAD

**Issue by moonwolf-github** [RocketChat/Rocket.Chat.Electron#977]
## My Setup
- Operating System: win10
- App Version: 2.14.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Error on startup (Module cannot be found). It happened on three different desktops with win10/win7.

### Current Behavior
![image](https://user-images.githubusercontent.com/10871358/48479499-cad26000-e807-11e8-8710-5019fc90f9c3.png)

### Expected Behavior
No error

On my Fedora everything work as expected. Version 2.14.1 works without problems.

**Comment by tassoevan** [comment]
This looks different from #974. Are you using some antivirus software?

**Comment by moonwolf-github** [comment]
Hmm... On one computer there is F-Secure. Don't know about others (probably there is some kind of antivirus).

**Comment by MattBosh** [comment]
Same issue on our win10 64bit machines

**Comment by sbiglia** [comment]
![img_20181114_100133660](https://user-images.githubusercontent.com/6143157/48487314-9c9b5300-e7fc-11e8-990b-9aab1709e9e7.jpg)

Same one here on Win8.1 x86 after upgrading to 2.14.3, rolling back to 2.14.1 works fine.

**Comment by tassoevan** [comment]
I think I've found it. May someone install **Microsoft Visual C++ 2017 Redistributable Package** and see if it solves the issue?

**Comment by MattBosh** [comment]
> I think I've found it. May someone install **Microsoft Visual C++ 2017 Redistributable Package** and see if it solves the issue?

I've installed **Microsoft Visual C++ 2017 Redistributable Package** and performed some testing.

It seems to work ok when windows 10 notifications are enabled....
When they are disabled for RC or generally then you get the error as below:
![capture](https://user-images.githubusercontent.com/38952980/48549146-d89aea80-e8c6-11e8-8f71-80bcef0ceed5.JPG)

**Comment by artem-levashov** [comment]
never had such problem in 2.14.1 starting from 2.14.2  - something critical was added into notifications

**Comment by tassoevan** [comment]
@artem-levashov Yes. The default notifications don't persist in Action Center after around 20 seconds, as expected by many users, therefore we're using the suggested `electron-windows-notifications` but we fell into some pitfalls...
@MattBosh **Thanks a lot!**

**Comment by Sierra1011** [comment]
@tassoevan We experienced this across a range of users too. I didn't get the issue at all. Upon checking I already have the C++ 2017 package installed so if you weren't sure, it could definitely be linked.
