### ISSUE TITLE
Push notification causes error

### ISSUE THREAD

**Issue by oktay89** [RocketChat/Rocket.Chat.Electron#979]
## My Setup
- Operating System: Windows 7
- App Version: 2.14.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Since the latest udpate, the app crashes every time I get a message, instead of sending me a push notification. I can reproduce it also over the push notification tester in menu - my account/settings/notifications

### Current Behavior
Javascript error:
![image](https://user-images.githubusercontent.com/5344698/48480886-1129be00-e80c-11e8-9f53-19287e29e897.png)

### Expected Behavior
Getting a push notification.

**Comment by svennd** [comment]
Don't know if relevant, we can also reproduce this issue, on Rocket.Chat server 0.68.0.

**Comment by tassoevan** [comment]
@svennd Which Windows version?

**Comment by MattBosh** [comment]
Getting this same exact error across all of our windows 10 systems running 2.14.2 or 2.14.3

**Comment by odrumond** [comment]
Getting same error here. Both versions 2.14.2, 2.14.3

**Comment by sbiglia** [comment]
Same error here with 2.14.2 and 2.14.3 on Windows 8.1 x64, had to rollback to 2.14.1 that works ok.

**Comment by tassoevan** [comment]
@oktay89 Is the same error showing in 2.14.3?

**Comment by MattBosh** [comment]
> @oktay89 Is the same error showing in 2.14.3?

Yes it does

**Comment by MattBosh** [comment]
Rolled back to 2.14.1 and its all good again... we need a fix

**Comment by tassoevan** [comment]
@MattBosh But your OS is Windows 10, right? (@oktay89 reported for Windows 7).

**Comment by MattBosh** [comment]
> @MattBosh But your OS is Windows 10, right? (@oktay89 reported for Windows 7).

@tassoevan Yes our OS is windows 10 1803 build (64bit) - all latest updates/patches installed
Java 8.181

**Comment by MattBosh** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/issues/977 - same issue on either OS

**Comment by oktay89** [comment]
> @oktay89 Is the same error showing in 2.14.3?

2.14.3 Fixed it for me.

**Comment by tassoevan** [comment]
I believe it's a different issue for Windows 8 and Windows 10 users, reported at #977.

**Comment by sbiglia** [comment]
> 
> 
> I believe it's a different issue for Windows 8 and Windows 10 users, reported at #977.

Checked again upgrading to 2.14.3 and the error is not the same as #977, but its not exactly the same as this one either, it has something to do with notifications as the error pops up as soon as the app wants to show one.

![image](https://user-images.githubusercontent.com/6143157/48497376-c5c6de00-e812-11e8-99bf-afbbb8056a81.png)

**Comment by FreeTheTech101** [comment]
Confirming this issue occurs on Windows 8.1 (x64) after upgrading to 2.14.3. I skipped 2.14.2 from 2.14.1, going straight to 2.14.3.

![rocket chat_2018-11-14_11-57-25](https://user-images.githubusercontent.com/7614507/48498715-c6f10e80-e804-11e8-9086-0b5334dd0202.png)

**Comment by MattBosh** [comment]
Check https://github.com/RocketChat/Rocket.Chat.Electron/issues/977
This issue seems to be actually caused by having windows notifications set to disabled or off for RocketChat, at least for win10 users.
If you turn them on then no java errors

**Comment by abicur** [comment]
> Check #977
> This issue seems to be actually caused by having windows notifications set to disabled or off for RocketChat, at least for win10 users.
> If you turn them on then no java errors

Some of our users have the same problem and windows notifications is on.

**Comment by jimDKE** [comment]
Not sure whether this info belongs here or in a separate issue (I've been reading up on #977 and #974).  With desktop notifications enabled, I receive an error and freezes.  With desktop notifications disabled, the client runs without errors.  Happens with 2.14.2 and 2.14.3

Operating System: Win 10 64-bit LTSB (Build 14393)
App Version: 214.2
Have Microsoft Visual C++ 2017 Redistributable installed (14.12.25810)

![rocketchat_notification_error](https://user-images.githubusercontent.com/45210650/48794980-6bb19700-ecb0-11e8-98f5-096ebb5a6172.png)

**Comment by tassoevan** [comment]
@jimDKE It's another issue, I'll take a look at it.

**Comment by tassoevan** [comment]
@abicur If I translated right, it's the same one that @jimDKE reported. There is a fix for that in #1000 now.

**Comment by abicur** [comment]
@tassoevan yes, "Notification tag is too large". Thank you.
