### ISSUE TITLE
Auto Updater

### ISSUE THREAD

**Issue by dryabchenko** [RocketChat/Rocket.Chat.Electron#98]
Will you include Auto Updater for your apps, like desribed here http://electron.atom.io/docs/v0.33.0/api/auto-updater/ ?
##

**Comment by engelgabriel** [comment]
We plan to publish the app to the App Store really soon.

**Comment by drasbeck** [comment]
Is there a way to be notified of new releases as of now? I'm on 2.2.0 and have received no update notification, latest release at the time of writing is 2.2.3.

The App Store version is lingering on 1.3.1, so that's not an optimal solution for automatically keeping on the ball.

**Comment by compuguy** [comment]
@drasbeck Wondering the same thing. The app store version is stuck at 1.3.1, and github has the latest 2.5.0.

**Comment by kainjow** [comment]
Yes, I think an auto updater for all platforms is sorely needed and should be a priority, because then you can update and get more feedback from existing users instead of those of us who follow the Releases page. Even just a "Version X is available, click to download" is better than nothing.

**Comment by alexbrazier** [comment]
@kainjow I'm currently working on this feature and it should be in the next release.
