### ISSUE TITLE
Rocket Chat main window isn't drawn when first opening on Linux

### ISSUE THREAD

**Issue by ttepatti** [RocketChat/Rocket.Chat.Electron#980]
## My Setup
- Operating System: Debian 9.5 x64 (Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux)
- App Version: 2.13.3
- Installation type:  deb x64 (From rocket.chat website install page)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Upon startup, a RocketChat window is never drawn on the desktop. Upon task killing and restarting Rocket Chat multiple times I finally noticed the tiny Rocket Chat status bar in the lower left hand corner of the screen, as seen in [this image](https://my.mixtape.moe/jlmted.png). This is fine if you know that it pops up, but for a majority of the users who are new to Rocket Chat, it will simply look as if Rocket Chat crashed or otherwise didn't open.

### Current Behavior

A main window isn't drawn, only the small toolbar/status bar in the lower left hand corner.

### Expected Behavior

The main Rocket Chat window should be drawn at least once when the software is opened for the first time.

**Comment by tassoevan** [comment]
Please, could you verify if it still happens in 2.14.* versions?

**Comment by ttepatti** [comment]
Ah, my apologies - in the new 2.14.* it seems to have been fixed! I also realized that the "status bar" I was referring to was also just a Gnome feature (tray icons), my mistake. So the proper report would be "Rocket Chat starts minimized and only shows a tray icon". But it appears to be fixed in the new version anyways.

Thanks for your hard work! :smiley: :+1:
