### ISSUE TITLE
No rocket.chat tray icon showing up at all on the tray (2.14.2 and 2.14.3)

### ISSUE THREAD

**Issue by je-vv** [RocketChat/Rocket.Chat.Electron#981]
## My Setup
- Operating System:  Arch GNU+Linux
- App Version:  2.14.2 and 2.14.3
- Installation type:  From AUR

According to the 2.14.2 release notes, there were several issues fixed, some related to the tray.  However what I'm seeing is that with 2.14.2 rocket.chat no longer shows up on the tray at all.

Notice 2.14.3 release notes indicates the only change is to get get "Fallback notifications for Windows 7", see [2.14.3 release](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.14.3).  Any ways, I tried also 2.14.3, with same results, no tray at all.

**Comment by tassoevan** [comment]
The tray icon is not default anymore for Linux environments (#941). To enabled it, use the menu `View > Tray icon`.

**Comment by je-vv** [comment]
Thanks that was it.  Though I hid the menu bar, so it was hard to guess...  I will no longer hide the menu bar, since it might be hard to check for options...  Closing then...  Thanks a lot !
