### ISSUE TITLE
(auto) update doesn't seems to work since 2.14.3

### ISSUE THREAD

**Issue by Nono-m0le** [RocketChat/Rocket.Chat.Electron#983]
## My Setup
- Operating System: Win10 x64 (can be reproduced on Win7 x64 with v. 2.14.1)
- App Version: 2.14.3 (same behaviour on 2.14.1)
- Installation type: exe (usually using the auto update)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When I go on Help => About Rocket.Chat, and I hit the "Check for update" blue button, this happens and never stop/succeed : 
![image](https://user-images.githubusercontent.com/3726435/48538499-f95a4480-e8b4-11e8-9ac7-931ec2f3a33c.png)

### Current Behavior
Update doesn't seems to reach the end of the process

### Expected Behavior
I should be able to see "no update available" (or in 2.14.1, that an update is available).

**Comment by svennd** [comment]
I believe in https://github.com/RocketChat/Rocket.Chat.Electron/issues/979 its stated that auto-update is disabled for a while until that issue is resolved ?

**Comment by Nono-m0le** [comment]
Hi @tassoevan ,

I'm sorry but it's still the same behavior at my end using v. 2.14.3.
The update is still looping (similar to my initial screenshot).

**Comment by tassoevan** [comment]
@Nono-m0le It's ok, the issue is really inside 2.14.3; only in the next versions it will work properly. Also, I kept the update for 2.14.4 disabled for now too because I'm waiting for some feedback for another issues before I feel confident to enable it.

**Comment by Nono-m0le** [comment]
Many thanks for the info (and the work done). Indeed, upgrading manually to 2.14.4 seems to allow the auto-update to work.
But would it means that no version 2.14.2 or .3 will be able to auto-upgrade **ever** ?

**Comment by tassoevan** [comment]
They will. Their issue was not handling an error when update was disabled; once 2.14.4 became enabled, they will update normally.
