### ISSUE TITLE
There is no translation into Russian in some menu panel items

### ISSUE THREAD

**Issue by cadetmsv** [RocketChat/Rocket.Chat.Electron#984]
## My Setup
- Operating System: Windows, OSX, Linux
- App Version: 2.14.3

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Description
The following menu items are not translated into Russian in the panel:
1. Reload ignoring cache
2. User status in tray
3. Show on unread messages

In the panel, the section "File" is translated as "файл", it should be as "Файл"

### Expected Behavior
This needs to be fixed so that everything is beautiful. ))

**Comment by tassoevan** [comment]
@cadetmsv Could you suggest some translation for those items?

**Comment by cadetmsv** [comment]
Suggestions for translation into Russian:

    1. Reload ignoring cache - Перезагрузить игнорируя кэш
    2. User status in tray - Статус в трее
    3. Show on unread messages - Показывать на непрочитанные сообщения
       (however, I did not quite understand what this function does, so the translation may not be accurate)
    4. you have 1 unread message - У Вас 1 непрочитанное сообщение (for displaying on a novice on the tray icon)
    5. you have 2 unread message - У Вас 2 непрочитанных сообщений (for displaying on a novice on the tray icon)
    4. File - Файл ))

**Comment by tassoevan** [comment]
@cadetmsv May ask you to review #987?
