### ISSUE TITLE
Notifications of answered messages display the previous message in raw format.

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Electron#985]
## My Setup
- Operating System: Ubuntu 18.04 LTS
- App Version: 2.14.3
- Installation type: dpkg
- Server: 0.69.2

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Notifications of answered messages display the previous message in the notification in raw format.

### Current Behavior

Notification with raw text

![notification](https://user-images.githubusercontent.com/8544984/48559108-35100100-e8eb-11e8-8678-53c51a59ba34.png)

### Expected Behavior

no raw text

**Comment by tassoevan** [comment]
I'm closing this issue since it's a server issue (https://github.com/RocketChat/Rocket.Chat/issues/9979) and I don't think there is a easy way to filter this markdown code on client-side.
