### ISSUE TITLE
Tray icon doesn't work on versions over 2.14.0 in Gnome on Ubuntu 18.04

### ISSUE THREAD

**Issue by Rumbles** [RocketChat/Rocket.Chat.Electron#986]
## My Setup
- Operating System: Ubuntu 18.04 with Gnome Shell 3.28.3
- App Version: > 2.14.0
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I installed 2.14.3 yesterday, and realised later that the system tray icon had disappeared. I tried 2.14.2, 2.14.1 and 2.14.0 and it only appears when running 2.14.0

### Current Behaviour
There is no system tray icon, so no way to know if someone has messages you and you didn't see the notification

### Expected Behaviour
Should have a rocket in my system tray which changed colour when a message is unread

**Comment by tassoevan** [comment]
The tray icon is not default anymore for Linux environments (#941). To enabled it, use the menu `View > Tray icon`.

**Comment by Rumbles** [comment]
Thanks, I hadn't noticed that change.

I just tried turning it on, then turned it off to demonstrate this to a colleague. The icon remained, and when I turned it back on, another icon appeared, I repeated this a couple of times and had 3 icons in the tray. It seems that when you turn it off the icon doesn't disappear. Would you like that on a new issue?

**Comment by tassoevan** [comment]
@Rumbles Yes, please! I'm aware of this and I forgot to create an issue for it. It seems there is some issues between Electron API and the libappindicator -- and it might be affecting KDE users too (https://github.com/RocketChat/Rocket.Chat.Electron/issues/696#issuecomment-431850757).

**Comment by Rumbles** [comment]
closed in favour of #989
