### ISSUE TITLE
2.14.2 Windows Tray Icon Weird

### ISSUE THREAD

**Issue by sergeydeg** [RocketChat/Rocket.Chat.Electron#988]
## My Setup
- Operating System: Windows 10 - 1703
- App Version: 2.14.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Icon is almost useless on resolution 1920x1200

### Current Behavior
Icon always stay Red with small green dot.
What this green dot mention - if status, then not changed when I change status
When new messages arrives - only small red circle with white dot or number showing - very hard to notify when new messages exists

### Expected Behavior
Restore older bahavior - 2.10.x
When no new messages  - black/gray icon
When new non-personal messages arrived - red icon
When new mentions or personal messages - red icon with big green number

**Comment by jkshapiro** [comment]
For @-mentions or direct messages, it would be okay to blink [up to three](https://www.w3.org/TR/WCAG21/#three-flashes-or-below-threshold) times in quick succession, especially if the user has the capability to turn off that feature. However, I don't think it's needed, since Rocket.chat already provides the capability for desktop notifications.

Continuous blinking would be extremely distracting.

**Comment by jkshapiro** [comment]
Here's a screenshot of my taskbar and notification area, showing why the current icon is so jarring:
![image](https://user-images.githubusercontent.com/3178838/49653884-3e7d1c80-fa04-11e8-92d2-b284447b3176.png)

The red colour, white background, and green dot all draw the eye, making it look as though there must be something important down there. But this is what it looks like when I'm completely caught up!

The "nothing to see" state needs to be much more muted. Black/grey, as the original poster suggests, or white, possibly with a thin black background. Red is the colour of alerts.

**Comment by abicur** [comment]
In Windows 7, the gray icon in the notification panel (especially when it is hidden) becomes almost invisible. The problem with the gray icon (it’s not possible to see it in Windows 7) has already been raised here several times. Gray icon is a bad option.

**Comment by stevenhfotofix** [comment]
> In Windows 7, the gray icon in the notification panel (especially when it is hidden) becomes almost invisible. The problem with the gray icon (it’s not possible to see it in Windows 7) has already been raised here several times. Gray icon is a bad option.
> The red icon is clearly visible in the panel.

I have seen those complaints - A black or dark-grey stroke around or shadow behind the icon would solve the issue, without having to resort to red, which we have become accustomed to meaning that there is a message waiting for us.

**Comment by abicur** [comment]
> > In Windows 7, the gray icon in the notification panel (especially when it is hidden) becomes almost invisible. The problem with the gray icon (it’s not possible to see it in Windows 7) has already been raised here several times. Gray icon is a bad option.
> > The red icon is clearly visible in the panel.
> 
> I have seen those complaints - A black or dark-grey stroke around or shadow behind the icon would solve the issue, without having to resort to red, which we have become accustomed to meaning that there is a message waiting for us.

I think it's just a matter of habit. Now on the tray icon display two additional icons. One for messages in the channels and one for direct messages. This is very convenient (users like different indicators for direct messages and for groups).

**Comment by sergeydeg** [comment]
Because main icon in all 3 states stays Red/White, it is hard to notify when status changed. Also on high resolutions, those additional circle (for group) and numbers (for mentions), which also Red/White, looks so small to be alerted

**Comment by luchsamapparat** [comment]
![image](https://user-images.githubshrufusercontent.com/875017/49927033-57cb1080-febd-11e8-8dc0-74612c219d90.png)

As others have already said, when there's nothing new, the red icon is quite prominent and catches the eye. To cite the WIndows UX guidelines for the notification area:

> "If you use notifications, make it a good user experience. Don't try to force users to see your notifications. If users are so immersed in their work that they don't see your notifications, your design is good."
https://docs.microsoft.com/en-us/windows/desktop/uxguide/mess-notif

However, what makes the red icon even less usable is the fact that it doesn't really stand out anymore when there *is* something new...

![image](https://user-images.githubusercontent.com/875017/49926998-3e29c900-febd-11e8-9e7b-1a475567d238.png)

Regarding the green dot, I also don't think that it's very useful. At least for me, "being online" is the default, so I don't need information about that. Maybe it makes sense, to add an overlay if you're in any other status 🤷‍♂️

**Comment by abicur** [comment]
> I guess I don't have any constructive suggestion besides: please restore the old behavior

The old behavior is bad for installations on Windows 7. Look at this issue #852 for demonstration. 
It will be good if there is an option that solves both problems. Without this, a return to the old will return a big problem with an invisible icon in Windows 7. Old problem with Windows 7 icon is more significant than problem with red icon.

**Comment by stevenhfotofix** [comment]
Funny enough - look at the flag icon right above where "Rocket Chat" is supposed to be sitting.  The grey stroke around the flag...  Why not go that route, like other Windows 7 compatible apps with white icons?

**Comment by stevenhfotofix** [comment]
(green dot stays green even if you are busy, away, or invisible - no idea what that dot actually does)

**Comment by abicur** [comment]
I don't know why developers didn't do so. May be there were some problems. If it possible to do white icon with some black line around it then it would be great.

**Comment by luchsamapparat** [comment]
I just tried to simulate the issue on Windows 10 by giving the task bar a light color and indeed, Slack is doing the same:

![image](https://user-images.githubusercontent.com/875017/49950127-7fd76580-fef7-11e8-9b79-2cf9916113d4.png)

**Comment by tassoevan** [comment]
@luchsamapparat I honestly surprised by these monochromatic icons on Windows 10. AFAIK, Electron just support template icons (monochromatic and adaptive to the system theme) for MacOS.

**Comment by brunosquadros** [comment]
Hey everyone, We've made a new version to fix these issues. The idea is the tray to be subtle and works on any background colour so we changed it to grey. 
The normal status is just the rocket icon and the user has a mention will appear a grey circle. 

<img width="644" alt="screen shot 2018-12-19 at 19 50 25" src="https://user-images.githubusercontent.com/4096458/50250231-60dd4580-03c7-11e9-8d05-40fe27d3b28d.png">

**Comment by stevenhfotofix** [comment]
In my opinion, It should be grey, unless there is an actual notification.  Then you can splash some color to it to indicate that there is something that needs attention.

As long as it still will catch attention when attention is needed, then I think this is a fantastic change.

**Comment by jkshapiro** [comment]
That one can be grey :-)

**Comment by sergeydeg** [comment]
If icon stays grey all the time - it will be more unusable than now (IMHO)

**Comment by brunosquadros** [comment]
We've changed the circle from grey to red. I t'll appear when the user has an @mention or private message. 
<img width="1230" alt="screen shot 2018-12-20 at 09 02 26" src="https://user-images.githubusercontent.com/4096458/50281265-0e873d80-0436-11e9-9a76-6943a5fc72ed.png">

**Comment by abicur** [comment]
@brunosquadros what about badge with number of unread messages? Red circle is not the same as badge with a digit

**Comment by sergeydeg** [comment]
@brunosquadros what about just unread messages, not @-mentions or private?
 Also this type of notification (red cirlce etc.) can be more bigger by size.

**Comment by tassoevan** [comment]
@sergeydeg For some workflows, you need to differentiate them. I'm myself subscribed in my channels with constant conversation which very occasionally need my attention.

**Comment by phlegx** [comment]
@tassoevan Hi!

The current behavior is that where there is a new message in a channel where I'm member of, I get a red dot. When someone mentions me or DM me, I get a red dot with a badge.

- First of all it is really hard to distinguish if there is a dot or a badge on a small screen.
- Second it would be really cool if I could turn of "Notification" completely for a channel. So that I do not even get a red dot. I mean I really don't need to have a red dot just because some channel I'm member of is written to, without even mentioning me.

What you think?

**Comment by xgdgsc** [comment]
I' d disable change of task bar icon in any condition and keep tray icon changes? Is there an option?
