### ISSUE TITLE
Tray icon doesn't disappear when toggled off

### ISSUE THREAD

**Issue by Rumbles** [RocketChat/Rocket.Chat.Electron#989]
## My Setup
- Operating System: Ubuntu 18.04 with Gnome Shell 3.28.3
- App Version: > 2.14.0
- Installation type: deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I installed 2.14.3 and turned on the tray icon through view > Tray Icon

When I turned it off with the same toggle, the icon didn't disappear, turning it back on gives a second icon, I did this again for a third icon.

### Current Behaviour
Icons do not disappear when toggled off

### Expected Behaviour
The icon should disappear when you toggle it off

**Comment by didierm** [comment]
Issue confirmed with latest version 2.17.2 on Fedora 31 (Gnome Shell 3.34.2).

**Comment by jeanfbrito** [comment]
Just researched about this and it's an Electron Issue. We can expect this to be solved in a future Electron update.

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
