### ISSUE TITLE
Pop up in notification

### ISSUE THREAD

**Issue by javi076** [RocketChat/Rocket.Chat.Electron#992]
## My Setup
- Operating System: Ubuntu 16.04
- App Version: 2.14.3
- Installation type: .deb

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
You have a pop up notification for each message you receive. Also tray Icon disappeared.

### Current Behavior
![otro-bug](https://user-images.githubusercontent.com/10394672/48646401-855c9100-e9c7-11e8-9bde-941254525f85.png)

### Expected Behavior
No pup ups at all

**Comment by ccfiel** [comment]
same problem here notification become a modal.

![selection_110](https://user-images.githubusercontent.com/1788360/48661131-3c303e00-eaa8-11e8-94a1-23d93731bcf0.png)

**Comment by ccfiel** [comment]
Hello @tassoevan 

bug still persist in version 2.14.4

Chris

**Comment by ccfiel** [comment]
@tassoevan is there any daily build for me to test? :)

**Comment by tassoevan** [comment]
@ccfiel Sure. Please look at https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.15.0-develop

**Comment by ccfiel** [comment]
@tassoevan I have downloaded it and now notification is working as expected
