### ISSUE TITLE
Ubuntu 14.04 Javascript Error Uncaught Exception

### ISSUE THREAD

**Issue by davidgut1982** [RocketChat/Rocket.Chat.Electron#993]
## My Setup
- Operating System: Xubuntu 14.04
- App Version: 2.7.0
- Installation type: Snap

- [x] I have tested with the latest version
I did try with 2.14, but I cannot install it via snap because of this error 
`error: cannot find signatures with metadata for snap "rocketchat_2.14.3_amd64.snap`
Will try deb packages. **tried deb packages, 2.14.3 works**
- [X] I can simulate the issue easily

## Description
I installed snap to Xubuntu 14.04. Installed Rocket.Chat Desktop via snap. Tried to run it from GUI. Nothing comes up. Decide to run it in terminal. I get the error
`A JavaScript error occurred in the main process`
`Uncaught Exception:`
`Error: /run/user/1000/snap.rocketchat-desktop/.org.chromium.Chromium.mZXesk: failed to map segment from shared object`
    `at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)`
    `at Object.Module._extensions..node (module.js:598:18)`
    `at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)`
    `at Module.load (module.js:488:32)`
    `at tryModuleLoad (module.js:447:12)`
    `at Function.Module._load (module.js:439:3)`
    `at Module.require (module.js:498:17)`
    `at require (internal/module.js:20:19)`
    `at bindings (/snap/rocketchat-desktop/4/resources/app.asar/node_modules/bindings/bindings.js:76:44)`
    `at Object.<anonymous> (/snap/rocketchat-desktop/4/resources/app.asar/node_modules/@paulcbetts/system-idle-time/addon.js:1:192)`

`$ snap version`
`snap    2.35.5`
`snapd   2.35.5`
`series  16`
`ubuntu  14.04`
`kernel  4.4.0-138-generic`

### Current Behavior
 I get the error
`A JavaScript error occurred in the main process`
`Uncaught Exception:`
`Error: /run/user/1000/snap.rocketchat-desktop/.org.chromium.Chromium.mZXesk: failed to map segment from shared object`
    `at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)`
    `at Object.Module._extensions..node (module.js:598:18)`
    `at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)`
    `at Module.load (module.js:488:32)`
    `at tryModuleLoad (module.js:447:12)`
    `at Function.Module._load (module.js:439:3)`
    `at Module.require (module.js:498:17)`
    `at require (internal/module.js:20:19)`
    `at bindings (/snap/rocketchat-desktop/4/resources/app.asar/node_modules/bindings/bindings.js:76:44)`
    `at Object.<anonymous> (/snap/rocketchat-desktop/4/resources/app.asar/node_modules/@paulcbetts/system-idle-time/addon.js:1:192)`
    `at Object.<anonymous> (/snap/rocketchat-desktop/4/resources/app.asar/node_modules/@paulcbetts/system-idle-time/addon.js:1:192)`

### Expected Behavior
I am assuming I would get to use Rocket.Chat Desktop for Ubuntu.

**Comment by tassoevan** [comment]
> I did try with 2.14, but I cannot install it via snap because of this error
> `error: cannot find signatures with metadata for snap "rocketchat_2.14.3_amd64.snap`

I think you forgot the `--dangerous` flag required to install snap files outside snapcraft.io:

```
$ sudo snap install --dangerous rocketchat_2.14.4_amd64.snap
```
