### ISSUE TITLE
running "yarn install" error

### ISSUE THREAD

**Issue by JohnLau** [RocketChat/Rocket.Chat.Electron#994]
## My Setup

I'd like to build the desktop code, just clone and start the app by following steps :

```
git clone https://github.com/RocketChat/Rocket.Chat.Electron.git
cd Rocket.Chat.Electron
yarn
yarn start
```

## Description

The third step is failed, the error message is 

```
Yarn version: 
  1.12.3

Node version: 
  10.13.0

Platform: 
  darwin x64

Trace: 
  Invariant Violation: There should only be one folder in a package cache (got )
      at invariant (/usr/local/lib/node_modules/yarn/lib/cli.js:2308:15)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:59337:11
      at Generator.next (<anonymous>)
      at step (/usr/local/lib/node_modules/yarn/lib/cli.js:304:30)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:315:13

```

Dose anyone know what's wrong and how to fix this?

**Comment by tassoevan** [comment]
Are you behind a proxy? It seems to be failing to download the binary at https://github.com/electron/electron/releases/download/v2.0.10/electron-v2.0.10-darwin-x64.zip.

**Comment by JohnLau** [comment]
> Are you behind a proxy? It seems to be failing to download the binary at https://github.com/electron/electron/releases/download/v2.0.10/electron-v2.0.10-darwin-x64.zip.

I hit another issue below, do any know what's the matter?
'''
Yarn version: 
  1.12.3

Node version: 
  10.13.0

Platform: 
  darwin x64

Trace: 
  Invariant Violation: There should only be one folder in a package cache (got )
      at invariant (/usr/local/lib/node_modules/yarn/lib/cli.js:2308:15)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:59337:11
      at Generator.next (<anonymous>)
      at step (/usr/local/lib/node_modules/yarn/lib/cli.js:304:30)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:315:13
'''

**Comment by JohnLau** [comment]
Got it! It was a network issue.
