### ISSUE TITLE
Windows 10 App icon not flashing

### ISSUE THREAD

**Issue by MLefebvreICO** [RocketChat/Rocket.Chat.Electron#996]
## My Setup
- Operating System: Windows 10 Professional
- App Version: 2.14.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
On my computer, the taskbar app's icon does not blink on new message. Doesn't seem to happen on other computers at my job, so I'm trying to figure it out, but  don't know where to start.

If I can bring more detail to help figure this out, please let me know.

### Current Behavior
The app icon in the taskbar does not blink on new messages.

### Expected Behavior
The app icon in the taskbar does blink on new messages.

**Comment by MLefebvreICO** [comment]
Well, seems like it was already fixed. 

Just switched to `2.14.3` manually (since rocket was looping to find an update ...) and it seems to work properly.

Sorry for not checking earlier, but didn't notice there was newer versions since the auto-update seemed to have died on me.

**Comment by tassoevan** [comment]
Oh, actually autoupdate for 2.14.2 and 2.14.3 was disabled by me due to #977, #979, and #991.

**Comment by MLefebvreICO** [comment]
> Oh, actually autoupdate for 2.14.2 and 2.14.3 was disabled by me due to #977, #979, and #991.

@tassoevan  None of the issue mentionned have happened to me since I manually updated, but good to know .. Thanks for the follow-up ! 😄
